@node
@author=Libanius
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Richard Foerster
@filename=tlg2200.tlg00528.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane
@publicationStmt=University of Leipzig, tlg2200.tlg00528.opp-grc1.xml.
@respStmt=Gregory R. Crane, Editor-in-Chief, Perseus Digital Library, Digital Divide Data, Corrected and encoded the text, Matt Munson, Project Manager (University of Leipzig), Annette Geßner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor, Greta Franzini, Project Manager (University of Leipzig), 2013-2014, Frederik Baumgardt, Technical Manager (University of Leipzig), 2013-2015, Simona Stoyanova, Project Manager (University of Leipzig), 2015, Project Assistant (University of Leipzig), 2013-2014
@sourceDesc=Richardus Foerster, Richard Foerster, Libanius, Declamationes XIII-XXXX, B.G. Teubner, Leipzig, 1911, 6, Internet Archive.
@sponsor=University of Leipzig
@title=Declamatio 28
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:58:05Z

2124	footnote 5 Et. M. p. 186, 14 βαλβὶς ἡ ἀφετηρία καὶ ὁ καμπτός; p. 609, 29  νύσσα ὁ καμπτός. 1 βουλόμενος — 8 προσαγγέλλει] καὶ ἀποτυχὼν ἀξιοῖ ἀποθα- νεῖν Va 2 τῶν reposui e CrHVPClLa τὸν Vi Mor 1  DB Mor 2 sed ex „alio Cod. mnsc. Reg." inserendum coni Notat.  ad Lib. f. IIIIV, Re | ἱπποδρομίου D Mor sed ἱπποδρόμου ex  alio Cod. mnsc. Beg. scribendum coni Not 1. 1. cf. p. 578, 8  6 καὶ(2) om ClLaVi 9 ἃ V sed ὃ adscrips m 2 | ἡμᾶς Cl  10 δυστυχῶ La sed χῶ in ras s | φωνὴ La sed in corr n
marginal R IV 151
footnote 7 Alciphr. ep. III 6. Plaut. Stich. 639. cf. t, IV 118, 12  13 Xen. apol. 1 | cf. p. 584, 3. Luc. paras. 1 sq. Giese de parasiti  persona p. 24 14 Her. VII 46, 3 3 οὖν om BLaViVa 4 τὸν om Va 5 καταλύσαι CrHV  DBClLaVa edd | ἔτι scripsi ex HBLaVi Mon 96 cum Iacobsio  Misc Philostr im. 649 feiPFaMor ἐστι CrV Re ὅτι Cl  7 προεπειχθῆναι Ρ sed προαπαγχθῆναι in marg m 2 cf. p. 585, 9 8 οἴας La sed ἁ in ras s οἵης Vi | διαίτης αὐτοὶ Va 9 δ’  ἐμοὶ scripsi δέ μοι libri edd 10 πρώτῳ scripsi e CrHVPB  LaViVa πρῶτα Cl sed in πρώτω corr m 2, edd πρῶτον D | τὰ  τοιαῦτα] ταῦτα Β 11 ἂν ante ἦν Mor del Re 12 τοῖς —  15 ἐκφροντίζωσι praemissis verbis τῆς μελέτης ἐν ᾖ παράσιτος  ἄδειπνος μείνας ἑαυτὸν προσαγγέλλει citat Macarius παράσιτος  phalus fol. 85 | τὴν αὐτὴν — 13 τέχνην] παρασίτοις Macar | τὴν  αὐτὴν scripsi e D cum Gasda ταὐτὴν La sed e ταύτην corr s,  Cl ταύτην CrHVPBViVa edd 13 τὴν om D 14 ὅταν —  15 δειπνίζοντες praemissis verbis δειπνίζω ἕτερον. Λιβάνιος citat  Andr. Lopadiota lex. Vindob. p. 52, 14 ed. Nauck | ὅτ’ ἂν Cl |  οἱ δειπνίζοντες μὲν ἐπιλείπωσιν ἐπιλείπωσι Vi ἐπιλίπωσιν Va)  LaViVa | ἐπιλίπωσι scripsi e CrHVD sed in hoc ἐπιλἰ in ras, Β  ὢ Macar ἐπιλίπωσιν Va ἐπιλείπωσι Vi edd ἐπιλείπωσιν La  ἐπιλείπουσι Ρ sed οὐ in ras m 2 15 αὐτοὶ post ἀναγκαίαν Macar | ἐκφροντίσωσι BClLaVa Mor ἐκφορτίσωσι Vi sed ρον  supra ορ m 2 ἐκφροντ(??)ωσιν Macar
footnote 1 Arist. nub. 695. 697 5 Xen. anab. II 2, 13 16 cf.  t. IV 452, 4 2 ἕτοιμον om D 3 ἀνθότου Ρ | ἔστιν supplere quam  οὐκ οἷδ’ ante ἀνθ’ ὅτου inserere malim 4 αἱρετόν PD sed  in hoc ετό in ras 5 τὸ inser ἁ· ἴ’ περὶ LaViCl sed in hoc in  παρὰ corr m 2 | ἀφθονέστερον scripsi e CrHVBLaViVa ἀφθο- νώτερον Cl ἀφθονέστατον PD edd 6 εἰπεῖν post ὅπως PD  Mor del Re 8 γὰρ om Mor 9 ὅλως Mor sed γρ ὅλον in  marg Mor 2 11 διαμαρτὼν δὲ PD 12 ἐπικουφίσαι ἑτέρωθεν  Ρ Mor 14 τοσοῦτο D | „malim ὂν“ Re | χαλεπώτερον συμβέβη- κεν scripsi e CrHVBLa Vi Va συμβέβηκε χαλεπώτερον PD edd 15 ὅσω LaVi | μὴ δὲ HPBLaVi οὐδὲ ἁ | ἔσται ἁ  16 καταμέμψεσθαι Cl 17 καὶ ante οὐκ inserendum coni Gasda  | οἶδα δ’ scripsi e BLaVi oldcc Cl οἷδ’ CrHVPDVa edd | ὅ  τι scripsi cum Laur ὅτι reliqui libri edd | ὀδύρωμαι scripsi e  CrHClVa cum Gasda ὀδύρομαι VPDBLaVi edd
marginal R IV 152
footnote 10 cf. ad t. IV 151, 11 16 cf. t. V 540, 16 17 Aristophont.  ἰατρ. III 357, 1 M (II 277, 4 K). Amph. III 318, 38 M (II 248,39 K) 1 δ’ LaViVa | δίδωμι Vi sed σι supra μι m 2 | ὀδύρασθαι  BClLa Vi Va 2 μοι inserui e CrHVBCW Vi om PLa Va edd  | πρότερον Vi sed ρ(1) del 5 ὁδεύων Ρ Mor | τὴν non ante  περὶ sed ante συμβᾶσαν LaViVa 7 καὶ(2) Μορ om libri  8 οὐδ’ om Ρ | ὀδύρεσθαι HVPD | μοι post ὀδύρασθαι Β  9 δ’ om D 10 ἄνωθεν εἰπεῖν reposui e libris εἰπεῖν ἄνωθεν  edd | τοῖς — 11 ἐξαγγέλλειν citat Macarius fol. 85 | ἀσθενοῦσι  BCl sed in hoc σθεν in ras 2 litt m 4 11 ἑτέρους Va sed  ους ex οις corr m 2 12 τίς Cr 13 ὡς om Va ἐς D | συμ- βαλεῖν DVa sed in hoc in συμβάλλειν corr m 1 et γρ συμβάλλειν  in marg m 2 15 ἐκ παιδὸς non ante τὸ sed ante ἤμην BCl 16 τἀς ante τραπέζας D | ποιουμένοις HV | ἤμην in ἦ μὴν  mutandum censuit Iacobs Misc, delendumAch Τ 728 ἤμην in ras  Va 2 ἥμην Ρ 17 καὶ ante οὐδὲν Va et ex ‘alio Regio Codice’  Mor Not | οὐδ’ ἔτι D sed οὐδὲν καὶ νῦν suprascr m 2, Β  οὐδὲ τι corr Cl οὐδὲ νῦν ἔτι παύομαι (neque adhuc nunc  memoriae imprimere) coni Re | παυόμενος scripsi παύομαι libri edd ἐπαυόμην Iacobs Ach | ὁμιλῶν post παύομαι Va et ex  ‘alio Regio Codice’ Mor Not | ὅτι ante τοῖς inserendum  lacobs | ἐπὶ scripsi coll p. 577, 10 et Luc. paras. 13 περὶ libri  edd πρὸς Iacobs | τὰ ante δεῖπνα Cl
footnote 11 Amm. Marc. XXIII 6,30 1 πρώτως BLa sed in hoc ως ex οις corr w, Vi πρῶτος  D | ἁπαντηκώς Mor 1 ἀπαντηκὼς Mor 2 sed ex ‘alio Regio Codice’  ἀπαντηκόσι Not | ὅ τε scripsi ut coni Re ὅτε libri edd | ὁ ante  νοῦς inser D 2 τρόπος ViVa sed in hoc γρ τόπος in marg  m 2 | εὐτρεπής scripsi e PD sed in hoc τ in ras, ClVa ut coni  ex ‘alio Regio Codice’ Codicey Mor Not et Re εὐ(??)πὴς Β  CrHVLaVi edd | δὲ Va edd 4 με post πτερωτὸν BCl om V  LaViVa | μὴ inser Ρ 5 ἵν᾿ reposui e libris ἵνα edd |  εὐωχίας in ταῖς εὐωχίαις corr Las | εὐμερῶς Re 6 πρὸς in- serui om libri edd sed εἰς vel πρὸς inserendum coni Gasda |  ἑτέραν La sed α in ras f | δ’ La sed δ in ras f δὲ PDVi |  ἐτράπην Vi sed ἐτραπόμην in marg m 2 7 δὲ PD edd  8 τοὖργον scripsi e CrHVClLaViVa τοὔργον Β τὸ ἔργον PD  edd | ἐπισφαλὴς Β | δὴ ante διὰ Β 9 γε om Va 11 ὁπόταν  περιττ cum lac 2 vel 3 litt Ρ | ἐφ’ ἵππου — 13 κεκληκότα citat  Planudes fol. 105 v, παράσιτος in marg 12 εὐτρεπῶς Μου sed  e Begio εὐπρεπῶς Not 13 τε inserui e DClLaViVa, ut e  Begio inserendum coni Mor Not om CrHVPB edd | ἡγησά- μενον Ρ Mor sed ἡγησάμην e Begio Not | προθήσειν Va
marginal R IV 153
footnote 8 cf. p. 581, 11 18 Heliod. Aeth. VI 2 1 προστυγχάνουσιν BClLaVi sed in hoc ἐντυγχάνουσιν in  marg m 2, Va | ἔσεσθαι La sed αι ex ε corr s 2 ὁ inserui e  CrHVPLaViVa om DBCl καὶ edd | δ᾿ inserui e CrHVPDB  ClViVa ut e Regio inserendum coni Mor Not om La edd | οὗτος  Ρ | δὴ La sed ὴ in sl corr n et s, Vi 4 τῶν(2) om Cl | πλου- σίων coni Gasda 5 οὐκ Vi sed τούς in marg m 2 6 ἐμοὶ  Mor sed e Regio ἐμοῦ Not 8 τὴν τοιαύτην ἀγωνίαν coni  Gasda 9 εὐθὺ scripsi cum Gasda εὐθύς libri edd | τοῦ  λουτροῦ D sed in τῶν λουτρῶν corr m 2 | ὠχούμην scripsi cum  Gasda ᾠχόμην PDCl et e Regio coni Mor Not εἰχόμην CrH  VBLaViVa edd 10 ὡς om Mor | τε τῷ Cl | τε om Β  12 δὲ PD 14 voce αἰτήσας des D | ἔχεσθαι Cl 16 τῆς om  LaViVa | αὐτῶ ante πάρεργα LaVi 17 γινόμενα HPBLaVi  Va edd | δ’ post ἐπέβην Cl 18 ποῖ δὲ scripsi e BClLaVi  icf) δὲ Va ποῦ δὲ Ρ edd τῆ δὲ Cr sed τῆ parum certum, V (et  Pal. gr. 213) τῇδε Η vpraefero aut πῇ aut ποῖ“ Re
footnote 4 Xen. Cyr. IV 3, 17. Luc. fug. 10 8 Her. I 163, 2 cum  nota Kruegeri 9 cf. p. 607,13 et 603,3. [Isocr.] Demon.  § 26 p. 7 d 2 πρὸ Cl sed in πρότερα corr m 4 | ὁ σκοπὸς κατὰ γνώμην Va  δρόμος vel στόλος coni Gasda num ἵππος? cf. ad p. 586,8  4 μέν με scripsi μὲν libri edd με Re 5 τὸν om Va | βελερο- φόντην Πω 6 πλείστους Ρ 8 δ’ La sed in ras f δὲ VVa  edd | ἀποκρινόμενος Mor | οὑτωσὶ P | δή τι scripsi coll Her.  ll. ll. τι VLaVi edd τί CrHCl τοι Β Pal 213 et Par 3017  (Boissonad. Eunap. H 557) om PVa | τὸ om Mor 9 γὰρ om Β  | παρομαρτεῖ — 10 φθόνος praemissa voce ἐπεὶ citat auctor ex- cerptorum codicis Neapolitani II C 32 fol. 285 12 ἐμαυτὸν  scripsi ex HVPBClLaViVa ἑαυτὸν Cr edd sed γρ ἐμαυτὸν in  marg Mor2 13 πέπονθα reposui e libris πέπονθεν edd | γὰρ  inserui ex HVPBClLaVi om CrVa edd | πρὸς Va 14 οἰκίας  scripsi e CrHVPBClLaVi hxlagVa edd sed γρ οἰκίας in marg  Mor 2 | βωμός] βωμὸς Ἑστίας. coni Mor Not | λέγω; scripsi e Cr  HPBClLaVi cum Cobeto Coll 281 λόγῳ VVa edd sed γρ λέγω;  in marg Mor 2 | μὲν inserui e LaViVa cum Cobeto coll p. 578,15;  t. I 249, 14 om CrHVPBCl edd | οὖν om BCl 15 ὡς —  580, 1 ἐπεβεβήκειν citat Planudes fol. 105 v
marginal R IV 154
footnote 1 cf. t. I 137, 5; II 32, 16 3 Xen. cyn. 10, 1 7 Od. ξ  475. Hes. op. 547 10 Arist. vesp. 875 c. schol. 1 μόνον οὐ Vi 2 κνίσης La | αἰσθανόμενος scripsi  αἰσθόμενος libri edd | μικρόν — 3 ἡμᾶς ornissa particula γὰρ  citat Macarius fol. 85 r | τι om Va 3 κριτικῶν La Κρητῶν  Mor | αἳ HLa | ῥινηλατοῦσαι La sed αι in ras s ῥινηλατοῦσι  Vi | ἡμᾶς] τὸ παρασίτων γένος Macar 4 τῶν inserui e Va  om reliqui libri edd 5 καὶ ante τὴν Va 7 προσδοκῶν  scripsi δοκῶν BClLa sed in hoc et κ in ras s, Va δόξων Cr  Η δόξαν V δόξας Ρ edd δοξάζων Vi sed δοκῶν in marg m 2  | πεσούσης scripsi e CrHVBClLaViVa προσπεσούσης P edd  8 πτήξαντος La sed τ in λ corr n, Va | ὥσπερ La sed ὶ inser s  ὡς περὶ CrHVCl Re ὡς πρὸς Β | περὶ delendum censet Cobe- tus Coll 282 παρὰ CrHVLa 9 ἐνεχθεὶς — 10 βωμὸν in marg  Cl | μὲν om Va | παρεθρύφθην Β 10 περὶ Vi sed παρὰ in  marg m 2 | ὁ ἵππος post βωμὸν inser Cl 4 11 δὲ La sed δ’ in  ras s γε CrHVBVi om Va 12 ἡ scripsi ex HVVa cum  Iacobsio Misc ᾖ CrB Re ἢ PClLa sed in hoc in corr n,  Vi Mor 16 ἐνεδεικνύμην BClLaVi ἀνεδεικνύμην Va | καὶ  ante ἐφερόμην Cl
footnote 4 Eur. Or. 2. Soph. Oed. R 255. Thom. M. s. v. p. 178, 3 R 11 cf. p. 578, 8 15 Aelian. fr. apud Suidam s. v. ἀωρία  cf. p. 538, 5 1 ἐπὶ cancellandum ? Ι οὖν om CrHVPCl 2 τοῖς(2)] τὴν Va  | πε ρὶ Ρ I αὐλείου Vi sed οὑς suprascr m2 ἀμφίους V 3 οὐδὲ  εἰπεῖν ἔχω om Va Ι δ’ inserui e ClLaVi om CrHVPBVa edd 4 ἐκὶ om Va | γὰρ τί Cl | γινόμενον CrBClLaVi edd γενό- μενον Va 5 ἵππον post βοῶν edd delevi 7 ὀλεθρίαν Vi  sed ὀλέθριον suprascr m2 8 κρείττων Vi κρείττονος Va  10 συνήθης Ρ | τοῦτο HVVa et Iacobs Misc 11 τὰς Cl sed  ὰς ex ῆς corr m4 | ἁμίλλας HClLa | τοὺς δρόμους Vi sed τοῖς  δρόμοις in marg m2 | ἀσκουμένοις Mor sed γρ ἠσκημένοις in  marg Mor2 12 voce θε[ατῶν] des Cr fol. 25r reliqua perierunt  | τῶν θεατῶν om V 13 εἰς τάχος ἑαυτούς reposui e libris  ἑαυτοὺς εἰς τάχος edd 14 με om Vi | ὧς scripsi ex ΗΒΟἰLa  ViVa ὥστε VP edd cf. Herm. Χ 10 15 σκότους cancellavi  ut e glossa σκότος ortum σκότος ἀωρία La sed ἀργὸν supra  σκότος ’ν, Vi sed σκότους ἀωρίαν in marg m2 σκοτοδινίαν coni  Cobetus Coll 282 at cf. Suid. et Herwerdeni lex. graec. supplet.  s. v. Ι καὶ om libri et delendum censet Re „Hic Graeca mendi  et lacunae suspecta suntu Mor j μηδὲν ἀναστείλαντα scripsi  μὴ δὲ (μηδὲ VCl) ἐνστείλαντα HVPBClLaVi μηδὲ ἐνδιαστείλᾶντα Va edd sed μηδὲν συστείλαντα coni Re | με ante τὴν  libri edd delevi auctore Re
marginal R IV 155
footnote 1 cf. Meier-Schoemann-Lipsius, Att. Proc. p. 965 8 sq.  Lotophagi cum Ciconibus (Od. ι 45 sq.) confusi, ut Circes domus  (Od. κ 210 et 287) cum Calypsonis (Od. α 15) antro cf. p. 565  not. 2 13 Od. κ 234 sq. 14 Od. κ 98 | Od. ι 116 sq. et 182 11 μυθεύουσιν] εἰς συῶν μεταβάλλεις (corr μετέβαλλε?) μορ- φὰς τοὺς ἐκεῖσε καταγομένους in marg Lay 1 καὶ ante ὥσπερ inserendum coni Re | ὥστε Β | ὑπερή- μερόν Vi sed τρόν supra ρόν m 2 | με om Va | τὴν La sed in τῶν  corr n 3 κενῆς Mor sed „leg. καινῆς καὶ κενὴν in marg vers.  lat. p. 21 5 ὑστερίζων HVP 6 ὢ libri sed ex ὦ corr Laf,  edd | πολυθρήνητε scripsi e Β πολύθρηνε reliqui libri edd  7 πολυτίμητον scripsi ex HVBClLaViVa πολύτιμον Ρ edd |  ὦ Ρ ὢ reliqui libri edd 8 ὦ ClVi Vi ὢ reliqui libri edd | τοὺς  Λωτοφάγους — 10 ἀπώλλυον citat Planudes fol. 105 v 9 οἱ om  Ρ | ῥαψῳδοῦσιν Ρ 10 ἀπώλλυον La sed ο inser n | εὐτυχής  HV 12 μετέβαλλεν scripsi e LaViVa μετέβαλεν HV edd  μετέβαλλον PBCl sed in hoc ο in ε corr 16 τοιγὰρ οὗν La |  ἐξανθρώπων Cl | íxqhsvmai La
footnote 1 Plat. Lach. p. 195 E; Phaedr. p. 261 A 1 ἑτέροις Va | γὰρ om PCl Mor | ἀποβολὴ χρημάτων BCl  LaViVa 2 δὲ post ἑτέρῳ inserendum coni Gasda | ἑτέροις  Va 4 μηδὲ scripsi e K cum Iacobsio Misc μὴ δὲ HPBCl  Vi μηδὲν LaVa edd | τηναρχὴν Β | ἀρχήν τι P | τι scripsi  cum Iacobsio τί HBCl om VLaViVa edd | σπουδάζεταί τι  La sed supra ι et τι f, Vi 5 δὲ inserui e σπουδάζεταί  om HVLa edd sed „malim δὲ interponi“ Re 6 ἐστιν  ex HBClLaViVa om VP edd 7 φησὶ HVLaVi φασὶ Va  1 τίς Η 8 ἑστίασις — κεκληκότος om HVPClLa sed in hoc  in marg ὁ κεκληκὸς f, ViVa 9 κεναὶ coni Cobetus Coll 282 10 (??)σιζάνουσιν Β | ἐπεῖδ’ ἂν La 11 τίς HPBClLaVi  Mor | ἐκλείπῃ HVP sed in hoc ι supra ει, LaVi 12 πηλίκον  scripsi ex HVBCl πηλίκα PLaViVa edd 13 προβάλλωνται  PLaViVa sed in hoc ω ex ο corr ms προβάλλονται Η sed in  προβάλωνται corr Mor 14 καὶ om Mor 16 ὑποψίας Μορ 1  1 ὀμόσωσι VClVi 17 προεστῶτες HVCl sed in hoc σ supra ο  inser, LaViVa Μορ 1 et γρ in marg Mor 2
marginal R IV 156
footnote 8 cf. t. V 554, 15 13 cf. p. 574, 13 1 οἰόμενοι] „hic interpres necessario paraphrasten et con- iectorem egit, cum non liqueret in Graecis hic mutilis et laceris“  Mor vers. lat. p. 23 | γὰρ om HVBClLaViVa | αὐτὸν scripsi  ex HVPBGlLaVi cum Mor 1 αὐτοῖς Va edd sed γρ αὐτὸν in  marg Mor 2 | ὥσπερ Ρ Mor 2 Re om HVBClLaViVa Mor 1  2 ἠδικημένον HVPBClLaVi ἠδικημένῳ Va sed ω in ras m 2 |  καὶ ante μὴ δὲ HVBClLaViVa 3 ὅσῳ] „bene si locus hic  habet, videtur haec eius esse sententia: τοσούτῳ ἧττον, ὅσῳ καὶ  μᾶλλον τεχνίτην” Re cf. 1. 8; p. 581, 9; 585, 11 num ὃν vel ὅτι? 4 αἰτιάσαιτ’ ἂν scripsi αἰτιάσαιτο HVPBClLaVa sed in  hoc τὸ inser m 2, Mor 1 αἰτιᾶσαι Vi αἰτιάσαιτ’ ἄν τις τὸ Mor 2  Re 5 δέ; post ἀσχολίαν Mor sed e codice Begio delendum  censuit Not delevit Re | ἤδη Va | πάντα reposui e libris πάν- τως edd sed γρ πᾶς τις in marg Mor 2 | με Va sed οι supra ε m 2  μοι PLaVi 6 μὴ δὲ HPBClVi 7 γυναῖκας HLaVa |  ἐκβιάσαιτο Va sed το eras | ἑαυτὸν HVLa sed in hoc ὸν in οὑς  corr s, Vi | ἤδη Ρ 8 μόλις ἀρκοῦντα] vvidetur ἐμαυτῷ inter- ponendum sc. πρὸς τὴν τροφήν. vel πρὸς τὴν τῶν ἐπιτηδείων χορη- γίαν” Re | „fort. προφανεστέρα” Re at cf. ad l. 3 10 τρυφῆς  La sed υ in ras s τροφῆς Β Vi | ὅτι om Va ὡς Iacobs Misc |  vmalim legi ἀρκῶν ἔτι, καὶ τάχει” Re 11 νικῶν post ἅπαντας  Β et in marg inser Vi 2 | ἐν ταῖς περὶ δεῖπνα ἁμίλλαις scripsi  ἐν ταῖς περὶ τὰ δεῖπνα ἁμίλλαις Va ἐν τε περὶ δεῖπνα τούτους  τοὺς ἐν Ρ) ταῖς ἁμίλλαις HVPLa sed in hoc τε in τοῖς corr s et  τούτους in τῶν ἐν corr n, Vi sed τῶ post τε in marg inser et τῶν  pro τούτους ἔν τε τῶ περὶ δεῖπνα δρόμω Β ἐν ταῖς (sed αῖς in ras m 2) περὶ δεῖπνα (sed α in ras m 2) ταύταις ἁμίλλαις Cl ἐν  (ἔν τε Iacobs) τοῖς περὶ δεῖπνα τοὺς ἐν ταῖς ἁμίλλαις edd Iacobs
marginal R IV 157
footnote 14 cf. t. ΙΙΙ 449, 3 1 γ’ οὖν Η 2 ὧν Ρ Mor 1 | πονήρως BCl sed in hoc et  ως in ras m 2, Vi 3 ἤδη Cl sed in ἔδει corr m 2 4 γοῦν scripsi  e Va οὖν HVPBClLaVi edd | τἀς Mor sed γρ τῆς in marg Mor 2 5 ὑμᾶς PVa sed in hoc υ in η corr m 2 | δὲ scripsi e BClVa  δεῖ Η δὴ VPLaVi edd sed δὲ δὴ coni Re 6 καὶ τύχην scripsi  καίτοι ἂν PBClVa καίτοι ὃν LaVi sed in hoc ἂν in marg m 2  τοῖον HV Mor 1 καὶ πῶς ἂν Mor 2 sed γρ καίτοι ἂν in marg, Re  ποτ’ vel ὀψέ ποτε Iacobs Misc | ἐσπέραν Vi sed ἑτέραν in marg  m 2 ἑτέραν Β | ἐπαγγελεῖ scripsi cum Iacobsio ἐπαγγέλλει HVLa  sed in hoc η supra ει s, Vi sed ἐπαγγείλῃ suprascr m 2, Va ἐπαγ- γέλλοι Ρ ἐπαγγέλλῃ Cl ἐπαγγείλῃ Β ἐπαγγέλλοιτο edd sed ἐπαγ- γέλλοι coni Re 7 τὴν ante κλῆσιν Ρ Mor 2 Re | κλῆσιν La sed  καλεῖν suprascr n καλεῖν Vi sed κλῆσιν suprascr m 2 τῷ ante οὕτω  Va et γρ in marg Mor 2 | οὕτω σφοδρὸν vel δεινὸν λιμὸν vel δεινὸν  οὕτω coni Re ἐν τούτω οὕτω δεινὸν λιμὸν ὑποστάντι Iacobs  8 ὑποστῆναι ClLaVi sed in hoc ὑποστάντι suprascr m 2, Va Mor  sed γρ ὑποστάντι in marg Mor 2 „Hic utique divinandum nobis  fait, Gr. deploratis“ Mor 1 vers. lat. p. 23 | πῶς —  ματος in marg Cl 2 9 ἀπαλλαχθήσομαι scripsi collp. 574,7 ἂν  (om Va) ἀπαχθήσομαι HVPBClLaVi edd 10 δὲ post ἤδη Β  ClLa Vi Va 11 ὥστε Β 13 ὤφειλεν HVBCl | ἵππων BClLa Vi
marginal R IV 158
footnote 2 Soph. O. C. 714 | Eur. Hippol. 1223 sq. 6 sq. Philostr.  Her. 20 t. II p. 218,8 sq. K. 8 cf. t. IV 994, 6 R. [Apollod.] bibl.  II 5, 8. Hyg. fab. 30. Diod. IV 15 1 τοῖς ante ἀνθρώποις Cl | οἴα VVi 2 με ante ἀφείλετο  Va 6 ἀλλ’ — 7 ἠλέγχθησαν om Ρ Mor 6 ἀλλ’ ἀρθεῖσαι]  ἀναρθεῖσαι Iacobs 8 τἀς — 10 σώμασι praemissis verbis σι- τίζω ἕτερον, σιτοῦμαι δὲ ἐγώ Λιβάνιος citat Andr. Lopadiota  lex. Vindob. s. v. p. 170, 7 ed. Nauck | Αἰτωλικὰς τἀς inserui  ex HVBClLaViVa om Ρ Lopad edd sed γρ in marg Mor 2 |  ἵππους scripsi ἐκτὸς HVPLa sed in hoc in ἵππους corr s, Vi  edd et γρ in marg Mor 2 om BCl sed in hoc lac 5 litt, Va Lo- pad τοῦ Θρακὸς coni Re at cf. p. 565 not. 2 τἀς δὲ Διομήδους  ἄνακτος Iacobs | οὐκ om Ρ et γρ in marg Mor 9 ἀνθρωπί- νοις Va sed in ἀνθρώπων corr m 2 ἀνθρώπων Lopad ἀνθρω- πίνης Ρ et γρ in marg Mor ἀνθρώποις LaVi 10 δὲ inserui  e libris om edd 11 ἰλίου Vi sed ἰ in ras ἡλίου La | πορίσας  scripsi auctore Meisero Ber. d. Bayr. Akad. d. Wiss. 1905 II 158  πορθήσας HVLaViVa edd sed „συσκευάσας vel tale quid; num  ποιήσας?” Re ποιήσας Β sed πορθήσας suprascr, Cl 12 μὲν  οὖν] „sententia potius postulat γἂρ” Re | Τροίας scripsi e V coll  t. V 386,12; 393,5 τροίαν reliqui libri edd | ὁλωλότων Cl ἑαλω- κότων Β 14 ἦν· ἀναίσθητος Va | ἄσιτον, ἄποτον om Ρ Μορ 1
footnote 3 Od. μ 342. Plat. rep. III p. 390 B cf. t. IV 226, 24 R  4 Arist. Plut. 45 12 cf. p. 594, 9 2 πεποίηνται Η | τῶ La sed co in ὁ corr n, Va | γὰρ post  τὸ edd delevi δὲ coni Cobetus Coll 282 3 λοιμῷ Mor  θανεῖν HVClLaViVa ἀποθανεῖν Β 4 τὴν om Cl | „malim  ἐπίπνοιαν. ipsa veritas videtur tibi hanc sententiam in os in- didisse" Re at cf. Arist. l. l. 5 ταυτὶ] ταὐτὸ Va om Ρ et γρ  in marg Mor 2 | τάδε post πεποιηκέναι Ρ et γρ in marg Mor 2 |  δαιμονίως scripsi auctore Cobeto Coll 282 εὐδαιμόνως libri edd 7 ἀντῶ Va sed ν in ras m 2 | ὦ ante ἄνδρες BVa | δικασταί  om Cl 8 ἀλλύω HV ἀλλοιῶ PLaVi sed in hoc ἀλγῶ in marg  m 2, Mor ἀλλοιοῦμαι B | ἤδη om LaVi | ἔσθομαι  Cl | ἐπαγ γειν cum ras 1 litt Va ἀγαγεῖν Ρ 9 τὰ Cl sed ἁ  in ras m 2 10 δὴ PCl Mor 11 καὶ scripsi μοι Ρ om reli- qui libri edd | λαβόντα scripsi ex HVBClVi et γρ in marg Mor 2  λαβόντες PLa edd | φαγεῖν scripsi auctore Meisero l. l.  ε  φέρειν libri edcl 12 ἐμοῦ Vi sed ov del m 2 | κηρῦξαι PLa cf.  ad t. III 116,9 14 num scribendum &lt;ὡς&gt; μὴ? 15  ἵππον ἀγέτω τις scripsi τὸν ἵππον ἀγέτω La τὸν ἵππον ἀγα- γέτω τις Va et γρ in marg Μου τὸν ἵππον ἐχέτω Cl τὸν ἵππον ἡκέτω τις Ρ edd τῶν ἵππων ἡκέτω τις HV τίς τῶν ἵππων  ἱκέτω Β τῶν ἵππων ἐχέτω (sed ἡκέτω in marg m 2) τίς Vi |  φέρων post τις Ρ edd delevi | μὴ δὲ HPBClLaVi
