@node
@author=Libanius
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Richard Foerster
@filename=tlg2200.tlg00540.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane
@publicationStmt=University of Leipzig, tlg2200.tlg00540.opp-grc1.xml.
@respStmt=Gregory R. Crane, Editor-in-Chief, Perseus Digital Library, Digital Divide Data, Corrected and encoded the text, Matt Munson, Project Manager (University of Leipzig), Annette Geßner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor, Greta Franzini, Project Manager (University of Leipzig), 2013-2014, Frederik Baumgardt, Technical Manager (University of Leipzig), 2013-2015, Simona Stoyanova, Project Manager (University of Leipzig), 2015, Project Assistant (University of Leipzig), 2013-2014
@sourceDesc=Richardus Foerster, Richard Foerster, Libanius, Declamationes XXXI-LI, B.G. Teubner, Leipzig, 1913, 7, Internet Archive.
@sponsor=University of Leipzig
@title=Declamatio 40
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:57:51Z

8270	marginal RIV 582
footnote L = Codex Laurentianus LVII 27 Pa = Parisinus gr. 3018 Ma = Matritensis 4679, olim N-49 Cl = Berolinensis gr. 195, olim Claromontanus Vi = Vindobonensis philos. et philol. IV 82 Β = Barberinus II 41 nunc Vaticanus Barb. 220 Va = Vaticanus gr. 82 1 Sopat. rhet. gr. VIII 229, 18 sq. ed. Walz. Ach. Τ. VIII 8, 13 1 Ἄλλη μελέτη. Ὑπόθεσις ante Νόμος Mor Re delevi | Νό- μος — 9 κρίνεται inser Va 2 4 ἑτέραν ἐπέδωκεν B Va 2 6 κατέσχεν Ma | ἐπέδωκεν Ma sed ἁ supra ἑ m 2 ἀπέδωκεν Cl 7 μὲν ἐκεῖνος B Va 2 | ἡ δ’ scripsi ἥδ’ LPaMaCl Vi edd ἡ δὲ B Va 2 8 καὶ inserui e MaClVi om LPaBVa edd 9 Ἡ στάσις ἀντέγκλημα post κρίνεται. LPaMa Mor Re delevi cf. ad p. 326, 6 10 ἡ ante προθεωρία MaCl Vi Ferr Ι προθεωρία in marg rubr L
marginal RIV 583
footnote 5 cf. p. 330, 7; 364, 20; t. IV 31 7, 7 11 Plat. leg. V p. 733 D 13 Plat. rep. III p. 409 A 14 Her. III 80, 2. Thuc. III 43,3 3 ἐπιστενάξει scripsi e PaBVa ut coni Re ἐπιστενάζει L MaCl sed in hoc ζ in § corr m 2 Vi edd 6 ἐς MaClVi | κα- κὸν Οἶ’ sed ὸν in οῦ corr m 2 | παρέτρεψε Ma sed γρ in marg m 2 ClVi Ι αὐτοῦ libri edd 7 ἐξεβιάσατο coni Re cf. p. 333, 10; 352, 22 num ἐξεβίβασε? 10 ἀβουλήματα Vi 11 ὑφορμοῦν reposui e PaMaClViBVa coll t. IV 639, 8 sq. R et Thom. M. p. 265, 6 R ἐφορμοῦν L edd 12 ὀλίγον BVa 13 τῶν γυναικῶν Ma sed in τῆς γυναικὸς corr m 2, Vi | εὐεξαπάτητον ὢ sed α(1) in ras m 2 15 σκαιωρίας reposui e libris cum Ferr σκευωρίας Mor Re et Boissonade Pachym p. 210 cf. ῥ’. 336, 17; 334,20; 336,1; 345, 10; 337,1; 349,21; 363, 13; t. IV 805, 17 R σκευωρεἷν p. 339, 1; σκευωρεῖσθαι 362,11; t. IV 802, 35 R 17 ταπρῶτα MaVi 18 βεβιᾶσθαι edd 19 ἀντεισάξει scripsi e BVa ἀντεισάξῃ LPaMaClVi edd cf. p. 319, 15 sq.
marginal RIV 584
footnote 9 Philostr. im. II 31 6 ἡ στάσις ἀντέγκλημα MaClVi Par 3017 ἡ μελέτη ἐξ ὑποδιαιρέσεως Vi 1 καὶ inserui e BVa om LPaMaClVi edd cf. p. 319, 7 sq. 3 ἅπαντες Vi 5 τιθέμενος BVa Par Par (Boissonade Anecd. V 351) 6 Ἡ μελέτη scripsi e LPaBVa sed in hoc in marg inser m 2 cum Ferr μελετῶμεν τὸν πατέρα MaClVi Par 3017 Κρινομένου φόνου ἀπολογία Mor Re 12 με inserui coll p. 328, 18, ut ante μόνον e Par 3017 inserendum coni Boisso- nadius Pachym p. 165 not. 2 om libri edd 13 καὶ(1) inserui e MaClVi Par 3017 om LPaBVa edd 14 ἄλλος Β 16 ἔχη BVa 17 num καταψηφίσησθε? at cf. p. 319, 15 sq. | μὴ δ’ libri Ferr 18 ἂν om BVa
footnote 4 cf. t. VI 460, 17 1 „num leg. νομίσητε παρεστάναι τῷ βήματι, τῷ γε λογι- σμῷ?" Re I καὶ inserui e MaClViBVa om LPa edd 3 δόξετε Β | καὶ inser Ma 2 om ClViBVa | πηλίκη Vi 4 ξυλ- λογιεῖσθαι Vi συλλογιεῖσθε Ma num ξυλλογίσησθε? at vide p. 319, 15 sq. ; Ι τί BVa 5 ἐς MaClVi 9 του τῶν Mor sed γρ τούτων in marg τοῦ τῶν Ferr του delendum censet lacobsius Lect 130 11 τὸν Pa sed ὂν del | μὴ δ’ Pa sed μὴ del, MaClViVa Ferr Mor | ἔσεται coni Mor | βουλευόμενον coni Mor at cf. p. 320, 13 12 δ(2) ὢ Ι δ’ ὁ MaCl Ι βέλτιστός Ma sed ιστο in ras m 3 13 ποιεῖσθαι MaClViB sed in hoc αἰ in ras, Va sed αἰ in ἑ corr m 2 11 ἐν Ma sed ὡς antep m 2, ClViBVa I αὑτὸν αὑτοῦ Re αὐτὸν αὐτοῦ αὐτοῦ Vi) libri edd αὐτὸς αὐτοῦ Bast ep. crit. 212 18 δὲ Οἶ’ sed ἑ in ἡ corr m 3, Vi 19 ἕτερον μὲν ἀτυχεῖν scripsi e MaViBVa ἕτερον μὲν ἀτυχεῖ Οἶ’ ἕτερος μὲν ἀτυχεῖ LPa edd 20 οἰκτείρεσθαι scripsi οἰκτείρεται οἰκτείρετε Vi) libri edd | ἕτερον δὲ κακουρ- γεῖν scripsi e MaClViBVa ἕτερος δὲ κακουργεῖ LPa edd
marginal RIV 585
footnote 1 κολάζεσθαι scripsi κολάζεται κολάζετε Vi) libri edd 4 ἀπονάμενον scripsi e MaClViVa ἀπωνάμενον LPaB edd | οὓς Ma sed ὗς in ras m 3 | ἐπὶ in ras Ma 3 5 πρώην libri edd 6 συνοίχεσθαι Ma 7 ὑμῶν Cl sed ὒ in ras m 3 9 καὶ inserui e MaClViBVa om LPa edd Ι προτέρου scripsi e MaClVi πρώτου BVa πρότερον LPa edd | δεόμενον Macl, sed γρ λειπόμενον in marg Ma 3Cl1, Vi 12 πείθειν coni Re | ἐπεὶ ante ὡς edd delevi ut coni Re et Sintenis 13 οὖν om BVa 14 τούτοιν] τοίνυν Ferr τοίνυν τούτοιν Mor 15 μηδὲν in ras Pa 2 16 αὐτὸν reposui e LMaClViBVa cum lacobsio Lect coll p. 344,22 αὐτὸν Pa edd 17 θεάτρου scripsi auctore Re coll p. 341, 20 θάτερον libri edd 18 με om BVa 19 „μὴ aut delendum aut cum δὴ mutandum" Re cui cutus est lacobsius Lect
marginal RIV 586
footnote 6 cf. ad t. III 89, 1 13 sq. Sopat. 1. 1. p. 229, 26 sq. 4 τὰ δάκρυα om Mor | ἐκκεκόψεται scripsi auctore Re ἐκκό- ψεται libri sed αἰ supra ἑ B, edd cf. p. 319,15 sq. 5 οἰχήσηται Va 8 colon post λογισμόν edd delevi 9 μὴ δ’ LPaMaCl ViVa | ὅτι Vi | καὶ om BVa 11 τίς MaClVi | ἀγενὴς Vi 12 ψηφίζεσθαι Cl sed αἰ in ras m 3, Vi Ferr Mor 13 Ἠγα- ἠγαγόμην — γυναῖκα praemissis verbis ἠγάγετο ὁ ἀνὴρ γυναῖκα Λιβάνιος citat Andr. Lopadiota lex. Vindob. s. v. ἦγ’. p. 99, 3 ed. Nauck 16 καὶ χρηστοὶ in lac 7 fere litt om Β | παιδωες Ma παίδων ClViBVa 17 χρησιμευόντων Vi 19 τοι Vi BVa 20 τόδ’ LPaMaCl | γὰρ om Vi
marginal RIV 587
footnote 3 cf. t. III 449, 3 6 Antiph. tetr. I 2 § 2 p. 116, 29. Lys. de vuln. ’ξ 9 p. 101, 23 7 cf. p. 325, 5 8 Sopat. 1. 1. p. 229, 27 10 Plat. leg. III p. 677 B 2 ἱεροῖς Cobet Misc 166 | τι scripsi e Vi ut coni Re et Boissonadius Anecd. V 157 τοι reliqui libri edd 5 τουλοι- ποῦ LPaMaVa 7 Τελχῖνος Mor Re | τὸ praeferam" ’ Re Ι αὖ MaB 10 μεῖραξ MaClViBVa edd 11 μὲν om Ma Wolf Ferr delRe 12 ἀντήλαμπε Β ἀντέλαμπε Va 15 ὑπὸ MaClVi Par 3017 (Boissonade Pachym. p. 170 not. 4) | ὁπόσα MaBVa 18 μὴ δὲ LPaMaClViVa sed in hoc ’ supra ἡ eras, Ferr | τὴν ἀρχὴν L sed ’ supra η(1) del τηναρχὴν PaB | αὐτὸς om BVa 20 μὴ δὲ LPaMaClVi VaFerr 21 οὐκ post μὲν Β
footnote 2 πᾶν Οἶ’ 4 δὴ MaClVi | σε om Β | παρὰ σαυτῆς scripsi e Β ut coni Re περὶ σαυτῆς PaClViVa sed in hoc in ἁ corr περὶ σαυτὴν LMa edd 6 τὰ περὶ inserui e BVa sed in hoc τὰ inser m 2 καὶ περὶ MaClVi om LPa edd 8 δῶρον scripsi e MaClVi δῶρα LPaBVa edd | νομίσει Cl sed νομί in ras m 2 θαυμάσει in νομίσει corr Va | εἰ lacobs Lect ἣν Mor 10 ἐπιτηδεύῃς Vi 12 μὲν inser Pa 2 μὴ Vi 13 λαμπρὸν scripsi e Ma sed γρ καλὸν suprascr m 2, ClVi κα- λὸν LPaBVa edd | ὑποφανεῖς scripsi ὑποφαίνεις ἀποφαίνεις Ma) libri edd | μὴ δὲ MaClViVa 14 καταρρυπανεῖς scripsi καταρρυπαίνεις libri edd 16 εἰς Vi 17 σοι Pa sed οἱ in ras m 2 20 „malim ἀπελέγξει“ Re „quod reperi in cod. Par. 3017" Boissonade Mich. Psell. de op. daem, p. 213 21 καθε-κάστην LPaClViVa
marginal RIV 588
footnote 8 sq. Sopat. 1. 1. p. 229, 28 19 Soph. Ai. 35 1 πρότερον Β Va 2 προσδόκησιν Ma 4 ἐπεσέμνυναν MaViB 5 ταῖς scripsi e MaClViBVa Par 3017 cum Bois- sonadio Anecd. V 417 τὰς LPa edd | διελοιδορούμην scripsi e MaClVi Par 3017 cum Boissonadio διελοιδόρουν LPaBVa edd 1 ἡ δ’ scripsi ἥδ’ libri edd 8 ἐπίγαμον scripsi e Ma ViBVa Par 3017 (Boissonadius Psell. 192) ut coni Re ἐπὶ γά- μον LPaCl edd 10 κήδους Ma sed γρ κέρδους in marg 11 ἐξηρευνώμην Va sed η(1) ex ἑ corr m 2 Ι τοὺς om BVa 13 ἔοικεν L 15 ἔπεισεν MaVa | ξυνάψαι μοι scripsi e Ma sed ξ supra σ, ClBVa ξυνάψαιμι LPaVi edd συνάψαι με Par 3017 (Boissonade Psell 192) ξυνάψασθαι coni Mor ξυνάψαι με Re 18 συνεορτάσοανντες L 19 εἰς ἔπειτα Vi
marginal RIV 589
footnote 16 Eur. Tro. 514 7 ἀτέλεστα scripsi e MaVi ἀτέλευτα Οἶ’ ἀτελεύτητα LPa BVa edd 9 τόν δ’ Va | σφαγέως reposui e libris σφαγέος edd 10 ἐκβιάσομαι Ma Ι παρ’ οἷς om Vi ,,fort. παρ’ οὓς καὶ μονοῦν Re 11 μόνοις Vi sed νόμοις suprascr Ι ἀμείνους in marg inser Ma | ἐλπίδας ἔτρεφον Ma Ι ἐπίμακρόν Vi 13 ἐσχη- κέναι] ,,neque tempus praeteritum convenit, (futurum melius qua- draret) et deest aliquid, e. c. προσεδόκων Re num ἐσχηκέναι? Ι τἄλλ’ LPa edd 14 γάμους Pa sed μ’ in ras m2 16 ἁψάμενός PaMaClViBVa Ferr Ι ἐπὶ κηδείαν Va 18 ἐντεῦθεν in marg Β | εἴχετο Mor 19 οἰωνοὺς MaVa sed in hoc οἱ in υἷ’ corr | ὀνειρώττομεν Β
footnote 3 Sopat. 1. 1. p. 230, 1 11 cf. p. 349, 14 12 sq. cf. p. 349, 2 2 ἕδνων scripsi e LPa ἕδνων MaClViBVa edd cf. p. 336, 2 I τοὐμὸν Ferr Mor sed in hoc γρ ὁ μὲν in marg 6 ἐφ’ Ferr 10 ὥρμησεν Va 11 καὶ om MaClBVa | λόγους Β sed γ in ras m 2 | προὔπεμψεν scripsi e libris (προέπομψεν L) ἐξέπεμψεν Ferr Mor sed in hoc γρ προὔπεμψεν in marg προσέ- πεμψεν Re fortasse recte coll p. 270, 7 et Sopatri loco p. 320, 22 at cf. p. 349, 14 12 χρήσαιτο καὶ δῶρα inser Ma 13 num προὐβάλετο scribendum? at cf. p. 335, 9 14 ἂν om MaB 20 ἐσκαιώρησε scripsi e BVa sed in hoc in marg ἐσκευώρησε ἐσκευώρησε LPaMaClVi edd (ἐσκευώρισε Ferr) cf. ad p. 325,15
marginal RIV 590
footnote 4 cf. p. 349, 9 2 οὐχ in marg Va 2 3 τολοιπὸν L τοῦ λοιποῦ BVa 4 χρηστὸς MaClVi Par 3017 (Boissonad. Pachym. 13,1) | ,, verba δηλαδὴ τοῖς νόμοις periodum onerant. saltem δηλαδὴ delendum sed sic iterum p. “ lacobs Lect cf. p. 317, 16 6 μοιχευ- θεῖσαν τῆς οἰκίας ἁ sed ’σαν τῆς οἱ in ras m 2 | οἰκείας Vi 7 μηχανησάμενος Va sed γρ συσκευασάμενος in marg 10 γυ- ναιξὶ μόναις in ras Cl 2 12 κινδυνεύουσαν Cl sed ’σαν in ras m 2 et tuentur lacobsius Anth Pal III 811 et Bastius ep. crit. 282 coll. Chor. Patr. p. 243, 6 ed. Boiss. κινδυνεῦον ViBVa Par 3017 13 ἐπὶ τοῖς παροῦσιν om BVa | ὅτι ἁ 14 „malim χρήσωμαι“ Re | ἑστήκειν MaClVi 15 ξυμφορᾶς reposui e libris συμφορᾶς edd 16 διέσειεν Ferr | δὲ Β Re 18 πύθοιντο LPaMa sed in hoc ’ν inser, ViBVa Ferr 19 τὸν δὲ οὐχ οὐ- τω scripsi τὸν δὲ οὕτω PaMaViBVa τὴν δὲ οὕτω LCl edd τὸν δὲ οὔπω coni Re, τὸν δὲ οὕτω σκαιωρήσασθαι οὐχ lacobs Lect
footnote 1 sq. Sopat. l. l. p. 230, 5 6 cf. p. 342,16; 344, 7 10 Sopat. l. l. p. 230,6 11 cf. p. 345,1. Oppian. cyn. II 443 1 σκαιωρίσασθαι Β σκευωρήσασθαι Mor Re cf. ad p. 325, 15 | ὐποτοπίσας BVa | ἀπέδωκα MaClViBVa cf. p. 324,4 et 6 et Sopat. l. l 1 2 ὡσὰν Va | εἴποι scripsi e MaClViBVa εἴπῃ LPa edd | ἕδνων Β Va cf. p. 334, 2 3 ἐκρότησα defendit la- cobs Anim. ad Anth. gr. XIII 685 contra Re qui adnotat ,,malim συνεκρότησά“ | punctum post ἐκρότησα libri edd delevi 4 ἀπειλήσας BVa 5 ἐκείνοω Vi ἐκεῖνον Β Va Ι τά δ’ Οἶ’ τὰ δ’ Va 7 τῇδε BVa 8 προσβάλλοι scripsi e LBVa προσβάλοι PaMaCl edd προσβάλλει Vi | συνάψας Ma 9 δῆθεν om Va 10 τουλοιποῦ LPaVa | οἱ δ’ scripsi οἱδ’ Vi οἶδ’ PaMa Cl edd οἳ δ’ Va ἥδ’ Β 11 ἥδ’ Cl ἣ δ’ Va 12 πρα- χθῆναι L Mor 14 ἥδ’ Va 16 τόν δ’ ClViVa 17 σκευ- ωρίας Mor Re cf. ad p. 325, 15 | ἠξίουν] ,,hic videntur quaedam deesse“ Re 18 ταὐτὰ scripsi auctore Re qui ἐποίουν post πάλιν perperam supplendum censuit ταῦτα libri edd Ι οὐκ scripsi e LPaMaClViVa οὐδ’ Β edd
marginal RIV 591
footnote 5 cf. p. 351, 12. Eur. Med. 1149 1 σκευωρούμενοι Mor Re cf. ad p. 325, 15 2 παντελὲς Va sed ἕλες ex ἐς corr m 2 | περὶ οὐσίας L οὐσίας Β | ἐκκενκοομυμένην Va 3 ὰπανταχηοῦ Ma ἀπανταχοῦ Β 4 οὕτω Vi Ferr 6 ἀπαλλήλοις Οἶ’ Ι ἐξαμαρτόντων scripsi e LPaMaClViVa ἐξ-αμαρτανόντων Β edd 8 τὰς cl | πολλὰ Vi 12 δυστυχὴς scripsi e Macl sed in hoc εὐτυχὴς in marg, Vi εὐτυχὴς LPa BVa Ferr et γρ in marg Mor ἀτυχὴς Mor Re 14 μὰ inser Ma 3 | ,,post ἐλογιζόμην excidisse videtur εἶναι“ Re 15 τοῦτ’ Ma sed τ’ in ras m 3 16 πολιτῶν reposui e libris cum Bastio app. ep. crit. 54 πολλῶν edd | οἰκτείρειν ἐμὲ reposui e libria (sed ἐμὲ οἰκτείρειν ἐμὲ L) ἐμὲ οἰκτείρειν edd 17 σεντεντια postulat εἰ δ’ οὖν μή, {scil. ἔμελλον ἐμὲ οἰκτείρειν) ἀλλ’ οὐκ ἐμέ. ἀλλὰ τὴν τύχην“ Re
marginal RIV 592
footnote 3 Sopat. 1. 1. 230, 14 sq. 8 cf. t. IV 466, 1 R 1 τούς in ras Ma 3 | ὅ δ’ libri edd 4 δώσεῳν Va | δίκην Va 5 προὐβάλλεται L edd 7 ἑαυτὸ Vi Ι μὴ δ’ libri Ferr Mor μήθ’ Re | ,,post οὕτως videtur ἀπλῶς deesse“ ὂν ὂν 8 τῶν εἰργασμένων BVa τῶν εἰργασμένων Pa 9 φαυλοτέραν Ma sed αν in ras m 2 11 τίς LPaMaClBVa 12 ἐκπέ- φευγε Ma sed γε in ras m 3 16 τοῦ BVa sed in hoc hoc ex ὁ corr 22 ἀπῄτησεν MaClViBVa 23 πεφύραται L
marginal RIV 593
footnote 17 cf. p. 335, 7 1 τὸν ante τρόπον ViB et in ras Va | σκεαυιωρήσας Β cf. ad p. 325, 15 2 ἠδίκει καὶ MaClViBVa | ὅ MaBVa 4 οὐδεὶς Ma sed εἰ in ras m 2 6 τί Va | διάβαλε Β | τὸν inserui e Ma ὢ ViBVa om LPa edd sed ,,fort. τὸ πέρα τῆς φύσεως μου ὠμόν, aut τὸ παρὰ τὴν φύσιν praeter naturam, secus atque natura fert“ Re 7 πατὴρ] πρὶν Ferr Mor 8 δ’ οἱ scripsi e Β ShLPaMa ClViVa edd sed δὲ οἱ coni Re 11 προεπόμπευσα reposui e libris coll p. 333,3 προὐπόμπευσα edd 12 τοῦ MaClViBVa | ἱκέ- τευσα Ma sed ἁ add m 3 13 τὸ ante μηδέν libri edd sed ,,aut τὸ aut τι est delendum“ Re delevi 14 καὶ τῶν θυμά- των om Β | ἐπὶ τελουμένοις scripsi e Pa ut coni Re ἐπιτελου- μένοις reliqui libri edd 15 ἀνόητά LPaViB et γρ in marg Mor et Re | ἐκαλλιέργουν ClVi ἐκαλλιέρρουν Va 18 κἂν γονῆς ἑτέρας ante παῖς δ’ οὖν καὶ οὗτος ἐμὸς MaClViBVa
marginal RIV 594
footnote 4 παρὰ MaBVa 5 μὲν scripsi μὴ libri edd | οὕτω Ma ClViBVa | ὤφθης MaClBVa Mor 6 πρὸ ViVa | μὲν, οὐδ’ οὕτως ἂν Ma sed μὲν, οὐδ’ in ras m 3 et οὕτως ἂν in marg m 3 οὐδ’ ἂν οὕτως ἂν Vi 8 τολμᾶν Vi 9 ,,fort. πρὸς“ Ρε | θτραχσὐνεσθαι L | μετριώτατος Vi 10 μὲν Β 12 καὶ(1)] κατ’ BVa 13 κακοῦργος τίς MaClViVa | τὰ Ma sed ἁ in ras m 3, BVa τῆς Cl 14 δόξῃς reposui e PaMaClViBVa δόξεις L edd ] σύνοιδας L edd 15 ὡς scripsi ut coni Re οἶς libri edd 17 δῆλος BVa 19 δυσμενὲς BVa 22 λέ- γειν Pa sed εἰ in ras m 2 | οὐδ’ οἱ Ma
footnote 3 τοὺς om MaClVi | ἀγαγομένῳ scripsi ἀγομένῳ libri edd 4 ἰδόντι Ma sed τι in ras m 3 ἰδὀντους Γέ ἰδόντα Vi ἰδόν ΒVa 6 ἀπώνασθαι ΒVa sed in hoc ω in ο corr 7 ἔχοις scripsi e MaClVi ut coni Re ἔχης LPaBVa ἔχεις edd 9 ἔχοις reposui e libris sed οἱ ex εἰ corr L ἔχεις edd 11 ἄνθρωπον scripsi e MaClVi ut coni Re ἀνθρώπου LPaBVa edd 13 ἀλλ’ ovg ἔτεκεν om BVa 14 ἀλλ’(2) om Β | ἐφ’ Β 15 καὶ πλείους ἐπιδεῖν παῖδας MaClVi | ἤλπισεν LPaMaVa edd 17 ἀφῆκεν BVa | καὶ ante σὲ Β 21 αὐτοῦ libri edd 23 τέκνου Vi | τιμήσειν Ma τιμ(??) Cl | ,,post τιμήσαις ἂν deesse videtur εἴ τις σε βούλοιτο τὸ πατὴρ εἷναι πρὸς τῆς σεαυτοῦ δεξιᾶς ἀφελέσθαι“ Re cui recte oblocutus est lacobsius Lect
marginal RIV 595
footnote 1 πρὸ ClViBVa | αὐτοῦ libri edd 3 οὕτως μικρολόγος MaClVi 4 καὶ (2) om BVa | καὶ τί λέγω βάρβαροι om Mor 8 αὐτὰς om Vi | μετὰ καὶ τοῦ scripsi e MaClViBVa καὶ τὸ LPa edd cf. ad p. 343, 4 10 ἀσύνετος Ma | μὴ om MaClVi BVa 11 πολιτεύομαι Vi | τῆς ante τύχης BVa 12 ἔξω Vi 13 πᾶσιν Ma sed ἄσιν e ρο(?) corr m 3 14 νόμοις Vi 16 παρεκόντων Οἶ’ 21 εἰ lacobs Lect at cf. p. 319, 16 sq. 82 ξυνοίσεται Ferr Mor
marginal RIV 596
footnote 2 δὲ Β edd 3 περὶ Macl 4 μετὰ καὶ scripsi e LPa MaClVi coll p. 326,1 et 13; 327, 15; 331, 18; 342, 8 et 19; 351, 17 καὶ μετὰ BVa edd 6 ἀποίσομαι Ma sed γρ ποιήσομαι suprascr m 2 7 μετου ClVi 10 καὶ post δὲ δέ Ma | τῆ πόλει Ma sed ῆ et εἰ in ras m 2 11 ὅτι Vi 12 τύχοιεν Cobet Misc 141 | τὰ μάλιστα LPaMaViVa Ferr | σπουδαζόμενος Mor sed γρ σπουδαζόμενον in marg 13 τὸ] πῶς coni Re, εἰ la- cobs Lect I δυνήσεσθαι scripsi e MaClViBVa δυνήσεται LPa edd 14 ὅλως BVa | μηχανῆς BVa 16 μὴ δὲ LPaMaClVi Va Ferr | τὴν ἀρχὴν ΡαΒ | ὅλως ut scholium dictionis τὴν ἀρχὴν delendum censet Re cui lacobs Lect adstipulatur, Not. crit. in Lib. apol. Socr. p. 47 adversatur | τοῦ scripsi ut coni Re τε libri sed in ras Ma 3, edd 16 καὶ] μήτε lacobs Lect, μηδὲ Not crit | ταύτην BVa 18 τὸ Ma sed ὁ in ras m 3 | ἑαυτῶ Ma sed ὦ in ras m 2 ἑαυτοῦ BVa 19 ἐπαιτιασαίμην Πα ClVi
footnote 17 cf. p. 331, 17 sq. II. ’ς 209 1 κἀμὲ scripsi e MaClViBVa coll p. 365,11 κατ’ ἐμὲ L Pa edd sed καὶ ἐμὲ coni Mor quod probaverunt Re et Sintenis 3 μηδ’ scripsi μήθ’ libri edd | ὑπό του BVa | τανῦν libri edd 4 ἡμέτερος Vi 5 ὃλωονς L 6 τούτοις Β 8 ἀπένευον MaClViBVa 9 παρακρουσάμενος Vi 10 ἐς MaCl 12 ἀδικεῖν om Re 17 ἐγίνετο MaCl 21 τά δ’ Pa 22 ,,fort. τῆς κατ’ ἐκείνων τόλμης (subaudi ἐμῆς)“ Re
marginal RIV 597
footnote 1 cf. p. 336,11 4 Sopat. 1. 1. p. 230, 19 8 cf. p. 338,19; 363,6 9 Sopat. 1.1. p. 230,20 14 Anacreont. 36(41),3 17 Sopat. 1. 1. p. 230, 22 20 cf. t. IV 473, 18 R 1 δόλους ὁ μὲν MaClViBVa | ἀπήῥ͂υεν Vi 2 ἡ δ’ scripsi ἥδ’ libri (ἥ δ’ Ma) edd | ἐπήγετο BVa | ἀνὴρ Ma sed νὴρ in ras m 3 4 ἡ δ’ scripsi ἥδ’ libri (ἥ δ’ Ma) edd 5 ἑάλωκε Mor I τε inser Va om Mor 6 μὴ δὲ libri 8 ἀξία Cl 9 τηνικαῦτα Vi | ἐπ’ αἰσχυνόμενον Ma 10 σκευωρήματος Mor Re cf. ad p. 325,15 12 ἐπήρετο BVa Ferr | ἀπ’ BVa 13 τολοιπὸν LPaVa Ferr | τῆς ante γλώττης BVa 14 ἥδετο Vi 15 γρ θυγάτριον in marg Mor 19 θεοῦ Ma 31 δεινῶς Va
marginal RIV 598
footnote 10 Sopat. l. l. p. 231, 13 sq. 2 ἢ inser Ma 2 | ἄλλως Vi | συνήθων BVa ξυνήθως Vi 4 κατελεουμένων scripsi καὶ τελουμένων e καὶ τελούντων corr γ’ L καὶ τελουμένων Pa καὶ τελουμένων MaClViBVa Ferr καὶ γελωμένων Mor sed γρ τελουμένων in marg, Re sed κατελεούν- των coni cf. p. 328, 1; de medio cf. ἐπαπειλούμενος p. 347, 4 6 εἰδόσιν Ma | ὁ om MaClVi 8 ἢ scripsi ἢ libri edd 9 signum interrogationis post ἔχουσιν Mor Re 10 πειρᾶσθαι inser Va 2 11 πατρὸς scripsi e Vi ut coni Re πρὸς LPaMa ClBVa edd 11 et 13 οὐκ οὖν scripsi οὐκοῦν libri edd 12 ἀλλὰ μάτην. vel ἄλλα ἐποίουν coni Re | τἀς BVa | τελευτᾶν Ma sed v add m 3 τελευτᾶσ’ Οἶ’ τελευτὰς Β Va 13 signum in- terrogationis post ἀπελεγχομένων edd delevi 14 τελευτᾶν Re 15 ἐπιπλήξεις scripsi e MaClVi ἐκπλήξεις LPaBVa edd 17 ἀπέσεισα ὢ sed ἁ in ἑ corr m 3 | τὸ Ma sed ὁ in ras m 3 τῶ BVa | δὲ post τὸ Ferr Mor sed in hoc γρ τὸ γὰρ in marg, Re sed aut delendum aut in τε mutandum censuit delevi
marginal RIV 599 6 sq. cf. p. 360, 9. Plat. rep. III p. 406 A et D 16 Od. δ’ 10 20 sq. Sopat. 1. 1. p. 230, 14 sq. 2 ἁπλοὶς Β Va | ἐπιστίφειν BVa 3 ταῦτα Ma sed e τοῦτο corr m 3 4 δ’ om Vi 5 ἐπέραινον scripsi e BVa ἐπέ- ρανον LPaMaClVi edd | ὁπλίζομαι Va sed ομαι in ὢ corr 7 καυτῆρας Ma sed ὒ in ras m 3 κρατῆρας ClVi | καὶ inser Ma om ClVi 9 τελευτῶσι BVa | τοῦ Ma sed ov in ras m 3 | δόλου Πα sed ὁ in ras 2 litt m 3 δούλου Vi 10 εὐδοξίας Vi 14 περιουσίας Ma sed περιουσ in ras m 3 | τὸν νόμον Ma ClViBVa 15 γημαμενον Vi γημαμένους BVa 16 ἑτέρους scripsi ut coni Mor Not et Re coll p. 350, 16 ἕτερον libri edd 17 ἐπετείχισα Ma sed ἑ (1) ex ἁ corr m 3 18 ἀποκλέπτειν Ma 19 καὶ ante μέχρι Vi | σχήματος MaClViVa | τὸν μοιχὸν ὀρῶν MaClVi
footnote 2 cf. t. IV 444, 5 20 Opp. hal. III 194 2 οὐ γὰρ ὁ πεσὼν Va | μοιχὸς Πα sed ἴ’ in ras m 3 3 με- μοίχευται MaClVi ἐμεμοίχευτο coni Mor Not cf. p. 349, 20 4 ,,malim ἀλλὰ γὰρ καὶ πάλιν“ Re 5 μου MaViVa 6 δυστυχῆ] δὶς BVa 7 αὐτοῦ libri edd | πολλή τις ἀνάγκη σώζεσθαι in lac 15 fere litt om Β | ἀνάγκη σώζεσθαι] ἀνασώ- ζεσθαι MaClViVa 9 ἅμα scripsi auctore Re ἀλλὰ libri edd | ἀνέχεσθαι scripsi auctore Re ἀντέχεσθαι LPaBVa edd ἀντέχεας MaCl ἀντέχειν Vi 11 οἰός τε Re 13 ἐκ τῶν ὀφθαλ- μῶν om Β 14 ὡς om Vi 16 ὅμως inser Ma 3 18 μοι- χεύσων scripsi e MaClVi μοιχεύων LPaBVa edd | μαστρωπί- δων ClBVa 19 γυναικὸς reposui e libris γυναικῶν edd sed γρ γυναικὸς in marg Mor 20 τὰ MaClB Va
marginal RIV 600
footnote 1 πινακίσκῳ lacobs Lect | καὶ ante τὸ Mor Re qui delen- dum censet aeque atque lacobs Lect | ἐσήμηνε L ἐσήμαινε MaClViVa ἐσήμανε Β 2 προέτεινε L Ferr προτεῖναι Ma προτεῖναι Οἶ’ προτείνει Vi προτεῖναι BVa | μετου ClVi 3 μακρὸν scripsi auctore Re μικρὸν libri edd | ἐπὶ δὴ τούτοις in lac 7 litt om Β | δὲ Ma | ἡ] καὶ Ma 5 ἐθέλοι ὢ 6 ἐκεῖνος Ma sed ἐκε in ras m 3 7 σύνθημα BVa 10 τῆς] τοῦ MaCl | ὐπ’ ἀμφοῖν scripsi ἐπ’ ἀμφοῖν ἐπαμφοῖν Cl) libri edd 13 ἐνεδέησε Vi ἐδέησεν BVa 14 προὔπεμπεν LPaClVa edd cf. ad p. 334, 11 | ἡ δ’ scripsi ἡδ’ Οἶ’ ἥδ’ reliqui libri edd 18 ἡ δ’ scripsi ἡδ’ Ma ἥδ’ reliqui libri edd 19 ἐν οὐκ MaClVi 20 ξυνεληλύθεσαν reposui e libris ξυνεληλύθησαν edd sed ,,aut ξυνεληλύθεισαν aut ξυνε- ληλύθεσαν leg.“ Re 21 σκευωρούμενον Mor Re cf. ad p. 325,15
marginal RIV 601
footnote 1 „fort. τοσοῦτον λέγω· δυστυχὴς εἰς τοῦτο τὸ μέρος καὶ κακοδαίμων“ Re 2 ὁ καὶ τοῦτο τὸ μέρος κακοδαίμων lacobs Lect I μὴ δὲ LPaMaClViVa Ferr 3 πάμπαν lacobs Lect 6 οὐ τόγε μή coni Mor 7 οὐκ inserui e MaClViBVa om LPa edd sed οὐκ ἂν inserendum coni Re 8 μὴ δὲ LPa MaClViVa Ferr 10 βουλὴν MaClViB sed in hoc ὒ eras, Ferr Ι τὰ om BVa 12 τὸ inser Fa om MaClVi 13 τοῦτό — 14 ἐξηπίστατο inserui e libris om edd sed latine reddidit verbis hoc profecto etiam callidus ille vir noverat Mor 15 ἐπέ- ’γραφε Ma sed ε(3) in ras m^ 17 τολμήσαι scripsi e PaMa ΟἰVτ ut coni Re τολμῆσαι BVa sed in hoc * in ’ corr m* ToX^riaag L edd | tov Ta] t6v6s Mor 19 ,J,ocus hic depra- vatus est. utcunque mollias addendo nad^sLv post \\loi%svo^bvcov. Verum tamen aliud melius requiro*’’ Re at cf. praef. p. 318, 35 Ι κατέκρινεν Vi 20 ἐν scripsi ἐπὶ libri edd sed aut delendum aut in ἐπιτιμίοις mutandum censet Re ἔτι coni lacobs Lect | ἐναχόμενον L ἀνεχόμενον Ma sed ἁ in ἑ corr m2, ClVi
footnote 12 cf. p. 337, 5 1 ἂν om BVa | εἴη post δίκαιον inserendum videtur 4 ἀπεσκευακότα Β | καὶ om MaClVi 5 παντάπασιν MaVi ,,num ἀπαντᾶν πᾶσι? non satis placet“ Re | προσῆκον | καί om Vi 7 τῶν om BVa 9 γένοιτοτ’ Vi | τις repo- sui e libris cum Morello Not et Cobeto coll 297 τι edd 10 γυνὴ reposui e libris τις edd γυνή τις coni Re 12 ὐπο- ὑποκλέψαντός scripsi ἀνθελόμενον libri edd 15 ἀνελόμενον Ferr Mor sed in hoc γρ ἀνθελόμενον in marg 17 καὶ τῆς] καλῆς lacobs Lect 19 δὲ scripsi e MaVa δὴ LPaClViB edd 20 αἴσχιστος Va sed γρ ἔχθιστος in marg | τοσοῦτον Vi 21 δικαιότατον B Va
marginal RIV 602
footnote 4 Sopat. l. l. p. 230,25 16 Anacreont. 58 (52), 20 2 δὲ χρῆν Vi 3 ἐκείνου Ma sed οὐ in ras m 3 4 το-λοιπὸν LPaMaViBVa edd 6 εὐδοξίας Ma sed γρ ἀδοξίας in marg m 2, Cl | καὶ scripsi e MaClViBVa coll p. κατὰ LPa edd 7 καὶ inserui e MaClViBVa om LPa edd 9 αἴσχιστον Β 11 ἑαυτούς αὐτοὶ scripsi αὑτοὺς ἐαυτοὶ BVa αὐτοὺς ἐαυτοὶ LPaMaCl αὐτοὺς αὐτὸ Vi αὐτοὶ ἑαυτοῖς edd sed ,,malim αὐτοὶ ἑαυτοὺς“ Re 12 ἐξ ὅτουπερ ClVi 13 κεκωδὧνιστο Vi 16 προδότης LPaMaClBVa Ferr | ἀπο- καλούμενος BVa 18 ἀνηλλάξαντο Pa 19 εἴθ’ Pa 22 δοκεῖν libri corr Ferr
marginal RIV 603
footnote 9 cf. p. 253, 3. t. VI 620, 12 1 σωφρονούσῃ Ma sed ὕσῃ in ras m 3 σωφροσύνη Re | τοῦ τὴν τἀνδρὸς scripsi auctore Re τὴν τοῦ ἀνδρὸς libri edd sed τοῦ τὴν τοῦ ἀνδρὸς coni Mor 6 νόμοις libri et γρ in marg Mor corr Ferr ,,aut servanda vulgata aiit, si νόμοις praeferamus, legerit ὑποταττόμεθά“ Re 8 βουλομένους MaCl sed in hoc ἑ supra βαυ, ViBVa 10 ὅτι ClVa 12 οὐκοῦν Ma sed οὑν in ras m 3 13 επραξααίμην Ma διεπραξαἰμην Cl 15 γέμων LPaCl 16 παρὰ τούτων Va 20 ἀδοξεῖν Ma sed ἁ in εὑ corr m 3 22 καὶ inserui e MaClViBVa ut coni Re om L Pa edd
marginal RIV 604
footnote 12 cf. t. II 362, 3 15 Alciphr. II 3 22 Sopat. 1. 1. p. 231, 16 3 τί Va | ἑτέρως Cl sed ὡς in ras m 3 5 συνῆκε Ma | τί MaClViVa 6 τοσοῦτο Macl τοσούτου Vi 7 τοῦτο in τούτω et τὸ in τῶ corr Ma 10 ,,malim τι“ Re 11 χυθεὶς scripsi auctore Re ἐπισχεθεὶς libri edd 12 ὃ δ’ L Ferr Mor ὃ δ’ PaMaClViB Re 15 τῶν om Va 20 τὸν Vi 22 τὰ τῆς αἰσχύνης om Β | τε om Β
footnote 14 Testim. apud Dem. cor. ’ξ 137 p. 273, 8 16 cf. t. V 389,9 1 ἐφεῖρπε Β ἐφῆρπε Va | ἀστυγείτοσιν περὶ Ma 2 comma post ξένοις posui piinctum libri edd 7 δπη BVa S δὲ Vi 12 παραβαινόντων Β | ὑπεραλγοῦσι Cl 13 αὐτῶν Ma ClViVa Ferr Mor | αὐτοὺς om BVa 14 οὓς Vi | τὰ om Β Va I τὸν νόμον in τῶν νόμων corr Va | ,,malim τηρήσειν“ Re 15 περιύβριστον Β 16 ὅλος MaClViVa | ἄλλων Vi 17 ἠτίμωμαι Vi | ὅ MaVi | δ’ ὁ MaClVi 18 τούτω MaCl sed in hoc ύτω ex ῦτο corr, Vi „malim τούτῳ“ Re 19 ἐμέ- λησεν scripsi e MaViVa ut coni Re ἐμέλλησεν Cl ἠμέλησεν Pa edd
marginal RIV 605
footnote 1 Nonn. Dion. IV 182 11 Sopat. 1. 1. p. 231,20 sq 12 Eur. Andr. 921. Arist. ran. 750. Plat. leg. IX p. 881 D 19 Arist. nub. 1036; ran. 844. 1006. Eur. Cycl. 424 23 Lys. or. 31 § 2 p. 187,1 1 μετήλλαξα BVa 3 τότε Va | μικρὸν BVa 6 ἔστι scripsi e Vi ἔτι LPaMaClBVa edd 7 θεάτρου MaClVi 10 ,,malim περιόπτεσθαι“ Re | ὑφέρπον Ma sed ὒ in ras m3 11 ποτὲ BVa 14 γε ClVi | γε Vi | ἀδοξίαν Vi 16 ὑπεισῆλθε τίς MaClVi 18 τοῦ Ma sed v in ras m 2 τοὺς ClVi | ὁρᾶν ἔχειν ἐσκέψατο in ras Ma3
marginal RIV 606
footnote 2 τομηδὲν L 4 γίνεται MaClVi | δραμόντων Vi 5 ἔχοι scripsi e ClViBVa ἔχῃ LPaMa edd 9 μωρίας Β | ἐς in- serui e MaClViBVa om LPa edd 10 ἀναλογίσασθαι MaCl 11 τηλικαῦτα Ma sed καῦτα in ras m 3 | ὁ om Mor 12 οἶδε Β 13 παραυτίκα scripsi e PaMaClViVa παρ’ αὐ- τίκα LB edd | ἐπέσεισεν Ma 15 ἡμῖν libri Ferr et γρ in marg Mor corr Mor 16 ἀπωκνήσαντα LPaCl Ferr ἀπωκνή- σατε Ma sed γρ ἀπωκνήσαντα suprascr m 2, ViBVa corr Mor | ἢ scripsi auctore Re εἰ libri edd 18 τι ante ἀποστήσομαι edd delevi ὑποστήσομαι Ferr 19 ἐξήλεγχε BVa 21 τῶν in ras Ma 3 | σύ γε μάτην reposui e libris μάτην σύγε edd | γίγνου B Va
marginal RIV 607
footnote 1 cf. t. IV 813, 7 R 4 Eur. Med. 119. 348 13 Her. IV 54; 195, 2; VII 195 14 Opp. cyn. I 122; IV 254 cf. p. 360, 10 1 ἢ ClBVa | πρὸ Ferr | Δίκη Mor | αὐτὴ Re 2 ,,fort. ἄνθρωπον ἀνθρώπου“ Re 3 τῶν μετριωτέρων scripsi e Ma sed γρ τὸν μετριώτερον in marg m 2, ClViBVa μετριώτερον L Pa edd 4 λήμματος MaClViBVa | ἀνθρωπικώτερα BVa 5 ,,post ἐπιπηδῶντα deest aliquid, e. c. τοῖς ἐμοῖς“ Re 6 καἰ- τοι τι λέγω coni Re 8 ἐξαστυγεἰτονος ViVa 9 πορροτέρω edd 10 δοκεῖς μ’ scripsi δοκῆς libri δοκοῖς Vi) edd et de- fendit Re ἐμὲ ad ἐθελῆσαι supplens | καὶ Ma sed ἢ suprascr m2 om BVa 11 αὐτῆς φύσεως scripsi e MaClVi cum la- cobsio Lect φύσεως αὐτῆς LPaBVa edd sed αὐτῆς φύσεως κοινωνοὺς vel μερίτας coni Re 13 περὶ? at cf Her. 11. 11. 14 signum interrogationis posui e Β comma reliqui libri edd | οἱ δ’ BVa 16 εὐλόγως Ma
footnote 1 Arist. av. 1100 11 Hierocl. apud Stob. floril. 67, 24. Soph. Ai. 492 3 καὶ om Vi 4 φόνου scripsi e PaMaViBVa φόβου LCl edd 9 καὶ(2) om MaClVi 12 μύσος MaVa μῖσος Cl | ἐπ’ οἴκου om Β ἐποίειν Va | ὐποτελούμενον BVa 15 ταὐτὰ scripsi e MaClVi ut coni Re ταῦτα LPaBVa edd | „circa ἄξιοι deesse videtur οἱ τοιοῦτοί“ Re | παραμφοἱν Cl 18 ἐφ’ Ma | ἐφῆκεν Mor sed γρ in marg ἐφήκει ἐφῆκε Ma ἀφῆκε BVa 19 ὁ inserui auctore Re coll. p. 357, 11 om libri edd 20 ἀλλὰ ante καὶ Β | τὸ δ’ MaClViB Va 21 ἀφαι- ροῦμαι MaClViBVa
marginal RIV 608
footnote 10 sq. Ael. var. hist. 1 34 18 Sopat. 1. 1. p. 231, 20 1 τὸ(1) scripsi e PaMaViBVa ut coni Re τὸν LCl edd | ἄλλο τι ἢ ὅτι] ἀλλ’ ὅτι MaClViBVa 2 δικαίως ἠγώνισμαι] δίκαιος ἀγωνίζομαι γα sed γρ δικαίως ἠγώνισμαι in marg m 2, ClViBVa 5 οἷός τ’ Re 9 „malim ὁπόσα κατασέσηπέ“ Re at cf. p. 319, 6 10 ὁπόσους Ma sed ὅσους in ras m 3 ὁπόσας Cl ὁπόσα BVa | φωράσαι BVa 11 ἀποθνήσκοντα BVa 13 αὐτῶν scripsi e Vi αὐτῶν reliqui libri edd 15 ἶσον Ma ClViBVa | τὸ BVa 18 ἡμῖν ἐμπηδῶντες MaClVi | καὶ οὗτοι Vi 19 κοινωσάμενος scripsi e MaViBVa coll p. 361,8. Sopat. l. l. κοινωνησάμενος LPaCl edd 20 τοῦ Vi 21 τὸν ἐμὸν Cl sed in τῶν ἐμῶν corr m2
marginal RIV 609
footnote 2 τάχα MaClVI 7 ὅτι MaClViVa 10 ταῦτ’ BVa | κακὸν Ma sed κ in λ corr, Vi 13 ὁ om Re quod notavit Bastius Greg. Cor. ed. Schaefer p. 139 14 προσεπιτούτοις MaClViB πρὸς ἐπὶ τούτοις Va | ἐξεπιστάμην MaClVi 15 πάντα scripsi πάντας Hbri edd sed ,,malim πάντας πάντα“ Re 20 ὠθήσωσιν BVa 21 καὶ ante τὰ MaClViBVa | τα- πρῶτα LPaMaVa Ferr | εἶχον reposui e libris sed ex εἶχεν corr L, ut coni Re εἶχεν edd 22 ὅτι MaClViBVa 23 ἔψευσαν Cobet Coll 297 at cf. p. 95, 3 24 τοσοῦτον Ma Vi
footnote 9 sq. Sopat. l. l. 1. p. 231,9 sq. 18 cf. p. 363,6 et p. 338,19 2 μὴ δ’ libri Ferr | ἐλθεῖν Vi | ὅλως inser Va 2 | ὡς om Va 3 τίς MaClViVa | ὧς Pa sed πῶς in marg, Ma sed in πῶς corr m 2, Mor sed γρ πῶς in marg πῶς L ,,malim οὕτως“ Re | ,,malim οὕτως“ Re | ἐπὶ κενῆς coni Re at cf. t. IV 811, 33 R | καινοῖς B Va 6 τί LMaClViBVa edd 6 ἶσον MaClViVa 8 νόμος καὶ φύσις Vi 9 ἄν φησιν in ras Ma 3 11 καινῷ Ma sed ιν e κ corr m 3, BVa | σοι inserui e LPaMaClViVa om Β edd | σκευωρουμένοις Vi 12 καὶ om B Va 13 ἐκακούρ- γουν — μοιχῶν in marg Ma 3 | τῶν om Vi 14 μοιχὸν BVa | πάλαι Ma sed άλαι in ras m 3 15 πρὸς BVa | ὑμῶν Β 16 κληρονομησάμενοι BVa 18 καταιδέσειν LMa sed έ in ras LMa3 19 λέγειν ViB
marginal RIV 610
footnote 4 cf. p. 331,17; 344,17 9 Eur. Alc. 650 22 Plat. apol. p. 40 C 3 ἔτι Β 8 ὑμῶν Ma sed ὑ in ras m 3 9 κερδανοῖς Cl 10 βιάζει MaClVi 11 ὧς τάχιστα Β | punctum post τοι- αὐτὰ edd sed delendum vidit Mor Not 13 οἱ δ’ scripsi e ἁ Vi οἵδ’ LPaMaBVa edd | σκευωρεῖν Mor Re cf. ad p. 325, 15 18 φιλοστοργὧτερος BVa 23 πονηρὰ ἁ 24 ἐπὶ τῇ γονὴ scripsi ἐπὶ τὴν γονὴν libri edd sed ,,aut ἐπὶ τῇ γονῇ leg. videtur aut κατὰ τὴν γονήν“ Re
marginal RIV 611
footnote 20 cf. p. 325, 5 21 sq. cf. t. V 145, 12; t. IV 803, 11 sq. R 23 Sopat. l. l. p. 232, 11 sq. 1 ἀτυχέστατον scripsi ἀτυχέστερον libri edd 3 ὀλοφύ- ρομαι Ma 6 πατρὸς Vi 7 τἄλλα πάντα MaClVi 11 ὸ́φε- λον Β 14 ἀνομίαν MaViVa 16 ὑπανεῖχον scripsi e LMa ClViBVa ἐπανεῖχον Pa edd 19 ἀλλ’ ante ἐκεῖνον BVa 21 καὶ ante τάφος BVa | ἐκεῖνος ὁ γάμος MaClVi 22 Πυρι- φλεγέθων reposui e libris πῦρ φλεγέθον edd sed γρ πυριφλε- γἐθων in marg Mor | Ὑμέναιος Mor Re
footnote 10 Eur. Cycl. 152 15 Sopat. l. l. p. 232, 7 sq. 1 ἐμαυτῶ Vi 4 τοπρῶτον Pa Va Ferr | τοτελευταῖον Pa 5 πατέρος Fa Mor Re | οὐκ ante ἐμοὶ MaClViBVa 7 ἐν scripsi ἐφ’ libri edd 8 τί MaClVi | ὄψωμαι Pa sed ω in ο corr, BVa et coni Re at cf p. 319, 16 sq. 10 καὶ om MaClViBVa | ἀναμνημονεύσω MaClViVa μνημονεύσω Β B cf. p. 329,2 | τότε(2) scripsi e MaVa τό τε LPaClViB edd 12 μὴ καταλγεῖν Vi 13 καὶ σοὶ scripsi e MaClVi καἰ σοι LPaBVa edd 15 οὐχόπως Β | οὐ om BVa 16 εὐκτέον Bast ep. crit. 217 et Boeckh Plat. Min. 170 cf. p. 342,13 17 ἀπαλλάξειν Pierson Moer. 137 ἀπάλλαξιν Boeckh 18 βολό- μένος Pa Mor sed vertit caesits, Re sed adn: „lege βαλλόμενός“ 19 σώματος BVa Mor sed vertit: in tumulo | ἐπαυτοφώρῳ Pa sed ras supra παυ, ClViB 20 παισὶν Ma
marginal RIV 612
