@node
@author=Origen
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Charles Vincent Delarue
@filename=tlg2042.tlg058.1st1K-grc1
@funder=Harvard Library Arcadia Fund
@principal=Gregory Crane
@publicationStmt=Harvard College Library, tlg2042.tlg058.1st1K-grc1.xml.
@respStmt=Digital Divide Data, Corrected and encoded the text, Gregory Crane, Editor-in-Chief, Perseus Digital Library, Matt Munson, Project Manager (University of Leipzig), Annette Gessner, Project Assistant (University of Leipzig) 2015 - 2017, Thibault Clérice, Lead Developer (University of Leipzig) 2015 - 2017, Bruce Robertson, Technical Advisor
@sourceDesc=Origenis Opera Omnia, Charles Vincent Delarue, Origen, Imprimerie Catholique, Paris, 1857, 2, The Internet Archive.
@sponsor=University of Leipzig
@title=Selecta in Psalmos [Dub.]
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T15:11:15Z

127449	footnote (17) Τέλος δʼ εἶναι λέγουσι, etc. S. Hilarius pro-logo in librum Psalmorum num. 18 : « Finis est cujus causa cætera fiunt, ipse autem nulli alii cansam suam præstat. Ob finem enim umnia, nihil
footnote 21 Psal. 1, 1. 22 Psal. XLI, 2. 23 PsaI. LXXII, 1. 24 Psal. LXXXIX, 1. 25 Psal. CVI, 1. 26 Psal. LXXXIX, 1. 27 Psal. XC, 1. 28 Psal. XCI, 1. 29 ibid., 2. 30 Psal. XCII, 1. sorum auctorum nominibus sub diversis superscrip-tionibus habentur, antiquorum virorum is-ta traditio est, quod ex eo psalmo, cujus auctor in sperscriptione præponitur, qui deinceps sine aucto rum superscrptione succedunt, ejus esse existimandi sunt, qui anterioris psalmi auctor inscribitur, usque in eum psalmum, in quo nomen alterius auctoris præferatur: ut si psalmi alicujus superscriptio talis sit, psalmus David; cæteri qui sine titulo consequantur, David esse credantur, donec prophetæ alterius nomen in superscriptione ponatur; et ex eo usque in alterum prophetam, qui sine inscriptione medii sunt, qjus sint qui in anteioris psalmi superscriptione auctor cœptus sit anteferri. »
footnote 31 Psal. XCIII, 1. 32 Psal. XCIV. 1. 33 Psal. XCV. 1. 34 Psal. XCVI, 1. 35 Psal. XCVII, 1. 36 Psal. XCVIII, 1. 37 Psal. XCIX, 1 et 2. 38 Psal. XCVIII, 5, 6, 7. 38 Jerem. XV, 1. 40 III Reg. XIII, 2. (20) Τοότων εἰρημένων, etc. Hilaius ibidem num. 4 : « Quod » torte aliquis per id intelligentiæ huic ﬁdem detrahet, quod in his. psalmis qui eum psalmum, cni Moyses auctor prælatus est, subsequuntur, scriptum sit, id est in nonagesimo octavo, Moyses et Aaron in sacerdotes ejus, et Samuel inter eos invocantes nomen ejus, nnn posse a Moyse eum prophetatum videri, cum Samuel nomen, qui tanto postea quam Moyses, natus ed, exstet in psalmo: meminert nulli mirum ant dilicile videti oportere, ut tantus popheta tanti
footnote 41 Psal. LXXIV, 2. 42 ibid., 4. 43 Psal. LXXV, 2. 44 ibid., 4. 45 ibid., 10. 46 Isai. v, 2. est ex epistola Hieronymi ad Mat cellam; quæ exstat tom. II, editionis Vallarsii, p. 707. (22) Ναόν. Grabius, λαόν.
footnote 47 Psal. VIII. 2. 48 Psal. LXXV. 2. 49 ibid., 12. 15. 50 Ps. LXXXIII, 2, 3. 51 ibid. 4. 52 ibid. 10, 11. 53 Ps. VI, 5, 6. 53 ipid. 10. 54 Ps, XI, 2. 56 ibid. 6. (23) Ὁ Κύρος ἡμῶν. Montefalcoaius, ὁ Κύριός μου. (24) Grabius, ὑπολήνιος.
footnote 57 Ps. LIX, 8, 9, 10. 58 Ps. LXVIII, 22. 59 ibid. 2. 60 Ps. XLIV, 1. ⁶1 ibid. 11. 62 Ps. LXXIX, 9. 63 Ps. IX. 4, 64 ibid. 12. 65 ibid. 15. 66 Ps. XLV, 7. 67 ibid. 11. usus est Montefalconius, aliquot folia quæ hic sup-plentur e schedis Ernesti Grabii cui integrior codex ms. obtigerat.
footnote 68 Matth. XI, 29. 69 Ps. LV, 2. 70 Ps. LVI, 4. 71Ps. XXXVII, 4. 72 Ps. LVIII, 1. 73 Ps. XCI, 3. 74 ibid. 14.
footnote 75 Ps. XCIX, 5. 76 Ps. XXXIII, 1. 77 I Reg. XXI, 1 et seqq. 78 Ps. XXXIII, 1. 79 ibid. 9. 80 Reg. XXI, 15.
footnote 81 Psal. X, 2. 82 Psal. XIII, 1. 83 Psal. LXI, 3. 84 Psal. LIV, 2. 85 Psa. XXVI, 1. 86 Psal. LXXI, 2. 87 ibid. 8. 88 ibid. 17, 19
footnote γραμμένους εἰρῆσθαι. Hæc desiderantur in codise ticani, quo usus est Montefalconiuseædem schedæ, οὐδὲ γὰρ ἂν ἔχῃ.
footnote 90 Psal. IV, 2. 91 Psal. VI, 9, 10. (29) Πρὸς τόν υἱόν. Codex Vaticanus, πρὸς τὸ υῦν. (30) Codex Vaticanus, ἐπεγέγραπτο. (31) Codex Vaticanus τὴν φωνὴν τοῦ κλαυθμοῦ μου· εἰσήκουσε Κύριος τῆς φωνῆς τῆς δεήσεως μου. (32) Οἱ πλείους, etc. Hilarius Prologo in librum Psalmorum, num, 9 : Psalmus tertius secundun historiani quinquagesimo psalmo posterior est: inscriptio namque utriusque multo intervallo temporis œtalisque diversa est. Nam hic quœ sub Uria et Da
footnote 93 Apoc. III, 7. 94 Apoc. V, 1 et seqq. 95 Isa. XXIX, 11, 12. 96 Luc. XI, 52. habet; quia ipse per hæc septem qeædam signacula, quæ de corporalitate eus, et passione et tnorte, et resurrectione, et gloria, et regno, et judicio Datid de eo in psalmis prophetat, absolvit : apeiens quod noemo claudet, ct claudens quod nemo aperiet: quia per hanc quæ in illo expleta est, prophetiam, aperiet quod nemo præcludet; et contra expletæ in eo prophetiæ ﬁde abnegata, claudet quod nemo possit aperire. Nullus enim nisi lle, in quo iæc prophet ata sunt et expleta, clavem intelligentiæ hujus impertiet. Denique idipsum consequenter docuit dicens : Et vidi super dexteram sedentis in hrono librum scriptum deintus et deforis, ngnatums signaaulis septem: et vidi alterum angelum valan prdicantem voce magna: Quis cst dignas apcire librum, et solvere signacula eius Et nemo potuit neque n celo, ncque in terro, neque inira rear, aperire lbum, neque video ipsum. Et ﬁebam qui nemo diquus repertus esset aperire librum neφue rdere psum. Et unns de senioribus ait mihi ς Npli ﬁere, ecce vicit leo de trib Juda, radix Datid, aperire
footnote inveniat : sitque aut familiaris scientiæa, cogaitma cito ex copia illa congestæ in uaumu raroostis eligere; aut ingentis laboris, aptam et congruos clavem aperiendi uniuscuiusque aditus invenire: quteratio et qualitas non sinat, non suas clares claastm disparibus coaptare. (45) Ἀσάφειαν. Unus codex Regius, ἀσφάλειαν. παρακαλεῖσθαι. (47) In vuigalis Apostoli codicibus Græcis leg·. tur, Πνεύματος ἁγίου.
footnote 98 Psal. 31, 7. 99 Matth. v, 18. (48) Φαίνεται. Huetius maluisset καταφαίνεται. (49) Ἰδίωμδ τι. Uterque codex Thuanæus, ἰδιώ- μιουργῷ ad Christi Patrem. HUETIUS. ματα.
footnote hæc exstant in codice Barocciano, et in schedis niss. Conibefisii, Latine antei in Catena Barbari. In Catena Corderii Gennadio tribuuntur.
footnote 4 Luc. XXIII, 45.
footnote hæres. LXIV. (61) Post ποιεῖν deest ἐπιτρέπειν, vel quid simile. (62) Ἀλόγους. Forte ἀλόγως.
footnote 6 Matth. VIII, 12. 7 Matth. X, 28. 8 Rom. VIII, 11. (63) Αὐτόν. Forte legendum, αὐτῶν. (64) Εἰς τήν. Forte τοὺς τήν, etc. (65) Ὤσπερ, etc. Hunc locum in Apologia Pam .1, ili sic vemt Ruﬁnus : Scot enim in nobis eadem μσρςi es permanet ab iefantin nsque ad seneclutem, »ρe-t characteres multam rideantur mmutotionem ρσi rere ς ita imellgendum est hanc speciem qnæ ἄη σεæ inest nobis, ipsam permansuram etiom in fu χ r, plurima tamen immutatione in melus et aloiasi æns facta. V eresαe est enim ammnam in locis φ ryarets habitantem nti corporibus talibas pur apli pse ais locis in quibus degit. Et sicut, verb caus. i i ss aquis maris not habitare, vel degere posceret,
footnote 9 I Cor. XV, 44. 10 ibid. 20, 1¹ Psal. XXI, 15. 12 Psal. VI, 3. 13 Ezech. XXXVII, 11. (66) Περὶ τοῦ τὸν ἅγιον. Forte legend. περιττὸν τὸ τῶν ἀγίων. Sed hic locus corruptus est. (67) Ἐεὶ τὸ ὅσον. Forte, Ἐπεὶ ὅσον.
footnote 14 Matth. VIII, 12. 15 Psal. III, 8. 16 Psal. LVII, 7. 17 Matth. X, 28. 18 Rom. VIII, 11. 19 Col. III, 4. 20 I Cor. XV, 35. (68) Κρίσις ἐστί, etc. Descripta sunt e schedis Ernesti Grabi, et Combefi, ii, Latineque exstant apud Barbarum.
footnote 21 II Tim. 11, 19. 22 Joan. XIV, 6. 23 Jerem. VI, 16. 2⁴ Genes. 111, 9. 25 Marc. V, 9. 26Luc. III, 45. 27 Matth. XI, 27. 28 Psal. XLIII,, 24. 29 Act. XIII, 33. psalm. I, num. 19. (70) Δυσὶν ἐντυχόντες, etc. E codice Barocciano, et schedis Combeﬁsii. Latine exstant in Catena Danielis Barbari. In Catena Corderii perperam tribuuntur Georgio.
footnote 30 Act. IV. 31 I Cor. 11, 6 et seqq. 32 Jerem. XII, 5. Zach. XI, 3. 33 I Joan. 11, 23. 34 Matth. X, 40. (71) Τέσσαρα γένη τῶν, etc. E codice Baroccia-no, et schedis Combeﬁsii. Latine exhibet Barbarus in Catena, postremam autem hujus fragmenti parent, vel ipse propheta. A Diapsalmate autem ﬁi personæ mutatio: Christus enim est, ut infra ostendetur, cum singulas voces expendemus. Nec mirum si in uno psalmo non una est persona quæ loquitur. Hoc enim pluribus in locis videre cst, nt infra ostendemus. Interim hæc pro exordio psalmi dicta sint, nunc ipsa verba discutiamne.
footnote 35 Psal. CXLVI, 1. 36 Psal. 1, 6. 37 Psal. LXVIII, 22. 38 Psal. XXI, 19. 39 Psal. XVII, 45. 40 Isa. LII, 13. (72) Δοκεῖ μοι, etc. E schedis Grabii et codice Coisliniano.
footnote ⁴1 Jon. III. 42 Ps. VI, 1. (73) Οἱ λόγοι τῶν ἀπειλῶν, etc. E codice Barocciano, et e Catena Corderii. Eatine exstant in Catena Barbari.
footnote 43 I Thess. 11, 16. 44 Joan. XVII, 6. 45 ibid. 10. 46 I Cor. IV, 21. 47 Ps. LXXXVIII, 33, 34. (75) Τὴν κληρονομίαν, ete. E schedis Grabii. (76) Καὶ παρὰ τῷ Ἀπεστό τῷ, etc. E codice Barocciano. et schedis Combeﬁsii. Latine exstant aped Barbarum.
footnote 48 Isai. XI, I et seqq. 49 Ps. L, 19. 50 Isai. LXV, 11. 51 Ps. LXXVII, 31. 52 Jerem. IV, 2.
footnote (78) Οὐκ ἀλλότριον μέν, etc. E schedis Combeﬁsii, et codice Barocciano. Latine habes in Catena Barbari.
footnote 5⁴ Isai. IX, 5. 55 Jerem. X, 24. 56 Mich. VII, 9. 57 Math. XII, 41, et seqq. 58 Prov. VIII, 10. (79) Δόξει μέν τισιν, etc. Ibidem hæc reperiuntur.
footnote (80) Τὴν μὲν προκοπήν, etc. E cod. Barocciano, et Catena Corderii. Latine exstat apud Barbarum.
footnote 59 Ps. VI, 6. 60 ibid. 8. 61 Ps. LXXXVIII, 21 et seqq. 62 Isai. XVI, 5. (81) Εἰ καὶ δεύτερον, etc. Codex Roe 4, Daniel Barbarus. (82) Δοκεῖ ὁ ψαλμός, etc. Codex Baroccianus, Corderius, Barbarus.
footnote 63 Joan. V, 27. 6⁴Jerem XXIII, 4. 65 II Reg. XV, 11. 6⁶ Joan. XIX, 15. (83) Ὅσον ἐπὶ τῇ λέξει, etc. Cod. Anglic., Roc 4, Coislinianus, Barbarus.
footnote 67 Psal. XXXIII, 20. 68 Philipp. II, 9. 69 Philip. III, 19. 70 Reg. II, 30. (84) Ἐὰν μὲν ὁ Δαυῒδ λέγῃ, etc. Codex Baroccianus et Daniel Barbarus.
footnote 71 Joan. VII, 37. 72 Rom. VIII, 15. 73 Habac, 1, 2, et seqq. (85) Ἄξιον ζητῆσαι, etc. Codex Baroccianus, patimque Corderius. Latine exstant apud Barba-rum.
footnote 74 Prov. IX, 4. 75 PsaI. XIX, 7. 76 I Cor. XV, 20, 51. 77 Job. III. 78 Gen. XLVII, 30. 79 Matth. XXVII, 52. 80 I Cor. XV, 20. (86) Ἡμεῖς μἐν ἡγούμεθα, etc. Indidem.
footnote 81 Dan. XII, 2. 82 Prov. VI, 4. 83 Psal. LXXV, 6. 84 Ephes. V, 14. 85 Psal. LVII, 5. 86Job. III, 11. 13, 14, 15.
footnote 87 I Petr. III, 19. 88 Psal. XXVI, 3. 89 Gal. IV, 16. 90 Psal. CXXXVIII, 21. (87) Πρέπουσα ἁγίῳ φωνή, etc. Corderius, codex Baroccianus, schedæ Combelisii, Barbarus. (88) Τῷ Ἑβραῖκῷ ἐντυχύντες, etc. Codex Baroc. Barbarus, partimque Corder. Plurima autem iisdem fere verbis exstant apud Euseb.
footnote 91 Joan. XV, 2 92 Luc. XIII, 28. 93 GaI. V, 19. 94 Psal. LXVII, 21. 95 Psal. CXLV, 3. et Corderius Origeni tribuunt, quanquam similia aut eadem saltem quoad sensum reperiuntur apad Easebiun.
footnote 96 II Cor. IV, 8. (91) Τὸ λέγον πρόσωπον, etc. Codex Baroccianus, Barbarus. Exstat etiam in codice Roe 4, sed mancum et mutilum.
footnote 97 Isai. LVIII, 9, 98 Joel. II, 32. 99 Jerem. XV, 1. 1 Psal. XCVIII, 6, 7, 8. 2 Psal. CXLIV, 18. 3 Matth. VII, 21. 4 I Cor. I, 30. (92) Ἕοικεν ἡ θεία Γραφή, etc. Schedæ Combefisii, codex Roe 4, Daniel Barbarus.
footnote 5 Psal. XXXIII. 20. 6 Psal. XXXI, 10. 7 Prov XIII. 2. 8 Psal. LXXXVIII, 31, 32, 33, 9 II Cor. IV, 8. 10 II Cor. VI, 12. 11 II Cor. VI, 13. 12 Joan. V. 27. 13 Psal. LXXXI, 6. 7. (93) Τὸ, Υἱοὶ ἀνθρώπων, etc. Cod. Roe. Baroccianus, schedæ Combefisii, Barbarus.
footnote 14 I Cor. III, 3. 15 Psal. XXXV, 7. 16 Psal. XLVIII, 2. 17 I Cor. XV, 47. 18 Psal. IV, 4.
footnote 19 I Joan. II. 20 Exod. XIV, 15. (94) Μεγάλη φωνή, etc. Schedæ Combefisii, et Grabii, codex Coislinianus, Daniel Barbarus. (94·) Vide Millii Nov. Testam. Matth. VI, 25. (25) Ἡ « ὀργίζεσθε, » φωνή, etc. Codd. Barocc. Roc, schedæ Combefisii, et Daniel Barbarus.
footnote 22 Psal. LIX, 4. 5. 6. 23 Genes. XXVII, 38. 24 Psal. XLIX, 7 et seqq. 25 Psal. I, 18. 2⁶ Jerem. VI, 20. 27 Jerem VII, 22 et seqq. (97) Ὁ ἐξ ἀδίκων πόρων, etc. Corderius, Barbarus, Codex Bareccianus et Roe 4.
footnote 28 Matth. XII, 6. 29 Osee. VI, 6. 30 Hebr. VIII, 5. 31 Psal. CXXX, 3, 32 Psal. CXIII, 9. 33 Psal. XC, 4. 34 I Cor. XIII, 5.
footnote 35 I Cor. II, 9. 36 I Cor. II, 16 et 12. 37 Matth. XXIV, 45. 38 Ps. CVI, 43. 39 Ps. XIV, 1. (98) Οἱ μὲν ἀπλούστεροι, etc. Codd. Roe, Barocc., schedæ Combefissi, Daniel Barbarus.
footnote 40 Matth. XXV, 2. 41 Luc. VI, 46. 42 Exod. XV, 26. (3) Legendum, ἀγαθός. (4) Leg. γραμμάτων.
footnote 43 Deut. XXVIII, 58 et seq. ⁴⁴ Levit. XXVI, 16. 45 Deut. XXXII, 24. 46 Levit. XXVI, 3 et seq. 47 Deut. XXVIII, 1 et seq. 48 ibid. 16 et sqq. (5) Biblia Græca, πιστάς.
footnote (10) Leg. συμπόσιον. (11) Leg. ἐρήμοις.
footnote 50 Job. XI, 3. 51 Rom. VIII, 28. 52 Ps. XIV, 5. 53 Ezech. XVIII, 8. 54 Prov. XIII, 8. 55 ibid. 56 Isai. I, 6. (12) Ἄρα δέ. Leg. ἄκαιρον δέ. (15) Leg. τάδε τινὰ συμπτώματα γεγονέναι, πῶς ἂν αὐτῷ κακὰ λέγοιμεν ὑπάρχειν.
footnote 58 Ezcch. xxviii, 15. 59 Isai. xiv, 12. 60 Rom. ix, 10. 61 Job. ii, 10. 62 Mich. 1, 12.
footnote 63 I Iosn.I, 5. ⁵¹ Iob. vu, 29. (14) Ὅτι φῶς ἐστιν ὁ Θεός, etc. Curderius, codex Baroccianus,
footnote 5 Psal. LXVI, 1. 66 Psal. LIX, 6. 67 Ezech. IX, 3 et seqq. 68 Psal. CIII, 15. (15) Συνάδει τοῦ στίχου, etc. Codex Baroceiahus, Daniel Barbarus.
footnote 18 Χρὴ ἡμᾶς ἐννοεῖν, etc. Barbarus, Corderius rius, et schedæ mss. Ernesti Grabii. (19) Ὁ ἀποθέμενος, etc. Schedæ Grabii, Barbarus, Larus.
footnote I Cor. VI, 19. (20) Ἅμα τῷ ἀνατεῖλαι, etc. Corderius, Barbaus, codd. Roe, Baroccianus, et schedæ Combeti- (21) Τοὺς μέν ἐν τῇ πολιτείᾳ, ete. Daniet Bar. arus, schedæ Combetisii, ct codd. Anglicani.
footnote (26) Αἰών ἐστι σύστήμα, etc. Schedæ Grabil, Barbarus. (27) Εἰ κρείττους, etc. Cordetius, codd. Roe, et Baroccianus.
footnote 73 Isa. LII, 6. 74 Exod. XXXIII, 15. 75 Prov. IV, 9. (28) Ταυτόν ἐστι τῶν, etc. Corderius, partimque Barharus. (29) Ὑπέρ τῆς ὀγδόης, etc. Codex Coislinianus. (30) Θυμός ἐστιν, etc. Corderius, partimque Bar-barus.
footnote 76 Joan. xiv, 6, 77 Psal. liv, 16 78 II Cor. v, 4 79 Psal. xxxvii, 9. 80 Luc. vi, 21. Ephes. iv, 22. Coislinianus, Barbarus. (36) Οὐδέν οὕτω, etc. Corderius, codex Coislinianus, Barbarus. (37) Δαιμόνων τό, etc. Schedæ Grabii, Barbarus.
footnote 82 Psal. III, 3. (38) Ὁ τῶν κλαιόντων, etc. Corderius. (39) Ἡ αἰσχύνη, etc. Schedæ Grabi, Barbarus. (40) Ἐὰν τακήσωμεν, etc. Schedæ Grabi, Babarus.
footnote 56 Joan. XII, 32. (50) Ὅταν οὐκέτι, etc. Corderius, Barbarus. (51) Μήποτε παρασεσιωπημένως, etc. Codex Coislin. (52) Σκεύη θανάτου, clc. Schedæ Grabii. (55) Ὁ μὴ φιλόθεος. Codex Coislin. et Corde-rius.
footnote 87 Cen. IX et XLIX. 88 Psal. CXXVII, 3. Psal. oa t5. Eccles. II, 4. Prov. III, 10. 92 Matth. XXI, 9. ibid. 16. dæ, et Barbarus. (60) τι ὄψομαι. Corderius. Barbarus, codd. Baroccianu, et schedæ Combeﬁsii.
footnote 94 Psal. LXXXVIII, 35. 95 Οsee. IV, 14. 96 Hebr. II, 9. 97 I Petr. v, 4. 98 Psal. XLVIII, 13. 99 Ephes. II, 6. (61) Εἰ θαυμάζων, etc. Corderius, Barbarus, schedæ Combelisii, codex Broccianus. (62) Καὶ αὐτὺς γὰρ σου, etc. Cordeius. Barbarus. (63) Κούφιά ἐστι, etc. Schedæ Grabi, et rus.
footnote (68 Θρόνος μὲν Θεοῦ, etc. Schedæ Grabii. (69) Τὸ, Ἐπετίμησας, etc. Corderius, Barbarus. schodæ Combeﬁsii, et codex Baroctianns. (70) Εἰ τὸ ὄνομα, etc. Schedæ Grabi.
footnote 4 Mauh. XI, 5. (71) Οἱ ἐκζητοῦντες, etc. Corderius. (72) Ἐκεῖνος ψάλλει, etc. Schedæ Grabii, partimque Corderius et Barbarus. (73) Ποῖα ἐπιτηδεύματα, etc. Schedæ Grabii.
footnote ⁵Joan. Iν, 24. 6 Psal. LXX, 5. 7 Galat. IV. 8 Psal. LXXII, 27. ⁹ Jerem. XXIII, 23. 10 II Τim. III, 15. 11 Psal. LXXII, 12. schedæ, et Barbarus. (81) Τίς; πότερον ὁ Κύριος, etc. Eædem scbedæ. Barbarus. (82) Ὁ μὲν δίκαιος, etc. Eædem schedæ, el Βarbarus. (83) Τῶν πειρασμῶν, etc. Eædem schedæ, et Βarbarus.
footnote 12 Psal. ΧΧ, 12. 13 Job. I, 7. Prov. XVIII, 17. Prov. Πα, 9. Psal. CXXXVIII, 22. (86) Ὁ τῆς ἀγιότητος ἐκπεσώγ, etc. Corderius. (87) Ἐν γὲν τοῖς ἔχοθσι, etc. Schedæ Grabii,et Barbarus.
footnote 19 II Cor. V, 10. (93) Μὴ ἀρκούμενοι, φησὶ, τῇ, etc. Corderius, et Barbarus. (94) Τόξον ἐστὶν ἀκάθαρτος νοῦς, etc. Schedæ Grabii, et Barbarus.
footnote 21 Rom. VII, 24. 22 II Cor. VI 10. 22 ibid. 24 II cor. v, 4. 25 Rom. VII, 24. 26 Psal. XXXIII, 11. 27 Psal. LXXVIII, 8. 28 II Cor. VIII, 9. 29 Hebr. 1, 2. 30 Cor. XII, 28. 31 Act. XX, 28. (5) Καὶ ὁ Φαραώ, etc. Schedæ Grabii. (6) Ὡς ὁ Παῦλος ἔφη, etc. Schedæ Grabii, Barbarus. (7) Καὶ ἄλλως δὲ τῶν, etc. Catena collegii novi Oxoniensis, Barbarus.
footnote (12) Φωτίσατε ἑαυτοῖς, etc. E codice Anglicano hæc exscripsit Grabius. (13) Ἐπιχαίρουσι γὰρ πίπτουσι, etc. Ε Catcna collegii nov Oxoniensis.
footnote 34 Isa. LVIII, 9. Jacob. v, 13. Luc. XVII, 10. 37 Isa. LIX, 20. (14) Ἐκεῖνοι μὲν ἐπιχαίροντες, etc. Schedæ Grabii. (15) Ὁ εὐεργετηθείς, etc. Schedæ Grabii. (16) Εἰ ἐν τοῖς ἐπιτηδεύμασι, etc. Schedæ Grabii. (17) Οἱ λέγοντες, etc. Schedæ Grabii, et Corderus.
footnote 88 Isa. LII, 10. 89 Psal. XCVII, 2. 40 Psal. LXXXIV, 8. 41 Psal. CXIX, 5. lgit Dominus brachium surm sonetum in conspetu omnium centium, et cognoscent omnes ﬁnes terræ satutare Dei ostri. Omnibus igitur gentibus revelatum est, et ab omnibus cognitum est. Et rursum in Psalmis Spiritus sanctuis exclamat: Camare Domaao canticum novum, quia mirabilia fecit. Ostendit Domnus salutare subm, in conspectu gentium rerelert justitiam suam. Et rursum: Annuntiate in genuibas gloriam ejus, et ln omnibus populis salutare ejus. ἐt rursum : Ostende nobis, Domine, misercordiamæ tuam, et salutare tuum da nobis. » (21) Πολλὰ παρῴκησεν, etc. Schedæ Grabii. (22) Ὄρος ἅγιόν ἐστιν, etc. Eædem. (23) Τὸ, πορευόμενος, etc. Schedæ Grabii, ac Barbarus, partimque Corderius.
footnote 42 Job. II, 10. (24) Ὁ κατὰ τόν, etc. Codex Anglicanus. (25) Ὡς καὶ οἱ διάκονοι, etc. Codex Coislinianus. (26) Ὡς πολεμίων, etc. Corderius, et codex Coislinianus. (27) Εἰ ἀγαθὰ πᾶσαι ἀρετὶ, etc. Schedæ Grabii.
footnote γει, ete. Didymo tribuit Barbarus, at Corderius Origenis quoque nomine nonnulla ex his inscripsit.
footnote 45 Joan. ΧΧXΙΙΙ, 34. ⁴⁶ Jocl. II, 28. 47 Psal. VII, 10. (30) Κληρονομία φύσεως, etc. Schedæ Grabii, partimque Barbarus, et Corderius. (31) Εἰ τὸ σχοινίον, etc. Schedæ Grabii, Barbarus Barba-rus.
footnote 48 Rom. X, 10. 49 Psal. III, 4. 50 II Cor. III, 17. 51 Job. X, 11. 52 Act. II, 27. 53 Isa. LXIII, 1. (36) Exstat hoc fragmentum in Apologia Pataphili martyris pro Origene.
footnote 54 Joan. III, 18. 55 Matth. VII. 13. (37) Πᾶς ὁ δίκαιος, ete. Corderius, et schedæ Grabii. (38) Εἰ πᾶσαν τὴν κρίσιν, etc. Schedæ Grabii Origeni tribuunt, Corderius Eusebio. (39) Ἐπείπερ ὁ πιστεύων, etc. Codex Roe. (40) Περὶ τῆς ἀποκαταστάσεως, etc. Codex Rue.
footnote Coislinianus, num. 189; alter vero num. 10, Eusebio tribuit. (48) Στέαρ μέν νοητόν, etc. Codex Coislinianus Theodoreto tribuit, alii Origeni.
footnote 57 Eccle. x, 4. 58 Ephes. iv, 27. 59 Job. ix, 34. (49) Ἔνδον ὄντας. etc. Codex Roe. (50) Τοῦτον κυκλοῦσιν οἱ δαίμονες, etc. Codex Coislin., 10 (51) Ἐν ἀποκρύφοις, etc. Codex Roe.
footnote (59) αὐτοϊσχύς, etc. Corderius. (60) Διὰ τοῦ ὁμοίου, etc. Schedæ Grabii, et barbarus. (61) Στερέωμα εἶπε, etc. Eædem schedæ, et barbarus.
footnote »61 Luc. I, 69. 62 I. Reg. II, 10. 63 Joann. X, 27. (62) Βοηθὸν εἶπε, etc. Schedæ Grabii. (63) Ὑπερασπιστὴν ἔφη, etc. Eædem schedæ. (64) Ὁ μετὰ τοῦ ὑμνεῖν, etc. Codex Roe. (65) Ὁ Χριστὸς, etc. Codd. Coislinianus ct Roc. Corderius sutem habet tanquam anonymi. (65) Ὠδῖνες θανάτου, etc. Schedæ Grabii.
footnote 64 Ps. XXXIII, 17. 65 Ps. IV, 7. 66 Isai V, 6. Amos VIII, 11. (73) Ὀ Φεὺς ἐν μὲν τοῖς ἀγίοις, etc. Schedæ Grabii, et cooex Coislinianus, num. 10. (74) Ἐπειδὴ ἔθετο σκότος, etc. Codex Coislinianus, num. 10, et schedæ Grabii.
footnote 68 II Cor. V, 16. 69 Ps. LXXIX, 9. 70 Jcrem. II, 13. (75) Ὅλα ὲκεῖνα, etc. Corderius. (76) Ὅτετ τὰ πνευματικά, etc. Schedæ Grabii, et Barbarus.
footnote 71 Matth. v, 8. 72 Luc. X, 19. 73 Ps. IV, 2. 74 Ps. CXL, 2. 75 IIebr. IV, 15. (80) Οἱ θλιβόμενοι, etc. Corderius. (81) Ὁ ἐπαίρων ὁσίους, etc. Codex Roe. Corderius autem anonymo tribuit. (82) Καθαρειότης ψυχῆς, etc. Schedæ Grabii, et Barbarus.
footnote 76 Matth. VI, 23. 77 Joan. XIV, 6. Ps. XVII, 31. 79 Matth. VII, 2. 80 Ps. CXVIII, 17. 81 Levit. XXVI, 27, 28. (83) Χωρὶς Θεοῦ, etc. Codex Roe. Corderius vero tanquam incerti habet. (84) Ἄμωμός ἐστιν, etc. Schedæ Grabii, Barbarus. (85) Ἐν ᾧ μέτρῳ, etc. Schedæ Grabii, Barbarus.
footnote 82 Joan. XIV, 6. 53 Luc. XXIV, 52. 84 Rom. XII, 11. 85 Luc. XII, 49. (92) Κατὰ τοῦτο τὸ σημαινόμενον, etc. Schetæ Grabii Origeni tribuunt, sed Corderius habet tanquam incerti aucloris. (93) Καταρτίζονταὶ τινος, etc. Schedæ Graba. codex Coisinianus, Barbarus.
footnote 86 Ezech. XVI, 56. Psal. cxv, 16. (94) Ὁ χαλκὸς σύμβολόν ἐστι, etc. Schedæ Grabii, codex Coislinianus. Barbari Catena. (95) Ὁ ἐν δεξιᾷ καθήμενος, etc. Schedæ Grabii, coedex Coislinianus, Catena Barbari. (96) Εὺφόρως ὑπομένοντος, etc. Schedæ Grabii. (97) Ὁ ἱκανωθείς, etc. Codex Roe.
footnote 88 III Reg. XVIII, 21. 89 Rom. XII, I9. 90 Luc. X, I9. Psal. CI, 27. 92 I Reg. κ. 50. (8) Ἕως πότε, etc. Schedæ Grabii, et codex Barbarus. (11) Εἰ οἱ οὐρανοί, etc. Codex Coislimanus, schedæ Grabii, Barbarus.
footnote 93 Joan. XII, 31. 94 ICor. II, 10. 95 Joan. VI, 69. 96 ibid. 63. 97 ibid. XIV, 10. 98 ibid. 99 II Cor.V, 19. (15) Ὁ Κύριος ἡμῶν, etc. Schedæ Grabii, BarBarbarus Didymo tribuit. (16) Εxstat hoc fragmentum in Apologia Pamphili marlyris pro Origene.
footnote (2Ο) Ἁγνεία ἐστίν, etc. Schedæ Grabii, Bararus. (21) Εἰ ὁ δοῦλος, etc. Corderius, schedæ Grabii, Arbarus.
footnote (29) Σωτήριόν ἐστ Θεοῦ, etc. Corderius. (30) Ἀλλʼ οὐ τὰ κακά, etc. Schedæ Grabii. (31) Ἐπακούει γάρ, etc. Schedæ Grabii. (32) Οἱ μὲν ἀντικείμενοι, etc. Codex Coislinianus schedæ Grabii, Barbarus. (33) Εἰ Χριστός, etc. Corderius.
footnote 6 Matth. vii, 6. 7 Gen. ii, 7. 8 ibid. i, 24. 9 Joan. xiv, 6. 10 ibid. xii 23. 11 Ephes, ΙΙ, 12. (38) Ὁ βασιλεύς, etc. Corderius. (39) Τὸ σωτήριον, etc. Schedæ Grabii. (40) Ἡ δόξα, etc. Part m Corderius partimque schedæ Grabii. (41) Οἱ μέν ἐχΘροί, etc. Codex Coislinianus, schedæ Grabii.
footnote (46) Διὰ πάντων οἱ φαῦλοι, etc. Schedæ Gra bii. (47) Μωτὰ τίθεσθαι, etc. Codex Coislinianus Eusebio tribuit, Corderius anonymo, schedæ Grabii Origeni. Certe in Eusebii commentariis in Psalmosnihil simile reperitur. (48) Εἰ δύναμις Θεοῦ, etc. Cordetius.
footnote 14 Ezech. xxxi, 9. 15 Gen. xxv, 25. (49) Αὕτη ἡ φωνή, etc. Corderius, qui et silia fere habet sub nomine Gregorii Nazianni. (50) Ὡς ἔλεγε, etc. Codex Coislinianus, et sche Grabii.
footnote 19 Jerem. 1, 5. 20 III Reg. VIII, 46. (57) Ἀνάγοις δὲ ταῦτα, etc. Schedæ Grabii, partimque Corderius apud quem incerto auctur tribuuntur. (58) Ζητήσεις δέ, etc. Schedæ Grabii.
footnote 21 Joan. XIX, 30. 22 Psal. VI, 3. 23 Luc. 11, 35. 24 Math.αν, 26. » Psal XXXIII, 3. Grabi, partimque Corderius, et codex Coislinianus, (63) 7ὰ ἐκ τούτου, etc. Codex Coislinianus, schedæ Grabi. 64) αῦτα οθονεί, cic. Corderius. 65) Ἐν τῷ Κhρῳ, etc. Codex Coislinianus.
footnote 26 Joan. vI, 41. 27 Eccles. 1, 4. 28 Prov. XXI, 4. 29 Isa. ΙX, 2. codex Coislinianus, Barbarus. (71) Εἰ ἔστι τρίβος, etc. Schedæ Grabii. barus. (72) Ἐντεῦθεν ὁ λόγος, etc. Codex Barocciamis Barbarus. (73) τι ὁ ῥάβδος, etc. Codex Barocciamis, Barbarus.
footnote 30 Psal. LXXXXVIII, 31 et seq. 31 Hebr. XII, 6. Psal.LXII, 2 et seq. 32 Prov. XIII, 24. 34 Rom. v, 3. (75) Τί θούλετα, etc. Codex Baroccanus, partimque Corderius.
footnote 35 Luc. XXII, 29. 36 Cor. 1, 9. 27 Psal. CXL, 5 38 Joan. XV, 14. 39 I Cor. I, 30. (76) Πρότερον μέν, etc. Schedæ Grabii, codex Coisdinianus. (77) Τίς ἐστιν, etc. Corderius.
footnote Joan. 1,16. ⁴¹ Psal. XIV, 1. 42 Philipp. III, 13. 43 Exod. xxxiv. 44 Psal. xxxix, 3. 45 I Cor. x, 4. (8) Ὅρα δὲ καὶ οὔτως, etc. Schedæ Grabii, Barbarus. (9) Πρὺ τῆς καὶ οὔτως, etc. Corderius,Barbarus. (10) Σύγκρινον δὲ ταῦτα, etc. Partim Corderius, et schedæ Grabii, ac Barbarus.
footnote 46 Exod. XXXIII, 20. 47 Matth. XVIII, 10. 48 Psal. CXVII,19. nus. Apud Corderium vero et in codice Roe ?? ribus vertis habentur. (85) Εἰ ἀγγέλων ἐστὶ τὸ βλέτεαν, etc. Codex Coisdnianus, et schedæ Grabii. (86) Πύλας δὲ λέγει, etc. Codex Cuisdinianus, schedæ Grabii, partimque Barbarus.
footnote 49 Joan. XVI, 33. 50 Joan. XI, 31. 51 Joan. 1, 3. 59 I Cor. IX, 21. bii, Darbarus. (92) Ὁ θέλων γνῶνα, ete. Schedæ Grabi, et codex Coislnianus, ac llarbarus. (93) Ἐφʼ οἰς γὰρ ἔτι. etc. Schedæ Grbii, partimque Corderaus. Nonnulla tamen iisdem fers verbis habent Eusebius, et lhdymus in Catena Barbari.
footnote (96) Ὁ πάντα πράττων, etc. Codex Coislinianus schedæ Grabii, Barbarus. (97) οὐ πᾶς κόπος, etc. Codex Coislin., Schedæ Grabii, Barbarus.
footnote 55 Joan. XIV, 6. (98) Ἡ ἐλπίς, etc. Schedæ Grabii, et codex Coislinianus. (99) Nεφροὶ μέν, etc. Codex Coislinianus. (1) Ὁ νοῶν, etc. Corderius. (2) Εἰ ἡ ἀ λἡθεια, etc. Codex Coislinianus, scheAuæ Grabii, Barbarus.
footnote VIII, 35. 59 Joan. XIV, 6. 60 II Cor. I, 8. ⁶¹ Apovertis. Coislinianus num. 189. Verum nonnulla iisdem fere exstant apud Eusebium. (9) Ὄτε πειραζόμενοι, etc. Codex Coislinianus 189.
footnote 62 Joan. VI, 55. 83 Isai. 1, 19, 20. 64 Gal. V, 19. (10) Εἰ ἡμεῖς τὰς τοῦ Χριστοῦ, etc. Schedæ Gra-ii. codex Coislinianus, Barbarus. (11) Ἡ παρεμβολή, etc. Corderius. (12) Ὁ μὲν πρακτικός, etc. Schedæ Grabii, codex
footnote (14) Σκηνὴν τὸν Χριστόν, clc. Schedæ Grabii, codex Coislinianus. Barbarus.
footnote 65 Psel. XVIII, 6. Job. I, 19. (15) Εἰ ὁ κυκλώσας, etc. Schedæ Grabii, Barrus. (16) Ὅταν τὸ πρόσωπόν τινος, etc. Corde- Corderius, Barbarus. (17) Διʼ ὧν καθαίρει τις, etc. Schedæ Grabii. (18) Μακάριος ὁ ἐγκαταλειφθείς, etc. Eædem
footnote 67 PsaI. XXIII., 6. 68 Jerem. 11, 13. 69 PsaI. cvm, 4. 70 Luc. XII, 40. Rom. XII, 29. 73 sai. LXI, 1. (22) Τῶν πρὸς τέν Θεόν, etc. Codex Daroccianus, partimnque Catena Corderii; Origeni ?? ascribil Daniel Barbarus.
footnote 74 ITi. n, 1. Εsod. XVa, 11. sI Tim. n, 8. ¹ Psal. cxi, 2. (23) Εἰ ναός ἐστιν, etc. Schedæ Grabii, et codex Coislinianus. (24) Ἐμοὶ δοκεῖ δυιφέρειν, etc. Codex Baroce. Catena Barbari.
footnote (29) Ἕργα μὲι Κιρίου, etc. Schedæ Grabii Coislinianus. Similia fore habet Euse bius.
footnote 79 Act. VII, 50. 80 Luc. III, 6. (30) Σάρκα μέν ὠνόμασε, etc. Codex Coislinus, schedæ Grabii, partimque Catena Barri. (32) Aὐτὸς ὁ Χριστός, ete. Codex Roe. (33) Παλλος ὁ ὅγιος, etc. Codex Roc, Barba· barus.
footnote (40) Ὅτι ἐκ προσώπου, etc. Godex Bsreccia?? Catena Barbari. (41) Ταῦτα μέν οὗν, etc. Catena Barbari, Baroccianus.
footnote 87 Ps. XXI, 2. 88 Ps. LXVIII, 6. 8, Deut. XXXII, 4. 90 Matth. XXV, 21 91 Matth. XII, 35. Joan. XIV, 6. 93 Prov. XVIII, 21. (42) Ἐαεὶ οὐχ ὡραῖος etc. Codex Daroccianus. (45) Ὥσπερ ἐκ τοῦ λεγομένου, etc. Eædem schedæ. (43) Τάχα δὲ καὶ τούς, etc. Schedæ Grabii. (44) Πᾶς ὁ μσυνημένος, etc. Eædem schedæ. derii.
footnote Grabii, sed vereor ne quid ex Basilio hic inserium fuerit : nisi malis ditere Basilium ex Origene ?? esse mutuatum. Vide Barbari Catenam. (51) Ὁρῶν μηδέν ἅξιον, etc. Catena Corderii, et codex Coishmmanus 189.
footnote (52) Οὐ δοξάσει, etc. Schedæ Grabii, partimque fx Coilintanus votus. (53) Λέγοι δʼ ἄν ταῦτα, cte. Schedæ Gabli. Siautem uiduam hbet Clena Barbari.
footnote 29 Ι Cor. II, 12. 1 Eccl. 1, 2. nianus num. 189, partim Catena Corderii. (61) Νῦν τὸ πνεῦμα, etc. Codex Coislinianus, Catena Barbari. (62) Εἰ οἱ ἁμάρτωιοί, etc. Schedæ Grabii, partimque vetus codex Coislinianus. Latiue Omuia habet CAtena Barbari. (63) Οἱ λόγοι, etc. Schedæ Grabii.
footnote 9 I Cor. VI, 18. (64) οὐδέν οὕφω, ctc. Eædem. (65) Κλῆροι τῶν δικαίων, etc. Codex Coislinia- Catena Barnari. nus, Barbarus, et schedæ Grabii, (66) Φεύγετε τὴ πορνείαν, etc. Iidem mss. et Babarus. (67) Εὐεργετεῖται, etc. Schedæ Grabii. (68) Ὥσπερ τὸ πρόσωπον, etc. Eædem schedæ, et Βarbarus.
footnote bii, et Gatena Barbari. (79) Κλθάρα ἐστί, etc. Schedæ Grabii, codex Coislinianus, partimque Barbarus et Corderius. (80) Ὁ κατὰ τὸν ἔσω, etc. Schedæ Grabii, et Catena Corderii. (81) Ἀντὶ τοῦ, etc. Codex Coislinianus. (82) Ἀγαπᾷ ἐλεημοσύνην, etc. Catena Corderii.
footnote ⁵ Psal. XVIII, 19 et XXXV, 7. 6 Joan. VII, 24. 7 Matth. v, 45. 8II Cor. v, 17. 9 l Tim. 11, 4. (85) Οἱ λδγοι, etc. Schedæ Grabii, codex Coislinianus, et Catena Barbari. (84) Τοῦτο ἐν τῇ παρουσίᾳ, etc. Catena Corderii. (85) Σάλος ἐστίν, etc Codex Coislinianus, et sche læ Grabii. (86) Ἡ μὲν γένεσις, etc. Codex Coislinianus.
footnote 13 Hebr. XI, 37, 38. (96) Ὁ ἄγγελος, etc. Iidem mss. (97) Εἰ γευστός ἐστιν, etc. idem uiss et Catena Barbari. (98) Εἰ οὐκ ἔστιν, etc, lidem mss. et Catena Barbari. (99) Παρὰ τοῦ, etc. Istud necnon sequentia fragmenta exhibent sehcdæ Grabii, et codex Coisli nianus.
footnote 14 Psal. L, 19. 15 Sap. v,18. Isa. 11, 4. (1) Εἲδὼς, ὄτε, etc. Catena Corderii. (2) Οὑδὲν οὔτως, etc. Codex Coislinianus, sche-
footnote (9) Νομίξω περὶ τοῦ, etc. Codex Coislin partimque Catena Barbari.  Ἐντεῦθεν, etc. Codex Colslinianus. (11) Ἄτεκνός ἐστι, etc. Schedæ Grabii, et catena Barbari. (12) Οὐδέν οὕτω, etc. Schedæ Grabii et codex Coislnianus, partiæque Catena Barbari
footnote 18 Gen. III, 5. 19 2. Cor. 7. 20 Mich II, 1. (13) Ἑλεῖν οὐ δυνηθέντες, etc. Catena Corderii, (14) Τῷ δικαίῳ, etc. Codex Coislinianus. (15) Ἔσεσθε γάρ, etc. Partim ex eodem codice, Bartim e schedis. Grabii. (16) Καὶ ὁ Παῦλός φησι, etc. Ex eodem codice, et hedis Grabii. (17) Οἱ μὲν εἰς Χρστόν, etc Ex codem codice.
footnote 24 II Tim. 13. sequentia fragmenta. (25) Ἐνταῦλθα ξῆλον, etc. Codex Coisdiniamus. (26) Πῆς ὁ φαῦλα, etc. Catena Gorderii. (27) Ἡ ὑποταγὴ αὔτη, etc. Schedæ Grabii.
footnote 25 Rom. 1, II. 26 Joan. VI, 41. (28) Θυμός ἐστιν, etc. Eædem schedæ. (29) Τὸ ἐξολοθρευθῆναι, etc. Eædem. (30) Ἀμφίβσλος ἡ Δέβις, etc. Catena Corderii. (31) Τόπος, etc. Scbedæ Grabii. (32) Ἡ γῆ νῦν, etc. Eædem. (33) Κρεῖισσον ὀλίγη, etc. Eædem.
footnote 7 Psal. CXLI, 3. 75 Abd. 16. Rom. LV, 17. 77 Psal. LXII, 9. 78 Joan. v, 30. ἐτρύφα χρόνον, εἰς ἁμαρτίας ἐξώλισθεν. Assimilatur araneæ propter fragilitatem quidquid peccator texit, quantumvis tenue, quantumvis varium exsistat, juxta illud Isaiæ: Telas araneæ texunl. Increpans igitur eum qui docebat, ait: Plagas et manum tuam intu etc. listi, et tabescere fecisti animam ejus, quam attenuasti, ob utilitatem ejas propriam. Nam quando deliciis fruebatur, in peccatum impingebat.
footnote (82) Πρὸς τὴν τῶν ἀγαθῶν, etc. Catena Corde rii. (83) Τί ἐστιν ὁ συνιών, etc. Catena Corderii.
footnote  82 Psal. XXIX, 12. 83 Marc. IV, 11. 84 I Cor. v, 13. (84) Κλίνη ὀθόνης, etc. Codex Coislinianus. (85) Οἱ ἀόρατοι, etc. Catena Corderii. (86) ΟI ἀφανεῖς, etc. Eadem.
footnote (92) Τροφιμώτατός ἐστι, etc. Schedæ Grabii. (93) Ὁ Θεὸς μέν, etc. Eadem.
footnote 87 Luc. xv 7,88 Cor. iii, 18. 89 IV Reg. xix, 34. (94) Ἡ μὲν κατὰ Μωσέα, etc. Catena Corderii. (95) Ἰορδάνης κατάβασις, etc. Schedæ Grabii. (96) Ῥαψάκου, etc. Eædem. (97) Τὰ μὲν ἀγαθά, etc. Catena Corderii.
footnote (1) Και ὁ Χριστός, etc. Catena Corderiiel Barbari. (2) Ἐγώ εἰμι τὸ φῶς, etc. Schedæ Grabii, Catena Barbari.
footnote 92 Coloss.III,10. 93 Psal. CII,5. 94 Matth. xv,13. (3) Τὸ ἐξαπεσταλμένον, etc. Catena Corderii. (4) ρος γιιον, etc. Codex Coislinianus. (5) ἔΚφὶ ἐν τῷ, etc. Catena Corderii. (6) ψυχὴ δεάτα, etc. uadeu.
footnote (13) Κέρας ψυχῆς νοῦς καθαρός, etc. Scheδæ Crabii, codex Coshnianus et Catena Barbari. (14) Ὁ μέν μακάριος ἐπαινεῖται, etc. Schedæ Crabti, et Catena Barbari. (15) Ἔμπροσθεν ἡμῶν, etc. Codex Coislinianus, schedæ Grabii et Catena Barbari.
footnote 97 Psal. CXXIII, 3. (16) Οὐ γὰρ πάντα, etc. Catena Corderii. (17) Ταῖς γὰρ ἁμαρτίαις, etc. Codex Coislinianus, odæ dGralm et tCatena Harbari. (18) Οἱ γειταῶντα, Catena Corderii. (19) Ἑαυτοὺς μέν, ete. Codcx Coislinianus, tæ tIrtbii, et Catena Barbari. (20) Τοῦτο λεκτέον, etc. Schedæ Grabii, codex
footnote (28) Λέγοιεν τοιαῦτα, etc. Catena Corderii. (29) Τὸ δὲ, Ἐξηρεὐξατο, etc. Catena Corderii. (30) Λόγος ἀγαθός ἐστιν, etc. Codex Coislinis-nus et Catena Barbari. (31) Κάλαμος γραμματέως, etc. Catena Conherii, (32) Ἐκ τοῦ προφητικοῦ προσώπου, etc. Eaduai Catena.
footnote 95 Matth. IX, 5. (33) Τὴν σοφίαν, etc. Codex Coislinianus et ca-ten(- Burlvri. (34) Αὕτη ἡ ῥομφαία, etc. Schedæ Grabii. (35) Μήποτε ὁ μηρός, etc. Catena Corderii. (36) Οἱ ἀληθεῖς, etc. Schedæ Grabir.
footnote (44) Πλησίον ἡμῶν, etc. Codex Coisliuianus schedæ fGrahii ct catena Barbari. (45) Ἀντὶ Ἀβραάμ, etc. Schedæ Grabi et cater Barbari. (46) Θεὺς μόνος, etc. Catena Corderii.
footnote 1 Psal. XXXIII, 20. 2 Matth. VII, 14. 3 Psal. XLV, 6. (47) Φεύγοντες τὴν πορνείαν, etc. Schedæ Grabii et Catena Barbari. (48) Θαλάσσας καὶ ὄρη. etc. Schedæ Grabii, codex Coishinianus et Catena Barbari. (50) Πόλις Θεοῦ, etc. Schedæ Grabii et Catena
footnote (56) Οἱονεὶ φωνήν, etc. Catena Corderii. (57) Ἐπὶ ταῖς νίκαις, etc. Schedæ Grabii. (58) Ὑπέταξε λαούς, etc. Catena Cordurii.-
footnote 6 I. Thess. Iv, 15. 7 Jacob. m, 13. (59) Ἔδωκεν ἡμῖν , cte. Codex Coislinianus, sctedæ Grabi et catena Barbari. (60) Ὥσπερ ὁ Κύριος. etc. Catena Corderii. (61) Ἐκατέρως τῷ Θεῷ, etc. Eadem Catena. (62) Τῷ κατὰ Θεόν, etc. Schedæ Grabii. (63) Θρόνος μὲν Θεοῦ, cte. Codex Coislinianus.
footnote (71) Ἔξω μέν τῆς πόλεωο, etc. Catena Corderii. (72) Ὅσα διὰ τῆς πίστεως, etc. Codex Coislinianus, schedæ Grabii et Catena Barbari. (73) Ὁ Χρστός ἐστιν, etc. Schedæ Gabii, codex Coislinianus et Catena Barbari. (74) Εὐφραίνηται τὸ Σιών, etc. Catena corderii.
footnote 10 Is. XL., 11. 11 Math. αἱ, 28. (75) Ταῦτα πληροῦται, etc. Catena Barbai et ledæ Grabm.
footnote (81) Ἄνθρωπος οὐ δώσει, etc. Catens Corderii. (82) Ἐπασορηακῶς, etc. Cade coislinianu. (83) Ὁ ἐφʼ ὅλον, etc. Catena Cordert.
footnote 13 Joan. Xν, 6. 14 Cor. I,19. Jerem. ν, 22. (84) Ὁ κοπιῶν, etc. Schedæ Grabii. (85) Ὀψόμεθα τοὺς σοφούς, etc. Eædem schedæ et partim Catena Barb.
footnote 19 Petr. 11, 8. 20 Psal. xv, 10. Psal. XLVIII, 16. 22 Prov. XXVIII, 22. (92) Τοῖς τοῦτον, etc. Catena Corderii. (93) Ἐπαπορητέον ό ἐν τιμῇ, etc. Catena Corderii. (94) Ὁ Θεὸς τῶν θεῶν, etc. Catena Corderii.
footnote 23 Luc. XII, 49. Dan. VII, 10. 25 I Cor. XV, 49. (95) Εἴπερ εὐπρέπεια, etc. Eadem Catena. (96) Ὁ Θεὸς ἡμῶν, etc. Schedæ Grabii. (97) Χριστὸς ἐλήλυθεν, etc. Eædem schedæ.
footnote 26 Rom. VIII, 29, 30. Joan. v, 22. Matth. x, 29, 29 Psal. L, 19. 30 Matth. xv, 8. (5) Οὐ μόνον, etc. Catena Corderii. (6) Ὅτι οὐ δεῖ, etc. Codex Coislinianus et sche-dæ Grabii. (7) Παιδεία ἐστί, etc. Iidem mss. (8) Ἡ μέρις ἡμῶν, etc. Iidem mss.
footnote 31 Matth, v, 16. 32 I Cor. 11, 7, 8; Rom. XVI, 25. (9) Ὁμοίωσίς ἐστιν, ete. Iidem mss. (10) Ἀρπάξεται ψυχή, etc. Iidem mss. (11) Ἐν τῇ θυσίᾳ, etc. Catena Corderii.
footnote (16) Κατʼ ἐνέργειαν, etc. Schedæ Grabii, codex Coislinianus, et Catena Barbari. (17) ᾯ ὀφείλεταί τι, etc. Catena Corderii.
footnote 37 l Cor. 1, 31. 38 Eccli. XXL, 29. (18) Ὁ καυχώμενος, etc. Codex primus Coislinianus. (19) Οὐκ εἶπεν, etc. Caten Corderii. (20) Εἰ ἔστι δυνατός, etc. Codex Coislinianus prinus. (21) Φαῦλον μέν, etc. Coislinianus secundus.
footnote 42 Rom. x, 13 plicere. Non avocat autem ab hominum gratia Deus justorum mentes et ﬁdelium rationabilem sanctitatem. Et audiamus eum per Paulum loquentem : Sine oﬀensione estote Juderis et Græcas, et Ecclesiæ Dei, sicuti et ego omnia omnibus place, non quærens cuod mihi utile nt, sed quod mπultorum est, ut salventur, Icc est non hominibus sed Deo placere, cum per id quod Deo placetur, et homnibus sit placendum. Ex causa enim placendi Deo, causa etiam hominibus probabilis lt placendi. Cæterum stuhum, quod ut hominibus tantum places tur impenditur, ad id quod Deo placendum est, uon refertur : ania tantum eorum causa quibus plaττtur adhibetur, » etc.
footnote 43 I Cor. x, 32, 35. 44 Rom. XI, 26. (33) Ἥξει ἐκ Σιών, ete. Codex Coislinianus. (34) Εὔξεται, etc. Codex Coislianus secundus.
footnote 16. Psal. XLI, 7. Pianus secundus. (40) Ἔχει τι ὅμοιον, etc. Catena Corderii et co-dex Coislinianus.
footnote (41) Πτέρυγές εἰσι, etc. Schedæ Grabii. (42) Ἡ τοῦ φυγαδεύειν λέξις, etc. Codex Cois
footnote (46) Ἐλθέτω δή, etc. Schedæ Crabii. (47) Ἐκεῖνοι εἰς ᾅδου, etc. Codex Coislinianus secundus.
footnote 49 Gen. XLVIII, 15. 50 Hebr. X, 28. Psal. CIII,9. 52 Cen. III, 15. (48) Ἐν μέσῳ υοῦ πρωΐ, etc. Schedæ Grabii. (49) Ἑσπέρας. Catena Corderii et codex Coislianus secundus. (50) Εἰ πάντα δἰ αὐτοῦ, etc. Schedæ Grabii. (51) Ὡς διέθρεψε, etc. Codex Coislinianus sendus. (52) Ὁ Χριστός, etc. Codex Coislinianus secuns.
footnote (64) Τῶν διαβαλλόντων, etc. Eædem schedæ. (65) Ἐὰν ὑψωθῶ, etc. Eædem. (66) Δύναται τοῦτο, etc. Codex Coislinianus se. cundus. (67) Ἐπεὶ ὁ ἐλεούμενος, etc. Idem. (68) Δὶς ἐν τῷ, etc. Idem.
footnote 55 Matth. XXIII, 28. 56 I Cor. I, 30. 57 Psal. LIV, 11. (69) Ἴδωμεν τί ἐστιν, etc. Catena Corderii.
footnote Corderii. (75) Ὥσπερ τῷ, etc. Schedæ Grabii et codex Coislinianus primus. (76) Ὅν ὡς ἥλιον, etc. Iidem mss. (77) Ἡ κόλασις, etc. Iidem mss.
footnote 59 II. Tim. Iv, 7, » Joan. VI, 14. 61 Psal. v, 6. (78) Ὁ δίκαιος, etc. Iidem mss. (79) Διὰ τό, etc. Codex Coislinianus secundus. (80) Ἐθήρευσαν, etc. Catena Corderii et codex Coislinianus secundus. (81) Ὁ λέγων, etc. Codex Coislinianus. (82) Οὐκ ἔστι, etc. Schedæ Grabii. (83) Τίς ἄρα, etc. Eædem.
footnote (92) Ὁ αἰσθανόμενος, etc. Catena Corderii. (93) Ἀκηδιᾷ, etc. Eadem.
footnote 64 Cor. I, 30. 65 Matth. IV, 19. 66 I Tim. I, 1. (94) Πέτρον σημαίνεσθαι, etc. Calena Corderii.
footnote (98) Ἰδιθοὺμ κριτοῦ, etc. Eadem. (99) Πᾶς ὁ ὑποτασσόμενος, etc. Eædem. (I) Τὸ, ὑποταγήσεται, etc. Catena Corderii.
footnote 72 Joan. VIII, 40. (2) Τοῦτο ὅμοιον, etc. Cutena Corderii. (3) Τιμὴ τῆς, etc. Schedæ Grabii. (4) Ἐπὶ μὲν τῇ προτέρᾳ, etc. Catena Corderii. (5) Ὡσεὶ ἔλεγε, etc. Eadem.
footnote 73 Hebr. I, 3. 74 I Cor. VII, 34. 75 Isa LVI, 3. 76 Psal. XXI, 30. (13) Τὰ χείλη, etc. Codex Coislinianus secundus. (14) Αϊρει καὶ ἐπαίρει, etc. Schedæ Grabii. (15) Λιπαρ ρὰ δέ, etc. C. Calena Corderii.
footnote 77 Psat. VI, 7. I Cor. VI, 17. 79 Isa. VIII, 12. (16) Πιθανὸν εἰς ἁγνείαν, ete. Catena Corderii. (17) Εἰ ὁ κολλώμενος, ete. Schedæ Grabii. (18) Ὅσω χεῖται, cte. Calena Cordeii. (19) Ἵνα πιστεύσατες, cic. Codex Coisliniansus
footnote (27) Καὶ πάντες ἀπήγγελλον, etc. Catena Corderii. 28) Εὐφραίνει ἄδικον, etc. Codex Coislinianus. (29) Καρδίαν εὐθεῖαν, etc. Idem.
footnote » Mah. αα,I6. Pel. Xc, 14. Joan. Xν, 2. s¹ Psl. uXv, 3. (30) Εὐθεῖς τῇ καρδίᾳ. etc. Catena Corderii. (31) Ἐν Σιών, etc. Eadem. (32) βίοάκουσον, etc. Eadem.
footnote (39) Κέτος φησίν, cte. Catena Corderii. (40) Ἐαὶ τοῖς Ἰησοῦ, etc. Eadem. (41) Πλοῦτον μέν, etc. Codex Coisliuianus. (42) Τρπφὴν μέν, etc. Calena Corderii. (43) Κατὰ μιρά. etc. Eadem.
footnote 88 Lsa. LXI. 1-3. 89 Psal. XL, 9. 90 Cant. 11, 10. 94 ibnd. c, 23, 24. 95 I Co. Xιν. 1. (44) Ἐν Ἡσαῦᾳ, etc. Catena Corderii. (45) Ἐπιφαrείenς, etc. Eadem. (46) Ἐπὶ ιἴ βέίτιων, uic. Eadem.
footnote (56) Οἱ παραπικραίνοντες. ete. Eadem. (57) Παραπικραίνοντές εἰσιν, etc. Schedæ Grabii. (58) Ποῦ θεμένου εἰς ζωήν, etc. Catena Carderii.
footnote 99 Cant. V, 13. 1 Ezech. XX I, 18. (59) Σαφῶς τοῦτο, etc. Calena Corderii. (60) Διὰ γὰρ πολλῶν θλίψεων, etc. Eadcm, (61) Ἅ ηὐξάμην, ete. Eadem. (62) Εἰ εὐνή, e. c. Eadem.
footnote 2 I Cor. IV, 4. 3 Psal. XVIII, 17. ⁴ Joan. XIV, 6. Galat. V, 22. 6 Num. X, 35. 7 Joan. IV, 16. (72) ὅσοι γήϊνοι, etc. Eædem. (73) Ὁ Μωὕσῆς φησιν, cte. Codex Coi Coislinianus primus. (74) Μισοῦσι τὸν κττίσαντα, etc. Coislinianus secundus.
footnote (75) Ταῖς παραβολαῖς, etc. Catena Corderii. (76) Οὐ πῦρ ὡς ἄγγελοι, etc. Codex Coisllinianus secundns. (77) Τοῦτον τὸν καπν etc. Coislimanus pri-
footnote 11 Ephes. IV, 8. (85) Τοὺς κλήρους, etc. Idem. (86) Βασιλεῖς εἰσιν, etc. Idem. (87) Ἅρμα Θεοῦ, ec. Item. (88) Λἰχμαλωσία ἐστὶ Χριστοῦ, ete. Sel.dæ Grabii, partimque codex Coislinianus primus.
footnote 12 Isa. LXIII, 3. 13 Ephes. IV, 10. (89) Κεφαλαὶ ἐχθερῶν, ete. Codex Coislinianus secundus. (90) Βασὰν ἑρμηνεύεται, etc. Idem. (91) Ἐν τῇ Χριστοῦ ἐπιδημίᾳ, etc. Idem. (92) Οὐ ταυτόν ἐστι, etc. Idem.
footnote (4) Ἐντεῦθεν, οἶμαι, etc. Codex Coislinianus pimus et schedæ Grabii. (5) Εἱ καὶ ἀπέδωκεν, etc. Codex Coislini nra secundus. (6) Οὐδένα τῶν ἀνρρώκεν, etc. Idem.
footnote 17 Isai. I, 19. 18 Joan. II, 17. (7) Οὐ πάντων, etc. Schedæ Grabii et codex Coislinianus primus. (8) Ἐπειδὴ ψευδομάρτυρες, etc. Codex Coislinianus secundus. (9) Οὗτος ὁ στίχος, etc. Codex Coislinianus primus, et schedæ Grabii. (10) Εἵποι δʼ ἄν ταῦτα, etc. Codex Coislinianus secundus. (11) Τοῦτο οἱ μαθηταί, etc. Idem.
footnote 19 Psal. CXXIX, 1. 20 II Cor. I, 4. Matth. XXV, 42. 22 I Cor. I, 23. Prov. IX, 5. (21) Ταῦτα πάντα, etc. Idem. 22) Οἶνος τραπείς, etc. Coislinianus primus. 23) Τράπεζα τῶν Ἰουδαίων, etc. Idem. (24) Μήποτε τράπεζα, etc. Codex Coislinianus secundus. (25) Δυνατὸν ταῦτα, etc. Coislinianus primus.
footnote 24 Matth. v, 2. ipid. v, 8. » Psal. xviii, 2. (26) Ἠρημώθη, ete. Codex Coislinianus secundus. (27) Ὄτε οἱ ἀνόμως, etc. Codex Coislinianus pri-prus. (28) Πῶς γὰρ δύνανται, etc. Idem. (29) Βίβλος ζώντων, etc. Idem. (30) Ἄδικος μετά, etc. Idem. (31) Τουτέστιν ὑπέρ, etc. Idem. (32) Γενώμεθα πένητες, etc. Idem,
footnote (41)Τοῖς τὴν πλατεῖαν, etc. Idem. (42) Ἐὸν μὴ πληρωθῇ, etc. Schedæ Crbii et codex Coislinianus primus. (43) Ταύτας τὰς φωνάς, etc. Iidem mss.
footnote 29 Isai. α. 2. 30 Matth. v, 40. 31 ibid. ν, 17. (44) Τὸ, μὴ μακρύνῃς, cic. Codex Coislinianus primus. (45) Μακρὰν ἀπὸ ἀνθρώπου, etc.Schcdæ Crabii. (46) Τὸ, Ἄφες αὐτῷ, etc. Codex Coislinianus secundus, et schedæ Grabi. (47) Πσλλαὶ αἰνέσεις, etc. Idem codex Coisliniaius secandus, (48) Εἰ ἔστι γράμμα, cic. Idem. (49) Τῆς τοῦ Πατρός, etc. Idem. (50) Βραχίων, etc. Codex Coislinianus primus.
footnote 24 Matth. ν, . 25 Prov. Xm, 8. 26 Joan. Xm, 18. 27 Philip. n, 10. mus, at schedæ Grabi. (61) Ἀντὶ τοῦ, etc. Idem codex et schedæ Grabi. (62) Διαφοράν, etc. Coislinianus secundus. (63) Θαρσεῖς ἔθνος, etc. Coislinianus primus.- (64) Εἰ δουλεύσουσιν, etc. Codex Coishmanu secundus, et schedæ Grabi.
footnote 28 Gal. 11, 20. 29 Luc. 11, 3. 30 I Tim. vi, 15. 31 I Tim. iv, 10. (65) Ζῇ Χριστός, etc. Idem codex mss. et schedæ Grabii, (66) Αέγοντες. coislinianus primus. (67) Μαθόντες, etc, Coislinianus secundus. (68)Αἰβανον λέγει, ect. Codex Coislinianus primus, et schedæ Grabii. (69) Καρπὸς Χριστοῦ, etc. Coislinianus secundus. (70) Ὁ Παῦλος, etc. Codex Coislinianus primus et schedæ Grabii.
footnote 44 Joan. α, 9. (89) Ὡς πρὸς τὸ ῥητόν, etc. Ecodice Coisliniano serundo. (90) Τὸ, Εἰσελεύσεται, etc. Ex eodem. (91) Ζητήσεις ἀπὸ ποίας, etc. Εα eodem. (92) Ζητησεις εἴτε, etc. LEx eodem.
footnote (2) Εἰ θηρία, etc. Ε codice Coisliniano psimσ. (3) Μνήσθητι τῶν, etc. Ex eodem. (4) Ἐσκοτισμένος νοῦς, etc. Ex codem. (5) Ἀνάστα, ὁ Θεός, cic. E codice Coisiaiase secundo.
footnote 46 1Reg. ααvI, 9. ⁴¹ Calυt. n 9. (6) Νῦν ἄφρονα. etc. Ecodice Coislinianoprmno. (10) Γῆν λέγει, etc. Ex codem codice et schedis (7) Γέγραπεαι ἐν τῇ πρώτῃ, ete. E cohcs Coin Graba. (11) Καὶ γνόντες, etc. E codice Coislin. primo, hiano secundo. (8) Ἡ ἐν Χριστῷ, etc. Ex eodem.  (9) Ὁ Σύμμαχος cte. Ex eodem. et scheda Graba.
footnote (15) Τόξα νῦν, etc. Idem codex ms. (16 Τουτέστι διδάσκεις, etc. Idem. (17) Τὸ ταράττεσθαι, etc. Codex Coisluians secundus.
footnote 49 Prov. vi, 4,5. 50 Psal. 11, 2. (18) Διʼ ὃ καλῶς, etc. Codex Coislinianus primus. (19) Οὔτως ἄνδρες πλούτου, etc. Idem. (20) Οἱ δαίμονες, etc. Codex Coislinianus secundus. (21) Ἀφαιρεῖται πνεύματα, etc. Idem. (22) Ὅτε πᾶσα φωνή, etc. E codice Coisliniano secundo. (28) Ὁ κινηθεὶς μέν, etc. E Coisliniano secundo.
footnote » P.al. ααατ, 11, » Joan. XIv, d. » ICat. vm, 5. (29) Ὁ τὰ ἄδηλα, etc. E codice Coisliniano primno. (30) Ωσεὶ ἔλεγε, etc. Ex eodem. (31) Ὡς κόπτοντος αὐτοῦ, etc. Ex audem. (32) Οὐδέποτε ἤρξατο, etό. E codice Coisliniano serundo. (33) Ἀλλοίωσιν λέγει, etc. E cadice Coisliniano secundo. (35) Ὅρα εἰ διὰ τούτων, etc. Ex eodem. (36) Τουτέστι τὸν Χριστόν, etc. Ex codice Coisliniano primo. (37) Αἱ ἄβυσσοι, etc. Ex eodem. (38) Ὁ τροχός, ete. Ex eodem. (39) Πρώτη μάν, ec. E codice Coisliniano sæeuprimo. do. (34) Ἤτοι ἐν παντί, etc. Ε codice Coisliniano (40) Ἀνωτέρω εἴρητα, etc. Ex eodem.
footnote ⁴ Joan. v, 51. ss I Cor. v, 16. (41) Ah hoc psalmo xXvnn usque ad ﬁnem psalm exE, omnia scholia Græca vel e codice Coisli-
footnote ⁶ Iebr. vn, 14. Coloss. I, 15. ⁵ Joan. Xv, 6, » Rom., 26.
footnote 60 Jerem. I, 2I. PATROL. GR. XII.
footnote Sap. I, 4. ⁵⁴ Proν. m, 12; lebr. Xo, 6. » Psal. Xαὶ, 13.
footnote 47 lelr. , 6. ⁵ ICωr. , 3. «s roan. ν, 22.
footnote Rom. I, t7. Joan. v, 38.
footnote 77 Job xxvi, 7. 78 Psal. CXLVI. 4.
footnote 80. iRom. I. 25.
footnote 81. Zachar. III, 1. 82 Rom. xii, 14.
footnote 83 joan. XVI, 32. 84 Psal. cx 10. Matth. x, 27.
footnote 86 I Cor. iv, 1. 87 Matth. iv, 24. 88 ibid. xxiv, 6. 89 Gal. iv, 27.
footnote 90 Joau. xiv, 6. 91 l Thess. iv, 14. 92 Rom. ix, 2. 93 ibid. x, 15.
footnote 94 Deut. xix, 15. 95 Rom. xii, 8. 96 Exech. xviii, 4. 97 Deut. iii, 31, 98 Job. i, 1. 99 Psal. LXXXI, 7.
footnote 0se. XI, 4.
footnote 2 Rom. x, 13. 3 Matth. xiii, 28.
footnote ⁴ Prov. v, 3 5 Philipp. IV, 13. 6 Psal. XXIII,
footnote Joan. I, 14. 11 Psal. I.
footnote I Cor. I, 30. 15 VIII, 22.
footnote  16 Deut. XV, 12. Jacob. II, 10. 1Cor. X, 13.
footnote 20 Psal. XXI, 16. 21 Psal. XLIII, 25. 22 Philip. III, 21. 23 Rom. VIII, 24. 2?? Vers. 25, Prov. VI, 4 Matth. VII, 14.
footnote 23 II Cor. IV, 8. II Cor. VI 12. 30 ibid. 31 Joan. XIV, 15. Rom. I, 16.
footnote 34 Matth. v, 8.
footnote Psal. I., 12.
footnote 37 Rom. VI, 18. 38 ibid. 22. Rom. XIII, 12, 13. 40 I Thess. v, 5. 41 II Cor. II 11.
footnote Psal. LXXXVIII. 4. 40 Prov. XII, 5. 47 Petr. II, 22. 48 Psal. XXX, 5, 6.
footnote 49 1 Cor. 11, 9. 50 1 Reg. xv, 11.
footnote 51 Rom. v, 3. 52 Ephes. vi, 12. 53 Matth. x, 38.
footnote ?? Psal. cxi, 1.
footnote 56 Prov. ν, 16. Prov. ii, 17. 57 Psal. Lxviu, 10. 58 Hebr. iv, 12. 59 Psal. cxviii, 137. 60 I Cor. xiii, 8.
footnote Vemε. 1S2. fnino cognovi de testimoniis tuis, quia Κατʼ ἀρχὰς ἔγνων ἐκ τῶν μαρτυριῷν σου, ὅτι 62 Prov. 1, 22. 63 Ger. iv, 10. 64 Exod. xiv, 15 65 Psal. LXXI, 27.
footnote 64 Jac. iv, 10. 67 Sap. i, 4. 69 Luc. xix, 10. 80 Matth. v, 10.
footnote 70 Act. xiv, 21. 71 Psal. lxviii, 10; Joan. 11, 17. 72 ibid. xiv, 30 72 Matth. xviii, 6.
footnote 74 Luc. xii, 35. 75 Rom. vii, 22.
footnote 76 Joan. vi, 51, 52. 77 ibid. 55, 56. 78 Jacob. v, 13. 79 Luc. ii, 14. 80 Coloss. iii, 3. (42) Μόνοι οἱ τῷ βίῳ, etc. Catena Corderii.
footnote 81 Isai. xlix, 2. 82 ibid. 83 Psal. ci, 25 (43) Τῶν διʼ ἀρετήν, etc. Schedæ Grabii. (44) Συνεχῶς ἄνω, etc. Catena Cordcii.
footnote 82 Philip. i, 23. 83 Act. xiii, 36. 84 Eccli. xxvii, 12. (47) Κηδάρ, etc. Catena Corderii. (48) Ἐγὼ μέν ᾖρα, etc. Catena Corderii. (49) Μὴ περιτραπῇς, ete. Eadem. (50) Οὖτος, οἶμαι, etc. Schedæ Grabii. (51) Ἔξοδον τήν, etc. Eædem. (52) Δύνανται οἱ εἰρηκτότες, etc. Catena Corderii. (53) Ἐστῶτις ἦσαν, etc. Eadem.
footnote 87 Psal. xxi, 19. 88 Psal. lxviii, 22. 88* Matth. xix, 28. 89 Jerem. i, 14 et seqq. (54) Ὅταν ἡ τῶν, etc. Catena Corderii. (55) Προφητεύει, etc. Schedæ Grabii. (56) Περὶ τῶν θρόνων, etc. Catena Corderii. (57) Ὁ Θεός, etc. Schedæ Grabii. (58) Δοῦλοι κυρίων, etc. Catena Corderii  (59) Τῶν μέν ἐχόντων, etc. Eadem. (60) Σύμμαχος, etc. Schedæ Grabii.
footnote 90 I Cor. i, 28. 91 I Cor. viii, 6. 92 Rom. xi, I. 93 II Cor. xi, 22. 94 Joan. xiv, 6. (65) Ὑδωρ τροπιικῶς, etc. Eædem. (66) Χείμαῤῥον, etc. Eædem. (67) Καὶ ἐγένετο, etc. Catena Coderii.
footnote 95 III Reg. xvii, 2 et seqq. 96 Exod. xx, 14. 97 Rom. xiii, 9. (68) Ἐῤῥύσθημεν, etc. Schedæ Grabii; simile utem qudpiam anonymo tribuit Catena Corderii. (69) Θηρεύουσιν ἐπί, etc. Catena Corderii. (70) Ἠ μὲν Παλαιά, etc. Schedæ Garbii. (71) Οἱ προσερχόμενο, etc. Catena Corderii. (72) Εἰ ἐκ τοῦ, etc. Eadem. (73) Ὅρη κύκλῳ, etc. Eadem.
footnote 98 Psal. xxxiii, 8. 99 Psal. cxxxiv, 19. 1 ibid. 20. 2 Matth. xiii, 12. 3 Psal. cxxxvi, 1. 4 Psal. xxxviii, 2. ⁵ Psal. xxxvi, 30. 6 Prov. xxxi, 8. 7 II Cor. vi, 2. (74) Ἔργον Κυρίου, etc. Catena Corderii, (75) Εἰ κλῆρος, etc Schedæ Grabii. (76) Τήρει τό, etc. Catena Corderii. (77) Οἱ ἀπόστολοι, etc. Catena Corderii. (78) Αἰχμαλωσία, etc. Schedæ Grabii. (79) Τὸ μὲν στόμα, etc. Catena Corderii.
footnote 8 aruch. iii, 38. 9 Gen. ii, 22. 10 ibid. xi, 4. (80) Μετὰ ταῦτα, etc. Schedæ Grabii. (81), Ἀνωτέρω μέν, etc. Catena Corderii. (82) Οἱ μέν τόν, etc. Schedæ Grabii. (83) Χρηστέον τῷ ῥητῷ, etc. Schedæ Grabii. (84) Πρῶτον ᾠκοδόμησε, etc. Catena Corderii. (85) Τὸν ἐν Ἱερουσαλόμ, etc. Eadem. (86) Ἐφ᾿ ὅσον, etc. Schedæ Grabii.
footnote 11 Joan. xiv 6 (91*) Ἡ κλπρονοία, etc. Catena Corderii. (92) Πολλαὶ ὀδοὶ, etc. Catena Corderii. (93) Εἰ φόβος Κυρίου, etc. Schedæ Grabii. (94) Εἰ ὁ πορευόμενος, etc. Eædem.
footnote em. ii, 21. 3 Prov. iv, 6, 8. 14 ibid. vii, 4. 13 ibid. xiii, 22 14 Gen. xlviii, 15. 17 Isai. v, 18
footnote 18 Exod. iii 3. 19 Prov. xx, 9. 20 Job. xiv, 4. 21 I Joan. ii, 2. (8) Ὁ παρὰ τῷ Κυρίῳ, etc. Catena Corderii. (9) Ἡ διὰ τοῦ Θεοῦ, etc. Eadem. (10) Ἡ ἐλπίς, etc. Schedæ Grabii. (11) Τοτηνικαῦτα, etc. Eædem.
footnote 22 Galat. iv, 26. (12) Αὗται φωναί, etc. Catena Corderii. (13) Ὡς. ὁ Ἰσαάκ, etc. Eadem. (14) Τῇ τοῦ. etc. Eadem. (15) Ἐν μὲν τῇ, etc. Eadem. (16) Ἐκείνου μνημονεύει, etc. Schedæ Grabii. (17) Ἀντὶ πραότητος, etc. Eædem. (18) Τόπος, etc. Eædem. (19) Περὶ τῆς, etc. Eædem. (20) Ὥσπερ ἐνδύεται, etc. Eædem.
footnote (21) Μῦρόν ἐστι, etc. Catena Corderii. (22) Ἐν τῷ Δευτερονομίῳ, etc. Schedæ Grabii. (23) Ὅρη Σιών, etc. Catena Corderii. (24) Οἱ ἑστῶτες, etc. Eadem Catena. (25) Οἱ μέν, etc. Schedæ Grabii. (26) Ἀντὶ τοῦ, etc. Catena Corderii. (27) Αἰνεῖτε οὐκ ἄλλοι, etc. Eadem Catena.
footnote 23 Exod. xviii, 11. 24 Thren. iii, 38. 25 Psal. cxiii, 16. 222 Vεαs. 5. Quia ego cognovi quod maguus est (32) Εἰ ἡ κληρονομία, etc. Eædem. (33) Ὁ ἐν καθορᾷ, etc. Eædem. (34) Οἱ ταλαιπωροῦντες, etc. Eædem. (35) Ἡ ἐξομολόγησις, etc. Eædem.
footnote 26 Psal. lxxxi, 6. 27 Exod. iii, 6. 28 I Cor. viii, 5. 29 Job. xxvi, 7. (36) Θεὸς θεῶν, etc. Catena Corderii, (37) Δείκνυσιν αὐτόν, etc. Eadem. (38) Εἰ τοῦ ὕδατος, etc. Schedæ Grabii.
footnote (39) Τὴν εὐκολίαν, etc. Catena Corderii. (40) Ὅταν μέν, etc. Schedæ Grabii. (41) Ἡ τρεφομένη, etc. Eædem. (42) Πολὺς ὁ πύθος, etc. Catena Corderii. (43) Ὅσαι ψυχαί, etc. Schedæ Grabii. (44) Ἔγνων ἐγώ, etc, Eædem. (45) Τὸ, Ἐκκενοῦτε, etc. Eædem.
footnote (51) Γλῶσσαν, etc. Schedæ Grabii. (52) Ἐπίσκεψαι, etc. Catena Corderii. (53) Φωνὴ πολλούς, etc. Eadem. (54) Ὡς δυνάμενος πορεύεσθαι, etc. Eadem.
footnote 30 Amos. ix, 1 et srqq. 32 Rom. i, 21. 22* Joan. i, 5. (55) Εἰ ἡ ἄγνοια, etc. Schedæ Grabii. (56) Μακάριος, etc. Catena Corderii. (67) Ὀστοῦν, etc. Schedæ Grabii. (58) Ἀκατέργαστον, etc. Eædem. (59) Βιβλίον Θεοῦ, etc. Eædem. (60) Ἐν γνώσει, etc. Eædem.
footnote (65) Τὸν ὀξύτατον, etc. Eædem. (66) Ἀλλὰ καί, etc. Eædem. (67) Τοῦτο τό, etc. Eædem. (68) Προφητεία, etc. Catena Corderii.
footnote II Cor. ii, 15. (60) Τούτου, etc. Istud scholion necnon duo se-utia in hunc psalmum fragmenta exhibent ScheGrabii. (70) Ὡς φύσιν, etc. Catena Corderii. (71) Ὁ μόνα, etc. Eadem. (72) Πάσαις οἱ ἐχθροί, etc. Schedæ Grabii.
footnote 35 Psal. iv, 2. 36 Mich. vi, 3. 37 Psal. l, 6. 38 Psal. cxli, 4. (73) Ὁ ἀπολέσας, etc. Schedæ Grabii. (71) Εἰ ὁ Κύριος, etc. Eædem. (75) Πειρασμοί, etc Eædem. (76) Οὐ πάντων, etc. Eædem. (77) Ὁ θαῤῥῶν, etc. Catena Corderii. (78) Ἐπὰν κρίνηται, etc. Eadem. (79) Γῆ ἄνυδρος, etc. Schedæ (80) Ἐπὶ λεῖον, etc. Catena Corderii. (81) Τὴν θεωρίαν, etc. Schedæ Grabii.
footnote 39 Psal. xlviii, 13. (82) Δύναται τοῦτο, etc. Catena Corderii. (83) Γῆ ζώντων, etc. Eadem. (84) Ὁ διδαχθείς, etc. Schedæ Grabii. (85) Ἐπεὶ ἄνθρωπος, etc. Catena Corderii. (86) Ματαιότης, etc. Schedæ Grabii. (87) Ἁφή ἐστιν, etc. Eædem. (88) Ταῦτα τὰ βέλη, etc. Eædem. (89) Τῶν ἑτεροδόξων, etc. Gatena Corderii.
footnote 40 Jerem. xii, 1. 41 Psal. lxxii, 2, 3. 42 Psal. cxxvii, 5. (90) Καὶ ὁ προρφήτης, etc. Schedæ Grabii. (91) Ὁ τὴν Καινήν, etc. Catena Corderii. (92) Τοῦ μὲν διὰ τό, etc. Eadem. assiduum. loc ipsum ergo Propheta signiﬁcans subjunxit. (93) Μακσριότης, etc. Schedæ Grabii. (94) Υψωσις, etc. Eadem. (95) Καὶ ἐν περιστάσεσι, etc. Catena Corderii.
footnote 43 II Cor. iii, 3. 44 Gen. vi, 3. 45 I Cor. xv, 50. (96) Ἐπείπερ ἡ μεγαλωσύνη, etc. Catena Corderii. (97) Πάντων μέν, etc. Schedæ Grabii. (98) Εἰ οἱ οἰκτιρμοί, etc. Catena Corderii. (99) Νῦν ἕργα, etc. Schedæ Grabii. (1) Εἰ ἠ βασιλεία, etc. Eædem. (2) Ἐξολόθρευσις ἁμαρτωλοῦ, etc. Eædem. (3) Πᾶσα σάρξ, etc. Catena Corderii. (4) Καὶ ὁ Παῦλος, etc. Schedæ Grabii. (5) Ἀλήθειαν εἶπε, etc. Schedæ Grabii.
footnote 46 I Cor. xiii, 4. 47 Luc. xi, 23. 48 Psal. ciii, 25. 49 Psal. lvii, 2; cxxxix, 4. (6) Οὔτε τὰ πράγματα, etc. Schedæ Grabii. (7) Ἐκείνους δηλαδή, etc. Catena Corderii. (8) Ὁ Χρστός, etc. Schedæ Grabii. (9) Οὓς δικσκορπίζει, etc. Eædem. (10 Ὁ ἀριθμός, etc. Eædem. (11) Ζητητέον, etc. Catena Corderii. (12) Περιάλλετα, etc. Eadem.
footnote 50 Psal. lxxx, 17. 51 Luc. xii, 49. 52 Matth. (13) Μοχλοὶ, οἶλμαι. etc. Catena Corderii. (14) Μοχλοὶ μὲν τῆς, etc. Schedæ Grabii. (15) Τὰ ὅρια τῆς, etc. Catena Corderii. (16) Ὅρια τῆς, etc. Schedæ Grabii. (17) Ὅμοιον, etc. Catena Corderii. (18) Γῆν ἐνταῦθα, etc. Eadem. (19) Διττῶς λέγεται, etc. Schedæ Grabii. (20) Ἡ χιών, etc. Eædem. (21) Αἶνός ἐσειν, etc. Omnia in hunc psalmum scholia e schedis Grabii desumpta sunt.
footnote (25) Ἐὰν οἱ πολλοί, etc. Eadem. (26) Οἱ μὲν νεκρώσαντες, etc. Eadem. (27) Εὐδοκεῖ Κόριος, etc. Eadem.
footnote 55 II Cor. iii, 18, 56 Rom. xiii, 12, 13. 57 Il Cor. x, 5. 58 Psal. cxxxvi, 4. (28) Ἀγαλλιάσονται, etc. Catena Corderii. (29) Ὧν οὐ τάφος, etc. Eadem. (30) Ῥομφαῖαί εἰσι, etc. Schedæ Grabii. (31) Ῥομφαία ἐστί, etc. Eædem. (32) Ἐκδίκησιν μέ, etc. Catena Corderii. (33) Ὁ συμβιβάζων, etc. Eadem. (34) Δεσμός έστι, etc. Schedæ Grabii. (35) Ποιοῦσιν οἱ ὅσιοι, etc. Catena Corderii. (36) Μηδεὶς ἐξελθών, etc. Eadem.
footnote 59 I. Cor. xv, 52. 60 I Thess. iv, 15 61 Psal. lxxx, 4. (41) Σάλπιγξ έστί, etc. Schedæ Grabii. (42) Κιθάρα ἐστί, etc. Eædem. (43) Χορδαὶ πλείους, etc. Catena Corderii.
