@node
@author=Alexander of Aphrodisias
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Ivo Bruns
@filename=tlg0732.tlg001.1st1K-grc1
@funder=Harvard Library Arcadia Fund
@principal=Gregory Crane
@publicationStmt=Harvard College Library, tlg0732.tlg001.1st1K-grc1.xml.
@respStmt=Digital Divide Data, Corrected and encoded the text, Gregory Crane, Editor-in-Chief, Perseus Digital Library, Matt Munson, Project Manager (University of Leipzig), Annette Gessner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor
@sourceDesc=Alexandri Aphrodisiensis Praeter Commentaria Scripta Minora, Ivo Bruns, Alexander of Aphrodisias, Reimer, Berlin, 1892, 2, Supplementum Aristotelicum, 2.2, Internet Archive.
@sponsor=Harvard College Library
@title=De mixtione
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T15:07:56Z

11731	marginal Ed. Ideler p. 589 Ι
footnote 1 περὶ κράσεως καὶ μίξεως Β: περὶ μίξεως Ra 4 μηδὲ scripsi: μήτε libri τε circumscripsi 7 ὅσον] fortasse ὡς ὂν (ὡς ὄντος ἐν τούτῳ τοῦ Αpelt) τὸ] τῷ a 9 ἀλλὰ] ἀλλ’ ἢ Ra δύνασθαι Ra: δύναται (υνατ ex corr) rel. 10 ἐνοίας Ra ante τὸ add. ἢ man. rec. Ra 11 εἶναι] Ra 14 οὐδεμιᾶς] μηδεμιᾶς Ra 15 λόγον A1 (corr. A2) 16 οἱ] οὐ Ra 17 γενέσει a: γενέσι codd. τε om. a 18 ποιοῦντες Ra 19 post μέγεθος 2 litt. erasae A 21 ποιά a γίνεσθαι Ra: inter τἆλλα et ἐφ’ 7 8 litterae evanuerunt in A: fenestra in B: om. CPS 23 τούτῳ τραπέντες] τούτων ἐπέντες Ra: τούτων ἐπιόντες δόξαν Ideler
marginal ΙΙ
footnote 1 οὐκ ἀτόμους Diels Apelt: οὐ κατ' ἄλλους libri 2 post σύνθεσιν fenestra 7 litt. in fine versus A fort. ⟨ἐφ’⟩ ἧς 9 αὖ τῶν Diels: αὐτῶν libri διωρισμένη . . κεχωρισμένη Ra 10 τοσῆςδε] τοιῆσδε Ra 11 ⟨τῷ〉 μὲν scripsi: μὲν ARa: ὅτι μὲν BPS: ἐπεὶ μὲν ldeler εἶναι] ἐστιν εἶναι A2a 1 4 χαλεπήν τε Diels: χαλεπὴν ⟨χαλεπὸν SP δὲ ABSCP: χαλεπὴν Ra ἑκάστη A 15 ante ἄλλος C del. δὲ ἄλλος ἄλλη ABCP: ἄλλος S: ἄλλη ἄλλην Ra 15. 16 ἀπετράπετο] ἐράπτετο Ra 16 διαλαβεῖν] διαλαχεῖν Ra 17 ⟨καὶ〉 τοῦ ldeler 18 παρεχομένους] παρεχόμενα ta 19. 20 κατὰ—κιρναμένων om. PS 19 τῶν διαιρουμένων Ra τῶν ABC: καὶ Ra 24 παρακειμένων] περικειμένων] Ra 25 δύνασθαι om. a 26 ὑκνησεν Scheartz: ὑκνησαν libri 27 παραθέσει δὲ τοιαύτῃ A2 Ra: παράθεσιν δὲ τοιαύτην A¹ BCPS κρίσεις A1 καὶ οἱ ACPS: καὶ ὁ B: οἱ Ra 27. 28 εἶναι ὕλην Ra 28 βουλόμενος om. BCPS 29 βούλεται om. A1: βουλῆς CP: fortasse δὲ 31 λέγει A¹;  λέγων rel.
footnote 1 εἰς] εἰ a: ἐς R 3 ἔπειτα ποιᾷ Usener, cf. Epicurea p. 207,13: ἐπὶ τὰ ποιὰ libri 4 σῶμα ⟨οὐ⟩ Ideler 5 συμμιγνυμένων ⟨οὐχ⟩ Usener τε s. v. 6 φθόρᾷ τε Usener: φθοραῖς libri 7 ἡ add. Usener ἀνάλυσις Usener: ἀναλύσεις libri ἡ] ἐστιν Ideler 8 τὸ μὲν γένεσις add. Usener τὸ del. Ideler φθορά Usener: φθεῖρα ACRa: φθεῖραι BP: φθεῖρας S 9 οὔθ᾿ οἱ Ιdeler: οὖτοι libri 10 ἀνάλυσιν delet: ἀνά libri εἴ γε] εἴτε Ra 11 κράματος Ra 12 δὲ scripsi: δὴ libri 13 ἕνωσις a ἐστ] ἔτι ARa 15 ἐκεῖνα om. Ideler 16 pr. καὶ om. Ideler 17 ποιὰ a διαφορᾶς] διαφθορᾶς Ra 18 γεννωμένης] γενομένης Ideler 19 pr. γίνεται om. B 22 ὃ ἵσως] ὁμοίως Diels bene: ἴσως Ideler 26 ἐκείνης] ης periit in A 28 περὶ] παρὰ BCPS μὲν οὖν τῆς Ra 29 fortasse δόξης ⟨τῆς⟩ μηκύνειν] μηνύειν a τὸν] τὸ AB 30 πολλῆς SRa: πολλῶν ABCP 31 λέγων] λέγειν Ra κράσεις] σεις evanuit in A 32 κοιναῖς om. Ra ΙΙΙ
footnote 2 ldeler: ὑποθέτας ABRC?S? a: ὑποθέσεως P 3 ἐπὶ πολαιότερον a προκειρότερον Ra 4 αὐτὰς] δόξας Diels 5 περὶ κράσεως] fortasse πρὸ πάντων 6 περὶ κράσεως del. ldeler 9 αὐτὸν] αὐτῶν a 11 ἐκείνου] κείνου ex corr. ut videtur εἶς Α: εἰς Ρ 14 μαχόμενα] μαχόμενοι R(?)a, cf. Ind. s. v. Nentrum 16 οὖ s. v. συνέχεται] συνάγεται Ra 16. 17 τὸ πᾶν, τῶν Apelt: τὸ πάντων A ¹ Ra: τῶν πάντων A2 BCPS 17 παραθέσει μίξεις ldeler: παραθέσεις μίξει libri 18 ταὐτὸν] ταυτὸ Ra 19 ἁρμήν scripsi, cf. p. 219,   ὁρμὴν ABCPS: ὁρμῆς Ra 20 περιγραφὴν Ra: περιγραμμὴν rel. 21 φέρε corr. ex φέρειν 22 γίνεται scripsi: γίνεσθαι libri (θέσει· γίνεσθαι τὰς Ἀpelt) συγχύσει Ideler: συγχύσεις ABCRSa: συγχύσεως P 23 τῶν om. Ra 26 τοιούτων A 1 28 τοιάδε a δύο] διὸ a 30 τε s. v. a 31 λέγειν A1 32 τὸ] τῷ a
marginal ΙV
footnote 1 γίνεται A2: γίνεσθαι BΑ¹ CPS: γίνεσθαι τάττεται Ra τῷ Ra: τὸ ¹BPS 2 τὰς om. Ra 4 λαβόντας] fortasse λαβεῖν ταύτ τας τῶν om. Ra 5 ἁρμὴν scripsi: ὁρμὴν libri 6 ἀλλήλοις Apelt: ἀλλήλους libi 9 ἁρμήν scripsi: ὁρμήν libri 11 τῷ] αὐτῷ Ra κεκραμένῳ om. Ra 18 τε] δὲ Ideler 19 τὸν SR Ideler: τὸ BCPa 24 γενόμενοι] γινόμενοι ldeler 25 δὲ om. Ra 26 ἀλλήλαις om. R? Ideler 33 τοῦθ’] τόσοθ Ra 35 αὐτὸ] αὐτὴν Ideler οὐσίαν] φύσιν Ideler
marginal V
footnote 1 τῆς add. Ideler R? 5 ἀτόνων Ra: τόνων (α suprascr.) A:  τόνων BCPS 6. 7 φθείροντα] φάρμακα ldeler 12.13 οὐ πάσαις μᾶλλον ἢ ταύταις scripsi: οὔσαις μᾶλλον ἡ ταύταις BCPS: μᾶλλον ἢ τούταις R: μᾶλλον ἢ τούτοις a 15 ἀποδεῖ Apelt: ἅπαν δεῖ libri 16 οὐ add. Apelt 17 φυσικῆ ABPa τὸ] τῷ Ra: om. PS 19. 20 ὥφθησαν—ἣν] σαφήνειαν ἔχει, δι’ ἣν Diels: ὀφθαλμοῖς ἔστιν ἰδεῖν. ἣν Ideler: ὤφθησαν ἔχειν. δι᾿  ἣν Apelt 20 δοκεῖν BCPS 21 τι Apelt: τὸ libri δε| χόμενον ἐν αὐτῷ ἄλλο σῶμα| κτικὸν R ὃ scripsi: ὃν libri 24. 25 λέγει] ἔχει Ra: ἐρεῖ Apelt 25 οὐ scripsi: ἢ libri ἀλλ᾿  οὕτω scripsi: ἀλλὰ τὰ (τῶ S) libri: ἢ ἄλλα τινὰ Ideler 26 πλήρεις Apelt: πλῆρες libri 28. 29 εἴ γε Apelt: εἴτε libri 31 λεπτότατα τοῦ] λεπτοτάτου R2a 33 μετὰ στάσεως A ἔτι δ’ εἰ Apelt: ὅτι δεῖ libri 34 ἔτι A
marginal VI
footnote 2 οἵαν A2R: οἷαν A1: οἷ BCPS 3 ἁρμὴν ABCS: ἁρμὴν PR: ἀρχὴν a: ὁρμὴν ldeler 4 ποιοίη] ποιήσῃ Ra ἔσται om. Ideler 7 τοὺς corr. ex τοῦ A πόρους τοῦ σώματος Ra fortasse ὡς δ᾿ , εἰ πᾶν εἴη 〈πόρος, διάστημα πᾶν ἂν εἴη⟩ 8 ἂν] fortasse ὂν ἔτι] ἔχοι Apelt alt. οὔτ᾿ Schwartz (idem add. ἔχοι): δ’ οὐδ’ libri 10.11 ἐπιζητήσαι τις Apelt: ἐπιζητῆσαν libri: ἐπιζητητέον Ideler 11 τί] εἰ Ra οὐ ex corr. A alt. τὸ τυχὸν om. ldeler: fortasse τοῦ τυχόντος 12 τὰ del. Schwartz 14 σημεῖον] στοιχεῖον Ra συντεθείσαις R¹ 15 ἕξουσί] ἕξ in lit. A: προέξουσι Diels fortasse τι ⟨πλέον⟩ παρὰ 16 fortasse τὸ ⟨δὲ⟩ σῶμα τῷ 17 καθ’ ὃ] fortasse καὶ αὐτό, συντεθῇ (corr. ex συντεθεῖ) ARa: συντεθεῖ BCPS 20 ἀναιροῦσι AB (σι add. B2) CFS: ἀναιρεῖ Ra: ἀναιροῖεν Apelt 21 ante τινος fenestra 8 litt. 22 τὸν corr. ex τὸ AR: τὸν a: τὸ BCPS 26 κενὸς ἔσται Ra 29. 30 μὴ τὸ] fortasse μηδὲ 30 δεδεγμένου a 31 οὐ ἠρκέσθαι a 32 fortasse δεύτερον (τὸ⟩ ἐν et τὸ (33) del. 33 γενομένη] γινομένη Ra
marginal VII
footnote 1 τὰ]fortasse αὑτὰ, nisi praestat ἄλληλα cf. 221,25 3 προσελθεῖν] fortasse 7 πρόσω ἐλθεῖν εἰ del. Ideler 3.4 fortasse [εἰ] ἔδει, ⟨εἰ〉 ἕν τι δεχ. σ. ἐν αὑτῷ ἄλλο σ. ⟨μηδὲν μείζον γίνεται〉, μηδέν τι μεῖζον γίνεσθαι 5 μηδενὸς ex corr. A: fortasse μηδενὸς ⟨δέ〉 7 σωμάτων] σώματος Ra 9 ἔς τι Apelt: ἐστὶν libri 12 τῆς] τις Ra: τι Ideler 14 ἓν Diels: μὲν libri 16 πῶς δ’ οὐκ Diels: οὕτως δ’ ὂν libri τὸ corr. ex τῷ A 18 χεόμενα Diels: καιόμενα libri 19 μεταβάλλοντα] μεταβαλόντα Ra 21 alt. καὶ om. Ra 23 τό τε] τότις PCS 24 χωρεῖν] χαίρειν R¹a 29 fortasse τούτῳ 30 τῇ] αὐτῇ Ra 34 ὃ] ἃ Ra
marginal VIII
footnote 2 μόριον ἔχει] ἔχει μόριον R: ἔχειν μόριον a 5 ἢ R (man. rec.) a: τι rel. ὥστε Apelt: ὡς ὁ libri 6 ὃ Apelt: οἱ libri 8 περιγραφὴν Ra: περιγραμμὴν rel. τε om. a 12 τούτῳ] τοῦτο a 14 ante τὰ add. δὲ Ra: δὴ Ideler 17 ἕξ εἰς AB1 18 τε om. Ra 19 συνέχεσθαι Apelt: συνελέσθαι (συνελέχθαι B) libri καὶ om. ldeler 20 τὰ om. ldeler 22 οὐ γὰρ δὴ scripsi: εἰ γὰρ μὴ libri 23 ἐνίνων a 25 εἰ Ideler: ἢ libri 27 διὰ om. Ideler αὐτὸς Ra 28 ἐπικεόμενος Ra 29 διαιροῦντα CPRS: διαιροῦν τὰ ABa ἀδιαίρετα ldeler: διαιρετὰ libri 32 γίγνοιτο] φαίνοιτο Schwartz 33 γενομένη BCPS 35, 36 ἡ τομὴ γε BC: ἡ τὸ μὴ γεγονυῖα PS: ἡ μὴ γεγονυῖα Ra: om. Ideler 36 παρὰ A: περὶ rel.
marginal IX
footnote 4 ἢ del. ldeler 5 ⟨ἢ⟩ τὸ scripsi: τὸ libri: τῷ Apelt 9 παντὶ] fortasse πάντῃ post τι A1 del. τέμνεσθαι δυνάμενον 11 κίρναται B fortasse εἴ γε κίρναται μόνα, ⟨ἃ⟩ ἀλλήλοις καὶ παρεκτ. παρεκτείνονται a 12 fortasse ἄλληηλα, ⟨ἀδύνατον δὲ οὕτως ἄλληλα⟩ διῃρηκέναι del. Ideler: καὶ διηρημένα Apelt 13 post κεκρ. lacunam ind. Caninius 15 τὸ del. Schwartz 17 lacunam in Ideler 21 δ᾿  addidi 29 τὰ add. Schwartz 31 χωρὶς BCPRSa 32 δύναται Ideler 34. 35 οἷόν τε] fortasse οἴονται 35 εἶναι om. Ra 36 φασι scripsi: φησι libri
marginal X
footnote 4 ἀμείωτα ldeler: ἀμείω τὰ libri 7 καὶ om. Ideler 10 αὕτη ldeler: αὐτὴ libri 13 αὐτὰ] αὐτὰς Ra γενέσει] γένεσι Ideler 14 συνέχει RSa: συνεχεῖ ABCP 15 αὐτοὶ Diels 16 ὑλικαῖς] ὑτικαῖς BCPS: om. a 17 οὐσίαις a 18 τῷ scripsi: τὸ libri σώματι Ra 19 ψευδεὶς A1 20 τι ὂν] τινι Ra 22 ποτε ldeler: τότε libri 27 fortasse ⟨ἂν⟩ ἦν 28 ὁποίαν] ὁποία ἂν ⟨ᾖ⟩ Diels: ὁποιαντινοῦν (om. τὴν) Schwartz γενομένην ldeler 32 δὲ addidi alt. τὴν Apelt: τῇ libri tert. τὴν om. a 34 τὸ] τῷ Ra: fortasse del. τοῦ om. a δεσμώτης—πνεύματος om. Ra 35 συνδεόμενα Apelt 36 μὲν s. v. A
marginal XI
footnote 1 δι’ scripsi: δ’ libri 2 ἀπαθὲς δὲ] εὐπαθὲς Schwartz 3 δ’ om. BCPS 4 μάλλιστα AB 5 ἀρεστὴν] ἀρίστην Diels τὴν s. v. A 8 ἔχοιτο Ra 11 πάντων scripsi: τῶν libri 11. 12 πάντα φαίνοιτο] fortasse ἀπεμφαίνοι τὸ 12 ἀλλήλων om. Ra: ἀλλήλοις BS 13 λέγειν del. Ideler 14 ἀλλήλοις ldeler 16 ⟨τῷ〉 πᾶσιν ldeler 21 τοῦ om. Ra 22 ἂν τὸ] αὐτὸ a 23 ἡ om. Ra 24 τὸ] τὸν a αὐτοῦ Apelt: αὐτοῖς; οὐ libri συνέχει Idelet: συνέχειν libri CPRSa: ἢ AE ὂν Apelt: ὧν libri 25 πνεύματος ldeler κινούμενον Apelt: κινουμένου libri τί Apelt: τι libri 26 γίνεται] λέγεται Ideler: fortasse κινεῖται 28 διαλαλεῖν Ra 29 ἔχει] ἔχειν Ideler 32 alt. τε om. a αἰτιάσαιτο] αἰτιᾶσαι a: αἰτιάσαι Ideler 33 εὐλόγως om. Ideler ἐνταῦθα] ἐνθάδε Ra 34 ποιοῦντα scripsi: ποιοῦν libri
footnote 1 λέγειν Apelt: λέγει libri: λέγουσι Ideler 6 ὥσ που] ὥσπερ Ra 8 εἰ add. Apelt 9 λεγομένη Apelt: λεγομένης libri τοῖς] τῆς Ra 10 λέγοντα Idelet: λέγοντι libri 12 πεφοιτηκώς Idelet δι] τι Ra τεκνοῦν Apelt: τέκνων libri 13 ἑαυτό Apelt: ἑαυτῷ libri τε] δὲ Ideler 16 μέχρι φωνῆς ἀίδιος αὐτοῖς Schwartz: μέχρι φωνῆς αἰδοῖος αὐτοῖς A: μέχρι φωνῆσαι δ’ αὐτοῖς BCPS: μέχρι φωνῆσαι δύο αὐτοῖς Ra: εἰ χρὴ φωνῆσαι, δι’ αὐτῆς Apelt μόνοις Ideler 17 δὲ] δὴ Apelt sive del. 21 τὰ κατὰ τὰς] τὰς κατὰ Ra ἀπὸ] ὑπὸ Ideler 22 ἐπιπολῆς A: ἐπιπολλῆς BPCS: ἐπὶ πολλῆς Ra: ἐπιφανείᾳ Ideler 25 φασιν scripsi: φησάντων libri: ἔφησαν Apelt 26 ⟨εἶναι⟩ τὸ ποιοῦν Ideler 28 τῶν om. Ra 32 ἡ γινομένη] ἡγουμένη Ra ἄλλοτε om. a
marginal XII
footnote 2 γεννέσεως AC lacunam indicavi κατ’ αὐτῆς] κατὰ γῆς Apelt 3 κεχωρισμένα suspectum 5 γένεσις RSa 6 προέσεως Apelt: προθέσεως libri διὰ τοῦ σπ. Ra 7 αἴτιος add. Diels τῇ ὕλῃ] τὴν ὕλην Ra 12 φασὶ] φύσει Ra Apelt 13 ποιεῖν Ideler: ποιεῖ libri τῇ Apelt: τὴν libri πως Apelt: ὡς libri 16 ὕλῃ A: ὕλη rel. παρὰ AB: περὶ rel. 18 τῷ] τῇ a ἐστὶ om. Ra τῆς ὕλης del. A: om. a 19 ἂν om. Ra 20, 21 ἀλλάσσον R: ἀλάσσον rel. 22 εἰ R2a: ἡ rel. 29 κορόπλασθόν C¹a: κορόπλαστόν Ideler 33 χωροῦντα om. Ideler 34 lacunam indicavi. sententia quae ecidit legitur 227,23—25 προήχθω a μὲν] τῷ Ideler 35 τοῖς τοὶ a μόνοις Schwartz: νόμοις libri
footnote 1 πειρωμένους AR: πειρωμένοις Ra: πειρωμένου CPS τῆς δὲ BCP: τῆσδε AARSa 5 λόγος RS: λόγοις ABCPa 6 πολυθλύλλητος A 7 δὲ] fortasse τήνδε 8 ἔτι τε] εἴτε Ra: εἴ γε Apelt τὸ scripsi: ὁ libri: ὁ ⟨λόγος⟩ Apelt 9 αὐτοῖς om. Ra 10 τούτου δὲ ibi τοῦτο δὲ Apelt τοῦ scripsi: τὸ libri 11 πείσματα] πύσματα Ra περὶ BGPSa 12 λεγόμενον Ideler περὶ BCPSa 13 ἂν Apelt:  αἱ libri ᾖ] εἰ a 14 μὲν delevi 16 ἐθέρμανε Diels 18 ἔξωθεν] ἔξω μὲν Ra 19 δὲ om. Ra 20 τῷ σιδήρῳ om. Ideler 21 φλόγα RSa: φλόγαν ABCP 23. 24 καὶ—ταῦτα circumscripsi, cf. 226,34 24 τὸ ante τὴν om. Ideler ταῦτα ⟨ἄτοπα〉 Ideler 26 πυρὸς ἐξάπτεται Ra 27 τινός om. Ra εἰ Apelt: ἢ libri φυλάσσειν A2Ra 28 ⟨καὶ〉 ἐφ’ Ideler ἧς ὂν Schwartz ὅσον libri ἐπλησίαζε Ra 28, 29 οὕτε τὰ scripsi: οὐ τά τε libri: οὐδὲ τὰ ldeler 29 pr. οὔτε scripsi: οὐδὲ libri 30 δὴ χωριζόμενον scripsi: διαχωριζόμενον libri 32 ἢ] ἡ A 33 αὐτός Ideler: αὐτή libri
marginal XIII
footnote 1 πυρὶ γίνεται] περιγίνεται a τις corr. ex τῆς A 7 ἀνάξιον Ideler ἡ add. Ideler 8 εἰρημένα A1 δὴ] δὲ Ideler 9 ποι᾿ ἐστίν Ra: τότ᾿ ἔσται A: τότεστιν Η BCPS 10 αὐτῆς] αὐτῶν Ra 12 ἀποσκευάσεται Diels: ἀποσκευάσαι τε libri 13 〈δὲ〉 δὴ ldeler 15 τοιούτων PSRa χωριστὸν Apelt: χωρὶς τῶν libri 16 ἂν om. a 23 οὔτε scripsi: οὐδὲ libri 25 τόπον] τότε BPS 30 fortasse σύνθεσιν ⟨γένεσιν⟩ 32 πυρῶν corr. ex πυρὸς A 35 περικειμένων Ra 36 εὐχωρίστοις vel εὐδιαιρέτοις Diels 37 τῶν om. ldeler
footnote 2 καίτοι BR2a: καἰ τι rel. 3 μὲν] fortasse μένει τοιαῦτα CPRS ταῦτα ABa 5 οἷόν τε Ra: διά τε S 5. 6 ἐστὶν— ἀλλήλων om. Ideler 8 δύναται Ideler: δύνασθαι libri 9 ἐκκοινώνηκεν] R Ideler: ἐκκοινώνημεν a 10 τῆς αὐτῆς] τῆς B: τοιαύτης a: τῆς τοιαύτης Ideler ἐκκοινωνηκότων Ra 11 ἐναντίωσιν] αἰτίωσιν Ra 12 οὐδὲ scripsi: οὔτε libri 14 πάντῃ] πάντα Ra 16 ἀντιπάσχειν ⟨μηδὲ〉 ldeler: fortasse ἀντιπάσχειν εἰ μὴ διὰ τὸ〉 18 ἔχει] ἔχε A: ἔχειν B οὔτε scripsi: οὐδὲ libri 20 καθὸ ὑγρόν om. a 21 ἐναντία A1 Apelt: ἐναντίοις rel. ἐναντίοις] ⟨ἐν⟩ ἐναντίοις Apelt: ἐναντίους ldeler: ante ἐναντίοις fenestra 15 litterarum A: 20 litterarum BC: fortasse ἀλλ’ 〈ἔστι τὸ ἀντιπάσχειν μόνον ἐν τοῖς⟩ ἐναντίοις 24 ἐστι τῷ] fortasse ἔνεστι τὴν 30 γοῦν] γὰρ in ras. C 34 πυρὶ semel ldeler μὲν s. v. A: om. BCPS τὸ εἶναι om. Ideler
marginal XIV
footnote 1 ὡς πυρί τε scripsi: ὡς πῦρ ἐστι Apelt: ὥσπερ είτε libri διαφέροντι] διαφέρον τι Apelt 6 ποιεῖ τὰς Apelt: ποιεῖται libri 8 αὑτὸ scripsi: αὐτὸν libri 8 κατισχύῃ Apelt: καὶ ἰσχύει libri 11 fortasse δὲ 〈τοῦ,〉 εἰς 16 ἀλλὰ] fortasse οὔτε 17 καὶ del. Apelt τὸ τρεφόμενον scripsi: τῷ τρεφομένῳ libri 18 μεμιγμένα Apelt: μὴ μιγνύμενα libri 20 λέγειν διαφοράν addidi 26 ὅταν] ὅτε Ra 27 ἔχῃ scripsi: ἔχει libi 31 ἀποβάλλοντα Ra τὰς κατὰ Apelt: κατὰ τὰς libri: καὶ τὰς Ideler 33 γενήσει Ra
marginal XV
footnote 3 προσήκῃ scripsi: προσῆκε libri ἄλλη Ra 11 περικειμένων Ra 12 θᾶττον A2 13 διαιροῦντα] διαιροῦν Ra πρὸ BCRS: πρὸς APa 14 περιτιθέμενα Ra 17 πᾶν τι Ideler: παντὶ libri τοσοῦτον BCPS: τὸ σοῦτο A¹: τοσούτων A2: τοσούτῳ Ra τοῦ Apelt: τὸ libri: τῷ Ideler 19 αὐτῶν om. PRa ὀλίγης] ὀλιγάκις Ra: ὀλίγης τινὸς Apelt 19. 20 πρὸς αὖ τὴν Apelt 20 ὃς ἦν γε αὐτῶν ABCPS: ὅς ἦν γε Ra: ἤν γε Idelet, qui ante ἢν lacunam esse statuit: ὅση γε Apelt χωριεῖ Apelt 20, 21 πάντῃ ἀχώριστα Apelt recte ut videtur, reliqua ita constituerim [τῆς] πρὸς ⟨τὴν⟩ αὐτῶν εἰς ταύτην (scil. δύναμιν) μεταβολήν, ὅσα γε αὐτῶν τοιοῦτο χωρεῖ, 〈ἐπεὶ⟩ μὴ πάντῃ ἀχώριστα τὰ κεκραμένα 21 τὰ om. Ra εἰς] πρὸς Ra 24 τοῦ circumscripsi 26 καὶ οὐ Ra 27 ἀπὸ circumscripsi τοιούτου corr. ex τοσούτου A 28 μεταβάλλοντος (sc. τοῦ κράμ.) εἰς τὸ τὴν ἀρ. Diels 30 τι delevi
footnote 5 χωριζόμενον Apelt τοῦ γλεύκους] τοὺς λευκοὺς A1 ὁμοιομεροῦ ldeler 6 προελθοῦσα Ra αὐτοῦ] αὐτῶν Ra γεννᾶ τε Apelt: γεννᾶται libri 8 fortasse κατέχεσθαι ⟨σώματι τὸ⟩ 9 εἴρηται] 223,19 πρὸς Ra γεννώμενον Apelt 10 ἀπὸ] fortasse ἐπὶ 14 ἔχει] εἶχε ldeler μεταβάλλοντος BRa 18 τοιαύτης a ἢ del. Apelt 19 διακρίνασθαι a 21 ὅμοιος ldeler: ὁμοίως libri ἐπὶ τῶν ἀλλήλοις scripsi: ἐπὶ τοῖς ⟨τῆς a) ἀλλήλων (ἀλλήλοις A2) libri: ἐπιπολῆς ἀλλήλων Apeit παρακειμένων] περικειμένων Ra: περιθέσεως κειμένων Ideler 22 αὖ τῷ scripsi: αὐτὰ lilbri: ὁ αὐτὸς Ideler: αὐ Apelt τῶν scripsi: τῷ libri 25 τὸ ἐναντίον Ra 26 ταὐτὸν] ταὐτὰ ldeler 27 ὑποκείμενον BCP τοῦ] τούτου Ideler πόσον ldeler 29 ἐκκρίνεσθαι Apelt 30 ὑπ’ δι’ a ldeler 32 fortasse γίνεσθαι
marginal XVΙ
footnote 1 κοινοὺς a 1. 2 Ἀριστοτέλους] Ra 2 λόγου a 8 τὰ addidi διαιροῦντά Schwartz: διαιρεῖταί libri 4 εὐπαθέστερα Apelt: ἀπαθέστερα libri 5 ὁμοιότητας] fortasse ποιοτητ τας 7 τῆς] τὰς Ιdeler 8 fortasse ὑγρὰ ⟨γὰρ⟩ 10 τύχοι] τύχη a 11 κουφοτάτου Ra 13 ἑνοῦσα] ἐνοῦσα sic A: ἐνοῦσαν Ρ 15 αὐξήσεσιν, ⟨καὶ περὶ τούτων διαλεκτέον〉 ideler εἰ scripsi: ἡ libri 16 αὔξησις delevi τροπῆς a πάντῃ] fortasse πάντ α 17 ὑπάρχοντι A¹BPSC (signo praeposito): προυπάρχοντι A2Ra 17 et 18 πάντῃ] fortasse παντὶ 18 μὴ scripsi: μίαν libri πρὸς ἐνεχθεῖσαν a: προσενεχθεῖσαν ldeler 23 φέρε καὶ ⟨νῦν ἀποδειξώμεθα⟩ ἐκθέμενοι ldeler: fortasse φέρ’εἴπωμεν ἐκθέμ ενοι ἐκθέμενοι BCPS 27 ἔχει coll. post ἀὑοῖς Ra δὴ] δεῖ Apelt 28 ὑπάρχει scripsi: ὑπάρχειν libri δεῖ ldeler: δὴ libri τοὺς 2Ra: τῆς A¹BCPS 29 ὄντα om. Ideler 32 αὐξάνεσθαι Ra ἔτι τε οὐ scripsi: ἔτι τε libri: ἔτι δὲ ldeler: οὔτι δὲ Αpelt 33 fortasse ⟨καθ’〉 ἕν τι: ἐστι Αpelt
footnote 1 αὐξανομένων RSa 2 τῶν om. Ra ταὐτὸν Apelt: τοιοῦτον ldeler: τρίτον libri 5"εἰς] fortasse ⟨εἰ καὶ⟩ εἰς fortasse μεταβάλλει μεῖζον A1 6 λέγεται ⟨οὔτε τῶν⟩ Apelt 7 ἐκ] fortasse ἐπὶ 9 τῶν om. a 10 ἐπιτελούντων Ra ὑπομένον scripsi: ὑποκείμενον libri 12 αὐξανομένη Ra 14 δὴ scripsi: δὲ libri 14. 15 προκριτικὴ Ra 15 ἐστιν ἐν τούτῳ. ⟨τούτων⟩ scripsi: ἐστιν. τούτων Apelt 16 ἐπεὶ] ἐπὶ? προστιθεμένμ scripsi: προστιθεμένου libri τὸ add. Diels 19 μὲν ⟨οὐ⟩ Apelt 20 intellegerem λέγουσι ⟨τὸ αὐξῆσαν αὐτὸ μὴ λέγειν⟩ κατέχειν τόπον· [οὐ] κατεῖχε δὲ 23 δὲ Apelt: τε libri 24 γινόμενον σώματι] fortasse δεχόμενον σῶμά τι 28 αὐτὸ] αὐτοῦ Apelt δ’ om. BCPSR 30 τούτῳ scripsi: τοῦτο libri 32 post αὔξεται add. Ideler: κενὸν ἄρα κατὰ πάντα 33 τε] δὲ a 34 πρῶτον ⟨μὲν⟩ Ideler λαβεῖν] λέγειν Ra
footnote 2 ὁμοιομερῆ A1 2. 3 τὰ δὲ—καὶ ἀνο add. A2 in mg. 4 τε] τις Ra μῦς a: ex corr. AR: om. BPS: om. cum indicio lacunae C 5 pr καὶ om. Ra 6 ἀνομοιομερῆ A2 Ra: ὁμοιομερῆ A1B (post ὁ spatium 2 litt.) GPS 6. 7 ἐκ προσώπων scripsi: εἰς πρόσωπον libri: ἐστι πρόσωπον sive ἐκ προσώπου Apelt 10 εἰς καὶ σ. κ. Ra 14 δεῖ Diels: διὸ libri 17 δὲ a 23 λέγωμεν a 24 ἀπὸ] αὐτὸ Ra τὸ εἶδος] τοῦ εἴδους Ra 25 μαρτηροῦμεν Ra 29 κατὰ τὸν ἀρ. Ιdeler 30 ἔστι μένον] ἔτι μενον Ιdeler: εἴ τι μένοι Apelt: fortasse ἔ στ’ ἄν τι μένῃ cf. v. 34 32 αὐτοῦ Apelt: αὐτὸ libri 32. 33 ἐν τῷ τοσῷδε pelt: ἐντὸς τόσῳ δὲ libri 33 μεγέθη Ra ὃ οὐ Apelt: οὐ libri εἴδη a 34 ὃ Αpelt: οὐ libri
footnote 2 μὲν om. Ra λέγῃ corr. ex λέγει A1 3 τὸ τὸ ACPSa: τὸ RB αὐξανόμενον a τὸ τὸ αὐτὸ A 4 τὸ om. Ra 7 αὐτοῖς] corr. in αὐτοὺς B : αὐτὰ Ideler 9 τῷ Apelt: τὸ libri 11 τῆς αὐτῆς ὕλης Ra 12 ⟨ἢ⟩ σώματος Ideler 13 εἰ καὶ ldeler: εἶναι libri: om. a cum indicio lacunae 17 τῇ] τῆς σαρκὸς Ideler 18 σώζει ldeler: σώζειν libri 22 ἐπιρρεούσης a πρὸτότε (25) om. Ideler 26 ποσή A2R: πόσει A1: ποσ. BC: ποσ PS: πόση a τὸ Ra συναύξειν ldeler μὴ del. ldeler 27 πάντως A: πάντη. BCPS: πάντα Ra 29 alt. τὸ om. Ideler 34 fortasse ὅταν τὸ ἀεὶ⟩ ἐκ om. Apelt μένει Ra προσετάθη Ra
footnote 3 τοῦ Αpelt: καὶ libri 4 ἔχοντα] ἔχον τὸ Ideler μείνῃ] μένῃ Ideler ἔχει] εἶχε Ideler 6 τὸ om. Ideler 8 τι Diels: ἢ libri: del. Αpelt 9 τοῦτο Αpelt: τὸ ὑπὸ libri: del. Ideler 10 ἄνωθεν ⟨ἐν⟩ Schwartz 11 πρὸς αὐτὸ] πρὸ αὐτοῦ Apelt 13 fortasse κατὰ ⟨τὸ⟩ τοῦ 14. 15 φυλάσσειν ἡ γῆ Ra 16 γίνεσθαι delevi αὐξανομένων BPRa 18 γενέσθαι Ra 19 ἄλλου προωθοῦντος Apelt ἀλλ’ οὐ προοδοῦντος libri 21 ὁμοιομερῶν Apelt: ἀνομοιομερῶν libri 21. 22 σχήματος Ra 22 pr. τῶν] τῆς Ra ὁμοιομερῶν A (corr. ex ἀνομοιομερῶν) Ra: ἀνομοιομερῶν CPS 23 σχήματα A : σχηματι rel. 26 δεῖ Αpelt: διὰ libri 27 τῆς om. a 28 εἰ ⟨ὕδωρ πρὸς⟩ οἶνον sive εἰ ⟨ὕδωρ ἢ⟩ οἶνον Diels τις Ra: τις εἰς A: τις εἰς BCPS διὰ om. A1 29 ὑγρότητος Ra μαλακότητος Ra 31 Ra: ἦν ABCPS
