@node
@author=Herodianus
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=August Lentz
@filename=tlg0087.tlg022.1st1K-grc1
@funder=Harvard Library Arcadia Fund
@principal=Gregory Crane
@publicationStmt=Harvard College Library, tlg0087.tlg022.1st1K-grc1.xml.
@respStmt=Digital Divide Data, Corrected and encoded the text, Gregory Crane, Editor-in-Chief, Perseus Digital Library, Matt Munson, Project Manager (University of Leipzig), Annette Gessner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig) 2015 - 2017, Bruce Robertson, Technical Advisor
@sourceDesc=Herodiani Technici Reliquiae, August Lentz, Aelius Herodianus, Teubner, Leipzig, 1868, 2, Grammatici Graeci, 3.2.1, Hathi Trust.
@sponsor=University of Leipzig
@title=Περὶ τῶν εἰς μι
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:58:24Z

10936	footnote 1. 25 posui ἐϲμί pro εἰμί, cui Gaisf. substituere vult ἐμμί. l. 45 οὐ post ὅπερ eieci.
footnote 1. 34 παραγωγοί pro παράλογοι posui.
footnote 1. 2 cf. Orthogr. fr. 27. l. 22 τινῶν ex cod. Βarocc. inserui, l. 24 ὑπέρ τινων scripsi pro ὑπὲρ ἦν, caeterum in καὶ πῶϲ, ἤκουϲαν ήμῶν, δέδωκεν ἡμῖν accentum mutavi et I, 28 οὐ ante περιϲπᾶται inserui.
footnote 1. 17 πῶϲ ἐϲτε scripsi pro πῶϲ τε [ὑμῶν]. l. 27 γηρέντοϲ scripsi pro γηρόντοϲ collat. E. M. 230, 50, qui locus fluxit ex Herodiani libro περὶ παθῶν; ibi Xenophanes pro teste participii γηρέντοϲ citatur: ἀνδρὸϲ γηρέντοϲ πολλὸν ἀφαυρότεροϲ. Alterum participium γηράϲ ἀπὸ τοῦ γήρημι δευτέραϲ ϲυζυγίαϲ ibidem profertur. cf. Buttm. Il p. 138. — l. 29 ἔραμαι scripsi pro ῥέραμαι. inclinamentis secundae coniugationis accedunt et δίδη E. M. 273, 4: ἀπὸ τοῦ δέω διδῶ παραγωγὸν δίδημι τὸ δεϲμῶ. ὁ παρατατικὸϲ ἐδίδην ἐδίδηϲ ἐδίδη, ὅθεν καὶ «δίδη μόϲχοιϲι λύγοιϲιν» Ἰλιόδοϲ (105) et γέλαν E. M. 225, 7. l. 31 cf. Mon. 23, 15 δίδωμι: οὐδὲν τῶν εἰϲ μι ληγόντων ῥημάτων τῆϲ τρίτηϲ ϲυζυγίαϲ κατὰ χρῆϲίν ἐϲτιν Ἑλλήνων ἐπὶ ἐνεϲτῶτοϲ χρόνον, ἀλλὰ μόνον τὸ δίδωμι. νῦν γὰρ τοὺϲ Αἰολεῖϲ παραιτούμεθα (de quibus Choer. 844). l. 35 — l. 4 pag. seq. inserui, quum
footnote origo Herodianea non dubia sit cf. Lehrs Herodian. p. 78. l.6 de ἔδυν cf. E. M. 290, 1. ἐκχύμενοι scripsi pro ἐκχυνόμενοι, 1. 8 πέπειϲθι exhibui pro πέπειθι cf. Hermann. ad Aeschyl. Eum. 589 et Βuttm. II 24. κέκραχθι pro κέχραθι scr., verbis καὶ ἄλλα πολλὰ intelleguntur κέκλυθι ἄνωχθι τέθναθι δείδιθι (E. M. 260 25). —ln cod. sunt: ἀπὸ μέντοι περιϲπωμένων οὐχ εὕρομεν χρῆϲιν αὐτῶν· ἑαυτοῖϲ δὲ φωνὰϲ περιτιθέντεϲ τὸ νενοηθέν, emendavi ex Herodiani sententia, qul perfecti et plusquamperfecti imperativum in θι exire existimavit, in ε finiri negat cf. περὶ ῥημάτων fr. 37. l. 11 Αhrensii emendationem πάθοϲ pro ἔθοϲ non necessariam arbitror, caeterum idem pro κέκλυϲε et κεκλύκω scribendum esse κέκλυκε et κεκλύκω vidit do dial. Dor. p. 328. Ex hoc loco fluxerunt E. M. 253   οἷον δέδοικα δεδοίκω ὡϲ ὄλωλα ὀλώλω, Ζon. 186, ubi βέβρωθα βεβρώθω pro ὄλωλα ponitur; Epim. cod. Coisl. 387 in An. Par.IΙΙ 295,1 μεταβάλλει τὸ τέλοϲ Ϲικελικῶϲ (sc. μέμονα μενοινῶ) ὡϲ τὸ λήθω λέληθα καὶ Ἰακῶϲ λέλαθα· τὸν οὖν λέλαθα παρακείμενον οὑτοι λελάθω λέγουϲιν ὡϲ τὸ πεποίηκα πεποιήκω, ἀφ’ οὗ καὶ «ἐκλέλαθον κιθαριϲτύν» (Β 600) καὶ ἀπὸ τοῦ βρωθῶ βέβρωθα μεταβόλλοντεϲ λέγουϲι βεβρώθω «ὠμὸν βεβρώθοιϲ Πρίαμον » (Δ 35); Ep. Cr. I 374, 23 ταῦτα ϲυνεχῶϲ Ϲυρακουϲίοιϲ, ἀλλὰ καὶ παρ’ ἡμῖν ἕϲτηκα καὶ ἑϲτήκω, ὁ μέλλων ἑϲτήξω «ἑϲτήξειν δὲ τὸ τεῖχοϲ ἐπ’ ἀρχαίοιϲι θεμέθλοιϲ» (Callim.hymn.in Apoll. 15)καὶ ἀπὸ τοῦ ἐγρήγορα ἐγρηγορῶ. περὶ μον. 43, 33 δειδίω non a δίω duphlicatum, sed ex δείδια transformatum dicitur; κεκλήγω, πεπλήγω affert Arcad. 151,1.Il.Pr.Μ 125. 1. 22 de εἰϲ cf. Mon. 44, 23, de ἐϲϲί Mon. 44, 16 accuratissime forma ἐϲϲί explicatur in An. Paris. III 338, 37.
footnote 1. 1 καὶ ὁ Ἡρωδιανὸϲ huc retuli ex p. 857, 19, ubi eadem leguntur; cf. περὶ ὀρθογραφίαϲ fr. 49. l. 4 in Choer. p. 852, 33 post τὸ εἶ nonnulla deesse mihi videntur ἔνιοι λέγουϲιν, ὅτι ἐκ τοῦ εἰϲ inserui.
footnote 1. 3 λέγειν ante λέγει inserui, ita ut ὁ αὐτόϲ non ad Apollonium referendum sit, sed ad Herodianum , qui Apollonii sententiam attulerat eique suam etiam ex Il. Pr Z 336 notam opposuerat; sed nomen Herodiani in praecedentibus sive Choerobosci neglegentia, qui Herodianum in mente habens eius nomen ponere oblitus est, sive librarii intercidit. Sed licet ὁ αὐτόϲ ad Apollonium pertineat, non dubito, quin idem senserit Herodianus. l. 11 de ἐϲτί cf. Mon. 23, 29.
footnote 1. 8 de ἐϲμέν et ἐμέν cf. Mon. 23, 32. l. 20 cf. περὶ ῥημάτων fr.   l. 30 de «παῖδα ἔντα» v. Ahrens dial. dor. p. 324, qui propter παρέντων, quod apud Alcmanem erat, hoc fortasse eidem Alemani tribuendum conicit.
footnote 1. 9 quod contra Choeroboscus dicit in illis accusativis non synaeresin locum habere, sed homophoniam cum nominativis et Apollonius citatur docens diphthongos non dissolvi nisi in eas vocales, ex quibus constarent , neque ει in τιθεῖϲι in εα dissolvi posse, quia ει non ex his contractum sit. Tum Choerob . 862, 22 περὶ γὰρ τῆϲ αἰτιατικῆϲ τῶν πληθυντικῶν ὦν παρέθετο ὁ Ἡρωδιανὸϲ εἰρήκαμεν, ὡϲ οὐκ ἐγένετο κατὰ ϲυναίρεϲιν, ἀλλ’ ὁμοφωνία ἐϲτὶ τῆϲ εὐθείαϲ πληθυντικῶν. Sed Herodianus etiam aliam tuendarum distractarum specierum τιθέαϲι διδόαϲι ζευ γνύαϲι rationem iniit.
footnote 1. 5 praeceptum de ἐδίδουν transiit in E. M. 316, 20 cf. etiam An. Paris. III 312, 10 ἰϲτέον ὅτι τοῦ τίθημι καὶ ἵημι καὶ δίδωμι οἱ παρῳχημένοι μᾶλλον ἀπὸ τῶν εἰϲ ω εἰϲὶν ἐν χρήϲει ἤπερ ἀπὸ τῶν εἰϲ μι οἷον «ὥϲ εἰπὼν ἐν χερϲὶ τίθει» (γ 51) καὶ «ἐδίδουν αὐτῷ ῥαπίϲματα» (Ev. Joh.19, 3) l. 24 de ἦα et ἔα Ιonicis
footnote imperfeeti formis cf. Il. Pros.Ε 887 τὸ ἔα Ἰωνικόν ἐϲτιν ἐκ τοῦ ἦν γεγονόϲ. διὸ ϲυϲταλτέον τὸ α ὁμοίωϲ τῷ «τοῖοϲ ἔα ἐν πολέμῳ» (ξ 222) ὃ καὶ διὰ τοῦ η λέγεται «οὐκ ἀποφώλιοϲ ἦα οὐδὲ φυγοπτόλεμοϲ» (ξ 213). l. 33 supra Choer. 670, 14 ═  περὶ ῥημ fragm. 31, not. δάμνω scriptum cst l. 19 cf. περὶ ῥημάτων fr. 6.
footnote 1. 10 ἄλλο ante ἀλλὰ inserui, potui etiam scribere ἄλλο τοῦ. l. 37 potius οἶκαϲ; cf. Bergk, frg. Alcm. 76, Lehrs ad Hdn. Mon. 24, 9. . 44 Bekker. Anecd. p. 1294 edidit τόκων ἔχων τόκουϲ.
footnote 1. 8 cf. Il. Pr. Δ 222 πᾶϲ δεύτεροϲ ἀόριϲτοϲ ἐπὶ τῶν εἰϲ μι μακροκατάληκτόϲ ἐϲτιν ἔγνων ἑάλων ἐξέτρων ἔτληνἔϲτην ἔδην ἔφην· ἔφυν ἄρα καὶ ἔδυν. de ἕκτην cf. Il. Pr. Δ 319. l. 10 cf. Choer. 873, 21 seqq.
footnote 1. 3 codd. habent Ἰωνικῶϲ, καὶ. l. 10 cf. Il. Pr. O 10, Ω 84.
footnote 1. 48 cf. περὶ ῥημάτων in sectione περὶ ἀπαρεμφάτων.
footnote 1. 7 de infinitivο εἶναι i. q. ἰέναι, quem veteres sumpserunt, cf. Hauptium in Herme I p. 251. l. 10 de imperativo ἵϲτη cf. Herod. περὶ παθῶν in E. M. 447, 56, de ectasi vocalis in δίδωθι Schol. HM ad Od. γ 380: ἵληθι. ἀπὸ τοῦ ἵλημι. διὰ δὲ τὸ μέτρον ἐκτέταται ἡ παραλήγουϲα ὡϲ ἐν τῷ «δίδωθι δέ μοι κλέοϲ ἐϲθλόν». ὑγιῶϲ οὖν Καλλίμαχοϲ ἔκλινεν «ἵλαθί μοι, φαλαρῖτι πυλαιμόχε». E. M. 749, 50 ἐκ τοῦ θνῶ γίνεται κατὰ ἀναδιπλαϲιαϲμὸν τεθνῶ, ἐξ οὖ τέθνημι ϲυζυγίαϲ δευτέραϲ τῶν εἰϲ μι, ἡ μετοχὴ τεθνάϲ τεθνάντοϲ καὶ τὸ εὐκτικὸν τεθναίην τεθναίηϲ. τὸ προϲτακτικὸν ἐνεϲτῶτοϲ τέθναθι. ὅτι δὲ ἐνεϲτώϲ ἐϲτι τὸ τέθναθι, δείκνυται ἐκ τοῦ εἶναι βραχὺ τὸ ᾱ· εἰ γὰρ ἦν δεύτεροϲ ἀόριϲτοϲ, ὤφειλεν εἶναι μακρόν. — De imperativo ἴθι cf. Schol. BAL ad ll. B 8 βάϲκ᾿  ἴθι: ὁ Ἡρωδιανὸϲ μέν φηϲι τὸ ἴθι ἐνεϲτῶτοϲ νῦν, Ἐπαφρόδιτοϲ δὲ ἀορίϲτου. — De ἔϲθι cf. Ep. Cr. I 207, 15, ubi Hecataeus pro teste huius formae citatur. Verisimile est hoc loco Herodianum etiam alteram imperativi ἴθι formam, εἶ, protuhisse eo fere modo, quo in E. M. 347, 57 ἔξει ἀντὶ τοῦ ἔξιθι. ἐκ τοῦ εἴω τὸ πορεύομαι παραγωγὸν εἶμι. παρατατικὸϲ εἰν, τὸ δεύτερον εἶϲ, τὸ τρίτον εἶ. καὶ ὥϲπερ ἀπὸ τῶν εἰϲ ω γίνεται προϲτακτικὸν ἐκ τοῦ τρίτου προϲώπου τοῦ παρατατικοῦ, οὕτω καὶ ἀπὸ τοῦ εἰϲ μι ϲχήματοϲ Αἰολικὸν καὶ Ἀττικὸν οἶον ἵϲτη ἀντὶ τοῦ ἵϲταθι καὶ ἐμπίπλη ἀντὶ τοῦ ἐμπίπλαθι. οὕτω καὶ ἐκ τοῦ τρίτου προϲώπου τοῦ παρατατικοῦ γίνεται εἰ, ἐν ϲυνθέϲει δεύτερον προϲτακτικοῦ «ἔξει τὸν ἀϲκάντην λαβών» (Aristoph. Nubb. 633) ἐκ τοῦ ἔξειμι ϲυνθέτου ϲχήματοϲ τῷ εἰρημένῳ τρόπῳ. l. 15 διὰ τοῦ ντ κλινομένη verba omisi ut ab Herodiano aliena, qui eiam perfecto, proper quod a Ϲhoerobosco haec verba adduntur, exitum θι attribuit.
footnote 1. 1 inserui verba διὰ τί δὲ οὐκ ἔχει —1. 15 καὶ οὐκ ἐγένοντο εἰϲ θι τὰ προϲτακτικὰ αὐτῶν ex p. 874, 22 —875, 8.
