@node
@author=Libanius
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Richard Foerster
@filename=tlg2200.tlg00550.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane
@publicationStmt=University of Leipzig, tlg2200.tlg00550.opp-grc1.xml.
@respStmt=Gregory R. Crane, Editor-in-Chief, Perseus Digital Library, Digital Divide Data, Corrected and encoded the text, Matt Munson, Project Manager (University of Leipzig), Annette Geßner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor, Greta Franzini, Project Manager (University of Leipzig), 2013-2014, Frederik Baumgardt, Technical Manager (University of Leipzig), 2013-2015, Simona Stoyanova, Project Manager (University of Leipzig), 2015, Project Assistant (University of Leipzig), 2013-2014
@sourceDesc=Richardus Foerster, Richard Foerster, Libanius, Declamationes XXXI-LI, B.G. Teubner, Leipzig, 1913, 7, Internet Archive.
@sponsor=University of Leipzig
@title=Declamatio 50
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:57:55Z

4519	marginal RIV 841
footnote Mon = Codex Monacensis gr. 96 Va = Vaticanus gr. 82 Α = Ambrosianus L 64 Ma = Matritensis 4679, olim N-49 Cl = Bodleianus Miscellaneus 208, olim Claromontanus Β = Barberinus II 41 (Vatic. Barb. 220) 1 Harpocr. s. v. βουλεύσεως 1 Ἐγράψατο — 3 νόμον spatio relicto om Va | παῖδα Ma  ὁ  sed αιδ supra ras 2 litt m2 2 ἄκριτος ΑΒ 3 τῶν Mon 4 οὖν inser Va2 | εὐτυχέστερον Ma sed in ras minore m2  om VaAClB | ὦ ἄνδρες Ma sed in ras minore m 2 6 μὴ  δ’ libri Re 7 ποιήσασθαι, φανερὸν ἐπεὶ Β | εὔξασθαι —  9 διαφυγεῖν praemissis verbis τῆς μελέτης ἐν ᾖ παῖς παρὰ πα- τρὸς γραφεὶς βουλεύσεως ἀκρίτως ἀποθανεῖν ἀξιοῖ citat Macarius  Chrysoc. fol. 78 (Villoison Anecd. II 11; Reisk. Lib. t. I p. XXV) 8 δὲ om Α 10 ἄνθρωπος in lac 6 — 7 litt om A | ἱκα- νὸς Mon A
marginal RIV 842
footnote 1 εἰς ὑμᾶς om VaA | εἰς inser Ma 2 εἰ Mon | ἦττον  2 ἐν inser Re om libri 3 ὦν ἐσπούδακα τυχεῖν scripsi e  VaAMaClB cum lacobsio Lect 157 Schul ὢν ἐπούδα κατα- τυχεῖν Mon ὢν ἐσπούδακατα τυχεῖν Re 6 ἐξελόμενον A |  παραδώσεται VaB παραδόσετε Ma 8 πρᾶον MonAB  12 ἠγανάκτησε τις Ma 15 δοίην scripsi e Β δοῖεν reliqui  libri Re 17 ὑπομεῖναι Ma sed ὕπο inser m 3 | σιωπὴ scripsi  e VaAMaClB cum Cobeto Coll 303 σιωπεῖν Mon Ee σιωπῶν  lacobs Lect Schul 18 εἰ ετί Mon 20 ὑφεστηκότα Ma sed  ν in ras m3 | τ(??) ἐναντί(??) A
footnote 7 Her. VII 168, 3; 211, 1; VIII 29. [Andoc.] Alc. § 4 p. 29, 18 1 τε om MaClB 4 αὐτὸν Va | μὲν om Va 7 οἴσεσθαι  scripsi cum Sinteni coll. 11. 11. οἴεσθαι libri Re | τοῦ om A 10 γίνεσθαί Β 11 ἡ ante νὺξ MonVa delevi cum Sin- teni 12 οὐδεὶς inser Ma3 om VaAClB | με om VaMaClB  | ὀργὴν inser Ma 3 om VaAClB 15 ἐμοὺς ClB | τίς Mon  ταὐτὸ AMa 16 ἐμοὶ in ras Ma3 17 ἑτέρους A 19 δια- φέροντος A 21 μὴ inser Ma2
marginal RIV 843
footnote 16 cf. p. 615, 17 21 cf. p. 615, 20 sq. 1 γενόμενος ηὐξήμην post prius ἔδει del et post alterum in  marg inser Ma 2 | ηὐξόμην scripsi e VaClB ηὐξήμην AMa Re  οὐξήμην Mon 3 ὑπὸ reposui e libris sed παρὰ ὑπὸ Mon  παρὰ Re Ι πάντη Cl 6 ἔτι Mon 7 παρ’ ἐμοῦ] ἐμῶν A 8 κἂν ΑΒ Ι διδασκάλοις MaCl 9 ἑταίρους Α 11 ποι- οῦντα AMaClB 13 οὐδὲ A 14 ἀναλίσκειν Α ἁλίσκων Va  | εἰς τὰ ἱερὰ coni lacobs Schul | ἀπὸ τοῦ πατρὸς inser Ma3 17 signum interrogationis posui coll. p. 615,11 comma Β  punctum reliqui libri Re 19 ἐνηλικιωτῶν Α 21 τοῖς  Ma sed οἶς suprascr m3
footnote 6 Isocr. Panath. § 25 p. 238 b 10 cf. p. 563,6; 388,10 3 δυνατώτεροι Α 4 καὶ post μὴ Mon Re et inser Ma  delevi 6 πεπλησμέναις Α 9 πρὸς om Α 10 ἐξεπο- λέμωσαν scripsi ex AMaClB ἐξεπολέμησαν MonVa Re  11 αὐτοῖς Ma sed ex ἑαυτοῖς corr m 3, Β | ῥαδίως διεπράξαντο  Α 12 ἑτέροις MaClB 13 τὰ om AMaCl | πραχθείη  14 ἄρα Α 17 παρὰ scripsi ex AMaClB περὶ MonVa Re  18 εἷπεν Sintenis | ἐπεποίηντο Α sed ν eras | comma post ἐπε- ποίητο inserui om libri Re 19 comma post παρόντων Mon  VaCl Re delevi τῶν παρόντων οὐδέν, οὐδ’ ἂν ἡμᾶς coni lacobs  Add 310 Schul | δὲ Α | πατὴρ(2) inserui e ClB om MonVaA  Ma Re 20 ἐπανῆλθεν ἐξαίφνης πολέμιος scripsi ex AMaCl  Β ἐπανῆλθε πολέμιος ἐξαίφνης MonVa Re
marginal RIV 844
footnote 1 II. μ 162; ο 397; π 125. Philostr. vit. soph. I 21 t. II  p. 32, 32 K 2 Ach. Τ. VIII 1,5 15 Arist. rep. Ath. 57, 3;  59, 3. Harpocr. s. v. βουλεύσεως. Meier-Schoemann-Lipsius, Att.  ProceB p. 384 sq. 17 Chor. p. 209,24; 211,1 ed. Boiss.  18 cf. t. I 143,18 1 τὸν μηρὸν scripsi ex AMa cum lacobsio Add Ach Τ 925  Lect App Pors 331 Schul τολμηρὸν MonVaClB Re 2 ἐνεμ- πίπλα Mon ἀνεπίμπλα Α 5 ταῖν χεροῖν scripsi e VaAMa  ταῖς χεροῖν MonCl ταῖς χερσὶ χερσὶν Re) Β Re 8 ταὐτὰ  VaA sed in hoc ~ supra ν eras | οὐδένα scripsi ex AMaClB  οὐδὲν MonVa Re 15 τοῦ om Α 16 εἷπεν scripsi auctori- bus lacobsio Schul — ad calumniatores εἶπον rettulit Lect —  ἁ  et Sinteni εἷπον libri Re 17 ἔοικε Β | ἐμβελόντες Mon  ἐμβαλόντος Α 18 τοπρῶτον Β om A | ἐρίπιζον MonVa Re  ἐ(??)ίπιζον Α I μὲν ante γὰρ Α
footnote 1 cf. t. VI 214, 6; 270, 16 18 Dem. Phorm. p. 958, 13;  Olymp. p. 1182, 14. Arist. vesp. 1353 1 ὑμέτερα Va 2 τὸν παῖδα om Β 5 διατέλους ΑΒ |  λησόντων MaClB 7 ἐλθεῖν οὐδ᾿ ἐθέλων coni lacobs Schul 8 κατεσκευακόσι scripsi ex AMaClB παρεσκευακόσι MonVa  Re 9 βουμένοις Mon sed βουλομένοις in marg Hardt  11 δέη Ma 13 με om Α 14 ζητεῖ Va 15 αὐτοῦ Mon  VaMaClB Re 16 οὐ VaMa sed in hoc οὐδὲ suprascr m 2,  ClB 17 μετρίου scripsi e MaB μέτρου MonVaACl Re |  κώμαις Μοὶ 18 κύμαις Α | ἑταίραν scripsi e Β ἑταίραν Mon  sed ἑταῖρες in marg, VaAMa sed in hoc ἀν’ in αἷς corr m2 ἐταί- ραις ACl Re ἑταίρας Cobet Coll 303 | λελύσθαι scripsi e VaCl  cum Cobeto λελύσθαι Α κελύσθαι MonMa Re in lac 6 litt  om Β κεκτῆσθαι ἔστι τὸ ὀρθὸν ὧς μοι δοκεῖ in marg Va  Allatius ἑταίραις κολλᾶσθαι lacobs Schul 9 νέων om Α
marginal RIV 845
footnote 22 cf. t. III 161, 21 23 cf. p. 724,9 6 μὲν] με Va 9 ἱκετεύω Va 10 πείθω VaMa sed in  hoc in πειθώ corr m 2, ClB | πολύ om Α 11 δεηθέντα Α  15 τοῦτο MonVaA Re 16 δακρῦσαι MonA fortasse recte at  cf. ad t. II 355, 17 17 αὐτὸν Mon
footnote 1 ὅσπερ scripsi ex AMaClB ὧσπερ Mon Va Re ὃς ἂν Sin- tenis I ἀπήνεγκεν scripsi ἀνήνεγκεν libri Re 2 αὕτη scripsi  ex AClB ἀναστῇ Mon sed αὕτη in marg, VaMa Re 3 τἀ- κείνου, τὰ αὐτοῦ scripsi τὰ κινοῦντα αὐτοῦ αὑτοῦ Β) libri Re  τἀκείνου ὄντα (vel τἀκείνῳ δοκοῦντα), αὐτοῦ lacobs Schul  5 δὲ delendum censet lacobs Lect, in δὴ mutandum Schul  6 διώκειν — 7 πατέρα om Β | ἀλλ’ — 7 ἐροῦσιν om VaA  8 εἴη in οἴει corr Cl 4 10 προβεβηκέναι scripsi ex AMaClB  cum lacobsio Schul προβεβληκέναι MonVa Re | ἐδυνήθη προσ- θεῖναι Α 13 τοὐκείνου scripsi e VaAClB cum lacobsio Ach  Τ 912 τοῦ ἐκείνου Lect) τοὐκείνου MonMa τ’ ἐκείνου Re  15 τῶν Α sed ῶν ex ἑ corr m2 | τούτοις Α 16 προσέμενος  scripsi e MaCl sed σ inser Ma2 Cl4 προέμενος MonVaB Re  προσθέμενος Α 19 ἢ] εἰ Va 20 μικρὸν Α | ἀξιῶν ἠξίουν  coni lacobs Lect | οἱονεὶ MonVaAMaCl Re
marginal RIV 846
footnote 3 κεκύκλωκε scripsi ex AClB κεκώλυκε MonVaMa Re  κέκλεικε lacobs Lect Schul 4 ἐξελῶσιν Sintenis 5 μὲν Ma  Cl | αὐτὸν libri corr Re 7 ἐξεκείνου Β 9 ἣ — 10 ἐπιθυ- μητάς citat Macarius fol. 78 (Viiloison et Reiskia 11. 11.) | ἢ Α  sed ex ὁ corr m 2 ἢ Mon ἡ παιδεία Macar 13 ἡδὺ —  16 ἐλπίδας citat Macarius fol. 78 (Villoison et Reiskia 11. 11.) 14 κἂν ΑΒ 15 ἐκείνου Α sed in εἰς ἐκεῖνον corr m2  ἐκεῖνων Mon 16 ἔδεισα Α sed ex ἐδέησα corr m 2 ἔδησα Mon 17 signum interrogationis posui cum lacobsio Schul comma  Β punctura Α om reliqui libri Re | οὐκ — φόβους om Α |  ἐνταῦθα Va | signum interrogationis posui e Β cum lacobsio  colon reliqui libri Re 18 ποιήσατε Ma sed ποιή in ras m 2 |  μοι scripsi ex Α μου reliqui libri Re 19 κρατήσατε Ma sed  τε in ras m 2 | καὶ ante τῶν VaAClB | διασειόντων scripsi e Va  AMaClB διαστειόντων Mon διαστελλόντων Re 20 signum  interrogationis post ἠγανάκτεις (1) ponendum coni lacobs Schul
marginal †
footnote 1 κἀκεῖνά scripsi ἐκεῖνά libri sed α ex ος corr Va 2, Re  3 ἀλλὰ] καὶ Ma | μαστιγῶν Ma sed corr m 2 4 δ’ Α | comma  inserui e Β om reliqui libri Re 5 τῆς πόλεως inser Ma 2  om Cl 6 τις om AMa | ἠγανάκτεις Α 7 ὡς ante ὁρᾷς libri  Re delevi 8 τιμωρίας Ma sed ς in ras m 2 τιμωρίαν Cl | τί  — 10 ἀγαθῶν citat Macarius fol. 78 (Villoison et Reiskia 11. 11.)  | τί γὰρ ἂν εἴη] οὐδὲν Macar | τίς Β 9 μὴ δ’ ΑΜαΒ Ι  reposui e libris cum lacobsio et Sinteni ἥλιόν Re 11 τοίνυν  inser Ma 2 12 ἂν inserui om libri Re 13 τοῦθ’ AMa  15 ἐστί φησι MaClB 16 αὐτοῦ libri Re 17 οὐκ inser Ma 2  | οὐκοῦν om Va οὐκ οὖν Mon Re 18 ὁ] ὁ MaBVa Ι ὁ om  VaB | οὐ κωλύει post αὐτός inserendum coni lacobs Lect „sed  vel sic apodosis deest“ num νόμος δίδωσιν, αὐτὸς ποιήσει  19 νόμου Α 20 δυναμένων Va sed γρ πειρωμένων in marg
marginal RIV 847
footnote 1 προσέμενον Ma sed σ eras, ClVa sed in hoc in προμένοντα  corr et προσμένοντα in marg m2 προσέμενεν Α 3 μὴ Cl  5 ὑμῶν scripsi e VaAMaClB ἡμῶν Mon Re 6 τὰ inserui e  libris cum lacobsio Schul om Re 8 ὅτῳ reposui e libris cum  lacobsio Ach Τ 966 Schul ὅταν Re | θάνατον Α | ᾖ post  inserendum coni lacobs Lect 9 αἰτίᾳ τοιαύτῃ scripsi cum  lacobsio Schul αἰτία τοιαύτη libri αἰτίαν τοιαύτην Re | τὴν  &lt;ἐσχάτην&gt; ζημίαν lacobs Lect | χείρω Va 10  ἀπέχεσθαι libri Re 11 τις] πατὴρ lacobs Lect 13 πολλάκις  post καθάπαξ Α | ἡμῖν ΑΒ 14 τηνάλως VaAMaClB 15 τί  libri Re | λέγειν post ἀνάγκη inserendum coni lacobs Lect,  supplendum Schul Ι εἰ ClB εἷ Va om MonAMa Re | πολλὴ οἱ  | τὰ(2) om Β 17 ἐκδράμοι scripsi ἐκδράμῃ libri Re | τί  Β τὶ Α 18 τι om Va 19 πάτερ om A 21 τε] τοῦτο la- cobs Lect Schul | δαίμοσιν Ma sed δάι in ras m2
footnote 1 ἐμοὶ in marg inser Ma2 om VaAClB 2 τῷ om Ma  Cl 4 τὰ ἀδίκημα Ma sed τὰ in ras m 2 καὶ ἀδίκημα Cl  5 κἀκεῖνο Α sed ο in α corr κἀκεῖνα VaClB κἀκείνω Mon 8 signum interrogationis posui cum Sinteni om libri Re  τί λάθρα οὐ βαλεῖ; τίς lacobs Lect Schul | οὐ καλεῖ Ma  10 ποιοίη scripsi ποιῆ libri sed οι supra ῆ Ma 2, Re 11 θῶ  Va sed μὲν add et τῷ μὲν in marg m2, AMa sed in hoc θ in  ras m 2, Β τῷ ἁ 12 ἅπαντος inser Ma 2 om VaAClB  13 μὴ δ’ ΑΒ 14 δυσχερανεῖν Mon δυσχεραίνειν VaMa sed  in hoc ἁ supra αἰ m 2, ClB 17 λυσιτελῆ Mon 18 παρέσται  scripsi auctore Sinteni παραστῇ libri Re 20 μήτε — 21 ἡλι- κίας in lac inser A 2 | οἳ MonMaCl Re | τιμῇ scripsi e  MaClB τιμῶν Mon Re τιμωροὶ lacobs Lect Schul | αὐτῶν  MaClB num αὑτῶν? 21 οἱδ’ MonMaClB Re οἳ δ’ Α οἱ  δὲ Iacobs
marginal RIV 848
footnote 9 cf. ad t. V 36, 12 12 cf. t. I 149, 19. t. IV 872, 19 R.  Plat. rep. V p. 472 A 1 οἳ scripsi e Β cum lacobsio Schul et Sinteni οὐ Mon  sed οἳ in marg οἱ MaCl Re οὐκ VaA | κἀν MaCl Re ἂν Va  Α 2 ἐν om Β | ἰλιγγυῶσιν MonVa Re 4 τί Mon |  πονθὲν Va sed πεπονθὼς in marg m 2 5 τοι om Ma  7 εὐηργετηκέναι Α cf. t. III 279, 11 | μεγάλα inser Ma 2  αἰ  Α Ι ὑμῶν Α 9 πέδας Mon 10 μυλῶνα VaA cf. ad p. 98, 4  et t II 543, 10 | post οὖν signum interrogationis posui om  libri Re | πρός τινα VaAB | τίνα Cl | ἱκετεύσω scripsi οἴσω libri  Re αἰτήσω lacobs Schul 11 τοῖσιν Va 12 τἀς Β  13 ἀλλὰ Ma sed γρ πολλὰ suprascr m 2 | τίς inserui cum la- cobsio Lect Schul om libri Re 14 τίς MonB 18 ὑπὸ  στάσεως scripsi e MonB cum lacobsio App Pors 331 Lect Schul  ὑποστάσεως VaAMaCl Re | οἷόν Ma 19 τὸ om Va
footnote 18 [Dem.] prooem. 46 p. 1453,13; Dem. Phil. IV p. 161,4 1 αἰ om MaClB 2 ὀφρύες VaMaB 8 οὖν ante οὐκ  Α 9 ὀμοῦνται ClB 10 χαρίσαιτ’ ACl 12 καὶ ante πολ- λακὶς Α 13 πεποιημένους Ma sed η in ras m 2 et πε antep 15 γίνεται MaB 18 τἀληθῆ Α 19 ἐνταῦθα Α  20 ὁ om MaClB 21 ἄκων scripsi auctore Markowskio  ἀκούων libri Re 23 τῆς lacobs App Pors 331 Lect | ἀπάτης  scripsi ex Α cum lacobsio Add 10 App Pors Lect Schul et Sin- teni ἀπάσης reliqui libri Re
marginal RIV 849
footnote 6 cf. t. III p. XXIX 14 cf. ad p. 385, 3 16 cf. t. IV  250,1 1 ᾔδει Va sed εἰ ex ἡ corr m 2 ἤδη Mon | εἰ Mon sed ἐν  suprascr Hardt 4 κωλῦσαι? at cf. ad t. I 272, 5 6 ᾤετο  δεῖν μόνην Ma 8 ἐκπεπληγμένως Α 9 σκοτοδινιῶν AMa  ClB | καὶ om Β | μηδ’ inserui οὐχ lacobs Ach Τ 816  Schul om libri Re Ι τὰ MaCl 10 ἐπιλανθάνωμαι scripsi  ἐπιλανθάνομαι libri Re Ι φαίνομαι MaCl 11 signum interro- gationis posui colon libri Re 12 ἦν Α | φής libri Re  14 ἀποστρέφῃ scripsi ἀποστρέφει ἀπεστρέφει Cl) libri Re  16 τίς MaB 19 εἰ Ma sed οὐ suprascr m 2 20 γενήσεσθαι  scripsi 6 VaMaClB cum Sinteni ἐγνήσεσθαι Mon Re δυνή- σεσθαι Α γενήσεσθαι δὲ lacobs Schul, ἡγήσεσθαι Lect | ἂν  ὡμολογημένως Cl sed ‘ supra ω man rec ἂν ὁμολογουμένως Β ἂν ὡμολογημένως Sintenis δ’ αὖ ὁμολογουμένως lacobs Lect,  ὅτι πάντες ὡμολογημένως Schul
footnote 1 ὡς inserui om iibri Re | ἡγήσωνται Sintenis εἷναι la- cobs Lect 3 παρὰ Ma 5 γε lacobs App Pors 332 Lect  Schul Ι ἡ scripsi e VaAMaClB cum lacobsio Schul ὁ Mon Re  οὐ lacobs App Pors Lect 6 καὶ] καὶ γὰρ lacobs App Pors  Lect, ἀλλὰ καὶ Schul | ἀποφυγεῖν Α sed εῖ ex ὼ corr m 2  φυγεῖν lacobs App Pors Lect | μικρά τις scripsi cum  App Pors Lect et Sinteni μικρὰ τοῖς MonMa Re μικρὰ τοῖς  γὰρ cum lacuna 2 1/2 vers Α, cum lacuna versus dimidii Cl μικρὰ  VaB μικροτέρα lacobs Schul | καὶ — 7 ἀφόρητον om in lac  45—47 litt Β, in lac 1 1/3 vers Va 7 ἀτόποις] καὶ ἀτόποις  καὶ Ma sed καὶ(2) del m2 | ἀφόρητον Ma sed φό in ras m2  καὶ ἀπόρρητον Γέ καὶ πεπιστευκόσι· καὶ ἀπόρρητον Α 9 τὰ  ’κείνων Β 10 τοῦτον scripsi e Β τούτων MonVaAMa sed  in hoc ῦτον suprascr m2, Cl Re 11 καὶ om Va | βούλοιτο  ClB 12 ταὐτὰ scripsi ταῦτα libri Re 13 παρὰ scripsi  ex ΑΒ περὶ MonVaMaCl Re 14 προστεθεὶς Α | νοσή- μασιν ἑκὼν scripsi auctore lacobsio Schul νοσήμασι νοήμασι A)  μένων libri Re νοσήμασι μέτριον (vel μικρὸν) lacobs Lect  νοσήμασι μένος Sintenis | κέρδος &lt;οὐκ&gt; ἂν  15 ἡγοῖτο scripsi e VaAMaClB cum lacobsio et Sinteni ἠγεῖτο Mon Re Ι ἀποφύγοι MaClB Ι signum interrogationis posui cum  Sinteni colon libri Re
marginal RIV 850
footnote 4. cf.t.III 410,12. Dem. cor.§323 p. 332, 12. Plat.rep.IXp.586 A 1 λάβοι scripsi e VaAMaClJB cum lacobsio App Pors 332  Lect Schul et Sinteni λάβον Mon Re 2 καὶ κρατοῦντι scripsi  e VaAMa sed in hoc καὶ inser m 2, ClB cum lacobsio ἀρατοῦντι  Mon Re ἄρα τουτὶ Sintenis | κύπτειν scripsi auctore Markows- kio coll 11. 11. πίπτειν libri Re 5 ἐλευθερωθέντα Ma sed ὧς  antep, ῆναι supra ἔντα et ἴ’ supra α m2 6 ἀνέχεσθαι scripsi ex  Α cum Sinteni ἀπέχεσθαι reliqui libri Re 8 περὶ ὧν Α  9 ἐμβαλόμενος scripsi ἐμβαλλόμενος libri Re 10 δ’ scripsi e  Β δεῖ reliqui libri Re δὲ lacobs Anth. Pal. III 355 Lect 160  Schul | τοῦτον δι’ ἀγορᾶς ἔτι βαίνειν lacobs Add 92 quod im- probavit Anth. 1. 1. 13 με om Va | νενικηκότι VaA  16 οὐκ ante ἀκούσεταί Ma sed del m2 | κακῶς scripsi ex AMa  ClB cum Sinteni κακὸς MonVa Re 18 φήσει scripsi e Β  cum Sinteni φησι reliqui libri Re 19 τᾶν ΑΒ
footnote 10 Dem. Mid. p. 560, 9. Plut. Phoc. 21, 2 1 συκοφάντου Α 3 ἐπέκλυσε scripsi e VaAClB cum la- cobsio Add 125 Lect Schul ἐπέκλησε MonMa Re ἀπέκλεισε?  Sintenis 4 οὐδὲν Va | οὗ scripsi ex ΑΒ οἱ MonMaCl Re  ἡ Va | εἱστήκει Ma sed εἱστ inser m 2 | ὄνοισθε Α  μένου Sintenis 6 δόξειν scripsi e ClB cum Cobeto Misc 153  Coll 303 δείξειν MonVaAMa Re | μὴ ante δικαίως  dum coni lacobs Schul | ἡττῆσθαι δὲ Mon | ἔστιν  e VaAClB cum lacobsio Schul ἔστιν οὐχ οὕτως Ma sed οὐχ  inser m 2 ἔστι δὲ οὕτω MonUe 7 περιστησομένης scripsi e Va  ClB cum lacobsio Lect Schul et Sinteni περιστησόμενος Mon  AMa Re 8 χωρίζομαι Α | τὰ om MaClB 9 λόγου  λόγον Οἶ’ λόγος Α κολάκων lacobs Lect Schul | μήτε  τῶν Α 10 τί MonVaMaClB Re | δεῖσθαι μηδέν scripsi  cum lacobsio Schul δεῖσθ’ αἰ. μηδὲν μὴ δὲ Β sed ν eras, A)  libri Re | φθείρονται γὰρ παρ’ (vel πρὸς) lacobs Schul,  ρονται γὰρ αὐτὸν Lect φθέγγονται Markowski 11 αὐτὸν  scripsi e VaAMaClB cum lacobsio αὐτῶν Mon Re 13 τού- του MaClB 14 τί libri Re | ῥημάτων Mon sed  in marg, Va 15 τούτων scripsi ex AMaClB cum lacobsio Ach Τ 800 Lect Schul τοῦτον MonVa Re | ἐλευθερῶν Va |  το(??) Mon
marginal RIV 851
footnote 13 cf. t. VI 21,7 1 αὐτὸν ἐπ’ ἔργον Α 2 περικόπτον scripsi περικόπτων A  ων  MaCl κεκτημένον Mon sed περικόπ in marg, Va Re om Β  περικοποῦν lacobs Ach Τ 800 Ι ἢ τοῦ lacobs Lect Ι ξίφος scripsi  e Ma sed οὑς suprascr m 2 ξίφους reliqui libri Re 3 ἀνελό- μενον scripsi ex AMaClB ἀνελώμενον Mon Va sed in hoc ω in ο  corr ras, Re 5 οὐ MaClB | οὐ Οἶ’ 6 παράδειγμά lacobs  Schul | ἐστι MonCl Re 9 εἷναι ἀκρίτων Α 10 παίδων  Ma 12 οὐδὲ] ἄνευ vel ἔξω lacobs Anth. Pal. III 804 Lect  161 Schul | μύσους inser Ma 2 μίσους Cl | punctum  libri Re delevi 13 ἐκνίψειεν scripsi ex AClB cum lacob- sio Add 5 Anth Lect Schul et Sinteni ἐκνίψειν MonVaMa  Re | ἐμπιπλᾶν scripsi ex AClB cum Sinteni ἐμπιπλᾶν Ma  ἐμπιπλῶν MonVa Re | ἤκουσαν Cl 15 μόνος scripsi  Sinteni μόνου libri sed οὐ corr Ma 2, Re 17 ἔσται om Ma  | ποίαν φύσιν Α
footnote 1 cf. p. 691, 12 2 cf. t. VI 27, 7 et ad t. V 618, 5 et supra  p. 467,19. Knauth, ätter für Gymnasialwesen  6 Aeschin. fals. leg. § 152 p. 48,30 1 φύσις Ma sed ις ex εἰς corr m2 2 καὶ(2) om ΑΒ  3 μεγίστην Ma sed η corr m 2 μεγίστων Cl | ἀνακαλεῖν  Β Ι ἡ Mon 4 αὐτῆς libri Re | ἢ Mon 5 πατέρας  scripsi ex AMaClB μὲν πατέρας MonVa Re |  Ma sed ρο corr m 2 ππὰκινδυνεύειν Cl | comma post δὲ  Re delevi cum lacobsio Schul et Sinteni 6 τούτων Α |  punctum post τούτους posui cum lacobsio et Sinteni colon Β  om reliqui libri Re | καὶ παρατάξεις scripsi e VaAMaClB  τάξεις Μοὶ Re | comma post φόνους Β, punctum  libri Re delevi cum lacobsio et Sinteni 7 ἡ] ὁ, Mon  9 ἐκείνοις scripsi e Ma sed ι(2) corr m 2, cum lacobsio Lect  Schul ἐκείνους reliqui libri Re 10 καὶ ante αὐτοὶ in marg  inser A2 | αὐτοὶ Ma sed τοὶ corr m 2 | lacuuam post  statuit Sintenis | ἀλύπους γα 12 βοῶν Va sed mv in  m2 13 ὅτε scripsi e MaClAB ὅτι MonVa Re ὅ, τι lacobs  Lect 14 οἴκοι scripsi e VaAMaClB cum lacobsio Lect Schul  οἴκος Mon Re οἶκτος? Sintenis | „post διεφαύλισεν  quaedam interciderunt“ Iacobs Lect
marginal RIV 852
footnote 1 αὐτὴν] αὐτὸς Α2 νῦν δὲ μέγα] μητέρα Va | τί Mon 3 εὐνοίας Α Ι αὐτὸν MonCl sed in hoc ‘ ’ in ‘ corr 4 κτενεῖν Α | οὔ om Va | δυσμενῆ Ma sed υσμ corr  6 ὠθεῖ scripsi e MaClB cum lacobsio Add 9 Schul et Sinteni  ὠθῇ MonVa Re ὠθεῖν Α | ἠδικηκότως Mon 7 δὲ ClB |  ἂν om Ma | αὑτοῦ Α 9 ἐπαγγέλλετε scripsi ex AMaClB coll.  p. 710, 23 ἀπαγγέλλετε MonVa Re 14 ἐπὶ Ma ad quod δρα- μών in marg scr. m2 19 κατ’ ἐμοῦ διαλεχθεὶς πρὸς αὐτὸν  scripsi ex AMaClB (sed αὐτὸν AMaCl) διαλεχθεὶς πρὸς αὐτὸν  κατ’ ἐμοῦ MonVa Re | ἐμοῦ Ma sed ov corr m2 20 κοπτέτω  Β 21 τούτων scripsi ex AMaClB ut coni lacobs Schul  τοῦτο MonVa Re | punctum post δύναιτο posui signum in- terrogationis Β om reliqui libri
footnote 6 Xen. anab. VII 1, 25. Ant. tetr. III 3, 2 p. 127, 22 3 ἄν inser Ma | θαυμάσαιμι MaCl 4 ἀνθ’ αὑτοῦ  ἀντ’ αὐτοῦ libri Re Ι καὶ ante οὐκ Α 5 ἐπεῖδ’ ἂν Α |  ὧδε ᾖ scripsi ὅδ’ εἴη MonVaClB Re εἰδείη Ma sed e δείη  corr m2 ἥδ’ εἴην Α ὅδε ᾖ Iacobs Lect Schul ὦδ’ εἴη Sintenis 6 σπεισάσθω Ma sed σὰ in ras m2 7 ὀργὴν scripsi ex  AClB cum lacobsio Lect Schul ὁρμὴν MonVaMa Re | δότω  scripsi e VaAMaClB cum Sinteni δείτω Mon Re | τῷ τεθνε- ῶτι scripsi e Β τεθνεῶτι Cl τεθνεῶτι τῶν Ma τεθνεῶτι τῶν  θεῶν Mon Re τε τῶν θεῶν Va θεῶν Α 8 οἶς] οὐ Α  9 μὴ οἴεσθε lacobs Lect | οἴεσθαί Α 10 ἢ τί libri Re  12 αὐτῶ Α | δ’ ante ἐμὸς Ma Ι ἐμοὶ Β | φαινέτω Α 13 μὴ δὲ  ΑΒ I τίς MaB | λέγειν om Va 14 ἀγνοεῖσθαι Α Ι οὐ Α  15 ἀράτω Mon 16 ἃ τάφον Mon | με om Va
