@config
@author=Aretaeus
@availability=Available under a Creative Commons Attribution-ShareAlike International 4.0 License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@editor=Francis Adams Ll.D
@filename=tlg0719.tlg002.perseus-grc1
@fmt:text-orig-full={pre}{orig}{post}
@fmt:text-orig-main={main} 
@fmt:text-orig-plain={plain} 
@funder=National Library of Medicine History of Medicine Division
@placeName=Ciron
@principal=Gregory Crane
@publicationStmt=Cultural Heritage Langauge Technologies, Kansas City Missouri, February 1, 2005.
@respStmt=Prepared under the supervision of, Lisa Cerrato, William Merrill, Elli Mylonas, David Smith
@sectionFeatures=book,chapter
@sectionTypes=book,chapter
@sourceDesc=The Extant Works of Aretaeus, The Cappadocian, Aretaeus, Francis Adams LL.D, Boston, Milford House Inc, 1972 (Republication of the 1856 edition).
@sponsor=Perseus Project, Tufts University
@structureFeatures=_book,book,chapter,_sentence,_phrase
@structureTypes=_book,book,chapter,_sentence,_phrase
@title=De causis et signis diuturnorum morborum
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:47:21Z

