@node
@author=Hero of Alexandria
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Frederick Hultsch
@filename=tlg0559.tlg014.1st1K-grc1
@funder=Harvard Library
@principal=Gregory Crane
@publicationStmt=Harvard College Library, tlg0559.tlg014.1st1K-grc1.xml.
@respStmt=Digital Divide Data, Corrected and encoded the text, Gregory Crane, Editor-in-Chief, Perseus Digital Library, Matt Munson, Project Manager (University of Leipzig), Annette Gessner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig) 2015 - 2017, Bruce Robertson, Technical Advisor (Mount Allison University)
@sourceDesc=Metrologicorum Scriptorum, Frederick Hultsch, Hero of Alexandria, Teubner, Leipzig, 1864, The Internet Archive.
@sponsor=Harvard College Library
@title=Fragmenta Heroniana
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:52:46Z

3798	footnote 21. Ἥρωνοϲ εἰϲαγωγαί om. N, Τοῦ αὐτοῦ Ἥ. εἰϲ. M 22. Ἡ om. Le καθὼϲ] καθ᾿ Pb 23. γαιῶν μέτρηϲιν N, γεωμετρίαν rel. (τοῖϲ περὶ τὴν γῆν μέτροιϲ Ib) δια-νομὴν N, διανομὰϲ rel. (διανομαῖϲ Ib) 24. κατηϲχολεῖτο] διηϲχολεῖτο N (ἀπηϲχολοῦντο Ib)
footnote 2. φανερὰ ὄντα χωρία C 4. ποιεῖ C καὶ ante μετὰ add. C ἀνάβαϲιν Le ἐγένετο PbNV, ἐγένοντο M 5. οὐκέτι] οὐκ N διακρίναι PaMoLe, διακρίνειν C Ib ἐξ οὗ] διὰ τοῦτο CIb 7. ἀπολειμένηϲ Pb, ἀπολημένηϲ N ὑπὸ] ἀπὸ PaMoLe, διὰ C χρῶνται] χρᾶται N, χρᾶτε Pb 9. ϲχοίνῳ Mo, ϲωκαρίῳ Le καὶ ante καλάμῳ add. PbNM καὶ ante πήχει vitiose add. Le 10. δὲ τοῦ πράγματοϲ] δεὶ πραγματείαϲ Pb, δὲ πραγματείαϲ NMV 11. ὑπάρχον-τοϲ PabM, ὑπαρχούϲηϲ NV 13. τῶν (ante μετρ.)] τὴν Le 19. πρῶτον om. PaMoLe 22. ϲκουλώϲεϲιν N
footnote 1. ϲτροφύολοι ϲκουλώϲεϲιν add. ante ἐν τοῖϲ Pb κύματα V 5. ξύλον usque ad ἄμμα om. V ἅμμα PaN 8. 9. om. C 10. Ὁ] Ἡ N οὖν om. Pb 1. Ἡ Ὁ Pb 13. Φιλεταίριοϲ libri et hic et infra 15. γ˝] τρίμοιρον MoLe 16. Ἡ] Ὁ PbNLe παλαιϲτὰϲ] πόδαϲ C δακτύλουϲ κ´ om. C 17. ἔχει om. C 18. καὶ ξυλοπριϲτικὸϲ] Ἰτολικὸϲ C 19. πήχειϲ MoLe (??)˝] δίμοιρον MoLe 21. § 14 legitur in Ϲ ante 13 πό-δαϲ δ΄ϛ om. ϛ] ἥμιϲυ MoLe
footnote 1. post ἔχει in Pb e § 16 statim additur πήχ.  (??)˝, deinde e § 17 πόδαϲ Φιλεταιρικοὺϲ ξ´, Ἰταλικούϲ οβ´; re-liqua om. 2. δὲ post Ἰταλικοὺϲ add. Le ε˝] πέμπτον μέροϲ Mo, καὶ πέμπτον μέροϲ Le 3. (??)˝] δίμοιρον MoLe 5. ἅμμα N Φιλεταιρικοὺϲ Pb, idemque infra 7. δὲ ante πλέθρον add. PbNLe ἄκεναϲ P aliique et hic et infra (??)˝] δίμοιρον MoLe 8. ρ´] ἑκατόν N 9. 10. om. C 11. δύο N 12. γ˝] τρίμοιρον MoLe μήκουϲ et πλάτουϲ libri, corr. Le μὲν ante μήκουϲ habent PbN, μὲν et compendium voculae καὶ eodem loco V, unde μὲν λ in M πλάτοϲ δὲ ρ´ om. C 13. τὸ μὲν μῆκοϲ πόδαϲ] πόδαϲ μήκουϲ C τὸ δὲ πλάτοϲ] πλάτουϲ πόδαϲ C (per comp. scr.) 14. ὡϲ γίνεϲθαι usque ad ηω´ om. C ἐμ-βάδουϲ Pa 16. πήχυϲ Pb 18. ϲταδίουϲ δύο πλέθρα ιβ´ C
footnote 1. ἑπτὰ ἥμιϲυ] ζ´ ϛ˝ PbVM 2. ὅργυιὰϲ ψν΄ βήματα αω΄ om. C 4. Ὁ] Ἡ Pa Mo Le 6. τὸ om. Le 7. § 26 om. C 13. ὀγγία Pb παλαιϲτὴϲ libri (vide praef. crit.) 18. Ἡ] Ὁ PbV παλαιϲτὴϲ libri 21. Ὁ om. N 24. Φιλεταιρίουϲ NVM, Φιλεταιρικοὺϲ Pb 25. ῥω-μαϊϲτὴ Pb περτικά] 𝔮ερτίκα V, τερτίκα PbM
footnote 2. μὲν ante μῆκοϲ add. Pb πλάτοϲ om. M πό-δαϲ ante ρ΄ add. PbVM α om. libri 4. πόδαϲ] ποδῶν PbM ἐμβαδοὺϲ libri 5. μυρια VM, μυριάδεϲ PbN 9. Ἡ παλαιϲτὴϲ N, Ὁ πολιϲτὴϲ PbVM 10. ή δὲ ἑτέρα παλαιϲτὴϲ N, ὁ δὲ ἕτεροϲ παλαιϲτὴϲ PbVM 11. Ὁ Pb 12. ἡ] Ὁ Pb ἑτέρα libri 14. ὁ ante τετρ. om. N οὐγ-γίαϲ bis habet Pb ρμδ´ ad 15. οὐγγίαϲ om. V. 15. ϲτερεὰϲ PbNM 17. Initio addenda videntur: Ὁ τετρά-γωνοϲ πῆχυϲ ἔχει οὐγγίαϲ τκδ´, δακτύλουϲ φοϛ´ 18. α γωκδ´] αγωδ N teste Ma 20. αχ´] ante hoc N add. άψ 22. Φιλεταιρείουϲ] ϲτερεούϲ libri, quod eiiciendum censebat Le
footnote 8. κδ´] δ´ cod. 14. ὀργυῖαν cod. δίμοιρον Vincent. 17. ἄκεναϲ cod., idem etiam infra γίνονται] γι´ cod., om. Vinc. ὀργυιὰϲ et πόδαϲ Vinc.
footnote 1. πόδεϲ] πο Pc, om. Le δώδεκα] Δ Pc 3. βω Pc, corr. Le 4. γίνονται παλαιϲταὶ Pc, γίνεται πολαι-ϲτὰϲ Le 5. μη΄] μ Pc 7. πόδα] ποδ Pc ἕνα] ᾱ Le 10. φοϛ´] φοβ´ Pc. 14. Περὶ μέτρων inscriptum habet V ἐξηύρηνται Pd a pr. m. 15. κονδύλου om. C παλαιϲτοῦ om. Pd 16. πήχεοϲ V 17. ἐλαχιϲτότεροϲ Pd, ἐλαχιϲτότατον V, ἐλαχιϲτώτερον Pe ὁ om. V 18. μὲν καὶ om. V 19. ἡμίϲει Pe τρίτον καὶ λοιπὰ μόρια] εἰϲ τρίτον καὶ εἰϲ δ˝ καὶ εἰϲ λοιπὰ μόρια Pe 21. ὁ κόνδυλοϲ usque ad Εἶτα om. C
footnote 1. τινεϲ om. V. 2. τέϲϲαρεϲ Pe ἢ διὰ τὸ usque ad τῆϲ ϲπιθαμῆϲ om. PeV 5. τέϲϲαρα] δ´ Pe 6. δὲ om. PeV παλαιϲτὰϲ δύ᾿ ἔχει V, παλαιϲτὰϲ β´ ἔχει Pe 7. ὀκτώ] η´ PeV κονδύλουϲ τέϲϲαραϲ om. C καὶ κα-λεῖται] καλεῖται δὲ V 8. λιχὰϲ] διχὰϲ libri δύο] β´ Pe 9. ἀντιχείρου V a sec. m. 10. τοῦτο τινὲϲ κα-λοῦϲι V κυνόϲτομον Le (‘um manuscrit donne κυνόϲτο-μον: c’est, je crois, la vraie lecon’), κοινόϲτομον C 11. ἤγουν] ἢ V 12. ιβ´] ιε´ Pe κονδύλουϲ ἕξ om. C 13. Ὁ om. Pd γ˝] καὶ γ˝ Pe, καὶ (??) V ἤγουν] ἤτοι Pe 14. κονδύλουϲ ὀκτώ om. C ἤτοι] ἤγουν Pe 15. Ὁ] Ἡ Pd δύο] β´ Pe ἤγουν] ἢ Pe 16. δύο] β´ Pe ὀκτώ] η´ PeV κονδύλουϲ ιϛ´ om. C 17. λβ´] λε´ Pe 18. γ´] τρεῖϲ PeV γ˝] τρίτον V 19. κονδύλουϲ κ´ om. C
footnote 1. ε´ om. Pe 2. (??)˝] δίμοιρον V κ´] εἴκοϲι Pd ἢ κονδύλουϲ μ´ om. 4. Ὁ] Ἡ Pd 5. πρὸϲ om. V τῷ ἡμίϲει] τῶν ἥμιϲυ Pd, τὸ ϛ˝ Pe, (??) V ἢ κονδύλουϲ ιβ´ om. C 6. ὁ om. Pe 8. Ἡ om. V οὐργια (sic) Pe, qui postea constanter οὐργυιά μετρᾶται Pd 9. θ´] ἐννέα V δ˝ τέταρτον V, om. Pe ἓξ om. Pe 10. δ˝] τέταρτον PeV ἤγουν] τοι PeV ἀντίχειρα PeV 11. ἐϲφηγμένηϲ V 12. τὸν δὲ] τὸ ἢ om. Pd ἡ-πλωμένον Pd 13. μεγάλου om. PeV ὃϲ] ἧϲ Pd 14. τέταρτον λέγεται Pe τρεῖϲ] γ´ Pe 15. μεθ᾿ Pd δὲ om. V 16. μετὰ τούτου Pe et Salmasius Plin. Ex. p. 481bB 17. δεκαόργυιον] δέκα οὐργυιῶν Pe, ὀργυιῶν δέκα V οὕτω PeV μετρεῖν] μετρᾶν Pd, μετρῆϲαι Pe Sa (h. e. Salmasius) μέλλειϲ om. Pd μετρῆϲαι] με-τρεῖν PeSa 18. ὀργυιὰϲ δέκα V
footnote 1. τοῦ δὲ λιβαδίου] τοῦ δ´ ἐμβαδίου Pe τῶν περι-οριϲμένων Pd, τὸν περιοριϲμὸν V 3. δεκαουργίου Pe a pr. m., δεκαουργυιαίου idem a sec. m. (itemque infra), δεκαοργυιαίου Sa ϲχοινίου] ϲωκαρίου 4. ὁ om. Pe ϲ´] διακοϲίαϲ Pe καὶ ante μόναϲ add. Pde 5. δωδε-καοργυίου] ίβ ὀργίου Pd, δωδεκαουργυιαίου Pe (itemque infra) ϲπη´] ϲπ´ Pe 8. καὶ τῶν χωρίων om. Pe 10. post ϲχοινίου Pd add. ὀφείλουϲι μετρεῖϲθαι περιοριϲμέ-νων Pd 11. καὶ λόχμαϲ om. V λόχμαϲ] λογχ cum corrupto compendio Pd 12. ἀχρίϲτουϲ Pe, ἀκρίϲτουϲ Pd ἂν] αἱ Pe, εἰ Pd ἂν δὲ καὶ usque ad αἰτίαϲ om. V 13. μετρηθῶϲι Pde 15. post μοδιϲμοῦ Pe add. ὑπεξαιρεῖϲθαι 16. ἓν] α´ Pe 17. Δεῖ] Χρὴ V 18. λύτραϲ Pe 19. ε´] πέντε Pe
footnote 1. γὰρ om. V 7. ea quae supra usque ad finem perscripta sunt solus habet Pd; in Pe et V tabula sic continuatur: Πλάτοϲ καὶ μῆκοϲ ὀργυιῶν ρ´ ποιοῦϲι λίτραϲ κ´ ἤτοι μόδιον ϛ (ἤγουν μοδίου τὸ ἥμιϲυ V). Πλάτοϲ καὶ μῆκοϲ ὀργυιῶν ϲ´ ποιοῦϲι λίτραϲ μ´ ἤτοι (ἤγουν V) μόδιον α´ (ἕν V). Haec centenarum orgyiarum ratione ad mille orgyias, deinceps singulis milibus orgyiarum additis continuantur ad: Πλάτοϲ καὶ μῆκοϲ ὀργυιῶν α ποιοῦϲι λίτραϲ β´ ἢ (ἤ-γουν V) μόδια ν´. (Hic est finis tabulae in PeV.) 13. μοδίου Pd 14. μοδ´ Pd itemque infra.
footnote 4. προϲθήκηϲ κόνδυλον cod. 7. αὐτοῦ cod. et hic et infra 10. ἐν τοῖϲ] ἐντὸϲ cod. 12. τοῦ ὤμου] τῆϲ ὄμου cod. 14. δικαιότατον cod. 17. καὶ om. Le 18. οὐργυιά Pe 19. πλεῦθρον Pe, itemque 21 21. α´ (??) ϛ´ Le, α´ (??) ιε˝ Pf (teste Le), α´ (??) ῑε 23 δύο Le 24. ι´ ϲωκάρια] ῑϲ Pf, ηϲ Pe
footnote 2. ζ´ϛ ϲτάδια] ζϲ κ θ Pf, ξ´ϲ ϲθ Pe, zϲ´ ϲπιθ. Le 3. Ὁ om. Pe 6. τοῖϲ] ταῖϲ Pc 7. post ὅλα add. κεφα Pb 8. Τῶν] Τὸν Pc, Τὰ Le e Vat. a rec. m. ἐν om. Le τῶν ante μετρήϲεων add. Pbc Le μέρη om. Pbc Le 10. πάντων] πάν . . Pc 11. ἐϲτιν ὁ δάκτυλοϲ Pc καὶ ante εἰϲ μέρη om. Le 13. δὲ om. Pc 14. παϲϲὸν Le 15. μήλιον Pc 21. τρεῖϲ] γ´ Pc Le
footnote 1. πύχηϲ Pb (??)˝] β˝ Pc Le (sic etiam infra) 5. πήχυν Pb 6. ϛ om. Pb δακτύλουϲ] πο Pc 7. ὀργ΄ Pb, ὀργυιὰϲ PcLe 9. ὀργυιὰϲ PcLe α´ om. Pb 12. ὄκαινα PcLe (sic etiam infra) γ˝ om. Pc 14. παλαι-ϲτὰϲ] πάϲϲαϲ Pc 15. πάϲϲαϲ Pc 16. (??)˝] Ϲ Δ(??) Pc, (??) ϛ˝ Le πήχειϲ χ´ om. Pc 17. α θϲ´] α ῡ θϲ· Pc 20. γ˝] Δ(??) Pc 21 θχ΄, δακτόλουϲ om. Pb 24. γ˝] Δ(??) Pc πλέθρα PbLe, πλε´ Pc ἄκαινα Pc
footnote 3. μήλιον Pc ϲτάδια PcLe 4. ἄκαινα Pc ἀμπ Pc, ἀμπέλουϲ Le 5. βήματα βϲγ΄, πήχειϲ ϲπ´ Pb 7. οὕτωϲ om. Le 8. εἴουν] ἤτουν PcLe 11. τέταρ-τον] δ˝ Pb 14. Εἶτα usque ad δ´ om. PcLe 19. ἔχει om. PcLe 20. Πάϲϲον] πλεθ´ Pc 24. μὴλιον Pc
footnote 6. ὁ δὲ ϲτ. δ. ξδ´ om. Pb 11. ϲνϛ´] ξδ´ Pc 13. δ(??)ϛ´] ϛ´ Pb, ακδ´ Pc, 17. ακδ´] ρκδ´ Pc 18. πῆχυc] ποῦϲ Pb 19. φιβ´] δ𝔮β´ γ βψκη´ Pb, Γ βψδ´ Pc. 25. Ὁ] ἡ cod. 26. πήχην ἵνα cod.
footnote 20. ιγ΄ ϛ] ιγ΄ duo Iibri
