@node
@author=Libanius
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Richard Foerster
@filename=tlg2200.tlg00521.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane
@publicationStmt=University of Leipzig, tlg2200.tlg00521.opp-grc1.xml.
@respStmt=Gregory R. Crane, Editor-in-Chief, Perseus Digital Library, Digital Divide Data, Corrected and encoded the text, Matt Munson, Project Manager (University of Leipzig), Annette Geßner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor, Greta Franzini, Project Manager (University of Leipzig), 2013-2014, Frederik Baumgardt, Technical Manager (University of Leipzig), 2013-2015, Simona Stoyanova, Project Manager (University of Leipzig), 2015, Project Assistant (University of Leipzig), 2013-2014
@sourceDesc=Richardus Foerster, Richard Foerster, Libanius, Declamationes XIII-XXXX, B.G. Teubner, Leipzig, 1911, 6, Internet Archive.
@sponsor=University of Leipzig
@title=Declamatio 21
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:57:50Z

3694	marginal R IV 266
footnote 10 Thuc. I 123, 1. Isocr. paneg. p. 44 c 1 Titulum in lac om Β 2 δισχιλίους scripsi e VViMa  cl coll p. 337, 12; 299, 3; 306, 17. Diod. S. XIV 86 χιλίους Ρ  edd Ι ἀποδώσειν inserui auctore Gasda δώσειν Vi om VPMa  cl edd 3 λάβη Vi Ι δὲ post ἀξιοῖ Vi 5 Δημοσθένης om VB  ViMaCl 8 τὰ δ’ scripsi e V τά δ’ BVi τάδ’ ΡΜαΟἰ edd 9 lac 4 litt ante παρεσκευαζόμην Β Ι μὲν inserui om libri  edd 11 ὑμῖν scripsi ex Η qui hac voce incipit, VBViMaCl  ἡμῖν Ρ edd Ι εἷναι post ἡμῖν inserendum coni Gasda
marginal R IV 267
footnote 13 Thuc. epigr. Anth. Pal. VII 45, 2 2 ὑμετέρων scripsi ex HV ἡμετέρων PBViMaCl edd  4 τῶν γεγραμμένων V sed τοῖς γεγραμμένοις suprascr m 2 voce  γεγραμμένοις des Β 5 ἡμῖν Vi Ι τοὺς om Vi 7 ἀφίστην  Ma sed πε supra φι m 2, cl | δίδωσιν Ρ edd 10 ἐμαυτῆς  Mor | πεποιημένου Vi | με inserui ante μεταβεβλημένον post  πεποιημένον inserendum coni Re om libri edd 13 τοῖς Mor  | ἀπαλλαττομένης Vi 14 αὐτῶν libri ’ in ' corr Ma 2, edd 16 αὐτῶν libri edd 17 ὧν Ma sed ~ α et in ras m 2  ἀπολαβεῖν Ρ Mor Ι εὐδαίμων in εὐδαιμονεῖν mutandum censet  Re, delendum Gasda Ι δὲ ἐγώ scripsi e Vi δὲ ἐγὼ HVPMaCL  edd sed δ’ ἔγωγε scribendum coni Mor 21 ἡμετέρων Vi
footnote 7 i. e. Αἰσχίνης cf. p. 192 sq. 11 cf. ad p. 281, 3. Dem.  cor. § 169 sq. 13 Dem. cor. § 171 sq. 17 Dem. cor. § 187 1 τί HVViMaCl Ι ἄγον VVi Ι ταῦτα] τῷ HV 2 οἰκείαν  acripsi e Ρ coll t. V 380, 13; II 88, 1 ut coni Re οἰκίαν HVVi  MaCL edd 3 ἀποδοῦναι Ρ Mor 4 ἀθήνας in ras V 2  5 εἵμαρτο reposui e libris εἵμαρται edd 6 τὸ(2) et τῇ om Vi  Ι πυλαία ταραχὴ Vi sed τῇ παλαιὰ ταραχὴν in marg m 2 πα- λαιᾶ Η 7 φαιδρῶς V 10 οὐδὲ Sintenis Ι κατειλῆφθαι  scripsi ut coni Re καταλελεῖφθαι HVViMa sed in hoc α(3)  in ras m 2, CL καταλελῆφθαι Ρ edd 11 ἀγγέλλων scripsi e  VViMaCl ἀγγέλων Η λέγων Ρ edd 13 συνελθεῖν scripsi    ex HVViMaCl ξυνελθεῖν Ρ edd Ι τίς Η | (??) Ma 14 ἐτόλ- μησεν Η 16 δι’ ὅπερ Vi 19 ἐπαλλήλας ViMaCl Ι οὗτος Ρ  ὂν  dd sed οὕτως aut ὅμως legendum coni Re Ι ἥκων Ma
marginal R IV 268
footnote 1 Dem. cor. § 211 sq. 7 Dem. cor. § 222 12 Dem.  cor. § 285 15 cf. p. 44, 5. Dem. cor. p. 321 25 1 ποτε HViMa 4 ἡμᾶς Vi 5 ταμάλιστα Ρ | τὰ Vi sed  τὴν in marg m 2 6 ηὐξήνθη V et in marg Vi 2 7 τούτω  Ma sed ω in ras m 2 τοῦτο CL | με in ras V 2 | βουλομένῳ Ma  sed ο(2) in ras m 2 10 ὑμῖν Vi sed ὑμῶν in marg m 2 | ἐν in  marg Vi 2 11 προλαβόντος Vi προσλαβόντες Mor 12 φωνῆς  Ma sed φω in ras m 2 15 τῆς περὶ δεῖπνον Vi sed τοῦ περι- δείπνου in marg m 2 τῶν περὶ δεῖπνον Ma sed ν(3) ex υ corr  m 2 περὶ δείπνου Η Ι τοῦτο ViCl 16 τετίμημαι scripsi auc- tore Cobeto τετίμηνται HV edd τετίμηται PViMaCL | παρὰ  — οἰκείων vel saltein τοῖς πεσοῦσιν delenda censet Gasda | τἀς]  τοῖς Mor 17 ἐτραπόμην scripsi ἐτρεπόμην libri edd  18 τούτοις CL | οὐδὲ μιᾷ Πα οὐδεμία Vi 20 ἀνδρείας scripsi  ex HVViMaCl ἀνδρίας Ρ edd
marginal R IV 269
footnote 4 Xen. Hell. IV 3, 19. Eur. Phoen. 1405 5 Thuc. II 51, 3 18 Thuc. I 129, 3 2 ἀρχόμενοι Vi sed ἀρχομένης in marg m 2 3 αὐτούς  scripsi e Ma αὐτοὺς HVVi αὐτούς ἁ ἑαυτούς Ρ edd  4 ἀξιοῦντες τίΗViMa 6 διαταῦτα Vi | τοῦτο Ma 7 καὶ(2)  om PMa Mor | ἐρᾶν Vi sed ἐρεῖν in marg m 2 8 τὸν γὰρ Re  τὸν om Vi 9 ἀνέχοντα Η 10 αὐτοῦ libri edd | ἔμελλε  Ma sed λ(2) inser m 2 ἔμελλ(??)ν Ρ 11 χρήσασθαι HPMaCI  Mor 12 ἀποδρᾶναι Ma sed αναι ex αν corr m 2 | τότε Vi  num τὸ δὲ? 13 ἄλλους Gasda | οὔτε Ρ edd 14 ὑμῶν scripsi  ex HVViMaCl ἡμῶν Ρ edd | ἀποστει λάντων cum ras 2 litt V 16 τῶν αἰχμαλώτων scripsi exHVViMaCl τούς αἰχμαλώτους  Ρ edd Ι χρησομένους scripsi cum Gasda χρησαμένους Kbri edd 17 πολλοὶ Vi sed πολλὰ in marg m 2 | οὕτως Ma sed οὕτος  suprascr m 2 οὗτος HVP οὕτος· Ee καὶ οὗτος· Gasda | αὐ- τοὺς scripsi e Vi sed αὐτὸς in marg m 2 MaCI cum Iacobsio  Lect 104 Rev 4 αὐτὸς HVP edd 18 αὐτῶ libri edd
marginal R IV 270
footnote 4 Diod. S. XVI 87. Iustin. IX 4. cf. A. Schaefer Demosth.  III 4 2 12 cf. p. 274, 9 13 Plat. rep. V p. 468 A 1 ὑμῖν scripsi ex HVViMaCl ἡμῖν Ρ edd 3 ᾔδει]  ἤδη Vi 4 μὴ δὲ HPViMaCl | λογιζόμενον Ma sed ν(2) in  ras m 2 λογιζόμενος Ρ Mor 6 δήμου Mor 8 ἡ om Mor I  διατί HMaCI | ταῦτα Vi 10 παρ’ scripsi e Vi παρὰ HVP  MaCl edd 11 τοῦτον scripsi auctore Re τοῦτο libri edd |  ἔπεμψεν; edd | οὕτως] ὅτι πως vel ὅτι παντελῶς coni Re Ι ἡμᾶς  VP 14 λύσιν Ma sed λ in ras m 2 15 αὐτόν scripsi e Vi  MaCl αὐτὸν HVP edd 16 καὶ om Vi 20 οὕτως scripsi  auctore Re ὄντας HVViCl ὄντως Ma sed ω in ras m 2 om Ρ  edd | ὁπότ’ ἂν MaCI 21 τί HCI Ι αὐτὸν scripsi e MaCI  αὐτὸν HVPVi edd
footnote 3 Plat. soph. p. 265 A 8 Aesehin. fals. leg. ’ξ 33  13 ef. p. 269, 15 1 ἡμέτερα Ma sed ὒ supra ἡ m 2 Ι τοιαῦτά ποθεν HVi  2 ἤκουσαν scripsi e Vi ἤκουσα HVPMaCl edd | ἐν ante ἐκεί- νοις inser Vi Ι ἐκείνοις V sed οἱ in ras m 2 3 ἐγγυτάτω scripsi  ex HVVi ἐγγυτάτων MaCl ἐγγύτατα Ρ edd | γένει in ras Ma 2 6 τὰ Γέ sed τὸ in marg m 2 7 ἐκ ante παραδειγμάτων  Vi 8 καὶ — συμβέβηκε om Ma Ι δὲ HViMaCI | κενὸν V  ἂν in ὂν mutandum censet Gasda 9 εἴη inserui om libri  edd | πρόσθεν om Vi | γενόμενον scripsi ex HVViMaCl γεγε- γεγενημένον Ρ edd 10 ἐστέ om Mor Ι Ἀθηναῖοι inserui om libri  edd 11 ἡμετέρων HMaCI 14 ἄξια inserui cum Gasda  coll p. 326, 12 om libri edd 14 ἐμοὶ MaCl | ἴσθι Vi sed  ἴσως in marg m 2 15 ἥκουσι Ma sed ό supra ou m 2 16 et  17 μὴ δὲ HPViMaCl 17 καὶ ante ἐγὼ HV 18 ὅτι Vi  MaCl
marginal R IV 271
footnote 5 Arist. Phit. 101 11 cf. t. V 31,13; 75,8. Dem. cor.  p. 315,5 17 cf. p. 283,3 1 πατρῴων HP 3 οἶμαι Ma sed οἶμ’ in ras m 2 | καὶ(1) om  Ma 4 ἑκατέρου Vi 5 πολιτῶν ViMaCl πολιτευμάτων coni  Gasda | διὸ ΗP Ι δὴ HV 6 et 7 μήτε scripsi cum Gasda  μὴ δὲ HPViMaCl μὴ V μηδὲ edd 7 μὴ VP | διδασκαλίαν  Vi | δ’ Vi 8 ὑμίν V sed ὑ et iv in ras m 2 9 οἷς ante  ἐναντία Mor Ι ἐναντίον Vi | φησίν VP edd 11 τὸν om Ρ  13 τὴν ante πρόφασιν MaCl 18 ἀπὸ Vi 19 νόμους τε καὶ  post προγόνων Ρ edd delevi | κανόνας in lac 9 litt om Ρ Mor 20 ἐστράτευσαν ὢ 21 μὴ δὲ PMaCI μὴ δ’ HVi μηδὲ  V edd | ἄλλως HV sed in hoc ως eras et in ο corr m 2, MaCl
marginal R IV 272
footnote 2 sq. cf. ad p. 252, 14 sq.; t. IV 263, 6 R 3 cf. p. 278,  14 sq. 6 Dem. p. 1319, 27; 1365, 29. Arist. rep. Ath. fr. 5 ed.  Thalh. 1 τῆς inserui ex HVViMaCl om P edd 2 ἢ] καὶ Ma  Οἶ’ 6 γεννήτας scripsi e Vi γεννητὰς HVPMaCI edd Ι ἂν  om Ρ Mor 7 γραμματίου Vi 8 καὶ inserui om libri edd 9 παιδείαν om MaCI Ι οἷς ante καὶ libri edd delevi in δὲ  mutandum coni Re aposiopesin statuens (sc. λέγοιμι ἂν τὴν ἐμὴν  καὶ πλείω τούτων) παιδείαν δὲ καὶ πλείω τοιαῦτα σιγῶ ὡς φέ- ροντά τινα φιλοτιμίαν coni Iacobs Lect 104 Rev 4 | ἴσως Vi  sed ἴσῳ in marg m 2 ἴσω V 10 δοκεῖ Vi sed ἀρκεῖ in marg  m 2 11 ταῦτα Vi 14 τῷ Φιλίππῳ om Ma 16 ὑπὸ Vi  sed παρὰ in marg ms παρὰ HV 18 διδόντα Ρ Mor ἐκδι- δόντων coni Gasda 19 πανταχοῦ Vi sed πανταχῆ in marg m2
footnote 7 sq. cf. p. 303, 1 sq. Dem. fals. leg. p. 400,15; 402,26; 412,19  et 25 9 cf. ad p. 271, 23 15 cf. p. 350, 8 1 ἥξει Vi sed ἔξει in marg m 2 Ι ἐκδιδόντος coni Gasda  2 δὲ VPVi edd | ἐκδιδομένου Ma sed κου supra δο m 2  4 παρὰ HV sed in hoc περὶ suprascr m 2 Ι μηδὲν Vi 5 μὲν,  οὐδὲν εἷναι χείρους post ὑμᾶς Ρ sed οὐδὲν εἷναι χείρους del 7 οὐκ Αἰσχίνην om Vi Ι φρυνώνδαν Vi 8 ᾐσχυνόμην Vi  sed αἰσχυνόμενον in marg m 2 Ι ἀλλὰ Vi 9 ἀριστίδην HCI  ἀριστείδη Ma | νεικίαν HCI νικίδην V Ι τοὺς — 11 τότε om V  sed in marg add m 3 Ι οὐκ Vi sed ὀλίγα in marg m 2 10 μὲν  om Cl | ἴσθι Vi sed εἴς τι in marg scr et del m 2 εἴ τι V 3 11 δὴ scripsi ex HVViMaCl δὲ Ρ edd 12 λιπὸν V sed  in λυπῶν corr m 2 13 ἐλύπει Ma sed ουν supra ει m 2 Cl 14 ἐκβάλλειν scripsi ex HVViCl ἐκβαλὼν Ma sed εἰν supra  ων m 4 ἐκβαλεῖν Ρ edd Ι αὐτὸν libri edd | μὴ Vi sed μὲν in  marg m 2 17 εἰ in ras V 2 εἴ τι coni Gasda
marginal R IV 273
footnote 1 cf. t. IV p. 291, 7 R. Luc. Dem. laud. § 44; abd. § 32 2 cf. ad t. II 387, 14 6 cf. t. IV 950, 26 R 7 cf. t. IV  951,2; 977, 8 R. Dem. cor. p. 271, 6 sq. 9 i. e. Πύθωνος cf.  ad p. 238, 16 1 ἔταξα V sed α(2) in ras m 2 | ἐμαυτῶ HV et coni Mor 2 καὶ ποῦ φανῶ post φανῶ; V Ι δίκαιον αἰσχύνειν με coni  Re 3 τὸν et 4 στέφανον Vi 4 et 5 αἰσχύνειν coni Re  6 καὶ om ἁ Ι τὸ reposui e libris τὸν edd 10 ἀσθενεστάτην  Ρ Mor 11 ἡδέων αἱρούμενος πρὸ τῶν coni Re 12 ἀναι- νόμενος (recusans) Iacobs Lect 104 Rev 4 at cf p. 223, 11 Ι κατὰ  τῶν V sed ἁ in ras m 2 κατ’ αὐτῶν HMa sed in hoc γρ καὶ  ταὐτὸν suprascr m 2 CI καὶ ταὐτὸν Vi 14 λανθάνειν inser  v2 16 ἐν om Mor Ι περιχωρίοις Vi sed περιχώροις in marg  m 2, MaCl | εὐβοέσι HV | λέγων Vi 17 στήσεται Mor sed γρ  συστήσασθαι in marg συστήσεται HVViMaCl συστήσασθαι Ρ  sed in στήσεται corr m 2 18 βεβαιοῦθαι Vi
marginal R IV 274
footnote 5 Dem. Phil. III p. 129,10; Phil. ep. p. 160,8 10 Plat.  Theaet. p. 186 C 12 cf. p. 277, 14; 314, 6; t. IV 259, 5 sq. R 16 cf. t. IV 286, 17 R 2 μὲν ante πρεσβεῖαι Ρ Mor | παντί με scripsi e Vi παντὶ  μὲν HVP sed in hoc παντί με snprascr m 2, MaCI μὲν παντὶ  Re sed „malim με“ πάντα μὲν Mor 5 ἀφῖχθαι τὶς Vi  11 συνήγειραν ὁ χορηγὸς Vi sed συνήγαγεν ὁ χορηγῶν in marg  m 2 Ι punctum post συνήγαγεν posui, comma libri edd 13 ἐλ- λήσποντον Ma sed λ(1) in ras m 2 | χερόννησον HV χερόνησον  Vi 14 ἢν Ma | πάντες HV et in marg Vi 2 15 στεφανώ- σοντες scripsi ut coni Re στεφανώσαντες libri sed α(2) in o  ras corr Ρ, edd | comma post δῆμον posui, punctum libri edd 16 αὐτὸν HVViMaCl 17 φιλοτιμήσεσθαι Vi 19 διατί  HVi Ι φῆς Vi φὴς HVPMaCI edd
footnote 6 cf. p. 352, 3; 351, 17 sq. Thuc. III 19, 1 1 ἂν inserui cum Iacobsio Lect 104 Rev 4 et Gasda om  libri edd 2 οἶος Re 3 πείσωμεν HVi πείσομεν Ma  4 δικαίων Ma sed δικ in ras m 2 5 τολμήσαιεν HCI Ι φαγεῖν  Vi sed φυγεῖν in marg m 2 6 ἠδικηκότων ὑμᾶς ἢ εἰς κινδύνους  καθεικότων εἰσηνέγκατε προθύμως, πῶς ἂν οὐχ ὑπέρ του τῶν  πολιτῶν οὔσης τῆς σπουδῆς ἢ τὸ δοῦναι — ἡγεῖσθε; coni Re  | ἥκοντες scripsi cum lacobsio coll p. 352, 3 εἰκότως libri edd 7 ἥκατε coni Mor Ι ὅθ’ scripsi e Vi οὐχ HVPMaCI sed  in hoc in ὅθ’ corr m 2 edd εἰ coni Gasda Ι ὑπέρ του scripsi  auctore Re ὑπὲρ libri edd 8 ἡ] ἴση coni Iacobs Lect 104  ἡ ἴση Rev 4 | τὸ reposui e libris ut coni Re et Gasda τί edd  ἢ coni Iacobs | ἕκαστος reposui e libris cum Iacobsio ἕκαστον  edd Gasda 9 δεῖ] νῦν V 10 ψηφίσματα V 11 καὶ in- serui, ut δεῖ δὲ vel καὶ inserendum coni Gasda om libri edd 12 ἀνθρωπείας reposui e libris cum Iacobsio ἀνείσης Mor  ἀνίσης Re ἀνθρωπίνης Gasda et Cobet Coll 288 13 ταῦτα  scripsi ταῦτα ἢ Vi ταῦτ’ ἢ HPViMaCl edd 14 τῶν V Ι  αὐτῶν scripsi e Ρ αὐτῶν HVViMaCl edd 15 πῶς ante  ὃς Vi et inser V 2 | ὃς in marg Vi 2, del et πῶς suprascr Ma 4  καὶ παρ’] καίπερ MaCl
marginal R IV 275
footnote 6 cf. 1. 1 473,16 11 cf. 330,5 sq. 15 cf. p. 278,9; t. IV  262, 16 R 17 cf. p. 278,9. Dem. fals. leg. p. 393, 11 sq.  18 Dem. fals. leg. p. 394, 6 sq. 1 λείψεται Ma sed σθε supra ται m 2, CI λήψεσθε Vi 3 οὐκ  ante ἠγάπα HVMaCl sed in hoc del m 2 | αὐτὸν CI sed ν add  m 2 αὐτ(??) Ρ | καὶ ante τοὺς MaCI 4 ἐλπίζοντας Ma sed ζον  in ras m 2 5 καὶ om Vi 6 εὐπρεπεῖς ViMaCl | χαιρωνία  HV Χαιρωνεία Ma χερωνία Vi 7 ἐνέγκη MaCI 8 ὑμᾶς  scripsi ex HVViMaCl ἡμᾶς Ρ edd 9 αὐτοῖς MaCl Ι καὶ om  Vi 11 ἡμῖν Vi 12 περὶ MaCI 13 ἐμοῦ Vi sed ἐμὲ in  marg m 2 Ι οὖν om V | ἦν om Vi 15 τοσούτοις Ma sed ι in  υ corr m 2, CI 16 ἐλλήνων MaCl sed in hoc ἄλλων suprascr  m 2 18 δὲ ante ἐνθένδε Ρ Mor ἐνθἐνδεν Vi 19 οἶόν  scripsi ex HVViMaCl οἰός Ρ edd Ι ὤκνησεν Vi
marginal R IV 276
footnote 3 Dem. Aphob. I p. 815, 1 sq. 20 Plat. apol. p. 31 B 1 οὐκέτι Ma | 1 et 2 τοσοῦτο Ρ Mor | τοσοῦτον(2) delendum  censet Re 2 λέγω. Η et coni Re | οὖν inserui ex HViMaCl  om VP edd 3 μὴ δὲ HPViMaCl | πολλοὺς Η 4 πα- τρώων HVi 5 ἀνάλωται Vi ἀν(??)λωται Ma 7 ἀν’ οἱ μὲν  Mor sed γρ ἀνειμένον in marg ἀνειμεν P Ι ὑμῖν VMaCl  9 δεινὸν ὦ ἄνδρες ἀθηναῖοι Vi 10 καὶ om Ma 11 οὐχ  in ras Μa 2 11 et 12 ἕξεται V 14 ὑπερείδην HV Ι δη- μοτικώτατον scripsi auctore Re δημοτικὸν libri edd 15 ὃς  inserui om libri edd Ι ταῦτα VViCl 16 „malim γὰρ“ Re Ι  ἀπαιτήσεται V | γνώμας] καὶ λόγους Ma 18 ἡμῖν Ma sed η  in υ corr m 2 CI 20 τῶν in ras Ma 2 | αὐτοῦ Ma sed’ in  corr m 2 ὢ Ι ἡμετέρωνΜaCI
marginal R IV 277 18 cf. t. V 552, 20 1 ὑμνήσαντα Vi sed μεριμνήσαντα in marg m 2 6 ἡμᾶς  scripsi ex HPCI ut coni Re ὑμᾶς VViMa edd | βάθρον Vi  sed βάραθρον in marg m 2 et coni Iacobs App Pors 322 Lect  104 et Gasda at βάθρον nusquam idem est atque βῆμα magis  placeret Βαττάλου coll t. IV 312, 3 R. Dem. cor. § 180 p. 288, 17  et 22 c. schol. Lib. vit. Dem. p. 2, 23. Aeschin. Tim. § 126; 164;  fals. leg. § 99, at nihil mutaverim 10 ἄρτι in marg Vi 2  11 ταῦτα Vi Ι ἡμῶν Η 12 ὑμεῖς V | ἐξέδομεν Vi sed κεν in  marg m 2 ἐξέδωμεν V 13 ὑμῶν Ma sed υ ex η corr m 2 CI Ι  καὶ(1) om Ma 15 εὐλαβέστερον ἂν Ρ Mor | αὐτὸν HVViCl 16 αὐτῷ libri edd Ι ἔχει scripsi ex HVViMaCl ἔχοι Ρ edd  | παθεῖν ταῦτα Re 18 οὐδὲ HV 20 ἐάσαι HVPViMa edd
footnote 12cf.t.III170,6.Dem.cor.p.272,20 15 Plat.rep.IIp.36lE 19 cf. t. IV 319,12 R 1 ἡμεῖς Ρ Mor Ι θέλοντας V θέλοντα Vi sed τὰς supra τὰ  m 2 3 αὐτοὺς scripsi auctore Re αὐτοῖς libri edd 4 ὑπό- σχεσθε scripsi cum Cobeto Coll 288 ὑποστήσεσθε HVViMa sed  in hoc in ὑπόσχεσθε corr m 2, CI ὑποσχεθήσεσυε Ρ edd | ἔσεσθαι  scripsi ex Η cum Cobeto ἔσεσθε PVi sed in hoc εἷναι in marg  m 2, Ma sed ε in αι corr m 2, CI edd εἷναι V 5 λεγόντων in  ras V 2 7 ἦν V 9 ἄξιον HVMa sed in VMa ἀν antep m 2,  CI Ι παραμυθήσασθαι reposui ex HPViMaCl ut coni Re παρα- μυθήσεσθε V edd 10 καὶ ante ὑμῖν Ma 12 τοῦ inserui ex  HVMaCl om PVi edd 13 ἀπ’ — ἐκκλησίας in marg P 2  14 αὐτὸν HMa sed in ’ in ' in m 2, CI αὐτὴν Vi sed τὸν  supra τὴν m 2 Ι ἐκχειριεῖ V 16 πυρὶ καὶ σιδήρῳ Ρ Mor  17 τὰ ἐκείνου VMaCl 18 ἐθελήσοι Ρ Mor
marginal RIV 278
footnote 1 cf. p. 283, 11 5 cf. ad p. 259, 19; 280,16; 328,9; t. IV  977, 13 R 10 sq. Dem. Phil. III p. 119, 6 sq. 11 cf. ad  p. 285, 9 sq. 2 ἡ Vi 3 οὐ inserui ut inser P 2 et coni Mor et Iacobs  Rev 4 om libri edd οὐδὲν τὰ πολλὰ coni Gasda 4 αὑτῶ  scripsi αὐτῷ HVPViMa edd αὐτὸ CI Ι ὑπάρξειν Mor Ι περὶ  CI 5 αὐτῷ libri edd | πυθῶνας Vi Ι οἶδεν H οὐδὲν Ρ  Mor qui οὐδεὶς coni 6 αὐτὸν reposui e libris αὐτὸν edd  Ι οὕτως Mor sed γρ οὕτος in marg | μόνον in marg Vi 2  10 καλὸν Vi 13 ἀνασώσειν Vi 15 ἔρρωται scripsi cum  Iacobsio Lect 105 ἔρρωτο libri edd | οἷδαεν Ma οἶδα Vi | οὐ  scripsi με HVPMaCl edd om Vi οὐ post με inser CI οὐ- δένα ἢ ἐμὲ coni Re, μάτην Iacobs Add 167 Lect 105 Rev 4 |  κοπτέτω Vi sed κάτα in marg add m 2 17 γενέσθω VVi Re
footnote 4 cf. p. 284, 6 1 τίς HViMaCl 2 γε post τῆς Ρ edd delevi 4 αὑτηὶ  Cobet Coll 288 5 μενεῖ scripsi cum Iacobsio Lect 105 Gasda  Cobeto μένει VViCl sed in hoc in μενεῖ corr m 2, Re μένοι  PMa sed in hoc o in ras m 2, Mor μένη H 5 τίς HVVi 6 πεπονημένων Ma sed πε antepos m 2 | δὲ edd 7 ἀμνη- μονήσειέν Η Ι οὖν Ma | τούτου inserui e libris om edd  12 εἶδεν HV | τῷ e τὸ corr CI 2 14 μονονοὺ scripsi ex HV  MaCl coll p. 116, 6; t. IV 379, 18; V 306, 8 μόνον οὐ PVi edd 15 οὐ κεκράτηκα scripsi ex HVMaCl οὐκ ἐκράτησα PVi  sed in hoc κα in marg ad σὰ m 2, edd Ι τὰ ante τῆς Vi  16 στραγγεύομαι coni Iacobs Rev 4 | πάντως V ποτε MaCl  18 αἰτεῖν Vi sed ζητεῖν in marg m 2 | στεφάνων Ma sed ἄνων  in ras m 2 | ἦν τιμότερον Vi 19 οὕτως HV | μισῇ reposui e  libris μισεῖ εἰ edd
marginal R IV 279
footnote 9 cf. ad p. 107,6. Isocr. Archid. p. 125 a 12 cf. adp. 318,2 18 cf. p. 258, 18. t. IV p. 333, 3 Ι p. 38, 3 sq. t. IV 386, 8 1 πάντας Vi sed των supra τας m 2 πάντων HV Ι ὑπερ- βεβηκέναι V 2 αὐτὸν libri edd | ὁμολογῆ ViMaCI 6 λοι- δορήσαντας Ma sed ον supra αν m 2 7 τοῦτο HViMaCl 8 ἆρα Cl | καὶ inser Ma 2 om CI 9 νομίζειν ἔχειν Vi  MaCI Re 11 ὁμολογεῖ Vi sed ὡμολόγηκε in marg m 2  13 μεῖζον Ma sed in μείζω corr m 2, CI Ι ἐθέλει Ρ Mor  14 οὐδεπώποτε scripsi οὐδὲ πώποτε libri edd 15 τοῦτο Vi  CI Ι πόλεμος Mor 16 τοῦτ’ scripsi ex HVP sed in hoc τ’ in  τον corr τοῦτο ViMaCl edd | οὖν om Mor | ἔφθην MaCl  18 δὲ Ma 19 πατρῷε ΗΡ | Δήμητερ scripsi ex HViMaCl  cum Gasda δημήτηρ VP edd 20 ἴαχε HCI ἥλιε Vi sed  ἴακχε in marg m 2 | καὶ ἥρωες Ma sed καὶ ἥ in ras m 2
