@node
@author=Libanius, Libanius
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Richard Foerster
@filename=tlg2200.tlg00519.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane
@publicationStmt=University of Leipzig, tlg2200.tlg00519.opp-grc1.xml.
@respStmt=Gregory R. Crane, Editor-in-Chief, Perseus Digital Library, Digital Divide Data, Corrected and encoded the text, Matt Munson, Project Manager (University of Leipzig), Annette Geßner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor, Greta Franzini, Project Manager (University of Leipzig), 2013-2014, Frederik Baumgardt, Technical Manager (University of Leipzig), 2013-2015, Simona Stoyanova, Project Manager (University of Leipzig), 2015, Project Assistant (University of Leipzig), 2013-2014
@sourceDesc=Richardus Foerster, Richard Foerster, Libanius, Declamationes XIII-XXXX, B.G. Teubner, Leipzig, 1911, 6, Internet Archive.
@sponsor=University of Leipzig
@title=Declamatio 19
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:57:52Z

4498	marginal R IV 240
marginal R IV 241
footnote 2 εἰς σκέψιν reposui e libris σκέψεως edd 5 Δημοσθέ- νης inser Mor om libri 6 Ἀθηναῖοι inserui ex Ath om Ρ  edd 9 τοὐμοῦ reposui e libris τοῦ μοῦ edd | τουτονὶ re- posui e libris τοῦτον edd 10 μηδὲ scripsi cum Iacobsio  Lect 100 Rev 3 et Gasda μήτε libri edd
footnote 1 τῆς ἐμῆς inserui e libris om edd 2 ἐλεεῖ scripsi  ἐλεεῖν libri edd οἷος ἐλεεῖν coni Gasda | ὧσι τί Ρ 3 μή τί γε  scripsi cum Gasda μή τι γε Ath μή τοι γε Ρ edd | τὸν om Re 5 ὑμῶν scripsi e Ρ cum Sinteni et Gasda ἡμῶν Ath edd 8 τε καὶ] βίᾳ coni Iacobs Rev 3 | πρὸς τὸν ἐχθρὸν ἐμοῦ τε  καὶ ὑμῶν ἑλκομένου coni Mor | τ(??) ἐχθρ(??) Ρ 9 τὸ inserui  om libri edd 11 ἐλεεινότατον scripsi auctore Gasda ἐλεεινό- τερον libri edd 12 δ’ inserui, Καὶ ante μηδεὶς Gasda om  libri edd 15 καὶ inserui om libri edd 22 οὖν inserui  cum Sinteni et Gasda qui etiam de καὶ θαυμαστὸν cogitavit,  δ’ Iacobs Rev 3 om libri edd
marginal R IV 242
footnote 5 Dem. p. 156,17 6 Aeschin. fals. leg. § 26 et 27 sq.  Dem. Aristrcr. § 111 p. 657,20. Nep. Iph. 3,2 15 cf. t. II 132,17 2 μοί τις παρίστατο scripsi ex Ath μοι τίς παρίσταται P  sed αι ex o corr m2 μέν τις παρίσταται edd 4 πρὸς ἑαυτὸν  inserui coll p. 281,6; 322,6; 323,15; 337,10 om libri edd  5 τοῦ scripsi τοὺς Ath om P edd 7 ἔκείνων Ath edd  11 κακὸν οὐ scripsi ex Ath cum Iacobsio Lect 100 Rev 3 κακόν  οὐ P κακόν. οὐ edd 19 οὕς scripsi ὧν libri edd 24 ἤκουεν  scripsi ex Ath ἤκουσεν P edd
footnote 1 sq. cf. t. V 87, 14 2 Thuc. VII 75, 5 5 Xen. Hell.  IV 8, 10 sq. 9 Thuc. VIII 71, 1; 91,1 15 cf. p. 288, 19; 324, 13 18 cf. t. v 498, 18 sq. 19 cf. p. 228,7 et ad t. V 477 10 sq.  Isocr. paneg. § 89 p. 58 e 20 Her. VII 35 1 Δήλιον scripsi cum Gasda δῆλον libri edd 2 τὰς in- serui auctore Gasda om libri edd 4 ναυμαχίαι Ath  7 κατακλεῖσθαι Ath 9 τί Ρ edd 10 μοι τίς Ρ Mor | τῶν  coni Mor 12 τοὺς scripsi cum Iacobsio Lect 100 Rev 3 coll  p. 283, 3; t. II 553,11 τοῦ libri edd 16 κατήνεγκε inserui  coll p. 268,23; t. II 27,2 om libri edd 17 οὐ(1) scripsi οὐδὲ  libri edd 19 πλεύσασα scripsi cum Iacobsio Add 354 Lect  101 Rev 3 et Cobeto Coll 286 πεζεύσασα libri edd 20 πλεύ- σασα Ath cf. Iacobs Anth Pal III 592 | ἔδειξεν Ρ et γρ in marg  Mor ἐνίκησε vel δέδμηκε coni Iacobs Lect 101, ἐνίκησεν vel  ἥττησεν Rev 3
marginal R IV 243
footnote 1 cf. t. V 477, 6 2 cf. p. 207,4 4 cf. p. 208, 10 sq. Her.  VIII 143; Lyc. Leocr. § 71 10 cf. t. II 32, 6; t. IV 259, 8 R 15 cf. t. IV 255, 10; 298, 12 R 16 cf. p. 214,6 2 καὶ ante τοῦ libri edd delevi auctore Cobeto coll. t. II  286,2; 551,23; IV 163,15; V 16, 3 ὑπὲρ coni Iacobs, καίτοι  Mor qui simul adnotat: „Hic lacuna est in Graecis“  etiam cogitaverunt Sintenis et Gasda 3 ᾔδει scripsi cum Co- beto ᾔδη Ath Mor ἤδη Ρ Re 15 ἀργοῦντα scripsi ἀερ- γοῦντα libri edd | ἂν inserui cum Gasda om libri edd  16 καὶ τί δεῖ πολλὰ λέγειν; coni Gasda at cf. p. 214,6  20 τοὺς μὲν λόγους scripsi auctoribus Iacobsio Lect 101 Rev 3  et Gasda τοῖς μὲν λόγοις libri edd 21 χαίρειν inserui cum  Gasda om libri edd | με delendum censet Iacobs Leet 101 Rev 3
footnote 7 Plat. Lys. p. 222 B; Prot. p. 360 D 11 cf. t. V 486, 13 13 cf. t. Y 551, 14 23 cf. p. 89, 15; 327, 9 4 πῶς (vel οὕτως) coni Iacobs Lect 101 Rev 3 10 num  κατατρῖφαι? at cf. ad t. IV 125, 9 11 ἀναστρέψατε Ρ sed σ  inser ἀνατρέφατε Ath | ὑμῖν Ath 12 δὲ inserui om libri  edd 14 οὖν κρατεῖ scripsi cum Gasda οὐ κρατῇ Hbri edd  ἂν οὑν κρατῇ Iacobs Add 192 Lect 101 Rev 3 οὖν κρατὶ)  Anth Pal III 741 15 ἀπολαύσεις Ath 18 ἢ τί Ρ 20 τις  inserui e Ρ om Ath edd 23 ζηλωτὴν reposui e libris cum  Iacobsio Rev 3 et Sinteni ζηλωτὸν edd
marginal R IV 244
footnote 15 cf. p. 95, 8; 236, 7; t. V 512, 1. Her. VI 114 1 ἐξέταζε scripsi cum Grasda et Sinteni ἔταζε libri edd  3 διαγέγονα scripsi ex Ath διαγέγονε Ρ edd 6 μάχαις in- serui ex Ath om Ρ edd 7 ἔστηκεν libri edd | παρ’ inserui  ex Ath om Ρ edd 8 τάδε Ρ 9 εὐχόμην scripsi ex Ath  cum Gasda εὐχόμενος Ρ edd 10 ἡμᾶς Ath 15 Κυνέγειρος  Cobet Coll 286 at cf. 11. 11. 18 ἐξόδου om Ath sed in marg  lectio parum certa 28 ἐκείνας scripsi ἐκείνους libri edd |  ἐνεβάλεσθε Ath
marginal R IV 246
footnote 3 cf. t. III 311, 1; 465, 15; 478,5; IV 144,4 6 Plat. Gorg.  p. 481 D 9 Plat. conv. p. 186 A 10 sq. Dem. cor. p. 247,  9 sq. 16 Dem. 1. 1. 19 cf. ad p. 288, 3 20 cf. p. 94, 10;  t. III 442, 6; t. IV 468, 14 sq. R. [Dem.] epit. § 27 p. 1397, 16 sq.  [Apollod.] bibl. III 15, 4 3 punctuni post εὐχόμην posui, comma libri edd | comma  post Ἥλιε posui, colon libri edd 5 αὑτοὺς reposui e libris  cum Iacobsio Rev 3 αὐτοὺς edd | τοῖς inserui cum Gasda  om libri edd 8 τοῦ scripsi cum Gasda τε Ath om Ρ edd 10 οὐκ ἐκκέκομμαι scripsi cum Gasda et Cobeto Coll 286  coll Dem. 1. 1. οὐ κέκομμαι libri edd 12 τὸ inserui auctore  Gasda coll Dem. 1. 1. om libri edd 17 ἀπολεῖσθαι scripsi  ἀπολέσθαι libri edd ἂν ἀπολέσθαι coni Gasda 18 μὴ post  εἰ Ath 19 εἴδετέ scripsi ἴδητέ libri edd ἴδοιτε Gasda
footnote 18 cf. t. IV 491, 3 2 καὶ inserui ex Ath om Ρ edd | ὀνήσαιμι reposui e libris  cum Gasda ὀνήσαιμεν edd 5 νὺν libri edd 6 με coni  Gasda 9 πατέρων scripsi coll p. 323, 12 auctoribus Iacob- sio Lect 101 Rev 3 Not. crit. in Lib. apol. 34 et Gasda qui  aut πατέρων aut προγόνων coniecerunt παρόντων libri edd 12 μόνων Sintenis 13 οἱ reposui e libris οἳ edd | num  γράψωσι scribendum? | τε Mor sed γρ δὲ in marg δὲ libri  τῷ coni Gasda 16 διαβεβλήσεσθε scripsi cum Gasda et Co- beto Coll 286 διαβέβλησθε libri edd 20 ἕλλησι Ρ 21 ἔγνω- σθε scripsi cum Pappaiannopulo ἔγνωσται Ath ἔγνωσαν Ρ eed  αν corr ἐγνώσθητε edd
marginal R IV 246
marginal †
footnote 7 cf. t. IV 263, 22 R. Thuc. II 53, 3 8 cf. p. 181, 1; t. IV  282, 18 R 18 cf. p. 180, 12 2 πάντας scripsi cum Iacobsio Rev 3 πάντως libri edd 5 τῶν reposui e libris cum Iacobsio Rev 3 τοῦ edd τῶν  τοῦ coni Gasda 11 συμπολεμήσωμεν coni Gasda 12  μνῆσθαι inserui ex Ath om Ρ edd | χάριτος scripsi χάριτας  Ath χάριν Ρ edd 15 βελτίστους scripsi cum Iacobsio Lect  101 Rev 3 Not. crit. in Lib. apol. 17 et Gasda βελτίους libri edd 16 τοὺς βελτίστους ante ἀφώνους libri edd delevi cum Iacob- sio et Gasda 18 αὐτῷ libri edd 19 locum graviorem labem  contraxisse vidit Mor („Graeca hic mutila et perturbata“)  coniectura eius γράψει τὰ εἰς χρείαν minime sublatam esse  patet
footnote 3 Xen. comm. IV 1, 1. Isocr. Hel. p. 210 b. Plat. Phaedr.  p. 234 D 8 Dem. p. 10,6 11 cf. p. 95,9 | cf. p. 236,7 12 Dem. Lept. p. 465, 9 2 ἐάσαι libri edd 3 παίζων scripsi coll 11. 11. παίζων  μήτε πίνων Ath πίνων Ρ sed γρ παίζων in marg, edd  5 Ἕλληνας, διὰ πρέσβεων Ἀθηναῖοί coni Sintenis 9 λε- γέσθω scripsi, ut coni Mor λέγεσθαι Ath λέγεσθε Ρ edd  10 ἐπέδωκεν delendum censet Iacobs Lect 101 Rev 3 11 Λεὼς  scripsi cum Iacobsio λεὼς libri edd 14 ἡμῶν Re 16 ἂν  δὲ scripsi cum Iacobsio Lect 101 Rev 3 Sinteni Gasda ἄν τε  libri edd 18 comma post συμβάν posui, punctum libri edd 19 με scripsi auctore Sinteni μὲν libri edd 21 εἰ scripsi  ex Ath ὡς Ρ edd
marginal R IV 247
footnote 5 cf. p. 308, 9 9 Dem. Phil. IV p. 132, 18; ep. p. 1475,1 12 cf. t. IV 259, 1 sq. R 13 sq. cf. p. 258, 3 sq. t. IV 296,  15 R. Dem. cor. p. 254, 20 sq. 326,11 15 Dem. Phil. III  p. 118, 11; 129, 9 sq. cor. p. 252, 1 5 οὕτω scripsi auctore Cobeto Coll 286 τοιούτοις AthP edd 6 ἀνάλωσεν reposui ex AthP ἀνήλωσεν edd 8 καθε- κάστην Ρ 10 πόλιν, τὰ τοιαῦτα ἐροῦσι γάρ, vel γὰρ ἐροῦσι,  κελεύσουσιν coni Iacobs Lect 101 Rev 3 11 οὐκοῦν scripsi  ex AthP οὐκ οὖν edd 12 οὐ ante Δημοσθένης inserendum  coni Gasda | ψεύδη scripsi cum Gasda ψεύδη Ath edd sed γρ  ψεύδει in marg Mor ψεύδει Ρ sed ή suprascr m 2 ὅτι ψεύδη  coni Iacobs Lect 101 Rev 3 13 signum interrogationis posui  punctum libri edd | ναί in marg P 2 edd cancellavi 14 σιτοπομ- κίαν, κωλύων διορύττεσθαι reposui e libris cum Iacobsio Rev 3  et Sinteni σιτοπομπίαν κωλύων· διορύττεσθαι edd 15 πελο- πόνησον libri edd 16 et 17 signum interrogationis posui  punctum libri edd 19 λύει scripsi auctore Sinteni ἄγει libri edd
footnote 3 Dem. p. 1078,25 9 cf. p. 331,15; t. IV 262, 16 R  10 cf. ad p. 288,3 | cf. p. 308, 14 sq. 14 cf. ad p. 99,8; 326, 2;  t. IV 263, 6 R. Isocr. paneg. § 58 | Soph. Oed. Col. 461 sq.  15 cf. p. 326,2; t. IV 263, 1 R. Eur. Heracl. 31 sq. 16 cf. ad  p. 41,6; 99,14; t. IV 303, 11 R. Phryn. trag. fr. Nauck. p. 721 2 1 ἀμυνουμένους Cobet Coll 286 5 ἐξεπέσατε Ρ | τάδε Ρ 6 καθεκάστην Ρ |, ταῦτα cancellavi 7 ἕως scripsi cum  Iacobsio Add 192 Rev 3 et Gasda ὡς libri edd 11 δεησο- μένην scripsi ex Ath δεηθησομένην Ρ edd 15 πρὸς τοὺς  scripsi coll p. 32,16; t. I 454,14 πρὸς libri edd τοὺς coni  Gasda 16 Μίλητον scripsi μιλῆτιν libri edd | ἀποκρινεῖται  reposui e libris cum Iacobsio Add 129 Lect 101 Rev 3 ἀποκρι- νεῖτε edd sed γρ ἀποκρινεῖται in marg Mor | τοῖς inserui om  libri edd 17 πρέσβεσι Mor sed γρ πρέσβεις in marg πρέσβυς  Ath πρέσβ(??) Ρ 18 οὕτω ante πεπτώκαμεν inserendum cen- sent Iacobsius Add 129 Lect 101 Rev 3 Cobetus Coll 286 | πε- πώκαμεν Ρ et γρ in marg Mor
marginal R IV 248
footnote 9 Dem. p. 606, 26 10 cf. t. I 104, 8; II 211, 12 18 cf.  p. 349,6; t. IV 298, 11 R 1 ἡττήθημεν μέν inserui e Ρ ἡττήθημεν Ath om edd  2 Δημοσθένην scripsi cum Iacobsio Lect 101 Rev 3 et Gasda  δημοσθένης libri edd 8 καὶ ante πάλιν Ρ edd delevi  9 νουθετῶ μὲν Re 12 punctum post κληρονόμοι posui, signum  interrogationis libri edd | τῶν inserui e libris cum Iacobsio  Lect 102 Rev 3 Sinteni Gasda om edd 14 ἐκβαλεῖ scripsi  cum Gasda et Cobeto Misc 147 ἐκβάλῃ libri edd | τὸν δὲ re- posui e libris cum Cobeto τόνδε edd | τὸν δὲ reposui ex Ath  cum Cobeto τόνδε Ρ edd 16 δεῖ scripsi δεῖν libri et coni  Sintenis δεῖνα edd οὐ δεινὰ Iacobs Lect 102 („nonne  num“) Rev 3 δὲ Cobet 18 ἔοικας scripsi ἔοικε libri edd
footnote 6 cf. p. 311, 9 10 cf. p. 302, 12; 311, 8 Ι cf. p. 257, 16  11 cf. p. 258,17; 302,13; 310,14 14 cf. ad p. 224,9  16 cf. p. 238, 16; 259,19; 335,5; t. IV 306,11; 312,14; 951,8;  977,13; 1003, 14 R. Dem. cor. § 136. Diod. S. XVI 85 cum nota  Wesselingii t. II p. 147 11 τούτους] τοὐναντίον δῆλον P 2 Mor 3 ὁ δ’ scripsi ex Ath ὅδ’ Ρ ὃ δ’ edd 6 signum in- terrogationis post ἀναμνησθείς inserui cum Sinteni om libri edd 7 ποίων; scripsi ποίων· Ath ποιῶν Ρ edd πότερον Gasda  et Cobet Coll 286 8 τοὺς Ρ 9 οἷς scripsi οὓς libri edd δι’  οὓς coni Gasda | οἶδεν Mor sed γρ εἶδεν in marg εἶδεν Ρ  10 ἐστὲ scripsi cum Gasda εἰσὶ libri edd Ι Χαλκίδος cancellavi  | σώζονται reposui e libris cum Gasda σώζεται edd sed „Graecis  hic corruptis divinandum fuit interpreti" Mor 12 punctum  post ἠδικῆσθαι posui, signum interrogationis libri edd  14 πεζεταίρους scripsi πεζαιτέρους libri edd cf. ad p. 224,9  16 ἔχω scripsi ἔχων libri edd 16 ἃ inser P 2 om Ath |  φείσεται scripsi φείδεται libri sed σ supra δ P 2, edd | signum  interrogationis posui om libri edd
marginal R IV 249
footnote 1 [Plat.] Eryx. p. 395 B 2 cf. t. IV 950,26 R | Dem. cor.  § 102 et 105 efc 312 p. 260,9; 261,15; 329,18 3 cf. p. 320,  11; t. IV 299, 23; 977,15; 1003, 17 R. Glotz Bull. Corr. Hell. XXXIII  p. 526 sq. 4 Dem. cor. § 169 sq. et 177 sq. 7 cf. p. 228,6.  Dem. cor. p. 247, 17 15 Dem. fals. leg. p. 380, 22 17 sq.  Dem. cor. p. 324, 8 sq. Polyb. XVII 14. Bull. Corr. Hell. XXI  592 sq. cf. Er. Preuner, Delph. Weihgeschenk p. 7 sq. 1 num πολλῷ ῥέοντι, ut p. 334,12 et Dem. 1. 1.? at cf.  t. IV p. 306, 11 R | πολύν ἀντιφέροντι scripsi συναντιφέροντι libri  sed ἶσον supra σὺν P 2, edd | colon post συναντιφέροντι Ρ sed  del m 2 2 (1 et 2) et 3 signa interrogationis posui colon  libri edd 2 τὸν Ath | πονηρῷ inserui e libris om edd  4 με ante τούτων Ρ 7 Πέλλην Re 11 διαταῦτα Ρ  15 et 16 signum interrogationis posui punctum libri edd  16 ἀθροίσει scripsi auctore Iacobsio App Pors 311 Lect 102  Rev 3 Anth Pal III 651 ἀθρήσει libri edd 17 προδότας scripsi  coll. Dem. p. 324,18 προδόντας libri edd | Δάοχον scripsi (Mus.  Rhen. XXXII 90) δόαχον libri edd
footnote 2 Dem. cor. p. 325, 14 | Xen. Ages. 8,8 3 cf. p. 311,1  6 Dem. cor. p. 324, 20 sq. 9 Aeschin. Ctes. § 163 p. 77, 6  15 Thuc. I 138 17 Her. V 94 | Dem. Phil. II p. 70, 27 1 γε scripsi τε libri sed γε add P 2 τέ γε edd | ἐπιστέλλει  libri sed λεῖ’ suprascr P 2 corr Mor | ἥκετε scripsi cum Gasda  ἥκατε libri edd 7 διασπάσασθε reposui e libris cum Ia- cobsio Lect 102 Rev 3 Anth Pal III 651 Sinteni Gasda Cobeto  Mnem. N. S. III 248 διασπάσασθαι edd 9 θῶ inserui auc- tore Gasda om libri edd | φείσεσθαι scripsi φείσασθαι libri  edd 12 δὲ cancellavi | τί &lt;πλέον&gt; coni Gasda | τῇ  φιλανθρωπίᾳ scripsi τῆς φιλίππου φιλανθρωπίας libri edd  φιλανθρωπίᾳ ante τῆς excidisse coni Gasda 14 φοβερώτερον  scripsi cum Gasda φοβερόν libri edd ἀντὶ vel πρὸ ante τῆς  excidisse coni Iacobs App Pors 311 Lect 102 Rev 3 Anth Pal  III 651 15 ἐκείνου scripsi ex Ath cum Iacobsio et Gasda  ἐκείνης P edd 16 πολλὴν διδοὺς Ath 17 εἰ(1) scripsi cum  lacobsio et Gasda οὐ libri edd
marginal R IV 250
footnote 2 cf. p. 325, 17 4 Dern. 01. II p. 23, 15 sq. 6 Dem.  Phil. II p. 73, 3 sq. Lib. vit. Dem. p. 4, 16 7 Plat. Gorg.  p. 462 E 10 cf. p. 199, 1; 250, 15. Dem. fals. leg. p. 362, 29 11 cf. p. 335, 1 14 cf. t. IV 283, 17 R 15 Dem. 01. I  p. 10, 2; 19, 9 | [Dem.] Erot. p. 1410, 2 17 cf. t. IV 254, 15 R 1 ἐνέγκαμεν ἂν καὶ ἐνέγκαιμεν ἂν Ath | ἢ ante ζῆν libri  edd delevi διαζῆν coni Gasda | ἐν(2) inserui cum Gasda  om libri edd 5 καλῶς coni Mor 6 ἐστι inserui ex Ath  om Ρ edd 8 δὲ post ἐγὼ inserendum coni Gasda 9 καθη- μέραν Ρ 10 ἐγκαταλεγόμενος ad ἐν ταῖς in marg adscr P 2  14 ἐστιν om Ath 20 μὴ δ’ Ρ 21 ὥστε reposui e libris  cum Iacobsio Lect 102 Rev 3 Anth Pal III 273 Sinteni Gasda  οὔτε edd
footnote 6 cf. p. 336,4; 354,9; t. IV 257,16; 278,15; 296, 7 R  7 Dem. cor. p. 302, 25 2 νικήσει et γράψει scripsi cum Iacobsio Rev 3 νικήσειε  et γράψειε libri edd 2 τις om Ath 3 Ἀθήνησιν scripsi e Ρ  ἀθήνησι Ath Ἀθήνῃσι edd 4 τὸν inserui coll t. IV 257, 2 R;  p. 238,11; IV 118, 1 om libri edd 5 ὅτι Ath | βούλεται re- posui e libris βούληται edd 6 δέξαιτο scripsi cum Gasda et  Cobeto Coli 287 δέξοιτο libri edd | μὴ δὲ Ρ 7 Ὑπερίδῃ  scripsi coll p. 287,15; 332,14; t. IV 265,4; 306,14; 313,11;  321, 14 R ὐπερίδει Ath edd ὑπερίδη Ρ Ὑπερείδῃ Cobet  Ὑπερίδου Gasda | Δημομέλει reposui e libris cum Cobeto  δήμῳ μέλει edd Δημομέλους Gasda δήμῳ μέλοι Iacobs Rev 3  | γεγραμμένοις inserui cum Cobeto om libri edd 9 ταὐτῇ  scripsi τοιαύτη libri edd τῇ αὐτῇ Cobet | αὐτὸν ἄνθρωπον  scripsi ἄνθρωπον libri edd αὐτὸν Iacobs Rev 3 et Cobet  12 ψήφισμα Ath 13 ὐπ’ scripsi ὑπὸ libri edd 18 ἐκεῖνο  scripsi ἐκεῖνος Ath ἐκείνως Ρ edd
marginal R IV 251
footnote 2 cf. p. 296, 14 sq. 7 Dem. fals. leg. p. 436, 20 sq.  10 Orac. Sib. apud Plut. Thes. 24,5. cf. p. 335, 10 sq. Pind.  Pyth. II 146 14 Dem. 01. II p. 24, 18 sq. 15 Dem. cor.  p. 225, 26 17 Xen. Hell. II 1, 29 2 με] μὲν P 3 οὐχ scripsi auctore Gasda οὐδ’ libri  edd 4 μὴ scripsi auctore Sinteni μοι libri edd μοι &lt;πε- πραγμένων&gt; coni Gasda | ἐθέλειν Ρ 7 num ὑμὶν  dum? 10 ᾀδόντων scripsi ex Ath καλούντων P edd  11 εἶδε Ρ et γρ in marg Mor 13 βούλετ’ scripsi ex Ath  βούλεται Ρ edd | εὐψυχίαν scripsi coll p. 314, 7 cum Iacob- sio Lect 102 Rev 3 Sinteni Gasda εὐτυχίαν libri edd  ψυχὴν Weiske Hyp. err. II 47 15 ἀκούω Ρ Ι τῆς τοῦ Μήδου  κρατήσαντα scripsi ex Ath cum Sinteni κρατήσαντα τῆς τοῦ  δήμου Ρ edd 18 οὐκοῦν ὃ reposui e libris cum Iacobsio  Rev 3 et Sinteni οὐκ οὖν ἁ edd | ζητεῖ coni Sintenis | comma  post μάλιστα posui, post ἐζήτει Ath edd om Ρ
footnote 11 cf. p. 296, 1 1 τομὲν Ρ | χαρίσασθε scripsi ex Ath cum Sinteni et Gasda  χαρίσασθαι Ρ edd | τὸ om Ath 2 μηκέτι Ath | με inserui,  ἐμέ Gasda om libri edd | το(1) P 5 ἀλλ’ ὥσθ’ Ath | ὅτε scripsi  coll t. III 337, 11; IV 211, 1; V 14, 18 ὅτι libri edd | πραύναι  libri edd cf. t. IV 279, 17 6 σὺ scripsi cum Iacobsio Add 32  Lect 102 Rev 3 Sinteni Cobeto Coll 287 οὐ libri edd 8 οἷόν  τε Ath 9 &lt;δεῖ&gt; ἔχειν. οἱ coni Gasda at cf. ad t. II 553, 1 |  scripsi cum Iacobsio 11. 11. οἱ libri edd 10 ἐτιμήσαμεν scripsi  ἐτίμησαν libri edd | τον Ρ 11 ταῦτα Ath ταῦτ’ Ρ sed  ταῦθ’ suprascr m 2, et γρ in marg Mor | ἀρκέσαι scripsi ἀρκέ- σειν libri edd | τὸν θάνατον post ἐκεῖνον inser P 2 12 ὅτε  ecripsi δὲ libri edd 13 σαυτῷ scripsi αὐτῷ libri edd  15 λυπούμενος in lac 4 litt om Ath 16 χαίρων Ath 16 ἐπ’  om Re 19 γονέας τῶν scripsi auctore Cobeto Coll 287 τῶν  ἀστῶν libri edd οἰκείους vel συγγενεῖς coni Gasda
marginal R IV 252
footnote 12 Thuc. II 46 15 cf. t. IV 265, 4 R. Dem. Phil. III  p. 129,18 | Dem. fals. leg. p. 435,6. Plut. Dem. 13,5; 23,3.  Arr. anab. | 10,4 cf. A. Schaefer Dem. III 137 2 1 πεσόντ’ ἃς Ath 7 παραμυθηταί post γένεσθε inserendum  vel χρῆσθε pro γένεσθε scribendum coni Iacobs Lect 103 Rev 4  | πατέρες scripsi σωτῆρες libri edd 8 γεγεννημένοι Re  9 τῶν ἐπ’ ἐκείνοις ῥηθησομένων λόγων ὑπομνῆσαι (sc. ὑμᾶς)  ὑπομνήσεσθε δέ, εἰ vel λόγων οὐκ ἀμνηστεῖν· οὐκ ἀμνηστήσετε  δέ, εἰ coni Iacobs Lect 103 | σεμνύνατε scripsi ὑμνήσειν· εἰ  libri edd 15 Πολύευκτε reposui e libris cum Gasda πολύ- εκτε edd | Μοιρόκλεις scripsi (Mus. Rhen. XXXII 90) μυρόκλεις  libri edd 17 πολιτεύεσθαι Ρ 20 ἐπὶ ὁμοίοις Ath
footnote 3 cf. p. 273,19; 278,10; 308,14. Dem. p. 954,15; 840,15.  Aeschin. Ctes. § 77. Plut. Dem. 22, 2. vit. Χ or. p. 847 c  10 Soph. Ai. 550 14 Thuc. VII 77, 1 17 cf. p. 310, 13  19 cf. p. 269, 15 6 μὲν om Ath | δὲ Ath edd 7 δὴ Ρ 8 τέκῃ scripsi  cum Gasda τέκοι libri edd 12 τις ὑπόλοιπος ἄξιος Ρ et γρ  in marg Mor 16 ᾤεσθέ scripsi cum Gasda et Cobeto Coll  287 οἴεσθε libri edd 19 ἐν om Ath 20 κεναῖς scripsi  (Mus. Rh. XXXII 95) e Ρ coll t. I 500,21; t. IV 492,21; 830, 30;  835,25 R; ep. 335 cum Abreschio ad Aesch. Prom. 37 et Cobeto  κέν Ath edd κἀν vel ἐν Iacobs Rev 4 (praesentes) et Philostr.  Im. 668
