@node
@author=Libanius
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Richard Foerster
@filename=tlg2200.tlg00525.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane
@publicationStmt=University of Leipzig, tlg2200.tlg00525.opp-grc1.xml.
@respStmt=Gregory R. Crane, Editor-in-Chief, Perseus Digital Library, Digital Divide Data, Corrected and encoded the text, Matt Munson, Project Manager (University of Leipzig), Annette Geßner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor, Greta Franzini, Project Manager (University of Leipzig), 2013-2014, Frederik Baumgardt, Technical Manager (University of Leipzig), 2013-2015, Simona Stoyanova, Project Manager (University of Leipzig), 2015, Project Assistant (University of Leipzig), 2013-2014
@sourceDesc=Richardus Foerster, Richard Foerster, Libanius, Declamationes XIII-XXXX, B.G. Teubner, Leipzig, 1911, 6, Internet Archive.
@sponsor=University of Leipzig
@title=Declamatio 25
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:57:29Z

4391	marginal R IV 431
footnote 1 Κορίνθῳ Cl sed ορίνθῳ in ras m2 | τίς HVaViMa 2 μὲν post ἐραστὰς ViMaCl | αὐτῆς post κάλλει ViMaCl 4 τίς HBVaViMaCl Mor | λαίδα τῆς πόλεως Η Ι τὴν ante λαίδα BVa | ἔπεισε in marg Va 5 μεταταῦτα Ma | γενομένων Vi 6 λαμβάνοντα Β 7 ἐπαυτοφώρῳ ΗΜΜa ἐπαυτοφόρω Va | τὸν ante μοιχὸν ΒVa | ἀποκτείνειν ΒVa cf. t. III 406, 22 8 ἐπέμενον Ferr et γρ in marg Mor ὑπέμειναν coni Gasda 9 τίς HVaMVi | ἑτέρου τινὸς ἀντιλέγοντος om Β 11 με- λετῶμεν τὸν ἀντιλέγοντα om MViMa sed in hoc post πραγμα- τικὴ ἡ στάσις in marg inser m 2, Cl πραγματικὴ ἡ στάσις in fine tituli Μ et in marg Ma 2 πραγματική in marg rubr Va 12 Προθεωρία in marg Ma om ViCl Ferr
marginal R IV 324
footnote 8 cf. p. 22,8 15 cf. p. 477,5 19 Eustath. Hysm. II 6; IV 23 1 ἀδοξίαν Va sed οξι in ras 4-5 5litt m 2 | ἐν ante Κορίνθῳ Μ et inser Ma 2 3 λύσειν Re λῦσαι coni Gasda 5 ἐπι- δείξεως Va sed ἔπι in ras m 2 ἐπιδόσεως Β | λόγον Va sed del et χρόνον suprascr 8 ὑμεῖς ViMaCl 10 μὴ om Vi 11 μὴ δὲ HBVaViMaCl Ferr | περὶ VaCl 16 ἶσα VaViMa Cl | δὲ πέρας reposui e libris πέρας δὲ edd sed γρ δὲ πέρας in marg Mor 18 τὸ om Cl 19 Ἡ μελέτη in marg Ma 2 om BVaViMaCl λόγος ἀντιλέγοντος Mor Re 21 δεομένων Η | αὐτῇ ἀπελαύνειν VaMaCl
footnote 15 cf. 1. 1 102, 8 | Plat. rep. IV p. 439 D; Phaed. p. 68 C; 108 A 1 αὐτὴ om Vi | παραινούντων Va sed αινο in ras m 2 αὐτόθι ViMaCl 3 προσποιουμένοις Ma sed πρόσ’ inser Ma 2 4 πειρωμένοις καθιστάναι BVa | καθεστάναι Η 5 καὶ om BVa 6 τινες Va sed ἐς in ras m 2 8 voce φέρε inc Cr fol 95r | κοινὴ HVaViMa 10 ὑμεῖς Va sed ἡ supra υ m 2 | ἐξαμάρτωμεν CrH 12 συνεργοῦντας scripsi e ViMaCl συνε- ροῦντας CrHBM edd συναιροῦντας Va sed σὺν in ras m 2 et γρ συνεργοῦντας suprascr m 2 cf. p. 479, 12; 487,11 | αὐτῶν libri edd 13 ὑμᾶς Cr sed υ incertum 14 ἐγὼ μὲν] ἔγωγε Cr 16 πολίτας post ἀγαθοὺς excidisse coni Gasda 17 ἐνυ- βρίζειν Μ scriptura in Cr incerta | τοὺς νόμους CrH
marginal R IV 433
footnote 17 Isocr. Archid. § 59 p. 128 b 1 παρεχομένους inser Va 2 | ἀν’ ὕσαι Cl sed ' in ~ corr ἀνῦσαι MViMa fortasse recte at cf. ad t. IV 251, 5 2 ᾧ γε scripsi cum Gasda ὅ τε libri edd ὦ τε coni Iacobs Lect 121 4 αὐτὴν scripsi e CrHMaCl ταύτην BVaMVi edd 6 νενο- μισμένων Ma sed μένων in ras m 3 7 τί CrHVAMViMaCl ἀτιμίαν πράξαι Va sed ' in ~ corr m 2, Vi 8 (??) Β ἀτιμίαν Va sed γρ ἀτοπίαν in marg m 2 9 ἀναιδείας scripsi e CrHBVi MaCl ἀτοπίας VaM edd 10 πρώην HVaVi | διαβραχέων Vi | ἀκούσαι scripsi cum Gasda ἀκούσοι CrHVaMViMaCl edd ἀκούσει Β 16 ἄγειν Vi 17 εὐνοίας — 19 εὐπραγίαν om CrH 18 καὶ ante ἀμοιβὰς ViMaCl 20 ἀπέλαβε Vi
footnote 1 Athen. XIII p. 588 b; 589 a. Paus. II 2,5. Plut. Alc. 39,4; Nic. 15, 4. Synes. ep. 3 cf. p. 463 not. 1 4 Arist. Eccl. 441. Xen. Cyr. VI 1, 36. Dem. p. 928, 6 8 Xen. Cyr. V 1, 16 1 σικελὴ Μ 2 θηράσαι libri edd | τὴν ante νεότητα eras Va 4 ἐπιδεῖξαι CrHViMa sed in hoc γρ ἄπο supra ἔπι m 3, ὢ 7 ἐρᾶν πλουσίου Ma 8 ἂν cancellavi cum Gasda 11 δὲ post ἄλλοτε inserendum coni Gasda coll p. 472, 19 at cf. p. 450, 5 sq. 13 μόνον inser Ma 3 μόνω ΒVa 14 τοιαύτην — 472, 1 τιμώμενον citat praemisso titulo τῆς μελέτης ἐν ᾖ τὴν ἐν Κορίνθῳ Λαίδα διώκει τις: μελέτ. τδ Macarius fol 81 r | τοι- αύτην — δελεάζουσαι] ἀντεραστὰς ἔχουσαι πόρναι δελεάζουσι Macar | δελεάζουσι ViMaCl Re et γρ in marg Mor δελεάζουσι(??)ι Va δελεάζουσαν CrH δελεάζουσαι Par. 3017 3017 non bene" Bois- sonade Anecd. IV 291 15 αὐτὰς libri Macar edd | τὰς οὐσίας Ma sed γρ΄ οἰκίας in marg m 2 τὴν οὐσίαν ΒVa ἐκτόπως Par 3017 (Bast Greg. Cor. p. 567; Boissonad. Aristaen. p. 425) at cf. 1. 2; p. 476,10; 478,11; 482,3 17 ἂν ἕλοιτο scripsi e CrHViMaClMacar ἕλοιτ’ ἂν ΒΜ edd ἓλλοιτο Va sed γρ ἕλοιτ’ ἂν in marg m 2 οἶμαι ante ἕλοιτο Cl om CrHVa sed in hoc γρ in marg m 2, Vi Macar
marginal R IV 434
footnote 2 διχόθεν τὴν πόλιν CrH | ὅτε Β 3 ἐκκομίζεται ViMa sed in hoc ο supra αι m 2, Cl sed κ(1) inser et o ex ω corr m 2 | φιλοτιμούντων Vi 5 καταστῆσαι αὐτοῖς ViMaCl | αὐτοῖς Β Va 6 μελέτης Ma sed μέλε in ras m 3 | ἀμελοῦσα Va sed ἀμελ in ras m 2 ῥᾳθυμοῦσα CrHViMa sed in hoc ἤτοι ἀμε- λοῦσα suprascr m 2, Cl 7 ἀσχολουμένη Ma Mor sed διατρί- βουσα suprascr Μα 2 et praemisso σχο. Mor ἀσχολουμένης Β 8 ἐκίνησε Ma sed ε(2) add μ 2 9 γιγνομένη BVaM 10 προτέρας CrH 11 αὐτῶν libri edd 12 ποιουμένους scripsi e Ma πεποιημένους CrHBVaMViCl edd 15 ἐνδεικνυ- μένοις Ma sed οις in ras m 3 16 δοθείσης Ma sed σὴς in ras m3 | προκρίνουσι Ma sed πρὸ in ras m 3 17 τὴν ante τῶν Μ edd delevi 18 τὴν inserui e CrHBVaViMaCl om Μ edd | τὴν ante λαίδα ΜVἱ edd delevi 19 αὐτοὺς Va sed αὐτὰς suprascr m 2 αὐτὰς Β
footnote 14 Dem. Aristocr. p. 643, 10 sq. 1 τὴν om BVa | τὴν προτέραν ἐπειρῶντο Η | πρότερον Va MaCl | ἀναγαγεῖν Va sed να inser m 2 2 μὲν om Re (e Par 3017 inserendum coni Boissonade Theoph. Sim. p. 228) 4 λόγοις BVa | πέφυκε — 5 ἀρετῆς omissa particula γὰρ citat Macarius fol 81 r 5 θηρεύειν scripsi e CrHBVaViMaCl θηρεῦσαι Μ edd ἐρεθίσαι coni Gasda 6 ἔρωτα Μ | ἦν ἄμα- χον Re | ἀμήχανον Β 7 τοὺς MMa sed in hoc οὐ in ἁ corr m 3 | συνοίκους BVaMViMaCl 8 πολλαὶ scripsi e Μ πολλῶ Cr (sed scriptura parum certa) HBVa sed in hoc ω in οῦ corr m 2 et ῶ iterum suprascr m 3, Vi πολλοῦ Ma sed αἰ suprascr m 3, Cl sed οὐ ex ὢ corr, edd ἐκ πολλοῦ coni Re 9 σχήματος scripsi e Μ sed γρ χρήματος in marg, cum Gasda χρήματος Cr HBVaViMaCl edd sed γρ σχήματος in marg Mor | ἠδυνήθησαν Μ 10 τῆς ante λαίδος Cr sed parum certum, Η | κρίνουσι Vi Ma sed in hoc αι supra ι(2) m 3, Cl 11 περὶ Va | voce λαμ- βάνειν des Cr fol 95 v quae sequuntur usque ad p. 481,18 ὰτο]- πίας desunt 12 δεῖν Ma sed v add m 3 | τὴν ὥραν τοῖς βουλο- μένοις Η 13 λύπας ὡς οἶμαι Η | κἀν Vi 17 num δεινὸς? at cf. ad p, 537, 12 R IV 435
footnote 2 cf. 1. 11363,7 sq.; 433,17; 474,8 6 Epigr. apud Athen. XII p. 589 b v. 2. Prop. II 6, 1. Gell. I 8, 3. Alciphr. ep. fr. 5. Georg. Pachym. decl. X p. 189, 11 ed. Boiss. 21 sq. cf. p. 269,15; 324,13 2 ἴσχυσεν Vi 3 ἔτι om Μ | λαβομένην reposui e libris ἐπιλαβομένην edd 6 κατάπλουν Ferr Mor | τῶν inser Ma 2 11 τραφεῖσι coni Mor | τὶς HVaMMa 13 ἐν αὐτῇ πρα- χθέντα Η | ἀτόπου — 16 ὕβριν citat Macarius fol 81 r | οὐκ] τὸ μὴ Macar 15 βεβουλημένων Η 16 μείζων ἀτοπία? cf. p. 480, 7 20 πρώην HVaM 23 ἀκολασίας ἔρως Η | ἔρως om Β
marginal R IV 436
footnote 14 Dem. Timocr. p. 762, 18 1 φανερὰν — 2 πολιτευομένης inser Va 2 | φανερὸν ViMa sed in hoc ο in α corr m 3 2 παρ’ in ras Va 2 4 τὴν — ἄδειαν coni Gasda 8 διαταῦτα BMa | τοίνυν om ViCl inser Ma 3 | τινὸς οἶμαι H 9 οἱ om Η inser Va 2 | πάντες ΒΜ edd inser Va 2Ma 3 om HViCl cancellavi 10 πᾶσιν e πάντες corr Cl 11 μεταμείψει Ma sed γρ΄ μέμψει suprascr m 2 μεταμέμψει Cl 12 εὗρον λύσιν BVa sed in hoc ' in ~ corr m2 13 τελου- μένην Μ sed ἐνεργουμένην in marg, Ma sed ἐνεργουμένην su- prascr m 2, Mor sed γρ ἐνεργουμένην in marg „num ζηλουμένην? an τὴν οὔπω τελουμένην nondum consummatum?" Re 15 συν- ηγορούντων scripsi coll p. 469,3; 483,9; 486,12 συνερούντων ΗΒ Mor Re συναιρούντων Va sed ἑ supra αἰ m 2 et γρ συμβαι- νόντων in marg m 2 συμβαινόντων MViMa sed in hoc συνερούν- των suprascr m 2, Cl et γρ in marg Mor συνεργούντων Ferr cf. p. 469, 12 16 ταύτης Μ Ferr et γρ in marg Mor 17 ἀπελ- θοῦσαν om BVaMViMaCl Ferr | ὅποι om Vi ὅπη in marg Cl ἧ Β ἢ ex ἧ corr Va | καὶ om BVa 18 ὑμετέρας BVa
footnote 11 ἐλευθέρας φησὶ τὰς μὴ πορνευομένας, παρόσον οὐ δου- λοῦνται τοῖς τῆς πορνείας κακοῖς Mm Mor 1 ὑβρίζῃ et διαφθείρῃ scripsi ὑβρίζῃ ViMaCl ὑβρίζοι Η BVaM edd et διαφθείρῃ MaCl sed in hoc η ex οι corr δια- φθείροι HBVaMVi edd 2 μὴ δὲ libri Ferr | τολοιπὸν BVa 4 τούτοισι Va sed eras et supra ι(2) τούτοισι VaCl 5 χρηστοῖς scripsi ex HBVaViMaCl σεμνοῖς Μ edd | ἀνεχρή- σαντο Vi 6 φασίν scripsi φησίν edd | ἡ νεότης Ma sed γρ ὁ βουλόμενος in marg m 3 8 ἐν τῇ πόλει om BVaViMa sed in hoc in marg inser m 2, Cl | γεγόνασιν Va | δεῖ scripsi ex Η VaViMaCl ut coni Gasda δεῖν ΒΜ edd 14 πολιτεύωνται coni Mor „non improbo coniecturam Mor. possit quoque legi πολι- τεύσονται uel πολιτεύσωνται“ Re at πολιτεύονται recte defendit Boissonadius Pachym. p. 189 not. 3 | διάγειν Ma sed δι del 15 ἐγὼ supra παρῄνουν Ma 3 | ἂν inserui om libri edd 17 τὴν — 477, 2 ὀρῶ citat Macarius fol 81r
marginal R IV 437
footnote 3 ἁμαρτημάτων] ἤτοι πορνείας καὶ μοιχείας My 9 θάτε- ρον] πορνείαν MmMa 3 ἕτερον] μοιχείαν My Ma 2 10 τὸ πρό- τερον] τὸ ἑκατέρου κρατεῖν MmMa2 1 ἐσπουδακότας περὶ ταύτην BVa 5 δέον] „sententia postulat εἰ δέ δεῖ. Sed satius est suspicari hic aliquid deesse, e. c. εἰ δὲ φιλονεικεῖς ὧς δέον“ Re at cf. p. 468, 15 6 ἂν poat ἧς inserendum coni Gasda 7 τῆς ἀφ’ ἑκατέρου coni Re | φανείη scripsi φανῇ libri edd | θεοῦ Μ 8 δοκεῖ εἷναί σοι Η ἑκατέρου Μ sed et οὐ in ras m 2 10 ὁμολογήσαις scripsi ὁμολογήσης BVaMaCl ὁμολογήσεις HMVi edd ὁμολογήσειας Gasda | οὐ γὰρ in marg Cl 11 γὰρ ὁ om Vi | πλημελῶν Va MMa 13 ὧς ante ἐξ Vi | ἐξημισείας B 14 τέως post νεότης ViMaCl et inser Va 2 | περὶ ἐκείνην κωμάζουσα inser Ma 2 om BVaViCl 15 καταφρονήσει Va sed πέρι supra κάτα m 2 16 περὶ Ferr et γρ in marg Mor 17 δαπανήσεις Vi Ma sed in hoc ς add m 3 | τῶν ἡδονῶν in lac 7—8 litt om τῶν νέων ViMaCl
marginal R IV 438
footnote 15 Plat. Theaet. p. 145 C 3 τῇ inser Μα 2 4 ἂν Vi | ἀνθαίρετον coni Gasda at cf. p. 388, 9 7 πλημέλημα MMa | νομίζειν Va sed ν(2) in σ corr, Vi 8 μὴ ante δύνασθαι inser Μ 2 | νενικη(??) Ma 9 μεθόδω Β sed κα supra με, VaViMaCl 12 ὅτι VaViMaCl 14 ὡσὰν HVaMa 15 ἀναγκάζωνται reposui e libris cum Boissonadio Anecd. IV 335 ἀναγκάζονται edd 19 μὲν ἑτέ- ρους Ferr et γρ in marg Mor εὐμενεστέρους coni Re μετρίους Iacobs App Pors 327 20 ταύτας κρίνω BVa 22 ἐὰν scripsi cum Gasda εἰ libri edd 23 μενούσῃ Vi
footnote 19 cf. t. II 323, 18 1 αὐταῖς libri edd 2 κοινὴν scripsi e BVaViMaCl κοινῇ ΗΜ edd | ἰδίᾳ post ἀσφάλειαν inserendum coni Gasda 3 ὅτι MViMaCl Ferr et γρ in marg Mor 4 οὐ inserui auc- tore Gasda om libri edd | τιμωρίαν ἡμεῖς BVa 7 ὡς in ὥστ’ corr Cl | φής libri edd 10 τὴν διάνοιαν τοῦ ψηφίσματος Ma 11 τούτοις Vi | ὅτι VaViMaCl 12 ὁμολογουμένοις Ma sed ως supra ὄις m 3 | συνερῶν coni Re at cf. p. 469, 12 14 παιδεύει ViMa sed in hoc σ’ inser m 3, Cl | πλημελὲς Va MMaCl 17 μὴ δὲ libri Ferr | εἷναι χώραν Vi | ἐξ — 20 φρον- τίδες citat Macarius fol. 81 r 18 γίγνεσθαι BVa | τρυφῆς τοίνυν ταύτης Β | τοίνυν] δὲ Macar 19 ἀντεισφερομένης δὲ] καὶ ἀντεισφερομένης Macar 21 γίνεται μόνου H R IV 439
footnote 1 ἐρρῶσθαι MMa sed φθείρεσθαι in marg Mm et suprascr Ma 3 | τῆς πόλεως] τὸν πόλεμον Η 3 τὴν om Η 6 δὴ ante ταῦτα Η 7 πολλήν τις e πολλὴν τῆς corr Va 2 | τις om Β | ἀτοπίαν Va sed ν e σ corr m 2 | πεπεικότος Va sed εικ in ras m 2 8 διαφορᾶ Η | καταγαγεῖν Η 9 ἀπηλάσατε scripsi ex HViMa sed in hoc ε supra η m 3, Cl sed η in ras ἀπελάσατε BVa sed in hoc σατε in ras m 2, Μ edd 11 τοῦ πεπεισμένου BVaViMa sed in hoc γρ τῶν πεπεισμένων in marg m 2, Cl 13 παραγνώμην Vi 14 &lt;ὀ&gt; ἀναγκάζον coni Re at cf. p. 484,8 15 ἐργάζεται Ferr Mor | πλημέλημα VaMMa 16 ἡμῖν Η ΒVaM 20 ἔχε ἱν ἡγοῦμαι scripsi ex HViMaCl ἡγοῦμαι ἔχειν BVaM edd 22 πρὸς in marg add Μ2
marginal R IV 440
footnote 2 cf. ad t. III 338, 18. Synes. ep. 89 3 cf. ad t. II 555, 13. Aristid. or. XLVIII t. II 483, 25 ed. Dind. (II 298, 17 K.) 21 Pind. 01. XIII 6 | Thnc. I 124,3; 18,1 1 ἀκοσμίας Ma sed εὑ supra α m 3 4 μετατσρτέψας Va | πορεύηται HBVaMaCl πορεύεται Vi 5 καὶ ante τὸν Η 9 τὸν ἁ | τὰ ViMa 10 ψηφίσματα ViMaCl | ἐνδείξασθαι τίς HBVaViMaCl 12 προτιμᾶν Ma sed v add m 2 | ἐπειρᾶτο om Β | ψήφισμ’ Cl | ἀκυροῦν Va sed ἀ antep m 2 κυροῦν Vi Ma μὴ κυροῦν Η 17 καταψηφίζεσθε Vi 18 δουλεύοντος scripsi auctore Gasda δουλεύοντα libri edd | voce ἀτο]πίας inc Cr fol 5 v | τῶν om ViCl inser Ma 3 | λόγων Vi 20 ἀποδέχεσθε Ma sed ε(3) in ras m 3 | εὐνομουμένην Va sed eras et ομου in ras m 2 εὐνομουμένην Ma sed εὐ antep et νομ in ras m 3 αἰνουμένην Cl
footnote 1 cf. t. IV 287,8. Her. II 168. Thuc. I 130,1. Plat. rep. IX p. 574 D; 575 B 7 Hes. op. 240. Aeschin. Ctes. p. 73,1sq. 15 Arist. Ach. 285 7 φησὶ γὰρ Ησίοδος πολλάκις καὶ ξύμπασα πόλις κα- κοῦ ἀνδρὸς ἀπηύρα Μa 2Wolf Mor 1 δορυφορεῖν MMa sed τιμᾶν in marg Mm et ἤτοι τιμᾶν suprascr Ma 3 2 θεραπεύσει scripsi θεραπεύσηι Cr θερα- πεύση HViMa sed in hoc γρ δεῖ θεραπεύεσθαι in marg m 2, Cl δεῖ θεραπεύεσθαι Β VaM post θεραπεύσηι spatium —5 litt Cr 5 ὀλιγανθρωπίας Vi 11 μὴ inserui auctore Re coll p. 483,9 sq. om libri edd ἀποῦσα coni Gasda | „post ἀφορμὴν deesse videntur haec ferme: ἐγώ σοι φόνους καταλέξω, ὧν ἐκείνη παροῦσα δέδωκεν ἀφορμὴν“ Re 12 „post ὀκνήσω videtur γὰρ υel δὲ deesse" Re 13 αὐτόχειρ ἡδέως ἂν Ma | πλὴν πότε re- posui e libris πότε Ferr πότε πλῆ ’ν Mor Re qui adnotat: „πλὴν recte deest Wolf. verum eius loco malim γὰρ aut σύ“ πότε πάλιν Iacobs Add 358 15 αὐτῆς libri edd 17 τὴν ante χηρείαν inserendum coni Gasda
marginal R IV 441
footnote 1 sq. Thuc. II 44, 2 1 πολλὰς γὰρ ἐκώλυσε scripsi πολλοὺς διεκώλυσε libri edd πολλὰς vel πόσας διεκώλυσε Gasda 3 γίγνεσθαι Β | πολεμίων M | (??) Ma οὕτω ex οὔτε corr Cl οὔτε Vi | γὰρ inser Ma om Cl 4 πονεῖν Ma sed γρ ποιεῖν in marg m 2 ποιεῖν Μ sed γρ πονεῖν in marg, Vi | (??)τω Ma οὕτω Cl οὔτε Vi 5 „malim φυσάσης, pro patria" Re num ψυχῆς? 7 ποιεῖσθαι παροῦσα Η scriptura in Cr incerta 8 ἐκώλυσεν ViMaCl | συνηγορεῖς scripsi συνερεῖς CrHBVaViMa sed in hoc γρ συναγορεύεις in marg m 2, Cl συναγορεύεις Μ edd cf. ad p. 475, 15 9 κατη- γορε(??) Ma 10 τε inserui e libris om edd 11 προτιμῶν καὶ ταύτην ἐκείνης om CrHViMaCl 13 ἀδοξίαν ὀφλήσωμεν Cr sed parum certum, Η ὀφλήσομεν MaCl 14 εἰς inserui coll Plat. Gorg. p. 519 E om libri edd 15 ἑλλήνων Β 16 λαίδος χωρὶς Cr sed parum certum, Η quae sequuntur usque ad p. 486,2 ἡμᾶς in Cr iam non legi possunt | δ’ MaCl 17 εἰ om Vi | καταλ(??)εται Vi | μὴ δὲ HBVaMaCl μὴ Vi
footnote 13—15 Thuc. I13. Diod.S.XIV 42. 17cf.p.15,11.Thuc. I 13,2 1 τηναρχὴν BVa 2 οὐκ ViMa sed in hoc γρ εὖ suprascr, ὢ 3 (??) Ma 5 παρὰ om Re 6 οἰκεῖν scripsi auctore Re cui oblocutus est Iacobs Add 95 Lect 122 ἥκειν libri edd 7 συνειςσῆλθεν Ma sed σύνεις in ras 2 litt m 3 συνῆλθεν Β sed ησ post συν inser, VaViCl | οὕτω Vi 9 πρὸ ταύτης ἐκ τοῦ μηδὲν γενέσθαι αἰσχρὸν Ma sed β supra πρὸ ταύ- της, ᾱ supra μηδὲν m 2, Cl αἰσχρὸν πρὸ ταύτης ἐκ τοῦ μηδὲν γενέσθαι Vi 10 οὖσα post φαίνεται inserendum coni Gasda 11 δέ inser Va 2 | διὰ inser Ma 2 om ViCl | βραχέων Ma sed v e ς corr m 2, Cl sed v in σ corr m 2 βραχέως Vi | οἷα — 12 πόλει praemissis verbis ποτὲ δὲ οὔτε τῆς προθέσεως ἡ δύνα- μις ἐνεργ &lt;ὸς&gt; φαίνεται οὔτε τοῦ ῥήματος ἄλλη συντακτικὴ δύ- ναμις γίνεται ὧς καὶ παρὰ Λιβανίῳ citat Planudes ad Aesop. fab. 94 ed. Hausrath Byz. Zeitschr. Χ 102 12 ἑταίραν Οἶ’ sed αἶρ’ in ras m 2 ἑτέραν Vi | τῇ πόλει inser Μα 2 om ViCl 13 ἐν-εδείξαμεν Ma sed νε inser m 2 ἐδιδάξαμεν Β Va | θαλάσσῃ ViCl
marginal R IV 442
footnote 3 Her. VI 89. Thuc. I 41 4 cf. p. 35, 1. Thuc. 1 66 sq.; 69, 1 1 ἀξιοχρεωτέρους vel μᾶλλον ἀξιόχρεως coni Gasda 3 ἐπικουροῦντες ὢ sed ου(1) ex υ corr m 2 7 τῇ inser Va 2 8 τὰ inser Ma 2 om Cl | πρώην HVaMa 10 καὶ(1) inser Va 2 11 τῆς ante δόξης edd sed „melius abest a Wolf“ Re delevi τῆς πρότερον vel τῆς παλαιᾶς coni Gasda 12 ἔστι MMaCl ἐστι BVaVi 14 ἰδία πείθουσι scripsi auc- tore Cobeto Coll 294 διαπείθουσι libri edd 20 μὴ δὲ HBVa ViMaCl 21 πορνοβοσκοὺς scripsi auctore Gasda προγόνους libri edd 22 αὐταῖς coni Mor
marginal R IV 443
footnote 2 περὶ BVa | voce πεπλημμεληκότων inc Cr fol 8 v πεπλη- μεληκότων VaMMa 6 σχῆμα Ferr et γρ in marg Mor | εἰσ- πράξεσθαι Vi 9 ταὐτὰ scripsi ex HBVaMMa ut coni Re ταῦτα ViCl sed in hoc in ταὐτὰ corr m 2, edd scriptura in Cr parum certa 12 συνηγοροῦσιν scripsi collp. 475, 15 συνεροῦ- σιν CrHBVa συναινοῦσιν MViMa sed in hoc ερ supra αιν m 2, Cl edd 17 νομίζουσι ViMaCl | αὐτῶν δ’ scripsi ex ΗΜ δ’ αὐτῶν BVaViMaCl scriptura in Cr parum certa αὐτῶν δὲ edd 18 οἷονπερ Vi 20 λανθάνει σε BVa 21 οἰός Re | τ’ inserui e CrH τε Β Va om ViMaCl edd | ἄλλω Η | τὸ om Μ 22 τῷ inserui ut coni Re om libri edd | ἀλυσιτελέσι Vi | τι om Vi
footnote 1 κοινὴ HVa κινῇ Vi 2 προχειρισαμένων scripsi προ- χειρισαμένους libri edd „sed aut ad γράφειν subaudiendum est δι’ αὐτοῦ aut leg. κελεύειν γράφ.“ Re | δὲ Ma sed ὲ in ras m 2 4 ἐγράφη (2) Μ sed γρ ἐπράχθη in marg m 6 πλὴν ὀλί- γων in lac 8 fere litt om Β 7 αὐτοῖς BVa | ὑπάρχοις θ’ sed ς non prorsus certum ὑπάρχει MMa sed in hoc ras 1 litt post ι, Ferr et γρ in marg Mor ὕπ(??)ρ Β 8 τὸ Ma sed ἢν supra ὸ m2 τὴν CrHBVa 10 σὺ om ViMa sed in hoc ante καὶ inser m 2, Cl 11 συνεροῦντας CrHBVa συναινοῦντας Vi Ma sed in hoc ερ supra αιν m 2, Cl cf. 1. 14; p. 469,12 13 ἆρα HViMaCl ἄρα Cr | δόξεις μόνος scripsi e CrHBVa μόνος δόξεις δόξης M) MViMaCl edd 15 τιθεμένων potest defendi, scil. τὴν ψῆφον subaudiendo. malim tamen compositum προστιθεμένων aat συντιθεμένων“ Ke cf. schol. ad t. II 272, 14; IV 98, 11; V 50, 12 | μηδενὶ Cr sed νὶ parum certum, MMa sed in hoc ι add m 2 μηδὲν HBVaViCl et γρ in marg Mor 16 ἄρα Ma 18 τόδε scripsi τό δὲ Πα τὸ δὲ Cr sed parum certum, BVaMViMa edd | δέ τι Mor sed γρ δὲ in marg δέτι Ma | πλημελούντων VaM
marginal R IV 444
footnote 13 Plat. rep. III p. 412 C 1 πεποιηκότος CrH 2 ψηφισαμένῃ Ma sed ψῇ in ras m 2 3 πολεμίοις ViMa sed in hoc in πολέμοις corr m 2, Cl 5 τρόπον Ma sed αἰτίαν suprascr m 2 6 τῆς ἑταίρας om BVaViMaCl 7 ὀλίγοις ViCl sed in hoc οις in ους corr m 2 8 φὴς libri edd 10 δοκούσῃ VaM sed οὔσῃ ex οὖσι corr Va 2Mm | σώφροσιν edd 12 τῆ πόλει Ferr et γρ in marg Mor 14 τὰ inser Va 2 16 κελεύουσι reposui e libris καὶ λέ- γουσι edd sed καὶ in suspicionem vocavit Gasda 17 προστάτ- τουσιν Va sed τατ in ras m 2 18 οὐχ Cr 19 ἀδικήματι Β Va 20 πεφευγμένας BVa 22 μὴ δὲ HBVaViMaCl
footnote 7 cf. ad t. V 556,9 | [Plut.] vit. X or. Hyper. p. 849 D. Athen. XIII p. 590 c. Choric. Spart. § 31 Arch. Jahrb. IX p. 180,7 cum nota mea | Xen. comm. III 11, 1. Ael. var. hist. XIII 31. Athen. V p. 220 e; XIII p. 588 d; 574 e; XII p. 535 c 9 Paus. Χ 15, 1. Athen. XIII p. 591 b. Ael. var. hist. IX 32 15 Thuc. II 37,1 3 τοῖς ζῆν ἐθέλουσιν αὐτοὺς VaMViMaCl scriptura in Cr incerta 4 ἀκύρως inserui ut ἀκύρους inserendum censuit Re om libri edd | ἔχοντας post δεικνύναι Β ViMaCl et inser Fa 2 om HM edd scriptura in Cr non perspicua transposui δεικνύναι edd cf. p. 127, 5 5 δὲ inser Ma 2 ὁ Vi 6 ἔφη Vi 7 καὶ ante τὴν(1) H scriptura in Cr incerta 8 Φρύνην scripsi e Cr sed ν(2) parum certum, HBVaM φρύνιν Ma edd φρύννιν ViCl 10 παύσοιντο HVaMViMa sed in hoc ο(1) in α corr m3, Cl scriptura in Cr parum certa | θαυμάζοντες Cl sed ες in ras m 2 11 καὶ inser Ma 2 12 μαθὼν CrH | προ- φέρειν CrH προσφέρεις Va sed σ eras, Μ 13 νόμοις Vi | ἑτέρους post νόμους Β Va | ἧς vel ὧν scribendum coni Gasda καὶ inserui om libri edd 15 πολιτείαν ζῆν M | aut ἔχοντες et οἰκοῦσιν aut ἔχουσι et οἷς ἑπόμενοι (aut simile quid) οἰκοῦσι scribendum coni Re | καθ' οὓς inserui om libri edd R IV 445
footnote 11 ἐπίλογος M 1 οἷόν τε HViMaCl scriptura in Cr incerta 3 περὶ Va 4 μὴ δὲ HBVaMViMaCl Ferr | voce μέχρι parum certa des Cr fol 8 r 6 προτέρων ViCl sed in hoc in πρότερον corr m 2 9 τῇ σῇ διανοίᾳ παραδείγμασι Η 11 ἡμῖν MaCl | μέ- λει Va sed ει in ras m 2 μέλλει ἁ 12 μέλειν Va sed λ e λλ m 2 μέλει Β μέλλειν Cl | δὲ om Vi inser Cl 2 | καὶ om BVaM 13 οὕτος ἐκτίσει Η 14 μὴ δὲ HBVaMViMaCl Ferr 17 θεοὶ Ma sed οὶ ex ὸν corr m 3 om BVaM | οἱ om Η Vi inser Ma 3 | ἐπινεύσαιεν scripsi ἐπινεύσοιτε libri edd ἐπινεὐσαιτε coni Gasda 18 τοῦτον om Vi inser Ma 3 | ἀσε- βείᾳ scripsi ex HMViMaCl ut coni Re et Cobetus Coll 294 εὐσεβείᾳ BVa edd 19 οὐδὲν — 491,1 ἔχουσα omissa parti- cula γὰρ citat Macarius fol 81 r | δρῶσιν Β
marginal R IV 446
footnote 16 Thuc. I 13, 14. II. β 570 1 τοῦ ποθεῖν Macar sed γρ τοῦ ποθουμένου in marg 2 τοιαῦτα om Re 3 πρότερον ante διαλέγεσθαι BMa sed in hoc inser m 3, edd sed om γρ in marg Mor delevi | ἐστιν ἡ scripsi e BVaM ἐστι HViMaCl edd | ὥρᾳ σώματος λάμπει re- posui e libris λάμπει ὥρᾳ σώματος edd 5 προσδέχεται scripsi ex HViMa sed in hoc εἰς supra πρόσ’ m 3, Cl et γρ in marg Mor εἰσδέχεται BVaM edd | ἀπατῶντας Va sed v post α(2) inser m 2, Μ 6 τὸ Cl sed in τοῦ corr m 2 7 δουλεύειν — 8 ἀπούσῃ praemisso κείμενον in marg Ma om ViCl | χηρεύσομεν scripsi χηρεύομεν libri edd 8 ἀπούσῃ Μ sed γρ΄ σπουδὴ suprascr m 2 σπουδὴ HBVaMa sed in hoc ἀπούσῃ suprascr m 3, et γρ in marg Mor | κεχαρισμένος scripsi auctore Re κεχαρισμένον libri ἤτοι ἀποδεκτὸν suprascr Μa 3) edd 9 ἐμαυτῶ τὸ πᾶν Β 11 τἀς πολέω BVa 12 εὕρω vel ἔχω coni Gasda | σχῶ scripsi ἔξω Va ’ in' corr, ViCl sed in hoc' in' corr m 2 ἕξω ΗΒVaM Ma edd | πειθομένας Β 13 ἔσομαι πάντων Μ 14 τῆς οmVa | εὐκλείας Ma sed εὑ in ras m 3 | αὐτ(??) Ma αὐτῶν Cl 15 ἐντεῦθεν Va sed αῦ supra ευ m 2, Μ 16 πολύχρυσον Ma sed γρ πολυχρόνιον in marg m 2
footnote 8 Isocr p. 39 d et 71 d 15 Thuc. I 13, 3 5 διανοηθεὶς Va sed εὶς ex ὴς, ut videtur, corr m 2 6 ὤκνησε scripsi e Μ sed ὤ et ε in ras m 2 et supra η ras accentus, et Ma sed ώ ex ὀ et ησε ex εῖ(?) corr m 3 ὀκνήσω HBVaVi ὀκνεῖ Cl sed νεῖ in ras m 2, edd sed γρ ὀκνήσω in marg Mor | καὶ ante πρὸς Ma sed del, Cl sed in ras m 2 7 αὐτοῦ libri edd 8 δὲ inserui coll Isocr. ll. ll. om libri edd 9 ἡμῖν BVaM | ἀποψηφίσασθε BVaM sed in hoc σ in ζ corr 10 δόξετε Ma sed ε(1) ex η corr m 3 | σωφροσύνης Va sed ης in ras m 2 12 ἀνακόψετε scripsi ἀνακόψατε libri edd τὰ inserui e libris om edd 16 ἡμᾶς scripsi e Vi ὑμᾶς HBVaMMaCl edd | ἥκουσι scripsi ἥξουσι libri edd 18 περὶ reposui e libris εἰς τοὺς edd sed γρ πρὸς in marg Mor | ἀξιοῦν τοσαύτης HViMaCl 19 προιέμενον ViMa sed in hoc ἔμενον in εμένην corr m 3, Cl
