@node
@author=Libanius
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Richard Foerster
@filename=tlg2200.tlg00522.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane
@publicationStmt=University of Leipzig, tlg2200.tlg00522.opp-grc1.xml.
@respStmt=Gregory R. Crane, Editor-in-Chief, Perseus Digital Library, Digital Divide Data, Corrected and encoded the text, Matt Munson, Project Manager (University of Leipzig), Annette Geßner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor, Greta Franzini, Project Manager (University of Leipzig), 2013-2014, Frederik Baumgardt, Technical Manager (University of Leipzig), 2013-2015, Simona Stoyanova, Project Manager (University of Leipzig), 2015, Project Assistant (University of Leipzig), 2013-2014
@sourceDesc=Richardus Foerster, Richard Foerster, Libanius, Declamationes XIII-XXXX, B.G. Teubner, Leipzig, 1911, 6, Internet Archive.
@sponsor=University of Leipzig
@title=Declamatio 22
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:58:04Z

3932	marginal R IV 253
footnote 1 ἐκδοθεὶς φιλίππω δημοσθένης ἀφεθεὶς καὶ μὴ πολιτευό- μενος κρίνεται δημοσίᾳ Lau ἐζήτησεν MaCI | καὶ ante κατέ- φυγεν Wolf edd delevi 2 τοῦ ante ἐλέου WolfVaVi edd  delevi coll p. 353,16; 362,15 et Macario Chrys. p. —8 6 Δημοσθένης om CrHVCVaMaLau δημοσθένης ἡ μελέτη  BVi καὶ ὁ λόγος Wolf μελέτη CI μελέτη δευτέρα Ferr  7 πεπονθότων scripsi e CrViMaCl πεπονθὼς VCWolfVa sed  in hoc ὼς in ras m 2, BLau edd 8 παθὼν, ante ἐκδοθεὶς Ma  CI Ι ὑπὸ τούτων om MaCI | πάντων Lau | ὑφ’ inser Lau 2
marginal R IV 254
footnote 1 μὲν inserui e CrHVaBVi om VWolfMaClLau edd  2 οὐ Ma 3 δεινότατον Lau Ι ἂν inserui cum Gasda om  libri edd 4 καταλύσαι Η | a δὲ ἔχων Va sed γρ δἔχον in  m 2 Ι ἀφεστάναι Va sed ἁ ex ἑ corr m 2 5 ἐμοί δ’ Ma sed  ἐμοί τε suprascr m 2, Cl 6 καὶ V sed δὲ in marg m 2 | τὸν  ante τοῦ inser Ma Ι ἑνὸς Va sed ἑ in ras m 2 7 παρῆλθον  V sed ον in ras m 2 | ὃ ViVa sed in hoc in ὧ corr m 2, et  praeferendum censet Gasda | πεισθέντες Va sed σθέντες in ras  m 2 8 μεγάλως VaB | voce δόξαν des Cr fol. 39 v, quae sequun- tur in fol. 39 r usque ad p. 349, 15 ἐλλήνων abrasa iam non legi  possunt | μὴ om Vi 9 ἣ in ras Va 2 sed ὃ suprascr m 3 ὃ Vi  ἤ Wolf Ferr Ι post βέβαιον ras —15 litt V 10 τῆ πόλει  τηρήσετε Mor | ἀναιρῆσαι Va sed γρ ἀνηρῆσθαι in marg m 2,  BVi 11 ἐμὲ in ras V 2 13 ἡμᾶς Vi 14 comma post  πεποίησθε libri edd delevi 15 αἰδώ cum ras 1 litt V Ι comma  inserui ex HViMaCl om reliqui libri edd 17 ἂν οὐ καλῶς]  οὐκ ἂν ἔχον Va sed ν(2) in ras m 2 et γρ οὐκ ἂν καλῶς ἔχον in  marg m 3, οὐκ ἂν οὐ καλῶς Β οὐκ ἂν καλῶς Vi ἂν ἀκαλῶς  Wolf Ι ἔχων Vi 18 τὸ in τῶ corr Va2
footnote 12 Dem. p. 762, 17 1 τουτὶ μὲν C sed τὶ et ὲ in ras f τοῦτο μὲν MaCl sed  in hoc ο in ras m 2 τῆς τιμῆς Va sed τουτὶ μὲν in marg m 2,  BVi τοῦ τιμᾶν Η 3 τὰς ante χάριτας MaClLau Ι ἀνθῶν  Va | ὅτι Vi 4 ἐπεξουσίας Vi | δεῖ coni Gasda 5 τούτων  Lau 6 δεδήλωκα scripsi auctore Gasda δέδωκα HVCWolf  edd ἔδωκα VaBMaClLau ἔδωκε Vi | καὶ ante παρ’ WolfVi  edd delevi | προτεθῆναι scripsi auctore Re προστεθῆνοι  προστεθεῖν Lau) libri edd 6 ἐρῶ οὖν vel simile ante οὐχ  excidisse censet Re 7 ἀναβὰς V sed νῦν ἄνω suprascr m 2 |  μέν μου V sed ν μου in ras m 2, C sed υ ex ι corr f μέντοι Η  μὲν οὐ Wolf Ferr 8 ἐνηνοχὼς Ma 9 ὑπομένω HWolf  MaCl sed in hoc μένω e μενῶ corr m 2 10 ἄμεινον Lau  11 ἀνελόντα Va sed όντα in ras m 2 13 ἐν ἀθηναίοις ταῦτα  Lau 14 καὶ — Δημοσθένης delenda censet Gasda | καίτοι  ταῦτα Wolf | ῥήματα ἀφήσει VaBVi φήσει Lau ἀφήσω coni  Re 15 διατί HViMaCl | ὅτι om MaCl Ι οὐ inser Va 2  17 μεμνῆσθαι — 349, 1 μηδὲ om Wolf Ferr | τῶν — 349, 1 με- μνῆσθαι inser Va3 a Ι μὴ δὲ HBViMa
marginal R IV 255
footnote 6 cf. p. 279, 18. Dem. p. 1233, 25 6 sq. cf. t. IV 299, 1 R.  Dem. Phil. III p. 143, 13 10 Dem. p. 142, 14 1 μηδὲ Va Mor μὴ HVCBViMaClLau 2 ἕτεροι ΗVC  sed in hoc in ἑτέρους corr f, VaBVi ἑτέρου Wolf Ferr Ι δὲ(1)  om HVCVaBViMaClLau et γρ in marg Mor 3 κἀκείνου V  ποιῆσαι VaVi 4 ἐκλιπεῖν Lau et γρ in marg Va 2 5 καὶ  inser Va 7 καὶ ante τὴν VaB 8 ὑμῖν Va sed 00 supra ι  m 2 ἡμῖν V | τοῦτο Lau Ι οὐχήκιστα Vi Ι τῇ πόλει τὸ μέρος Ma  CI Ι τὸ μέρος om BVi inser Va 2 9 κατημελημένον scripsi  auctore Sinteni ἠμελημένον libri ἠμελημένων Lau ἠμεληθέν  Vi ἠδικημένον V) edd Ι τὸν V sed ο in ras m 2 om Vi  10 βωμὸν V sed o in ras m 2 | τουτωνὶ V Ι οὐδὲ πώποτε HVC  VaBViMaClLau edd 11 ἐπιτιμήσας Ma sed γρ ἐπιθυμήσας  in marg m 2 Ι οὐδὲν τοιοῦτον Lau 12 τἆλλα Η 14 ὑπὲρ  in πέρι corr V 15 voce προνοίας inc Cr fol. 46 v | πεποιημέ- νοι προνοίας MaCl πεποιημένοι V sed οι in ras m 2 Ι τοῦτον  scripsi e CrHVa sed in hoc et ον in ras m 2 Lau τούτων  VCBViMaCl edd τούτοων Wolf 17 ἐν inser Va 2 | νικᾶν  δύνασθαι Lau
footnote 3 cf. p. 339 not. 1 8 cf. p. 270, 15; 327, 15 2 τὴν γνώμην scripsi e CrHVVaBViMaClLau κῇ γνώμῃ  CWolf edd sed γρ τὴν γνώμην in marg Mor 5 παρ’ ὑμῶν  om HVC post παρ’ ὑμῶν pauca in Cr folio ν usque ad p. 352, 5  ναῦς dispici possunt 6 τὸν in ras V 2 Ι ἡμῶν V | ἀντιτεταγμένον  V sed νον in ras m 2 ἀντεταγμένον ClLau 7 αὐτον Va sed  ante ν ras αὐτῶν ViLau | ἐκκεκρουκότι Va sed ι in α corr m 2,  Β 9 τὸ VaBVi | οὖν om Vi | ἡμᾶς Vi 10 „malim θαυ- μαστὸν“ Re | ὡς del VaCl ὣς C Ι οὕτω Lau sed ου in ο corr m 2 11 ἐσθείην Lau Ι αὐτῶν Ma sed ης supra ων m 2 αὐτῆς B  Vi αὐτοῖς V | δήπου inser Ma 2 om CI Ι τοῦτό scripsi e MaCl  Lau cum Iacobsio Rev 4 τούτου HVCWolfVaBVi edd  12 γέγονε Β 13 ἐμὲ inserui ante μόνον, ante δηλοῦντος Gasda  om libri edd 14 ὧς οἱ] ὅσοι V | οἵδ’ Vi Ι δὲ MaCl  15 ὁ — 16 Μακεδόσιν in marg Va 2 16 μακεδόσι Wolf Ferr  Mor μακεδόνας Β | δὴ scripsi e MaClLau δὲ HVCWolfVa  BVi edd 17 τὸν Ma sed ν add m2
footnote 17 sq. cf. p. 330,6; t. II 134, 11. Dem. cor. p. 258, 4 sq. 2 δὴ om MaCl Ferr Mor | διανοεῖ V sed ει in η corr m 2  διανοεῖν Lau διανοῇ; Re | δρᾶν Va sed ἐρεῖν in marg  m 3 | signum interrogationis posui colon libri edd Ι λόγω μὲν  ἀφθόνω V 3 μόνου τούτου Va sed ου bis in ras m 2 Ι τοῦ  inser Va 2 4 ὠς om Β Ι καὶ om Lau Ι δικαιότατα scripsi  auctore Re δίκαια libri edd 5 ὦ ante ἀθηναῖοι MaCl Ι οἱ  V Ι ἴσται V sed ι(1) in ras m 1, ε vero supra αι m 2 6 ποτὲ om  V Ι τῇδε reposui e CrWolfLau sed in hoc δε add m 2 τῇδε  HVCVaBViMaCl om edd 7 ἔχοι Ferr Mor | καθὸ HVC  WolfMa Ι μέτοικος ἤ ξένος VaBVi 9 καλῶν V 10 δ’  οὖν scripsi ex HVVaBViMaClLau coll t. V 539, 1 δὲ CWolf  edd scriptura in Cr parum certa 13 εἰλήφατε MaCI  14 μὴ ante προέσθαι Β et in marg inser Va 2 Ι προέσθαι Va  sed σθ in ras m 2 15 μὴ δὲ HWolfBViMaCI 18 μέν τι  Lau Ι ἀλίαρτον Va sed αλ in ras m 2 ἀνίαρτον Vi
footnote 1 Dem. p. 258, 10 et 11. Xen. Ηell. VII 4, 4 3 cf. p. 330, 6 4 sq. cf. t. II 134, 14 sq. 13 cf. t. I 269, 16 1 Κορκυραίων Lau sed κυρ in ras m 2 | ἡμῖν MaCI  2 ἡμετέροις ViMaClLau Ι ἐσώζοντο κινδύνοις VaBViMaCl  3 τούτων MaCI 5 τριάκοντα τυράννοις VaBViMaCl | voce  ἀφηιρέθητε inc Cr fol. 46 r 6 δὲ τείχη Lau Ι δὲ VaVi | τού- τοις Lau 7 βοηθεῖν V sed ἐλεεῖν suprascr m 2 8 ἐξετάζειν  in marg Va2 9 (??)ἰδεῖσθε V ᾐδεῖσθε Lau Mor Re 11 καὶ  inserui auctore Re om libri edd | πολλῷ om Vi | δικαιοτέρως  Vi | ἄν om Ma 13 τοῦτο εἵνεκα MaCl | ἕνεκα VaBVi  16 τὸ om Lau τὲ Ferr 18 κωλυθέντες Va sed ω in ras m 2  καταλυθέντες Vi 19 πέμψαι Lau Ι μὴ δ’ HBViMaCl |  ὑπολείπητε BLau | μηδὲ μίαν CrCI
marginal R IV 257
footnote 1 τῷ om Lau | τῶ δήμω Lau 2 μακεδόνος Lau  3 ἀνάξιον Va sed ἄνα in ras m 2 | ἐμαυτῶ χρῆμα Ma 4 τοῖς  ante ἱεροῖς VaBViLau ἱεροῖς] αὐτοῖς in ras ὒ 7 περιειστή- κεισαν Va περιεστήκεσαν ΒCI 8 ὦ ἀθηναῖοι ante οἴῳ Lau 9 ἔμελλον Va sed ὂν in ras m 2 ἔμελλε Vi 10 δὴ Οἶ’ Ι  μὴ δὲ HViMaCl | διαφεύξασυαι Va | τίς CrHViMaCl 12 συν- είποντο Ma sed in συνεῖπον corr m 2 Cl | δὴ om Vi inser Va 2 13 μακεδόσιν Cr | ταὐτά Va sed ras supra ὒ ταῦτά reliqui  libri Mor Re 14 ὑφῃρεῖτο Lau | ἤγγελλε scripsi e CrHCVa  Ma ἤγγειλε VVi ἤγγελε WolfClLau edd 15 πρὸς VaBVi  | καιαπεφευγόια εἰς τὸν τοῦ ἐλέου MaCl 16 τὸν om Lau 17 γενναῖον in ras ὒ 18 ἱκεσίαν V 19 παρὰ Lau et  γρ in marg Mor 21 ἐκ Lau et γρ in marg Mor
footnote 8 Paus. I 8,5 9 cf. ad p. 284,6 18 cf. p. 235,16;  t. IV 315, 8 R 1 ἐδάκρυσαν Lau 2 εἶτα MaCl Ι ἀνάστ’ CrHVCWolfVa  Vi Ferr 3 ὦ om Lau 4 τουτὶ Β | ἔδοξαν V 5 ἐπ  ἐμαυτοῦ scripsi e Va coll II. ἡ 195 ἐπ’ ἐμαυτὸν VVi ὐπ’  ἐμαυτὸν CrHCWolfMaCl edd ὑπ᾿ ἐμαυτοῦ Β οὐκ ἐμαυτὸν Lau  στένων καὶ μεμφόμενος πρὸς ἐμαυτὸν coni Re Ι πολλὰ om Cl  inser Μa 2 ἀλλὰ Lau | τὸν inser Ma 2 | οὐκέτ’ WolfMaCl  6 ἔχοντα Ma sed ἔχ in ras σθένοντα Cl | περιβάλλοντες VLau 7 δεσμοῖς Va sed οἶς in ras m 2 δεσμοὺς V | ἐγκεκαλυμμένον]  οὐ κεκαλυμμένον Cr. 12 πεπιστευμένον Lau Ι θεσπ ἰῶν cum  ras 1—2 α litt V θεσπιῶν Va sed ἴων in ρωτων corr et  in marg scr m 2, Lau θεσπειῶν BVi θεσπρωτῶν Ma sed πρωτ  in ras θεσπεσιεῶν Cl 13 πλαταιῶν CrHVVaBViMaCl  14 τἄλλα MaClLau Ι τὰ om Lau 16 περὶ? 17 δὲ om Vi |  τοιοῦτον καὶ scripsi e CrHV sed in hoc inser m 2, VaViMaCl  καὶ τοιοῦτον CWolfLau edd τοιοῦτον Β Ι παρὰ inser V 2  περὶ HWolfVi Ferr scriptura in Cr parum certa
marginal R IV 258
footnote 1 Dem. fals. leg. p. 358,27 10 cf. ad p. 224,9  13 Ephipp. Peltast. com. III 336, 1 M (= II 1 p. 261 fr. 19 K) 1 ἃς Wolf Ferr 2 ἐλύπουν Va sed οὑν inser m 2  3 μὲν V | καὶ inser Va 2 4 ἀκηκοότες κακῶς VaBVi Ι ἢν C  sed in ἡ corr m 2, Mor sed γρ ᾖ in marg ἦς Lau sed in ἧς  corr m 2 scriptura in Cr parum certa 6 δὲ MaCl 8 ἀν- δρίας Lau Ι οὐκέθ’ Va sed θ’ in ras m 2 οὐκ ἔθ’ Vi οὐκ ἔσθ’  Cl 9 ἐπειδὴ δὲ Ma | ἥκομεν Ma 10 ἤκουον V sed ὗον  in ras m 2 inser Ma 2 ἤκουσα Lau Mor sed in hoc γρ ἤκουον  in marg, Re Ι πεζεταίρων scripsi e CrH πεζ(??)ρων Ma πεζαιτέ- ρων VCWolfLau edd ταίρων praevia ras 3 litt Β ἐξεταίρων  Va ἐξ ἑτέρων Οἶ’ ἐξ ἑταίρων Vi 11 γρ δὲ ante καὶ in marg  Mor 12 διηγήσαιτο Ma sed γρ διηγήσασθαι δύναιτο in marg  m 2, Cl 13 ἐπεὶ Lau | σεμνῶς σεμνὸς Β σεμνὸς om Ferr Re  σεμνῶς om VaLau Ι κάθητο VaLau 14 καὶ om Lau  15 τῶν om Re | τοὺς] δεσμοὺς Sintenis 16 μοι MaCI  17 εἰς Ma sed ὧς suprascr m 2 ὡς VaBLau | αὐτὸν libri edd  Ι καλέσας V κελεῦσαι Ferr Ι δεινὸν om VaB
footnote 14 sq. cf. t. V 556, 4 sq. 15 cf. t. V 500, 19 16 cf.  p. 217, 14 18 cf. t. II 305, 9 1 αὐτοῦ et αὐτὸν libri edd | δεινὸν ante τοσαῦτα VaB  2 ἐκπέμπειν Lau 4 οὐδὲ Vi | κακοῦ Ma 6 πᾶς — 8 φιλεῖ  praemissis verbis τῆς μελέτης ἐν ᾖ δημοσθένης γράφει παρ’  ἀθηναίους ἀνελεῖν τὸν ἐλέου βωμόν citat Macarius fol. 82 v Ι ὦ  Φίλιππε om Macar ὦ om VaBVi 7 αὐτοῦ scripsi e C  αὐτοῦ reliqui libri edd ἑαυτοῦ Macar 11 φρονεῖν Lau |  γε MaCl | ἂν inser Ma 2 12 φρουροῦσαν Wolf φρουροῦσα  Lau 14 οὐκ ante οἶσθα Vi 15 τοὺς πλαταιέας Lau  16 μυλάκην WolfLau Ι τῶ βασιλεῖ Va sed γρ ὦ βασιλεῦ in  marg m 2, BLau βασιλεῦ Vi 17 μυρί’ WolfMa sed in hoc  ’ in ἁ corr m 2, Οἶ’ μυρίαν Ferr | δ’ ἂν V ἂν om Ferr Ι βασι- λεῦ Β 18 ὢν inser Va 2 | &lt;καλλίστων&gt; α διηγήσεων &lt;ὧν  νος&gt; α coni Re
marginal R IV 259
footnote 4 cf. p. 277,12 sq 7 cf. p. 277,12 sq. 10 cf. ad  p. 270, 10 16 cf. p. 320, 2; t. II 88, 1 1 χρῆμα Vi | βῆμα &lt;λαμπρότατον α διὰ&gt; α σεμνῶν coni Re  scripsi μεστὸν VaB omreliqui libri edd Ι καλῶν καὶ σεμνῶν CI  | σεμνὸν καὶ σεμνῶν Μα sed σεμνὸν inser m 2 Ι καῖ inser V 2 2 ὀμο- λογεῖν Wolf Ferr 3 δέ om Lau 5 ἐπῆγον Lau | καὶ ante  εἷπον MaCI 6 ἐξήτασα Va sed ἐζήτησα in marg m 2 ἐζήτησα  HVCWolfViMaCl Ferr scriptura in Cr parum certa 8 πελο- πόνησος VC 9 μετ’ αὐτῆς Ma 11 τὸ om MaCI 13 ὅπη  Va 15 πόλεσιν Cr 16 οἰκίαν HVCVaBViMaClLau Mor  sed in hoc γρ οἰκείαν in marg scriptura in Cr parum certa 19 ἡμέροις Va sed καὶ τοῖς ἐλευθέροις suprascr m 2, Mor  sed γρ ἐλευθέροις in marg ἡμετέροις Lau ἐλευθέροις CrH VC  WolfMa sed in hoc ἡμέροις καὶ τοῖς in marg praepos m 2, Cl Ferr
marginal R IV 260
footnote 10 sq. cf. IV 36, 5; t. IV 320, 11 R. Dem. fals. leg. § 194 sq.  p. 401, 25 sq. 18 Thuc. I 129, 3. Plat. rep. I p. 345 A 2 οὖν ante ἀκριβὲς Lau 3 τεκμαιρομένων Vi 4 ἂν  post πολλὰ Β | ὦ ἀθηναῖοι πολλὰ ViMaCl 8 ἐδίωξεν scripsi  auctoribus lacobsio Lect 103 Achill Tat 889 Rev 4 et Weiskio  hyp II 46 ἔδειξεν libri edd naut λήψεσθαι ἔδοξεν aut ἐθήρασεν“  Re 8 ἐξῄτησε in marg inser Μα 2 om Οἶ’ ἐζήτησε CVaB  Lau Re scriptura in Cr parum certa 9 τῶν] τοῦ ΗC scrip- tura in Cr parum certa | „ζητῶν abesse ” Re 10 αὐτὸν  om HVCWolf Ferr scriptura in Cr parum certa 11 τῷ om  Ferr 12 πατρὸς — ἀπεκτονότος in ras V 2 Ι τῶν κορῶν om  HCWolfVa sed in hoc τὴν κορῶν in marg m 2, Β Ferr | ἀπο- κταινόντος Η ἀποκτανόντος CWolf Ferr 14 τοιαῦτα scripsi  e BViLau ταῦτα HVCWolfVaMaCl edd 16 ὅπου MaCl 18 μοι om CrHVC Ferr
footnote 2 Soph. El. 1311. Plat. Menex. p. 245 D 2 ἠπειγόμην Va sed ἡ in ras m 2 Ι verba οὕτως — πατρίδος  ad comoediae Atticae versum οὕτως ἔρως ἰσχυρὸς ἐντέτηκέ μοι  τῆς πατρίδος redire censuit Th. Kockius Fr. com. Att. III  p. 489 n. 431 qua de re cf. quae dixi in Addendis et Corri- gendis ad t. I p. 79, 8 | ἐντέτοκε V 3 οὐδ’ ἡ scripsi auctore  Iacobsio Add 368 Lect 103 Rev 4 οὐδὲ libri edd 5 παρὰ  om Lau ὑπὸ MaCl Ι καὶ ante μὴ δὲ Vi μὴ δὲ HBViMaCl  Lau 6 ἀκούειν πικρῶν MaCl πικρῶν C sed ’π’ in ras f  μικρῶν HWolf | καθ’ in ras Lau 2 | ὑμῶν CMa sed ὒ in ras ὁ  Ma 2 7 ἦσαν(2)] ἦπερ Re | τῇ ἐκδόσει et τοῖς Ἀθηναίοις et  τοῖς πολίταις scripsi τὴν ἔκδοσιν et τοὺς Ἀθηναίους et τοὺς  πολίτας libri edd 8 τῇ ἀφέσει et τῷ Φιλίππῳ et τῷ ἐχθρῷ  coni Gasda 11 ἑκστέρῳ Mor sed γρ ἑτέρῳ in marg ἐκατέρων  VaBViMaCl | γίγνεσθαι ViLau γενέσθαι Ma 12 ἐντεύξομαι  scripsi e VMaClLau ἐντεύξωμαι HWolfVaB Vi edd scriptura  in Cr parum perspicua 13 μεμνημένοις Lau sed ἲς in ras m 2 |  εἰς ὅσον] ὧς MaCl | οἶόν om Lau οἷον Β οἷός Re Ι τε Vi  14 ἥκων V sed ὢν in ras m 2, Mor sed γρ ἦγον in marg ἥκω  BLau ἧκον HCWolf ἤκουον Vi | ἐν] ἐνδε C ἐν δὲ Wolf Ferr  Ι πολιτεύομαι ὅπερ ἔφην Ma 15 τηνάλως HCWolfViMaCl  scriptura in Cr parum certa cf. ad t. V 272, 13
marginal R IV 261
footnote 14 cf. p. 245, 12; t. II 526, 13; V 353, 3 1 φήσει VaB Ι τις post φησί libri edd delevi 2 πά- τριον Va sed τίμιον in marg m 2, BLau 3 ἐκβάλλειν V sed  λ(1) inser ἐκβάλλειν Va Re 4 ὁ τοῦτό εἰμι MaCl Ι πονῶν  Lau Ι ὦ inserui e ViMaCl om reliqni libri edd | ἀθηναίοις  V Ι τιμὴν] τὴν νῦν Vi 5 ὁ τῇ] ὅτι Wolf | φυγῇ ΜαCI  6 ταῦτ’ MaCI | οὐ in ras V 2 9 ἀπέρριπτο Vi ἔρριπται  MaCl 10 εἶχεν scripsi ex HVCWolfBMaCI ἔσχεν VaLau  edd ἔσχον Vi scriptura in Cr parum certa Ι ἐξελέσθαι om Ma 11 τοῦ βωμοῦ τιμὴ VaBLau | τὸ ante τὸν VaBLau et inser  C 2 13 ἔστηκεν VCVaMa edd scriptura in Cr parum certa |  πέπτωκε Lau 17 βωμὸν Va Ι καὶ ante τὰ HVCLau Mor Re  scriptura in Cr parum certa delevi 18 τόπων Va sed γρ'  τύπων in marg m 2, BVi et coni lacobs Lect 103 Ι τούτων ante  ταῖς libri edd delevi cum Gasda τούτω, ταῖς coni Re τόπων  αἰδεσιμώτερα τούτων (= venerabUiora quam alia loca quae vi- detis) Iacobs Lect 103 Rev 4
footnote 6 cf. t. V 24, 14 7 Her. VI 105 9 cf. t. H 37, 17 1 οὕτω Ma sed πω supra τὼ m2, Cl | λίθων om C  2 ἅψασθαι Lau 3 του coni Re | τοῦτο Vi 4 εἰς om Πα  | ἐμοῦ MaCl 5 μὴ δ’ HViMaCl 6 παναθηναἰοις Vi  Mor sed in hoc γρ παρ’ Ἀθηναίοις in marg παρ’ ἀθηναίοις  HVCWolfVaB MaClLau Ferr scriptura in Cr parum certa Ι  ὁ διόνυσος Ma sed γρ δημήτηρ in marg m 2, Cl 7 πᾶν H  VMaLau Ι θεὸς VaB 8 νόμοις Ma 9 καὶ ante τῶν(1)  MaCl Ι ἑστηκόσιν ante ἁγιστειῶν HVVaBViMaCl 11 ἔστιν  Ἐλέῳ scripsi εἰς τὸν ἔλεον libri sed scriptura in Cr parum  certa, edd sed εἰς τὸν (subaudi ναὸν) Ἐλέου coni Re Ι ἐκεῖ Vi 12 δ’ ViMaCl | οὐκ ἔτ’ scripsi e CrHLau οὐκέτ’ VVaB  ViMaCl οὐκ CWolf edd 13 τις MaCI Ι ἀφελόμενος MaCl  ἀφελόμενον Wolf 14 αὐτὸν V sed ’ν in ras m 2 αὐτοῖς  CrHCWolf sed in hoc οἶς ex ὂν corr, Ferr | ἀξιοῖ CrHCViMa  ἀξιεῖ Lau ἀξιοῖς CI | καλεῖν στρατηγὸν VaBLau 16 φασι  κερδανοῦμεν Vi 17 διαφεύξεσθε(??)ι Va | νῦν VaBMaCl | κατη- γορίας Mor sed γρ προσηγορίας in marg
marginal RIV 262
footnote 15 Xen. comm. II 1, 4; III 11, 7 1 θεὸν μὲν Vi 2 δὲ om Wolf Ferr 3 αὐτοῖς HVCVi  MaClLau Ferr 4 et 6 τῷ CrHVCWolf Ferr et γρ in marg  Mor Ι γὰρ om Vi Ι ὅστις ViLau 5 μὴ δὲ HBViMaClLau  6 αἰτίας V | ἅ scripsi e Β ut coni Re εἴ CrHVCWolfVaViMa  Cl sed in hoc in ἅ corr m 4, edd ἄν Lau Ι καὶ ante πρὸς Lau 7 ταῦτ’ VaB 8 μὴ om Vi 9 τὸν βωμὸν scripsi e CrH  VCVaBViMaClLau βωμῷ Wolf edd sed γρ τὸν βωμὸν in marg  ὂν  Mor τούς βωμοὺς coni Re Ι μὴ δ’ HBVi μὴ δὲ MaCl | βωμῶν  Ma βωμὸν V sed ῶ supra ὁ m 2 10 νομίζειν Vi | ὀκνεῖν  om Lau 11 ἡμᾶς MaClLau 12 γευόμενα scripsi e MaCl  γινόμενα BVi γιγνόμενα HVCWolfVaLau edd Ι τούτους τί  scripsi ex HVVaBViMaClLau τί τούτους CWolfedd 14 καὶ  — ἐνεδρεύουσι om Lau 15 θηράτρων scripsi coll Xen. l. l.  auctore Re θηρατῶν libri edd
footnote 5 sq. cf. p. 329, 9 sq. 7 cf. p. 398, 6. Dem. cor. p. 316, 4 10 cf. ad p. 258, 3 15 cf. t. V 257, 1 1 κερδανοῦσιν Lau σωτηρίαν ante κερδανοῦσι inserendum  coni Re | πατέρα Ma 2 εὑρήσουσι εὑρήσουσιν Lau) ἀξιόχρεων  VaBLau | ὐπάρχη VaB ὑπάρξει Lau 6 ὀρθῶς Vi | καὶ(1) —  7 ἐθελοντὴς om Wolf Ferr 7 ὁ ante λυόμενος CWolfLau  edd delevi | ὁ ante θυγατέρας Wolf edd delevi 8 ἐλέου  scripsi ex HVaBViMaCl ἐλέους VCWolfLau edd scriptura  in Cr parum certa cf. t. V 424, 8 | μὴ VaBLau 10 σιτοπομ- πίας scripsi ex HCWolfVaBMaClLau σιτοπομπείας VVi edd 11 α ὁ στεφανούμενος om Ferr Mor 12 ἅτινι Ma sed in  τίνι corr m 2, CI 13 ἃ Ma sed ὧν suprascr m 2 ὧν VaB  14 δύναται Ma 15 ἐκπληξίας Ma sed k in μ corr m 2, Cl 16 voce γὰρ des H | ἦν inserui e CrVCVaBViMaCl post  ἀνάγκη Lau om Wolf edd | μὴ scripsi e CrVCVaBViMaCl  Lau, ut coni Re μηδὲ Wolf edd 17 ἂν inserui om libri  edd 18 ἡμῖν Οἶ’
marginal RIV 263
footnote 3 cf. ad p. 278, 15. Her. IX 27, 2. Philostr. ep. 39. Longin.  de invent. 2 ed. Walz rhet. t. IX 550,25 5 cf. ad p. 278,14  9 cf. p. 278, 14 13 Thuc. I 104 Ι Thuc. II 85 14 Thuc.  I 111 1 ἤπερ CI | ἠβουλόμην Ma 2 τὴν Cl | τὸν ὑπὲρ om Ma  Ι ὑπὲρ τῶν om CI 3 πελοπόνησον CWolfClLau | ὅλην ex  ὅλἣν corr V et ὅθεν in marg m 2 ὅθεν Va sed θὲν in ras m 2,  Vi | ἣν inserui e Lau ut coni Re om reliqui libri sed ἣν  ὅλην in marg V 2, edd 4 ὅσα CWolfVaViMaCl Ferr | πρᾶγμα  Lau 5 ἡρακλῆς CWolf Ferr Ι τῶν ViLau 7 νίκην V | εἰ  καὶ Lau Ι σεμνὸν C sed γρ σεμνὸς in marg, Wolf sed γρ  σεμνὸς in marg, VaBViMaClLau 8 ἡρακλείδης C sed γρ  ἡρακλῆς in marg, V sed είδ eras et ~ supra η, Va sed εἴδῃς in  ῆς corr m 2, ViMa sed in hoc ὴς supra εἴδῃς m 2, CI | περὶ in  ras Va 2 Ι ἡμᾶς Ma 9 οὔτε μικρὸν om Ferr Ι πεπόνητο Va Ι  οὔθ’ Lau 10 οὔτε Vi | ταλαὸς VCWolf Ι ἦσαν om Vi  11 ταῦτα] τοῦ Vi 12 τί ViMaCl 13 ἴναρος C ἴνατος V  MaClLau Ferr ἴκαρος VaB Vi scriptura in Cr parum certa Ι  τί δὲ om VaBLau | νικίας Va sed κ in ras m 2 14 τί δὲ in- serui e ViMaCl cum Gasda om VCWolfLau edd scriptura  in Cr parum certa
footnote 10 Diod. S. XIII 12 20 Dem. 01. I p. 10, 3  1 ἴν scripsi e VaBViLau ἴνα VCWolfMaCl edd scrip- tura in Cr parum certa 2 ἡμῖν MaCl 4 τί Cr WolfViMaCI 5 ταγμάτων Vi 7 εἰ — ἂν om Lau εἰ] ὡς Vi Ι τὸ C  τῶ WolfVaB Ferr 8 ποιεῖν Re ποθεῖν libri sed in Cr scrip- tura parum certa, Ferr Mor 9 ἀναιδείας Lau 12 μὴ Lau 13 οὐδὲ] καὶ VaBLau 14 τὸ ante οὕτω edd delevi  ὅτῳ Lau τῶι Wolf | πώποτε οὕτω coni Re 15 punctum  post ῥῆμα libri edd delevi Ι ὀρῶ C WolfVaVi Ferr 16 τοῖς  om Vi 18 ἤδη Ma Ι ὑμῶν Va | τῷ om VaBLau ViMaCI  19 οὕτως V sed τὼς in ras m 2 | οὐδ’ MaCI Ι ἐκεῖνος om Re 20 τοῖς ante πράγμασιν V sed eras voce πράγμασιν des  Cr fol 58 v eorum quae sequuntur in folio 58 r fere nihil di- spici potest
marginal RIII 264
footnote 4 sq. Plat. apol. p. 34 C 9 Dem. fals. leg. p. 446,11 1 τε in ras Va 2 om Lau Ι καὶ ante δοκεῖν Vi καὶ] τοι  Lau et γρ in marg Mor 2 τὸν inserui om libri edd Ι λοι- δορούμενον V sed in λοιδορεῖσθαι corr m 2 et γρ λοιδορούμενον  in marg m 2 „desunt hic “ Re 3 καὶ] τὸν VaB om  V | μέγαν V sed ἂν in ras m 2 μέγα CWolf Ferr | μέγαν V sed  αν in ras m 2 μέγα CWolfLau Ferr 5 αἱ — 7 λύονται omissa  particula γὰρ citat Macarius fol 82 v 6 παροξυνόντων Lau 7 ἔστω ὑμῖν Lau 8 δέδρακεν Lau 9 καὶ ante κατα- κρημνίσαι CViLau scriptura in Cr incerta Ι κατακρημνίσασυαι  VaBLau | κατακόψασυαι VaViMaClLau Ι ὅτι MaVi  11 καίτοι VVi | αὑτὸν scripsi e C αὐτὸν VWolfVaBViMaCl  Lau edd scriptura in Cr parum certa 12 κἂν scripsi καὶ  libri edd Ι εἴτις in ras V 2 ἥτις Vi | ἀπήγγελλε Vi ἀπήγγελε Cl  Ι δράσαι libri edd 13 καὶ ante τί Lau | πλέον ἐζήτησεν]  ἐζήτησεν ἕτερον Lau 14 μὲν om Lau | ἐκδόσεως inserui auc- tore Iacobsio Lect 103 Rev 4 qui τῆς μὲν ἐκδόσεως coni om  libri edd 16 μένειν Ma sed με in ras βαίνειν Οἶ’ μαἰνειν  Vi 17 ὁ Lau Ι ζητῶν Lau
marginal RIV 265
footnote 11 cf. ad t. Y 469, 6. Thuc. I 126, 7 1 μὲν Ferr Mor Ι ἠφάνισται VVi 2 μέλετε CWolfVi  μέλεται Lau 3 τηνταχίστην Β 5 δὴ ViLau 6 ἀφελκύ- σασθαι V sed σ(2) eras ἐφελκύσασαι Vi ἐφελκύσασθαι Lau 7 ὑμῶν om VaB | γενέσθαι Lau 8 ἀνασπάσατε scripsi e  Β ἀνεσπάσατε VCWolfVaViMaCiLau edd scriptura in Cr in- certa 10 ἀκολουθήσατε V sed ατε in ras m 2 ἀκολουθήσετε C  Wolf | ἡμετέροις Vi | τρόποις inserui, ut παραδείγμασι inserendum  coni Re om libri edd 11 τῶν(2) om V Mor Re Ι τῷ om Ferr  | Κύλωνι V sed λωνι in ras m 2 κύκλω CWolfVaBViMaCl Ferr  et γρ in marg Mor 13 τί ante μεῖζον V sed in ras m 2, CVaB  ViMaClLau, post μεῖζον Wolf edd delevi μέγιστον coni Re 14 οἱ scripsi e V sed in ras m 2, Lau ἢ CWolfVaBViMa  Cl edd sed delendum censuerunt Re et Iacobs Add 101 Lect  103 Rev 4 | ἐπαγαγόντες scripsi e ViMaCl ἐπάγοντες VCWolf  VaBLau edd scriptura in Cr incerta 15 τὰ om VCWolfVi  Ferr | τολμῶσι VCWolfViVaBMaCl Re 16 ᾤοντο ἀρκεῖν  scripsi δοκεῖν libri edd sed ἐνόμιζον vel ἡγοῦντο ἀρκεῖν coni  Re διαρκεῖν Iacobs Lect 103 Rev 4
footnote 3 sq. cf. p. 287, 15 1 οὖν om Lau οὐκ VaViMaCl Ι ἔγραφε Lau 2 τιμω- μένω Vi 3 ὑπερίδα VaBVi 5 πολιτείας μιμηταί MaClLau 7 ἀντιλαμβανόμενος CWolfViMa sed in hoc αμβ in ras, Cl  Ferr et γρ in marg Mor 8 voce ἐλεήσει des Cr fol ρ | δὲ  post τίς ViMaCI 9 τῷ βωμῷ om Vi 10 προσδοκῶντες Ma  sed ε in ras m 2 προσδοκῶν τἀς CI 11 αὐτῶν om Cl  12 δὲ] οὖν Lau Ι αἰτεῖν Lau Ι ἑτέραν V sed αν in ras m 2, Va  sed γρ δευτέραν in marg m 2 13 οὖν scripsi e VaBViMa  ClLau γὰρ VCWolf edd | τὸ om Lau 14 ποτε τουτὶ inserui  e VCVaBVi (in quo ποτὲ bis scriptum) MaCI τουτὶ χωρίον  ποτὲ Lau om Wolf edd | τὸ ante χωρίον V 15 δὲ scripsi e  ViMaCI δὴ VCWolfVaBLau edd | τὸ inserui e VaBLau  om VCWolfViMaCl edd Ι προβουλεύματα scripsi e Vi, ut coni  Re προβούλευμα reliqui libri edd 16 συνηγορίαι VaBVi  Ma sed in hoc συνηγο in ras m 2, Lau 18 τε V
