@node
@author=Libanius
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Richard Foerster
@filename=tlg2200.tlg00462.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane
@publicationStmt=University of Leipzig, tlg2200.tlg00462.opp-grc1.xml.
@respStmt=Gregory R. Crane, Editor-in-Chief, Perseus Digital Library, Digital Divide Data, Corrected and encoded the text, Matt Munson, Project Manager (University of Leipzig), Annette Geßner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor, Greta Franzini, Project Manager (University of Leipzig), 2013-2014, Frederik Baumgardt, Technical Manager (University of Leipzig), 2013-2015, Simona Stoyanova, Project Manager (University of Leipzig), 2015, Project Assistant (University of Leipzig), 2013-2014
@sourceDesc=Richardus Foerster, Richard Foerster, Libanius, Orationes LI-LXIV, Teubner, Leipzig, 1908, 4, Internet Archive.
@sponsor=University of Leipzig
@title=Oratio 62
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:57:24Z

6358	marginal R III 434
footnote C = codex Chisianus Mo = Monacensis gr. 101 Ρ = Palatinus gr. 282 Β = Barberinus II 41 Μ = Marcianus gr. 437 U = Urbinas gr. 126 I = Marcianus append.
footnote L = Laurentianus LVII 20 Κ = Cantabrigiensis olim Kerrichii Ath = Athous Laurae S. Athanasii Ω 123 7 sq. Luc. iud. voc. § 2 1 Λιβανίου τοῦ σοφιστοῦ λόγος ante πρὸς K, τοῦ αὐτοῦ Ath  πρὸς τούς λέγοντας μή τινας τῶν ὁμιλητῶν ὠφελῆσθαι παρ’  αὐτοῦ ἐπὶ λόγοις L sed ἑτέρα ἐπιγραφὴ πρὸς τούς εἰς τὴν παι- δείαν αὐτὸν σκώψαντας in marg m 2, Ath et praemissis vocibus  ἑτέρα ἐπιγραφὴ in marg Μο κατὰ τῶν λοιδορούντων: λόγ. λς  Macar fol. 92 Ι τὴν om Β 2 σκώψαντας Ρ Ι ξβ' et in ras ογ'  in marg C 2, κ in marg rubr Β post ἀποσκώψαντας 4 αὑτοὺς reposui e CBMUIL αὐτοὺς reliqui libri edd  5 τε inserui BAth om reliqui libri edd 7 οὐδὲν Μ
marginal R III 435
footnote 1 τοῦτ’ UILKAth 2 τῶ L sed ῶ in ὁ corr m 2, KI |  η  εἰς τοῦτο ΒΜ 6 εἴ Μ 7 ἔστι scripsi e Κ ἐστὶ reliqui  libri edd 8 δέ in ras L 2 | τουτουσὶ L sed ουτουσὶ in ras m 2 Ι  αὐτῶν scripsi ex UI cum Monnerio αὐτῶν reliqui libri sed'  in ‘ o corr P 2, edd 9 των Ι | τύχας Cobet Misc. 153.  275 Ι ἐξετάζοντας I sed α (2) ex o corr m 3 10 τούτων Ρ sed  ν eras et ι subscr m 2, Mo Mor | με πάλιν εἰς εὐφημίαν Mor  sed γρ μεγάλη εἰς δυσφημίαν in marg 11 καθιστῶσι UIK |  φεύγων I sed ω ex ει corr m 3 φεῦ ν cum ras 2 litt U  12 τέ ΚΜο τέ ante τι edd quod delevi 14 ἀπεχομένων Κ  15 γἂν UL sed in hoc γ eras τἂν ΙΚ | τῶν I sed ω in ras  m 3 17 ἀληθὲς ἐκείνους UILKAth 18 συγγνοίη τἂν U 20 τὴν om Mor
footnote 1 τίνα CMoPBMILK | καὶ(1) inser I 3 om UBM | πε- ριόντες ΚΜο Ι signum interrogationis post λέγουσιν ΙΜ, colon Β 2 τε om UI | εἴη Μο 3 εἶτα ΒΜ 4 ἐρωτῶσι Ρ sed ι  in ras m 4 Ι τῶν U sed ῶν eras et in o ι corr | τούτῳ Β sed τ (2)  in ras m 2 inser I 3 om U 6 et 7 δὲ UIBM 7 διδασκάλων  scripsi διδασκαλείων libri edd 8 φθάσαντας Μ sed ες  suprascr m 2 Ι αὑτοῖς reposui e CMoPIBML cum Monnerio  αὐτοῖς reliqui libri Mor Re 10 εἰλήφασιν I 11 ἐπιδείξω  μικρὸν ὕστερον ΒΜ | νῦν inser I 3 om U | εἷναι ἀληθὲς I sed  β' et α' suprascr m 3 ἀληθές εἷναι Κ 12 ὧς inserui e  PBMUILKAth om CMo edd ὅτι coni Cobetus Coll. 275  13 ἀπειρίαν reposui e libris (sed ἀπορίαν Μο) cum Cobeto  ἀπορίαν edd 14 αὐτὸς del P 3 | ὧν reposui e libris cum  Monnerio, ut coni Re Anim ὠς Mor Re Ι διδάσκοντα Ρ sed σκ  in ras m 3 δόξαντα UILK 16 τις om U τίς ΒΚ et inser I 3 17 γε om UILK μὲν Ath et Re Anim
marginal R III 436
footnote 15 cf. ad t. III 437,10 1 οὐ om Κ 3 ἀπενεγκὼν scripsi e PBMUILKAth coll.  t. III 70,23; 324,13; t. III 3,14 R, ut coni Re Anim ὑπενεγκὼν  CMo Mor ἐπενεγκὼν I sed ε (1) in ras m 3, Re 4 πόλεων  πολλῶν ΒΜ 5 ταμέγιστα Ι 6 τέ τινες scripsi τινες CMo  ΡΒΜ edd τε UILKAth 7 πάνθ’ ὅσα πάρεστι scripsi πάνθ’  ὅσ' ἄπεστι CMo sed in hoc περίεστι in marg, Ρ edd πάνθ’ ὅσα  περίεστι ΒΜ sed in hoc γρ πᾶν θ’ ὅσ᾿ ἄπεστι in marg, UIL  Ath πᾶν θ’ ὅσον περίεστι Κ πάνθ’ ὅσ᾿ ἔνεστι coni Mor, πάν- τοσε πέταμαι aut πάνθ’ ὅσα παρεσκεύασται κατά τῶν ὑπτίων  Re Anim „Fortasse legendum πάνθ’ ὅσα πάρεστι κατά τῶν  ὑπτίων. An παρέστηκε κατὰ ?“ i Iacobs Lectt. 217 10  om U 13 Μεγάλη—18 σύμμαχος citat Plan fol. 103 v  14 μὲν om Κ 15 γένοιτο LAth | δ’ Β 18 γενναῖος Ρ sed  ος in ras m 2 γενναίω ΙΜ sed in utroque ’ ω in ras m 2 | καιρὸς  Ι sed ὁ in ras m 3 καιρο cum ras 1 litt U
marginal R III 437
footnote 3 Thuc. III 13,4 καιρὸς δέ ὠς (corr. οἶος) οὔπω πρότερον  4 Plat. Polit. ρ. 305 D 8 cf. t. III 90,10 sq. 13 cf. t. II 304,11 2 καὶ πρὸς LKAth 3 κινῶν L sed κιν in ras m 2 νι- κῶν Κ 4 ἐνέβην scripsi e P (sed ἐ in ras m2) auctore Re  Anim cum Monnerio άνέβην reliqui libri edd 5 ἣν Ρ sed "  in ras m 2 ἦν Μο Ι οὐ scripsi e Ρ sed ὐ in ras 2 litt m 2,  ΒΙ sed in hoc inser m 3, KAth om MU οὖν reliqui libri Re  οὐ] νῦν Mor 6 δἐ Κ | τὴν inserui e libris om edd Ι ἐρήσε- ταί reposui e PBUILKAth αἱρήσεταί C αἱρήσεταί Μο εἰρή- σεται Μ edd 7 ὃς—9 προήγαγεν citat Plan I. I. 8 κακοῦ  Plan 10 καὶ om K Mor | (??) C 11 αὐτὸν scripsi e  CBM cum Monnerio αὐτὸν reliqui libri Mor Re 12 ἐκτείνων  scripsi e Μ (sed εἰ in ras m 3 et supra ω ras) auctore Re Anim  cum Iacobsio Lectt 217 et Monnerio ἐκ τι νων cum ras post ι  et supra ω U ἐκ τῶν ὧν reliqui libri edd | δὴ scripsi e ΡΒ  MUILAth cum Monnerio δεῖ CMo edd δ(??) Κ δέ coni Re  Anim Iacobs Ι τὴν θεῶν ἀπὸ coni Re Anim 14 φιλοσόφους  scripsi e Ρ sed v in ras m 5, BMUIK Φιλοσόφοις reliqui libri  edd
footnote 7 cf. t. II 301,17; 291,15 sq. Amm. XXII 3,12 et XVIII 4,3  cum nota Valesii 13 cf. t. III 91,15 14 cf. t. II 360,7; t. III  ρ. LV sq. Iul. Mis. p. i 344Α et 357 C; cf. Asmus Hebd. class.  1907 col. 152 16 cf. t. II 300,3 et 11 1 σοφιστάς scripsi e Ρ sed ὰς ex αἷς corr m 5, BMUIK  Ath σοφισταῖς reliqui libri edd 2 εἰς] καὶ εἰς CP sed in  hoc καὶ eras, L sed postea inser, edd sed ἔκλεισε τὴν πάροδον  εἰς coni Re Anim, ἔκλεισε Iacobsius, Monnerius, Cobetus Coll.  275 cf. t. II 302,13 | οὐδένα] καὶ οὐδένα CP sed in hoc καὶ  eras, edd anacoluthiae simillima exempla habes t. II 130,2 sq.  et 332,14 sq. et supra ρ. 46,8 sq. 3 εἶδεν reposui e libris (sed  οἶδεν Μ ut edd) cum Iacobsio 5 αὐτὸν reposui e Ρ cum Mon- nerio αὐτὸν reliqui libri edd 7 τινάς ante ἀνθρώπους BM |  ἐφειστήκει Mor sed γρ ἀφειστήκει in marg 9 ἡ] εἰ Κ  12 λάθῃ ΒΜ 13 δέ om Κ | τούς ὠχρούς inserui e PBMU  ILKAth τούς ἐχθρούς C sed ἑ ex ὠ corr, Μο om edd | τούς  scripsi e CPBMUI sed in hoc οὑς ex οῖς corr m 3, L sed e  τοῖς corr m 2, Μο τοισ Ath om Κ τοῖς edd 15 διασύραι  UILMo 16 ἀνῆγον coni Mor
marginal R III 438
footnote 2 τὰς (1) om Κ 3 ἀμφότερον U sed ν eras, Ι 4 ὁ (1)  om Κ Ι κναφέως scripsi e BMUI coll. t. II 293,7; III 319,8 et  10 γναφέως reliqui libri edd 5 τροφὴν Β 6 ἐφίππου Κ Ι  λαμπρὸς λαμπροῦ I 7 ὀφρύς Ρ sed ' p in ras m 5 ὀφρῦς  Μο ὀφρῦσον Κ 9 ῥήτωρ ὢν Cobet Coll. 275 16 καλὸς  om ΒMU inser I 3 | τὸ μόνον σῶσον scripsi auctore Cobeto  Coll. 276 τὸν μόνον σώσοντα CPBM Monn τὸν μόνον αωσ(??)τα  Μο τὸν μόνον σώσαντα UILKAth Mor Re 18 τοῦτο Ath  19 αὑτοὺς scripsi ex UI αὐτούς reliqui libri edd 21 τοι- ούτων Mor 23 δὲ inserui om libri edd
marginal R III 439
footnote 1 αὐτῶν Κ 4 αὑτῶν scripsi αὐτῶν ἁ αὐτῶν reliqui  libri ’ o in ‘ d corr Μ, edd 5 μέν in marg Mo 2 | τὸ (2) 6 θατέρων Μο τῶ θεάτρῳ UILKAth | δέ Μο | αὐτοί  scripsi οὔτοι libri edd 8 οὐκ inser L 2 10 ἀθήνηθε UI  sed in hoc ν post ε inser m 3 11 καὶ (1) om U inser I 3 Ι τὸ  e τὸν corr I 3 Ι λύκιον UILKAth 13 διακονούντων scripsi  e PBMUILKAth διακόνων CMo edd 14 &gt; βασιλείων  scripsi auctore Re Anim βασιλέως libri βασιλέων edd cf.  p. i 354,4 15 πανταχῆ MUILKAth 17 συνόντων Re  ιόντων libri Mor 18 ἔβλαψε UIK 20 οὐ Cobet Coll. 276  at cf. t. III 444,6 et ad t. III 391, 1
marginal R III 440
footnote 8 Plat. Rep. VIII p. 551 A cf. t. II 304, 8 14 cf. t. II 305, 1;  t. III p. LII; Weinberger Hebd. phil. Berol. 1907 n. 3 et 4 18 Οὐαί σοι κἀκείνῳ τοῖς μιαρωτάτοις K 1 τας (2) I 4 κωνσταντίνου C sed v (3) suprascr κωνσταντίου  P 5 post ἀντιόχου punctum M et Monn, colon reliqui  libri edd, comma posui 8 τὸ λέγειν που Πλάτωνα scripsi  τὸ λέγειν ποῦ πλάτων libri τὸ λέγειν, ποῦ Πλάτων; Mor Re  τὸ λέγειν που Πλάτων᾿ Monn λέγει που Πλάτων Cobet Coll. 276 |  ᾒδει μὲν CMoLKAth Mor 9 δὴ reposui e libris et γρ in  marg Mor cum Monnerio δὲ Mor Re 10 δὴ MoUILKAth 11 κωνσταντίνου Mo Mor 13 δὲ BM | γρ ἀμφοτέρων in  marg Mor 14 λέγοντος L | λέγοντες UIK Mor | ἑτέρου U sed  et ov m2 ἕτερου I sed et ov m3 16 τίς BIK 18 ὀ  ante Ἰουλιανὸς edd delevi
marginal R III 441
footnote 3 ΙΙ. β 453 7 Dem. Ol. II p. i 20,27 8 cf. t. II 103,6 2 καὶ —3 ἡδίων omissis verbis τοῖς νέοις citat Plan fol.  103 v 7 ἀνεχαίτισε UI 9 ἐπιδιδόντα Β sed δι inser m 2,  UILK 12 οὐκ αὐτοῦ μέν Ath 14 τίς ΒΙΚ 15 τινος  om Μ sed in marg add m rec 17 ῥᾳθυμίαν Ρ sed ὁ in  ras m 2 18 σε post ἤνεγκε Μο Re quod delevit Monnerius  21 τῶν(1) om UILK 23 δὴ reposui e CMoPBMILAth coll  p. i 356,4 δε(??) Κ δέ U edd | γιγνομένου reposui e libris  νου edd
footnote 5 Dem. fals. leg. p. 411,2. Plat. rep. V p. i 451 Α. 16  t. III 438,17 sq.; 465, 9sq. 1 κὰγ αὐτό] ταὐτό Κ Ι τὸ—4 κτώμενος omissa γὰρ  particula praemissis verbis τοῦ κατά τῶν λοιδορούντων citat  Macar fol. 92, unde ut fragmentum orationis ineditae ediderunt  Villoissonus Anecd. II 16 et Reiskia t. I praef. t. XXXI  3 τίθησιν Μο 6 ἐπ’ Mor 7 παρὰ τούτων scripsi auctore  Re Anim παρ’ αὐτῶν libri edd 8 τὸ Mor sed τοῦ coni  9 ἐγίνετο Κ 11 τριττός CMo sed in hoc τ (3) del, Ρ sed  in τρίτος corr m 5, Μ sed in marg τρίτος; IL 14 μὲν  om UILKAth 15 τά Mo Mor qui τούς coni Ι νέους in ras  L 2 π(??)ς Κ 16 τῆς in ras L 2 τῶν Ath Ι ἀναγκαίων Ath 17 τῷ scripsi ex UILKAth cum Monnerio om CMo sed in  ’ hoc in marg, Mor τὸ PBM Re | p τοὺς om PUILKAth  Ρ sed αβ in ras m 5
marginal R III 442
footnote 8 cf. t. I 107,5 Eur. Herc. 646 17 Aeschin. Ctes. § 146  p. 74,19 2 ἐδοκεῖτο Ath 3 προδεῖσθαι L | ἀμείνονος Ρ sed μεί in  ras m 2 6 ὧσάν ΒΙ 9 το (1) Ι Ι ἀλλά — εἰσέρχεται om BUI Ι  μέν inserui e CPMLKAth auctore Re Anim cum Monnerio  et Cobeto Coll 276 ἀλλὰ τὸ δεύτερον τοῦ προτέρου ἐκπεσόντος  εἰσέρχεται coni Monn Ι τὸ δέ οὐκ ἔστιν ὅπως οὐκ ἐξέρχεται  inserui auctoribus Re Anim τὸ δὲ ἀπέρχεται) et Cobeto τὸ  δέ πάντως ἐξέρχετ.αι) τὸ δ’ ἀπόλλυται in marg Μ m rec  12 ἐκείνων scripsi auctore Re Anim cum Monnerio et Cobeto  τούτων libri Mor Re 12 τούτω e τοῦτο corr ΡΒ τούτοις  et ἐκεῖνα coni Re Anim 13 ὥστε ΒΜ | ἂν om Μο 14 τού- του om Κ τούτου τὸ] τοῦτο LAth 15 ὡς Μο et inser C  om PBMUILKAth 16 τοῦτ’ εὑ scripsi τοῦτο libri Mor Re  τοῦτο καλῶς Monn 17 διαδικασίαν L sed ν in ras m 2  18 λαχεῖν scripsi auctore Cobeto λαβεῖν libri edd δὲ ΒΜ  om UILKAth
marginal R III 443
footnote 1 ἐντεθέντας scripsi e CPBM auctore Re Anim ἐι τεθέντας  U cum ras post ι ἐκτεθέντας reliqui libri edd | πόνους Monn  ὑπὸ reposui e CMoPBMUILK auctore Re Anim ὑπὲρ Ath edd  προτέρων scripsi e B auctore Re Anim πρότερον reliqui libri  sed in προτέρων corr K2, edd 2 τ σ cum ras 1 litt U τῆσ  I | ὑπὸ K 6 ἔστι νῦν reposui e libris ἔστιν οὗν Mor qui  ἔστιν ὅμως coni ἐστὶ μὲν Re | μὴ τῶ I sed in μή τω corr m3,  K | φθονεῖν δόξαιμι UILKAth adversante norma clausularum  Libanii 8 οὐδὲ] οὐ γὰρ M 9 τῆς ante τραπέζης edd  delevi 10 τοῖς reposui e libris sed in τὰ corr I3 τούτους  edd sed τοὺς coni Re Anim | κολάζουσι reposui e CPBM  κολάζουσιν reliqui libri edd | τὰ—11 ἀποκηρύξουσιν inserui e  CPBMUILKAth om Mo edd sed τοὺς δὲ φοβοῦσιν inserendum  coni Re | ἐκβάλωσιν L sed άλω in αλοῦ corr m2 ἐκβάλλουσιν K 11 καταλείψωσι Κ 13 δεδοίκασι L sed ω supra οι m2,  Ath | αὑτῶν L sed ‘e’ corr m2 αυτων U αὐτῶν CMIK  14 αὑτοῖς PBL sed in hoc in corr m2, K | οἱ K sed ι in ras  m2 16 πίνουσι scripsi πενθοῦσι libri Mor quod delevit Re  τενθεύουσι Ruhnken Tim. p. 181 s. v. τένθης τένθουσι Boissonad.  Pachym. p. 236, 2 et 328
marginal R III 444
footnote 4 Eur. Andr. 223 13 Dem. p. i 14,17 18 Dem. cor. §  p. i 226,13 sq. 1 δὲ om libri excepto Ath | ἐνδείκνυται Mor 2 τοῦτο  ΒΜ Ι εἰ Β et in marg m rec Μ | ἑτέρων Μο | post ἥξουσιν  comma posui, colon Mo Mor, punctum reliqui libri Re  3 δὲ(2)] „malim γε“ Monn 4 συνερῶσι I sed ω in ον corr m 3  συνεργῶσι ΒΜ Ι καἰ τις reposui e CMoBMILK cum Mon- nerio, καὶ τίς reliqui libri Mor Re 5 ἐπιμίξεις ἁ 6 καὶ (1)  —7 ἐθαύμασε om C 8 αὐτῷ Re | παρέξειν reposui e libris  auctore Re Anim παρέξει edd 9 ἐπιτιμῶντας; Mor Re  10 ταῦτ’ ILK 11 τὰ Β | μενούσας UL sed in hoc in μὲν  οὔσας corr, Ath 12 πράττειν KAth 13 διχῇ edd 15 οὑν  scripsi auctore Re Anim cum Monnerio οὑν σύν Ρ σύν reliqui  libri edd Ι παρ’ ante ἡμῖν inser coni Monn | παρείληπτο LK  Ath 17 τούτων Μο 18 ἀλαζονεύσομαι scripsi ex UB  ἀλαζονεύομαι reliqui libri edd
footnote 6 Constantinopoli cf. t. II 286,19; 391,6 1 ἐνέπλησα cum ras 1 litt post α Μο 3 ἡρακλείων U  et supra ἡρακλέους Μ 6 καὶ om UILKAth 7 ἐλησπόντω  I sed λ alterum inser m 3, LMo 9 γὰρ om Μ 11 ἴδοις  reposui e MoPBMUILKAth ἴδης C edd sed γρ ἴδοις in marg  Mor Ι οὐκ om Μο 12 ἁρμενία ΡΙ ἁρμονία Μο cf. t. II  518,12 Ι τούτους Κ Ι οἰκία L sed οἱ Κίλικες in marg, Κ  οἰκίας Ath 13 οἱ Μο sed ὃ καὶ in marg om Κ ὁ καὶ  L ὃ Ath Ι γε om Μ 14 βαδίσῃς scripsi ex UILKAth  βαδίζῃς reliqui libri edd 15 ἐπὶ om Κ 16 ἑταίρων om  Μο Ι φαύλοις L sed οις in ras m 2 Ι μοί τινα καὶ reposui e  libris μοι καὶ τινὰ edd 17 καὶ ante χάριν Ath, ras 1 litt L 18 ὰρραβία MUILKAth cf. t. I 125, 5; t. III 51,3; ep.  396 | o Ἴσαυροι reposui e libris Ἰσαῦροι edd | πισδαι B
marginal R III 445
footnote 5 cf. Seeck Epist. Lib. p. 198 1 ἡμῶν Ι sed ων in ras m 3 ἡμῖν U sed ι eras 3 φαίην  Μο sed ην in ras m 2 4 πολίται Ι πολίται LAth 5 ὀμω- νύμω Μο sed ν post ω (2) eras ὁμωνύμῳ Ath ὁμώνυμοι Re |  γαλάτα CPBM | καὶ (1) om ΡΒ Ι πέρυσι scripsi e BMUIL  πέρυσιν reliqui libri edd 6 οὐ om U inser I 3 Ι φοῖνιξ  BMUIL 9 οὐδέ—13 βεβουλῆθαι omissa γὰρ particula citat  Plan fol. 103 Ι οὐδὲ] ού Κ οὐκ Plan | ἐβουλήθησαν scripsi  e CPBMUI Plan ἠβουλήθησαν reliqui libri edd 12 εἴη αη- μεΐον L sed ημείον in ras m 2 εἴης ἡμῖν Ath εἴησ Κ 13 τὸ  in ras I 3 τ cum ras 1 litt U τῶ L sed ώ in ὁ corr m 2 Ι  μὴ om Mor 15 κωλύοντες U 16 αὑτοὺς scripsi e CPBMUI  sed in hoc ‘ v e ’ corr, LK αὐτοὺς reliqui libri  17 μυρίον reposui e libris μυρίοις edd 19 ἄρχειν Ι sed  ειν in ras m 3 post ἄρχειν ras 3—4 litt U
footnote 1 Phasganius | Panolbio 13 Plat. Symp. p. i 204 Β;  thyd. p. i 279 D 1 οὑμὸς] οὐ μόνος Mor sed γρ μόνον in marg | οὐδαμῆ  scripsi ex UI coll. p. i 173,15 et t. I 508,11 οὐδαμο(??) Β  δαμοῦ reliqui libri edd 2 ὅπου Μ 3 διεώσατο διεώσατο e  PBUI sed in his omnibus σ ante ω eras, Μ auctore Re Anim  cum Monnerio διεσώσατο reliqui libri Mor Re 5 οἳ reposui  e libris cum Iacobsio Lectt 217 ὅτι edd 6 τοῦτο ΒΜ  8 ὠγκωμένων reposui e CPBMIAth ὀγκωμένων ἃκ ὀγκου- μένων L sed ου in ras m 2, Mo Monn ἀγνοουμένων Mor Re  τῶν ἀγνοουμένων, ἐπειδὴ δέ ἦρξαν, ὀγκουμένων Iacobs 10 λυ- σιτελές τε L sed τε eras, KAth 12 ἔὸει L sed in εἰ δεῖ corr  m 2, Ath 13 παι cum ras 2 litt U παισὶ Ι 15 μὴ δὲ  ίαν UK 16 ἀλλὰ ΒΜ
marginal R III 446
footnote 5 cf. t. III 399,1 6 ἀλλ’ εἰς ἐμέ Ι sed apostrophus, spir. supra ι in εἰς, ε (1)  in ἐμὲ m 3 Ι τίς scripsi ex Ι sed ' p add m 3 Κ τις reliqui  edd 7; inserui | ὃς ex ὠς corr L 2 8 ἐπίταγμα Κ 10 γε  post δὲ UI Ι ὑπέρ τοῦ μὴ] μὴ ὑπὲρ τοῦ L sed μη eras, KAth |  τὸ Mor 11 ποιοῦσι Mor sed γρ ἔχουσι in marg 13 εἰπόντες  L sed ες in ras m 2 14 ἐπιδείξεις scripsi e Ρ sed ἐπι in  ras m 2, Β sed ἐπι supra ἀπο, et γρ in marg Patm auctore Re  cum Monnerio ἀποδείξεις reliqui libri Mor Re 15 εὖ φρο- νούντων scripsi e MoPBMIK εὐφρονούντων reliqui libri edd 17 ἠνώχλησας om Mor | τὸ UI sed in hoc ὁ in ω corr m 3 ι  καὶ σμικρὸν om Β | p μικρὸν I 19 μὲν post οό UI sed in hoc 20 οὐδ’ L sed οὐ ex o corr m 2 ὃ δ’ Κ ὃδ᾿ Αth οὐκ UI
marginal R III 447
footnote 6 cf. ep. 1033. 971. 984. Sievers p. s 42 not. 228 11  Ι 11,2; IX 16,3. II. β 111; ι 18. Soph. O. C. 526. 2 ἐνορῶντες et 3 θαυμάζεις Mor sed γρ ἐνορῶν τις et θαυ- μάζει in marg 7 δύναιτο Ι sed το add m 3 δύναι cum ras 1  litt U Ι δ’ Ι sed δ in ras m 3 om U 8 δὲ om LKAth |  τοῦτο παρέλθω Mor Re τοῦτον ἀπέλθω libri sed τοῦτον in  ταῦτα ἂν corr B 2, δείξοι δέ τοῦτο ἀπελθών in marg Μ εἰς  τοῦτο παρελθών coni Re | παρέλθω] πάρεργον vel παρέργων  coni Monn num παραλείψω, ut t. ΙΙ 18,6? 10 αὑτούς reposui  e CPBMUI cum Monnerio αὐτοὺς MoL sed in hoc οὑς in ras  m 2, Κ Mor Re αὐτοῦ Ath 11 ῥήτορα Iacobs Lectt 217 | φέρων]  φέροντα Ath | ἑαυτὸν I sed ' p ν in ras m 3 ἑαυτὸ U cum ras 1 litt 13 γεγενῆσθαι Κ 15 δέδωκεν Ρ sed ε(1) in ras m 2 ἔδω- κεν UIK 16 „malim ὑπῆρχε'· Monn 19 δέ τινες CMoUI  sed in hoc in δὲ τίνες corr m 3, LKAth Re Monn cf p. i 361,8  κά om Mor
footnote 3 Strategius et Albanius cf. ep. 1097.1480.450. 61 cf.  Sievers ρ. 288 sq. 4 ep. 642 cf. Seeck I. I. p. i 47 sq. et 50 2 τῇ πρώτῃ Ρ sed η πρωτ in ras m 2 3 τὸν μέν—6  παρέχονται citat Plan fol. 103 v 4 παρελθόντε ΡΙ sed in  hoc ε(2) in ras ex ες corr m 3 | τὸν βέλτιστον Ἀγησίλαον  om Plan τὸν—5 οὐδ’ in ras 12 fere litt et in marg I 3  5 ἀπολειφθέντε PI 3 6 αὐτούς scripsi αὐτούς libri Plan  edd Ι παρέχονται reposui e libris παρέχοντε· Μο sed ε· in  ras παρασχόντες in marg m rec Μ) Plan παρέχοντες edd  cf. t. III p. i XI 9 τίς ΒΙΚ om Μο | πράγμασι Monn 10 μονονοὐχ PU μόνον οὐχ ILKAth 11 αὐτῶν scripsi  e PML sed in hoc 'e' corr m 2 αυτῶν U αὐτῶν reliqui libri  edd Ι τοῖς ἡμετέροις λόγοις coni Re Anim 12 δείξειεν Ρ sed  εν in ras m 4 δείξειν C δείξοι MU sed in hoc ι(2) eras, Ι  δείξαι L sed αι in ras m 2 δείξοιάν Κ 13 „malim πολιτευ- σομένους“ Monn | πολλοὶ UILK 14 οὐ] οὐ πολλοὶ coni  Re Anim
marginal R III 448
footnote 2 cf. t. I 98, 4 4 Dem. p. 625, 6 12 Eur. Phoen.  1579 sq. 15 cf. p. 362, 1. Schol. Rehd. ad Apth. ed. Schaefer,  De Apth. soph. p. 3. Seeck Ep. Lib. p. 234 2 νέστερ L sed ε (2) in ω corr m2 νέστερος K 4 μὴ  δ᾿ MoBMIK 5 γὰρ &lt;λειτουργεῖν&gt; μὴ coni Re Anim  7 αὐτὸς &lt;λέγων&gt; coni Re Anim 8 δὲ in ras L2 9 λέγειν  inserui | περὶ οὐσίας B 10 οὕτως K 12 θεῶν om L |  τὴν δύ᾿ scripsi τὴν δι᾿ CMoP sed in hoc τὴν in ras m2, BML  sed in hoc ι᾿ supra ε m2, edd τὴν δε Ath τὴν δ᾿ UK τήν  δ᾿ I τὴν δυοῖν Iacobs Lectt 218 | τῇ ἐκείνων περιουσίᾳ τὴν  τούτων δεινότητα coni Re Anim | ἐκείνω K 13 χρἠματα  scripsi e BMUILK cum Iacobsio χρήματ᾿ reliqui bibri edd |  τῶν εὐπόρων scripsi cum Iacobsio εὐπορπῶν L ἀπορῶν K ἦν  εὐπορῶν reliqui libri edd ἐκείνων τῶν εὐπόρων coni Re Anim 15 θεῖόν τι γὰρ BM 16 γε om UI | καὶ om LK  18 κατηνάγκασαν reposui e CMoPBUILK κατηνάγκασεν reliqui  libri edd
marginal R ΠΙ 449
footnote Dem p. 750,21. Aristid. t. II p. 497,1; 534,5 et 7 D (= t. II p. 147,13; 183;6 et 7 K) 11 Dem. p. 975,17 et 17 1 παρὰ] ἐν? 4 βέλτιστε ΣΚΛίΤι 5 ἐμοῦ UI sed in hoc οἱ suprascr | διατοῦτ’ MoBI διὰ τοῦτο LKAth διατοῦτο M | οὐ om LKAth ὄν Mo | μισθοῦνται προσαγωγέας citat Plan fol. 103 additis verbis εἰσαγωγέας αὖ quibus spectat l. 11  10 περὶ BM | οὐδὲ BM 12 βῆσαι L sed o inser m2, K | ἐπιορκῆσαι om UI 14 ὡ cum ras 1 litt U | οὐδὲν om U inser I3 | οἱ om U 15 βούλ(??) Μ βουλεύονται reliqui libri sed βούλονται in marg Mo, in  βούλονται corr L2 | μὴ δὲ MoBMIK 16 μὴ δ' MoBMIK μηδὲ Ath | αὖ om Ath | ἀλλὰ CMoBM 17 τοῖς om UILK 18 ἔρυμα scripsi auctore Monnerio ῥεῦμα libri edd 19 ζητοῦντας et θηρεῦον- τας KAth
footnote 19 Aesop. fab. 420 et 420 b Η. Babr. 177 cf. t. IV 853 fab  2 R; t. I 138,6; ep. 72. Choric. dial. Philol. LX 193,14 sq. 1 εἰς πράξεις Ath 2 μίν ταῖς ΒΜ 3 τῷ Μ τό BUIL  sed ὸ ex ῶ corr m 2, K Re Monn 4 μήκει et κάλλει UIAth 5 τὸ om UIL sed in hoc inser m 2, Ath Ι τὸ τοῦ] τοῦ τὸ  CMoP Mor Ι τοῦ U sed ῦ eras om K | ὡσαληθῶς Β | ὄ λον  cum ras 1 litt U ἄλλον Ι ἄλλως post ὄχλον Μ 6 ἐπαι- νέσηται UI et γρ in marg Μ 7 δὲ in ras P 2 γὰρ Β  10 τοῦτο Monn at cf. ρ. 46,11; 351,3; t. II 16,15; 130,4;  332,17 Ι εἰ δὲ] οὐδὲ Μor 12 τὸν reposui e libris  cum Monnerio τὸ Mor Re 13 διδασκάλους K Re Monn  πάντως CPBM 18 ἐντεῦθεν — 20 νικῶσαι citat Plan fol. 103v  19 ἀλλὰ Μ 20 αὐτὸ τὸ Κ αὐτὰς τώ Plan αὐτῇ τῇ κτήσει Mor
marginal R III 450
footnote 6 Isocr. Euag. p i 198 b. Plat. ep. 8 p.353 A 1 τὸν μισθὸν UIL sed in τῶν μισθῶν corr I 3 L 2, KAth Ι  μοί om UIK | τίς BLK Ι ῥητορικώτερον CPUI et in marg Μο 2 ἀλλ᾿ — κτήσει om Mor 3 καρπωμένους UI 4 τἀργύ- ριον scripsi e BL ἀργύριον UIK τ᾿ ἀργύριον reliqui libri edd 5 με om Κ μέν LAth et in marg Μο 6 ἐκβαρβαρωμένας  UIK ι ἀξιῶ σε] ἀξιῶσαι Μο 7 οὐ] — 8 τεχνῖται citat Plan fol.  103v Ι γέλωτα PBMUI Plan et coni Cobetus Coll. 277 at cf. Aesch.  ου  fals. leg. p. i 42,43 8 τεχνίται I 9 χρυ(??)ν Κ | καθεκάστην  11 ἐζήτησάν scripsi e CPB ἐξεζήτησαν reliqui libri edd οὖν  ἐζήτησαν Cobet Coll. 277 Ι γε scripsi cum Cobeto et Sinteni  τε libri edd Ι χρήσασθαι UI (??)σασθαι Μ 13 δέ τις om UI  15 κατά τὴν coni Re Anim
marginal R III 451
footnote 16 cf. t. II 251,17 21 sq. cf. t. I 160,16 1 γεγενημένης Κ 2 τὸν νοῦν. μερίζει τὴν ἐπιμέλειαν repo- sui e libris τὸν νοῦν, μερίζει εἰς Mor δίκαις, τὸν νοῦν μερίζει  εἰς Re Monn 3 πρᾶσιν reposui e CMoPBMUI ἐπιμέλειαν  LKAth et in marg Μο, edd 5 ὁ ἠλιόδωρος Β 6 οὐ del  Cobet Ι μεταταῦτα MoBML 11 προλαβεῖν UI sed in hoc e  λαβὼν corr λαβεῖν C 12 ἁνὴρ? | τὸ Κ | εὐδοκιμεῖ LKAth Ι  δεξιόν Ath 13 δέ om Κ γε Ath 16 δ᾿ CMo 17 ἀνδρῶν  U sed ῶν eras, I 21 ὦ] οὐδὲν Κ
marginal R III 452
footnote 2 μόνον L 3 ἔγνωσαν scripsi e CPBM ἐγνώκεσαν  reliqui libri edd | τάχα UI 6 καὶ om Κ | ἄρξαντας  scripsi συνάρξαντας libri edd σύν ἄλλοις ἄρξαντας vel παρ’  ἄλλων ἢ ἄρξαντας αὐτούς ἢ συνάρξαντας coni Re Anim  7 ὁμιλητὰς scripsi ὁμιληταὶ libri sed αἰ in ras L 2, edd Ι  δέκα τοῦ δεῖνος L sed e δὲ κατουδὲν corr m 2 δέκα τὀὐδενὸς  Κ δέ κατά τοῦτ’ οὐδενὸς Ath 8 δ’ in ras 1 vel 2  litt L 2 8 γένη] δέ γένη Ρ γένη δ’ Β δέ ἐν UIL sed in  hoc in γένη corr m 2, KAth 9 διῴκηκας scripsi e CPBMK  διώκῃ ας cum ras 1 litt U διῴκησας reliqui libri edd | ὃν Μο  ὧν ILKAth 10 καὶ—11 ῥητορικῆς om Κ 12 τὸ LKAth |  γε inserui e PBMIKAth τε UL om CMo edd 13 πόλεων  scripsi auctore Re Anim cum Monnerio πόλεως libri Mor Re |  καὶ post λαβεῖν U sed eras, Ι 16 δ’ C μέν Κ | v ἀπὸ Κ  κωνσταντίνου Κ 17 ὡς Μο 19 εἱστήκεισάν PBMK Monn  εἰστήκεισαν Μο εἰστήκησαν Mor Re cf. p. 374,5 | τε om UI
marginal R III 453
footnote 4 cf. Seeck Epist. Lib. p. i 314 17 Alexander? cf. Seeck p. 53 1 μέντοι coni Re Anim | διακο cum ras 3 litt et τι ὶ cum  ras 1 litt U Ι τυχεῖν—2 μὴ om UI 2 καὶ ante δόξαι I  γρ διδασκαλείοις in marg Mor 3 τὰ τοιαῦτα προσθήσομεν  scripsi e PBMUILKAth προσθήσομεν τὰ τοιαῦτα CMo edd |  προθήσομεν Κ Ι δοῦναι, καὶ μὴ σεμνότερος Mor Re qui „possit  quoque inquit legi: καὶ δοῦναι καὶ ἀφελέσθαι, μηδὲν ἀσε- μνότερος vel καὶ δοῦναι καὶ ἀφελέσθαι. ὄρα μὴ σεμνότερος—  γίγνηται“ 4 γίνεται BMUK 7 ἀξιοῦνται I 8 οἶς Β ι  πρεσβεῦσαι CMo sed in hoc πρεσβύται in marg 9 τίς ΒΚ 10 τί ΜοΒΙ Ι ὁ χρόνος προιὼν ΒΜ 11 εἰ om UILKAth,  del Μο 12 τίς BI Mo | καὶ om UILK 13 αὐτοὺς  U sed u(2) eras ILKAth αὑτὸν Μονν | δ’ om UILKAth  ενι υ ἐνὶ ΙΚ 15 αὑτῶν scripsi cum Μ αὐτῶν reliqui libri  edd 16 μὶν inserui e libris om edd 17 αὑτοῦ scripsi e  PBMIK αυτοῦ U αὐτοῦ reliqui libri edd
marginal R III 454
footnote 4 Themistius. cf. ep. 312 550. 578. Seeck ρ. 307  16 cf. t. Ι 163, 2 cf. Seeck ρ. 75 17 II. κ 243 4 οὐδὲν πλέον Ath | τούτων reposui e CPBMUIKAth  τούτω Μο τούτου L edd 5 μὲν om Κ 7 τοῖς scripsi  e PBMUILAth auctore Re Anim coll. t. I 409,21; II 16,22;  95,11; t. III 300,22; t. IV 136,6 τούς reliqui libri edd  8 ἀνήγαγεν Re Anim, fortasse recte cf. p. i 94,11 |  CPUIL αὐτὸ Κ 9 παρὰ scripsi e PBMUILKAth ἀπὸ  CMo edd Ι μέγα Κ | ἤνεγκε τὸ] γρ ἀντὶ τοῦ ἡγεῖτο in marg  Mor 10 οὕτως Ath 12 γρ λογίῳ in marg Mor 16 Οὔτ  scripsi e BUILKAth οὔτε reliqui libri edd 17 ἑταίρων scripsi  e CPBM cum Monn coll. p. i 360,16; t. III 259,20 ἑταίρω  ἑτέρων UI ἑτέρῳ L sed in ἑταίρων corr m 2, KAth Mor Re |  τε om Κ | λόγῳ ἀμνημονήσας Κ | s νῦν ὰν ἀμνημονῶν  λέγω inserendum coni Re Anim
marginal R III 455
footnote 1 cf. t. II 546, 20 3 ep. 192. 166. 216. 217 6 Kalendarum  Ianuariarum cf. t. IV 1054, 3 sq. R 1 τε ante ἂν KAth, γε edd delevi | ἀδικοί ην cum ras 2  litt U | ἥττων scripsi ex UILK ἡττον reliqui libri edd 3 μὲν  om K δυναμένης L sed ένης in ras m2 4 ἐν ante ἑκάστοις  CMo edd sed „aut ἐν delendum aut leg. ἐν ἑκάστῃ sc. πόλει“  Re delevi cum Cobeto Coll. 278 4 καὶ ante ἀκριβέστερος  libri edd delevi auctore Cobeto | τῶν ante δεσποτῶν inserendum  coni Cobet 5 εἰώθεσαν scripsi ex UIK εἰώθεισαν  reliqui libri edd cf. p. 371, 19 6 καὶ cancellavi coll. t. II  553, 18 ὐποκοριζόμενοι τὴν ἀνάγκην εἰφήμῳ ῥήματι; Aristid  t. II 151, 22 D τὰς κακίας ὑποκορίζεσθαι τῷ τῆς ἀρετῆς ὀνόματι;  Philostr. iun. im. prooem. t. II 390, 4 K σχήματι εὐπρεπεῖ τὸ ῥᾴθυμον ὐποκοριζόμενοι 7 ὀνόματι scripsi e PMUILKAth  ὄνομά τι B ὀνόματα CMo edd 9 ἐκέλευε PBMUI \\ τοῦ I  sed eras | τουλοιποῦ BLK 10 φόνων scripsi e PBMUILKAth  cum Cobeto φόνῳ CMo edd sed „aut φόνου leg. aut φόνω τοίνυν  χρῆσθαι μόνος“ Re Anim | ὀλίγων scripsi e CPBMULK cum  Cobeto ὀλίγ ν cum ras 1 litt U ὀλίγον I edd | ἐδεήθη ὀλίγων  M 11 κατὰ om UILK 13 δὲ BMUI 14 ἐπιτάττειν εἰωθότων  UI | εἰωθότων inser L2 om K | των I
footnote 14 cf. Seeck ρ. 74 15 Procopius cf. ad t. II 391, 7;  519.21 18 cf. Amm. XXVI 7,6 19 Dem. ρ. 371, 18 1 τῶν(1) om UIK 2 καὶ βοῆ om Β 6 ὥστ’ ΡΙΚ | ἐκεί- νους Re ἐκείνοις libri Mor | ὡς δέ ἐκείνους ἔχειν ἐκμαθεῖν  coni Monn | ἐνδεικνύμενος δέ inserui coll. t. I 129, 18 om libri  edd διδαχὴ δέ vel ὑπομνήσει δέ inserenda coni Re Anim,  δείξας δέ Μοηη, ἀλλ᾿ εἰπὼν Cobet 7 οἵ MoBI | δὲ Μ  8 αὐτῶν Ρ sed ῶ in ὸ corr, ILKAth | οὐκ om C 11 τοῦτό  scripsi e CPBMUI coll. t. I 479, 18 τοσοῦτο MoLath τοσοῦτον  Κ τούτου edd 13 ἐκείν ν cum ras 1 litt U ἐκείνων Ι  14 καὶ om Κ 17 παρόντων πολλῶν UILKAth 18 δὲ(2) om  Β 19 ἐδέξατό Κ 21 μαχοῦνταί L sed ουν in ει corr m2 R III 466
footnote 3 cf. ad ρ. 254, 11 14 Dem. p. 283, 16 3 κακῶς Ath καλῶς Κ 5 φιλόπολις CMo sed in hoc  in marg φιλόπονος | βέλτιον LKAth 8 ὁρωμένων in marg  Mo 2 9 εἰς] ἡ CMo Mor | σπήλαιον ULKAth | καταδύς ἢ]  καταδύσειν LK καταδύς Ath 10 κρύψαι CMo | αὐτοῦ  scripsi e ΡΜ αὐτοῦ reliqui libri edd 13 πρᾶγμα εἷναι LK 14 ἐπὶ Β sed ὑπὸ suprascr m 2 | αὐτὸν scripsi e MILK  αὐτὸν reliqui libri ’ in ‘ corr B 2, edd 15 μακρότερον 1 |  μὲν om Κ | ἦν ΡΚ 16 τελευτήσας U | ἀπῆλθε I | δὴ ante  δημεύων Β et in ras P 5 | δημεύων Ρ sed ημευ in ras m 5  18 τὸν τρόπον ἐθαύμασε ἐθαύμασεν UK) UILKAth Χρόν(??)ν  ἐθαύμασε τὸν Μο sed τρόπον in marg 19 a κείνου  CB κείνου PML ἐκένου reliqui libri edd
marginal R III 457
footnote 5 cf. Seeck ρ. 104 sq. 12 ep. 654 1 αὐτῆς scripsi e PBMLAth αὐτοῖς CMoK Mor  αὐτοῦ UI Re Monn 2 πρότερον Κ | ποτέρῳ UIL sed in  hoc in πότερον ᾦ corr m 2, KAth 4 ὑμᾶς scripsi e  PMUILK cum Monnerio ἡμᾶς reliqui libri Mor Re  6 οὗτος in οὕτως corr P 2 7 ἐδυνήθη ΡΒΜ cf. ρ. 97, 5 8 πρὸς scripsi e BMUILKAth εἰς Ρ sed in ras m 5, CMo  edd 9 φυλάξας scripsi e C cum Monnerio φυλάξαι reliqui  libri sed ασ supra αι m rec M, Mor Re 10 ἔροιο Ρ sed ras 1  litt ante ρ εὕροιο Κ | δὴ om LK 11 ἡμῶν coni Mor |  παρά τοῦ reposui e libris (sed e παρ’ αὐτοῦ corr L 2) auctore  Re cum Monnerio παρά του Mor Re | τὸ del Μο om IKAth |  ῥητορεύειν; ἔχεις Ath 12 ἐμοῦ LK | ἀκούση scripsi ex  UILK cum lacobsio Lectt 218 ἀκούσεις CBM et ex ἀκούεις  corr P 5 ἀκούσης MoAth edd 15 εἰ ante δόξη KAth  δόξῃ—p. 378, 2 καλεῖν citat Plan fol. 103 v | ἧκεν ἐκεῖσε post  πειθόμενος Plan 16 λυκίῳ UILKAth 17 καὶ eras L om  MUIK
marginal R III 458
footnote 1 Zendob. II 33. Diogen. I 96. Babr. 76, 18 1 ἔδακνέ Plan | τε om C 2 με om Κ | ἡγουμένην  scripsi e CPBM ἡγουμένη UI ἡγούμενος L sed in ἡγου- μένην corr m 2, KAth ἡγουμένους Μο edd 3 αὐτὴ Β    αὐ(??) Μ 5 αὐτὸ cum ras 1 litt Β | καθαυτὸ Μ | αὐτὸς  Ath | ἔσχε scripsi e CMo sed in hoc εἶχε in marg, PBAth  εἶχε Μ sed in ἔσχε corr, ILK edd sed γρ ἔσχε in marg Mor  ’χε cum ras 2 litt U | ἐξ(??)ταζε L ἐξήταζε KAth 6 παῖδα et  7 ἐοικότα scripsi auctore Re cum Monnerio παῖδας et ἐοικότας  libri sed ς bis eras M, Mor Re 8 ὃ scripsi e PBMUILK  Ath οὑ CMo edd | τοῦ reposui e libris τοῦτο edd | μὲν τά  Κ 10 ἡμῶν Ρ sed ω in ι corr m 5, ΒΜ sed in hoc ἡμῖν  in marg, UIL sed in hoc ω in Ι corr m 2, KAth 11 ὧ Μο  ὢ Mor Re 14 ἐπίστασθαι Mo Mor qui ἐπίσταμαι coni  interpunctionem post ἐπίσταμαι sustuli, post μόνος inserui  auctore Re Anim cum Monnerio et Cobeto Coll. 278 | οὐκ ante  ἀδικοῦμαι inser B 2, οὐ μόνος ante τὴν inser coni Re Anim  at cf. p. 382, sq.
footnote 2 Din. c. Dem. § 30 20 Strab. XIII ρ. 626 1 δέ. εὐπορεῖς scripsi Auctore Re Anim δέ εὐπορεῖς  libri edd | ἀλλ’ ἐκ coni Re Anim | ὠμότητος — τόκους] περὶ  τούς τόκους ὠμότητος UILKAth 2 ἀναταράξας CMo sed in  hoc ἀνατέτραφας in marg ἀνατρέψας Ρ sed ρέψ in ras m 5  ἀνέτρεψας ΒΜ | χήραν C 8 οὐχὶ ῥοῇ scripsi e CMoPBM  οὐχ ὑπὸ UILKAth et in marg MoM, edd 6 καὶ ταῦτα scripsi  e BMUILKAth τοιαῦτα CMo sed in hoc καὶ ταῦτα in marg,  Ρ sed in lac 8 litt m 5 et ante τ(1) ras, edd 8 εἶτα Μ | προσαι- τήσαντες Ι 10 αὐτὸν ἁ αὐτὸν ΙΜ 14 λῃστὴς ΜοΒΙ  15 τοῦ Monn | του δέ Ι τοῦδε Μο 18 πράξεσιν UILK |  μόνον οὐ ILK 19 τῶν inserui e libris om edd
marginal R III 459
footnote 8 Dem. Ol. Ι ρ. 16, 4 1 αὐτοῦ scripsi e Μο sed ‘e’ corr, PBL cum Monnerio  αὐτοῦ U αὐτοῦ reliqui libri MorRe 2 μισουμένους Ρ sed  e μισούμενος corr, ΒΜ 4 δ’ scripsi e MoUILK δέ reliqui  libri edd 5 ὧσάν ΒΙ 6 ἀνάγκη Β I κατακλυσθῇ UIL  κατακλυσθε(??)ς Κ | πλουτεῖν post κατακλεισθῇ libri del Mor | δὲ  ΒΜ 7 ἔμελλες scripsi e PBMUILK ἔμελλε reliqui libri  edd | πλουτεῖν om libri inser Mor 8 καιρὸν scripsi e CMoP  BMUIL καὶ Κ καιροὺς Ath edd | σαυτῷ scripsi e BMUILK  αὐτῷ reliqui libri Re Monn αὐτῶν Mor 10 λόγους Ρ sed υ  in ras m 4 | εἷπεν Μο 11 οὕτος Mor sed γρ οὕτως in marg 14 δ’ ἐωνοῦ scripsi e CP cum Cobeto Coll. 278 δὲ ἐωνοῦ  ΙΒΜ δἒωνοῦ Μο sed δέ ἐῶν οὐ in marg δὲ ἐώνου ULAth  δὲ ἐωνεῖ Κ δὲ ὠνοῦ edd 14 βιάζη I sed η ex εἰ corr m2 17 αἰσχρὸν L sed αἰσχρο in ras m 2 | λόγοι Ath
marginal R III 460
footnote 6 cf. ρ. 242m 13 sq. Veget. mil. c. 23. Claud. in Ruf. II 353 sq.  Suid. s. v. θώραξ et ἱππική aliosque locos quos collegit Iac. Becker,  Grabschrift eines roemischen Panzerreiterofficiers ρ. 29 sq. 1 τἄλλα scripsi e BMIL τ’ ἄλλα ἄλλα Μο) reliqui libri  edd | δ’ om Mor δὲ Β | ἂν om Β | τύχοι reposui e  PBMUILKAth, ut coni Mor τύχῃ CMo edd | δὲ ΒΜ  2 στρεφόμενον reposui e CMoPBM τρεφόμενον reliqui libri  edd | τῶ ante βασιλεῖ Β 3 αὑτοῦ reposui e ΡΒΜ cum  Monnerio αὐτοῦ ἁ αὐτοῦ reliqui libri edd | πάλαι scripsi  πάλιν libri edd sed in suspicionem vocat Re 4 καὶ ante  οἴει Β 5 ποτε PBMUL 6 τὸν ὐπ’ αὐτὴ Ἱππέα μαχό- μενον ΒΜ 7 num οὗτος? | ἀλλά ΒΜ 8 τοῦ λόγου scripsi  τοὺς λόγους libri Mor Re τῶν λόγων Monn | τῇ τιρῇ coni  Re Anim 9 ἐπίστευεν scripsi e BUILKAth ἐπίστευσεν Μ  ἐπίστατο Ρ ἠπίστατο CMo edd sed ἠπίστατό σοι ἐχθρούς coni  Re Anim 10 ἀλλήλους Μ 11 ἃ] σύ δὲ Re Anim 12 ἥκου- σὰς Μ ἤκουες ILK | ὢ reposui e CMoPBMLK ὦ UIAth  τῳ Mor τὸ Re Monn 13 ἔναγχός scripsi e CPBMUILK  ἔναχός MoAth Ἴναχός edd 14 περὶ τῆς τοὺς Β 15 τυχεῖν  τινος UIK | οὐ δυνηθεὶς scripsi e MoBMUIAth ὀδυνηθεὶς  reliqui libri edd
marginal R III 461
footnote 1 Luc. Asin. 21 3 Eur. Phoen. 391 1 τε inserui 2 κηρῦξαι B 3 ἔχει ex ἔχων corr B  4 ἐπέσχον scripsi e PBMUILKAth, ut coni Re Anim ὑπέσχον  CMo edd 6 τοῖς οἰκέταις om UI | ἱκέταις M | δὲ M 7 τὴν  παρρησίαν αὐτῷ σεσωκότος UI 8 ταύταις K 11 οὐδὲ UI  προσήκειν P sed ειν in ras m2 12 αὐτῷ scripsi αὐτῷ libri edd  ἀρχῆς P sed ἀρ ex εὐ corr in ras m5 εὐχῆς CMo Mor qui ἀρχῆς  coni 13 ὁ del Monn 14 ἀλλ᾿ ἀεί] ἀλλ᾿ εἰ ex ἀλλά τι corr P  ἀλλὰ ἀεί BM ἀλλὰ εἴ UILK | πρότερον scripsi e PBMUILK  Ath προτέρων CMo edd | ζητῶν scripsi auctore Re Anim („fort.  ζητῶν aut si ζητημάτων servatur, deest ἐξευρών“) ζητημάτων ibri  edd 15 καὶ ante αὐτὸς inser Monn | αὐτὸν Mo K Mor Re  αυτο U αὐτῶ I 19 γε ante τὰς I, σοι LK 20 πονηροῦ P  sed οῦ supraser m5 | τινος om PBMUILKAth | σπέρματος P  sed σπερ in ras m5 σώματος BM sed in hoc κόμματος in marg
