@node
@author=Euclides
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Johan Ludvig Heiberg, H. Menge
@filename=tlg1799.tlg010.1st1K-grc1
@funder=Harvard Library Arcadia Fund
@principal=Gregory Crane
@publicationStmt=Harvard College Library, tlg1799.tlg010.1st1K-grc1.xml.
@respStmt=Digital Divide Data, Corrected and encoded the text, Gregory Crane, Editor-in-Chief, Perseus Digital Library, Matt Munson, Project Manager (University of Leipzig), Annette Gessner, Project Assistant (University of Leipzig) 2015 - 2017, Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor
@sourceDesc=Euclidis Opera Omnia, I. L. Heiberg, H. Menge, Euclides, Teubner, Leipzig, 1895, 7, Hathi Trust, Internet Archive.
@sponsor=Harvard College Library
@title=Opticorum recensio Theonis
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:54:55Z

12708	footnote Τὰ πρὸ τῶν Εὐκλείδου ὀπτικῶν V p v. 1. Post ὄψιν add. Εὐκλείδης m. rec. V. ἐκόμιζε] mut in κομίζει m. rec. V. 2. διότι] δι- del. m. rec. V. 4. ἀπορριπτουμένας] γρ. γινομένας m. rec. V, ἀπορριπτομιένας p. 10. τε] γε V v. 14. Post
footnote 2. φωτίζωντα V, sed corr. 5. συμβαίνειν p. μή] corr. ex μί v. 9. ἔχων v, sed corr. 11. πίπτειν] ν in ras. V, add. m. rec. V. 12 πτυχίον] supra scr. πυκτίον m. rec. V. ἔγγειον V, cor.r m. rec. 13. πόντος v, corr. m. 2. 16. κατά]
footnote 3. οὖν] om. vp, m. rec. V. ὡρᾶτο V, corr m. 1. ἐξ- εριμμένον V p. 5. θεωρεῖσθαι] -ει- in ras. m. 1 V. 7. ἀτενι- ζώντων v, sed corr. 8. ἔφασκεν V v. συνιστάμενος ἔφασκε] del., supra scr. ὁμοίως φησί m. rec. V. 9. πολλάκις V, corr. m. rec. 14. ἐστι, διότι] mut. in ἐστιν ὅτι m. rec. V. 15 ἄλλων αὐτῶν V, corr. m. rec. 17. ἅμα] supra scr. m. rec. V. 18 Post ὑπερβολῇ ras. 1 litt. v. τάχους] corr. ex τάχος m. 2 v
footnote 1. γίνεται p. 5. εὑρήσκουσι v, sed corr. 6. εὐρήσκουσι V, sed corr. 9 ἔφασκεν V p. τά (pr.)] τό V. 10 κατα- σκευακέναι v, V, sed corr. m rec. 11. μέν] om. v. 12. ἔξοθεν v, corr. m. 2. 14. ἐπιτήδιον V. 15. ἀναμῆναι v,
footnote 1. τό (pr.)] τοῦτο V, corr. m. rec. εἶναι] in ras. m. rec. V. 4. ταῖς] corr. ex τάς m. rec. V. 5. ἔλεγεν V, ν eras. v. ἡ] om. p v. αὐτῷ] bis p. v, sed corr. 8. ταπεινωτέρα V, et v, sed corr. 9. ὑψιλλοτέρα v, sed corr. ἐστίν] - ίν in ras. m. 1 V. 14. γίνεσθαι p. 17. ὄψη v. 20. περιφέρεια]
footnote 2. οἵων v, sed corr. 3 ὅροι] mg. m. 1 V; ὅροι ὀπτικοί ins. m. 2 p; ἐντεῦθεν οἱ ὅροι τῶν Εὐκλείδου ὀπτικῶν mg. m. rec. v. numeros om. V pv. 8 τῷ] corr. ex τό m. 2 v. 9. πέρασιν V v. 10. αἱ ὄψεις] ras. 3 litt. v 11 προσπίπτωσιν (pr.)] -πτω- supra scr. m. 1 v; praeterea supra add. β;
footnote 6. προσπίπτειεν v. 7 καί] del. m. rec. V. 12. διαστήμασι m. rec. V, Post κειμένων add. ἀνίσοις m. rec. 13. ἔγγειον V, corr. m. rec 14 ὁρώμεναν m. rec. V. 15. ἔγγειον V, corr. m. rec 18 αἱ] om. p. 19. τό] corr. ex
footnote 1. Γ&#8736; — 2. τό] add. m. 2 v. 2. φημὶ δή] λέγω v. 7. πρός — 8. ὁρᾶται] om. p. 8. ἐκείνω v, sed corr 10. γενομένου v, V, sed corr. m. rec. 13 διαστημάτων] μεγεθῶν m. rec. V. 16. Post ἴσα add μεγέθη m. rec. V. 22. Post
footnote 10. &#8736;Ζ] Ζ corr. in E m. rec. V. 11. Ante ὄμμα add. τὰ δὲ παράλληλα τὰ ΞΛ, ΠΝ, Β&#8736; V. 12. ἔγγειον V. 14. ΚΞ] Ξ corr. in Ζ m. rec. V; item lin. 15, 16, 17. 16. μεῖζον v. ΞΚΛ] ΞΛ v. γωνία] in ras. v. ὑπό (alt.)]
footnote 2. ΚΞ] corr ex ΚΖ m. rec V 3. Ante κάθετος add. ἡ ΚΜ m. rec. V, idem post ἐστίν (lin. 4) m. 2 v. 4. ΜΛ] supra scr. Ζ m. 2 v. 6. ἐστί ] ἐστίν V v. 8 μεῖζον v. 9. μεῖζον v, corr. m 2. 10. μεῖζον — 11. ΗΞ] om V v. 11. Ζ Μ] ΞΝ p ΗΞ] ΠΞ p. 13. καὶ ὅτῳ] om. V v. 14. τὰ μεγέθη] om. V; καὶ οὕτω τὰ μεγέθη add m. rec. 17. Supra. ἀλλήλων add. μὴ ἐφεξῆς ἀλλήλοις m. 2 v. Post τεθέντα add. καὶ ἄνισον διεστηκότα τοῦ ὄμματος m. 2 v. 21. μεῖζον v. 22. μεῖζον v. 23. Post μεγέθη add. τὰ ἄρα ἴσα μεγέθη τὰ ἐπὶ τῆς αὐτῆς εὐθείας ὄντα πορρώτερον ἀλλήλων τεθέντα ἄνισα φαίνεται m. rec. V
footnote 2. ἄνισον] καὶ ἄνισον v; supra add καὶ παράλληλα m rec V, παράλληλα m. 2 v Supra οὐκ add ἀπὸ τῶν ὀμμάτων m. 2 v. 3 ἀποστήμασιν] corr. in διαστήμασιν m rec. V.
footnote 7. ἑστὼς μετέωρον] m. rec. V. 10 γενομένου V p. 15. ι΄] V, ια΄ mut. in ιβ΄ m. rec. 16. ἐπιπέδον κειμένων V (α, β, ω m. rec.), κειμένων ἐπιπέδων vp. 17. φανεῖται] φαίνεται vp, m. rec V. 20. Β&#8736;] &#8736; in ras. m. 2 v. ΒΚ  (pr.)
footnote 1. ἐπεὶ οὖν] bis p. 2. τό  (pr.)] ἐστι τό V. 4. ἡ &#8736;Γ] m. 2 p. 6. Ζ&#8736;] &#8736;Ζ V. 7. ΖΚ] Κ im ras. m. 2 v. 8. Post φαίνεται add. τῶν ἄρα κάτω τοῦ (corr. ex τῶν) ὄμματος κειμένων καὶ τὰ ἐξῆς V. Mg. m. 1 V: ??. ἐκ δὴ τούτου φανερόν ἐστι (ὅτι add m. rec.) τὰ ἐπίπεδα ἐκ τοῦ μέσου θεωρούμενα κοῖλα φαίνεται. τεθείσης γὰρ τῆς ὄψεως κατὰ μέσον τοῦ ἐπιπέδου ἐν τῷ μετεώρω φανερὸν τὸ λεγόμενον προσεκβληθέντος τοῦ ΓΚ ἐπιπέδου ἐπὶ τὰ ἀριστερά, ὥστε καὶ εἰς τὰ δεξιὰ τὰ πόρρω προσέχειν καὶ εἰς τὰ ἀριστερά. εἰ γὰρ μετεωρότερα τὰ ἄκρα, δῆλον, ὅτι τὸ μέσον κοῖλον. 9. ια΄] mut. in ιβʹ m.
footnote 3. δέ] δʼ p 7. αἱ] λέγω ὅτι αἱ v. 8. ΚΗ] ΚΝ V. 9. Η]| Ν V. 12. τοὔμπροσθε V. ἐχώντων v, sed corr. 13. δεξιοῖς — 14 τοῖς] om. v. 18. ΚΛ] om. v.
footnote 3. Β] m. rec V. 7. &#8736; — τό] om. p v ὥστε καί] m. 1 V, καὶ διὰ τοῦτο m. rec 9. Post ΚΝ add τῶν ἄρα ἴσων μεγεθῶν καὶ τὰ ἑξῆς m. rec V 13 ἀπιόντος] -ον- in ras. V 17 τῷ (pr.)] τό v ἴσον] m rec V, comp m. 1.
footnote 4. δή] δέ v προσπιπτέτω] -σπ- in ras. V. 7. ἔλαττον v 11 μεγέθη v. ὄντως v, sed corr 15. ΘΗ] ΘΗ V v ΘΝ p 16. ΓΘ] in ras m. 1 V. 23. ΘΗ] ΘΗ V v.
footnote 2. ἐνήρμοσται v. Ante &#8736; add. πρὸς τῷ m. rec. V. 4 ΓΒ] Β p. 8. ἐστιν V v. 9 σκιά· γνώριμον] in ras. m 1 V Post ὕψος add. τὸ ἄρα δοθὲν ὕψος ἔγνωσται πόσον ἐστί m rec. V. 13. ἐστί p. 15. Supra &#8736;Θ add. τῷ κατόπτρο
footnote 3. ἐστίν] ἐστί V p 4 KB] corr ex Κ v. προσπιπτέτο πιπτέτο v. 5 τὸ βάθος] mut in τὸ πέρας τοῦ βάθους m. rec V. 6. Supra παρά add ἤτοι παράλληλος m. rec. V.
footnote 4. φανεῖται] cor. ex φαίνεται m. 1 V. 5. τό] τῷ v. 6. ὄν] in ras. m. 1 V. 9. ἐπεί ] ἐπί v, V, sed corr. 12. τὰ δέ] mut. in ἀλλὰ μόνα τά m. rec. V. 17. ἀεί p. 19. ἔστω (alt.)] del. m. rec. V. 21. τό] im ras. V. 22. ΓΚ&#8736;] cor. ex &#8736; m. rec. V. 23. ποιείτο v. τόν] τό v. Γ&#8736;ΛΝ] Ν mut. in Ζ m. rec. V, Ζ add. m. 2 p. διάμετρον] m. rec. V( 25. ΒΛ] corr. ex Β&#8736; V.
footnote 5. Θ] e corr. m 1 v. 8. εἰς τό] εἰς v. 9 φέ-] in ras. V. Post ἕν add. σημεῖον p m. rec. V. 13. ὅ γε] mut. in καί m. rec V. ἐστιν] mut. in ἔσται m. rec. V. τό — 15. ἡμισφαιρίου ] mut. in ἡ γὰρ ΖΛ διάμετρος οὖσα τοῦ κύκλου τοῦ διαιροῦντος τὸ ὁρώμενον τῆς σφαίρας ἐλάττων ἐστὶ τῆς &#8736;Γ διαμέτρου οὔσης τῆς σφαίρας m. rec. V. 13 ΖΛ] ΖΝ V, Ν supra scr. m. 2 p. 14. ἐστι p. περιεχόμενον] ὁρώμενον v et supra add. m. 1 p. 17. ἔγγειον V 22. &#8736;Ν]
footnote 4. ΡΚ] p, ΚΡ 8. ὁρ-] in ras. m. 1 V. 9. τὸ. ΝΖΛ (pr)) τὸν Ζ Λ v; τὸ ΝΖ, add. ΣΛ m. 2, p. τὸ ΝΖΛ (alt.)] τὸν ΖΛ v; τὸ ΝΖ Λ, supra add Σ m. 2, p. 10 ἐστιν (pr.)] ἐστι p. μεῖζον v. P] e corr p. 13 ΝΖΛ]
footnote 5. ἡμισφαίριον v, p, sed corr. 10 ποιείτο v. 11 ἀκτῖνος v, sed corr. ἕν] ὃν σημεῖον v, σημεῖον add. m. rec. V.
footnote 4. ἐπειδήπερ — 6. διάμετρος] mut. m. rec. in ἐπειδὴ ἐλάσσων ἐστὶν ἡ BΓ τῆς διαμέτρου τῆς σφαίρας V. 19. τοῦ] corr
footnote 1. ἐπιφάνιον v. 2. Ante δείξομεν ins. τὸ αὐτὸ συμβαῖνον m. rec. V. 3. ἡμίσεως V, sed. corr. 5. δέ ] del. m. rec V. ἔγγειον V. 9 Κ (alt.)] e corr m. 1 V. 12. διά — 14. ὁραθήσεται] mg. m. 2 V, om v. 14. ἢ] om. p. 20. Post ΝΖ Λ ras. 1 litt V. μεῖζον v. 21. Ante Φ ins. πρὸς τῷ m. rec. V. Ante Β ins. πρὸς τῷ m. rec. V.
footnote 8. &#8736;] &#8736; ὡς ἡμικύκλου v. 9. ΒΖ] corr. ex &#8736;Ζ m. 1 V. 10. Post τοῦ ins. Β m. rec. V. 11. ΖΡ&#8736;] Ζ&#8736; v. 12. ΝΡΛ (alt.)] Ν postea ins. V. ἐστι V p. 13. ἡμικυκλίου pr. κ in ras. V. 15. ἐν τῇ] in ras. m. 1 V. 18. δέ| del. m. rec. V. ἔγγειον V, sed corr. m. rec. 22. ἐπί] in ras. m. 1 V. 23. ἐπιζεύχθω V, sed corr. 24. ΓΚΒ] ΚΓΒ V
footnote 5. καὶ αἱ] corr. ex καί m. 2 V 7 ΖΦ&#8736;] Ζ ΦΛ pv e corr. V. 8. μεῖζον v. 9. τῷ] τό pv. 11. κόνου V, sed corr. 14. ἐπιφανίας v. 15 ἀχθεισῶν] -ει- e corr. V. 16 Ante ἐπίπεδα ras. 2 litt V 19 παραλλήλου] comp. pv, omnibus litteris scriptum add. m. rec. V 24 &#8736;, Γ] Γ, &#8736; p. 25. αἱ ] im ras. V.
footnote 1. ἐκεβλήσθω, supra scr. Β, V. 3. τὰ ἐπίπεδα] supra scr V, renou. m rec. 5 ἄν] δʼ ἄν V vp. 8 Ζ] postea ins. m. 1 V. 9. Supra παρά (pr.) add ἤτοι παράλληλος m rec. V. Supra παρά (alt.) add. παράλληλος m. rec. V. 10 ΓΚ] in. ras. V. 13 ἐστι p 16. ΚΓ] ΚΝ p 17 τῷ] corr. ex τό m. 1 18 ἄν] corr ex α m 2 V. 25. ὁ] ὁ περὶ τήν V.
footnote 2. ὀφθήσεται p, ὠφθήσεται v. ὡρώμενον v, sed corr 3. Σ] om. v. 5. Λ] corr. ex &#8736; m. 2 V. 9. τῷ (sec.)] τό v. τῷ (tert.)] τό pv, V, corr m. rec. 10 τῷ Λ τῷ] τὸ Λ τό v. τῷ (tert.)] τό pv 11. τῷ] τό v σημείου v, V, sed. corr. ὄντως v. 12. ἐλάσσων V, sed corr. 15. ἀπὸ τοῦ κέντρου] in ras. m. 1 V. 19 τῷ] τό v. 20. τοῦ] om. p 23. Ante B Κ (alt.) eras. Γ V. ΚΓ] corr. ex Κ&#8736; m. rec. V.
footnote 2 Σ] Σ γωνίᾳ p. 3. BΓ] corr. ex Β &#8736; m. rec. V. 5. Β&#8736;] corr. ex BΓ m. rec. V. 10. ΓΒ Α] ΓΑΒ p. 11. ἐστί p. 17. Post ἐπιπέδῳ add, τοῦ κύκλου m. rec. V. 18. Ante αἱ add. καὶ οὕτως m. rec. V. 19 Post ἔστω
footnote 7. ἴση] εἰσι v. 11. ἐστί p. &#8736;ΖΑ] ΕΖΑ p. 14. ΕΖΑ]  Ζ e corr. V. ὑπό] ἀπό v. 15. &#8736;ΖΒ]  &#8736;ΒΖ V, corr.
footnote 4. μείζων (pr.)] μεῖζον v. μείζων (alt.)] μεῖζον v, μεί- in ras. V. 6. Post τοῖς add. προτέροις m. rec. V. ἀποδείκνυται] mut. in ἀποδέδεικται m. rec. V. 7. μείζωνος v, sed corr. 11. λζ΄ V p v. κέντρον] m. rec. V, comp. m. 1. 12. ἀγωμένη V, sed corr. 16. ποιουσῶν] - σῶν e corr. m. rec. V. Post τῇ ras. 1 litt. V. 17. τῶν] del. m. rec V, seq. ras. 2 litt. v. 18. τήν] τό v. 22 μεῖζον v. ΑΓ]
footnote 1. τῶν (utrumque)] del. m. rec. V. ἐστιν V v. 3 Post τῇ ras. 1 litt. V. 4. τῶν] del. m. rec. V 5. λη΄ V p v, del. in v. Post ὅτι ins. δέ m. rec. V. ἐστιν V v. 6. ἐστίν V v. 8. τῶν] corr. ex. τῶ m. 2 V. 9 ἐκβαλλόμενον
footnote 3. πεποιείσθω v. 5. Α &#8736;] corr. ex Α Β m. 1 V. 6 ἐστίν V v. 7. ΒΓΑ] Α corr. ex &#8736; m. rec. V. 9. μεῖζον 10. Ζ ΑΒ] Β e corr. m. rec V 11 μ΄ V p v, del. v. Ant. δύο eras. αἱ V. 17. ἐστιν V v. 20. Post σημείου add. in media linea — V v. 23. ΗΘ] corr. ex. ΕΘ V. 24 Pos ΛΜ del. πρὸς ὀρθάς p.
footnote 3. ἀρχόμενον V, corr. m. rec. 4 μείζων] μεῖζον v. 6. ΞΛ.] ΖΛ p. τῷ] im. ras. V, τό v. 7. ἐστίν V v. 9. ἐκκείσθω] ἔτι κείσθω e corr. p. ΖΗ] e corr. v. 11. ΛΟ] Ο e corr. v. ΜΟ] corr. ex. ΜΘ v. περιγράφθω V. sed corr. 12 Post τό (pr.) 1 litt. eras. v. 13. ΛΟΜ] Ο e corr. v.
footnote 1. μεῖζον v. 2. μεῖζον v. 3. εὐθείας] γωνίας V, εὐθείας γωνίας p v. 4. μ΄ V v, μαʹ p. 7. μεῖζον v. 11. ἐπιζευχθῆσα v. 18. ἐστίν V v. 19. τῷ] τό v. 22. ἡ] om. v. 24. τμῆμα] τμῆμα κύκλου p. 25. ἡ] supra scr. m. rec. ἐστίν V v.
footnote 3. ἡ (pr.)] supra scr. m. 2 V. ἡ (alt.)]  addidi: om. V p v. 8. φανήσεται] νήσεται in ras. m. 1 V. 11. ΑΕΒ] ΛΕΒ p v (Α deformatum est im V). 13. λζ΄] μα΄ V v, μβ p. 15 παρεσπαμένοι V. 16. διάμε-] in ras. m. 1 V. 18. ᾖ] corr. ex εἰ m 1 v. τῇ] corr. ex τοῦ V.
footnote 1. λη΄] μβ΄ V v, μγ΄ p. 3. τό] τῷ v. τοῦ — 4. περι-]  dimid. eras. V. 4. Post περιφερείας add. κέντρον ἔχοντος τὸ ὄμμα p. 6. μετεορώτερον V, μετέωρον p; μετεωρώτερον v, sed corr. 8. κεντρῳ] comp. V v. 10. περιφερείας] comp. V v. 12. τήν] om. v. 13. κέντρου] in ras. m. rec. V. 16. Ante ἀχθῇ ras. 2 litt. V. ἐπί]  supra scr. m. 1 p. 17 μεγέθη v, sed corr. μετακεινῆται V, sed corr.; μετακινεῖται v, p, sed corr. 19. λθ΄ ] μγ΄ V v, μδ΄ p. 21. ἐπιπέδῳ] om. v.
footnote 5. τούτω v. ἐστι p. 6. τό] corr. ex τῷ m. rec. V. 9. μʹ] μεʹ p, μδ΄ V v. 11. δέ] δὲ τὸ (τω v) ὁρώμενον vp. 12. Post ὀφθήσεται add. κατὰ παράλληλον θέσιν τῇ ἐξ ἀρχῆς μεταβαῖνον mg. m. 2 v. 14. σημείου v. 17 Post ποτέ (pr.) del. μέν p. μεῖζον v. 18. ἤτοι δή] ἢ δέ e corr. v, ἤτοι
footnote 3. -ς με-] in ras. V. 4. δέ] δή v. 7. πρός] supra scr. p. γωνίας p. 8. ἀλλά — 9. ἐστιν] om. v. 9. ἐστι p. 10. ἐστίν V v. 11. ἐστι p. δεῖ] in ras, V, corr. ex δή m. 2 v. 12. ὅτι] om. v, ὡς comp. m. 2. ἐλάσσων V, corr. m. rec. 13. δεῖ] corr. ex δή m. 2 v. ἔλασσον v. 14 ἐστίν V v. 17. ἔλασσον v. ἐστίν V v. 18. τῷ] corr. ex τό m. 2 v 19. τό (pr.)] corr. ex τῷ m. 2 v. τό (tert.)] τῷ v. 22. μέν] del. m. 2 v. 24. ἐστίν V v.
footnote 5. ἐστιν Vv. 7. διαγώνιαι p. 11. ΚΝΡ] corr. ex Κ Ν m. 2 v. 13. ἐστίν] ἐστί p. 14. ἡ δέ — 15. ΑΕΒ] mg. m. 2 v (κείμενον). 15. ἴση] om. v. ἐλάσσων ἄρα] ὥστε καί v. ΑΕΒ] ΑΕΒ ἐλάσσων ἐστί v. 17. ἐλάσσων V, sed
footnote 3. ΘΝ&#8736;] mut in ΘΝΑ m. rec. V, ΘΝ p add. &#8736; m. 2 v. ΘΝ] corr. ex m. rec V. &#8736;Ο] ΛΟ V. 4 &#8736;Ο] ΛΟ V. 5. Θ&#8736;] &#8736;Θ p, Θ V. 6 τοῖς] τῇ p. ἡ μέν] om. v. 7 ΘΝ&#8736;] ΘΝ V. ἐστίν Vv. 8. ἐστίν Vv. 10. ΘΝ&#8736;] ΘΝΛ V. καί] om. Vv. 14 ἐλάσσων p.
footnote 2. ὑπό (sec.)] ὑ- in ras. m. 1 V. 3 μείζων (utrumque)] μεῖζον v. ΓΕΑ] τὴν v (inter Γ Α ras. 1 litt.). 9. ὑπὸ &#8736;ΕΖ] &#8736;ΕΖ p. 12. μα΄] μη΄ p; μζ΄ V v m. 1; με΄ v m. 2. 13. μένωντος v, sed corr. 15. Post Ζ eras. &#8736; V. 17. ΖΒΓ] ΒΖΓ p. 18. ἐπί] ἐ- im extr. lin. v. 21. τᾖ] τῆς V. περιφερείᾳ] -σ add. m. rec. V. 22. Post ἡ eras. η V. τῇ] τῆς p. γωνίᾳ] γωνίας p. ἴσον ἄρα φαίνεται τὰ δὲ ὑπὸ ἴσων γωνιῶν ὁρώμενα ἴσα φαίνεται v, corr. m. 2 litteris αβγ adpositis. ὑπό] ὑπὸ τῶν p. 23. τό] τῷ v. Γ&#8736;] Γ supra scr. m. 1 V.
footnote 1. μβ΄] μθ΄ V p, v m. 1; μϚ΄ v m. 2. 2 -θιστα-] in, ras. V. 11. τοῦ] mut in τό m. rec. V. μεταπιπτέτωσαι V,
footnote 2. εἰσι p. 3. Ante Β ras. 1 litt V. ἄρα] in ras. V. 4. ἐστί p. 5 ἐπί]  supra scr. m. 1 V Β] e corr. V. 6. μδ΄] να΄ V p, v m. 1; μη΄ v m. 2. 7. ᾖ] supra scr. V. 10. δὲ ἀνήχθω] διανοίχθω v. 13. Α] postea ins. V. 15. ΚΝ] Κ e corr. m. rec. V. 16. τοῦ] mut. in τό m. rec V.
footnote 1. μεʹ] νβ΄ V, v m. 1; μθ΄  v m. 2; νγʹ p. 6. μείζων v. 7. ἐστίν v. 8. μείζονι] μείζωνι v, sed corr. 9 μείζων] μεῖζον v. 12 μϛʹ] νδʹ p; νγ΄ V v m. 1; ν΄ v m. 2. 13. ἴσα] supra scr. m re.c V. 15 μεῖζον v.
footnote 2. φαίνειτο v, corr. m. 1. τις] in ras. m. 1 V. 4. μζʹ νεʹ p; νδ΄ V, m. 1 v; να΄ m. 2 v. 6. συντιθέντα p. 7. μεῖζον v
footnote 3. ἐστίν v. 6. μθʹ] νζʹ p; νϚ΄ V, m. 1 v; νγʹ m. rec. v. 8. τελευτέον V. 13. Μ] supra scr. m. 1 V. 14. μετεορωτάτη V, corr. m. rec.; μετεοροτάτη v. 23. δόξει] mg. m. I V.
footnote 1. νʹ] νηʹ p; νζ΄ V, m. 1 v; νδ΄ m. 2 v. 2. συμπαραφέρειται v, corr. m. 1. 3. τό] corr. ex τῷ V. τῷ] τό v 4. φερόμενοι V, sed corr. 5 φαίρεσθαι v. 9. ἰσωταχῶς V, sed corr. m 1. 11. ΚΒ] Β Κ seq. lac.1 litt. v. 14. ΓΚ
footnote 1. νβ΄] ξ΄ p: νθ΄ V, m. 1 v; νϚ΄ m. 2 v. 2 ἔγγειον V. 3. ηὐξεῖσθαι V, sed corr. 6 ἔγγειον V. 9 Ante &#8736;Γ ras. 2 litt. v. 10 μεῖζον v. 11. μειζώνων V, sed corr.
footnote 5. μέρεσιν V v. 7 τὸ δέ] corr. ex τοῦ δέ V. 11. νε ξγʹ p, ξβ΄ V. νθ΄ im ras. m. 2 v. 12. ἔγγειον V. 14 ΒΓ p. 15. ηὐξείσθω v, sed corr. 16. μεῖζον v. 16 ἔγγιον (pr.)] ἔγγειον V, μείζονα p, om. v. φαίνεται] om.
footnote 2. ἄν] scripsi: om. V v p. 3. ἔγγειον V. 5. νζ΄] ξεʹ p ξδ΄ V, m. 1 v; ξα΄ m. 2 v. 8. ἐπὶ δέ] ἐπεὶ δή v. ταύτης αὐ seq. lac. 3 litt. v. 9 ἴσοι p. 15. Β&#8736;] Β e corr.
