@node
@author=Lucian of Samosata
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=A. M. Harmon
@filename=tlg0062.tlg041.1st1K-grc1
@funder=Harvard Library Arcadia Fund
@principal=Gregory Crane
@publicationStmt=Harvard College Library, tlg0062.tlg041.1st1K-grc1.xml.
@respStmt=Digital Divide Data, Corrected and encoded the text, Gregory Crane, Editor-in-Chief, Perseus Digital Library, Matt Munson, Project Manager (University of Leipzig), Annette Gessner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig) 2015 - 2017, Bruce Robertson, Technical Advisor
@sourceDesc=Lucian, A. M. Harmon, Lucian of Samosata, Harvard University Press, Cambridge, MA, 1961, 4, The Internet Archive.
@sponsor=University of Leipzig
@title=De Syria dea, The Goddesse of Surrye
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:52:29Z

7416	footnote Available in photographs, ΓΝ. 1 Hierapolis, or better, in accordance with the coins, Hieropolis. It is N.W of Aleppo, on the main road into Mesopotamia, 15 Roman miles from the crossing of the Euphrates, and by road about 116 Roman milas from Lucian's birthplace, Samosata. Its Syrian name was Mabog, (properly Manbog, i.e. “spring.” according to Baudissin, Studien, ii, 159), in Greek, Bambyce. It was dubbed Hieropolis in the time of Soleucus Nicator (Ael. N. H. 12, 2), but the old name persisted (Manbij; le Strunge, Palestiane under the Moslems,
footnote 1 In Astrology, Lucian similarly credits the Egyptians with priority over the Chaldaeans in the study of the stars. In both cases his view, surprising in a Syrian, was the common one of his time, to be found, for instance, in Diodorus (1,9,6). 2 The dod was Melkart. Herodotus was told by the priests there that the cult was established when the city
footnote 1 The coins are described in Head, Historia Nummorum 2nd ed., pp. 797 sq. The temple itself contained, in later days at least, a painting of the Europa episode (Achilles Tatius 1, 1). The story was also localized at Tyre, where the house of Agenor and the bower of Europe were shown (Arrian, Anab. 2, 24, 2; Nonnus, Dionys. 40, 353 sqq.) and where in the eighth century (Malalas, p. 31) the people still mourned the abduction in a feast called the κακὴ ὀψινή. The name Europe is considered Greek; whether this particular myth is Cretan or Phoenician in origin the evidence does not seem anfficient to determine. 2 This cult was at Heliopolis (Baalbek). The god, who appears to have been originally Hadad but to have undergone syncrisis with the sun-god and with the Syrian “Apollo,” was worshipped far and wide as Jupiter Heliopolitanus.
footnote 1 καὶ τοῦτο —τὸ καὶ N: not in ΓΕ. In both old MSS. the first hand left a space in which these words were entered long afterward. 1 Lucian abridges his account of the rites because they were familiar. 1 see no reason to suppose that they differed essentially from the Alexandrian rites as described by Theocritus (15 end). From him we learn that Adonis comes to life for but a day, during which he is couched with the goddess in the temple. Next morning the women carry him to the sea-shore, and (cf. scholion) commit him to the waves. Lucianʼs phrase ἐς τὸν ἠέρα πέμπουσι, which has been curiously interpreted, is to my mind equivalent to ἕξω οἰσεῦμες in Theocritus and the usual ἐκκομίζονσι. 2 See Frazer i, 36 sqq., and the comment of How and Wells on herodotus 1, 199. Note also the apocryphal Epistle of Jeremiah 42; and on the “hire,” Deuteronomy 23, 18.
footnote 1 The Adonis is the present Νahr Ibrahim, a short distance S. of Byblos. “I have crossed it on Easter day when it was turbid and ruddy with the rich red sandstone soil from Lebanon” (C. R. Conder, Palstine, p. 206; cf. Frazer i, 225), A similar discoloration of certain unnamed rivers and springs is implied in the tale of Philo of Byblos that Uranus
footnote 1 At Aphaca, between Byblos and Baalbek, at the head of the Adonis, where Adon was buried and Baalat died of grief Down to the fifth century a bright light appearing in the sky near the temple summoned the worshippers at set times, and an artificial pond gave omens; offerings were thrown into it, which sank if the goddess was favourable or floated if she was adverse (Zosiamus i, 58; cf. Socrates 1, 18), The site is eloquently described by Frazer, i, 28, and pictured
footnote 1 Σισύθεα Buttmann. 1 Deucalion in the röle of a Scythian is odd. Hence Buttamann, rightly recognising that the tale is close akin to
footnote 1 In spite of Lucianʼs repeated assurance, the story is more Semitic than Greek. On the West Semitic origin of the flood-story, see Clay, where also a translation of the Babylonian tale according to Berossus may be found (p. 82 sq). 2 At Gezer, not far from Jerusalem, “there is a living tradition that the waters of the flood burst forth in the neighbourhood” (Cook, p., 107, Likewise at Athens, within the enclosure of Olympian Zens, in the precinet of Olympian
footnote chthonic, and so was the water-pouring there (Cleidemus in Athenaeus 5, p. 410A). At Hieropolis the object was to quell evil spirits, according to Melito. “But touching Nebo. which is in Mabug, why should I write to you ; for lo ! all the priests which are in Mabug know that it is the image of Orpheus, a Thracian Magus. And Hadran (i.e. Hadaranes, a double of Hadad) is the image of Zaradusht, a Persian Magus, because both of these Magi practised Magism to a well which is in a wood in Mabug, in which was an unclean spirit, and it committed violence and attacked the passage of every one who was passing by in all that place in which now the fortress of Mabug is located ; and these same Magi charged Simi, the daughter of Hadad (cf. c. 33), that she should draw water from the sea, and cast it into the well, in order that the spirits should not come up,” etc. (Cureton, Spicil. Syr. 44 sq.) Early modern travellers have seen seawater poured into a brook (Baudissin, Studien, ii, p. 181), and it is perhaps significant that nowadays the Jâns are angry if water is spilled on the hearth (Baldensperger, Immovable East, p. 85). Cf. Baudissin, p. 437, 3. 1 A legend of Ascalon made Semiramis the daughter of Derceto by a Syrian youth with whom Aphrodite (i.e. Astarte) made Derceto fall in love. In her grief and shame,
footnote 1 See cc. 45, 54, with the notes thereon. 2 On the transformation of Semiramis into a dove, see Athenagoras, Legat, pro Christ. 76 (Ctesiae Fragmenta ed. Müller, p. 17) ; Diodorus 2, 20, 2. Diodorus (2, 4, 6; cf. Hesychius) says that the name Semiramis is derived from the word for dove in the Syrian dialect. At all events the similarity of the Assyrian word summatu (dove) helps to account for her introduction into these stories (Lehmann-Haupt, Roscher's Lexikon, s. v. Semiramis, p. 694). 3 Lucian's scepticism is unjustified. Pliny (5, 81) and Strabo (16, p. 785) were better informed. Atargatis is the Greek version of ‘Atar-‘ata; Derceto is the Greek version
footnote 1 ἐπικνέεται Lehmann: ἐπικέεται ΓΕ: ἀπικέεται Ν.
footnote 1 τόδε A.M.H.: τάδε MSS. 2 μὲν Fritzsche: μιν MSS. 3 μὴ—γεγενημένον: first Aldine; ; not in MSS. ΓΕ show lacunae ; the space in Γ is about 31 letters. 1 Phallic pillars, farther described below, cc. 28–29. The inscription is much too pointed to be genuine ; it is a hoax like that in the True Story 1, 7 (vol. i, p. 255). Pillars were an ordinary feature of Semitic “high places,” both of wood (asherim) and of stone (masseboth); see Frazer, Folklore, iii, sqq. In the case of the asherim I know of  no direct evidence that they were phallic, but the masseboth, many of which stilI survive, are sometimes clearly of that nature (Cook, 14, 28 ; see also le Strange, Palestine under the Moslems, p. 294, for a curious survival of this significance). The pillars at Hieropolis were made of wood, since cleats were
footnote 1 προξενέειν Koene, Schaefer: προξενέεις N: lacuna in ΓΕ.
footnote 1 Compare the famous story in Herodotus (3, 119) of the wife of Intaphrenes, who preferred brother to husband and sons. 2 The known facts are that Seleucus made Antiochus joint-ruler in 293 B.C.; that the marriage of Stratonice to Antiochus may have taken place at that time, but the date is not known ; and that in 281, on becoming master of the whole realm of Alexander through the defeat of Lysimachus, he planned to entrust, and perhaps actually did entrust, all
footnote 1 The name Kombabos, which does not occur elsewhere in Greek, has been identified as that of the opponent of Gilgamesh in the Gilgamesh-Epic, Hu(m)-ba-ba (Schrader-Zimmern, p. 570, and note 2). Clay has shown (pp. 49–53) that this name is not Elamite, but Amorited or West Semitic; he holds that it was borne by a historical personage who lived in a cedar district of the West and humiliated Babylonia at the time of Gilgamesh, about 4000 B.C. However that may be, Kombabos is Humbaba, and in this story, which is the temple-legend, the name of Kombabos is the
footnote 1 αἰδέετο Lehmann: ἐδέετο Γ, ἠδέετο N.
footnote 1 αἴτεε Koene: ἀΰτεε ΓΕ, ἄτεε N. 2 ἀμβώσας Valckenaer: θαμβώσας MSS. 3 οὕτως—ἄνδρων N: lacuna in ΓΕ, in which the supplement (a conjecture) has been entered by a late hand.
footnote 1 Hermocles of Rhodes is known only from this passage; his name must have been preserved by an inscription on the statue, which we may be sure was the restoration of an
footnote 1 Since Κombabos bears a very ancient name, since the temple-story ascribes the origin of the Galli to him, not to Attis, and since Attis does not figure at all in the worship as described by Lucian, the Galli can hardly be a Seleucid importation from Phrygia (Cumont) ; in that case Attis would have been imported also. Meyer, who believes the cult ancient here, but Hittite-Anatolian in its origin, finds evidence of Attis-worship in the name Atargatis (Atar-Ata), which he interprets as the Astarte of Attis; i.e., the goddess that is characterized by the worship of Attis (Gesch., p. 650). This view not only leaves Kombabos out of account, but does not reckon with the fact that the deity Ata was often, if not always, thought of as feminine(cf. Baudissin, p. 158, 1).
footnote 1 ἕνα φαλλόν N : lacuna in ΓΕ, in which these words are entered in a late hand. 2 μικρῇ Kuster: μακρῇ MSS. 1 This is evidently the true reason, and not either of the two that follow, That the gods can hear better from near at hand is good Semitic paychology : but the use of a pillar instead of a mountain-top, or a ziggurat, or the roof of a house, appears otherwise unevidenced in early Syria. “ It was perhaps the memory of this strange rite (not however
footnote 1 ἐχῖνον Α.Μ.Η . : ἐκεῖνον ΓΕ. Ν reads: οἱ δὲ χαλκὸν κομίζουσιν, εἴτʼ ἀφέντες ἐκείνου πρόσθε κείμενα ἀπιᾶσι, etc. Γhis Byzantine correction has been followed in all editions since the princeps, which reads as ΓΕ. 2 γῆς Longolius τῆς MSS. 1 Very likely the bronze sistrum ; fragments of these have been found in Phoenicia (C00k 45). The object was to scare
footnote 1 The other name, the right one, is Hadad, or Ranmman, gd of the lightning and of the waters (rains and floods), known from very early times to the Semites, to the Mitani folk under the name of Teshub, and to the Hittites, upon whose monuments he is conspicuous, with the axe and the thunderbolt for attributes. He underlies not only Jupiter Heliopolitanus but Jupiter Dolichenus. Consequently his ideutification here also with Jupiter was inevitable, and it is chiefly in virtue of this that his spouse was identified with Juno (cf. Dussaud, Pauly-Wissowa, s.ν., and SchraderZimmern, p. 447). 2 Lucianʼs statement is borne out by the coins; see Head, Hist. Numm., 2nd ed., p. 777. Atargatis is seen sometimes
footnote 1 Compare Plutarch, Crassus, 17, 6 : “ And the first warning sign came to him from this very goddess, whom some call Venus, others Juno, while others (cf. Cornutus ) atill regard her as the natural cause which supplies from moisture the beginnings and seeds of everything, and points out to mankind the source of all blessings. For as they
footnote 1 ἐσορέη du Soul, Edd. 2 ἕδος Schaefer: εἶδας MSS. 1 Compare Herodotus 2, 44, on the great emerald pillar in the temple of Melkart at Tyre ; also Mandeville, pp. 239 276, ed. Halliwell, on luminous stones in the possession of the Emperor of Cathay and of PresterJohn. Diodorus (3,39, 8) credita the topaz with this power. 2 It is clear from the passage in Melito quoted above that Lucian's “ token (semeion) rests upon a misunderstanding
footnote 1 Compare Meyer, Gesch., p, 192, on the lack of images and temples in the Egyptian worship of Ra. Apollo is Nebo, whose statue, bearded and clothed, erected at Κelach by Adad-Nirari III, son of Semiramis, may be seen at the British Museum (illustrated in Roscher, Leæikon, l, p. 49). The inscription that it bears implores long life for Adad-Nirari, king of Assyria, and for Sammuramat, the Lady of the Palace. Nebo was highly favoured
footnote 1 ἔρονται Fritzsche : ἔσονται MSS. 1 At Heliopolis, Jupiter Heliopolitanus, who had absorbed “ Apollo,'' gave oracles in much the same way (Macrobins, Saturn, 1, 23. 13 Sqq.). So also did Ammon at his great Libyan shrine (Siwa); the description of the procedure when Alexander consulted it (Diodorus, 17, 5Ο-51), somewhat blind in itself, is clear in the light of these parallels. The ikon of the yirgin at Phaneromene, Salamis, is credited with similar powers to-day (Capps), and for a parallel in modern Sierra Leone, see Frazer, Folklore, iii, p. 323.
footnote 1 σνμφοραὶ Ν, du Soul: συμφορή ΓΕ.
footnote 1 Sacred animals were a common feature of temple closes in Greece (Gardner-Jevons, Manual, p. 188), Plato introduces sacred bulls into his utopian Atlantis, Critias, 119 D.
footnote 1 ὑφεστεὼς Gesner: ἐφεστεὼς MSS. 1 “ At Hierapolis in Syria, in the lake of Venus, they (the fish) obey the spoken commands of the aeditui; when called, they come with their golden ornaments ; they show affection and let themselves be tickled (adulantes scalpuntur), and they open their mouths for people to put in their hands᾿᾿ (Pliny, Nat. Hist. 32, 17). According to Aelian (Nat. Hist. 12, 2) they swam in regular formation, and had leaders. The pond still exists, but the fish are no more (Cumont, Etudes Syriennes, p. 36 sq.). There were similar ponds at
footnote 1 “ The rite of descending to the water (κατάβασις, Semitic yerid) was common all over Syria. . . . Its purpose was to revive the water-sources and bring rain᾿᾿ (Dussaud, PaulyWissowa ς.ν. Hadad). Why the fish should need protection
footnote 1 ὄργια du Soul : ὅρκτα MSS. 2 τὸ A. M. H.: τὰ MSS. 1 Baudissin (176, 3) knows no closer parallel than the Continental Mai-feste, and thinks that, if the Syrian custom came down from the North, a community of origin is possible. Somewhat similar is the practice at Tarsos of erecting a pyre, setting on it an image of the god Sandan, and then burning it up. Frazer (i, 126, 146) associates the two customs and ascribes their origin to the immolation of a
footnote 1 Compare Joshua 8, 29, and for the modern practice, Baldensperger, 16, 1. Perhaps originally the Gallus was stoned to death at the expiration of a certain time. 2 On the pollution of death, see Leviticus 21, 1-3 ; Ezekiel 44, 25. Cf. Frazer, ii, 227 sqq. On shaving the head, Levit. 21, 5 : Ezekiel 44, 20. 3 Elagabalus, by way of sportula, gave away all manner of animals except pigs; “ for he abstained from them by the law of the Phoenicians᾿᾿ (Herodian 5, 6, 9; cf. Dio Cassius
footnote 1 ἀπικνέηται Werfer: ἀπικνέεται MSS. 1 “In Syria by the sea is a city named Ascalon. . . . I saw there an impossible number of doves at the crossways and about every house, When I asked the reason, they said it was not permissible to catch them ; for the inhabitants, from a remote period, had been forbidden to enjoy them. So tame is the creature through security that it always lives not only under the same roof with man but at the same table, and abuses its immunity᾿᾿ (Philo Judaeus, quoted by Eusebius, Praep. Erang. 8, 14, 50). See Hehn, Kulturpflanzen und Haustiere, 6 p. 329 sqq.: Baudissin, Studien, ii, p. 191. 2 Shaving the head and brows was probably purificatory in this connection. See Plutarch, Isis and Osiris, 4.
footnote 1 A relic of child sacrifice. “Shall give my first-born for my transgression, the fruit of my body for the sin of my aoul?᾿᾿ (Micah 6, 7). On traces of infant sacrifice discovered in he excavations in Palestine, see Cook, pp. 36, 38, 43 Fazer, Folklore i, 418 and note. From recent excavations in a sanctuary of Tanit at Carthage, it is apparent that firstborn children were offered to that goddess during the whole period of punic occupation (Am. Journal of Archaeol., 1923 p. 107). “Jephthah᾿s daughter had many successors before Hadrian tried to stamp out the practice. At Laodicea a virgin was annually aacrificed to ῾ Athenaʼ until a deer took her place; Elagabalus was accused of offering children in his sun-temple at Rome; . . . an Arabian tribe annually sacriced a child, which they buried beneath the altar that served
