@config
@author=Lycophron
@availability=Available under a Creative Commons Attribution-ShareAlike International 4.0 License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@editor=G.R. Woodward, H. Mattingly
@filename=tlg0341.tlg002.perseus-grc1
@fmt:text-orig-full={pre}{orig}{post}
@fmt:text-orig-main={main} 
@fmt:text-orig-plain={plain} 
@funder=Google Digital Humanities Awards Program
@placeName=Ciron
@principal=Gregory Crane
@publicationStmt=Trustees of Tufts University, Medford, MA, Perseus Project.
@respStmt=Prepared under the supervision of, Lisa Cerrato, William Merrill, Elli Mylonas, David Smith
@sectionFeatures=book
@sectionTypes=book
@sourceDesc=Lycophron, Alexandra, A.W. Mair, London: William Heinemann; New York: G.P. Putnam's Sons, 1921.
@sponsor=Perseus Project, Tufts University
@structureFeatures=_book,book,_sentence,_phrase
@structureTypes=_book,book,_sentence,_phrase
@title=Alexandra
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:38:57Z

