@node
@author=Callimachus
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=open-close-tag without further specification. See the name of the .tf-file for it's meaning
@editor=John Burnet
@filename=tlg0533.tlg003.perseus-grc1
@funder=Tufts University
@principal=Gregory Crane
@publicationStmt=Trustees of Tufts University, Medford, MA, Perseus Project.
@respStmt=Prepared under the supervision of, Lisa Cerrato, Anne Mahoney, David Smith
@sourceDesc=Hymns and Epigrams, Callimachus, Ulrich von Wilamowitz-Moellendorff, Berlin, Weidmann, 1897.
@sponsor=Perseus Project, Tufts University
@title=Epigrams
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:37:37Z

2461	1
displayNumAndIndent
2
displayNumAndIndent
displayNumAndIndent
3
displayNumAndIndent
4
5
displayNumAndIndent
6
displayNumAndIndent
displayNumAndIndent
7
displayNumAndIndent
8
displayNumAndIndent
displayNumAndIndent
9
displayNumAndIndent
10
displayNumAndIndent
11
displayNumAndIndent
displayNumAndIndent
12
displayNumAndIndent
13
14
displayNumAndIndent
15
displayNumAndIndent
16
displayNumAndIndent
17
displayNumAndIndent
18
displayNumAndIndent
19
displayNumAndIndent
20
displayNumAndIndent
displayNumAndIndent
21
displayNumAndIndent
22
displayNumAndIndent
23
displayNumAndIndent
24
displayNumAndIndent
25
displayNumAndIndent
26
displayNumAndIndent
27
displayNumAndIndent
28
displayNumAndIndent
displayNumAndIndent
29
displayNumAndIndent
30
displayNumAndIndent
31
displayNumAndIndent
32
displayNumAndIndent
33
displayNumAndIndent
34
displayNumAndIndent
35
displayNumAndIndent
36
displayNumAndIndent
37
displayNumAndIndent
38
displayNumAndIndent
displayNumAndIndent
39
displayNumAndIndent
40
displayNumAndIndent
41
displayNumAndIndent
displayNumAndIndent
42
displayNumAndIndent
43
displayNumAndIndent
displayNumAndIndent
45
displayNumAndIndent
46
displayNumAndIndent
47
displayNumAndIndent
48
displayNumAndIndent
49
displayNumAndIndent
50
displayNumAndIndent
51
displayNumAndIndent
52
displayNumAndIndent
displayNumAndIndent
53
displayNumAndIndent
54
displayNumAndIndent
55
displayNumAndIndent
56
displayNumAndIndent
57
displayNumAndIndent
58
displayNumAndIndent
displayNumAndIndent
59
displayNumAndIndent
60
displayNumAndIndent
61
displayNumAndIndent
62
displayNumAndIndent
displayNumAndIndent
63
displayNumAndIndent
64
displayNumAndIndent
65
displayNumAndIndent
66
displayNumAndIndent
67
displayNumAndIndent
68
displayNumAndIndent
69
displayNumAndIndent
70
displayNumAndIndent
displayNumAndIndent
displayNumAndIndent
displayNumAndIndent
displayNumAndIndent
displayNumAndIndent
displayNumAndIndent
displayNumAndIndent
71
displayNumAndIndent
72
displayNumAndIndent
displayNumAndIndent
73
displayNumAndIndent
74
75
displayNumAndIndent
76
displayNumAndIndent
displayNumAndIndent
77
displayNumAndIndent
78
displayNumAndIndent
displayNumAndIndent
79
displayNumAndIndent
80
displayNumAndIndent
displayNumAndIndent
81
displayNumAndIndent
82
displayNumAndIndent
displayNumAndIndent
83
displayNumAndIndent
84
displayNumAndIndent
displayNumAndIndent
85
displayNumAndIndent
86
displayNumAndIndent
87
displayNumAndIndent
88
displayNumAndIndent
displayNumAndIndent
89
displayNumAndIndent
90
91
displayNumAndIndent
92
displayNumAndIndent
93
displayNumAndIndent
94
displayNumAndIndent
displayNumAndIndent
95
displayNumAndIndent
96
displayNumAndIndent
97
displayNumAndIndent
98
displayNumAndIndent
99
displayNumAndIndent
100
displayNumAndIndent
101
displayNumAndIndent
102
displayNumAndIndent
103
displayNumAndIndent
104
displayNumAndIndent
105
displayNumAndIndent
106
displayNumAndIndent
107
displayNumAndIndent
108
displayNumAndIndent
109
displayNumAndIndent
110
displayNumAndIndent
111
displayNumAndIndent
112
displayNumAndIndent
113
displayNumAndIndent
114
displayNumAndIndent
115
displayNumAndIndent
displayNumAndIndent
116
displayNumAndIndent
117
displayNumAndIndent
118
displayNumAndIndent
119
displayNumAndIndent
120
displayNumAndIndent
121
displayNumAndIndent
122
displayNumAndIndent
displayNumAndIndent
