@node
@author=Libanius
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Richard Foerstser
@filename=tlg2200.tlg00502.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane
@publicationStmt=University of Leipzig, tlg2200.tlg00502.opp-grc1.xml.
@respStmt=Gregory R. Crane, Editor-in-Chief, Perseus Digital Library, Digital Divide Data, Corrected and encoded the text, Matt Munson, Project Manager (University of Leipzig), Annette Geßner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor, Greta Franzini, Project Manager (University of Leipzig), 2013-2014, Frederik Baumgardt, Technical Manager (University of Leipzig), 2013-2015, Simona Stoyanova, Project Manager (University of Leipzig), 2015, Project Assistant (University of Leipzig), 2013-2014
@sourceDesc=Richardus Foerster, Richard Foerster, Libanius, Declamationes I-XII, B.G. Teubner, Leipzig, 1909, 5, Internet Archive.
@sponsor=University of Leipzig
@title=Declamatio 2
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:57:58Z

3680	marginal Mor p. 192
marginal Mor p. 194
footnote Μ = Codex Marcianus gr. 514 Ma = Matritensis 4679 (N-49) Β = Barberinus II 41 6 cf. p. 17, 1; 129, 15 8 Dem. c. Lept. p. 504, 17 sq. 1 κωλύει τίς Ma quocum facit Macarius fol 87 v τῆς μελέτης  ἐν ᾖ κωλύοντός τινος ἐν τῷ δεσμωτηρίῳ Σωκράτην διαλέγεσθαι  ἀντιλέγει τις 2 καὶ om Ma 3 τις om Ma τὶς Β | ἀντίληψις  post ἀντιλέγει: Ma, λιβανίου μελέτη Μ 4 τί Ma 6 προσειμέ- νοις scripsi προσιεμένοις ΜΒ Mor προσιεμένους Ma 9 πάν- των Β 11 θανόντων Ma 13 σωκράτη Β | πράως MaB | καὶ  om Ma
marginal Mor p. 196
footnote 5 Plat. apol. p. 38 C 13 Dem. p. 118, 16 22 cf. p. 95, 12.  Xen. comm. I 2, 60 2 καὶοmΜa 3 δύναται scii-psi dvvaLtolihiiMoi | καὶ(3)  inserui e Ma om ΜΒ Mor 5 αἰτίαν scripsi e Ma coll 1. 16  et t. III 361, 18. Plat. 1. 1. Thuc. II 18, 2 ἀτιμίαν ΜΒ Mor  8 σωκράτει MaB 12 ταύτην γνώμην Β | τοῦτο scripsi e  Ma ταύτην ΜΒ Mor 13 τὴν ζημίαν Μ Mor | μηδὲ scripsi  μὴ δὲ MaB μὴ Μ Mor 16 αὐτοῦ scripsi αὐτοῦ libri  Mor 17 ἀναξιωτάτας scripsi e Ma ἀναξιὧτατα ilfMor  ἀναξίῳ cum lacuna 2 — 3 litt Β 21 ἀντιπαραταξάμενος  scripsi e Ma ἀντιταξάμενος ΜΒ Mor 22 χρήματα καὶ μι-
marginal Mor p.198
footnote 8 Plat. apol. p. 38 C 11 Diog. L. II 5, 23, 43 14 cf. 1. ΙΙ  460, 20 sq. Thuc. III 36 sq. 15 cf. p. 17, 2 17 cf. p. 112, 6  18 cf. p. 112, 11 20 Plat. Phaed. p. 59 E; 85 B σθὸν τῆς συνουσίας Ma | τῆς inserui e libris om Mor | μὴ πρα- ξάμενος τοὺς φοιτῶντας αὐτῷ) τοὺς φοιτῶντας οὐκ αἰτῶν Ma 1 συνόντας Β | ἰδίων scripsi διὸ Ma δύο ΜΒ Mor  3 ἄλλους ἀγαθοὺς scripsi ἀγαθοὺς ἄλλους libri Mor | ἡμῖν inserui  e MaB om Μ Mor | ἐργασάμενος MaB 5 τοῖς om Mor | καθ’  αὐτὸν Ma 6 ἀπὸ Ma | τούτου MaB | διαπεμπομένοις scripsi  e MaB πεμπομένοις Μ Mor 7 οὖν om Ma | τοιοῦτος καὶ  τοιοῦτος Ma 8 δίκαιον scripsi δικαιότατον libri Mor  10 μετὰ om Ma 11 τοῦτ’ scripsi ταῦτ’ libri Mor | οἷδ’ Ma 12 ἂν inserui e Ma ut coni Mor om ΜΒ Mor 13 περὶ  om MMa 16 κἂν Μ Mor 17 οὔτε scripsi e MaB οὐ  Μ Mor 18 σωτηρίαν om Β  LIBANIUS ed. Foerster. V. 9
footnote 11 Il. π 853 1 λύκιον MaB cf. p. 24, 11; t. IV 353, 11 3 αὑτοῦ  scripsi αὐτοῦ libri Mor | φθέγξασθαι MaB | λαλῆσαι Β  4 τις inserui e Ma om ΜΒ Mor 5 ἑταίροις Ma sed ταί- ροις in ras m 2 8 οὕτω καὶ θείους Μ sed καὶ eras | οἱ Ma  9 πάντες Ma | ἂν om Ma 10 μὲν om Ma 12 δὲ  MaB 13 φθονῶν scripsi ut coni Mor φθονεῖν libri Mor |  Μέλητος reposui e libris Μέλιτος Mor ut constanter in hac  declamatione cui oblocutus est Boissonadius Anecd. V 324 sq.  17 δεσμὸς Μ | εὑρίσκουσι ταῦτα Ma | σωκράτει MaB 21 καὶ  inserui om libri Mor 22 τοιοῦτον reposui e libris τοιοῦτο Mor
marginal Mor p. 206
marginal Mor p. 208 1 Dem. p. 352,12; 1075,10 2 Andoc. myst. § 87 et 89.  Dem. Timocr. § 59; Aristocr. § 86; Steph. II § 12. Aen. Theo.  p. 24, 8 ed. Boiss. 6 Thuc. I 73, 1 cum nota Kruegeri 11 Thuc.  II 45, 1. Dem. p. 330, 3; 441, 29 17 Lys. c. Erat. p. 394, 13 1 ἄντικρύς τε καὶ διαρρήδην] ἂν cum lacuna 8 litt Β | καὶ  om Ma | ὑπὸ scripsi e MaB ἀπὸ Μ Mor 3 μὴ δὲ Β | πο- νηρός τε καὶ κατ’ ἐψηφισμένος ὤν om in lac 10 litt Β 4 καὶ  om Ma | ὤν] ἐστί coni Mor 6 καταβοῆς scripsi e MaB  καταβολῆς Μ Mor 7 σεμνυνεῖσθαι Μ | Σωκράτει om Ma  8 Χίλωνι MaB 9 καὶ Περιάνδρῳ Κορίνθιοι om Ma  10 αὐτόν Ma 11 πᾶσι — 13 κρίνεται omissa γὰρ particula  citat Macar fol 87 v (Villoison Anecd. 11 13; Lib. t. I p. XXVIII R)  | ζῶσι μὲν om Β | πλησίον scripsi e MaB Macar πλησιόνων  Μ Mor 12 προσφύεται Macar 14 νυνὶ Ma | ὧσπερ Ma |  ἔδοξαν ΜΒ 15 πράττεσθαι Ma 18 ἀποδραίη scripsi  ἀποδρῴη Μ Mor ἀποδρώη MaB  
footnote 5 Luc. Icar. 20 11 Plat. rep. V p. 558 A 1 ἡμῶν Ma | ἐξέλθοι scripsi e MaB cum Boissonadio An III  199 ἐξέλθῃ Μ Mor | κἂν — 4 πόλεις om Ma κἂν] οὐδ’ ἂν Β  2 τῶν ἄλλων om Β 3 θετταλούς Β 4 ἁρπάσαι Β | καλοῦσι  Β 5 ἂν inserui 7 verba καὶ δίψᾳ τοῦ κωνείου citat  auctor Coisl. περὶ συντάξεως ed. Bekker Anecd. p. 135, 22 s. v.  διψῶ· γενικὴ. Δημοσθένης ὁ μικρὸς ἐν τῇ σιωπὴ Σωκράτους·  καὶ δίψᾳ τοῦ κωνείου atque hinc auctor metricus περὶ γραμ- ματικῆς ἡ. 198 (Boiss. An. II 350 cf. Add. p. 485) διψῶ κωνείου  γενικῇ παρὰ τῷ Δημοσθένει et codex Suidae A in marg s. v. διψῶ·  Δημοσθένης· διψῶ τοῦ κωνείου cf. Mus. Rhen. XXXII 87  9 δεῖν Ma sed in δεινὸν corr m rec 10 δεῖ — 15 νόμους  citat Melissa Augustana (Mon. gr. 429 fol. 16 v) τοῦ μικροῦ δη- μοσθένους· δεῖ γὰρ — νόμους et omissa γὰρ particula Macar  fol 87 v (Villois. Anecd. II 13 Lib. t. I p. XXVIII R) δεῖ —  11 δικασθεῖσι] οὔτε πλείω τοῖς δικασθεῖσι χρὴ Macar | προστε- θῆναι Meliss κατατιθέναι Ma Macar | τὴν inserui e Μ om re- liqui libri Mor | φιλανθρωπία Meliss 12 ἀνάγκῃ scripsi  ἀνάγκης libri Mor | ὑπὸ scripsi e MaB Meliss Macar παρὰ Μ  Mor 13 πικροτέρας Ma 14 ἐστι] ἐστιν ἄτοπον Meliss | τὸ  om Meliss | προσθεῖναί Ma Macar πρὸς τὸ τιθέναι Meliss |  τὸ] τῶ Meliss 15 ἐπιεικείας Meliss ἐπιεικίας Macar
marginal Mor p. 212
footnote 6 Dem. p. 790, 20 8 Dem. p. 487, 10; 1116, 2 9 Isocr.  p. 75 e. [Luc.] salt. § 61. Arist. Eq. 1283 1 ὅδ’ Β Ι Κήρυξ ΜΒ Mor cf ad t. IV 316, 7 | ἂν εἷπε MaB  2 σωκράτη Ma 3 μὴ δὲ Β b γε MaB 6 καὶ can- cellavi Ι σιωπῆς scripsi e Μ coll Dem 1. L σιωπὴ MaB Mor  7 ὃ] οὐ Μ 9 ἀκμὴν scripsi e MaB ἀκοὴν Μ Mor | οὐ om  Ma 1 νῦν scripsi e Ma ut coni Mor τοίνυν ΜΒ Mor | προσεξ- ευρίσκετε scripsi e Β προσευρίσκετε Ma εὑρίσκετε Μ ἐξευ- ρίσκετε Mor 10 γὰρ om Ma 13 φθέγγεται scripsi coll  p. 130, 3 et 137, 19 φθείρεται MMa Mor in lac 5—6 litt om  Β 14 δέδωκε Ma 15 ἀπηγορεύετο Β \\ καταδικασθέν τι Β  καταδικασθέν τὰ Ma Ι τίς Ma sed ’ς add m rec 16 δ’ in- serui e Ma om ΜΒ Mor Ι ἤχθη scripsi e MaB ἤχοη Μ  ἥκοι Mor 11 τίς Β om Ma \\ γλῶττα Ma ἀπεκόπη scripsi e  Ma ἀπέκοπτε ΜΒ Mor Ι ἡμᾶς Ma sed ἡ in ras m2
marginal Mor p. 214
marginal Mor p. 216
footnote 1 cf p. 104,4 2 cf. p. 120, 13. Xen. comm. 1 1, 18 1 ἐδέθη — 16 ἀξίῳ citat loann. Doxap. comm. ad Hermog.  de inv. IV 1 (Rhet. gr. t. III p. 145, 16 Walz; t. II p. 234,20  Speng.) cod. Barocc. 175 fol 175; Par. 2922 fol 231 (Cramer  Anecd. Ox. IV 164, 7 sq. cf Mélanges Graux p. 629 sq.) καὶ τὸν  Λιβάνιον εὗρον τούτῳ (τῷ ἁπλοῦντι σχήματι) χρησάμενον ἐν τῷ  τοῦ Σωκράτους ζητήματι τοῦ κωλυομένου ἐν τῷ δεσμωτηρίῳ φι- λοσοφεῖν· καὶ γὰρ ἐκεῖ ἐστι μὲν ἐπιχείρημα ὅτι οὐ δεῖ τοὺς τε- λευτῶντας δίκην διδόναι, ὅτι τελευτῶντες φθέγγονται, εἶτα ἐρ- γασία ἐκ παραδείγματος ὅτι ἐδέθη κτλ — 2 δεδεμένος καὶ πάλιν  ἑτέρα ἐργασία· κατεψηφίσασθε κτλ. — 6 ἐπετάξατε, εἶτα τὸ  ἐνθύμημα ἡπλωμένως ἐξενεχθὲν· δεινὸν δὲ ὅταν κτλ. | ἡμῖν  Dox | οὐκ ἐσιώπα δὲ scripsi e Ma Dox καὶ οὐκ ἐσιώπα ΜΒ  Mor 2 ποτε inserui e Dox om libri Mor 3 ἀθῴων —  5 ποιουμένου om Dox ἀθέων Μ | ἄκοντος scripsi εἴκοντος Ma  ἑκόντες ΜΒ Mor | κοινωνοῦντες Β 5 ποιούμενοι Ma  8 τὰ μέγιστα] ἄλλα Dox | κακὰ inser Ma 2 10 κωλυομένων ὐπ’  οὐδενός Dox | ἐπισκεπτόντων MaB 12 ἄλλων Ma sed v add  m rec 14 ἐπὶ Dox | ἐκ τοῦ παντὸς τοῦ Β 15 τεθνηξομένῳ
marginal Mor p. 218
marginal Mor p. 220
footnote 1 Plat. rep. IV p. 423 C 2 cf 47, 2; 99, 7 8 Xen.  comm. I 2, 37 9 Plat. Tim. p. 22 D 10 Xen. comm. I  2, 32 15 cf. p. 100, 18. Diog. L. II 5, 10 17 Her. III 14, 2 scripsi e Ma Dox τεθνηξομένων ΜΒ Mor | τούτῳ ποτὲ ante  μὴ ΜΒ Mor, quod delevi ut anticipatum e p. 135, 1, ποτε Ma 1 τοῦτό ποτε τὸ scripsi τούτῳ ποτὲ libri Mor qui τοῦτο  scribendum coni 3 μαθητὴς scripsi μαθητῶν libri Mor  5 γράφεται scripsi e MaB γράφετε Μ Mor 6 ἶσα MaB  7 ἀπηγόρευσε Ma sed σε in ras m 2 | τοῖς νέοις διαλέγεσθαι  σωκράτην Ma 8 οὔτοι — λέγειν om Β | οὗτοι MMa | πᾶσι  Ma | μὴ λέγειν om Ma | ἐπέχεσθαι Ma | τῶν — 9 βουκόλων in  lac 25 litt fere om Β 9 τεκτόνων olim conieci Mus. Rhen.  XXXII 93 coll. Xen. l. l. | καὶ cancellavi | τῶν (2) om Ma  10 τὸ delendum vel in τοῦ mutandum videtur cf t. IV 79, 6 R 11 ὃν δὴ] ᾧτινι MaB | καὶ Β 12 μηδὲ Μ μὴ δὲ Πα  14 ἂν ἔρηται] ἂν ἄρηταί Ma ἀνήρηταί Β 15 Λαμπροκλῆς  — 16 Σωκράτης in lac 24 litt om Β 16 ἀποκρίνηται Ma  17 τοῖς κοινοῖς Ma sed in τῆς κοινῆς corr m rec, Β
marginal Mor p. 222
marginal Mor p. 224
footnote 2 Plat. leg. I p. 641 A 3 Isocr. p. 310 d; 418 b 6 cf  t. III 443, 10. Dem. p. 331, 23 11 Xen. Hell. II 3, 52. Aesch.  fals. leg. § 45 p. 34, 9 12 Aesch. Ctes. p. 87, 21 14 cf.  p. 120, 10 20 cf. p. 47, 9; t. II 134, 15 1 καὶ inser Ma m rec 2 γὰρ om Ma | φιλόλογον Β Mor  3 πολύλογον Mor | ὑπόγυος Ma ὑπόγνος Β 4 φιλολαλιά  MaB 9 καὶ γὰρ] οὐδὲ Ma 13 χιλίων MaB | ἕνεκα scripsi  secundum usum Libanii εἵνεκα libri Mor | σωκράτης Ma  15 ἦγε μὲν Ma 16 αὐτός Ma 17 δ’ οὑν Ma 18 μηθένα  Ma 19 μὴ δὲ MaB 20 οὐ (3) om Μ 22 ἐπιτάττεται Μ
marginal Mor p. 226
marginal Mor p. 228
footnote 2 cf. p. 143, 8 11 II. ψ 65 sq. 14 Her. I 85, 2 2 τίς Β 3 ἀφήσων τὴν ψυχὴν αὐτίκα Ma | μηδενὶ in  lac 6 litt om Β μηδὲν Ma 4 αὐτὶ χ’ ὡς Ma | ἀποθάνῃ  scripsi e libris sed η in οι corr Μ ἀποθάνοι Mor 11 ὄμμα  olim conieci Mus. Rhen. XXXII 88 12 φωνήν; Ma Mor  καὶ om Β | μὲν γὰρ Ma 13 πάντες — 15 συμφορᾷ citat  Macar fol 87 v 14 γε in ras Ma 2 | τοῦ om Ma | παῖδά φασι  Macar φασι om Ma 15 τὴν ante φωνὴν Mor delevi coll  t. II 400, 1 et Her l. l. | ἐπὶ Μ 16 μὴ δὲ (1 et 2) Β  17 ἐπὶ Μ | τύχῃ; scripsi e Ma τύχη· ΜΒ Mor 18 φυλακτέα  scripsi φυλάττεται libri sed pro αι lac 2 litt Β, Mor  19 φθέγγεσθαι καὶ λαλεῖν MaB 20 πλησίον — 21 τέλους καὶ  om Β 21 φασὶ φιλοσοφεῖ Ma φασὶ φιλοσοφεῖν Β
marginal Mor p. 230
marginal Mor p. 232
footnote 8 cf p. 29, 10; 100,10; 144, 1 et 2. Plat. Phaed. p. 59 B  13 Plat. apol. p. 34 A 16 cf p. 26,7; 114, 15 sq.  18 Plat. Prot. p. 313 D 1 μὴ δὲ Β | ὅρος in ras Ma 2 φιλοσοφίας· Β 5 οὐ- δενὸ αὖ Β 6 ἑάλωκεν Ma | μηδὲ in lac 4 litt om Β μὴ  δὲ Ma | τιμᾶσθαι MaB 7 τί] τὸ Ma 9 καὶ Κρίτων et  καὶ Σιμμίας et 10 Ἀντισθένης et 12 λέγει om Ma 14 εἰσὶν  οἱ δίκαιοι Ma 15 γὰρ ἂν οὐ Ma 17 καὶ Ἱππίαν] ἱππίαν  καὶ Ma 19 ἰδ’ ία καὶ κοινὴ MaB 20 αὐτ’ οἶς ἀνθρώποις  om in lac 8 litt Β αὐτοῖς τἄνοίς Ma unde olim Gepperto τανα- γροις scriptum esse testanti fidem habens Ἀκραγαντίνοις post  καὶ Κείοις scribendum conieci Mus. Rhen. XXXII 96 quod iam  improbo | Κείοις scripsi χίοις libri Κίοις Mor | αὐδηρἰταις Ma
marginal Mor p. 234
marginal Mor p. 236
footnote 10 Plat. conv. p. 174 A 11 Plat. Prot. p. 311 A | rep.  III p. 400 B; 424 C; Axioch. p. 364 12 Plat. rep. I p. 327 A;  328 C | Plat. Phaedr. p. 229 A; 230 B 13 Plat. Phaedr.  p. 230 C; 258 E 14 cf ad p. 87, 14 15 Plat. rep. I p. 336 A sq.  cf. ad p. 26, 8 | Plat. Charm. p. 154 A sq. 16 Plat. Lach.  p. 178 A sq. 17 Xen. comm. II 3 cf p. 101, 1 | Plat. Men.  p. 70 A sq. 18 Plat. Hipp. mai. p. 286 sq. | Plat. Gorg.  p. 447 sq. 3 ἐμφορηθήσεσθαι Ma sed αι in ε corr m rec | τοῦ om  Ma 4 μὲν om Μ 6 καθέξει Ma sed έ in ras m 2  11 Δάμωνος scripsi ἄμμωνος libri Mor qui Δάμωνος coni, sed  fortasse οὐκ ἐν ἄμμωνος nihil nisi lectio varia ad οὐκ ἐν Ἀγά- θωνος fuit 14 οὐκ ἐν Ἀμφιπόλει ante οὐκ ἐπὶ Δ. excidisse  coni Mor | Δηλίῳ scripsi e Ma δήλῳ ΒΜ Mor qui Δηλίῳ coni  15 Χαρώνδαν Β 16 ἀνδρείας Β
marginal Mor p. 238
marginal Mor p. 240
footnote 1 Plat. Prot. p. 319 sq. 2 Plat. Euthyp. p. 10 C sq.  3 Xen. comm. I 3, 8 sq. 11 Philostr. vit. soph. I 12 20 Plat.  Phaed. p. 84 E sq. Aesch. Ag. 1398 2 τοῦ inserui coll Plat. Eutyp. l. l. om libri Mor 3 οὐ  — 4 καλόν inserui e MaB om Μ Mor | περὶ τοῦ μὴ inserui  om libri 4 τὸν καλόν scripsi e Ma om in lac 5 litt Β  7 αὐτῷ in ras Ma 2 8 βασανίζεται· εἰ MaB 9 καὶ (2)  inserui om libri Mor 10 post δεδεμένος verba (9) οὐκ ἀλγεῖ  — θρηνεῖ repetivit Ma sed del m 2 et 11 ἐγὼ — 12 λόγων in  marg scr m 2 13 ἦλθεν Ma 15 καὶ om MaB | ἀνάγκαζ’ Β  | παυσόμενος Β 16 τί δ’ αὐτὸν om Β 17 ὅτι καὶ in lac 7  litt om Β ὅτε τίς Ma
marginal Mor p. 242
marginal Mor p. 244
footnote 1 cf ad p. 115, 9 2 Plat. Phaed. p. 85 B 4 Diog. L.  II 5, 18, 37 9 sq. Eur. Palam. fr. 578 sq. N 2. Arist. Thesm.  770 c. schol. 14 cf t. IV 588, 26 R 22 cf p. 119, 13 sq. 2 κατὰ Πα 5 σοφώτατος scripsi e Ma σοφώτερος ΜΒ  Mor 7 ἐγένοντο καὶ πρότερόν ποτε (ε in ras m 2) Ma  8 ποτε inserui e Ma om ΜΒ Mor | τῶν Ma sed ων in ras m 2  9 κἀν scripsi ἐν libri Mor 13 τύχην in ras Ma 2 14 ἐπιθα- λάττιον Ma | καὶ post δὲ Ma 16 ἀλλὰ om Β 17 ἐπιέναι  Ma | πείθεται Ma sed πειθ in ras m 2 | τῷ om Ma 18 οὕτως  Ma | νῦν om M 19 τὸ om Ma 20 αὐτὸν Ma 21 τὸν  om Ma 22 θράττιαι Β θρακίαι Ma
marginal Mor p. 248
marginal Mor p. 250
footnote 4 Ael. var. hist. XIII 20 14 cf Ael. var. hist. 16; XII 49 2 ἡ κεφαλὴ Ma sed ἡ κεφα in ras m 2 | κατέβαινεν Ma 4 ὁ κεκολασμένος scripsi Mus. Rhen. XXXII 96 οὐ κεκο- λασμένου MaB οὐ κεκολασμένα Μ Mor | ἀμείβεσθαι δώροις  olim conieci δωριᾶ αὐλήματα coni Mor 5 ἀλλ’ οὐδὲ Ma  9 ἡμῶν Ma 12 punctum post ἐστίν posui, signum interro- gationis libri Mor 13 &lt;    ὡς&gt; κἀν scripsi κἂν ἐν libri sed ὡς  ante ἐν inser Ma 2, Mor 15 μὲν νῦν reposui e libris νῦν μὲν  Mor 16 σωκράτης Μ | ὅτε scripsi e Ma ὅτι ΜΒ Mor  17 τοιούτους λόγους scripsi e MaB τοιοῦτον λόγον Μ Mor  18 οἷόνπερ] οἶα γὰρ MaB 19 τί — πολιτείας om Μ 20 πα- τρίων scripsi e Β πατέρων MMa πατρικῶν Mor | τὰ δὲ] τάδε  Β et coni Mor 21 νῦν καὶ] καὶ νῦν Β
marginal Mor p. 252
marginal Mor p. 254
footnote 1 Plat. ep. 8 p. 354 E 3 Plat. Crit. p. 53 B sq.; 45 C  7 Plat. Phaed. p. 60 D. Dio Chr. or. 43 t. II p. 580 R  8 Socr. fr. 2 Poet lyr. fr. ed. Bergk II p. 287 4 13 cf p. 119, 9 sq.;  146, 10. Plat. Phaed. p. 58 A sq. 15 Eur. Alc. 650 21 sq.  Plat. Phaed. p. 60 B sq. 4 μενεῖν scripsi ut coni Mor μένειν libri Mor 8 καὶ 0111  Ma | κεκελευσμένος Ma sed ε et ελ in ras m 2 | καὶ ante τοὺς MaB  9 ποιήματα in lac 7 litt om Β πᾶσαν Ma 15 θεράποντι  Ma sed ερ in ras m 2 17 ἀνόητον Β 19 εἰ inserui e libris  om Mor 20 τηνίκα δὲ Ma τηνικάδε Β 21 ἀποτείνας Ma  22 μὴ δὲ (1 et 2) Β | τούτου scripsi e MaB τοῦτο M Mor
marginal Mor p. 256
footnote 4 Plat. Phaed. p. 117 B 7 Plat. Phaed. p. 118 A  9 Plat. Phaed. p. 117 B sq. 13 Plat. Phaed. p. 117 D  17 Plat. Gorg. p. 493 A; Cratyl. p. 400 B 2 περὶ Β | ἀλλ’ om Ma 5 μὴ — 6 πείθεται om in lac  fere 27 litt Β | διαδέξη Ma 6 μηδέ inserui | λέγων ante  ἀθάνατον εἷναι τὴν ψυχὴν Ma | πείθεται scripsi e Ma πύθε- ται Μ Mor 8 κελεύσῃ scripsi κελεύσειε Μ Mor ἐκέλευσε  MaB | τινὶ τῶν ἑταίρων Ma | μέλη ποεῖσθαι Ma 9 μηδ’ Mor  | εὔχηται Β | αὑτῷ scripsi αὐτῷ libri Mor 12 κάθηται om  Μ κάθεται Mor 16 ἡμῶν Β 16 καὶ inserui auctore Mor  om libri | τε om Β 18 ἔπιμεν Ma 19 χρὴ — 145, 1 βίον  citat Macar fol 88 r post 145, 5 — 13 τοὺς μὲν — τιμωρίαι ταμιεύον- ται addita particula διὸ ante χρὴ (Villois. Anecd. II p. 14. Lib.  t. I praef. p. XXVIII R) | μὲν] ἡμᾶς Macar
marginal Mor p. 258
marginal Mor p. 260
footnote 1 Plat. Phaed. p. 81 A 2 Plat. Phaed. p. 72 E 8 Plat.  Phaed. p. 82 C 9 Plat. Phaedr. p. 247 C sq. 11 Plat. leg.  Χ p. 905 B; ep. VII p. 335 B 12 Luc. luct 3 1 μελέτην scripsi e Ma Macar coll Plat. l. l. μνήμην MB  Mor | τὸν πάντα βίον Macar 5 μένουσι MaB | τοὺς μὲν  Macar 6 καθαροῖς Β | δικαίοις Β καὶ βιοῦσι καὶ Ma | βε- βιωκότας et 7 ἀνασχομένους Macar 8 ἀκολουθίαι δέχονται  καὶ ἡ ὑπερουράνιος περίοδος καὶ θέα αὐτοῦ τοῦ δικαίου Macar 9 καὶ θέαν αὐτοῦ inserui e Ma Macar om ΜΒ Mor | τοῦ  inserui 10 καὶ inserui e Macar om libri Mor | ψυχῶν  εὐδαιμόνων scripsi e Macar ψυχὴν εὐδαιμόνων Ma ψυχῆς  εὐδαίμονος Μ Mor ψυχῆς cum lac 8 litt Β | ἀθύμως Macar  11 καὶ — ἀνοσιουργημάτων om Macar 12 πυριφλεγέθοντος Μ 13 ταμιεύονται post τιμωρίαι Macar ἐν] καὶ Ma 16 ταῦτα  scripsi e ΜΒ ταῦτ’ Ma ταῦθ’ Mor | ἡμίν ἐπισκήπτει in lac  7 litt om Β  LIBANIUS ed. Foerster. V. 10
footnote 12 Plat. Phaed. p. 58 B sq. Xen comm. IV 8, 2 15 Plat.  Crit. p. 44 A 1 τὰς inserui e libris om Mor 2 λέγῃ reposui e libris  λέγει Mor 3 μακρὸς γὰρ? 4 θεαί Ma | ἐκείνοις in marg  add Ma 7 ἔσαι? | μήποθ’ Ma 8 ἀπολαύσει scripsi e MaB  ἀπολαύσῃ Μ Mor | τίς Β | ἐστι Ma 10 κατέσχε Ma  12 ἐρέσθαι scripsi ἐρήσεσθαι ΜΒ Mor om Ma 14 με ante  μέχρι δ’ ἂν post μέχρι Ma | Σωκράτους scripsi σωκράτης libri  Mor | ἴσως ἡ ναῦς M 15 προερρήθη scripsi e MaB προἐρήθη M  προειρήθη Mor 16 φθονήσητε scripsi e MaB φθονήσετε  Μ Mor | ἦ scripsi e Β ἤ Ma εἰ Μ Mor | καὶ om Β | ἐγὼ  μὲν scripsi e Ma μὲν ἐγὼ ΒΜ Mor 17 ἑταίροις scripsi  ἑτέροις libri Mor
marginal Mor p. 264
