@config
@author=Dionysius of Halicarnassus
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@editor=Hermann Usener
@filename=tlg0081.tlg004.perseus-grc1
@fmt:text-orig-full={pre}{orig}{post}
@fmt:text-orig-main={main} 
@fmt:text-orig-plain={plain} 
@funder=Google Digital Humanities Awards Program
@placeName=Ctesiphon
@principal=Gregory Crane
@publicationStmt=Trustees of Tufts University, Medford, MA, Perseus Project.
@respStmt=Prepared under the supervision of, Lisa Cerrato, Alison Babeu, Bridget Almas, Monica Berti
@sectionFeatures=chapter
@sectionTypes=chapter
@sourceDesc=Dionysii Halicarnasei Quae Exstant, Volumen Quintum, Opsuculorum, Volumen Prius, Dionysius of Halicarnassus, Hermann Usener, In Aedibus B.G. Teubneri, Leipzig, 1899, Keyboarding.
@sponsor=Perseus Project, Tufts University
@structureFeatures=_book,chapter,_sentence,_phrase
@structureTypes=_book,chapter,_sentence,_phrase
@title=De Isocrate
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:45:14Z

