@node
@author=Galen
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Karl Kalbfleisch
@filename=tlg0057.tlg019.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane, Monica Berti
@publicationStmt=University of Leipzig, tlg0057.tlg019.opp-grc1.xml.
@respStmt=Gregory R. Crane, Editor-in-Chief, Perseus Digital Library, Digital Divide Data, Corrected and encoded the text, Matt Munson, Project Manager (University of Leipzig), Annette Geßner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor, Greta Franzini, Project Manager (University of Leipzig), 2013-2014, Frederik Baumgardt, Technical Manager (University of Leipzig), 2013-2015, Simona Stoyanova, Project Manager (University of Leipzig), 2015, Project Assistant (University of Leipzig), 2013-2014
@sourceDesc=Galeni De Victu Attenuante Liber, Carolus Kalbfleisch, Galenus, In Aedibus B.G. Teubneri, Lipsiae, 1898, HathiTrust.
@sponsor=University of Leipzig
@title=De Victu Attenuante
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T15:00:25Z

7544	footnote 1—4, 6 187, 5—188, 7 1 γαληνοῦ περὶ λεπτυνούσης διαίτης: — καὶ παχυνούσης: — G: Incipit lib. (gal.᾿ ν) de subtiliante dieta pv: Liber de subtiliante dieta d: cf. praefatio ἴ’ 5 μόνη ταύτῃ Ο: sola ea L: ταύτῃ μόνη G 6 διορίσασθαι G: determinare quid (quid᾿ p) L: fort, διορίσασθαί τι 10 ὅσαι γε μετὰ ἀπέφηναν τὰ ἄρθρα (om. μεστά) Ο: quecumque nondum cum poris (nudos corporis v) ostenderunt (offenderunt 6.) articulos L id est ὅσαι γε μὴ (vel μηκέτι) μετὰ πώρων ἀπέφηναν τά ἄρθρα, fortasse recte 11 παντελῶς] omnino L: καὶ παντελῶς Ο: om. G &lt;τῇ&gt; addidi ex 12 post τὰς δέ add. καὶ O
footnote 6 8 τῆσδε] genetivus post ἐναντίος apud rarissimus, nisi quod dicere solet τοὐναντίον τινός ἐφ’ ἑκατέρας om. L 14 τέ εἰσὶ G ταῦτα G: universa (= πάντα) pd: om. V 24 hec omnia sufficientes cognitiones et maxime sunt (super v) L γνωρίσματα εἰσὶ G
footnote 11—7, 12 193, 1—194, 2. o 156, 1—11 7 ἐκπεσεῖν G: incidere L 11 κρόμυα G 15 μίνθη Ο, cf. adnota ad 7, 10 σισύμβρια GO: σισύμβριον Ο et C2 in Ο: sisimbrium L γλίχων G 16 θύμα Ο: θῦμα G: θύμον ὁ (sed θῦμα F): thymus L 18 τε induxi: om. Οο· farmaca iam sunt L: an φάρμακ’ ἐδτὶ? δέ G cf. § 78: γὰρ Οο: ἁ L 20 εἰσὶν G 22 23 ταυτὶ μὲν G: ταύτῃ μὲν οὖν Ο: ταῦτα μὶν οὑν o: hec igitur L: cf, VI 326, 18
footnote 23 μικρῷ πρόσθεν] § 8 3 κράμβη GO: caulis L: κράμβαι Ο τεῦτλα] εὑ et λ in lit. G1 (scripserat τλεῦτα) 4 bleta d: blitum p: bletum v δ’ τλεύτων G γε scripsi: τε G: om. L 7 κολοκύνταις G 10. 11 μῆλα—σίκυοι om. L 20 ἀπλᾶ G: tenera L 22 δυνάμεσιν εἰσιν G
footnote 12—19 ὁ 201, 10—202, 1. o 159, 21—24 2 τούτοις ex τούτους corr. G1 καὶ σκολύμου om. L ἰρυγγίου G 6 εἰδέναι δέ (malim δὴ) δεῖ G: iam autem L 7 τμητικά G: sunt incisiva L 8 λεπτύνειν G: subtiliant L ἀκαλίφη G παραπλησίως — τεύτλοις om. L γε G: an ταῖς γε? 10 μάραθρον Οο: μάραθον G: cf. VI 622, 16 638, 17 641, 3 ss. X 678, 2 post coriandrum add. mentastrum pd: cf. μίνθη Ο 193, 2 18 ἀγροίκοις G in versu: rusticis L: γρ. ἀττικοῖς G1 s. V.: Οο Ἀττικοῖς Ο ο χονδρίλαι, δρί s.v. G1 21 antiqui vero L
footnote 4—20 ὁ 188, 7—189, 2 1 πανταχόθεν G: ubique L 5 δριμύ G: acutum quid L 7 κατά ταὐτὰ scripsi: κατὰ ταῦτα G: secundum hoc L 9 ἐμποιεῖ G 15 εἰσὶ G 22 ὅσα G: omnium quecumque L: cf. Fleckeiseni annal. suppl. XXIII 682 7
footnote 3 ἑφθὰ G itemque infra ἑφθοῦ, ἑψοῦσιν 5 ἄνισον G 8 ἡγεῖται G: subenarrat L (an ὑφηγεῖται?) 10 πολλάκις multotiens) post ἰδιώτας L fort, recte 11 ὑποτρίμασιν G &lt;ἂν&gt; addidi: iubebam L 14—16 τὰ — εἰρημένα καὶ om. p 15 &lt;διὰ&gt;] per dv: om. G 18 ἐστι εἷναι G sunt (praeced. cf. 15, 5 et 7) L 19 quidem hiis L: fort, μὲν τούτων plus L: fort. πλεῖον 24 ἐλόυ G 25 βρυονίας G
footnote 6 G utrobique 7 τοσούτῳ — χαμαιδάφνης om. L 9 βρυονίας G &lt;ὁ τῆς&gt; om. Gpv: qui d 10 post ἀκτῆς verba καὶ τῶν ὁμοίων ἐν τούτω δὲ [134v] τῷ γένει καὶ οἱ τῶν ἀμπέλων e versu 1 et 2 repetivit G 12 &lt;ὁ&gt; addidi: quales qui palmitis (palmitis vitis d) et qui rubi (et rubus v) L 14 τῶν . . ἄλλων] eorum que roborant ventrem (om, τῇ γεύσει) L 22. 23 teneram productionem earn (earn om. v) que fit in summitate plante L: fort. &lt;τὸ γινόμενον ἐν τῇ κορυφῇ&gt;, 623, 2 τὴν κορυφὴν τοθ’ φοίνικος, ἢν ὀνομάξουσιν ἐγκέφαλον αὐτοῦ 20 τἀς] τά? cf. XII 161, 11
footnote 25—12, 10 ὁ 194, 1—6. 4 μνημονεύω G: memorabor L: fort, -εύσω, cf. 12, 24 19 fort. αὐτὴ: ipso L (ex ipse mut. d) post, spermate (semente v) add. som(p)nolentius L τὸ ex τῆς corr. G1 23 καὶ G: vero pv: enim d 25 καροῦς Οο, nisi quod σκάρου C1 et καρύου C2 in Ο
margin f.135r G
footnote 1 αμεώς G 2 τορδίλου, ρ ex λ corr. G1 9 λυγοῦ, γ’ e corr. G1 κανάβεως G 10 farmacosa et dolere facientia caput L 12 προαιρεῖται G 16 δημήτρεια G 18 αὐτῶν G 19 εἰσὶ — 21 προσαγορεύουσι om. pd 21 δρέπονται cum medium esse possit, in δρέπεται mutare nolui: carpuntur v 28 πυροὸν G utrobique itemque mox πυρροὶ, πυρρῶν αὐτῷ] ei (scil. tritico) v: αὐτοῖς G: om. pd 24 ἐθέλοι G
footnote 2 &lt;καὶ&gt; om. G: et L δ’ οὐκ οὑν οὐδ’ G: propter neque ἴ’ 8 αὐτούς G: id (sc. triticum) L οὐτ’] εἶτ’ G: neque L ποιήσαντες ἑψοῦσιν G: faciendo coquere (coquentes v) L 9 δεύσαντες G: infundentes v: infundendo pd 14 μεμνῆσθαι G: meminere v: imitari (= μιμεῖσθαι) pd 24 &lt;καὶ&gt; — om. G: et — et (vel v) L 26 λεπτοῦ G: subtile v: album
footnote 19 ὀλίγον ὕστερον] § 87 et 110 (= λευκοῦ) pd 1 πολλοὶ G: multis L 2 ἐπιμιγνύντες permiscendo L 6 γλίχωνος G ὑσώπου G 8 ἄλλοις ἐδέσμασιν σχεδὸν, sed. corr. G1 9 αὐτὴ G: ipsa quidem (= αὐτὴ μὲν) L fort, recte 10 ὑσώπου G 14 πνεύμονα ex πνεύματα ut vid. corr. G1 17 αὐτῶν] αὐτὰ G: a sorbitionibus que ex condro ipsis per (secundum v) se ipsas (ipsas om. v) L 22 in ptisana solum L: fort, μόνον ἡ χρῆσις αὐτῶν ἐδώδιμος G: usus eius est esibilis v: usus eius utilis pd: possis esus eius utilis id est ἡ ἐδωδὴ αὐτῶν χρήσιμος (nam hiatus ante
footnote αὐτῶν saepissime invenitur apud Gal.) 5 χρὴ G: oportet quoniam L 7 post de alphitis vero add. quoniam pd: alfita vero omnia sunt etc. v 9 ὑγρὸν G: humidior L 
footnote 6 Μνησίθεος] Gal. VI 512, 9 88., cf. Athen. Ill 115 f. (265, 14 88. Kaibel) 2 ἕτερον &lt;γένος&gt;? 11 τῶνδε] τοῦδε G: his vp: om.   ἐπειδὴ G 23 δὲ delevi: om. L 25 γὰρ εἰς G: enim sunt secundum γάρ &lt;εἰσιν&gt; εἰς?) L
footnote 1 φάσιλοι G 11 οὐδὲν ἧττον G: nulllo minus L 12 βούκερα G 17 ἐς ἄμφω G: ἐς m hoc libello nusquam legitur nisi hoc loco, cf. Helmreich ad Gal. de temperamentis I p.13, 22 (p. 49, Aug. Vind. 1897) 21 εἰσὶ G 22 φάσιλοι G 23 δαμασκινὰ G 26 θαλάττιοι G1 Galeni de victu atten. 1. ed. kalbfleisch.
footnote 14—19 8 ὁ 194, 6—195, 1. o 156, 15—23 3 προειρημένον G 8 ἔτνος, οἵπερ G: etnum quod p: et υῆα v: unum ferculum quod d: fort, ἔτνος, ὅπερ (=   ταῖς λοβαῖς G 13 πρὸ ex πρὸς G1 ἄλυποι Οο: ἄλυπα G   δεύτεροι Οο: secumndi v: δεύτερον G: secundario pd 18 πλὴν εἰ διά μακροῦ χρόνου ὁ 19 πισσῶν ἢ φακῆς G: de pisis vel lente L: πίσσου ἢ φακοῦ Οο δή om. Ο ο L 22 ἀπό τε τῶν O o
footnote 8—10 ὁ 196, 1 s. ὁ 166, 23 s. 16—23 ὁ 195, 2—10. o 156. 24—157, 5 2 ξηρότερά τε καὶ θερμότερα Οο: sicciora et calidiora L: θ’. τε καὶ ’ξ G 9 κοττύφους G1 11 νιττῶν G 18 πύργων Οο of. VI 485, 9: turribus pv (ex turturibus p): ruribus d: πέτρων G 28 τῶν ἐναντίων GO o: contrariis v: eis que contrarium (scil. respirant aerem) pd
footnote 12—21, 15 ὁ 195, 8—197, 2. o 157, 5—24 1 2 ἐν αὐταῖς G: in se ipsis L 4 μέλλει G 5 ἀκραίων] cf. Stephani Thesaurus s. v. ἀκραῖος et ἄκρεος et adnota ad Hippocr. Epidem. I 2 p. 182, 6 7 ῥύγχη] μύτη sscr. G1, cf. Sophoclis lexicon b. v. 11 ὑπό G: in p: fort, ἐπί 13 κοττύφου G1 14 ὅσοι Οο.. ὅσα G: quecumque L 15 μαλακήν te ἄμα καὶ Οο fort, recte: mollem simul et L 19 &lt;καὶ&gt; et pd: om. Gv ταῦτα οὑν ἔχειν ἄμφω τὰ γνωρίσματα ὁ fort, recte: τ’ οὔν ἔχεις ἔχει ΑC1) τὰ γν. Ο: hee igitur due (ambe v) sint (sunt d) tibi (tibi om. v) congitiones L 20.21 τὸ μ’ τε καὶ ψ. (om. εἷναι) Oo: mollities et fragilitas L
footnote 21—22, 5 197, 2—5. o 24—27 1 γάρ delevi: ᾧ μὲν ἂν ὑπάρχῃ τὸ σ’. Ο ο fort, recte: cui utraque existunt (insunt v, utrumque existit d) L 3 θάττερον G τοῦδε O o: om. L 6 ἐξέστω G: ἵξεται (ἐξέσται editores) Ο: ἐξέσται (ἔσται BP, ἐξ ἔστι F 1) σοι o: licet L μὴ παρόντων 0 o: non presentibus L: προσφερόντων G 10 τοιαύτην delevi: om. LOo 13 αὐτῶν G: quod est in eis v: αὐτῆς οΟ (αὐτο BV in o): om. pd 19 malacostracorum (-atis v) L, cf. VI 735, 16ss.: μαλακοσάρκων G 20 vel propter solam duridem p d, sed solam om. v
footnote 5 βούγλωσσα G ψίτται G 6 τῶ ν G1 11 τοὺ σ G1 13 ἐγὒς γ G1 prope asinos vero (vero as. d, vero om. v) sunt cervi. quare (unde v) et ab horum (eorum v) esu abstinendum L: itaque fort, scribendum ἐγγὺς δὲ τῶν ὄνων εἰσὶ καὶ οἱ ἔλαφοι, ὥστε καὶ τῆς τούτων ἐδωδῆς ἀφεκτέον 23. 24 neque in asia neque in grecia (elladea v) L: Ἀσίας — τῆς om. G 25 ταῦτα G: hec v: hos pd
footnote 6—15 197, 5—10. 157, 27—158, 3 1. 2 τοῖς τῶν λαγωῶν G: ei que leporum (scil. virtuti) recte v: leporibus pd 2 post sicci (ξηρὰ) add. complexione id est τῇ κράσει L, quod fort, addendum 8 ἀκραίοις] cf. p. 20, 5 3 τοῖς ἐν ὄρεσι τεθραμμένοις G: earum (sc. gallinarum) que sunt nutrite in montibus v: montanorum (sc. gallorum) d: montana (sed praecedit corporibus gallorum) p 13 ἐργασαμένους Ο (-νοις ABC) ο: suspendendo (= κρεμασαμένους ?) L μιᾶ G et F in o: ἡμέραν μίαν O o: uno die pd: die una ν: cf. v. 21 τοὐλάχιστον 0 o: ad minus L: om. G 20 σκληρὸν ex -ρῶν G
footnote 4 existtmt (= καθεστήκασιν) L 10 κάρου G: caroti L: cf. Orib. I 87, 4a. 10 220, 12 (unde corrig. Gal. VI 654, 12. 17 794, 18). 211, 6 Buss.-Dar. 11 γογγύλες G 16 καὶ — δέ G: quamvis L : an καίτοι τοῦτό γε ? 18 Quid oportet (autem add. v) dicere adhuc (adhuc om. v) fort, τί &lt;δ’ ἔτι&gt; δεῖ λέγειν coll. § 54 in. 28 tamen (attamen v) quecumque (= ὅσα ut 15, 20 et 20, 4) L
footnote 8—17 Ο 198, 2—5. ο 158, 7—9 24—26,12 O 198, 5—9. o 158, 10—13 2 κρομύου G 9 λυποῖτο Ο ο: λυπῶτό G 10 μῶρα G κοκύμηλα G 11 πάντων ex μᾶλλον G 1 18 precokia pv: precobia d: βεβρώκια G: cf. VI 786, 17 811, 12 466, 6 585, 9 593, 8 594, 6 20 διασποιρα G sic 21 οὔοις ex ὄφοις ut vid. G1
footnote 4 et nuces, aliter (aliqualiter ν) quidem et rum (nil v) minus ad preiacentem (nobis add. v) dietam. adhuc autem pistacia (-cea 4) ad hanc quidem non sunt prava (Sunt autem et fistice adhuc non prave v) L. restituenda igitur haec fere: καὶ κάρυα &lt;ἄλλως καὶ οὐχ (vel οὐδὲν) ἦττον πρὸς τὴν προκειμένην (ἡμῖν ?) δίαιταν προσέτι δὲ&gt; καὶ τὰ πιστάκια πρὸς γοῦν ταύτην οὐ φαῦλα 8 castanee L, cf. VI 777, 16 ss.: κάστανοι G 9 χείριστοι G   ὥστε ἔχομεν G : ὥστε — ἔχοιμι ἂν Ο ο fort, recte: ut — habeam p d: unde — habeo v 13 βοτρύοις sic certo compendio G: botris L : fort. βρυτίοις coll. VI 579, 12 et Athen. 11 56 d, ubi vid. Kaibelii adnota 14 ἐθέλοις G ἐπιτιθέμεναι G : reponuntur L
footnote 13—16 O 197, 10—198, 1. o 158, 3—6 3 fort. ἔχοι, cf. index s. v. κἂν εἰ 10 ὑπηλάχθαι G 16 κητώδεις O o: cetodeos L : σκληρώδεις G 20 &lt;ἢ καὶ&gt; addidi: vel v: et pd: om. G 26 ἐπιτεχνάσθω G : mgeniare (-ri v, vigilare d) oportet L
footnote 2. 3 ὁ 198, 1 s. ὁ 158, 6 s. 8—10 ὁ 198, 9—11. o 158, 13—15 9—16 200, 11—201, 2. 159, 11—13 3 κρεῶν Οο: camibus L: om. G 8 μόνον] non v 9 [καὶ] om. Οο : καὶ οὐκ et μόνον (10) et πομάτων om. L, praeterea ἄλλα καὶ om. pd 11. 12 οἳ ἂν ὧσι γλυκεῖς scripsi: que dulcia L : οἱ γλυκεῖς Οο: κἂν εἰσὶ γλυκεῖς G 17 καὶ e corr. G 1 18 καὶ αὐτὸ τινὰ G : et quandam et ipsa L: fort, καἰ τινα καὶ αὐτὸ 22 certitudinaliter mature (= ἀκριβῶς πέπονα?) L 23 εἰσὶν G neque — neque L: οὐδὲ — οὐδὲ G
footnote 21—30,11 O 198, 11—13; 202,3—6. 158,15 s.; 159, 25—160, 2 1. 2 τῆς μέσης ἐστὶ κατωτέρω] inferiores a media stmt (a. m. s. i, v) L: τῆς παχυνούσης ἐστι κατωτέρω G 2 γὰρ εἰσὶ G 10 ὧς ὀπῶραι μᾶλλον G: ut opora solummodo (= μόνον, recte fortasse) pd : ut sunt v 11 σηπόμενα G : propter (per d) superfluam enim humiditatem faciliter putrefiunt pd, unde comcias διά &lt;γάρ&gt; ’π’. ὑ. σήπονται ῥᾳδίως: sed putrefientes omisso exhibet v 16 Parum autem gustabit quis de vinis dulcibus pd: minime autem inveniet quis fortassis vina esse dulcia v: unde γλυκεῖς recipiendum esse videtur pro παχεῖς, sed ὑπίδοιτο verum esse existimo. cf. 24, 13 et 25, 1
footnote 1 τοὺς παχεῖς χυμοὺς O o: grossitiem L: τούς χυμούς G 6 εἰσὶ δὲ oὐ πολλοὶ G: sunt autem talia multa (-tumd) pd: sunt autem plurima guidem v: itaque aut οὑν aut &lt;τοι&gt;οῦ&lt;τοι&gt; scribendum esse videtur 9 θυραῖος G καὶ ὁ Θ. om. L 14 ἄλλως G ex ἄλλοις, quod yertit L cephalea vel emicrcmea L : κεφαλὰς . . καὶ ἡμίκρανα G 18 ὀνίνανται G 19 ἐκκαθαίρεσθαι δέονται G : purgantur (exp- v) L 25 καὶ οἱ post οἴνων iteravit G
footnote 7 παμφιλίας G 8 quod et skibellitum (kibellicum d) nominatur pd: et skinelitum nominatum v: καὶ ὁ σκυβελίτης ὀνομαζόμενος G: cf. VI 582, 16. Aretaeus p. 322, 5 s. k. (Σκυβελλίτῃ τῷ Παμφυλίῳ). Hesychiua s. v. Κέσκος (Σκυβελίτης ἀπὸ Σκυβέλων τόπου Παμφυλίας) 9 ἔχειν εἰς τοὺς δμοίους ἅπαντας G: proponendo (supp- v) adinvenire et iudicare ab eo aimilia (omnia sim. v) L (= προθέμενον προσευρίσκειν καὶ κρίνειν ἐκ τούτου τ. ὁ. ἅ. ?) 11 θυραίω G : thireo L καὶ προτρόπω G : G: protropo v: eo (eodem d) modo pd 12 σιραίῳ G : thi- vel thyrino L id est Θηρίνῳ, quod haud scio an recipiendum sit coll. VI 801, 6 et XV 632, 6 ὀνοβάστην G: anate (-te v) L: legeudum esse existimo Ἀβάτην coll. VI 800, 14. O 345, 1. Athen. I 33 b. idem nomen in Ἀναβάτης corruptum XV 645, 11, in Ἀλβάτης Χ 833, 15, in Συβάτης VI 337, 14
footnote 5—12 O 345, 5—11 1 ἐξ αὐτοῦ ὠνεῖσθαι G: ipsa emere v: emere ca pd 2 σπουδάζεσθαι supra vers. m. pr., πιπράσκεσθαι in versu G: habeantur studio (cure v) L 4 convivia L 5 sacrificia L 5 6 πλήσμιός ἐστι (praeced. ὁ οἶνος) Ο: repletionalia sunt L: at hiat πλήσμιοί &lt;εἰσι&gt; 6 δία | διαχωρήσεις G 8 αὐτῶν αὐταῖς G : om. LO καὶ μεσάραιον delevi: om. LO 9 μένουσι G : ἐμμένει Ο: immorantur pd: permanent v: fort, ἐμμένουσι 12 πινόμεν G: bibta pd: cum . . bibuntur v &lt;οὐκ ὀλίγος&gt; om. G : non paucum L 12. 18 in egis L: ἐν γαῖς G : cf. XV 645, 10 15 Περπερίναν cf. XV 645, 10 VI 800, 11. 16 804, 18 337 15 (unde corr. X 833, 16) 20 πινόντων G: bibentium v: famescentium (= πεινώντων) pd
footnote 2 χοιρέων G 3 ἐδωδῆς] hic desinunt versiones latinae 11 f G 12 οὐδ’ ἂν scripsi: οὐδὲ G 16 αὐτὴν potius quam αὐτὰ G: sensus hie fere τῶν μὲν πρώτων τε καὶ δι’ αὐτά, &lt;τῶν δ’ ὧς βλαπτόντων τὰ&gt; αἱρετά 17 &lt;μέσον&gt; addidi coll. 19 an ὑγιεινὸν &lt;ὂν&gt;? cf. § 53 20 &lt;μὴ&gt; scripsi: φύγομεν G: fort. φεύγωμεν 24 φύγειεν G 
footnote 1 post συγχωρητέον add. αὐτοῖς· G, del. G 1 3 ποιούμενος G : cf. XV 543, 11s. VI 85, 2 8. 223, 4 s. 10 διακείμενα G1
footnote 1—6 198, 14 s. 394, 2—4. 158, 16 s.6—14 O 394, 2—395, 1 22. 28 ὁ 198, 13 s, ὁ 158, 16 s. 1 οὕτω G ἂν εἴη G: φανείη Ο 394, 4 3 γοῦν scripsi: οὑν G 4. 5 fort, τούτῳ &lt;γ΄&gt; οὐ 8 ἀπάντων om. Ο AC in Ο : ὑπάρχει G et BV in O τμητικώτατον fort, recte 9 οἴνῳ χρῆσθαι G : χρῆσθαι καὶ οἴνῳ Ο fort, recte 18 γενομένους Ο: γινομένους G
footnote 1ἀρμόσσει 3 προειρημένοις G 11 ὁσώπου καὶ γλίχ G 14 γάλατι G 21 παχυχυμώτατον G utrobique &lt;μὲν οὖν&gt; addidi 28 &lt;τὸ&gt; scripsi: καὶ
