@node
@author=Origenes
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=open tag without further specification. See the name of the .tf-file for it's meaning
@editor=Hermannus Mutschmann
@filename=tlg0544.tlg001.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane, Monica Berti
@publicationStmt=University of Leipzig, TO BE ADDED BY LEIPZIG.
@respStmt=Digital Divide Data, Corrected and encoded the text, Greta Franzini, Project Manager (University of Leipzig), Simona Stoyanova, Project Assistant (University of Leipzig), Bruce Robertson, Technical Advisor
@sourceDesc=SEXTI EMPIRICI OPERA, HERMANNUS MUTSCHMANN, HERMANNUS MUTSCHMANN, IN AEDIBUS B. G. TEUBNERI, LIPSIAE, MCMXII, vol. i.
@sponsor=University of Leipzig
@title=SEXTI EMPIRICI OPERA
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T15:13:43Z

64012	footnote Argiimentum primi libri in codicibus misere foedatum correxi secundum titulos 3 διανωτάτω G 15 ὁλοσχερῶς L 19 τίνες τρόποι τῶν αἰτιολογουμένων ἀνατροπῆς G 21 περὶ τοῦ οὐδὲν μᾶλλον G || φωνῆς addidi 23 περὶ τοῦ ἔξεστι καὶ τοῦ τάχα G
footnote Argum. 3 καταληπτά G 4 καὶ οὐ κατ. om. G 5 λόγῳ — ἀντικεῖσθαι om. G 6 τῆς σκεπτικῆς φωνῆς G 11 ὁ πρωταγόρειος τῆς σκέψεως εἰ διαφέρει ἡ scr.: ὁ G 13 τὴν om. B Textus 13 ὑποτυπωτικῶς om. T 14 προειπόντες Τ (predicentes): προσειπ’. G
marginal 15a
footnote § 7 ~ Diog. Laert. IX 69. 70. 1 πρῶτον LM: πρώτου EAB 6 τῶν σκεπτομένων Gen. 7 γινομένου LM: γενομένου EAB || γιν. πάθ’. om. T 10 τὸν om. Gen. 11 προσελ. LM: προελ. 13/14 τρόπον MEAB: τρόπων L
footnote 21 τῷ Fabr. : τῶν Gr: τὸ Gen. 23 post φαινόμενα add. ἢ EAB 24 post νοούμενα add ἢ AB 26 ἢ—τρόπον om. EAB || τε EAB: om. LM 30 ἀπόφασις καὶ κατάφασις L 3 ἡ MEAB: τῆ L 9 οἱ γὰρ MEAB: οἱ μὲν L 11 μᾶλλον χρῆ Μ
footnote 13 EAB 15 ἴσον om, EAB 18 post ὃ inser. καὶ edd. 19 ἐνδοκεῖν L 21 ὁ ἐπισκεπτικὸς EAB   ἡ ex εἰ L: εἰ EABM 6 malim προφερόμενος || δυναμένας Kayser 7 fort. τούτων &lt;οὗτος&gt; Diels 8 τῶν om. EAB
marginal 15a
footnote §§ 16—17 ~ Diog. Laert. I 20. Suid. s. v.αἵρεσις. 12/13 αἵρεσιν ἔχει MEABT (sectam habeat): ἔχει αἶρ’. L 13 γάρ add. T (si enim aliquis vel sectam) 15 τὰ add. Bekk. λέγει—συγκ. om. Τ. 15/15a δόγματι ἀδήλω G correxi p. 5, 23/24: δόγμα τινὶ ἅδ’. Gen. 16 φάσκοι EABT (dicat) 18 δοκεῖν fort. secl. 21 αἵρεσιν &lt;δέ&gt; EAB 25 παραπλήσια καί om. EAB
footnote 1 ἀναιροῦσι om. EAB 3 παθητικὴν LMT (fantasiam passibilem) : παθητικὰ EAB 4 ἄγοντας EAB 10 μὲν addidi   τὸ add. coll. v. 8 || καὶ ἄντικρυς om. T 14 τὸ φαινόμενον EAB Gen. 19 αὐτῶν L 24 οὖν EAB 26/27 λέγομεν κρτήριον εἷναι· φαμὲν εἶναι περὶ τῆς σκ. EAB 28 &lt;αὐτοῦ&gt; οὕτω Fabr. e codice Saviliano
footnote §§ 25–27 ~ III 235–237 31 ἀμφισβητήσει Τ (dubitabit): ἀμφισβητεῖ G 2 αὕτη ἡ βιωτικὴ LM: ἡ βιωτικὴ αὕτη E: ἐν βιωτικὴ αὕτη (sic) AB 3 μέντοι EAB 7 ὁδηγεῖ ἡμᾶς M 14 διεξελθεῖν LM: διελθεῖν EAB
footnote 27 et pluribus T 28 καὶ &lt;τὸ&gt; LEAB edd.   Gen. (sic) e Yesontino 409 vel cognato aliquo libro 22 a (in titulo): σκέψεως Gen. 23 ἐπεὶ M: ἐπὶ LEAB 24 ἂν εἴη λέγειν MEAB: εἴη λ. ἂν L
marginal 5a
footnote 27 post φαινόμενα add. ἢ EAB, post νοούμενα add. ἢ AB 4 suppl. e T (construenti) coll. p. 9, 31 8 ἐρωτήσει L Gen. 10 ἡγησάμενον EAB 13 ὑποκείσθω EAB 15 δοκοῦν EAB
footnote §§ 36—163 : cf. Diog. Laert. IX ξ 79—88. Philo de 171 sqq. (cf. v. Arnim Quellenstudien zu Philo p. 59 sqq.) Aristocles apud Euseb. Praep. Ev. XIY 18, 11 sqq. §§ 40—78: cf. Diog. Laert. IX ξ —80 Philo de ebr. 171. 23 τύπους GT (figuras): τόπους edd. : τρόπους Kayser || συνωνύμως Μ: συνωνύμους LEAB 27 θέσεις ML: διαθέσεις EAB 31 fort. συγκυρήσεις sicut p. 33, 4. 2 θετικῶς om. T 5 κρίνειν · 6 ἢ ἐν scripsi: καὶ ἐν GT 7 add. Pappenh. 8 ὁ ἕβδομος post ὁ ἕκτος iterum EAB 10 ὧς—τι om. EABT 11 ἐννέα Kayser 14 εἶναι ἐλέγομεν EAB || παρὰ add. Gen.
footnote 15 ἀπὸ τῶν αὐτῶν om.T 18 ὀνομάτων EAB 19 et 20 μίξεων M 21 ζωΰφια Bekker: animaliaparvulaT: ζωόφθτα G 23 lac. stat. Fabr. addens ὡς μῦς 26 οἱ om. Μ 28 μὲν &lt;ὡς&gt; EAB 5/6 seclusi ut glossema ad p. 11, 14 7 καὶ ὑπόφασμα EAB 14 λάμπ’. ἐν τοῖς ὀφθαλμοῦ ἔχει LE (sic): ἐν τοῖς ὀφθαλμοῖς λ. ἔχει AB: λ. ἔχει ἐν τοῖς ὀφθαλμοῖς M
footnote 15 ἀπ’ αὐτῶν om. T 21 ἀλογώτερον Gen. 22 add. e Τ (et differentes) 28 οἴα Μ : οἶς LEAB 29 αὐτὰ EAB : αὐτὴν M : αὐτ’ ἃς L 1 ἀγγείων G : ὀργάνων iam a Bekkero coni. T (instrumentorum) atcf. Philoleg. alleg. Π37 (Ι 97, 28Cohn) 1/2 προπέπτωνκεν ΕΑΒ et Μ (ommisso τ) T (procidunt) : πέπτωκεν L edd. 4 ὅμοια LE AB : ὁρᾶν M 5 ὁρᾶν om. M 13 τὰ ante ὧτα om. EAB || καὶ G : ἢ T (vel)
footnote 15 παραβύσαντες MEAB: παραβήσαντες L 21 εἶναι et EAB (comp. script.): ταῦτα L 25 εὔλογον Salmasius: εὔλογα G: rationabile est Τ 26 αὐτῶν om. T 28 εἴγε καὶ ἡμεῖς MEABT (si quidem et nos): καὶ ἡ. εἴγε L 29 fort. coll. p. 13, 12. 14. 24. 27. || καὶ: ἢ Pasquali 30 παρὰ ΜΤ (secundum): περὶ LEAB 2 λαμβάνοι L: λαμβάνει MEABT (assumit) 6 αὐτὴν MEAB : αὐτῶν L 10 post αὐτὸ add. πνεῦμα MEAB
footnote 20 ἀνθρώποις om. EAB 22 τε GT: δὲ edd. 28 &lt;ἢ&gt; καὶ θάν’. (aut et) Τ 29 αἳ L : ἃ MEAB 31 δὲ (vero) T 34 ἀναρρώνυται Pasquali coll. Aelian. h. a. II 9 1 μόνον Bekk. : μόνου G II φυγοῦ LEAB 4 δὲ om. Τ 7 εὐηδὲς L 10 ζώων ML: νόμων EAB
footnote 12 οὐ (non) Τ 18 τῷ Μ: τὸ LEAB 21 προοισόμεθα G: producemus T: προσησόμεθα a Gen. coniectum recepit Bekk. 30 οὖν ML : γοῦν EAB || αἱ om. EAB 1 τὰ ἅλ’. ζῷα οὕτω EAB 6 εὑρεσιλογοῦντες Gen.: εὑρεσιολογοῦντες G 8 παίζειν ἔχοντες Kayser 11 ὧς om. Τ
marginal 20a
footnote ξ 65 cf. Porphyr. de abstin. III 2 23 &lt;καὶ&gt; add. e T (et in eo quod est circa coll. p. 17, 17. 28 τοι L: τι MEAB 30 γε LM: om. T: τε E AB 1 δὲ G : μὲν (quidem) T 4 ὄντα G: εἶναι T (esse)   συμπολεμοῦντα scripsi: πολεμοῦντα GT (qui maxime repugnat): προσέχοντα Diels
marginal 19a
marginal 24a
footnote 11 ἀναποδείκτῳ Apelt coll. Plut. de soll. anim. p. 969 B (vide p. 93,11): ἀναποδείκτων G: per plura inmittere quinto indemonstrativo T 12 ἐλθὼν MT (ueniens): ἐλθεῖν LEAB 14 ὁρμήσῆ Bekk. : ὁρμήσει G 16 οὔτε τῇδε Τ (neque hac) : ἢ τῇδε G 20 δυσαληθῆ L 22 τῶν γινομένων h 24(??) ἄσκυλον EAB 31 εἴη τοῦτο κατὰ τούτου EB : εἴη τοῦτο κατὰ τοῦτο A 3 τῇ om. L II παρὰ M: περὶ LEAB
footnote 17 παρὰ τούτῳ Gen.: περὶ τούτω MEAB: περὶ τούτου L || τε MT (m eo quoque et): om. LEAB 24 ἀλόγων om. T 25 ἀποδεικνύειν Gen.: ὑποδεικνύειν G || δυνατὸν om. EAB 32/3 ἔμπροσθεν secl., fort. ἐν τούτοις 2 ἀλλ’ om. M
footnote §§ 79—89 cf.Diog. Laert ξ 80—81. Philo de ebr. 175 sqq. 9 συγχωρήσῃ EAB: συγχωρήσει MLT (concedet) 11 τὴν om. L 15 μὲν om. Τ 17 παρὰ δὲ MT (cecundum autem): παρὰ LEAB 17 ἐπικράτεια — 18 χυμῶν om. L 20 ταῦτάτοι G: quapropter T 21 κατὰ τοὺς ἀνθρώπους Kayser 28 καὶ om. Τ 31 ἐνεθάλπετο EAB 33 Ψυλλαεῖς G: Ψύλλοι iam desid. a Salmasio praeb. T (psilli) || post ὄφεων M add. ἢ σκορπίων 1 Τεντυρῖται Fabr.: Τιντυρῖται GT (fintarite) || προσνηχόμενοι ἄνω κάτω Diels
marginal 29 a
footnote 2 ἄνω κάτω ab Apeltio olim deletum omisit T (non leduntur a crocodilUs) 3 Ἀστάπουν olim ab Herchero inventum praeb. T (astapum): ὑδάσπην G edd. 7 χύσερμος EAB: chrisormus Τ 8 καὶ om. T 11 ποταμόν M 13 ᾧ T (cui videbatur) cf. Aristot. l..: ὧς Paris. suppl. 133: ὃς G   τῶν om. M 27 τε add. Schroeder 28 βιοτά L: βιωτά M: βιωταῖς EAB 29 οἶδμα G 29 (??) θοὰ LMT (naui ueloci): θοσῶν EAB: θοᾷ σῶν Gen. : θοᾷ σῶς Fabr. || διαμείβων Maas: διαστείβων G: pergens T
marginal 29b
footnote 4 γε LM: τε EABT (quoque) 11 αὐτὰ add. Bekk. 12 εἰσάγετ᾿ EAB 15 κατὰ δύναμιν delevi 16 τοῖς om. M 20 Ἐπικούρειος a Stephano restitutum praeb. Τ (Epicurius) et Paris. suppl. 133: Ἐπίκουρος G 23 προοίσεται M: προοίεται LEAB: infert Τ: προσίεται edd. || οὐδενὸς τῶν ἀνθρώ-πων M
footnote §§ 90—99: cf. Diog. Laert. IX 81. 29 τινὰς — ἀλγεῖν om. Τ 31 ἀναγκαίων L || διὰ MEAB : ἐπὶ L 6 τὸ ζητούμενον Τ (quod queritur subripiunt) : τὰ φαινόμενα G edd. 7 ἵνα om. M 10 πρόχειρ’. ML (cf. p. 115, 1 e. a.): ἐγχ. EAB edd.: proponimus T ΙΙ δ’ ἐλέγομεν Diels: δὲ λέγομεν GT (autem dicimus) cf. p. 33, 5
footnote 27 ὁποῖον — 28 λέγ’ εἰν om. M 29 τ. τρ. delevi 32 ποτε om. Τ 33 μόνας ὄντως ἔχει L: μόνας ἔχει ὄντως Μ: μόνας ἔχειν EAB : solas vere ipsum habere Τ 4 μὲν om. EAB 7 ἐν delevi 8 ἐμπν. rest. e Τ (aspiratione) coll. p. 14, 10. 10 τἀς διαφορὰς EAB 12 τὸ μῆλον om. EAB
footnote §§ 100—117 Diog. Laert. IX 82. Philo de ebr. 178 sqq. 29 εἰ Gen. T (verum etiamsi): om. G cf. p. 6,4. 30 μόνας Bekk.: πλείονας GT (plures): πάσας Stephanus (omnes) 31 ἢ καὶ πλείους Kayser 32 τὰς ἡμῖν om. Μ || ἐστι om. EAB 33/1 ante λόγος inser. ἡμῖν M, ὁ L 1 suppL e T (ductoribus eum fallentibus) cf. p. 30, 11 5 στάντες Gen. Fabr. 6/7 Καταλλαγὴν L 11 ἔχειν addidi coU. p. 24, 16. 14 ἢ a Bekkero deL om. T 17 θεοφρουρούμενοι L 18 ἀπὸ φορᾶς EAB Gen. Fabr.: odorem Τ
footnote 23 κιρρόν Fabr.: κορρόν G 25 λέγοι T (dicat) || τινων om. L 29 τῇ φύσει G cf. p. 39, 10: φύσει edd. 31 μεταβάλλει post χυμοῖς add. M 5 ἔχοντες EAB 9 &lt;τὸ&gt; εἷναι ci.: quare esse et nonesse fii eis T 10 αὐταῖς Apelt: αὐτοῖς G 11 ἐγρήγορσιν &lt;γίνεται&gt; Pappenheim 12 ἀνύπαρκτα ἐν τῷ ἐγρ. MLT (que sunt non existentiam in devigilando) sic: ἐν τῷ om: EAB: ἐν τῷ εγρ. ἀν’. edd. 13 ἐν τῷ delevi: οὐ καὶ τὸ καθ’. Diels colL p. 565,16 15 ὅτι Τ (quia) edd.: ἔτι G
footnote 17 χρῶμα Bekk. : βρῶμα GT (cibus) 24 ἀπὸ Pappenh. coll. p. 58, 28. 27 πλέοντες Τ (navigantes) v. 34 om. Τ sed addit etc. (cf p. XI) 1 δὲ quod iam Bekk. ci. addit Τ (etiam et) ΙΙ ἔχοντες om. T 4 περὶ EAB 8 γίνεται M 9 εἶναι δοκεῖ om. T 14 περὶ δὲ τοῦ EAB
marginal 16/7
footnote 16/17 περὶ EABT (circa) 18 καὶ ἄλλοτε — 19 μὲν om. EAB 8 ἄλλως MLT (aliter) cf. Philo de ebr. 176: ἄλλων EAB 21 ἔστιν om. T 24 τὸ — 25 κινεῖται om. EAB 29 ἔσται T (erit): ἐστὶ G 33 ταῖς Τ (hiis que sanorum sunt): καὶ τἀς G 7 πάντως om. Μ ΙΙ κρινεῖ κριτηρίῳ EAB 9 ἄπιστος Bekk. : ἄπιστον GT (incredibile) 10 λέξει — 11 μετὰ ἀποδείξεως om. EAB 11 εἰ LMT (si): ὁ EAB
footnote §§ 118—123 : cf. Diog. Laert. IX 85—86. Philo de ebr. 181 sqq. 14 εἰς &lt;τὴν&gt; L edd. 20 καὶ ἵνα EAB 26 καὶ add. Stephanus 30 περὶ EABT (de): παρὰ LM || καὶ om. Τ || ὅσον MT (quantum): ὃς LEAB: ὡς Gen., del. Kayser 4 μείουρος A: μύουρος LMEB 10 ἀμαυρῶ L 13 λυνγούριον et λυνγί LM
footnote §§ 124–128 cf. Diog. Laert. IX — 85. Philo de ebr. 189 sqq. 15 γίνεται M (sicut p. 26, 8) 21 τόπῳ post τινι dubitanter Bekk., at cf. p. 29, 7 || καὶ alt. GT: ἢ edd. 22 περὶ EABT (circa) : παρὰ ML 24 τούτου τοῦ τρόπου Bekk. : τούτους τοὺς τρόπους GT (hos modos) 28 βουληθήσεται A 30 αὐτὸν L 31 δεῖ MLT (oportet)" δοκεὶ EAB 1 ἐστιν Τ (est): ἔσται G || περιστῆσαι EAB 7 τῷδε &lt;τῷ τόπῳx003E; dub. Bekk. at cf. p. 28, 21. 11 καθ’ ἑαυτὸ ἡμῖν MEBAT (secundum se ipsum): αὐτὸ ἡμῖν L
footnote 12 post ἡμῖν edd. 18 et 19 σὺν T (cum) 19 ἐν om.EAB II rcSdelevi: ἐν καταψύχρῳ Bekk. dub. 4 διαφορήσεσιν Μ : productionibus T 4 αἵ — 5 τόπων glossema? 6 χυμῶν Kayser (cf. V. 14) 11 sensus ductores eius fallunt T (vide p. 24,2)
footnote §§ 129–134 cf. Diog. Laert. IX 86 (hic octavus modus). Philo de ebr. 189 sqq. 13 post ἕκαστον inser. ποιεῖται EAB 14 εἶναι δοκοῦσιν MLT (putant esse): ἔχει. καὶ ὁποῖον εἷναι δοκ. EAB 27 τὰ μέρη GT (partes scilicet lineatura): seclusi 28 ὡς om. Μ 29 ταιναρείας Gen. : ταιναρέας L: ταιναρίας EAB: τεναραιεας Μ: tenarii lapidis Τ 1 κριμνώδης Fabr. : κριμώδης G 3 παραπλ. om. Τ 5 καθαίρει GT (purgat): καθαιρεῖ Fabr.
footnote §§ 135–140: cf. Diog. Laert. IX 87–88 (hic decimus modus). Philo de ebr. 186 sqq. 8 λεπτῶν μερῶν Stephamis: suhtilibus partibus T 10 μικρῶν μερῶν Stephanus: parvis partihus Τ 13 τρυφῆς L 19 &lt;καὶ&gt; μάλιστα T (et maxime) 21 ῥοπῆς LM: τροφῆς EAB 24 συνέχει T (continet) 30 ἀπολύτως GT (ansolute): ἁπλῶς Gen. Fabr. 4 κρίνειν EAB 5 πρὸς LM: παρὰ EAB
footnote 10 καὶ τόνδε τὸν τρόπον del. Kayser: τόπον pro τρόπον Pappenheim ΙΙ τήνδε τὴν σύνθ. M 15 διάφορον EAB 17 τε Bekk.: δὲ GT (autem) 29 πάντα εἶναι LMT (omnia esse): εἶναι πάντα EAB II &lt;μὴ&gt; εἶναι πάντα Pappenheim || εἶναι δείκνυσι MLT (esse ostendit): ἀποδείκνυσι EAB 30 &lt;εἰ&gt; οὕτω coni. Kayser 2 9 add. e Τ (quod sequitur) || ἀκολουθεῖ LT: ἀκολουθεῖν MEAB 3 δι’ ἡμας EAB
footnote §§ 141—144 cf. Diog. Laert. IX 87, deest apud Philonem. §§ 145–163 cf. Diog. Laert. IX 83–84 (hic quintus modus) Philo de ebr. 193 sqq. (cf. v. Arnim, Quellenstudien zu Philo V. Al. p. 66). 5 ἐλέγομεν εἶναι Τ (dicebanus esse): εἶναι λέγομεν G 9 καὶ om, T 18 καὶ GT: μὲν Gen. Fabr. 19 εἰ om. L 27 δὲ om. EAB 1 πρὸς del. Kayser: pertinet ad T
footnote 7 a concivibus Τ (σθμπολ.?) 8 ἢ T (vel): ἡ G 9 ὁ — 11 δὲ bis EAB 18 ἢ add, Τ (aut) at cf. Doxogr. gr. p. 312, 4 Diels 24 ἄλλων G: Ἑλλήνων Τ (grecorum) || τοῦτο εἶναι L: εἶναι τοῦτο M: εἶναι EAB 30 τὴν &lt;τοῦ&gt; EAB 31 τοῦ om. M 33 λέγωμεν add. Τ (dicimus) cf. p. 35, 3. 8.
footnote 3 δὲ om. L 11 μασαγέταις LM || ἐν addidi colL p. 33, 19 13 μὲν om. EAB 16 γαμεῖν Τ (in uxores ducere) 18 ἱππαρχίᾳ G: Praxarchidi Τ 19 ἀπὸ ἐξωμίδος GT (ob exomide) inusitatum, atforsitan rectum: ἄπο &lt;δύσ τῆς&gt; ἐξωμίδος conieci colL Aristoph. Thesmoph. 656: ἀπεξωμίδιος vel ἁπλῆ ἐξωμίδι Pasquali 20 ὡς om. Τ (quando) 23 consuetudo est Τ || ἀπειθεῖς EAB 27 λέγῃ Bekk.: λέγει GT (dicit) 28 ἡγῆται L: ἡγεῖται MEABT (putat) 30 ἡγώμεθα ME AB : ἡγούμεθσι LT (arbitramur)
footnote 31 &lt;εἶναι&gt; νόμῳ EAB ΙΙ ὅταν Bekk.: οὕτως GT (sic) ΙΙ νόμου &lt;μὲν&gt; ὄντος Τ (lege quidem existente) 38 τύπτωσιν Bekk.: τύπτουσιν G 2 ἑαυτῶν EAB ζῆν post μέτρ’. add. dubit. Bekk. || προῃρημένος L: προειρημένος Μ: προειρημένως EAB: moderate discretus T 9 τινος add. T (tamquam honum aliquid)   φαύλην Μ: pravam rem Τ 14 et 17 κωλύῃ Bekk.: κωλύει GT (prohibet) 17 μυθικὴν δογματικὴ δὲ πίστιν ὑπολήψει EAB 21 λέγῃ Bekk.: λέγει GT (dicit) 22 ᾖ add. T (est) 23 lacunam post ὅταν statui ΙΙ τὸν EAB: τὸ Μ: om. L
footnote 164–177 : cf. Diog. Laert. IX 88–89 (οἱ περὶ Ἀγρίππαν). 3 οὖν EAB : om. LM : sic igitur T 7 τοῦ LEAB : τῶν Μ ἀπὸ τοῦ om. T (qui est ad aliquid) 8 τὸν post τέταρτον om EAB 18 κρῖνον MEABT (id quod iudicat): κρίνειν L
footnote 26 τοῖς L || τοῦ om. EAB 32 οἱ δέ τινα — 33 νοητά om. ABT 2 λέγομεν scripsi : ἔχομεν GT (hahemus) 5 στήσομεν T (constituemus) : στήσωμεν G 7 προσδεήσεται Μ 9 τοῦτο om. T 12 ὂν ML: οὖν EAB: om. Τ 13 si enim Τ 16 ὁ δὲ ἄλληλος L 19 εἰσαχθήσεται Τ (introducetur): εἰς ἀπόδειξιν G || et modus Τ 20 erit Τ
footnote 25 EB: κατεσκευασμένων A 28 sermo erit Τ 29 ἔσται καὶ om. T 4 ὑπὸ ML: ἀπὸ EAB 8 ὁ ἐξ ὐπ’. scripsi coll. T (qui ex siipponere aliquid): ἐξ ὐπ’. ὁ G 9 νοῦν νοητὰ Τ (ad intellectum enim intelligibilia) : νοοῦντα Gr cf. p. 38, sp. 13 ἐπέχειν Salmasius post Stephanum: ἐπελθεῖν G: ἐπεξελθεῖν T (pertransire) 14 παρὰ Gen.: περὶ G: a Τ 16 καὶ om. EAB || τούτων Τ (per hos): τοῦτο G
footnote § 180 sqq.: cf. Phot. Bibl. 212 (p. 170b 17–22 Bekk.). 20 suppl. eT ex alio rememorantes quia neque ex se ipso quid neque ex alio cf. p. 80, 15 23 αἰσθητικῶν EAB 26/27 διαπεφ. εἶναι ἄπιστον Τ (quod omne . . . . . dissonans incredibile est): ἄπιστον εἶναι διαπεφ. Gr 29 καταλαμβάνεται L   καταλαμβάνεται T (ex quo apprehenditur aliud): τι καταλαμβάνειν G (sed M κατ καταλαμβάνεται) ενν || αὐτοῦ EAB 3 ἢ add. T υeἰ ex se ipso vel) 3/4 et dubitamus T 5 δίχα LEAB: δι’ M: om. Τ καὶ ἀποδείξεως?) 8 τούς om. Μ || τῆς add. Bekk. 10 invenimus Τ
footnote 11/12 Αἰνησίδημος Fabr.: ὀνησίδημος G: onisidimus T 14 τρόπον om. Τ (iam del. Kayser) 22 νομίζηται EAB 28 convenientia Τ 6 ἀπαρκοῖεν Kayser: ἀπαρκοῦσι GT (sufficiunt) 11 διάφωνον Bekk.: διαφωνεῖ G
footnote 12 et 16 λαμβάνειν EAB 15 εἰσάξει Kayser 19 τούτων τε om. EAB || τῶν om. Μ 20 &lt;τινες&gt; φωνάς τινας EAB 24 δὲ om. L 32 διπλῆ δυνάμει L: δυνάμει διπλῆ EAB: duplicem potentiam T || δυνάμει φαμὲν om. M || ἑστία G: domum Τ (fort. οἰκία cf. Lys. I 9): ἐσθὴς Fabr. : ἀπερίστικτος vel ἄστικτος Pappenheim 1 πλατεῖα et πλατεῖα ὁδός Diels: πλατεῖαν et πλατεῖαν ὁδόν GT (latam et viam latam) 4 τὸ οὐ Paris. SuppL 133: τοῦ οὐ G: pro inter-rogatione et non pro quid hoc quam hoc Τ Ι &lt;ἀντὶ&gt; τοῦ ego: τὸ G ΙΙ locus non integer: ἀντὶ ἀξιώματος τοῦ ὁὐ μᾶλλον᾿ πύσμα τὸ ‘τί μᾶλλον᾿ , οἷον τί μᾶλλον τόδε ἢ τόδε Bekk.: ἀντὶ τοῦ ‘διὰ τί᾿ πύσματος τὸ ‘τί μᾶλλον τόδε ἢ τόδε᾿ Kayser 7 ἀντὶ om. EAB 11 τί add. T (propter quid) 16 ἰσοσθένειαν Tsnp-penheim: ἰσότητα GT 16/17 ἰσότητα τὴν add. Pappenh. 17 πιθανὸν &lt;καὶ ἀπίθανόν ἐσότητα&gt; E. Weber 19 γοῦν Gen.: οὖν LEAB: om. Μ: igitur T || ἐμφαίνῃ MET (licet ostendat): ἐμφαίνει LAB 23/24 συγκ. om. T 24 γὰρ add T. (propositum est enim nohis) 29 fort. περὶ ταύτης?
footnote 31 post κοινῶς inser. τε L 1 ἄρνησιν AB 2/3 σημαῖνον (sic) L 5 ἐλέγομεν T (dicebamus) 6 οὔτε T (neque): οὐδὲ G   τοῦ ἀδήλου dub. Bekk. 22 μονομαχοῦμεν EAB 23 ταὐτὰ Pappenheim dubit.
footnote 7 &lt;τὸ&gt; αὐτὸ τὸ EAB 11 οὔτε EAB 14 ἀπαγγελτικῶς, οὐ δογματικῶς T (assertive non dogmatice): οὐκ ἀπαγγελτικῶς Gr cf. ῥ’. 45, 26/7. 22 προύχοντα Gen.: προϋπάρχοντα GT (preexistentia)
footnote 24 Τ 25 ἢ primum T (uel quo ad me): τὸ G 27 παρὰ τοῖς add. Τ (eorum que a dogmaticis queruntur) coll. p. 44,   τῶν δογματικοῖς ML (sic):· τοῖς δογματικοῖς EAB: τῶν δογματικῶς Bekk. 32 ἐμοὶ &lt;φαίνεται&gt; Kayser coll. p. 45,   296, 26. 2 τὰ om. EAB || τοῖς om. M 9 ἡ ὑπολαμβάνω EAB 14 ἴσος om. T
footnote 17/18 τῶν ἐγκλημάτων Μ 23 ζητουμένῳ Gen.: ἐζητημένῳ ML: ἐζητουμένω EB: ἐξητουμένω A 27 ὅ — πάσχοντι om. Τ 28/29 ἴσον ἀντικ. ML: ἀντικεῖσθαι τὸν ἴσον EAB: ἴσον om. Τ 4/6 αὐτῆς EAB 8 de tot autem T 14 συμπεριγρ. T (eircum-scriptas cum illis) : ἐμπεριγρ. G
footnote 20 ἄλλως Bekk.: ἀλλ’ ὧς GT (set sicut) 22 καὶ ὡς Kayser: καλῶς GT (pene) 29 τὰ μέρη GT (partes): malim τὰς ἀρχὰς cf. p. 3, 21. 10 ὀνησίδημον G: enesidimum Τ cf. p. 40, 12.
footnote 16 τούτους ML: αὐτούς EAB: ad quos ita dicimus T   σκεπτικῶν EAB 7 οὐ καταλ. Stephanus: οὐχ ὑπολαμβάνω GT (non presumo) 10 λέγειν &lt;πρὸς γνῶσιν&gt; Kayser || ἦς EAB
footnote 30/31 καταλαμβάνεσθαι Pohlenz coll. adv. dogm. I   καταλαμβάνειν GrT (comprehendere) 5 περὶ om. Τ
footnote 11 μέτρον — 14 ἔστιν om. EAB 15 οὕτως LEABT (ita): διὰ τοῦτο M 15 διὸ — IG Πυρρ. om. Τ 22 τὰς addidi coll. p. 49,31. 30 τὸν T (praeter naturam hahentem): τοὺς G
footnote §§ 220–235 (om. fort. 223–225) Aenesidemo attribuit Natorp Mus. Rhen. 38 p. 32. 7 δὲ om. Μ || γεγόνασιν om. EAB || post φασὶ Μ habet lacunam 5 literarum, οἱ suppl. Kayser 8 post πλείους EAB add. μὲν || ἢ del. Kayser || καὶ μία EAB || τὸν EAB 9 τὸν MEAB 12 τὴν Fabr.: τῶν G 13 τὴν &lt;τῶν&gt; Gen. 14 τὸν delevi 15 πρὸς ἡμᾶς suppl. coll. 50,26. 52,5. 17 17/18 21 25 ἀπορητικὸν Bekk.: ἀπορηματικὸν G 19 φασι om. T 21 γυμναστικόν τε καὶ del. ut glossema Rüstow 26 καὶ τὴν EAB || quae inter nos et illos est differentia T
footnote 29 λέγομεν T (dicimus): διαλαμβάνομεν G ΙΙ κατὰ &lt;τοὺς&gt; περὶ Μηνόδοτον Natorp: κατὰ περμήδοτον GT (secundum permindotum): κατὰ Μηνόδοτον Fabr.: κατὰἩρόδοτον Pappenheim 6 σκεπτικὰ EAB 7 περὶ τούτου EAB 8 ὅλως om. Τ 9 add. Pappenheim 12 ἐν — 25 διέσυρεν om. T 13 τ. Ξ. del. Kayser 16 ἀμφοτερόβλεπτος LM: ἀμφοτερόβλεπτα EAB: ἀμφοτεροβλέπτου dubit. Bekk. 17 ἔτ’ ἐὼν G: ἐτέων dubit. Bekk.: τε γέρων Nauck || ἀμενθήριστος Bergk: ἀπενθήτης ριστος G 18 ὅπη ML: ὅπου EAB 19 ταὐτό τε ML: ταυτότης EAB 20 ὁμοίην EAB: ὁμοία L: ἰσοσταθμοίην Μ 21 τελείως Menagius
footnote §§ 226–231 ~ adv. dogm. IT 166–189 cf. Mus. Rhen, LXVI (1911) p. 190 sqq. 23 Ξεινοφάνης Gen.: Ξενοφάνης G 24 εἰ τὸν Diels: ἔα τὸν G: ἔκ τὸν Paris. Suppl. 133: ἐκτὸς Bekk.: ὃς τὸν Roeper || ἀπ’ ἀνθρώπων Fabr.: ἀπάνθρωπον G 25 ἀτρεμῆ add. Diels II νοερώτερον Diels: νοερωτὸν G 26 μὲν om. L 26/27 ὁμηραπάτης M: ὁμηραπάτην L: ὁμυραπάτην EAB: 6 ἐπαπορεῖ EAB 8 ἄδηλα &lt;ἀδήλων&gt; Pappenheim 10 οἱ MET (qui autem): οὐ L: εἰ AB (deerat prima litera in archetypo) 11 εἶναι MLT (esse): οὖν EAB || πάντα om. Μ 12 πάντα om. M 13 καὶ om. T 14 et in T 19 ἀγαθῶν et κακῶν EAB
marginal 29a
marginal 4a
marginal 9a
footnote 26/27 περιωδ. Kayser 1 καὶ post δὲ om. T 4 ὃς πιθανὴν μὲν T (qui prohdbilem quidem sumehat): καὶ πιθανὴν G   cf. Mus. Rhen. 1. 1. 11 fortasse λέγονται 15 ἅπαξ — 17 τινι: et consentire alicui secundum ualde. cum electione et quasi conpassione Τ 15 τὸ Gen.: τῷ G 17 ὁ om. L 18 moventi T
marginal 4a
footnote 20 σφοδρῶς L 22 περὶ τοῦ τέλους T (de fine) 23/24 qui ipsam decora videntur viri T 31 εἶναι δοκεῖν Μ 3 est esse (sic) T, unde fortasse verbura eliciendum: λέγει vel φησὶ 5 ἐκτὸς scripsi coll. p. 243, 12. 746,26: ἐξὸν M: ἤτοι πλὴν LEAB: nisi quis dicat T || λέγει L || ἡμεῖς μὲν κατὰ om. L 8 εἶναι om. Τ || αὐτὸν scripsi T secutus (unde et bonum quidem ipse dicit): αὐτὴν G 11 ἐπὶ LEAB || ἑτεαριων M: sodaliumT: ἑτέρων LEAB 14 ἑταίρων MT (sodalium): ἑτέρων LEAB 15 παρεγχει-ρίζειν Bekk. dubit. || exinde fertur T 30 ἐπεὶ δὲ EABT (quando autem): ἐπεὶ δὴ L: ἐπειδὴ M 9 &lt;καὶ&gt; ἐλέγ. edd. 16 ἐατρὸς om. T cf. p. 56,1
footnote 17 ἐπὶ τὴν ἐμπειρίαν T (ad experientiam) , at cf. p. 565. 20 οἱ om. EAB 23 ἄρσιν Pappenheim: φύσιν GT (naturam) 24 τε EAB 29 add. Stepli. 31/32 suppl. e T (inopinabiliter utitur) 5/6 ea que convenientia esse videntur T 7 ὑπεμίμνῃσκον Bekk.: ὑπομιμνῆσκον LT (memorans): ὑπομιμνήσκων EABM 11 τεκμαιρομένους LMT (argumentantes): τ’ εκμαιρο μέν ὁ ἲς EAB
footnote 5 τι ζητεῖν B II 19/20 συντόμως G: celeriter T
marginal 9a
footnote 23 EAB || ὡς ἤτοι om. T 28 ὥσπερ — 30 εἰπεῖν: quemadmodum enim qui non novit si contigerit quid est omnis triangulus hdbet tres angulos equales duohus rectis vel duos trepidos theorema. nec dicere T 29 περιαιρ.: κριτήριον Kayser dubit. 3 δὲ ABT (autem) 5 ἄνευ — καὶ G: sine eo quod est intelligere et T 6 τὸ addidi 13 οὕτως Bekk.: οὗτοι G: ipsi Τ at cf. V. 27. || ὅταν om. Μ 14 ζητεῖ EAB 15 ὁ om. EAB
footnote 17 καὶ — κατείληφεν om. ABT 21 αὐτῶν secl. Kayser 24 συντόνως G: instanter T: ὁμόσε Kayser 26 ὄντως L 29 ἄπιστος MEAB Τ (incredibilis): ἄπιστον L 30 αὑτοῦ L || ἐνάργειαν Fabr.: ἐνέργειαν GT (actum) 31 αὐτῷ T (sibi): αὐτῷ G 1 &lt;καὶ&gt; κατ’ ἐν. T (et secundum actum) at p. 594,25 II ἐνάργειαν Fabr.: ἐνέργειαν GT | | λέγοι Τ (dicat): λέγοιτο LEAB: λέγει τὸ M 1 et 6 αὐτῷ Τ (sibi): αὐτῷ G   τε MEAB: om. LT 10 γὰρ om. Μ 13 αὐτῆς om. T
footnote 16/17 μεταγόντων ἡμῶν MLT (deducentibus nohis): μετὰ τούτων αὐτῶν EAB 23 ἐφεκτὴν L 24 λέγειν om. Τ 26 ἐν deL Bekk.: καὶ Pappenheim 28 παθητικῶς Gen. cf. p. 43,13: παθηματικῶς G || καὶ add. Τ (et) 29 λόγων GT (a rationihus): λόγῳ Gen. e cod. Yesontino 409 vel cognato aliquo libro, quod omnes editores receperunt 1 ἐνεργητικὴν EAB 3 ἀπείργωνται LT (prohibeantur): ἀπείργονται MEAB 9 ἡμῖν ἐστι MEABT (est nobis): ἡμῖν L
footnote 13 &lt;αὐτὰ&gt; εἶναι T (ipscts esse) 13/14 πλείων αὖ 14 τελεότερον Kayser 23 τόπος Τ (locus) 24 &lt;τοῦ&gt; edd. 25 vide p. XIII 29 περὶ om.T (in ratione skepseos). 3 καταλήψεως &lt;τεχνικὸν&gt; EAB; cf. p. 197, 10.; 5 πρὸς om.
footnote § 18 ~ adv. dogm. I 48–53. 8 οἶον post τριχῶς add, Τ (videlicet) 8/9 οἷον transp. ante ἄνθρωπος T (ut homo) 15 διαφωνίας T (a dissonantia): ἀληθείας G cf. p. 37, 6 sqq., quam methodum sequitur in sequentibus Sextus 18 ἄλλοι τινὲς καὶ EAB 21 ἐπέδχομεν Kayser: hesitamus Τ: ἐπίσχωμεν G 23 εἷναι om. T 24 ἐπικριτὴν T (iudicahilem) cf. p. 37, 33 sqq, 63, 25; ἐπικρίνεται G 25 μηδ’ L 33 κριτηρίου λαμβάνειν L
footnote §§ 22—28 ~ adv. dogm. I 1 ἄπορον Kayser 2 nohis eicientibus T 9 εἰδικῶς Gen.: ἰδικῶς G: specialiter Τ 15 ἐμμέθ.: artificialis Τ 19 ὑπὸ Τ a[d] dogmaticis): ἀπὸ G 20 ἀκούωμεν L || γοῦν τοῦ LEAB: γὰρ τοῦτο M 26 ἴσμεν G: ἴδμεν p. 248,26.
footnote apud ipsum Τ (= παρ’ αὐτῷ?) at cf p. 82, 27. 6 παρὰ ML: περὶ EABT (circa) 8 ἐπινοῆσαι? 9 τοιουτονὶ scr. coU. p. 249,4: τοιοῦτοί· Gr 11 ἔσται? 12 μὲν om. M 16 δὲ addidi 20 addain τῶν δογματικῶν post αὐτῶν 24 ἀνειληφὼς Pappenheim coll. p. 62, 27. 167,24: ἀπειληφὼς G: qui accepit T (cf. ad v. 27/28)
footnote §§ 29—33 ~ adv. dogm. I 283—313. 27 ἔχων τέλειον LT (qui rationem habet perfectam): τέλειον ἔχων M: ἔχων om EAB 27/28 qui accepit T 28 καὶ del. Bekk. 29 a ἀποφαίνηται Τ (assignat): ἀξιοῖ G 31 πολιτικῆς: τῆς κατὰγους 32 ἀ§ιοῖ G: vultT 12 τό τε τοι vel τὸ μέντοι Pappenlieim (corpus autem Τ) 14 post καταλάβωμεν Kayser add. &lt;οὐδέ γε τὸ βάθος καταλαμβάνομεν&gt;, 15 ταῦτα vel ταῦτα πάντα pro τοῦτο 19 ἐντεῦθεν om. EAB
footnote §§ 34—36 cf. adv. dogm. I 314—316. 21 τὴν om. Μ 22 μεσήνιον messanensem T 31 τὴν post καὶ om. EAB 6 ἂν add. Bekk. 10 καὶ post τοῦτο om. Τ 15 περὶ MLT (de quo est sermo): &lt;τὸ&gt; &lt;τὸ ὑφ᾿ οὗ&gt; λεχθήσεται MLT (dicetur): ἐλεχθήσεται EB: ἐλεγχθήσεται 16 κρίνεσθαι MEAB: κριθῆναι L 18 et 19 ὁ om. EAB
footnote § 39—42 no adv. dogm. I 320—326. 24 ἐκεῖνο MLT (illud): ἐκεῖνο πρὸς τὴν κρίσιν EAB 29 τὸ ὑφ’ οὖ fort. del. 32 πεπιστώσθω MEAB: πεπιστεύσθω LT (credatur) 1/2 φιλοσοφήτωσαν EAB 3 αὐτῷ om. T ΙΙ συγκατατίθεσθαι scripsi coU. vv. 6. 31. p. 66, 11: consentire T: θέσθαι G 7 ἐρωτήσωμεν L 9 add. T (aut cirinaico vel cunico) || L 11 ὄντων G: ἀνθρώπων Kayser : malim addere &lt;καὶ γεγονότων&gt; colL v. 14 et 18. 13 δοθῇ Bekk.: concedatur T: δοίη G
footnote 22 τούτου Τ (intelligibilior illo): τούτου σὺν. G 23τούτου om. Τ 30 μετὰ ταῦτα om. Τ 5/6 ταῦτα εἶναι δοκεῖν καὶ ποιεῖν EAB 7 φύσει Τ (natura): φύσεως G 8 αὐτῷ EAB 13 οἶόν τε μὲν εἶναι Apelt: οἴεσθαι μὲν GT (propter id, quod opinamur quidem) || ἀληθῆ εἶναι λέγειν EB: ἀληθῆ εἶναι λέγει A
footnote §§ 43—44 ~ adv. dogm. I 18/19 γρ δεῖ πιστεύειν A in marg.: δεῖ πιστεύειν in textu, γρ. χρ. πρ. i. m. B 23 οἱ — 25 συμφ. om. M 24 αὐτῷ om. Τ 7 τὸ om. EAB || πρόκρισις MEAB: πρόσκρισις L: prelectio T 10 &lt;καὶ&gt; κατὰ EAB || δόντες MEAB: διδόντες L
footnote § 47 cf. adv. dogm. I 263. §§ 48–50 ~ adv. dogm. I 343—346. 16 προιέναι Τ (procedere): ἰέναι G || καὶ om. Τ || εἰρημένον Gen. Bekk. 25 οὗτος ἔχοι MLT {hic habeat utique): οὕτως ἔχοι EAB 6 καταλαμβάνειν EAB 8 ἀλλ᾿ ἐπίκριτον L
footnote §§ 51 — 56 e decem tropis sumpta (cf. adv. dogm. I 345).  13inter εἷναι et οὐδὲν spat. 8—10 lit. habet L 18 τἀς et εἷναι — 14 ἄπιστοι om. Τ 14 ἧττον EAB : ἡμῶν L: om. M sed lac. habet 8—10 lit. vide p. VIII 14/15 κρίσιν (iudicium): TtlatLv Μ 15 πραγμάτων ora. T 19 δοκεῖ add. Τ (esse putat) cf. p. 68, 22. 69, 16 e. a 22 δοκοῦσι GT (putant) cf. V. 19 26 φήσει τις T (dicet aliquis): φήσειέ τις G 1 ἐν τούτοις secL Stephanus 4 ἀληθῆ &lt;εἶναι&gt; καὶ EAB
footnote §§ 57—60 ~ adv. dogm. I 348—352.  9suppl. coll. p. 9, 29. 28, 7. 13 ὡς om. Τ 14 ὡς add. Bekk. 16 μὲν om. AB 20 suppl. e T (manifestum iudicium) cf. p. 71, 18. 20/21 δύνανται G: poterunt Τ: δύναται Bekk. 31 ovv om. A del. Kayser 6 ὡμολογήσθω Gen.: ὡμολογείσθω G: ὁμολογείσθω Paris. suppl. 133.
footnote  11 καὶ om. EAB 13 οὔσης i. mg. L 15 λέγουσι EAB 19 τῇ δὲ τοῦδε A (ut etiam Bekk. dubit.) 20 τολμῶμεν MLT (ausi fuerimus): δοκῶμεν EAB 22 fort. ψευσόμεθα &lt;λέγοντες&gt; 23 τοῦ primum om. edd. ΙΙ λεγομένων om. Τ: λεγομένου Bekk., idem Paris. suppl. 133 25 τῶν ἄλλων om. T πάλιν om. T 32 ἔστιν ἀληθής MEABT (quod sit vera): ἀληθής ἐστιν L 2 γὰρ om. EAB
footnote 10 καταληπτοῦ EAB 11 διανοίαις Τ (intellectibus) : διαφωνίαις G 13 καὶ &lt;ἐν&gt; edd. 14 διανοίαις MLT (intellectibus): διαφωνίαις EAB 17 τῇδε add. Bekk. ταῖς διανοίαις Kayser 21 κρινοῦμεν LMT (iudicahimus): κρινούμενον EAB || post κρινοῦμεν L hab. spat. 30, Μ 25 lit: ut quibus quoque concedamus, quihusdam vero non Τ, unde sic fere suppleam &lt;ὤστε τισὶ μὲν συγκατατίθεσθαι&gt; 23 τοῦ EAB: τούτου L: τ . . . . . M: de hoc Τ || τούτων T (per hos): τοῦτο G 24 αἰσθήσεις om. EB exp. A 25 κρινοῦσιν Τ (iudicahunt) cf. v. 30: κρίνετε MEAB: κρίνεται L 26 ἢ—27 διανοίαις om. L 26 τε om. EABT 26 τἀς αἰσθήσεις—27 αἰσθήσεσι om. M 30 κρινοῦσιν G: iudicahunt T
footnote § 70 ~ nu adv. dogm. I 370—379 6 συναρπάζουσι EAB 11 invenietur T 12 τὰς — 13 προδι. om. M 13 προδιευκρινεῖσθαι EAB: προδιακρίνεσθαι L: prius declarari Τ 15 δύνασθαι EAB 23 καθ’ ὃ κριτηρίου EAB 24 τε post εἰπεῖν add. EAB 25 περὶ αὐτοῦ ὅτι ἁ om. L spatio versus (circiter 30 lit.) libero || ἀνεπινόητός (om. ἁ) LT (non intelligibilis) cf. p. 80,17: νοητός post spatium   fere lit. vacuum Μ: ἀπερινόητός EAB; lacunam sic fere expleverim: ὅτι &lt;οὐ μόνον ἀκατάληπτος, ἀλλὰ καὶ&gt; coll. p. 61, 19. 248, llsqq. ΙΙ ἐστιν om. Μ
footnote §§ 72—75 ~ adv. dogm. I 354—358. 30 κατὰ del. Arnim, at cf. p. 271, 8. 32 ἐπιγενομέναις AB 5 ὃ L 6 δύνασθαι L || καὶ del. Bekk. 7 δι’ αὐτῆς add. e T (per eam intellectus apprehendit) 13 πικράζεσθαί &lt;με&gt; 14 εἰ δὲ διαφέρει om. EAB 17 φαῦλος 18 ἔσται EAB 20 αἰσθητικῶν — 21 τῶν om. EAB
footnote § 76 ~ adv. dogm. I 388 sqq. 30 οὐδὲ LM: εἰ SsEAB 31 εἴσεται ML: πόθεν γὰρ εἴσεται ἡ διάνοια; αὐτοῖς· EAB 32 τὴν om, EAB 33 xm MT (cum eo quod intelligitur): τὸ LEAB 2 τοῦτο EAB –4 suppL e Τ (aut omni fantasie credemus et secundum ipsam iudicahimus aut alicui, set si omni quidem manifestum est &lt;quia&gt; et fantasie credemus secundum quam dicebat). cf. p. 60, 18. 275, 1. 277, 23. 6 εἷναι &lt;πιστὰς&gt; πάσας Stephanus || καὶ om. Τ, scr. μὴ 11 τά secL τινα deleverat Bekk.): aliquas res Τ 12 πῶς — 14 φαντασίας transp. post 14 δεήσει EAB 15 τῆς ἑτέρας φαντασίας T (secunde fantasie) cf. p. 77,13: τῶν ἄλλων φαντασιῶν G: del. Pappenheim
marginal 11a
footnote §§ 81—83 ~ ad. dogm. I 38—42. 20 πᾶσι GT (omnibus) : πάσῃ edd. 27 τὸ secl. 29 τι MLT (aUquod): τὸ EAB || αὐτοῖς LT (eis): αὐτούς MEAB   &lt;τό&gt; πως Kayser
marginal 26a
footnote 85 ~ adv. dogm. II 15—16. 14 τὸ μὲν MEAB: μὲν τὸ L 16 γνώσεων Τ (a multis veris cognitionibus): γνώσεως G 21 τὴν om. EAB 22 τοῦ λόγου EAB 28 μόνους G: λόγους Τ (rationes) 32 συμπεπτώκασιν sed in marg. γρ. συμπεριγράφονται Μ 5 producere T sicut saepius 6 ἄπιστα L
footnote §§ 86—87 ~ adv. dogm. II 32—36 §§ 88—93 00 adv. dogm. II 17—31. 8 add. Bekk. 14 πάντα ἐστὶ T (pmnia sunt): πάντες ἐστὶ EAB: πάντες ἔσται M; ἔστι πάντα L 18 et 27 ψεῦδος Bekk.: ψευδές G 19 τι M: om. LEABT 20 addam μέρος vel τι post καθεστὼς ΙΙ τῶν — ψεῦδος om. T 22 εἴγε — 23 εἶναι ἀληθές om. EAB 31 ἔστι τι ἀληθές? cf. w. 1. 3. 10. p. 78, 17.
footnote 9 ὑπόκεινται L 10 εἰ δὲ φαινόμενον om. Μ 15 &lt;τὰ&gt; φαῖν’. del. V. 16 primo τὰ Kayser 16/17 μόνον Μ (qui εἶναι μόνον εἶναι): μόνα LEABT (sola) 21 ἐπεὶ ζητοῦμεν T (quia querimiis) cf. v. 10 et p. 78, 3: ἐπιζητοῦμεν G 30 τε Bekk.: δὲ GT (autem) 1 τάδε μὲν LEAB: τὰ μὲν M || τάδε δὲ EAB: rd δὲ Μ: τάδε ΙΙ εἰ μὲν γὰρ scripsi coll. p. 74, 9: εἰ γὰρ G: si enim Τ 2 δι’ om. L 3 τὸ add. Gen.
footnote §§ 97—103 ~ adv. dogm. II 141—160. 4 γὰρ add. (cf. ad v. 1): μὲν G: γὰρ T (si enim) 5 δι’ om. L 12 μόνον Kayser 16 κἂν δῶμεν MT (et si ddbimus): καὶ δῶμεν EAB: κἂν δοκῶμεν L ΙΙ αὐτῷ AT (ei) Kayser coll. p. 721, 9: αὐτὸ MLEB 25 conjpeUuntur Τ
marginal 9a
marginal 14a
marginal 19a
marginal 29a
marginal 24a
footnote §§ 104–106 ~ adv. dogm. II 245—253. 3 memorativum enim signum T 8 δ᾿ ὑπὸ Τ (a dogmaticis): δὲ G 10 περὶ AB 14 productarum rationum Τ 15 rememorantes Τ (cf. ad p. 39, 20) 16 ὅσον Τ (quantum): ὅσα G
footnote §§ 107—108 ~ adv. dogm. II 258—261. § 109 cf. adv. dogm. II 80—84. 132. 135—136. 2 τὸ Gen: τοῦ G || τοῦ Gen. τὸ G 5 πρῶτον μὲν Τ (primum quidem) 6 et 6 a τι add. Gen. 11 &lt;ὄντων&gt; λεκτῶν Kayser ιστῶσα L 19 ὅτι G: εἰ Bekk. dubitanter 24 si dies est Τ
footnote § 110 ~ adv. dogm. 11 113—117. 28 οὐ συνυπάρξει EAB 31 μὴ secl. Kayser 10 συνάγοντες L 12 predicta T 17 τὸ om. edd. || διαφορούμενον MEAB: διφορόμενον (eras. ἁ) L: onine quod diversificatur Τ || ἀξίωμα del. Bekk. 19 post ἴσως add. ἂν L 20 opinionum T φάσεων, quod iam coni. Gen.)
footnote §§ 117—118 (=119—120) ~ adv. dogm. II 165. 26 καὶ ἡμέρα — ἔστιν om. T 27 περὶ τοῦ om. Τ (quesito autem quomodo) cf. p. 84, 16 8 ἐκκαλύψαντος L 9 ἔσται T (erit) cf. V. 13: ἔστιν G || σημειωτικόν A 22 ὧς σημειωτοῦ ML ex corr. signum ante signatum tamquam signati T: om. EAB, fortasse scrib. ὧς &lt;σημεῖον&gt; σημειωτοῦ coll. v. 19.
footnote §§ 119—120 ~ adm. dogm. II 165. §§ 121— 122 ~ adv. dogm. II 179—181. 31 τὰ suppl. e Τ (alia que sunt ad dliquid) 2 percognosciT (fort. ἐπιγνωσθῆναι cf. p. 83, 33). 4/5 ὑπάρχον om. Τ 18 quemadmodum enim Τ περὶ τοῦ om. T 21 οὐδὲ Bekk.: οὔτε GT (nec)
footnote § 125 ~ adv. dogm. II 174. 26/27 σημαντικὸν G: signatum T: ἀπόφανσιν Kayser colL p. 355, 22 9/10 nec signum esse T 11 καὶ πρὸς om. T
footnote § 130 ~ adv. dogm. II 279. § 131 –v. 24 σημεῖον) ἴον) ~ adv. dogm. II 277—278 31 αὐτά om. Τ 32 λέγηται G: videntur T 5 φαινόμενον T (manifesta): φαίνεται Gr 6 ὑποτιθέντα L 12 ἀρκέσειν EB 13 μὴ — 14 τοῦ om. EAB 15 ἀντικειμένων om. T
footnote § 131 (inde a. v. 24 ὅθεν) ~ adv. dogm. II 281—282. §§ 134—135 ~ adn. dogm. II 299. 25 τι om. EAB 29 εἰ om. L 7 τι L: om. MEABT || μὴ add.Kayser 14 δὲ om. AT at cf. p. 32, 27. 17 κατὰ τὴν τῆς L 20/21 ingrediemur T
footnote §§ 135—138 ~ adv. dogm. II 301—304 § 139 rsj adv. dogm. II 311. 21 temptantes Τ 29 ἢ post δὲ add. Gen. Bekk. συμπέρασμα om. T 30 ἀξίωμα del. Pasquali servato v. 29 a συμπέρασμα || λόγῳ suppl. e T (ut in hac ratione) cf. v. 23 et p. 88 passim 7 secl. Rustow ΙΙ φῶς ἔστιν bis ME 17 post λόγος edd. inser. ἡμέρας οὔσης coll. p. 356, 7. 17 ἀλλά — 19 καὶ εἰ ’ν. ἔ. om. Τ
footnote §§ 140—143 ~ adv. dogm. II 305—310. 19 εἰ secl. Riistow || καὶ εἰ νύξ EABT (et si): καὶ ἡ νύξ ML 20 add. Riistow 21 τὸ &lt;εἰ&gt; νὺξ T (et n. est) n. est) 7 post Fabr. add. θεῶν coll. p. 355, 16, ubi delendum 11 τὴν om. M
marginal 14 a § 144 cf. ’ξ  §§ 146—150 ~ adv. dogm. II 429—434. 20 καὶ del. Kayeer, om (??) φηνίζων EAB
footnote 16 et 19 socrates Τ 19 παρὰ – 23 ἔστιν om. T 21 συλλογιστικῶν scr. coll. p. 91,2; 382,4: συλλογισμῶν G 23 φῶς ἔστιν add. T 25 οὗτος G: secundum Jiec T || φῶς alter. T (Jumen): ἡμέρα G 26 ἡμέρα Τ (dies): φῶς G Ctranspos. iam Fabr.) 28 εἰκότως — 29 λῆγον om. EAB 29 ἀνῃρημένου ML: ἀναιρουμένου EAB 6 προειρημένος ΜΤ (predicta): προειρη-κὼς LEAB 8 λέγεται EAB 10 ἔστιν add. T (ergo dies est) cf. p. 90, 26.
footnote §§ 152–153 ~ adv. dogm. II 435—437. § 154 ~ adv. dogm. 11 444—445. 15 ἐστιν &lt;ὁ πλοῦτος&gt; L 18 οὖν ML; δὲ EAB: si enim Τ 19 σιακρίνεσθαι Bekk.: διακρίνασθαι G 20 συνακτῶν L 21 add. Kayser: proferuntur ah eis T 25 τε add. e Τ (ad invicem quoque) 28 ἅδ’. add. Bekk. Stephamim secutus || διαίρεσιν L 7/8 λεγόμενον Bekk.: λόγον GT (ratio)
footnote § 155 ~ adv. dogm. II 446. § 156 ~ adv. dogm. II 438—443. §§ 157—158 V. 8 νύξ ἐστιν ~ dogm. II 224—226. 12 δυνάμει — τούτων om. Μ sed relinqu. spat. 26 — 28 lit. (vide p. VIII) ΙΙ ἀντειρήκαμεν T {contradiximus) cf. p. 101, 32/3. 384,19: ἀντιρήσθω L: ἀντειρήσομεν EAB || τούτων T (per has): τοῦτο G 14 καὶ add. T 15 ἐλλιπὴς T (defectiva scil. ratio) cf p. 384,21: ἐλλείψει G ΙΙ ἔτι Bekk. Stephanum secutus: ὅτι GT (quia) 18 αὐτοῦ &lt;ἐλλιποῦς&gt; Pappenheim coll. v.   διὰ addidi, fort. τῷ (cf. Τ: in colligendo) 29 οὖν add.e Τ (quidem igitur, sicut p. 93, 15. 95, 19 e. a.) 31 τὸν add. Bekk.
footnote § 159 cf. ’ξ 156. adv. dogm. II 440. 2 ἐκ συνημμένου T ψ coniuncto): ἐκ κινουμένου G 4 εἰ om. L 6 ἐν tfj συμπλοκῇ p. 94, 2 et 336, 19 14 ἄρα om. L   αὐτῷ deL Kayser 22 ἔσται Τ (erit): ἔστι G 27 ἀναποδείκτου &lt;λόγου&gt; T (in secunda indemonstrativa ratione)
footnote 33 ὅτι om. T 4 τῷ M: τὸ LE AB 10 ψεῦδος Gen.: ψευδὲς G 12 ἀπ’ om. T 17/18 κατοπτρικῶν EAB 20 δὲ add. T (bonum autem prohum) 21 πρόδηλον MLT (manifestum): πρὸς ἡμῶν E AB 25 ἂν Bekk: ἐὰν G: omne quod bonum est Τ 30 δὲ om. L
footnote §§ 137—168 ~ adv. dogm. II 451—452. 33 ἂν Bekk.: ἐὰν G: omne utique (= ἂν) quod est homo T 2 ἕπεται om. T (si autem essentiam hominis et animal ipsum esse et propter hoc) || τῷ ἄνθρωπον Bekk.: τοῦ ἀνθρώπου G εἷναι τὸ scripsi: tco εἷναι E: τὸ εἶναι MLAB: τινα εἷναι τὸ Bekk. 3 ἀληθής T (vera scil. propositio): ἀληθές G 25 προσπίπτον Τ (incidens): προπῖπτον G
footnote § 172 ~ adv. dogm. II 345 et 383—384. 30 ἀληθοῦς T (rationis que dicitur esse vera): ἀληθὲς G || εἰ δὲ καὶ G: etsi T, καὶ del. Bekk. 14 συνακτικῶς Bekk., qui maluit τουτέστι σὺν. eicere || διά τινων ὁμολογουμένων T (per quedam manifesta) || ἀληθῶν ἐπιφοράν om. Τ 24: ἄλλο om. Τ
footnote §§ 173—176 ~ dogm. II 385—390. 28 ἢ LT: om. MEAB 6 ἔσται T (erit) 7 αὐτὴν om. T || ἢ &lt;αὐτὴ&gt; Τ (quam ipsa) 9 in aliis T 10 τὸν L   Kayser T (solum) cf. v. 1. 21: μόνων G 19 ἀλλὰ μὴν — 20 φῶς ἔστιν om. Τ 20 ’φ’. ἔ. deL Fabr. 21 μόνον Τ (solum): μόνων G 24: ταῦτα EAB
footnote §§ 177—179 ~ adv. dogm. II 391—395. §§ 180—181 ~ adv. dogm. II 327—334. 31 ἐστιν alt. om. Τ 3 δεηθήσεται EAB 8 συγκαταλαμβανομένων EAB || τῇ Bekk.: τῶ G 10 πρόδηλον αὐτὴν G: εἷναι Τ (cum . . . non inveniatur esse non manifesti demonstrativa): πρόδηλον τὴν Bekk. 14 dicendum est ergo Τ
footnote § 185 ~ adv. dogm II 465. 31 μὲν οὖν Τ (quidem igitur) 9 τὴν add. Bekk. (cf. Τ dissonantiam que est) 10 ἐπίκρισις G: διαφωνία T (dissonantia) 14 μήτε δι’ ἀποδείξεως om. T 16 πρόδηλος T (ex se ipsa manifesta): πρόδηλον G
footnote § 186 ~ adv. dogm. II 466—469. § 187 ~ adv. dogm. II 473—478. § 188 ou adv. dogm. II 480. 11 ἀληθὲς Sidd Gen. 12 καθάπερ καὶ Bcriipsi: καὶ καθάπερ MLEB; καθάπερ AT 16 τοῦτο δὲ T (hoc autem)
footnote 26 τοῦτο δὲ Τ (hoc autem) cf. v. 16 1 τὸ add. Gen. (hoc coniunctum Τ) 9 τοῦτο MLT: τὸ ὑπὸ EAB 10 μὴ μαχομένου δὲ secl. Kayser 20 post τι Τ add. tam aliquid (ὥς τι?) 21 ἀληθείας Τ (veritatis)
footnote 27
footnote  T (modum) 27 lacunam indic. Bekker, quam recte sic fere explendam censet μέρος &lt;ἐπαγωγικῶς συνάγοντες δὲ ἑκάστην τῶν κατὰ μέρος&gt;: τὴν δὲ κατὰ μέρος Paris. Suppl. 133 ex coniectura (cf. Mus. Rhen. LXIV p. 253). 1 post διάλλ. add. T τρόπον (modum) 4 τε om. T 6 τε G: δὲ T (autem) 9 τεθεώρητο ML: τεθεώροιτο EAB 11 τὸ primumom. L 13 ὅτι deL Bekk. || ἔστιν Pasquali: εἷναι G: om. T 17 τῶν προειρημένων G: τούτων Τ (eorum)
footnote 23 ὧς εἴγε G: quodsi vere Τ (fort. ἀλλ’ εἴγε) 25 τὸ Gen. : τῷ GT (m eo quod) 28 χρῄζει T (indiget) : χρῆζον G: χρῄζειν Gen. 1 ἀλλὰ — αὐτὰ om. Τ || μὴ add. Gen. 4 ἤτοι — 5 ἡμέρα ἔστιν om. EABT 7 μὲν πρὸς ΕΑB: πρὸς μὲν MLT (si ad certificationem quidem)
footnote 18 παλίνδρομον T (propter retrocedentiam) : παλινδρομεῖν G (μεῖν comp. script.) 23/24 καὶ τὸν τῆς ἐπαγωγῆς τρόπον T (et inductionis modum) 4 ἃ add. T (que) 5 post πάσης add. ἧς Gen, 8 χρησιμεύουσι LT (utiles sunt) : χρησιμεύσουσι MEAB
footnote 16 ὁρισόμεθα MEABT (diffinemus) : ὁριζόμεθα L 17 εἰς add. T (in infinitum) || ἄπορον EAB 19 καθ’ ὃν τρόπον G: quemadmodum enim T 22 secl. Bekk. 21 ἐπικρίνουσι iMEABT (iudicant): ἐπικρινοῦσι L 34 δὲ T (fortassis autem et): μὲν G 2/3 καταληπτοὶ EAB 3 ἐξ T (a quihus nt y. 2): ἐφ’ G 6 χρησιμεύσουσι MEAB cf. ad p. 105, 8. 9 obviavit Τ
marginal 24a
 11/12 ἀπήντηται coni. Bekk.: ἀπήντηκεν Kayser coll. p. 495,28: ohviavit Τ (cf. ad v. 9) 15 fors. ἀσάφειαν 16 οὐκοῦν — 1 7 λεκτέον om. Τ 18 creditur Τ 20 ὡς—21 εἰς om. Τ 20 οὐ ML : οὐδὲ EAB 24 εἴγε scripsi (licet videatur Τ) : εἰ G 24 a suppl. T secutus (destiere diffinitiones quantum in hiis inutilem esse diffinitionem dicimus. Tot) 25 ὄρων MEAB: ὅρον L   ἐπαγωγικὴν om. Τ 29 διαιρετικήν T (divisivam) : om. G 3 dinvidunt T
footnote 15 καὶ add. Τ (et semper diversis) 23 μονάδα T (in unum ut V. 26): μίαν G 31 εἶναι om. Τ cf. v. 22 3 γὰρ T (enim): οὖν G (quod v. 6 igitur T): γοῦν Bekk.
footnote 10 εἶναι om. T cf. ad p. 107, 31. 15 ἀπολείπεται EAB 23 om. T del. Bekk. 25 αὐτοῦ del Kayser 26 γένος ML: τὸ γένος EAB 28 ἐν add. T || κατὰ ταὐτὸ MEABT (secundum
footnote 7 T (et ipsa) 8 αὐτῶν T (eorum considerantur) 8 οὐ γὰρ — d λέγεται om. T 19/20 τῶν τινῶν G: quorundam T τινῶν?) 25 ἔχοι AB 26 τῷ MET (cum eo quod): τὸ LAB 28 δεήσει δὲ T (oportet autem)
footnote 6 καὶ τοῖον alt. G : est T 8 γένος del. Bekk. 9 λέγοι EABT (dicat) : λέγοιτο M : λέγει L 11 εἰ μὴ καὶ T (nisi et actu) : μή τις G: μή τις ὢν Gen. 15 τὰ δὲ — 16 ἐνεργείᾳ om. Τ 18 ὂν add. e Τ (corpus autem quod est actu) 19 τι add. (fortasse excidit exemplum) 25 ὁ αὐτὸς T (idem): αὐτὸς G 21 τὸ ἄνθρωπον T (hominem esse), coni. Pappenheim: rdj ἀνθρώπω G
marginal 19a
footnote 1 οὐδὲ Τ (nec) : καὶ G 7 ἢ add. T 12 τὴν &lt;μὲν&gt; Θέωνι : Bekk. dubit. || δὲ MLT (autem) : καὶ EAB 17 τῷ EAB : τὸ L: om. M(T?) 18 λόγον T (instare rationem) ΙΙ τὴν om. L   φασίν om. EAB 23/24 rw βίῳ Gen.: τὸν βίον G: adiuvantes concussam vitam Τ 24 δὴ om. Τ 28 ψευδεῖ EABT (false) : ψευδῆ ML
marginal 29a
marginal 2a
marginal 9a
marginal 19a
footnote 29 τούτου add. T (sicut in hoc sophismate) 29 a ποιεῖν EAB 31 ἔτι δὲ Gen.: ἐπὶ δὲ G: om. T (similis autem false) 1 δὲ om. L 2 ὁ EAB: om. ML 2—2a suppl. Bekk. coll. 20/1 2 a ἔτι δὲ ut p. 111,31 4 ἠρώτηκα — 5 εἰσιν om. Μ 5 οἱ LT: εἰ EAB || ἔτι δὲ ut p. 111,31 (aliter autem inacceptabiles T) 9 a ὁρᾶν ἤτοι om. T
marginal 24a
marginal 29a
marginal 5a
footnote 24 ἐπαγωγὴ Gen. 28 δὲ om. L 29 τῆς προσλήψεως om. EAB 29a γενομένης ML γινομένης EAB 30 προσλήψεως Bekk.: προλ. G: assumptionem T ut v. 29 5 τοὺς — 6 συνήθ. corrupta esse putat Pappeng., qui αὐτοὺς vel aliud desiderat   ἔνιοι MEABT (quidam) : ἔνθα L 5a ἐπάγεσθαι T (induci) : ἐπάγειν G 7 τινες om. T 9 οἰκειοτέρων L 14 δυωάμεως om. L
footnote 21 ἐπὶ om. T 23 ἰατρῷ secL, fort. leg. τοῦ τοιούτου σοφίσματος coll. p. 114,9 aut ἰατρικοῦ σοφίσματος 26 ante primum terWane T 27/28 ante primam paroxisim tertiane T   ante primam quidem tertiane T 4 καὶ om. T 9 τοῦ τοιούτου λόγου ML: τοῦ λόγου τοῦ τοιούτου EAB: huiusmodi ratione T
marginal 29a
footnote 20 προσεχές Τ 20/21 τὸ ψυχρὸν &lt;ψυχρὸν τὸ&gt; κατ. εἷναι δοκεῖν αὐτὴ Pappenheim 23 ἐρωτήσεις EAB || ἡμᾶς T (interrogans autem nos) : ἡμῖν G 24/25 et 25/26 καὶ κέρατα ἔχεις del. E. Weber 28 μενεῖ Kayser || μένει γὰρ &lt;ἐν εἴπερ ἐν αὐτῷ ἐστιν&gt; E. Weber coll. p. 137,26 || δὲ om. ὁ ἐνάργειαν Fabr.: ἐνέργειαν G: ad manifestam T 7 αὐτῶν alt. EAB: αὐτοῦ L: αὐ(??) Μ: eis Τ 8 τις add. T (quidam phil.) cf. p. 136, 25. || ad φίλ’. rubr. in L add. in mrg. ὁ ἀντισθένης   κατὰ om. T (rationem motus) 12 κατὰ G: de T
footnote 14 τι add. T (gratum quid) 15 ἐναπειροκαλῶν Bekk.: ἐν ἀπειροκάλῳ Gr: in dyalectica inexpertus T 16 κατὰ G: de T 18 ad ἐχαρ. L habet in mrg. εὐτραπελίσατο, ἒσκοψεν ΙΙ λέγων Τ (dicens): λέγω Gr 19 ὢν om. Τ 24 βιοῦν T (vivere) βίου G 26 λεγομένων om. T 29 κατὰ GT (secundum): fort. πρὸς 31 δὲ MEAB: om LT 6 λέγουσι γοῦν Bekk.: λέγουσιν οὖν G: dicunt enim T S τὸν L: τῶν MEAB
marginal 15a
footnote 15 αὐτοῦ om. T 22 ἢ μὴ μήτε T (nec) 27 περὶ T (circa) 31 μὲν MLT (quidem) : μὴ EAB 32 φασιν Gr: quod autem T ἐπειδὴ δὲ?) 1 ἀπάγειν τὸ σόφισμά φασιν ἀλλὰ καἰ scripsi sec. T (in falsum deducit sophisma dicunt quidem etiam) : ἀπάγειν τοῖς σοφίσμασιν ἀλλὰ καὶ G
marginal 24a
footnote 17 οὕτως GT (sic): οὗτός τις Rustow: Οὗτος? 18 ἡμῖν add. T (que videntur hobis) 22 καὶ ἐπέχειν om. Τ 24 προπίπτειν Bekk. : προσπίπτειν G: concedere Τ 6 ἢ Τ (duo aut plura): καὶ G: ἢ καὶ coniecerat Pappenheim coll. Diog. Laert. VII 62.
footnote 10 ἔχοντες — 14 δὲ om. T 17 παιδίων M 18 εἰ τύχοι om. T 20 οἴνους τις EAB ΙΙ λἐγοι λέγει G 31 λρατθνεῖ τυνεῖ Bekk.: κρατύνει GT (confirmat) 1 αὐτοῦ που suspecta Pappenheimio
footnote 5 et 6 inverso ordine leguntur in G 26 τίς B
footnote § 1 ~ adv. dogm. III 4 —12. § 2 — λέγομεν ~ adv. dogm. III 49. 30 τι om. B 32 τις om. B 34 τούς πιθανοὺς B ΙΙ 5 οὖν add. T (quidem igitur) 6 τοιαῦτα G: ταῦτα T (hec): τοσαῦτα Gen. 9 eis eis T (παρ’ αὐτοῖς?) ΙΙ τόπον L: τὸν τόπον MEAB: localiterT, fort. κατὰ &lt;τοῦτον&gt; τὸν τόον cf. p 392,15. 11 ἀρξώμεθα MEABT (incipiamus) : ἀρξόμεθα L 11 a et 15 a tituli inverso ordine exstant in L 13 δραστικὰς EAB: δραστηρίους ML
footnote 19 providere ipsos nohis Τ 24 εἰδωλοποιεῖσθαι Kayser coll. p. 109, 14 || τε: igitur Τ 25 που ML: του EAB: intelligi alicui (fort. pro alicubi cf. p. 134, 15) Τ 26 τὸν θεὸν εἷναι L 2 δὲ om. EAB 4 αὐτῶν &lt;ἐπινοηθὲν&gt;   τοῦτο EABT (hoc): τοῦτον L: om. M 6 γάρ add. T (quemadmodum enim qut) 16/17 περὶ τοῦ πότερον G: de hoc prius utrum Τ
footnote 19 Bekk. : προέπιπτεν G: incideret Τ 22 add. Τ (qui enim demonstrat) cf. v. 24 25 ἀποδεικνυόμενον ML: ἀποδεικνύμενον EAB 29 post πρόδηλον add. pappenheim τὸ εἷναι θεόν, quod fors. e p. 121,1 huc transponendum censet 1 del. Pappenheim 5 προεκκειμένου GT (preexistentis): προκειμένου edd. llsqq. Epicuri fragm. agnovit Pasquali 13 δὲ G: γὰρ Τ (enim)
marginal 14a
footnote 14 a ἀεὶ post προνοεῖ add. Τ (providet semper) 29 οὐδὲν L 30 καταλαμβάνεται Τ (apprehenditur) : καταλαμβάνει G 1 ἀσεβεῖν ML: ἀσεβεῖς EAB: impii Τ ΙΙ ὀνομάζονται T (appellantur) 7 ἀναγκάσωσιν T (compellant)
marginal 9a
marginal 0a
footnote 9 κοινῶς Pappenheim dubit. 13 add. T (de causa assignant) cf. p. 123, 23. 14 περὶ αὐτοῦ Kayser 20 τὸ αἴτιον Gen. : τὸ ἀγγεῖον GT (vas) 29 αἴτιον Τ (causam): αἴτιος G   γὰρ add. T (sic enim) cf. v. 28 30 a συναίτιον Kayser, at cf. V. 29 1 τι et τις om. T
footnote §§ 17—19 ~ adv. dogm. III 200—204. 17 ὄμβροι κατὰ &lt;κατὰ τύχην&gt; EAB 18 χίονες ὡς &lt;ὡς ἔτυχεν&gt; et ὂμβρων ἐπεὶ &lt;ἐπεὶ μετέχει&gt; EAB ΙΙ ἐγίνοντο Beek.: έγένοντο G   ἐστι om. L 22 φήσει Kayser || λέγειν G: εἶναι Τ (esse)   τίθησι GT (ponit): θήσει Kayser || ἀποδιδούς Kayser: ἀπο-δίδωσι γοῦν Bekk. : fort. locus sic reficiendus τὸ αἴτιον, &lt;αἴτιόν τι&gt; τίθησιν ἀποδιδούς cf. p. 433, 13sqq. 23 ἀποδιδόσθω —   αἴτιον.. causam causam T διὰ — οὖν om. Μ 25 εἶναι —   ἐστι om. M 26 τι om. EABT
footnote 5 αὐτοῦ prius om. T 8 add. T (ut dixi) 16 a—17 add. T (hii quidem igitur esse aliquid alicuius causam. hii autem non esse. hii vero destiterunt qui dicit igitur) 11 τι add. Τ 18 λέγειν om. T 21 δὲ MLT: καὶ EAB: δὲ καὶ Gen. 22 τι add. Bekk. ΙΙ νομίζει Bekk.: νομίζοι GT (estimetn) 24 τοῦ εἶναι Τ (essentie cause), Stephanus: τὸ εἶναι G
footnote §§ 26—28 ~ adv. dogm. III 232—236. 10 suppl. e Τ (aut esse postquam fiat effectus) 11 λέγειν G: differre T 20 add. T (sed neque effectus est ante eam), coniecerat Kayser
marginal 14α
footnote §§ 30—32 ~ adv. dogm. III 359—364 (cf. Doxogr. p. 248 sqq. Diels). 27 τι del. Bekk. 28 &lt;ἄρα&gt; ἐστὶν Gen. 29 λοιπὸν om. ΜΤ ΙΙ εἰ Τ (quod si): ἐπεὶ Bekk.: om. G 5 δραστικῆς &lt;αἰτίας&gt; Τ (de . . . agenti causa) 9 γὰρ om. EAB 16 καὶ τοὺς Τ (qui autem circa empedoclem et stoicos) A: πρὸς τοὺς MLEB cf. p. 462,3.
footnote 30 ἄλλαις ML: ὅλαις EAB: et dliis etiam Τ 1 ποιά Gen.: τοῖα GT (talia) 3 περὶ G: ἐν T (in) 6 οὐ—7 ἀποδείξεως G: manifestum est qui (i. e. quiaT) T 7 συγκαταθησόμεθα Bekk. dubit. 11 ἀληθὴς EABT (vera): ἀληθὲς ML
footnote § 37~adv. dogm. III 365. § 38~adv. dogm. III 366. § 39 cf. adv. dogm. III 367. adv. math. III 19—20. 17 ἀποδείξει MLT (demonstratione): ἀποδείξεως EAB, unde editorum error δι᾿ ἀποδείξεως 18 ἐκβληθήσεται olim tentatum a Nauckio T (eicietur): ἐμβλ. G vide ad p. 132,28.. 23 καὶ om. T 24 ἐνδιατρίψωμεν GT (retardemus) : ἐνδιατρίψομεν edd. 29 ἂν Bekk. : ἐὰν G: quamcumque si quis T 2 ἐστιν T (sunt): ἔσται G 11 μὲν om. L || φασιν om. T
footnote § 40 ~ adv. dogm. III 368. adv. math. III 83. §§ 41—44 ~ adv. dogm. III 434. 17 ταῦτα Τ (ad hec) 24 λέγειν G : differre T (at cf. ad p. 125, 11) 28 et 30 et 129, 13 περὶ G: T (in) cf. p. 127,3 31 μὴ om. EAB
marginal 12a
marginal 12b
marginal 12c
footnote §§ 45—46 ~ adv. dogm. III 259—261. 10 μὲν add. Τ (ciuidem) 12a—c suppl. verbotenus e T non erit sine profunditate differentibus eius partibus intelleciis secundum profunditatem hac quidem cui opponitur tangenti hac autem secundum &lt;quod&gt; coniungitur corporl est terminus. Non ergo) 25 σώματα LT: σώματος MEAB || λέγοι τὰ πέρατα MEABT (si autem aliquis est corpora esse dicat terminos): τὰ πέρατα λέγοι L 32 σώματα om. Τ
footnote §§ 47—48 ~ adv. dogm. III 437—439. 12 ἅ add. Bekk. 14 καὶ — 16 μερῶν om. Τ 17 ἔσται om. Τ 18 non soUditas Τ 26 ἁπλοπαθεῖς Stephanus: ἁπλοπαθείας GT (simplices passiones) cf. v. 33 et p. 146, 7   simpliciter passihiles Τ || excidit totum emintiatum, quod ex p. 146, 7 sic fere expleverim &lt;ὥστε τούτων πάντων ἔχειν οὐ δυνήσονται&gt;, plura excidisse putat Pasquali
footnote 3 ὄντων om. T 6 ἀφ’ οὗ om. Τ 9 μηδὲν scr. coll. p. 476,4: μηδὲ G 10 &lt;μὲν&gt; οὖν T (quidem igitur) 11 δοκεῖν del. T secutus (quod videtur existens) 31 δοκοῦσιν EAB 32 ὁ γὰρ T (qui enim)
footnote 4 Kayser coll. Diog. Laert. VII 157. Doxogr. p. 406,4 Diels : ἔνστασιν GT (instantiam) || γίνηται Bekk.: γένηται G 5 suppl. T (sive secundum fluxus radiorum) 7 τὰ pr. om. L || περὶ L: πρὸς MEABT (ad) 9 καὶ οἱ χυμοὶ — 10 καὶ om. T 10 αὖ τῇ Bekk.: αὐτὴ G 12 add. T (sensu hec apprehendi)   καταλαμβάνεσθαι Τ (apprehendi) : λαμβάνεσθαι G   γὰρ G: δὲ T (autem) 17 τι ἀσ. MEABT (aliquid incorporeum): τι ἀσ. τι L 20 ἀποδείξει Τ (demonstrabit): ἐπιδείξει G 23 post καὶ add. EAB τοῦτο 28 ἐμβαλλ. AB (eicimur T) vide ad p. 127, 18
footnote 2 Apelt coll. Plat. Tim. 49 d e : quocum consentire videtur T (ut neque eam que est hoc possit demonstrationem accipere): τότε G 5 ἀσωμάτου scripsi: σώματος GT (de corpore)   corpora T 12 ἔσται Bekk. dubitanter 15 dubitandum est Τ 21 &lt;καὶ&gt; μικρῷ Gen.
footnote 14 &lt;διαφορὰς&gt; λέγειν T (differentias dicere) 15 καὶ om, T, del. Kayser || alicui T cf. ad p. 119, 25 22 τοι AB
footnote 1 ὀφείλῃ L 4 συνεξισοῦνται Gen.: συνεξισοῦται GT coequatur) 6 κιρνώμεναι Kayser coll. v. 17 7 που G: τε T (quoque) 8 προθέσει EAB 14 &lt;ἄλλο&gt; ἐπινοεῖν T (aliud 21 καὶ oni. Stepbanus: fort. καὶ οὓτως? || ἀδύνατον AB
marginal 29a
marginal 4a
footnote § 64 ~ adv. dogm. IV 37—41. § 65 ~ adv. dogm. IV 45—49. § 66 ~ adv. dogm. IV 67—68. 1 μετέρχεται scripsi coll. p. 139, 11. 484,24: περιέρχεται G: transit Τ 2 add. Τ (secundum totum) 6 βίος Τ (vita): Βίας G cf. p. 485,19 9 εἶναι T (esse): κίνησιν G 15 ὅσον — λεγομένοις om. T || ἀρξώμεθα T (inciiamus): ἀρξόμεθα G
marginal 20a
footnote § 67 ~ adv. dogm. IV 70—76. § 68 ἀλλ᾿ οὐδὲ–69 ~ adv. dogm. IV 83—84. 17 δὴ MEAB: δὲ LT (autem) 21 &lt;αὐτοῦ&gt; γιγνομένας T (eius factas) 24 secundum quem autem modum Τ 25 ἐστι Τ (sunt) || ὁ ἀντισθένης in mrg. G 26 addidi coll. p. 115, 8. 490, 3. 1 lacunam quam statui sic fere expleverim &lt;οὐκ ἔσται κίνησις&gt;, sed plura excidisse monet forsitan v. 6 ἐπιβολὴν : 6 ἄλλως—9 κίνησιν hunc in locum transferri iubet Pasquali || ἑτέρου alt. T (ab alio): ἑαυτοῦ G 3 μὲν &lt;οὖν&gt; Bekk. 11 γὰρ add. Gen.
marginal 29a
footnote § 71 ~ adv. dogm. IV 87. § 72 ~ adv. dogm. IV 93. 103—107. § 73 ~ adv. dogm. IV 94. 105—107. 12 κινοῦν Τ (quod se monet): ἀγνωθοῦν ML: ὠθοῦν EAB   τρόπων Τ (modorum) : τρόπον Gt 26 οὔτε Τ (neque) : οὔτε δὲ G 2 &lt;καὶ&gt; μεταφέρειν Τ (et circumferre) 7 duo tenet loca T
footnote § 75 ~ adv. dogm. IV 95. 108—110 § 76 ~ adv. dogm. IV 139—141. 14 ἐν ᾦ — 15 δύναται secl. Kayser 23 τὸ κυρίως ικν. Kayser 33 προτ. add. T (jprius primo) 3 ὡς δείξομεν om. Τ
footnote § 77 ~ adv. dogm. IV 154. § 78 ~ adv. dogm. lV 124—126. 10 καθ’ ἕκαστον EAB 11 ἀμερεῖ &lt;ἀμερεῖ&gt; coni. malim &lt;μέρει&gt; ἀμερεῖ 19 σταδίου LT (stadii): σταδιαίου 25 τύχοι AB Par. suppl. 133: τύχη MLE: si contingit T   κατὰ om. EAB 2 τῶ MEABT (cum eo quod): τὸ L
footnote 6 &lt;κατὰ&gt; μικρὸν Kayser 8 σωτηρικὴν L 12 producent προσοίσονται?) 14 κατὰ add. Gen. 17 πρότ. add. Gen. 28 in alio Τ (ἐν ἑτέρῳ?) 29 γενομένης Bekk.: γινομένης G
marginal 11a
footnote §§ –88 ~ adv. dogm. III 297—307. 1 ἕτερον ἀγαγών τις G: aliud aliud differens aliquid T: ἀλλάσσων e. g. Apelt 23 ὑπολίπηται G: corr. Bekk. 24 τούτῳ scr.: τοῦτο G: hoc Τ 26 ἐν add. T (in quinque) 29 τετράσι G
footnote §§ 88 (inde a καὶ μὴν) —93 no adv. dogm. III 308—320. 3 &lt;καὶ&gt; ἄπειροι T (et infiniti) 10 καὶ — τινος om. 14 δὴ scr.: δὲ GT (autem) 28 δοίη Bekk.: δώῃ G
footnote §§ 94—96 cf. adv. dogm. III 321—325 et 326—327. 30 δεκὰς T (decas) : μονὰς Q 32 ἄτ. — 33 εἴκ. om. EABT 1 dinidetur Τ 24 ἑαυτῶ EAB
footnote §§ 98—101 ~ adv. dogm. III 338—349. 32 ἐστιν T (est): ἔσται G 13 ὅλον‘ LEABT (totum): ὅλ.ου M   τὸ add. Bekk.; inter αὐτοῦ et ὀλὸν spat. unius lit. M   ἀναιρουμένων (ablatis parttbus) quod iam Bekker restituit: αἱρουμένων LE : αἰρομένων MAB cf. p. 458, 3. 22 ἔσται EAB
footnote §§ 104—105 cf. adv. dogm. III 267—268. 25 περὶ AB 145, 1 τὰ γὰρ — 160, 20 om. T (vide p. XI) 2 παρέκβασιν L: παρέμβασιν M: παρέκτασιν EAB 10 lacunam quam statuit Apelt sic fere explet &lt;ὃ ἀδύνατον&gt; melius fort. &lt;ὅπερ ἀδύνατον&gt; Pasquali, at malim &lt;κατὰ μὲν οὖν ἐνεργείας αἰτίου οὐ μεταβαλλει&gt; coll. p. 148, 8. 155, 12 ante εἰ L inser. ὃ
footnote §§ 106—107 cf. 144—145. (ad 107 cf. adv. dogin. III 271 sqq.) 19 ἔστι G: ἔσται edd. 1 ἐν add. Bekk. || ἀμερῆ L 2 μαλ-θακότητα EB : μαλκαότητα A (sic) 5 μήτε — 6 οὐδὲ add. Fabr. qui οὐ scripsit, quod correxit Pasquali 6 μεταβάλλειν Fabr. : μεταβάλλει G 7 τις EAB : τι ML || lacunam quam statuit sic fere explendam censet Bekker ἤτοι &lt;αἰσθητή ἐστιν νοητή. καὶ αἰσθητὴ μὲν οὔκ ἐστιν· αἱ μὲν γὰρ&gt; αἰσθήσεις
footnote § 109 ~ adv. dogm. IV 323. § 111 ~ adv. dogm. III 269. IV 346. § 112 ~ adv. dogm. IV 326—327. §§ 113—114 ~ adv. dogm. IV 344—345. 23 ἐγενήθη L 24 ὁ σωκρ. post ἐγενν. EAB || ἤτοι add. Bekk. 28 ὑπόθεσιν. οὐκ ἄρα ἐγένετο x003E; E. Weber
footnote § 116 cf. adv. dogm. IV 246.  ἀφαιρέσεις in mrg. L (cf. p. 146, 15), quod probat Kayser coll. p. 146,15; at malim ἀποθορήσεις cf. p. 49,19.
marginal 29a
footnote §§ 120—121 ~ adv. dogm. IV 7—12 (cf. Aristot. Metaph. p. 983a 26sqq. Fhys. 208b 11sqq.) 23 ὡς del. Bekk. 24/25 περιέχομαι MEAB: περιέχο L 25 πρὸς ἄκρ’. secl. Kayser || τόπου secl. Bekk. || τοῦ addidi 26 τούτων EAB 28 ἂν om. MA 29 λέξειε Kayser: λέξει G 29/30 fort. &lt;τὰ&gt; ἔμπρ.&lt;τὰ&gt;ὀπ.?   τῶν Kayser
marginal 5a
marginal 25α
footnote §§ 122—123 ~ adv. dogm. IV 13—19. § 124 ~ adv. dogm. IV 3—4 1 ἀκούω M 5 ἔσται edd. 7 ἐν ἑκατέρῳ et ἐν ἀμφοτέροις del. Kayser 7/8 ἀμφοτέροις EAB: ἀμφοτέρων ML 8 fort. &lt;οὔτε αὐτὸν τὸν τόπον οὔτε&gt; add. post τόπον 16 τὸ Bekk. dub. || ἀνύπαρκτα EAB: ἀνύπαρκτον ML 17 τε G: δὲ Gen. 21 ἐμβριθεστέραις Gc cf p. 65, 11. 15. 18. 20. 27 et saepius: ἐμβριθεστάταις Bekk. 22 τῇ alt. om. L
footnote 9 Pappenli. et Apelt coll. p. 62, 1. 574, 13: μένον G οὐ G: ὃ Pappenh. 11 ἢ δὴ L
footnote § 129 adv. dogm. IV 21—23. § 131 cf. adv. dogm. IV 30 1 ante πρὸς lac. exst. in M || περὶ κενοῦ ML i. mrg. 5 κινούμενον Bekk.: κενούμενον G 9 εἷναι Gen: ἐστι G 10 διὰ — 12 τόπον bis EAB: om. M
footnote 28 τῷ om. edd. 10 τῷ τόπῳ L 24 fort. οὗτοι οἱ λόγοι?
marginal 33α
marginal 4α
footnote §§ 136—137 ~ adv. dogm. TV 170. 176. 181 (ubi singulis placitis continuo additur ἡ ἀντίρρησις). 219. 228. §§ 138 ~ adv. dogm. IV 216. 31 ὅλου et ὅλον Bekk. : χρόνου et χρόνον G 2 μονῆς Gen. et A corr. : μόνης MLEB 11 fort. γὰρ &lt;ἀλλήλαις&gt;? 14 τὸ om. L 18 τὸ addidi || τὴν tert. om. EAB
footnote §§ 141—142 ~ adv. dogm. IV 189—192. § 143~adv. dogm. IV 193—195. 23 τι addidi coll. p. 155, 9. 2 &lt;δὲ&gt; ἔσται EAB
footnote §§ 144—145 ~ adv. dogm. IV 197—199. § 146 ~ adv. dogm. IV 200—202. §§ 147—148 ~ adv. dogm. IV 203—205. 31 ἐνεστῶτα M 32 ἀνεπινοήτως Kayser: ἀπερινοήτως G 1 fort. &lt;καὶ&gt; οὕτως 5 οὖν del. Bekk. coll. p. 146, 27; fort. 9 ἔσται Μ || τι om. L || ἀνυπάρκτων Kayser: ἀνυπάρκτου G
footnote §§ 149–150 ~ adv. dogm. IV 206—211. 29 αὐτῷ Bekk. : ᾧ G 32 οὐδὲ Stephanus: οὔτε G 7 μήτε alt. Gen.: μηδὲ G
marginal 24α
footnote § 153 cf. adv. dogm. I 104. § 154 ~ adv. dogm. I 99—100 adv. math. IV 4—5. § 155 ~ adv. dogm. I 95—97 IV 283. 15 τοῦ Πυθ. Bekk. : τῶν ΙΙυθ. G 19 αἱ ἄτομοι coll. p. 527, 7 28 ἄρα ML: γὰρ EAB 29 ἀόριστος Fabr.: ἄριστοςG: om. Stephanus 30 δυάδες alt. om. M 5 τριάδος EAB
footnote § 156 ~ adv. dogm, IV 285—287. adv. math. IV 11—13. §§ 158—162 ~ adv. dogm. IV 293—298. 16 τὸ add. Rüstow 17 lac, quam stat. Gen. κατὰ τὸν ἑαυτοῦ λόγον Gen.: καθὸ ζῷόν ἐστιν Bekk. 20 οἱ del. Kayser 21 ὁ EAB: om. ML 22 ἀριθμὸς om. M (fors. recte) || τύχοιεν Gen.: τυχοῖσαν G 23 ὄντες scr. Sexti variandi studium respiciens coll. p. 102,3. 160,12: τυγχάνοντες G 29 εἰ om. EAB 6 αὐτὴ Gen.: αὕτη G
footnote 14 μενοῦσιν scr.: μένουσιν G 15 μέρος τι ML: τι μέρος EAB 18 μονάδος Stephanus: δεκάδος G 26 excidit ὅπερ ἀδύνατον vel simile quid || γὰρ G: οὖν Bekk. dubit. 2 ἑκάστῃ Bekk.: ἑκάστην G
footnote §§ 164—165 ~ adv. math. IV 21—22 (e Platonis Phaedone 96 E sqq. sumpta.) 27 τι add. Bekk. 29 δυάδα Kayser: μονάδα G 30 ὥσπερ ὥστε G ἐκ τῶν LEAB: αὐτῶν M 11 παρὰ Bekk.: περὶ G
marginal 30a
marginal 5a
footnote § 168~adv. dogm. V 2. §§ 169—171 ~ adv. dogm. V 22—27. 20 inde a τοσαῦτα denuo incipit T (cf. ad p. 145, 1) 21 ἀρκούντως T (sufficienter): : ἀρκοῦντα G 25 &lt;καὶ&gt; περὶ T de) 26/27 ζητήσωμεν LEABT (queramus): ζητήσομεν Μ
marginal 14a
marginal 19a
marginal 19b
footnote § 172 ~ adv. dogm. V 30 §§ 173—174 ~ adv. dogm. V 35—39. 10 reputari Τ 14 a τὴν add. Kayser 15 πρᾶξιν EAB: πρᾶξις 19b συλλαμβάνον G: collectivum Τ: συλλαμβανόμενον Bekk. dub. coll. p. 551,25: συμβαλλόμενον Kayser coll. p. 97, 13. 163, 1: fort. συνεργοῦν coll. v. 24 22 τινες — λέγουσι Τ (quidam — dicunt) 24 quod cooperatur T 28/29 habentia communitatem cum aliis Τ 33 οὕτω καὶ Τ (ita et): οὕτως G
marginal 20a
marginal 25a
footnote § 175 ~ adv. dogm. V 42 — 44 (ex Aenesidemo) § 176 ~ adv. dogm. V 40. § 177 ~ adv. dogm. V 59—61. 9 ἀγαστὸν Fabr. coll. p. 553,4 (idem Plato): ἀγωγὸν GT (agogon) 12 ἄσπειστον Fabr.: ἄπιστον GT (incredibile)   &lt;αὐτοῦ&gt; τούτου Τ (ipsius eius) 19 &lt;οἱ μὲν&gt; λέγ’. Pappenheim
marginal 29α
marginal 20α
footnote § 179 ~ adv. dogm. V 69—71. §§ 180—181 ~ adv. dogm. V 44—47. 73. 1 συλλαμβανόμενον? cf. p. 558,21 6 καὶ post δῆλον add. EAB: fort. ἐστιν T (manifestum est) 20 ἀδδηφαγεῖν G
marginal 29α
footnote §§ 183–184 ~ adv. dogm. V 79—84. 28 τὸν addidi 30 ἢ ἐκτὸς vel ἢ del. Apelt 3 ἐπεὶ L 8 τῇδε LEAB: τῆ Μ 9 τῆς add. Bekk. 24 εἴγε μὴ A
footnote §§ — 186 ~ adv. dogm. V 87—89. 29 fort. &lt;τῆς σαρκὸς&gt; κίνησιν coll. p. 48, 32. 1 γίνεται Τ (fit): ἐγγίνεται G 3 αὐτῷ MAB: αὐτὸ LET (ad ipsum) 6 ἢ περὶ ἀμφότερα del. Kayser coll. p. 166, 7/8. 9 ἑαυτῷ T (in se): ἑαυτὸ G 19 παραλείπωμεν ML: παραλίπομεν EAB
marginal 25a
marginal 29a
footnote 23 ἡδονὴ L 26 τινάς, τὰς ἀρετάς G: αἱρετάς T (artes eligihiles) 1/2 ἀνειδωλοποίησιν G: ymaginum ydeas simulationem Τ 2 ἐπιδεκτικὴν LT (susceptibilem): ἐπιδεικτικὴν MEAB 4 ἢ om. L 8 μηδὲ Bekk. dubit. 16 οὐδ’ ἀδιάφορόν Τ (nec indifferens) : οὐ διάφορόν G || τι E in ras., T (aliquid): τῆ ML: om. AB || περὶ om. T
marginal 19a
marginal 24
footnote §§ 191–192 ~ adv. dogm. V 62—66. § 193–192 dogm. V 99 33 ἐστι om. AB 2 καὶ Τ (quod leones naturaliter auda-ces sunt et videntur fortiter agere) : ἐπὶ τὸ G, unde Gen. ὁρμᾶν pro τολμᾶν coniecerunt 3 δοκεῖν MEAB: δοκεῖ L 5 λαγῴ scr.: λαγὼς MLE pr. : λαγωοὶ AB et E in ras., unde edd.   βλακ. post 10 τῶν ἀνθρώπων transponi iubet Apelt: lasciviens quideni vel Τ 9 τυφωθεὶς MEABT (elatus): τυφλωθεὶς L
marginal 14a
footnote §§ 194—196 ~ adv. dogm. V 96—98. 14a ἔνεστι Τ (inest) 20 ἀμέτρως Nauck: ἀμέτροις GT (inmoderatis) 23 ἀγαθοῦ MLT (boni): ἀγαθὸν EAB: ἀγαθῶν edd. 28 ἡ AB: om. MLE 8 ἐθῶν GT (consuetuclinibus): θεῶν Kayser 9 κατηχουμένους L
footnote 12 Γερμανοῖς GT (apud germanow): Καρμανοῖς Fabricius cf. p. 35, 8 19 Κιτιέα Bekk.: Κιττιέα G: citiensem Τ 23 γοῦν ML: οὖν EAB 28 καὶ om. T 7 ἀπ’ Gen.: om. G: in eis dependent T 9 ἂν add. Bekk. 10 τοῦ vel τούτου secl. Pasquali
marginal 4a
marginal 9a
footnote 11 &lt;οὕτω&gt; καὶ T (sic et) cf. v. 20. 23 ἀσκοῦντες δοκεῖν 27 Κιτιεὺς Bekk : Κιττιεὺς G 28/29 τῷ ἑαυτοῦ μορίῳ MLT (suo memhro confricare): τῶν αὐτοῦ μορίων EAB 2 δοκι-μάζει Kayser 6 ἀπέρατον EAB 7 ἄλλοις EAB 8 τούτῳ om. T
footnote 18 σκύθας L 20 et 24 fort. &lt;ὁ&gt; παρ’ ἡμῖν v. 21 ἑταίρων T (amicorum) 22 καὶ — 23 μίγνυσθαι om. EABT 5/6 secundum mancipia T 8 fort. ἀλλήλους pro πολλάκις scrib. cf. p. 35, 32. 36, 2. 10 δὲ add. Τ (autem et)
footnote 23 post φιλοφρονησάμενος fort. inser. ὠνείδισε vel simile quid coll. Thuc. I 5, 2 || διὰ τὸ ὑποπτεύειν G: sed propter id quidem suspicdbatur Τ 24 τὸ add. coll. p. 170, 5. 9. 13. 171, 14 || post κλέπτειν Gen. inser. μὲν 25 θεὸν om. M 28 κλέψαντας MEAB: κλέπτας L ὁ ἔντος Brunck: ἐντὸς G: interius Τ || κάλλιπον Τ (dimisi): κάλλιπεν G 7 ὐπ’ αὐτῶν Τ (ab eis): περὶ αὐτὰς G: παρ’ αὐταῖς Bekk. 9 ἔσχον G: hahebant se T: εἶχον vel ἐσχόλαζον Bekk. dub. at cf. p. 177, 13.
marginal 19a
footnote 15 θεραπείας vel θρησκείας add. e Τ (de creduUtate autem atque pietate deorum) cf. p. 173, 3. 174, 10. 21 τὸν θεὸν εἶναι AB 1 ἐμπίπτειν T (incidere): ἐκπίπτειν G 4 add. Τ (in quibusdam sacris pufantur sancta) 6 τοῦτο om. Τ: τι τοιοῦτον Kayser 10 excidit τινὲς δὲ vel nomen proprium cf. p. 170, 17
footnote 11 Ὥρῳ Fabr.: ἥρω G: yro Τ 12 σίλφην GT (silfen) suspectum 16 ἐῶ ΜΤ (dimito): ἐν ὧ LEAB 17 στοχαζόμενος Bekk.: παραστοχαζόμενος G: breyitatem considerans T 24 ancipitres T (legit fors. ἱεράκων interpres) 26 νομιζομένων EAB 28 κρόμυον L 30 σκορόδου edd. et A 31 οἶς add. Bekk.: abstinentiir autem in sacris quidam T 3 τε ML: δὲ EAB: om. Τ
marginal 4a
footnote 10/11 ea que putantur religiosa et que putantur illicitaT 12 δέ &lt;τούτοις&gt; T (proxima autem hiis) || ἔστι om. EABT || κατοιχουμένους L 20 γυψίοις L
marginal 14a
footnote 17 om. L 20 gaudentes et henedicentes T 23 μηδ’ ἐσιδεῖν Gen.: nec aspicere T: μὴ δὲ ἰδέειν G || ἠελίου L: ἠελίοιο MEAB 7 τούτων Τ (de hiis): αὐτῶν G
marginal 9a §§ 235—237 ~ I 25—27, adv. dogm. V 158—161. 18 post πρακτέον Gen. inser. ἢ μὴ πρακτέον 19 δὲ om. Τ 27 λιποψυχεῖν EB 33 καὶ om. Τ cf. p. 8, 23sqq. 3 desistere compellemus Τ
footnote § 239~adv. dogm. V 173—177. §§ 240—242 ~ adv. dogm. V 180—183. 13 se hahet Τ (cf. ad 172, 9) 18 τἀγαθοῦ Bekk.: ἀγαθοῦ G 28 ἐκ καταλήψεων Bekk.: ἔγκατ’. G: om. T 2 τε om. Τ 4 καταλαμβανομένης EAB
footnote §§ 243—244 ~ adv. dogm. V 188—189. 197—199. 207—209. 15 κατελῆφθαι: γεγενῆσθαι Kayser coll. p. 580, 32. 19 ἂν Τ (utique): ἐὰν G 21 malim παρ’ παρακαταθήκας ἧκας coll. p. 584,   οὐδὲ Pappenh. dubit. 24 γινόμενον GT (factum): λεγόμενον Stephanus coll. p. 185, 18; at hic γινόμενον pro locutione πραττόμενον usurpatur, quae differt a verbo ποιούμενον || τι Gen.: τε GT (quoque) 28 τῶν om. L 31 τὴν Bekk. : τῶν G
marginal 4a
footnote §§ 245—249 ~ adv. dogm. V 190—196. 3 add. Bekk. 8/9 διαμηρίζειν Gen. : διαμερίζειν G 10 διαφέρει ἐν Τ (differt in): ἐστι G 11 &lt;ἄλλα&gt; ἢ μὴ edd. 19. καὶ om. edd. 22 καὶ τὸν ὁμομήτριον — 23 ὁμομητρίας om. Τ 23 suppl. e T (et continu &lt;u&gt; m etiam) 25 πρὸς — om. T
footnote 1 οὐδὲ GT (nec): οὐδὲν edd. 4 ἐπέβαλλε Bekk.: ἐπέβαλε G: expedit Τ 5 &lt;τὸ μνῆμα&gt; ἐᾶς. Dyroff coll. p. 583, 28 18 ὑπαρκτὴ MEAB: ὑπαρκτικὴ L 25 ὑπῆρχεν Kayser
marginal 30a
marginal 14a
footnote § 253 ~ adv. dogm. V 232. § 254 ~ adv. dogm. V 227—228. 30 ἐκ κατ’. Bekk. : ἔγκατ’. G 1 προωμολογῆσθαι Μ: εῖσθαι L: -ομολογεῖσθαι EAB 8 λέγοιτο om. L   διδ. coni. Gen.: ambiguitates Τ
footnote § 255 ~ adv. dogm. V 224—231. §§ 256—258 ~ adv. dogm. V 219—223. §§ 259—265 ~ adv. dogm. V 234—238. 22 supplevi 32 add. T (secundum quod est ens, est docibile) 4 ἄλλο om. Τ 8 inde ab ἄδηλον incipit Ρ 10a εἰ ἔστιν τις διδ. ἢ μαναὶ. P
footnote 17 ὥσπερ &lt;γὰρ&gt; P 18 ὁ P: om. a 21 λέγεται GT (dicitur): φαίνεται P 26 ἐνέσται GT (inerit): ἔνεστιν P 27 ἐκκαταλημεων P Paris suppl. 133: ἔγκατ’ G 29 λέγοι Gen. 33 δύναιτο om. L 4 ἐγνωσμένα &lt;τῶ&gt; P
footnote §§ 266—269 ~ adv. dogm. V 239—243. 18 ἐς GP 19 ἂν λάβοι P: ἀναλάβοι GT (non assumeret) 24 τῆς om. L 29a tit. exst. in L et P; in Μ et EAB sectio nova incipit v. 31 Οὐδὲν κτλ. praefixo titulo: εἰ ἔστι μαθήσεως τρόπος 82 οὗτος addidi, κατὰ ἰδίαν Riistow coll. p. 182,12 33 ἐναργείᾳ utrobique Fabr.: ἐνεργείᾳ GPT (actu)
footnote §§ 270—272 ~ adv. dogm. V 243—247. 8 μὲν add. P: om. GT 9 οὐδεὶς EAB 10 τι alt. om. P 27 μάθησις &lt;τις&gt; P 30 περὶ &lt;τὸν&gt; Gen. 5 εἷναι om. L
marginal 29a
footnote §§ 273—277 ~ adv. dogm. V 210—215. 14 καὶ ante ἡ om. P 18/19 τῆς φρονήσεως scr. coll. p. 594, 4: τῆς ζητήσεως T (questionis) : τήσσεως G (in P vv. 18 — 21 obliterati sunt): μαθήσεως Gen.: τῆς μαθήσεως Bekk. 23 λεγομένη τέχνη MLP: τέχνη λέγ’. EAB 81 καλὸν P: κακὸν GT ( malum)
footnote 32 σοφὸς om. T, sed exstat quoque p. 587, 17. 3 φαύλων L 6 οὖ om. P: ἦς A 9 τῶν τοιούτων GT (talium): τούτων P sicut p. 587,25. 17 18 20 21 ἣ pro εἰ P sicut G ἧ p. 588, 1.   4. 5. ἴ’ 21 τῆς om. L 24 διόΠερ P: ὥστε G: qtiod Τ 28 τὰρ. σφόδρα GT (turbatur valde): σφόδρα ταράττεται P
