@node
@author=Libanius
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Richard Foerster
@filename=tlg2200.tlg00549.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane
@publicationStmt=University of Leipzig, tlg2200.tlg00549.opp-grc1.xml.
@respStmt=Gregory R. Crane, Editor-in-Chief, Perseus Digital Library, Digital Divide Data, Corrected and encoded the text, Matt Munson, Project Manager (University of Leipzig), Annette Geßner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor, Greta Franzini, Project Manager (University of Leipzig), 2013-2014, Frederik Baumgardt, Technical Manager (University of Leipzig), 2013-2015, Simona Stoyanova, Project Manager (University of Leipzig), 2015, Project Assistant (University of Leipzig), 2013-2014
@sourceDesc=Richardus Foerster, Richard Foerster, Libanius, Declamationes XXXI-LI, B.G. Teubner, Leipzig, 1913, 7, Internet Archive.
@sponsor=University of Leipzig
@title=Declamatio 49
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:58:00Z

8144	marginal RIV 739
footnote Η = Codex Hierosolymitaims S. Sepulcri 107 V = Vaticanus gr. 940 Vi = Vindobonensis philos. et philol. IV 82 Ma = Matritensis 4679 (N-49) Cl = Bodleianus Miscellaneus 208, olim Claromontanus Ath = Athous Laurae S. Athanasii Ω 123 Β = Barberinus II 41 (Vatic. Barb. 220) Va = Vaticanus gr. 82 M = Marcianus gr. 439 1 ἀντεγκληματικὸς στοχασμός Ma rubr στοχασμὸς ἀντεγκλη- ματικός B rubr 1 ὑπόθεσις. ὅρος. ante Διέσωσέ Ath Ἄλλη μελέτη. ὑπόθε- σις. Mor Re delevi Διέσωσέ — 648, 10 μητρυιά praemissis ver- bis ὅμοιον τῷ παρόντι προοιμίῳ καὶ παρὰ τῷ Λιβανίῳ ἐν (om Vat) ἐκείνῳ τῷ διπλῷ τελείῳ στοχασμῷ citat Io. Doxapat. in commentario ad Hermog. de inv. I 1 Rhet. gr. t. III 70, 22—71, 3 ed. Walz. = t. II 181, 16 sq. ed. Spengel. cod. Vat. gr. 2228 fol. 209 v. Bar. gr. 175 fol. 29 v | αὐτοῦ Doxap 2 σώσειν Mor 3 σῶσαι in ras V 2 σώζειν H Doxap 4 ὁ πατὴρ μητρυιὰν Doxap | μητρυὰν ΗΒ 5 δεδεμένον] δὲ μόνον Vi 7 παιδὸς HVi | ἂν ante εἴη Η
marginal RIV 740
footnote 5 Schol. ad Hermog. stat. Rhet. gr. t. VII 261, 17 ed. Walz. 8 cf. t. IV 184, 3 10 ἡ στάσις στοχασμὸς ἀντεγκληματικός Μ ἡ στάσις Ma3 1 μεταταῦτα VMaClBVaM 2 ἀποκληρονόμον Μ ἀπό- κληρον ViMaCl sed in hoc κλῆρον in ras fere 8 litt, BVa et γρ in marg Mor | post ἀπόκληρον· ras 3—4 litt Va 3 τὸν om Vi | κατέλιπεν Vi | καὶ νυκτὸς om Doxap 4 δὲ post θο- ρύβου Doxap | κατὰ — 5 μὲν in marg Ma 3 5 εὕρηται ὁ μὲν πατὴρ scripsi ex HVViMa 2 ClBVa Doxap ὁ μὲν πατὴρ εὕρη- ται AthM edd 7 μητρυὰ Η | τῆς οὐδοῦ ante παρακαθεύ- δουσα Vi 8 τῆς Vi | ὀδοῦ Ath | ἔμεινεν Ath 9 ὁ τυφλὸς] ὃ τε παῖς Doxap 10 μητρυά ΗΒ | αὐτοῦ post μητρυιὰ Vi, στο- χασμὸς ἀντεγκληματικός in marg Va 3 edd delevi 11 Προθεω- ρία om ClVa inser Vi3 12 Τὸ — 651,12 πιστεύωσιν inser Vi3 13 καὶ φαίνεται Ath 14 ἀκριβεστέρως MaCl ἀκρι- βεστέροις Ath 16 καὶ — 649, 1 οἰκονομίας in marg Ma3
footnote 5 cf. t. V 393, 15 1 ἐξεραίτως edd sed „emenda ἐξαιρέτως“ Mor Not f. VII 4v 2 πλοκὴν scripsi ex HVViMaCl Ath συμπλοκὴν BVaM edd 3 πράγματι Ma sed πλάσματι suprascr m 3, Cl 4 ἕκαστον in marg insei AthMa 3 5 προθεῖναι scripsi ut coni Re coll 1. 19 προσθεῖναι Vi 3MaCl sed in boc σ eras, Ath M edd προσθῆναι HV προστιθέναι BVa | ποιούμενος, ἢ δι’ ὅλου Ath 6 πληρώσαντα Β | τὸν Μ Mor 7 εὑρίσκουσι Ath | ἀγω- νιστικώτερον om Ath 9 συγχύσεως V sed χυ in ras m 2 συγ- γνώσεως HVi 3 | δὲ om HVVi 3 | δι’ ὅλου Ath 11 κατηγορίαν Β et in ras Va 2 | δεύτερον HVVi3 Ath | ἀπολογίαν BVa γρ ἀντιλογίαν in marg Mor 13 καταδύναμιν Ath | τὴν ante δύ- ναμιν Ma 14 et 16 τοῦ] τὸ Vi 3 17 τοῦ Ath 18 δὲ Ath 19 παρατάττοντες Β Va
marginal RIV 741
footnote 8 cf. t. IV 170, 22 1 ἀφ’ MaClAth | καὶ ante ἰδίαν Ma | ἰδίᾳ om HVVi 3 2 εἰσάγομεν Ma sed ἠγάγομεν supraecr m3 3 διαχείρισιν scripsi ex Ath et Par. 854 cum Bastio Greg. Cor. p. 80 ed. Schaefer διαχείρησιν reliqui libri edd | γίγνεσθαι AthM edd γενέσθαι VVi 3 6 τοῦτο V sed ~ το in ras m2 τοῦτον Vi 3 | ἑκάτερος ἐν Η 7 αὑτοῦ Μ αὐτοῦ reliqui libri edd 8 μητρυᾶς Η 9 βλέποντα HV sed in hoc in βλάπτοντα corr m2 | τῇ inserui ex HVVi 3 εἰ AthBVa om MaClM edd 10 ἁθρόοις Μ 13 οὐδὲ μίαν HMa 15 μὴ inser Va 2 | δοκεῖ Cl | περιγίγνεσθαι MaVaM edd 16 δι’ αὐτῶν BVa 17 κατηγορεῖ συναπολογούμενος V sed κατηγορεῖ σὺν in ras m2 συναπολογεῖται ἀπολογούμενος Η 19 τῆς — 20 παρεχο- μένης om HVVi3 20 παρεχόμενος Ath παρεχόμενον MaCl
marginal RIV 742
footnote 1 Longin. inv. Rhet. gr. IX 595, 7 sq. ed. Walz. 12 Προοιμιαζόμενος ἐν τῷ διπλῷ τούτῳ τελείῳ στοχασμῷ ὁμολογεῖ ὁ υἱὸς ὑπὲρ τοῦ πατρὸς ἀγωνίζεσθαι καὶ οὐ κρύπτει τοῦτο, ἀνεπίφθονος γὰρ ὁ ὑπὲρ τῶν προσηκόντων λόγος, ὡς ὁ ἐρμογένης διδάσκει: καὶ ζήτει ἐκεῖσε post πιστεύωσιν Ath 13 στοχασμὸς ἀντεγκληματικὸς HVB 14 τὸ ᾶ προοίμιον ἐξ ὑπολήψεως τῶν δικαστῶν M rubr Ma3 2 διόλου Vi 3 MaB 3 φυλάττειν Μ | τοῦ om Va Re 4 ἀποκειμένων Cl sed ἀ ex ὑ corr 7 εὐεργεσίαν HVVi 3 8 ὧς inser Ma 3 | ἐπιτοπλεῖστον Vi 3 B | τὸ om Ath 9 προσκα- λεῖται HVVi 3 MaAth sed in hoc σ del 12 πιστεύωσιν V sed ω in ras m2 πιστεύουσιν HVi 3 13 Ὁ πηρός scripsi ex H rubr V Ma rubr Ath ὁ πηρός. ἡ μελέτη M rubr ἡ μελέτη Vi rubr B om ClVa τυφλοῦ φιλοπάτορος ἀπολογία edd 14 Μόλις — 652, 7 ἀνῃρη- μένῳ praemissis verbis ἐν τούτῳ τῷ ζητήματι μελετῶν ὁ λιβάνιος τὸν πηρὸν προοιμιάζεται οὕτως citat lo. Doxap l. l. cod. Vat, fol 209 v Bar. fol 29, — 15 ἀναπαυσάμενος praemissis verbis Λιβάνιος ἐν μελέτῃ τῇ Διέσωσέ τις ἐμπρησμοῦ γενομένου τὸν ἑαυτοῦ natSQaTho- mas Mag. s. v. διέπαυσέ τὶς τινα καὶ διεπαύσατο αὐτός. καὶ ἔπαυσε καὶ ἐπαύσατο, καὶ ἀνέπαυσε καὶ ἀνεπαύσατο p. 85, 3 ed. Kitschl 15 παυσάμενος ViMa παρ’ in fine lineae absumptum Cl πρὸς Ma
marginal RIV 743
footnote 1 τίς — 2 παραμυθία; om Doxap 2 ἔτι om Vi 3 ὑπο-λαμβάνω BVa 4 εὐλογωτάτων Η | δυνατωτάτοις Doxap 5 ἀφειδῶς ἐμαυτὸν Doxap | ἔδωκα ἀφειδῶς Vi 6 νῦν Ath | παρὰ — 7 νόμους ora Doxap | παρὰ Vi sed περὶ suprascr m2 7 ἀνῃρημένον Vi sed ω supra ὂν m 2 8 γενομένην scripsi ex HVViMaClAthB Va γεγενημένην Μ edd | καθ’ Ma 9 ἐλέγξαι Μ Mor | ἐλέγξαι μεθ’ ὑμῶν BVa | ὅμως γάρ, κἂν scripsi ὅπως γὰρ ἂν HClAthBVa ὅμως δὲ Vi εἰ γὰρ ὅπως ἂν V sed in ras m 2, et in marg Β, edd εἰ γὰρ ὅπως γὰρ ἂν Ma sed εἰ γὰρ inser m 2 et γὰρ(2) del κἂν γὰρ Μ εἰ γὰρ coni lacobs Lect 140 10 αἰτία γεγενημένη scripsi ex HVVi Ma sed in hoc γρ γενομένη suprascr, Cl αἰτία γενομένη Ath γενομένη αἰτία BVaM edd | ὑμίν coni Mor aut πολλοὺς ἡμῖν ἔχουσα πολεμεῖ τοὺς συνηγόρους, οὓς ἀπὸ τῶν scribendum aut ἡμῖν delendum coni Re ὑμῖν ἕλκει τοὺς συνηγόρους οὓς lacobs Lect | ἔχει ViB 11 οὓς inserui ex HViMaClAthB Va ut coni Re lacobs del ras V om Μ edd 13 co scripsi e Μ ὦν reli- qui libri edd | ὅμως ἂν ante οἶμαι inserendum coni lacobs Lect 14 τὴν om Mor | ὑμῶν Vi sed ὑμῖν in marg m 2 15 ἡμῖν Cl | καταστήσειν scripsi καταστῆσαι libri edd | καὶ ante τὴν Vi 16 ταύτην M | ἂν om ViBVa Re
footnote 4 προοίμιον δεύτερον H sed δεύτερον abscisum, VB rubr 1 καὶ inser V2 om Vi | ἡμῶν Vi sed ι supra ω m2 ἐπιχειρεῖ Ma sed st ex ῆ corr m2, Cl sed εῖ in ῆ corr, BVaM ἐπιχειρεῖν Vi sed ν del m2 2 αὐτῶν HViMaClAthBVa et scribendum coni lacobs Lect | ἐγκλήμασι δείξομεν Vi | ἐπι- δείξωμεν MaCl 4 συμβέβηκε Vi 8 μὲν om ViVaM 10 ἄμα om Vi 12 δὲ om Vi 17 συμβῇ τι, παθεῖν scripsi συμβῇ τί παθεῖν HVViAth συμβῇ τι παθεῖν BVa συμβῇ, τί παθεῖν Μ edd συμβῇ τι καὶ παθεῖν MaCl sed in hoc καὶ inser m3 18 ἐάσαι HAth sed in hoc e ~ corr 19 τοῦ — 20 ἡμέτερον in marg Vi2 | τοῦ scripsi ex HVVi2Ma sed in hoc γρ τὸ suprascr m3, ClAthBVa ut coui Re τὸ Μ edd | ὑπάρξει scripsi ὑπάρξαι HVVi2Ma sed in hoc οἱ supra αι, ClAthBVa ὑπάρξοι Μ edd | ὑπολαμβάνειν αἰτίαν AthBVa Μ Mor | αἰτίαν om Vi2 20 ὑπολαμβάνω HMa sed in hoc εἰν supra ω m3, Cl sed ω ex εἰν corr | τοῦ HVVi2Ma sed in hoc γρ τὸ suprascr m3, ClAthBVa | ἡμετέραν HVVi2Ma sed in hoc ἡμέτερον suprascr m3, ClAthBVa RIV 744
footnote 4 cf. ad p. 430, 16. t. VI 387, 9 1 προοίμιον] τρίτον κατα[σκευὴ] τοῦ προ[οιμ]ίου τούτου Η προοίμιον τρίτον VBrubr 6 κατασκευὴ τοῦ προοιμίου τού- του Β 1 ἐγὼ om BVa | ἐκείνου om Vi 3 παντάπασι — 4 ἐκέρ- δανα praemisso Λιβάνιος citat Andr. Lopad. lex. Vind. s. v. ἐκέρδανε τὴν συμφορὰν ἀντὶ τοῦ ἐξέφυγε p. 58, 13 ed. Nauck | μεταταῦτα VViMaClBVaM Lopad edd 4 ἐκέρδανοα Μ ἐκέρδανον MaCl 5 τῇ inser Va2 et in marg Vi2 | σωτηρίαν Vi sed v del m2 6 με om Vi 9 ἂν ante τὴν Va 10 οἰκτρότερον scripsi ut coni Mor et lacobs Lect οἰκειότερον libri edd | πατρὸς Ma sed πράγματος in marg m3 11 δὴ Vi sed δὲ in marg m2 | κουφότερον Vi sed κουφοτέραν suprascr m2, M Mor | εἶχον Cl2 13 γὰρ ἂν] ἄνευ Vi 14 ἐζήτησεν Ma | ἂν om BVa
marginal RIV 745
footnote 6 κατα[σκευὴ τ]οῦ προ[οιμίου το]ύτου Η 12 τὸ αὐτὸ ἐμαυτῷ τὴν μητρυιὰν ἐπεισάγειν M m τὸ βιάζεσθαί βιάσασθαί Mor) με μητρυιὰν ἐπαγαγεῖν μοι Ma3 Mor 1 νῦν H | συμβᾶσαν scripsi ex HV (σθμβάσαν) α Β ξυμβᾶσαν VaM edd 2 εὐχερῶς Va sed cog in ras m2 3 ἀφῃρημένος Va sed σ ex v corr m3 4 ὑπῆρχεν Ma 7 νενίκηκεν Ma 8 τοῦ om Vi | αὐτὸς Va sed τὸς in ras m2 9 ἑαυτῶ Vi sed ἐμαυτῶ in marg m2 | τῶν — ἐμαυτῷ om Ath 10 τὴν om HVViMaCl „non male omittit B(avaricus) articulum τὴν“ Re | μητρυὰν Η | δὲ om Vi | παροινίας HVMa ClAth | ἢ MaCl 11 τούτοις scripsi ex HViMaClAthBVa sed in hoc ἐπὶ τούτοις in marg m2 τοιούτοις VM edd 12 τὸ scripsi auctore Re τί vel τι libri edd 13 τοῖς εἰρη- μένοις om Vi | γὰρ om Η δὲ V | τὴν om Ath 15 παρειλή- φασιν Ma 16 τούτων Ma sed ύ et ων in ras m3 | αἴτιον inser Va2 17 πιστεύουσιν Vi sed νομίζουσιν in marg m2 ἀκριβῶς ViMaCl
marginal RIV 746
footnote 1 cf. ad p. 128, 4 | cf. ad t. III 453, 5 10 cf. ad p. 693, 7 4 προκατάστασις ἤτοι καὶ Β) προδιήγησις M rubr Ma3 B rubr προκατάστασις Mor 1 ἅπαντα ἄνωθεν ViBVa 2 διηγήσωμαι Va sed ω corr m2 | ὁμολογήσετε Va sed σετε in ras m 2 ὁμολογήσεται Η 4 δυστυχέστερον HV | γὰρ inserui ex HVViMaAthB sed in hoc inser rubr om ClVaM edd 7 ἡμῖν HVVi 8 δείκνυσιν scripsi ex HVViMaCl cum Bastio ep. crit. 136 δεικνύει AthB VaM edd 11 μόνος Va sed o(1) in ras 2—3 litt m2 12 ὑπερβαλλόμενος HVViMa sed in hoc λ(2) inser m2, ClBVa 13 ἀνέθρεψε Vi sed ὒ supra ἑ m2 ἀνέθρεψεν Ma ἂν ἔθρεψε Va Re | ἐλευθερίαν Aih 14 διδασκαλίων HVMa sed in hoc εἰ supra ι(2) m3 | ἀπείραστον Vi sed τ supra στ m2, MaCl ἄπειρον HV 16 εἴασεν Ma | τε om HV 16 μὲν οὖν scripsi ex HVMaClAthM μενοῦν ViBVa edd | τὰ inserui om libri edd sed „post μαθήματα videtur ἃ vel τὰ deesse“ a 17 ἀρετὴν μετιέναι post περισπούδαστα Μ edd, post θεοὺς θεραπεύειν in marg Ma3 delevi | θεοὺς θεραπεύειν om Μ
footnote 4 cf. p. 689, 15; 686, 10. Solon. el. fr. 4, 14 apud Dem. fals. leg. p. 422, 10 sq. 9 cf. t. V 52, 6 12 Thuc. IV 86, 1; VIII 52, 2 15 cf. p. 591, 6; t. V 107, 10 sq. 3 μὲν post μηδὲν ViMaClBVa edd delevi 4 νομίζειν Vi sed νομίζοντας in marg m2 5 ἀπέχεσθαι Vi sed ἀπέσχε- σθαι in marg m2 7 τῇ om Vi 9 εἴρητο MaCl | τε om Va 10 διεξίασιν HV 11 ἐπαινοῦντες in marg Vi3 | ὡς inserui ex HVViMaClAthBM om Va edd 12 τούτοις Vi | ἐπαληθεύοντας reposui e libris ἐπαληθεύοντες edd 13 ἐπο- νομάζοντες Va sed τες in ras m2 | λέγων Vi 14 οὓς acripsi ex HVMaClAthBM μεθ’ οὓς Vi ὡς Va edd ὡς ἔνι μάλιστα lacobs App. Pors. Adv. 293 Lect | ἔδει HVVi 15 μετ’ om Vi 16 ἐκείνους Re | κεχαρισμένοις Η „malim κεχαρισμένος, tametsi accusativus quoque ferri possit“ a Re | γηρωκομεῖν ex HVViMaCl sed in hoc ω ex ο corr, AthVaM γηροκομεῖν Β edd cf. p. 660,9; 663,2; 664,6; t. VI 563,20; I 112,2; VI 90,7; VII 269,12; 562,11. Lobeck. Phryn. p. 692 sq. | γηροτρο- φεῖν post γηρωκομεῖν ViMaCl
marginal RIV 747
footnote 8 cf. t. ΙΙΙ 156,18: 231,21 1 τίς HViMaAth | τίς HMa | κίνδυνον HVMaClAthB κίνδυνον ὑπομένειν Vi 2 τεθναίην Vi sed τεθνάναι in marg m2 | συμβαίη HVViMaClAthBM Re συμβαίνει Va 4 γενό- μενος Vi 7 εἰ περιῆν Cl sed περιῆν e περὶ ῆν corr m2 εἴπερ ἣν ViBVa | ὑμῖν om Cl Re ἡμῖν Μ 9 γὰρ inser Va2 10 ἐκείνοις scripsi ex HVViMa sed in hoc γρ γονεῦσιν in marg m3, ClAthBVa τοῖς γονεῦσιν (γονεῦσι α edd) Μ 14 προσήκουσαν Ma sed προσηκ in ras m3 | κομίζονται Vi sed νομίζονται in marg m2 15 δεῖ om H inser V2, post καθ- έκαστον Vi, post λέγειν Ath | καθ’ ἕκαστον scripai e Par καθ- έκαστον reliqui libri edd 17 παρέδωκαν scripsi ex HV παρ- έδωκεν reliqui libri edd 18 μόνην in marg Vi2 19 ἐπι-η δείξασθαι Ath | ἐμέλησα HCl ἐμέλησα Ath ἠμέλησα ViMa sed in hoc η(1) in ras m3
marginal RIV 748
footnote 2 εὐλαβέστερον Va sed α supra ον m2 | διετέθην Μοι· sed γρ διεθέμην in marg διεθέμην Va sed γρ διετέθην in marg m2 3 ἤπερ ἰδεῖνHVi 4 μόνον Vi sed μένον in marg m2 | τὸν om HV | νομίσας ζηλωτόν τε καὶ περισπούδαστον HV 6 μοι βοηθεῖν ἐδόκει Vi 7 ἀμφοτέροις — 8 ἀδυνατώτερον om Ath 8 ἀδυνατώτερον scripsi ex HVViMaClAthBVa ἀδύ- νατον Μ edd 12 ὡς ἔφην post οὕτω, non post μητρός Vi 14 οἰκείους scripsi ex HVViMa sed in hoc γρ περὶ τοὺς παῖδας in marg m3, ClBVa sed in hoc γρ παῖδας in marg m2 παῖδας AthM edd 18 ἐπ’ inserui auctore lacobsio Lect om libri edd sed „aut supervacaneum est ἐμαυτῷ aut deest ὡς ἐνῆν vel potius, quod nunc video, ἐμαυτῷ deducendum in versum inferiorem et legendum ἔχει δέ τι καὶ ἐμαυτῶ φιλοτιμίας“ Re 21 κουφότερον scripsi κουφοτέραν libri edd
footnote 10 cf. p. 686, 7 2 ὑμᾶς MaVa sed u in ras Ma3Va2 ἡμᾶς V sed ἡ in raa m2, Cl 3 μεταταῦτα VViMaClB VaM edd 4 ἔφη post και- ρός, non post κατειληφότων Vi 5 βουλεύεσθαι scripsi ex HV ViMaCl βουλεύσασθαι AthBVaM edd 6 δὲ Vi 7 τὴν ἡλικίαν ταύτην ἄγω MaCl 9 γηρωκομήσει scripsi ex HVViMa ClAth γηρωβοσκήσει BVaM γηροβοσκήσει edd cf. ad p. 657,16 11 εὐφημίσεις Β | ἔλεγον post εὐφημήσεις, non ἔφην post πάτερ Vi ἔφην post εὐφημήσεις, non post πάτερ Ath 12 ἔφην om HVCl sed in hoc post συγχωρήσεις inser post συγχωρήσεις, non post πάτερ Ma 13 γὰρ om HV | μοι post νῦν BVaM edd delevi 14 ὑποφαίνεις ViCl sed in hoc ὑ ex ἁ corr m2 15 ἀνακινῶν Vi sed κε supra κι m2 16 ἡμῶν Vi sed ᾶς su- prascr m2 17 οὐκ ante ἀνέχομαι Vi | ἀνάσχομαι Β 18 γυναικὸς inser Vi2 | οὑτωσὶ Ma sed σὶ in ras m2 οὕτω σοι HVi sed in hoc σοι in marg m2 inser, Cl | ἵνα om Vi
marginal RIV 749
footnote 12 τὸ μὲν οὖν ἀντὶ τοῦ δὲ M m Ma3 1 αὐτὴν ὀφθαλμοῖς Ma sed η ex ο corr m3, ClM | αὐτὴν om Va | θεάσομαι Vi 2 τῇ συνεχεῖ θέᾳ in marg Vi2 3 ὁμιλίαν Μ sed γρ εὔνοιαν in marg | βεβαιώσωμαι scripsi e Par βεβαιώσομαι reliqui libri edd 6 γίγνεσθαι AthVaM edd 7 τούτου Ath 9 πῶς] πόθεν Ath | οὖν inserui ex Η VViMaCl om AthBVaM edd sed „non male B(avaricus) πῶς οὖν“ Re | εὐφροσύνη Vi sed ὁμο in marg m2 10 ἐκγάμου Vi sed ἀθανάτου in marg m2 11 γέννησις Vi | εἴπῃ HV | τίς HVi 12 μᾶλλον inserui ex HVViMaClAthBVa om Μ edd sed „W(olf.) et B(av.) post κωλύει addunt μᾶλλον. Laudo factum, nisi quod ante κωλύει id addi “ Re 15 προ- ῃρημένοι Ma sed ῃ in ras 2—3 litt m3 16 δεδιδαγμένοι Va sed δαγμένοι in ras m2 18 ἀπόλαυσιν Ma sed et σιν in ras m3 19 προβλέπειν ClBVa Re | γιγνώσκειν Ma
footnote 13 cf. ad t. V 75, 18 1 τυφλῷ — 2 ἐστερημένῳ om HV | δὲ] τε Sintenis 2 καλῶν Vi sed ἀγαθῶν in marg m2 | ἀπάντων ViMaCl 3 γὰρ ὅμοιος Ma sed παρόμοιος suprascr m3 παρόμοιος HV Ath 4 τίς δέ μοι in marg Vi2 6 δεινότατον scripsi e Vi ut coni Re δεινότερον reliqui libri et suprascr Vi2, edd 9 ἂν Vi sed γὰρ in marg m2 | καὶ νόθους ἡγήσομαι HV 10 προσφιλέστατον ViBVa | τὸν δῆμον κληρονόμον Vi 11 κοι- νῇ scripsi κοινῆ libri sed ῆ ex ὰ corr Μ κοινὰ edd 12 τῇ πατρίδι scripsi ex HVViMaClAth τῆς πατρίδος BVaM edd 15 τὸ scripsi τῶ libri sed ῶ ex ὸ corr Ma3, edd 17 καταδύναμιν Ath 18 σε inser Cl τε Ma | γηροβοσκήσει Vi γηρωκομήσει Ma 20 m om Μ | ἀγαγοῦ Ma sed γ(2) et ~ in ras m3 ἀγαγοῦ HVClAthBVaM edd
marginal RIV 750
footnote 7 cf. t. I 189,18; Ν 136, 12, Plat. leg. XI p. 932 E sq. 11 Hypoth. ad Eur. Hippol. 7 φαρμακεία ἡ διὰ φαρμάκων γενομένη μαγεία, μαγγανεία δὲ ἡ δι’ ἐπῳδῶν Ma^ Wolf cf. schol. II. ἁ 86. Suid. s. v. γοη- τεία 12 τὸ γοῦν ἐνταῦθα ἀντὶ τοῦ γάρ M m Ma3 2 δὲ reposui e libris καὶ edd Ι τὴν om Ma inser Ὂν j γνώμην Vi 3 οἶμαι Ma sed γρ καὶ οἶδα in marg m3 | χρῆμα inserui ex HVMaClAthBVa om ViM edd 6 ἀνοσίαις HV Vi 7 σκαιωρήμασιν Ma sed εὑ supra αι m3, Cl sed αι in ras m3 cf. ad p. 680,11 et ad p. 326, 16 | μαγγανεύμασι Ma sed γρ μαγεύμασι suprascr m’ μαγκανεἰας Β 8 καὶ ante δια- λῦσαι HV I ἐκπολεμῆσαι ΠVΟἰ sed ἡ m ὢ corr υα· 9 δὲ] τὲ HMaClAth | γένη Ma sed γρ μέρη in marg m2 μέρη Vi | μίση Vi sed μέση in marg m2 μίσση Ma 10 μηχα- νῆσαι Vi sed μηχανήσασθαι in marg m2 11 μιαιφόνου Β Ι σκη νῆς] μ—ρικῆς καὶ πρ—ικῆς Vi Ι μεστὰ ΓΑ sed εστὰ in ras m2 12 δρᾶ μάτα cum ras 1 litt ante μ’ Va 14 ἡμερωτάτην HV 16 βιάζηται Ma sed ἡ in ras m2 16 διελέγξεις Va sed γξ in ras m2 ἐλέγξεις Η ἐλέγξῃς V | οὔτε — 664, 1 μηχα- νωμένης praemissis verbis ἀνέχεται δὲ παθητικῶς ἀντὶ τοῦ ὑπομένει· καὶ συντάσσεται κοινῶς μὲν γενικὴ. Λιβάνιος citat Andr. Lopad. lex. Vindob. s. v. ἀνέχει p. 17, 8 ed. Nauck
footnote 1 μηχανωμένην Vi μαχομένης HV 2 ἢ scripsi ex HV ViMa sed in hoc γρ καὶ ἐν suprascr m3, ClAth καὶ BVaM edd | συγκειμένης VaM 4 καὶ om HVMaCl 5 punctum posui post ἠγάγετο ex HMaAth om reliqui libri edd | δ’ in- serui om libri edd at „fort. ἀλλ’ αὐτόχειρά“ Re 6 αὐτ’ αὐτόχειρα — ἀγαγόμενος om Vi | ἀγόμενος HV 7 ἐκεῖνον ante κατει- ληφότων inserendum coni Re at cf. p. 660, 4 9 τε scripsi τὲ HVVi μὲν MaClAthBVaM edd | φαρμακίαι BVa 10 σκαιωρήματα Ma sed εὑ supra αι m3, Cl cf. ad p. 663, 7 11 ἡ δὲ — 666, 5 πεπεισμένος praemissis verbis τῶν λεγομένων παράδειγμα λάβοις ἂν ἐκ τοῦ Λιβανίου ἐν τῷ τοῦ πηροῦ πονη- ροῦ codd.) ζητήματι, ἐν ᾦ ἀντεγκαλοῦσιν ἀλλήλοις φόνον ὃ τε πηρὸς καὶ ἡ μητρυιά ἐν τούτῳ γὰρ ὁ Λιβάνιος — κέχρηται ἐν ταὐτῷ δυσὶν ἐπιχειρήμασιν ἀπὸ μιᾶς περιστάσεως τῆς τοῦ προσ- ώπου. ἔχει γοῦν παρ’ ἐκείνω ταῦτα οὕτως citat lo. Doxap. ad Hermog. de inv. III 5 πολλάκις — ἐποίησεν Rhet. gr. III 116, 18 —20 ed. Walz. = II 216,3—6 α ed. Spengel. cod. Vat. fol. Bar. fol. 131 v | ἄρα Doxap 13 τῷ παιδὶ scripsi ex HVVi Doxap ἐμοὶ MaClAth sed in hoc γρ τῶ παιδὶ in marg, BVa Μ edd 14 γοῦν om Vi | οἶς inser Ma3
marginal RIV 761
footnote 5 Arist. nub. 1468 c. schol. Plat. Euthyd. p. 302 C sq. Dem. Eubul. § 67 p. 1319, 26 2 ἐπιχείρημα ἀπὸ τοῦ προσώπου τοῦ πατρός M m Ma3 et praemisso εἶτα ante ἐγὼ in textu Doxap 1 τὸν inser Va2 2 ἀπέκτεινας scripsi ex HVViMaClAth Doxap ἔκτεινας Β Va sed in hoc τείνας in ras m2, Μ edd 3 τοῦτο — 6 πατέρα om Doxap | ἀνηκεστέρων MaCl 4 καὶ (2)] ἢ Va 5 πρὸς &lt;Διὸς&gt; α Πατρῴου? | πατέρων 6 ἐμὸν BVa | διεχειρισάμην Doxap | τὸν — 7 ἀναθράψαντα prae- missis verbis τὸ ἀνέθρεψεν οὐ γενναῖον ὅμως εὕρηται. Λιβά- νιος citat Andr. Lopad. lex. Vindob. s. v. ἔθρεψεν p. 22, 7 ed. Nauck I πειράσαντα HV 7 τὸν(1) scripsi e Vi sed καὶ in marg m2, et Lopad καὶ reliqui libri edd 8 καὶ(1) om Mor κουφότερον Doxap κουφοτέρας et τὰς συμφοράς BVa 10 μόνος Vi sed ἦς supra ὃς m2 | ἡδονῶν Β | αἴτιος Vi sed ὂν supra ὃς m2 11 κεχαρισμένως Doxap | οὖν Doxap 12 ηὐ- φραινόμην scripsi ex HVMaAth Doxap εὐφραινόμην ViClB VaM edd 18 μὲν om Vi 14 τῶν om HV 15 νῦν Ath
footnote 1 ἕτερον ἐπιχείρημα ἀπὸ τοῦ πράγματος ἤτοι τοῦ φόνου Mm Ma3 ἐπιχείρησις ἀπὸ προσώπου τοῦ ποιοῦντος HB rubr καὶ τοῦτο μέν ἐστι τὸ ἐπιχείρημα ἀπὸ τοῦ προσώπου τοῦ πατρός, ἐν ᾧ ἔδειξεν ὅτι οὐκ ἂν ἠβουλήθη ὁ υἱὸς τὸν τοιοῦτον πατέρα ἀπο- κτεῖναι. εἶτα ἕτερον ἐπιχείρημα ἀπὸ τοῦ προσώπου τοῦ υἱοῦ in textu ante Πατρός Doxap 11 ἐργασία ἀπὸ παραβολῆς M m Ma3 B rubr 15 εὐδαιμονίαν ἐνταῦθα λέγει τὸν πρὸ τῆς πηρώ- σεως χρόνον Ma3 2 ἀνθρώπου — ἄνθρωπος om Doxap | δὲ om Β | ἄνθρωπος ὅλως Va | ὅλως om Μ 3 ὄντα Vi sed δέοντα in marg m2 | τὸν Ma sed ὁ in ras m3 ova. BVa | εἰδέναι ante βεβιωκότα Vi 5 πεπεισμένον Vi 6 μὲν] δὲ MaCl 7 τί HM 8 ξένους Ath sed γρ νόθους in marg 10 περιβάλλοι AthBVaM περι- βάλλει ViMa 11 οὕτως ante ἀνήμερος Vi | αἰδεῖται — 13 ἐπι- δείκνυσιν praemissis verbis ἀγριαίνει εἰς παθητικὴν σημασίαν. Λιβάνιος citat Andr. Lopad s. v. p, 22,15 ed. Nauck cf. p. 668,12 12 ἅπας Η ἅπαν V 13 πολύ τι om Lopad | τι om Η VVi | ἡμερώτερον HVVi Lopad 14 γὰρ Ma | „mallem εἴδετο“ Mor Not 15 μὲν om HV 16 τε V
marginal RIV 752
footnote 5 cf. ad t. VI 214, 5 sq.; 270, 16 10 cf. t. III 394, 8 11 cf. t. II 139, 12 sq. 2 ἐνθύμημα M m 9 ἐργασία ἀπὸ τοῦ ἐλάττονος M m Ma3 13 περίεστι] περιουσία ἔστι μοι suprascr Ma3 14 ἐνθύ- μημα ἀπὸ προσώπου ἐργασίας ἐλάττονος B rubr 16 ἀπὸ τοῦ ἐναντίου M m Ma3 2 δὲ inser Ma3 | περὶ in marg Vi2 4 ἡμερώτερον Vi | ἀγριωτέρων et πρᾳότεροι Vi sed ατ supra ερ m2 6 παραλίπω Ath sed ει suprascr, MaClB 7 γὰρ om Vi | ὑμῶν in marg Va2 ἡμῶν Mor | δὲ om Vi | δήμου Vi sed δή που in marg m2 8 γεγό-νατε πάντες BVa 9 γεγενημένοις Η 10 υἱὸν Mor τισιν libri edd 11 τῶν om ViAth | ἢ ante μόνος BVaM edd delevi 12 πάντων ante μιαιφονώτατος Ath | ἂν inserui e Β sed in ras om reliqui libri edd 14 καταλίπω Ath 16 ἄλλους HV | φιλανθρωπότατος HV 17 οἰκειοτάτους HV ViCl
footnote 6 II. ζ 429 10 cf. p. 693,5; t. V 540,16; VI 576,16; 597,12; 600,1 et 3 1 ἐργασία ὁμοίως (om Ma3) ἀπὸ τοῦ ἐλάττονος B rubr Ma3 11 ἐργασία ἀπὸ παραβολῆς M m Ma3 B rubr 14 ἀπὸ τοῦ ἐναντίου ἐργασία M m Ma3 1 οὗτος ante τοῖς Μ edd delevi | μὲν om HV 2 ἤδη ViVa sed in hoc οἶμαι in marg m2 3 ἐμαυτοῦ om Vi | διεχρησάμην Ma sed γρ διεχηρησάμην in marg m2 διεχειρισά- μην BVaM Mor | καὶ ante γνησίως Μ edd delevi 5 ἂν om BVa | σοι Re 6 καὶ inserui ex HVViMaClBVa om AthM edd | καὶ ante μήτηρ ViMaClBVa | καὶ inserui ex HVViMaCl BVa om AthM edd 7 comma post δοῦλος MaCl edd delevi | τὰς om Re 8 ὑμᾶς VM sed in hoc υ in η corr y 9 γοῦν inser Va2 οὖν Vi 10 θεραπεύοντος scripsi ex HAthCl θεράποντος VViMaBVaM edd | οὖν Vi | ἤμην] ἦν μοι Β | τὸν τρόπον HV 11 εὐνοιίαις Re | πραότατος ViMa 12 ἀγριαίνωνται Vi sed νῶσιν suprascr m2 14 τοσαύτης ἐπιμελείας τυγχάνειν παρὰ τοῦ πατρὸς BVa | περὶ πατρὸς Ath 15 τυγχάνων Μ sed εἰν supra ων m
marginal RIV 753
footnote 1 Plat. rep. VI p. 509 B. Anth. Pal. I 102, 1 cum nota Ia-cobsii 4 ἐπιχείρημα ἀπὸ τοῦ (om Ma3 Brubr) πράγματος M m Ma3 B rubr 14 ἐνθύμημα ἀπὸ πράγματος B rubr 2 ἠβουλόμην Ma | διπλασιάσαι Ma 3 ἔφθην Mor 5 τὰ om Vi 6 δεόμενος Ma 7 ὧς Vi sed καὶ in marg m2 8 εὐχόμην Vi | καὶ — 9 ἀνεδεχόμην in marg Vi3 11 ἂν om BVa 14 θρασυνόμενος ViAthCl sed in hoc ο(1) in α corr m2, BVaM Mor | γε inser B rubr om Va 16 τῶν ἀδι- κημάτων καὶ φαῦλα HV | καὶ ante πρὸ MaCl 16 καὶ δεινο- τατῶν ἅπαντες scripsi ex HVMaClAthBVa καὶ δεινοτάτων ἀδικημάτων ἅπαντες Vi ἄπαντες καὶ δεινοτάτων Μ edd 17 ἀντείποι ViMaBVa | τίς HViMaB | ὑβρίσει reposui e libris ὑβρίσῃ edd 18 κἂν — προιών praemissis verbis τυπτήσω ἀττικῶς. Ἀριστοφάνης — καὶ Λιβάνιος citat Andr. Lopad. lex. Vindob. s. v. p. 176, 14 ed. Nauck
footnote 1 Thuc. Ι 1, 1 cum nota Kruegeri 1 ἐργασία ἀπὸ τοῦ ἴσου B rubr 6 ἐνθύμημα M m Ma 1 καινότατος scripsi ex HVViMaCl καινότατα AthBVaM edd 2 γεγενημένος Vi sed ων supra ος m2 | καὶ ante κακό- νους (κακόννους α Β) BVa 4 προαιρέσεως scripsi ex MaClAthB αἱρέσεως VaM edd | ἀνελεῖν ὃν διέσωζον in marg Ma3 5 γεγενῆσθαι Vi sed γενέσθαι in marg m2 | ἐμαυτὸν Ma sed ὸν ex οῦ corr m3 6 δέδωκα scripsi ex HVViMa sed in hoc ἐκ antepos, ClAthBVa ἐκδέδωκα Μ edd | ἂν om V 7 εὐνοίας Ma sed γρ καὶ διανοίας in marg m3 ἐννοίας Vi 9 τὸν αὐτὸν inser Va2 | καὶ om HV 12 δυσμενέστερον παντάπασι πολεμίων HV 13 γένοιτο HV | τῆ μῆ Ath τῆ ᾿μῆ Β τῆ δὲ HV τῆ ἐμῆ δὲ Ma sed γρ τῶ μὴ δὲ in marg m3, Cl sed δὲ eras τῆ᾿ μῆ δὲ Va sed τῆ in ras m2 τῶ μὴ δὲ Μ μιᾶ Vi | ταμιεύεσθαι Β Va 14 νῦν δ’ αὐτόχειρα τοῦ πρὸς αὐτὸν φόνου γενομένου; ante πάνυ Vi 15 οὐδὲ] καὶ Vi | αὐ- τῶν Vi sed ῆς supra cov m2 | τούτων om Mor
marginal RIV 754
footnote 1 ἡ βούλησις M rubr Ma3 9 ἐπιχείρημα ἀπὸ αἰτίας B rubr 16 τὰ εἰκότα τῶν ἀέ ἀρχῆς ἄχρι τέλους ἄχρι τέλους om M rubr) M rubr Ma3 18 ἡ λύσις κατὰ ἔνστασιν M m Ma3 1 βουλόμενος Va sed λο in ras 4 litt m2 | οὕτως ἂν Μ Mor 2 ὑπὲρ Β | ὑπὲρ γονέων post ἐριννύων HV | καὶ om HV ViMaClAth 3 αὐτῶ Vi | κατασκευάσαι HVCl κατ’ καταστῆσαι Ma sed γρ κατασκευάσασθαι suprascr m3 | καὶ om ViClAth 4 τὴν inserui e ViClAthBVa om HVMaM edd 5 καὶ (2) inser Va 2 | αὐτὸν ViB 6 οὐδὲ Ma 7 τὰ om Η 12 ταύτην Bcripsi ex HVViMaClAthVa ταύτῃ ΒΜ edd | ἡμῖν iuserui ex HVViMaClAthBVa om Μ edd | ἐπιβουλεύουσαν scripsi ex H VViMaCl ἐπιβουλεύσασαν Ath ἐπεβούλευσα BVaM edd | οὐδὲ πώποτε Η οὐδὲ πώποτε VMa sed in hoc πο inser m3, ClBVa edd | δικαίως ἀμύνασθαι] „interponi velim ἂν“ Re | ἀμύνεσθαι ὢ 15 ἂν inserui e BVaM om HVViMaClAth edd 18 μοι om HV | θεοῦ Μ
marginal RIV 755
footnote 3 cf. ad t. III 256, 11; IV 126, 15; 262, 20; V 64, 15 3 ἐπιχείρημα ἀπὸ πράγματος B rubr 1 ἐμοῦ Ath sed γρ ἐμῶν in marg | συμβουλευσάμενος Ma sed συμ antepos m3 2 βεβούλητο MaAthVaM Mor | καὶ om HVViMa sed in hoc inser m3, ClAth 3 μεριστὴς HVViMa sed in hoc γρ μερίτης in marg m 3, Cl | signum interrogationis posui ex HAth punctum reliqui libri edd 6 τὴν τῶν in- serui e libris om edd 7 εἰ τὸν βίον αὐτὴ καταλίποι post συμφέρειν edd delevi | αὐτοῦ Vi ἑαυτῆς Ath | ἡμῖν om BVa 9 ἐπιβουλεύουσαν ἡμῖν MaCl | ἡμῖν om Β | καὶ post δὲ Ma 10 καθ’ ἡμῶν ῥᾳδίως] ῥᾳδίως ἡμῖν Vi 12 καὶ om Οἶ’ inser Ma3 | τῶ ante μόνῃ Ma et in ras Cl2 | ἀπολιπεῖν Vi sed κάτα supra ἄπο m2 13 δὲ BVa | ἔξει Vi | καλῶς ἑκάτερον Η VVi | ἑκάτερα πεπαύσεσθαι HVVi 14 τὴν ante ἐπιβουλεύουσαν Vi 16 ἥδει 15 εἷναι Ath | ἐξῆν Ma | αὐτὰ Vi | μεταταῦτα V MaClBVaM edd 16 τὰ inser Va2
footnote 14 Arist. eth. Nic. I 4 p. 1096 a 16. [Quintil.] decl. II § 15 p. 33, 33—14 ed. Lehn. 8 λύσις (om (M m Ma3) κατὰ ἀντιπαράστασιν M m Ma3 Mor ἐργασία ἀπὸ τοῦ ἐναντίου B rubr 12 ἐνθύμημα ἀπὸ πράγμα- τος B rubr 1 τότε om HV 3 διαταῦτα ViMaB 7 ἐκτίνειν Μ 8 signum interrogationis posui punctum (colon Ath) libri edd I καὶ om M 9 ὄντος Vi | τοῦ κλήρου καταστῆσαι ViBVa | βουλόμενος scripsi ex HVViMaClAth cum lacobsio Lect βου- λευόμενος ΒΜ edd βουλευσάμενος Va 10 μοι om HV 11 διὰ Va sed ὰ in αὐτὸ corr m2 | προιόντος Vi sed περιόντος in marg m2 12 καὶ om MaVa 13 λῦσαι Ma sed γρ κω- λύσαι suprascr m3 λύσαι HAth κωλύσαι BVaM Mor 14 προτιμότερον Ath a 17 παντελὴς Vi sed πάντα in marg 19 ἔτι om Vi | ὑπολειπομένης Vi sed ἔπι in marg m2
marginal RIV 756
footnote 5 ἐργασία ἀπὸ ἐκ M m Ma3) τοῦ ἐναντίου HB rubr M m Ma3 1 εἴπερ ἢν HV | ἴνα VaM edd 3 βεβαίαν Ma sed αν in ras m3 | γρ ἐργασία in marg Mor quod fuit scholion ad 1. 5 „vide num vocabula τῶν ὑπαρχόντων e scholio sint, quae idem dicant atque τῆς περιουσίας“ Re at cf. p. 677, 13 | κρί-σιν BVa et γρ in marg Ma3 4 καὶ — 5 ἀνεδεξάμην om Vi | ἐνεδεξάμην Ma 6 ἢν om Μ | κομίσασθαι Ma sed ο in ras m3 7 δὲ om Vi | πρόχειρον scripsi ex HV sed in hoc δῆλον supra χεῖρον m2, Μ πρόδηλον ViMa sed in hoc γρ πρόχειρον suprascr m3, ClAthBVa edd 10 τὴν omVi | προ- ετίμησα Vi sed προσετίμησα in marg m2 11 καὶ τεθνάναι προθύμως BVaM Mor 13 ἡμῖν Vi | δὲ τίς Vi 15 τοῦ inser Vi2 | ἀφαίρεσιν Vi sed ἀναίρεσιν in marg m2 16 πολλὰ τίς | εἴποι Va sed οι ras m2 εἴπη HV εἰπεῖν MaCl | αὑτὸν Vi | ἔχοι post ἑαυτὸν MaCl, ἔχει Vi sed οι supra ει m2 17 δέ μοι HVMaClAth
footnote 10 cf. p. 692,4; 340,19. Dem. cor. p. 300,24 13 ἐπιχείρημα ἀπὸ τῆς αἰτίας M m Ma3 1 πρὸς Vi sed εἰς in marg m2 | ἐξήμαρτεν Cl sed ὲν corr m2 2 τῶν — κατέστησεν om HV | πεποίηκεν BVa sed in hoc κατέστησεν in marg m2 3 γεννήσεως HV | τὰ μείζω — 6 τιμιώτερα praemissis verbis ἐκ τῶν μελετῶν laudat auctor excerpt. Neapol. II C 32 fol. 284 v 9 ἑαυτὸν Ma sed ἑ in ἐμ corr m3, ClAth 10 δυσμενὴς HV δυσμενὴς ὢν Vi | μὴ Vi sed μὴν in marg m2 11 ἕνεκα Ma 12 τί Vi sed τίνα in marg m2 14 δήπουθεν ἐμαυτὸν ἀδικεῖν scripsi ex HVVi sed in hoc ἀδικεῖν ante ἐμαυτὸν, Ma sed in hoc δεινότερον post δήπουθεν inser m3, ClAth δήπου δεινότερον ἀδικεῖν ἐμαυ- τὸν BVa sed in hoc τερον ἀδικεῖν in ras minore m2, Μ edd 15 χαλεπώτερον Vi sed α supra ον m2 | ἂν ante τις Μ edd delevi | τίς HViMaAth 16 τιμωρίας Vi | λαμβάνει scripsi ex HVViMa sed in hoc γρ ἐπάγει in marg m3, ClBVa ἐπάγει Ath sed γρ λαμβάνει in marg λαμβάνῃ Μ edd | διατούτων Ma ἑαυτ(??)ν Ath ἑαυτὸν Vi sed ἑαυτῶ in marg | βλάβην in marg Vi2
marginal RIV 757
footnote 4 cf. t. V 540, 9; VI 597, 4 17 cf. p. 678, 17; 681, 3; 687, 16; 690,4; 691,5. Poll. III 27 1 ἐνθύμημα ἀπὸ προσώπου B rubr 7 εἰσβολὴ τῆς (om Ma3) δυνάμεως M m Ma3 ἡ δύναμις ᾖ (ἦ α cod.) ὡς φεύγων κέχρηται λέγων Β 11 ἡ δύναμις M rubr Ma3 ἡ βούλησις ῃ ἠ cod.) ὡς κατήγορος κέχρηται ὁ πηρός Β 15 ἐπιχείρημα ἀπὸ τοῦ (om Ma3) προσώπου τῆς μητρυιᾶς καὶ τῆς αἰτίας Mm Ma3 2 καὶ om V | τίς HViMaAth 3 παρὰ inserui ex HVVi MaClAthBVa om Μ edd 4 τολμήσει ViCl | τίς HVi 6 ἂν om ViBVaM Mor 7 ἐκεῖνο Vi 8 τῶν Va sed ῶν in ras m2 | τοῦ om BVaM Mor 10 λάθοιεν τί Ma 11 οὖν ἂν MaCl I ἂν om HV | οὖν om Vi 13 δὲ V edd 14 πάν- τοσε HV πάντα Vi „fortasse voluit πανταχῆ“ Re 15 οὕτως Ath | ταῦτα AthBVa | ὅθεν Vi sed πόθεν in marg m2 16 γυναικὸς Ma sed ὸς in ras m3 | ταῦτα Η 17 προγόνων Ath προγόνοις ViVaM Mor | μὲν om Va | προειρημένης H
marginal RIV 758
footnote 6 ἀποστροφή ΗΒ 11 ἡ ἑτέρα βούλησις M rubr Ma3 12 ἐπιχείρημα ἀπὸ τῆς αἰτίας M m Ma3 1 καὶ om Μ 2 ἐώρας Ma sed ἃς in ras m3 ἑώρακας AthCl 3 ἡμᾶς Va sed ῶν supra ᾶς m2 5 καὶ ἀποστροφῇ ante κατειλημμένον ΒΜ edd, ἀποστροφῇ Va delevi ut e scholio sequenti ortum 6 ταὐτά σε Η 8 χρημάτων Vi sed χρηστῶν in marg m2 9 ἐν ἡμῖν in ras Va2 | ἡμῖν om Μ | ἐπεβούλευεν ἡμῖν Vi | ἐπεβούλευσε HV | νῦν δὲ] καὶ νῦν Vi 10 ἀθρόον Ath | ἐπήνεγκεν Ma 11 Καίτοι] καὶ Vi 12 γεγενημένη Η V 13 „post βεβαιοτέραν videtur deesse ποιεῖσθαι tibi facere scil. βουλομένη“ Re | καὶ om HVMaClAthBVa | ἀσφαλεστέραν Vi | „malim ἔχειν“ Re 14 μὴ δὲ μίαν Η μὴ μίαν Μ 17 περὶ Vi | συνεβούλευσεν HV 20 τούτου Vi | χρωμένης Vi
footnote 16 ἡ δύναμις Β 19 ἡ ἑτέρα δύναμις ἤτοι ἡ τῆς μητρυιᾶς M rubr Ma3 1 „aut ὑπενόεις delendum est, ut schol. vocabuli ὑπώπτευες, aut 60 servato sic est leg. ὑπώπτευες. ttim nova init sententia: ὑπενόεις, μᾶλλον δὲ σαφῶς ἐγίνωσκες“ Re 2 τοῦ om HV | et 3 διατοῦτο HViMaAthB 3 τοῦ ἐμοῦ MaCl 4 εἷναι Η V | περὶ — 5 προαίρεσιν in ras Va2 et in marg Va3 6 παρ- αιρουμένη Va sed αρ in ras m2 προίαιρουμένη Ma προ- αιρουμένη Οἶ’ προορωμένη Vi γρ περιαιρουμένη in marg Mor 8 ἐκέκτητο Ath sed σο in marg 9 αὐτοῦ ΒVaM edd 11 καλὸν om AthBVaM πρέπον MaCl et γρ in marg Mor 12 εἷναι καὶ πρέπον post λογισάμενος Μ 13 κτημάτων Vi 16 ἐσπούδαζεν V 18 καταστήσασθαι Vi sed σασα supra σασθαι m2 19 τοῦ πατρὸς τὴν ἀναίρεσιν ἔσεσθαι Vi sed τὴν ἀναίρεσιν ἔσεσθαι in marg m2, MaCl
marginal RIV 759
footnote 16 Dem. Boeot. dot. p. 1012, 17 1 ἐπιχείρημα ἀπὸ τοῦ προσώπου M m Ma3 ἐπιχείρημα ἀπὸ προσώπου οἰκείου τῆς μητρυιᾶς Β 7 ἀπὸ τοῦ καιροῦ M m Ma3 1 προχειρότατον HV 2 μὲν περὶ] περὶ Vi sed δὲ πρὸς 4 φυλάξαντος Cl sed α(2) in ο corr, AthM | ἢ — 5 δυνάμενος om Β 5 δὲ HV | διαχρωμένη Vi 6 ἐπι-βουλεύσασαν Vi | φωράσει Ma sed γρ καὶ φράσει in marg m3 φράσει Vi 7 οὐ scripsi e ViB ὁ reliqui libri sed οὐ supra ὁ Va, edd 8 γενέσθαι δυνήσομαι scripsi ex HWiMaClAth γενήσομαι BVaM edd 10 μὲν om Ma | γὰρ om Β | ἐγκα- λέσει scripsi ex HVViMaClAthVa καλέσει Β ἂν καλέσῃ Μ ἂν καλέσει edd sed γρ ἐγκαλέσῃ in marg Mor 11 τίς δὲ ἐλ- κύσει inserui ex HV om reliqui libri edd | τὸ ante δικαστήριον Vi 12 ᾖ Vi sed ἦν in marg m2 14 μηδὲν ἀκριβῶς scripsi ex HVViMaClAth ἀκριβῶς οὐδὲν VaM edd οὐδὲν Β 18 πατρῷον HVi
footnote 14 [Quintil.] decl. II § 5 p. 24, 12 8 τὰ εἰκότα τῶν ἀπ’ ἀρχῆς ἀπαρχῆς Ma3) ἄχρι τέλους M rubr Ma3 τὰ ἀπ᾿ ἀρχῆς ἄχρι τέλους ἐξ ἀντιθέσεως Β 9 ἡ λύσις τῶν ἀπ’ ἀρχῆς ἄχρι τέλους ἐξ ἀντιθέσεως διὰ μεταθέσεως τῆς αἰτίας Β 1 χρήσασθαι scripsi e MaClAth διαχρήσασθαι HV sed in hoc δία eras χρῆσθαι ViBVaM edd | τοῖς ante τεκμηρίοις inser Ma2 2 ἐπιβουλεύσασα Vi 3 χρήσομαι (sed ομ in ras m3) κατὰ τοῦ (sed τ in ras m3) παιδός Ma 4 ἐπιδείξομαι Ma ἐπιδείξομαι Cl ὑποδείξομεν BVa ἀποδείξω Vi sed ὑποδείξομεν in marg m2 5 φεύξομαι Vi sed διαφευξόμεθα in marg m2 6 μὲν Vi sed οὖν in marg m2 | οὕτως HVViMaClAth 8 οὖν HV | κατ’ αὐτῆς ἄν τις Vi ἄν τις κατ’ αὐτῆς HVAth Re 9 προσφέρειν Ma sed σ eras 10 τὸ ante φάρμακον Μ 11 ὅτι — 12 πρόδηλον praemissis verbis σκευώρημα ἡ ἐπι- βουλή Λιβάνιος citat Andr. Lopad. lex. Vindob. s. v. σκευωρῶ p. 164. 15 ed. Nauck | δὲ HVVi Lopad | ἐκ om HV | σκαιώρημα Ma sed ευ supra αἰ m3, Cl cf. p. 663,7; 664,10; 681,2 et 9; 683, 13; 686, 6; 687, 9 et 14; 691, 15 et ad p. 325, 15 12 δῆ- λον Lopad | τούτω Vi 13 τὴν om Η inser V2 | ἐπενόησε Vi MaClAth 14 διατούτου Β
marginal RIV 760
footnote 13 cf. p. 682,13; 683,8; 684,12; 685,3; t. IV 441, 7 7 ἡ πιθανὴ ἀπολογία B rubr 11 διλήμματον Β 1 ἡμᾶς Β | ἐπιδειξάμενος HV „malim ἐκδεξάμενος intelli- gens, colligens“ a Re 2 σκευωρήματος Cl sed εὑ in αἰ corr σκευωρήματος Ma | τιμωρίαν BVa 3 τοιαῦτα scripsi ταῦτα libri edd 5 τὴν ante ἐπιβουλὴν Vi 6 ἐπιβουλεύματι Vi sed πλεονεκτήματι in marg m2 7 ἐκείνω Μ | τῷ ἱματίῳ MaCl | ἐγκατέδησε scripsi auctore Cobeto Coll 293 συγκατέδησs libri edd 8 οὐκ ἂν] ἂν οὐκ ἂν HV οὐ ViMa sed in hoc οὐκ ἂν suprascr m3 ἂν οὐ Cl | λάθοι reposui ex HVMaClAth BVa cum lacobsio Anth. Pal. III 110 λάθῃ ViM edd | τὰ ante κατ’ HV 9 σκαιωρούμενος MaCl sed in hoc αι ex ευ corr m3 | πράττειν Vi sed ων supra ειν m2 12 τοὺς om Η inser V2 13 τούτῳ scripsi auctore Re τοῦτο libri edd 14 ἐπι- βουλεύων Ma sed ἐπεβούλευον suprascr m3 Cl | τοῦτο Vi | δια- φθείρειν BVa 16 διλήμματον post πατέρα Ath sed in textu circumductum et in marg deletum cf. schol. Β ad l. 11 | γὰρ om Vi
footnote 11 Dem. cor. p. 300,21 15 cf. t. VI 596,2 11 διλήμματον Ath 1 συκοφαντοῦσθαι Re 2 καὶ inser Ma om Μ 3 ταύ- την Vi sed ταύτῃ in marg m2 4 ἂν ante ἠγανάκτησα HV MaCl Re post ViBVaM Mor delevi cum lacobsio Lect | τίς HMaBM | „locum hunc non intelligo. num ἴνα τις ἂν εἴποι καλὴν αἰτίαν; δῆλον γὰρ, ὅτι οὐχ ἕνεκα χρημάτων, οὐ προλαβὼν (id est ὅτι αὐτὰ οὐ προέλαβον) ἐπεβούλευον. verum ne hoc qui- dem satis “ Re | εἴπῃ Vi sed οι supra η m2 5 πάλιν H V | αἰτίαν om HV | ἣν scripsi ex Ath cum lacobsio Lect ὧν ViMaClBVaM edd ὦ HV 6 ηὐτρεπίσθη Vi | δηλητήριον ΗVMaCl | ὡς Mor 8 μὲν om HVMaClAth 9 τὸν πατέρα BVa | τοῦτον Vi | ἀπῃτούμην Ath 12 ὑμῶν Β sed ὑ in ras ἡμῶν ViVa | πότε V 15 πρῶτον — 683, 1 καταμηνύειν prae- missis verbis ἄντικρυς ἀντὶ τοῦ σχεδόν. Λιβάνιος citat Andr. Lopad. lex. Vindob. s. v. p. 22, 18 ed. Nauck 16 τί λάθρα HV | λάθρα om Lopad | τί libri Lopad edd
marginal RIV 761
footnote 1 τούτω Vi | δεδιὼς scripsi ex HVViMaClAthBVa edd δεδιότα Μ edd cf. ad p. 406, 21 ; t. I 480, 15 sq. 3 μὲν om Vi 4 μητρῴας Μ Mor Ι οὐδέποτε JBV οὐδὲ πώποτε reliqui libri edd | οὕτως Vi sed τοῦτο in marg m2 5 ἤλεγξε Ma sed διή supra ἤ m3 ὢ Ι τὸ om HV τοῦτο Β Ι ἅπασιν inserui ex HVVi πᾶσιν MaCl om AihBVaM edd 6 εἷναι Vi sed γεγενῆσθαι in marg m2 7 λανθάνειν scripsi ex HMaClAth Va λανθάνεις Vi sed εἰν supra εἰς m2 λανθάνον VBM edd I λέγει scripsi ex ΗVΜαΟἰ λέγοι ΑtὸΒΜ edd λέγειν Vi sed εἰν del et εἰ suprascr m2 λέγω Va 8 λανθάνειν Vi sed ὂν Bupra εἰν m2 9 περιεργάζεσθαι Μ | τὰ scripsi ex HVViMa ωΑΙh τὸ BVaM edd 10 οὖν post μὲν Μ edd delevi Ι ἡγοῦμαι Ma 11 δήπουθεν ΜαΟἰ τὸ Vi sed δήπου in marg m2 12 λανθάνον μὲν V sed e λανθάνομεν corr m- λανθα- νομένη Η I ἐζήτησε Ma edd Ι σαφὲς Πω sed in hoc ἐς in cbg corr m2, Αtὸ | ἐγίγνωσκε ΒΜ edd 13 σκευωρήσασα in marg Vi2 σκαιωρήσασα ΜαΟἰ sed in hoc αἰ ex εὑ corr m2 14 ὅ τι περ scripsi es. HV cum lacobsio Ach. Τ 908 App. Pors. 327 Lect εἴπερ reliqui libri edd 15 ὂν post δεδεμένον HV | οὔτε V Re Ι ἐγίγνωσκεν Β edd 16 „malim ἐνδήσασP Re at cf. p. 647,5; 680,10
marginal RIV 762
footnote 3 [Quintil.] decl. II § 5 p. 24, 23 sq. 13 ἐργασία ἀπὸ παραβολῆς Β 1 οὖν Vi Ι ἐνέδραν HVViMa sed in hoc in ἐνέδραν corr m3, ClVaM edd 2 συνιεὶς ViBVa I εἴρετο Vi 3 καὶ om Va | τοῦ] τὴν Μ 4 ταύτην Ma | ἐνόμιζεν ἐπιβουλεύουσαν BVaM Mor 6 ἑαυτὸν Vi sed ἑαυτοῦ in marg m2 | τὴν et προαίρεσιν Vi 7 κωλύειν V sed ειν, in ras m2 κωλύσειν Η | διὰ — 8 ἤνεγκε praemissis verbis καιριωτάτη πληγὴ ἡ νατηφόρος. Λιβάνιος citat Andr. Lopad. lex. Vindob. s. v. p. 107, 4 ed. Nauck | διὰ τούτου HV διατοῦτο Lopad 8 πληγὴν in marg Vi 2 | καιριωτάτην Lopad | „malim ἐπήνεγκε“ Re δὲ MaCl 9 φαρμάκοις Va sed ΄ et in ras οις m2 | ἂν marg Vi2 10 δὲ Vi edd 12 ἐντεῦθεν Ma sed αῦθα supra εὐθεν m3, Cl 13 σημεῖον εἷναι τὸ φάρμακον Μ 14 μὲν eras Ma inser Va 2 15 ἔχοι λέγειν scripsi ex Ath coll p. 565, 14 ἔχειν λέγοι HV et Iacobs Lect λέγειν ἔχει Ma sed ει in η corr m 3, Cl ἔχει ViVa sed in hoc οι supra ει ἔχη Β ἔχοι Μ edd sed „videtur dare voluisse μηδὲν ἔχη vel ἔχοι λέγειΝ Re | δὲ om Vi inser Va2
footnote 2 Isocr. or. XVIII § 243 p. 308, 5 5 Dem. cor. § 110 p. 263, 12 8 [Quintil.] decl. II § 5 p. 24, 12 12 [Quintil.] l. ’ξ 22 p. 38, 26 12 ἡ μετάθεσις τῆς αἰτίας M rubr Ma 3 ἑτέρα μετάθεσις αἰ- τίας Β 1 λέγει ViMaCl Ι τίς HViAth | ἂν Ath Ι signum interro- gationis post ἐκεῖνον posui, comma Ath edd colon reliqui libri comma post ἐμβρόντητε posui colon Mor signum interro- gationis Re om libri 4 δὲ τίς Η | φθείρει HV 6 τε om Η VVi 12 καὶ νῦν om B Ι ἡμῖν om Vi | ἐπιτείνεται Ma sed γρ ἐπανατείνεται suprascr m 3 ἐπανατείνει τε? Iacobs Lect 13 καὶ in ras Μα3 | νῦν post καὶ BVaM Mor et inser Ma 3 del Re I οὐ ante τοσοῦτον Η 14 ξίφος (2) delendum censet Re | ἀλλ’ ante ἐφ’ HV et inserendum censet Re 15 „malim ἐλ- πίσιν, ἴν’ — 16 χρήσωμαι“ Re Ι κἂν MaCl 16 τῶν om Ma ClBVaM I προὔθηκα Vi 17 ἡ τύχη] εἰ τύχοι Vi | κἂν HVi MaAth Va Ι ἂν om Ma del Cl 18 προελόμενος scripsi ex HViMaClAthBVa ἑλόμενος cum ras 3 litt ante ε V ὑφελό-μενος Μ edd Ι διαχρήσαιτο Vi
marginal RIV 763
footnote 7 cf. p. 660, 10 10 cf. ad p. 657, 4 5 φώριον] τὸ (om Mor) κλέμμα suprascr Ma 3 et in marg Mor 10 ἐφόδιον] ἀφορμὴν Ma 3 Mor 1 ὑφαιρουμένου scripsi ex HCl sed in hoc ου in οὑς corr m 3, AthBVa et γρ in marg Mor ὑφαιρομένου Μ ὑφαιρουμέ- νους Ma sed ου supra ους m 3 ὑφαιρούμενον V edd ἀφαιρού- μενον Vi 2 δήπουθεν Ma | δυναμένου Ma sed in corr m 3, Cl | δ’ ἂν Ma | τοῦ ἐμοῦ HV τοῦ μοῦ Ath 4 om Vi | τῶ ἐμῶ HV τῶ ’μῷ Vi τῶ μῶ ClAth | Vi | τοῦτον HV | διαχρησάμενος Ma sed γρ prascr m 3 γρ τοῦτο διαπραξάμενος in marg Mor 6 σκαιώ- ρημα Β 8 προσεδόκησεν edd 9 ἑλεῖν — 10 δαιμόνιον inser Ma 2 et in marg Cl 2 10 γὰρ τὸ scripsi e Vi coll. p. 572, 14 γάρ τοι τὸ Ma 2 γάρ τι reliqui libri sed ρ τι abscissum Cl 2, edd 11 ἑτέροις ἐπιβουλεύῃ Β | ἐπιβουλεύων Vi sed η λεύῃ in marg m 2 12 ὑπολαμβάνει AthVa sed in hoc η su- prascr m 2 13 ἐλέγχει VaAth | αὐτὸν Ma ἑαυτὸν Vi αὐτὸν reliqui libri edd 15 τ~?
footnote 19 τὸ σημεῖον δι’ οὖ ἐλέγχει τὴν μητρυιὰν τὸν φόνον ἐργα-σαμένην ἤτοι τὰ ἀπ’ ἀρχῆς ἄχρι τέλους ΗΒ 1 καὶ om Vi 2 προσεδόκησα in ras Ma 3 | οὔτ’ ἂν Ma sed γρ ὅταν suprascr m 3 3 διεχρησάμην Vi 4 συνέθηκεν Ma sed γρ προσέθηκεν suprascr m 3 5 τῆς μητρυιᾶς διελέγχει τὴν HV Re 7 καταλίπῃ HV 9 δέ Vi | σου Vi sed που in marg m2 | γέ σου HV 10 προσφέρειν ViCl sed in hoc σ del m 3, Va 11 τῆ ἐμὴ HV τῆ’ MaAthB τῆ μῆ ViCl | χρηστό- τητι Vi 12 ἂν HV 14 „malim ἔφης, et tum ἑαυτὴν erit idem atque σεαυτήν“ Re | αὐτὴν ViMaAth αὐτὴν Cl Ι ὄψομαι Vi | σκευωρουμένης Vi sed σκευωρουμένην suprascr m2 15 ἂν BVa | καὶ ante τίς σκευωρουμένην 16 τὸν φόνον καταμηνύσει BVaM Mor Ι τὸν φόνον ἐργασαμένης om Ma | ἐργασαμένης V sed γα inser m2, Cl sed ης ex η corr m2 17 ἀπαιτῶσι Vi 18 σοι Vi 19 μέν inserui ex HVViMa ClB sed in hoc inser rubr om AthVaM edd
marginal RIV 764
footnote 4 [Quintil.] decl. II § 8 p. 27, 1 14 cf. t. II 139, 6 1 δὲ om Η 2 τὸν om Vi 3 κατενόησα HV Ι ὃν HV Ma sed in hoc in ὦ corr m 2, ClAth Ι εὐτυχέστατον Vi sed δυσ- τυχέστατον in marg m 2 6 τὸν τρόπον ὁ φόνος ἐπράχθη Β Va 8 σέ inserui e Par ut coni Re om reliqui libri edd | τίς Μ | ἐλάνθανε MaCl 9 δὲ om VMaCl 11 τοῖς Vi Ι ἀνηρημένους HVM ἀνῃρημένοις Vi 12 „fort. αἵματός σε“ Re διήγειρεν om Vi 13 ἅπασαν τὴν κοίτην HV Re 14 σοῦ omVi ἅπασαν HV | τὸ σῶμα Vi | τατελευταῖα Ath 15 ὁ in- serui ex HVViMaClAth om BVaM edd 16 που om HClB inser Ma3 et in marg Vi2 18 τὴν εἴσοδον Vi sed τῶν εἰσ- όδων in marg m2
marginal RIV 765
footnote 1 Lyc. Leocr. § 21 p. 150,33. Arist. Plut. 435 4 cf. p. 695,6 15 cf. p. 657, 4; 694,2; t. IV 169, 13. Eur. El. 771. Dionys. Hal. ant. XI 27, 1 1 πεπονθὸς HV I διήγειρεν Ma | καὶ om Vi | ἐκ γειτόνων] ἐγγειτονῶν ViVa ἐν γειτόνων Par 3017 (Schaefer Greg. Cor. p. 47) at cf. 11. 11. 2 αἰσθόμενοι V sed ο(1) in ras 3 litt m 2 αἰσθανόμενοι H 3 αὕτη scripsi ex HViAth αὐτὴ VMaCl BVaM edd sed „αὐτὴ si bene habet, διενηνόχεις erit leg. cum B(avar.) aut si διενηνόχει servatur, leg αὕτη“ Re | καὶ ante μόνη HV 5 διενηνόχεις HVi sed in hoc χει supra χεῖς m2 6 πάλιν] „malim πάσης σοῦ“ Re at cf. p. 690, 6; 693,4 7 γινόμενον Η 9 ἑαυτὴν διὰ τούτου κατασκευάζουσα Η V Ι δὴ τούτω MaCl 10 γενομένοις Vi 11 μὲν ante γὰρ Η V | καὶ om Ath 13 κατάφορον VVi | εἰ — 14 τις in marg inser Cl2 14 καταλάβη VVi sed in hoc οἱ supra η m2, MaCl2 | τίς HMa | ἐπισταμένη Vi sed νην suprascr m2, Ma sed η ην corr m 3, Cl sed ν post η eras, Ath sed v supra η add 16 τῶν ἀνθρωπίνων Ma sed γρ τῶν ἀφορήτων suprascr m3
footnote 3 πιθανὴ ἀπολογία M rubr Ma 3 ἀντίθεσις B rubr 6 λύσις Β 9 ἐπιχείρημα ἀπὸ τῆς αἰτίας Β 3 φησί Οἶ’ sed ἡ ex ὁ corr m3 Ι τίς ViMaAth 4 οὕτως inser Va 2 5 ἐμαυτῆς Vi sed ἐμαυτοῦ in marg m 2 6 αὐτῆς in marg Vi 2 7 καὶ om Vi | ἀπιστήσαντες Va sed ἀπι in ras maiore m 2 ἐπιστήσαντες Μ Mor qui οὐκ anteponendum coni Not 8 μεμηχανευμένοις Vi μεμηχανωμένης Va sed ἡ supra ὢ et ης in οις corr m 2 9 αὐτῆς καὶ τοῦτον BVa αὐτῆς Vi λόγον αὐτοῖς Mor | τρόπον Ath 10 διεκώλυσε HV ἐκώλυε Va 12 κίνδυνος in ras Va2 13 ἀναιρέσεως Va sed αἰ in ras m2 | δὲ καὶ ante τῶν Vi sed διὰ in marg m2 14 ἐνεδίδου scripsi ex HVMaClAth ἐδίδου Vi sed ἐνεδίδου in marg m2, BVaM edd 15 ῥαδίως Οἶ’ sed in δεδιὼς corr m2 | καὶ inser Cl2 16 οὔτ’ ἂν] οὔτε Vi | τὸν φόνον — 691, 1 πικρότατος marg inser Cl2 | διέλαθε Va edd 17 οὔτ’ in ras Ma 4 | χείρησεν Ma sed γρ εἶχεν suprascr m3 εἶχεν Μ
marginal RIV 766
footnote 2 προτέρας HVB | καὶ — 3 πιστούμενος om HV 3 τῆς Va sed ῆς corr m 2 4 πρὸς ἔλεγχον om Vi Ι τούτου HV 5 μητρυιὰ HVViClAthVa Ι τὸ inser BMa 3 om HVViClAthVa | πολέμιος Vi sed πολέμιον in marg m 2 6 ἐδήλου HV | εἰς Vi sed εἰ καὶ in marg m 2 7 διαφεύξεσθαι Cl sed e δὴ φεύ- ξασθαι corr m 3 8 σαφῶς στερησαμένη BVa στερησομένου Ma | ἐγίγνωσκε Μ edd 9 παρ’ αὐτῆς ὁ πατὴρ Β | ἔλαβε αὐτῆς Vi 10 αὐτὸν Vi sed αὐτῆς in marg m 2 11 πρόφα-σιν δέδωκε Vi 12 ταῦτα Vi | σαθρὰν HV | δὲ Vi | Ath 13 ὅμως δὲ συναιρόμενον Vi | συνειρόμενα lacobs 220 | δ’ Ma | εὐφώρατον Ath ἀφώρατον Cl 14 δὲ Va μὲν et δὲ om Vi 15 δ’ ἂν HVViMa sed in hoc ἂν inser δὲ VaM edd | σκευωρήσασαν Vi | ἑπὶ ante τῆς ViBM Mor 16 ἑτέραν ViCl sed in hoc in ἕτερον corr m 3, AthBVa | μὲν om HV 17 ἀναιρεθέντος BVa | ὕστερον ἀναιρήσειν Va 18 προσεδόκησε Ma | μηδὲν Vi | ἔτι φυλάττοντος ὁμοίως Ma | φυλαττόμενον Vi
footnote 10 κοινὴ ποιότης M rubr ἢ καταστήσασα BVa 3 δέ μου HVMaClAth | συμβή- σεσθαι inser Va2 | δυεῖν Ath 5 προσανελεῖν Οἶ’ sed σ inser m3 | αὐτὸν ViMaClVa 7 διαταῦτα ViB | μὲν om Vi 8 ποιήσασθαι HV sed in hoc ὑπερέθετο suprascr m 2 | γέγονε τὸ scripsi γέγονεν ὃ ὁ HAthVaM ὅ V) libri edd | μιαιφονίας προοίμιον Ma sed ς προοίμ in ras m 4 et προοίμιον in marg m3 11 δυστυχῆ Vi sed δυστυχεῖ in marg m 2, MaCl | προσήκοντι Β 12 καταλῦσαι Vi καταλύσαι reliqui libri edd cf. ad t. V 330, 9 I „malim ἡδὺ“ Re Ι τὴν om Vi Mor 14 παραδέδωκε scripsi ex HVMa sed in hoc παρέδωκε suprascr m 3, Cl παρέ-δωκε ViAthBVaM edd | δρᾶμα ViMa sed in hoc e δράματι corr m 3 16 signa interrogationis post τυφλότης et συμφορά Vi | παντάπασι λυσιτελὴς Va sed ἁ ante λυ inser rubr 17 φέρει — 18 ἀνυπέρβλητος laudat excerpt. Neapol. II C 32 fol. 284 v γὰρ post φέρει Neapol. | τί libri Neapol. edd | καὶ Va 18 τίς libri Neapol. edd | ἀτύχημα Vi
marginal RIV 767
footnote 3 cf. p. 650, 16 5 cf. ad p. 668, 10 7 cf. p. 629, 9; 656,10; 697,10 1 φρικωδέστατον Vi sed ἔρον supra ατον m 2 2 οὕτως ante ἀνήμερον inserendum coni Mor | ἀνηρημένον Va 3 ἐπε- πηρώμην Vi πεπηρωμένος ἦν HV 5 δὲ om Vi 6 ἡμῖν, ὦ Ἥλιε, δραματουργίαν scripsi ex HVMaClAth co ἥλιε δραμα- τουργίαν ἡμῖν ViBVaM edd 7 ἀπήγγειλας MaCl | ποίαν μιαιφονίαν Ma 9 ἀφ’ Β sed α in ε corr, Va | τούτοις ViB τούτω MaCl 10 ἀπανθρώπῳ scripsi ex HVViClAth cum Iacobsio Ach Τ 736 ἀπανθρώπου Ma ἀνθρώπου BVaM edd 11 περιρραινόμενος Vi 12 παντὸς θηρίου scripsi ex H VViMaClAth θηρίου παντὸς BVaM edd | μιαρωτέρους Vi ρα supra ῥοῦς m 2 13 εἰργασμένη Iacobs Lect 14 ἐκεῖνο Va sed ~ νο in ras m 2 16 τοῦτο Vi | τετόλμηκε Vi 17 πάν- τα Vi I καὶ διηγούμενος] διηγουμένων ut p. 698,10? 18 μὲν om Vi I διετίθην Ma | καὶ om Vi
footnote 2 cf. p. 698, 6 1 Ἐριννύες θεαὶ τρεῖς παρ’ Ἕλλησιν ἔφοροι φόνου καὶ τι-μωρούμεναι τοὺς φονεῖς. καλοῦνται δὲ Ἀληκτώ, Μέγαιρα καὶ Τισιφόνη Ma 3 cf. Harpocr. s. v. Εὐμενίδες. [Apollod.] bibl. 1 1, 4 1 ἐμοῦ Vi I νομίζω ante τὴν Vi2 οὔτε(1)] οὕτω Vi 3 ταῦτα HV τἀς ViMa 5 τῶν inserui ex HVMaClAthVa om ViBM edd | δὲ τοῖς τοιούτοις HV et lacobs App Pors Adv 283 Lect | δὲ inser Μί’ 6 τὸν — 7 διαχρησαμένης praemissis verbis πίστις ἡ στοργή citat Andr. Lopad. lex. Vindob. s. v. πίστις 141, 14 ed. Nauck | παρ’ αὐτὸν τὸν scripsi ex HVViMa Cl Lopad cum Iacobsio Lect παρὰ τὸν Ath περὶ τὸν BVaM edd sed διαχρησαμένης ἄνδρα περὶ τὸν τῆς in marg Mor 7 καὶ κοινωνίας om Vi Lopad | καιρὸν καὶ κοινωνίας 8 signum interrogationis edd 9 οὕτως HV ὄντας Mor sed ὄντως corr Not 10 ὑπέστης Vi | γάρ με HV Re | ἠγάπησας Μ Mor 13 δυστυχεστέραν HV 14 οὕτως HVMa sed in hoc ς eras, Cl 15 ὑπόκρισιν Ma sed χειρῖσιν supra κρίσιν m3 | εὐνῆς Vi sed ὀργῆς in marg m2 16 ἔκδηλος Vi HV | ἧς Ma sed ν supra ς m 3 cf. p. 640 not. 2 | τὸ Vi
marginal RIV 768
footnote 2 πατὴρ Vi | ὑποκρίνεσθαι MaCl 3 πανουργοτάτη 4 καὶ ante δι’ Ath | οὖν om MaCl γοῦν AthM Mor 5 ἔργον om BVa 7 προσέσται Ma sed πρόσεστι suprascr m3, ὢ 8 οἰκείων Vi sed ἐκείνων in marg m2 9 τἀμὰ MaAth 10 δαπανωμένην πυρὶ Vi 12 κἀκείνους (sed ὢν supra ὄης m3) προσαφῃρέθην παραχρῆμα θεασάμενος Vi 14 λοιπὸς BVaM Mor 15 τούτου Mor 16 μεγέθους scripsi μέγεθος libri edd ,,malim ὦ μέγεθος“ Re 17 εἴποι scripsi ex HV ViMaClAthBVa εἴπῃ Μ edd | τίς HMaAth | πονηρὸν ὀνομά- ζουσιν ἄπαντες HV 18 πονηρὸν HV | δ’ εἰ BVa | λέγει Cl λέγ(??) Va λέγοις HV | τίς Ath om HV | δηλώσεις HV 21 πεποίηται? | τἀτύχημα τῷ ἀτυχήσαντι πεποίηνται coni Re
marginal RIV 769
footnote 3 cf. p. 541, 8 4 μεμελέτηκε γὰρ ὑποκρίνεσθαι om Β 5 ὕπνον Va sed ὂν in ras m 2 | προτείνουσα post ὕπνον Β | ποτὲ(2) — 6 κλῆρον in marg Va 2 6 ἤδη πάλιν Μ | προτείνουσα om Β 8 δὲ post νῦν HV 9 καιρὸς — δακρύων om HV 11 θεοῖς Vi sed δαίμοσι in marg m 2 12 ἐργασαμένη HV 13 καὶ ante μή- τε(1) Vi | βίου scripsi cum lacobsio Lect βίον ἢ VaM edd om HV „recte quidem omittit B(avaricus) videtur tamen in his epithetum aliquid cuius accusativus in ῆ exit, la- tere, quod nunc non exputo“ Re | τὴν ante συνήθειαν dum coni lacobs 15 τῶν ante τοιούτων BVa | HV 16 τε Mor | ἡμῖν HVViMaCl 18 δὲ om 19 λοιπὸν MaCl 20 ἐπελθὼν BVa
marginal RIV 770
footnote 2 Thuc. II 77, 3 10 cf. ad p. 406, 9; IV 144, 4; VI 273, 3 1 νῦν Μ edd 2 λειπόμενον Ma sed εἰ in ras m 4 4 καὶ om HV 5 πατρῴα HViAth 6 ὑποδέχεται Vi 8 ὁ κλῆρος] ὁλόκληρος HV | ἡ om Mor 9 παντελὴς Vi sed πάντα in marg m 2 11 καταλιπών Va sed ´ν in ras m 2 et ´ supra ι eras | διὰ ταῦτα (1 et 2) ViMaAthB | τεθνάναι καλὸν in marg Ath 12 καταλύσαι HAth cf p. 692, 12 | τὸν βίον Ma sed τὸν βι in ras m 4 13 τιμωρήσαντι HV τιμωρήσασθαι Vi | γὰρ om Vi 14 εὐτυχέστερον Ma sed ατ supra ερ 15 δοίη Vi sed δέη in marg m 2 16 ἕνακα Ma | σωτηρίας μαχόμενος BVaM Mor 19 δὲ Η 20 με om Vi 21 τοὺς om Va Re
footnote 13 cf. t. IV 250, 12. Her. Ι 1, 1; V 39, 2. Isocr. Areop. § 47 p. 149 b. Plat. Criti. p. 121 A 1 δὲ γάρ. δεήσομαι γὰρ sed δὲ et γὰρ inser Va | ἴσως om HVB 2 διαχρησάσθω AthVa sed δία antepos AthVa 2 χρη- σάσθω HV Ι καὶ ante ταύτην HV 3 τὸ HVViM | ἀποκα- θαίρωμεν Ma 5 ἀποκτείνωμεν Vi | δικαιότατον scripsi ex HVViMaClAth coll 1. 19 δίκαιον BVaM edd 6 οἶμαι om Vi | ἐκεῖ Vi sed ἐκείνου in marg m 2 7 μὲν om HVVi 8 δικαίως om Mor sed γρ in marg | ἀποκτεινομένην inserui om libri φονευομένην edd | οὐ Μ 9 τῆς τιμωρίας HV | καὶ om ViMaCl 11 πρώην in marg inser Vi 2 | ante τῷ inser Ma 3 | πατρὶ πάθος Vi sed τοῦ πατρὸς πάθει marg m2 13 ἐκείνην in marg inser Ma3 15 ζῶντι Vi sed ζῶν in marg m2 18 τελευτήσαντι Β 19 καταβοήσομαι Ma Cl sed o del Ma2 Cl2
