@node
@author=Libanius
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Richard Foerster
@filename=tlg2200.tlg00547.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane
@publicationStmt=University of Leipzig, tlg2200.tlg00547.opp-grc1.xml.
@respStmt=Gregory R. Crane, Editor-in-Chief, Perseus Digital Library, Digital Divide Data, Corrected and encoded the text, Matt Munson, Project Manager (University of Leipzig), Annette Geßner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor, Greta Franzini, Project Manager (University of Leipzig), 2013-2014, Frederik Baumgardt, Technical Manager (University of Leipzig), 2013-2015, Simona Stoyanova, Project Manager (University of Leipzig), 2015, Project Assistant (University of Leipzig), 2013-2014
@sourceDesc=Richardus Foerster, Richard Foerster, Libanius, Declamationes XXXI-LI, B.G. Teubner, Leipzig, 1913, 7, Internet Archive.
@sponsor=University of Leipzig
@title=Declamatio 47
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:58:04Z

5211	footnote Ρ = Codex Parisinus gr. 3018 Μ = Marcianus gr. 439 Cr = Hierosolymitanus S. Crucis 57 Ma = Matritensis 4679, olim N-49 Cl = Berolinensis gr. 195 olim Claromontanus Pa = Parisinus gr. 3017 Β = Barberinus II 41 (Vaticanus Barb. 220) Va = Vaticanus gr. 82 1 Συγγνώμη Μ cf. Hermog. stat. 2 et 6 Rhet. gr. ed. Spen- gel. II 140, 6 et 163, 19 sq. c. scholl. Rhet. gr. ed. Walz. t. IV  650, 12 sq.; 670, 8; 687, 12 699, 14 sq. 1 Θεωρία ante Ἔχων Ferr, Ἄλλη μελέτη. Θεωρία Mor Re  delevi | τίς MaCl VaPa edd | παῖδας δύο MaClPa | ἐχθρωδῶς  scripsi e MaClB sed in hoc θ inser m 2, Va et γρ in marg Mor  cum Iacobsio Lect 136 ἐχθρὼ Μ sed δῶς add y ἐχθρῶςωδῶς  Pa ἐχθρῶς Ρ edd 2 ἐκέλευε MaClPa ἐκελεύετο Va | ἐν  ταῖς om Va 3 αὐτὸν MaCl 5 εὑρὼν καὶ om Pa sed ἰδών  post ἐγγεγραμμένον 6 γράψαντα ΒVa 7 Φιλαδέλφου ἀπο- κηρυττομένου ἀπολογία. Ἀλλ᾿ Mor Re, Ἡ μελέτη Ferr delevi 8 οἶος Re
marginal RIV 670
footnote 1 ἄνδρες MaClVa cf. p. 585,5; 587,11; 589,22; 596,3; 597,  17; 598, 12; 599, 3; 603, 10; 605, 1; 607, 12 | ἀεὶ post ἐπαινῶν Pa  cf. Boissonad. Tzetz. alleg. 396 4 ἐστὶν Ρ Mor Re | ἤδη ante  δύναται Mor Re delevi | δύνασθαι Ferr et γρ in marg Mor  5 εἰ om Β | πρῶτον MaClPa 6 ὑγιείας Μ sed ι(1) inser y, Ma  Cl | παρακελεύεθ᾿ VaPa | γε om MaClPaBVa 7 τὲ MaClPa  ΒVa et γρ in marg Mor 8 ἂν μᾶλλον BVa | ἂν om MaClPa |  ἐβουλόμην Μ sed ε ex η corr y, Pa 9 τοῦτο BVa 10 φόβον  Ma sed γρ τρόπον in marg τρόπον Cl sed γρ φόβον in marg  11 συμβαίνειν Pa sed συμβῆναι in marg 12 ἀποθανεῖν Pa sed  γρ΄ ἀπελθεῖν in marg | μέ Ma | μὴ om MaClPaVa | τούτοις  MaCl τούτου VaPa 13 ἐθέμην ἄν MaClPaVa et γρ in  marg Mor | ἂν — 14 κακὸν in marg Cl 2 | οἶς om PaBVa | ἔκαμ  cum lacuna 2—3 litt Β 14 λύσαι PPaBVa edd 16 τὸν  om Μ | πρᾶον Va 17 δοῦναι om sed εἷναι post ταύτην Ma  ClVa δοῦναι εἶναι Β 18 τοῖς δικαστηρίοις Ma
marginal RIV 671
footnote 1 τῶν scripsi e PMClPaVa ut coni Re τῷ MaB edd  4 ὧς om ΡΜ et γρ in marg Mor 5 ἄνδρες MaClPaVa et  γρ in marg Mor | τὴν αἰτίαν MaClPa 6 εἰωθότων — 9 ἀκού- οντες om Va 7 τῶν πατέρων om Β 8 γίνεσθαι MaClPa  τι om MaClPa et γρ in marg Mor τί edd sed „aut delen- dum est τι ex auctoritate marginis Mor aut leg. est eius loco  τισί“ Re at cf. t. VI 576, 17 9 μου MaClVa 10 ἐγίνεσθε  MaClPa 11 τῶν ἔργων Β sed v bis eras et τὸ ἔργον suprascr,  Va | πρᾶξαι MaClPa 13 οὕτως οὖσιν MaClPaBVa  14 ὠμομοκότες Ρ ὀμωμοκότες Ma ὀμωμωκότες Va sed ‘in’  corr m2 | πεποιημένοις MaPa sed in hoc γρ΄ ποιουμένοις in  marg, Β 16 ἡδικεῖσθαι edd sed ἠδικῆσθαι scribendum dixit  Mor Not f. VII 3 17 τὸν om MaClPaVa 18 ἐβουλήθη Β  edd 19 καὶ om Cl | γινομένοις MaClPaBVa 20 δύναιτ’  ἂν] δύνατ’ Va δύναται MaClPa
footnote 6 cf. t. I 101, 16; VI 608, 5 16 Dem. Mid. p. 576, 11 1 ἑορτὴν ἡμᾶς ἄγειν MaClPaVa γρ ἡμᾶς ἄγειν ἑορτὴν in  marg Mor 2 νῦν om MaClPaVa | τῷ τοῦτον Ma sed e τοσ- οῦτον corr m 3 8 ἑτέραν PaVa sed v in σ corr m 2 | οἴκοις  Cl 9 τὸ Va | αὐτοῦ PMaClBVa edd 10 ἐμοῦ MaCl  ἐμαυτοῦ Pa | γεγενῆσθαι Pa 11 εἰπεῖν πάρεισι MaClPaVa  13 οἴκων Va | συναινοῦντα MaCl 15 ἂν εἰκότως Β | εἰκότως  om MaCl 16 συνεξητάζετό scripsi e MaClPaBVa ut coni Re  συνεξήταζέ ΡΜ edd | τάμεν Pa 19 γέγονε Μ sed ο in ras  y 21 οὖν om MaClPa | ἠβουλόμην Va 22 γεγραμμένα Ma
marginal RIV 672
footnote 1 τινά μοι MaClPaBVa | γρ παρὰ in marg Mor 4 τὸν  om Re 5 ἦν om ΡΜ | τοῖς πολλοῖς MaClVa 6 τῆς κατη- γορίας δὲ καὶ τοῦ πατρὸς MaClPaVa 7 διὰ βραχέων om Ma  ClVa 8 ἔστω om Pa | καὶ τούτων αὐτῶν δέ μοι Pa | αὐτῶν  om MaCl 10 δύο τούτω Ma | γρ τ’ οὖν ὁ φεύγων in marg  Mor | ὦ ἄνδρες ὁ νῦν φεύγων MaCl 11 ἄνδρες MaClPaBVa 13 ὥσπερ ἂν εἰ PMMaClPa ὥσπερ ἂν ἐν BVa 17 τε  om MaClPa 18 ἢ Cl ἧ Pa 19 περὶ Va 21 διάγειν  Ma sed δια in ras m 3 22 ᾔεις scripsi e MaClVa cum lacob- sio App Pors 308 Lect εἴης PMPaB edd
marginal RIV 673
footnote 2 κληρονόμω τῆς οὐσίας Ma | κληρονόμους Β 3 μὴ δὲ  PMaClPaBVa Ferr 5 ἆρα Cl 7 πλημελεῖ PMMaVa Ferr  | οὑμὸς] ὁ MaClPaB Va | τά γε ἀληθῆ] τὰ τε ἀληθῆ Va τἀληθῆ  MaClPa 8 φέρεται PaVa 9 ἄνθρωπος τίς Ma 11 κατη- γοροῦντος Β 12 μικρὸν PaBVa 15 τί MMa 16 τί Ma  ClB 18 καὶ om Ferr | τότε scripsi e Ma τό τε reliqui libri  edd | τὴν ante ἀποκήρυξιν Pa 19 ἐκεῖνος ἄνθρωπος MaCl  PaB Va 20 πρὸς Ma | τοπρῶτον Mor | ἐξειργασμένος Pa  23 μὴ δὲ PMaClPaBVa Ferr 24 ποιῆσαι MaCPa
marginal RIV 674
footnote 4 Il. η 242 sq. 13 cf. t. III 52, 11. Dem. Apatur. p. 897,3 2 μὲν om Ma | τί post αὐτῷ MaClPa, τι Β 3 τε post  ἐλθεῖν Va 4 μὴ δὲ PMaClPaBVa Ferr 5 τοῖς ante τοι- ούτοις MaClPa 6 δ’ ἂν MaClPa 7 ἐν Mor sed γρ ἕκων  in marg 8 ὁ τότε] ὅτε MaClBVa 10 περὶ Va | μὴ δὲ Ρ  MaClPaB Ferr μὴ Va 11 θιγεῖν libri edd cf. t. I 127, 18;  σῶμα  III 259, 3 | μὴ δὲ PMaClPaBVa Ferr | νόσημα Va τὸν κάμνοντα  MaCl 12 γε om MaClPaBVa | δὴ Ferr Mor 13 καὶ(2)  om Va 14 καὶ om Ma | δέ Ma 16 ἐγνώκειν Va sed κ in  ras m 2 18 μοι post γενέσθαι MaClPa | καὶ] κατὰ coni Mor 19 ἀδελφὸς ὁ σὸς MaClPaVa | οὕτω ταῦτα MaClPa | voce  μὴ inc Cr fol. 88r 22 ἄνδρες CrMaClPaVa
footnote 2 πῶς ante οὐκ PMCrClPaBVa edd om Ma delevi πε- πραγμένον; πῶς; (scil. εἴποιμι ταῦτα) coni Re ὡς lacobs Lect  | ἠδυνήθην MaClVa 4 μοι om Va 5 τοῦ om Ma 6 μοι  CrMaClPaVa | ἐνέγραψα ταῦτα inser Cl 2 | ἐνέθηκα Va | ταῦτα  om Va 7 ἅπερ Cl sed ἅ inser m 2 9 καὶ et δυστυχὴς om  MaClPaVa | ὁ in ras inser Ma 3 10 παρὰ incertum Cr ut  pleraque quae antecedunt et sequuntur usque ad p. 591, 15 καὶ  περὶ BVa „παρὰ videtur delendum esse aut potius loco huius  παρὰ leg. esse πατέρα et loco pronominis τοῦτον paulo post ad- verbium πάλιν“ Re πάλι lacobs Lect | τοῖς post παρὰ PMB  edd delevi | τοῖς inserui e MaPaVa om PMClB edd | ὑγιάναι  MaClBVa 11 τε om Va 12 γρ ἐκεῖνον in marg Mor  13 ὧς] τὸ Re 14 ὕπεισι Pa 15 καλεῖ — 16 δὲ om MaCl  | καὶ ante πάλιν Mor Re delevi 17 διεστάναι MaClBVa  20 τὰ τοιαῦτα] ταῦτα MaClPaVa | οὕτω γράμμα MaClPa  BVa | πρᾶγμα Cobet Coll 299 at cf. p. 592, 15; t. IV 393,7
marginal RIV 675
footnote 6 cf. t. IV 746, 17 R 2 τοὔργον Va τοὔργον Cl 5 τοῖς ante πατράσιν Mor  Re delevi 6 μὰ PM Ferr cf. t. VI 527,2 c. schol.  7 θεοὺς in lac 12 – 14 litt om Va | νόμων Β | πεποίηταί Pa 8 παρὰ om BVa | καθέκαστον PMMaClPa 11 καὶ μὴ  Β et γρ in marg Mor 13 πρᾶον Va Ferr Mor | ἶσον Cl | καὶ  post ἴσον repet MaCl | τε — 15 καὶ om MaCl 14 τε scripsi  γε PMMaClBVa edd sed γρ τε in marg Mor μοι Pa  15 τ’ ἄλλα Β 16 ὅλως MaClPa | ἐποίει τῆς οὐσίας CrMaCl  PaBVa 17 οὐδεπώποτε scripsi e MaClPaBVa οὐδέ ποτε  PM edd 18 οἷον Va | ἔδοξεν Va 20 ὅτι ClVa 21 τρέ- φει scripsi e MaPaBVa ut coni Re τρέφειν Ρ sed v eras,  MCl edd
marginal RIV 676
footnote 1 Callim. epigr. 64, 4 3 cf. p. 97, 5. Dem. fals. leg. p. 417, 21 2 ἐβόησε Ρ 3 γρ ὄρεσι in marg Mor 4 μοι reposui e  libris μου edd sed γρ μοι in marg Mor 6 τὸν ante ἀδελφὸν  MaClPaVa 8 ἥδιστ’ CrMaClPaBVa | ἴδοι Mor sed γρ ᾔδη  in marg ἴδη BVa 9 τοῦτον Ferr | τί om MaVa 10 ἕτερα  — 12 ἑνὸς in marg Cl 2 11 δύο] σὺ MaCl 2 Pa | ἐποίησας Ma  sed σ in ras m 2 12 κληρονόμου Ma 15 πραγμάτων Ma  ClPa | καταστὰς — 16 πάτερ om Va 18 ἀλλὰ ΡΜ edd  19 ἔχοι Οἶ’ 20 οὐδὲ ΡΜ edd | πεποίηκεν Ma 22 ἔργοις  Ferr et γρ in marg Mor | τούτω MaClPaVa
footnote 1 cf. p. 563, 15 7 Antiph. tetral. III 4 § 7 p. 128, 39 1 καὶ ante κατέρχεται MaClPaVa Mor sed in hoc γρ in  marg om, Re | αὐτοῦ MaCl 2 τὸ ante τούτων Β 3 ἐκεῖ- νος MaClPaBVa edd | ἀπέκτεινεν MaPaBVa 4 ἔστιν Va  sed v eras 5 τὸν et βουλόμενον CrMaClPaVa et γρ in marg  Mor 6 διατοῦτο MaPaBVa | μισεῖν Re 7 αἰδεῖται CrMa  ClPaBVa et γρ in marg Mor 8 νικήσας ΡΜΒ Ferr et γρ  Mor 9 τοῖς om Va | δείκνυται Cr 11 κατὰ] καὶ MaCl  τοῦτο inserui cum Sinteni, ut inseruit M n om reliqui libri  edd 12 νῦν] σὺ νῦν Β σὺ Va 15 ταῦτα MaClPa  16 πρὸς(1) om Μ | τοὐς(1) om Cr | — 20 commata posui, cola Va,  signa interrogationis reliqui libri edd 17 φιλέτας MaCl  φιλτάτους ΡΜ Ferr et γρ in marg Mor | τούς om CrMaCl |  τοὺς om CrMaClPaVa 18 πρᾶον Va Ferr Mor 19 κατή- κοον τῆς μητρὸς MaCl 20 περὶ σὲ om MaClPaVa
marginal RIV 677
footnote 9 cf. ad p. 467, 19 12 cf. ad t. V 426, 8; VI 404, 19 1 ὃς om FaBVa 2 ἠβουλόμην MaClPaVa 3 ἀπαι- τῶμαι ΡΜ Ferr | δ’ αὖ MaClPa | σωφρονῶ Cl 5 οὐκ —  6 κληρονομεῖν om Μ 6 ἠξίους Ma sed σ suprascr m 3  7 ἀδελφὸν δυστυχοῦντα Μ | τὸν ante ἀδελφὸν inser Mor Re  delevi | γε om B Va | πολλάκις εἰπεῖν] λέγειν MaClPaBVa  9 Φύσεως scripsi φύσεως libri edd 11 ὥσθ’ om MaClPaB  Va | τύχη MaClBVa 13 χείρους MaClPaBVa Mor Re cf.  t. III 198, 2 14 τι MaCl 15 ἐπίοι scripsi e Μ sed οι ex  ῃ corr n, BVa sed in hoc ίο in ras ἐπίῃ PClPa edd ἐπιῆ  Ma sed ~ del et supra ι m3 16 τυγχάνη Β | ἆρ’ οὖν scripsi  cum lacobsio Lect ἆρ’ ἄν ΡΜ edd ἀρά MaClPaVa ἆρά Β 17 καὶ(2) om MMaCl 18 αὐτῶν Β | πέσοιμι Ma  19 ἄλλως lacobs Add 46 Lect coll t. V 543, 14
marginal RIV 678
footnote 6 Dem. Olymp. p. 1173,6 et 17; 1175,14; 1178,22  19 Dem. fals. leg. § 208 p. 406,5 1 καὶ τὸν παῖδα om MaClPaBVa 4 ἠλέησα — διαθη- κῶν in marg Ma 3 5 εἰ μηδὲ scripsi auctore Re εἰ μήτε  libri sed ἐπεὶ οὔτε suprascr P 2, edd 8 μετεῖχεν οὐδενός Μ 9 εἶχε scripsi e MaClPaBVa εἶχον ΡΜ Ferr εἶχεν Mor  Re 11 γερόντων MaClPaBVa 12 ἠξιοῦτο Ma et ex ἠξίου  corr Cl 2 13 κοινῶν reposui e libris ut coni Re κοινωνῶν  edd | ἶσον MaClVa 14 στρατιώτην BVa 15 ἐνεχειροτόνη- σεν Ma sed ἐν del et ροτ in ras m 2 16 αὐτοῦ libri ’ in  corr P 2, edd | πῶς] τίς Va 17 καὶ om Ma 19 τοῦτ’ Β  Va | αὐτῷ reposui e libris sed ex αὐτὸ corr Va αὐτὸ edd  20 ἐξέβαλε Pa 21 ὦ πάτερ ante εἰσῆλθε BVa
footnote 15 [Arist.] physiogn. 29 ed. script. physiogn. t. I p. 38, 3 3 εἰκότως ὑμεῖς Va | ἄνδρες MaClPaVa cf. p. 584, 1  4 αὐτοῦ MaClPaVa αὐτὸν Μ 7 ἂν om Ma 9 „malim  τινα“ Re at cf. p. 600, 1 10 ἐλεῶν inserui om libri edd  11 κηρύττοιτο ζῶν; Pa | ἐώρας Ma 13 διατί Β 17 οὗτος  scripsi e MaClPaBVa et γρ in marg Mor αὐτὸς ΡΜ edd  18 γάρ om Β 19 μὲν ἀμφοτέροις Ma 20 τὸ om Re
marginal RIV 679
footnote 23 cf. t. I 161, 6; IV 217, 17 1 καταφεύγομεν MaCl 2 τε om MaClPaBVa 3 εἶχε  Pa | τι Ma sed ι in ras m 3 5 ἀδελφὸς ὤν] ἀδελφῶ Β sed  ὃς ὢν supra ῶ, Va 8 καὶ ante σοι Pa | τι Pa | γρ χαρίσασθαι  in marg Mor 9 προσίεσθαι] προίεσθαι Β μὴ προσίεσθαι Va  μὴ προίεσθαι MaClPa et γρ in marg Mor 10 τὸ scripsi e  ΡΜ τὸν MaClPa Mor Re τοῦ BVa τὸ Ferr et γρ in marg  Mor | προσέχει Mor Re 12 εἰκότως MaClPaBVa | ἐκεῖνον Pa 16 γινομένῳ MaClPaVa | τῶ Pa 17 ἄνδρες MaClPaB  Va cf. p. 584, 1 18 μὴ MaCl 22 voce τὴν inc Cr fol 33 v  sed pleraque posteriore scriptura obtecta 23 ταῦτ’ BVa
marginal RIV 680
footnote 1 ἤδη Va | ἥξοντα scripsi ut coni Re coll t. V 72, 16  ἕξοντα PMPaBVa edd ἕξοντα MaCl | κατηρᾶτο MaClPa  2 διατοῦθ’ MaPaBVa 3 ὁπεροῦν coni lacobs Anth. Pal. III  741 | οὐκ ante ἐξῆν edd delevi, ut delendum coni Re | δι- δόναι διὰ τῶν coni Mor Not 4 ἀμφοτέροις om Re | ταυτὸ  MaPaBVa 5 βοηθῶν ἀδελφῷ καὶ πατρὶ Pa 8 ὑμῖν scripsi e  CrMaVa cum Sinteni ἡμῖν PMClPaB edd 9 ἠμελήθην Ferr  Mor | τι om Ferr | τῷ ἀδελφῷ MaClPaBVa et γρ in marg Mor  cf. ad p. 620,22 et t III 288, 20 10 διελέχθην scripsi διηλέχθην  BVa διειλέχθην PMMaClPa edd sed „malim διελέχθην“ Re  cf. p. 569,9; 603,2 | γε om Β μὲν MaClPa 12 ἄνδρες Ma  ClPa cf. p. 584, 1 | γενόμενοι Pa 13 ὑμεῖς Ma sed ὑ in ras  m 3 | ὑμεῖς ΡΜΒ Va Ferr et γρ in marg Mor 14 οὐ om Β |  ἀμώμητον MaCl sed in hoc inter ἁ et μ ras 1—2 litt | μὴ ante  εἶναι BVa 17 γε om MaClPa | καὶ — 599, 6 εἶναι praemissis  verbis τῆς μελέτης ἐν ᾖ ὁ ἀποκηρυχθεὶς διὰ τὸ γράψαι τὸν ἀδελ- φὸν συγκληρονόμον ἀπολογεῖται laudavit Macarius Chrysocephalus  fol. 80r | καὶ] ἔστιν ὅτε Macar 18 ἔδρασε BVa
marginal RIV 681
footnote 19 Thuc. II 37,2 1 μετεμέλησε scripsi e MaClPaVa Macar μετημέλησε ΡΜΒ  edd 3 συγγνώμης ὑπῆρξε Pa | δὲ Macar | ἄνδρες MaClPa cf,  p. 584, 1 5 θεοῦ Μ | τὸ κρείττους μόνων (μόνον MaCl) MaClPa  Macar | μόνων scripsi e ΡΡαΒ Macar μόνον MaClVa edd sed  „malim μόνων“ Re μόνου Μ | κρείττω Μ 6 καὶ om MaCl  Pa 7 παρατοῦτο Ma 8 δοκοῦντας ἀχρήστους τε εἷναι  scripsi e ΡΜ δοκοῦντας ἀχρήστους εἷναι Β Va Ferr εἷναι δο- κοῦντας ἀχρήστους τὲ MaClPa Mor εἷναι δοκοῦντας ἀχρήστους  Re | ἀπορριπτομένους MaCl 9 τὰ inserui e PMPaBVa om  MaCl edd | τούτους reposui e libris τοιούτους edd 13 νι- κῶσι BVa 14 καὶ om MaClPa | δεῖ — 17 ποιεῖν laudavit  Macarius fol. 80 r | δεῖ non post καὶ, sed post θαυμάζειν Macar  | τῶν om MaCl | τηλικούτων] παίδων Macar 15 τε om  Macar 16 μὴ ante ἐπαινεῖν, non post μὲν Pa 17 οὔ Macar  | δὲ Pa 18 καὶ ante ὄρα MaCl | „malim εἰ σοῦ τις vel εἰ σέ  τις“ Re 19 οἷς Ma sed ι m3
footnote 1 τυγχάνειν Ma sed ν(2) add m 3 | τίνα MaCl 2 δέδωκε  MaClPa 3 ἐγὼ φαίην ἄν scripsi e PMBVa ἂν ἐγὼ φαίην  MaClPa Mor Re φαίη ἂν Ferr 4 γρ χρόνον οὐ πολύν in  marg Mor | ἀγγελόντων Ma sed λ(2) inser m 3, ClBVa  7 voce διακόνων inc Cr fol 33 r 8 ἔκλαυσεν MaCl | αὐτοῦ Va  sed οῦ ex ὸ corr m2 12 ἂν om Pa | εἶκεν Cl 14 τοῦτον  Cl sed in τούτου corr m 2 15 ἐν om MaCl 16 με inserui  e PMCrMaClPaVa om Β edd | ἔπεισε om Cr ἔπεισεν MaPa 17 ἀξιῶσαι τὸν ἀδελφὸν τῶν ἴσων MaClPa | καὶ om Β  περὶ Va | μικρὰ κεκρίσθαι μικρὰ MaCl 21 διαφύγῃς MaCl 22 μάθοις Ma sed οι in η corr m3 23 εἰρήκει MaCl
marginal RIV 682
footnote 3 cf. t. II 126, 4 20 cf. p. 625, 20. Dem. cor. p. 312, 17.  Xen. anab. III 2, 25; IV 5, 29; VII 6, 31 1 δὲ Re 2 εὔδηλον ΡΜ Ferr et γρ in marg Mor | ἔγρα- φον MaCl 3 τε Ma sed ε add m 3 4 εἰσόμενον MaCl  5 τὸ scripsi e MaClPaVa τῷ PMCrB edd 7 μὲν om CrMa  ClPaBVa | πλούσιον MaCl 9 καλὴν ἂν MaClPa 10 τὴν  ἀφορμὴν τῇ κακίᾳ MaClPa | μὲν om MaClPa 11 κακίαν —  πανταχοῦ in marg Cl 2 om Cr 13 τῶ Pa 14 μᾶλλον om  CrMaClPa | ὅσου Ma | πλοῦτος — 602, 1 ἔνι citat Macarius  fol. 80 r 15 τὸν inser Ma 2 | μὴ MaClPa 17 καὶ(1) inserui  e libris sed καὶ τούς Β Macar om Ferr τοὺς Mor Re  19 εὐπόρων Cr 20 εὕρης Va | ἐν om Ma | ἀφθόνοις scripsi  e CrMaClPaB Va et γρ in marg Mor Macar coll Dem. et Xen.  ll. ll. ἀφθόνῳ ΡΜ edd
marginal RIV 683
footnote 2 cf. p. 573, 5 1 καὶ ante τὰ MaClPa | ἀνέχεταί Β ἀνάσχηταί Pa | στό- μαχόν γε ante πεινῶντα inserendum coni Re cui oblocutus est  lacobsius Lect | φέρειν Macar ζῆν MaCl θαρρεῖν lacobs  2 οὖν inserui e MaClPaBVa om PMCr edd 4 καταισχύνοι  MaCl 5 ποτ’ MaClPa | πᾶσιν Cr 6 καὶ om MaCl  7 ἔπειτ’ Cl 8 αὐτοῦ libri edd 11 αὑτοῖς Cr αὐτοῖς reli- qui libri edd | συνεισφέροντες Ma et in marg Cl 2 | τινὰ αὐτῷ  ClPa 12 ἂν ἦν MaClPa 13 τῷ om Mor | ὥσπερ Va  15 τὸν — 16 γενέσθαι om MaCl 16 οὖν] γὰρ Pa 18 εἰς  κοινωνίαν εἰσῆγον ὕστερον MaClPa 20 γραφόμενον MaClPa 21 τοσαύτην βλάβην MaCl
footnote 6 cf. ad t. VI 543, 15 7 Pittac. apud Stob. III 1 (Diels  Vorsokratiker II 522, 11). inscr. herm. Tiburt. Vatic. (Visconti  Mus. Pioclem. VI t. 22 a. Kaibel, Inscr. Sic. et Ital. 1195)  17 sq. cf. t. V 72, 4 sq. Plat. rep. III p. 389 B. Xen. comm. Socr.  IV 2, 17 1 ἀντίληψις Β cf. p. 424, 1 4 λύσις Β 1 σοι Β 2 διειλέχθης PMaClPaB Va sed in hoc ει in η  corr cf. p. 569,9; 598, 10 4 φλαύρως PaVa | τελευταῖον Ma  ClB 5 τῶν inser Ma 2 om ΒVa | αὐτοῦ Va sed ’ in ‘ corr  αὐτῶν MaClPa 7 ἐπαινούμενον τὸν καιρὸν BVa 9 δὲ  post ἴστε MaClPa 10 ἄνδρες MaClPa cf. p. 584, 1 | ποιλίκης  Ma sed λ in ras et κ e λ corr m 3 11 παρὰ Pa 12 καὶ(2)  — 13 δύναται citat Macarius fol. 80 r 13 τοιούτους] νοσοῦντας  Macar 14 φθέγγηταί Mor Re | ἑστήκῃ Cl sed η ex ὸς corr  ἑστήκοι PaVa ἑστηκὼς Ma | καθίζων ἦ Ma 15 κἂν σκυθρω- πάζῃ om BVa 18 μὴ δὲ PClPaBVa Ferr μὴ Ma
marginal RIV 684
footnote 1 διατοῦτο MaPaBVa | καὶ πρὸς αὐτοὺς MaClPa 2 ἂν  om BVa 3 ὑπάρχον scripsi e CrMaClPa et γρ in marg Mor  ὂν PMBVa edd 8 γρ ἄλλων ἰατρῶν, εἰ in marg Mor  9 οὐκ ante ἐπ’ MaCl 12 ἐμέμψατο Ma 13 ἐπήνεγκεν Ma 16 δίκαιά με Ma | μοι Pa 18 σου MaPa 19 ἐξωθεῖν  Β 22 δ’ ἂν] δὲ CrMaClPaBVa 23 κακοῦ inserui auctore  Re om libri edd 24 τινος Mor sed γρ τίνος in marg | ὀργῆς  post τινὸς Pa, αἰδοῦς MaClB Mor sed in hoc om γρ in marg,  Re delevi
marginal RIV 685
footnote 15 cf. p. 616,11. Dem. Boeot. nom. p. 1001,4 et 8; Boeot.  dot. p. 1016, 29. Arist. av. 922 1 ὦ δικασταί om MaCl 5 γε om MaClPa | σιωπᾶν BVa 6 ἀπαιτεῖν Va 11 πράοις Va Ferr Mor 12 καὶ om  Β 13 μὲν — δὲ om Ferr | ἑαυτὸν MaClPa Mor Re  14 μὲν om MaCl 16 γεγενημένων MaCl 17 δοῦναι Μ  20 τῶν om MaCl | αὐταὶ BVa 24 ὁ om Ma
footnote 12 cf. ad t. VI 213, 18 14 Arist. rhet. II 21 1 ὡς ante ἀληθῶς Pa 2 καὶ τοὺς] τούς τε CrMaClPa et  γρ in marg Mor voce τε des Cr fol 34 r 5 ἐπιμελεῖς Β  6 κατήφειαι Ferr 8 δὲ om MaClPaBVa | οὐδαμόσε PM Ferr  et γρ in marg Mor 11 ἐγκαλοῦνται Ma 13 μάχην MaPa |  ἀλλήλαις scripsi e MaClPaBVa ἀλλήλοις ΡΜ edd | συνευχόμε- ναι scripsi e ClVa συνευωχούμεναι MaPa συνευχόμενοι PM  edd 14 χαλεπαίνεις ἀθάνατα BVa | „malim χαλεπανεῖς“ Re cui  oblocutus est lacobsius Anth. Pal. III 105 15 ποιήσης Va  ποιεῖς MaClPa et γρ in marg Mor | σύμβουλον MaCl 16 κα- κώσας Va κακὸς εἶ εἰς MaCl et γρ in marg Mor | τὰ om Β et  γρ in marg Mor 17 αὐτῶν MaCIPaBVa et γρ in marg Mor |  συνεφήψατό σοι τῶν γάμων scripsi auctore Re συνεψηφίσατό σοι  τὸν γάμον libri edd 18 ταύτην om MaCl τοιαύτην coni lacobs  Lect 99 τὴν inserui auctore Re om libri edd | διατί MaCl  PaBVa Ferr | γενομένους Β γενωμένους Va
marginal RIV 686
footnote 9 [Dem.] Steph. p. 1103, 3; 1107,19 1 τοιούτων Ρ Ferr et γρ in marg Mor 9 κατασκευάζον- ταί reposui e libris coll Dem. ll. ll. παρασκευάζονταί edd  10 ἐξελάσαιμεν Cl | σε om MaClBVa | τοῦ Μ 11 δ’ MaCl  Pa | τοῦθ’ MaCl 12 ἄνδρες MaClPa cf. p. 584, 1 | πραότερον  Va Ferr Mor 13 καὶ(3) om Va 16 τίς MaClPaVa  17 αὐτοῦ MaClBVa αὐτῶ Pa | μεταδιδούς Cl sed ετα inser m2 21 καλεῖν Ma | ἀπ’ MaCl 22 λάβῃ MaCl
