@node
@author=Septuaginta
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Henry Barclay Swete D.D
@filename=tlg0527.tlg041.1st1K-grc1
@funder=Harvard Library Arcadia Fund
@principal=Gregory Crane
@publicationStmt=Harvard College Library, tlg0527.tlg041.1st1K-grc1.xml.
@respStmt=Digital Divide Data, Corrected and encoded the text, Gregory Crane, Editor-in-Chief, Perseus Digital Library, Matt Munson, Project Manager (University of Leipzig), Annette Gessner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig) 2015 - 2017, Bruce Robertson, Technical Advisor
@sourceDesc=The Old Testament in Greek, Henry Barclay Swete D.D, Septuaginta, Cambridge University Press, Cambridge, 1905, 3, The Internet Archive.
@sponsor=Harvard College Library
@title=Jonas
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:55:35Z

1304	marginal B
marginal U+05D0AQ Inscr Ιωνας ς BU+05D0AQ) I 1 Αμαθι AQ 2 πορευθητι Bᵃᵇ (-ρευθυτητι B*)] πορευου A | Νινευη] pr την A | κρουη U+05D0* (-γη U+05D0c. ᵃ) 3 ηφυγειν] υγ rescr U+05D0¹ (φοιιν U+05D0*ᵛⁱᵈ) | εκ 1⁰] απο U+05D0A | Ιοππην] Ιππην U+05D0* (Ιοππ. U+05D0c. ᵃ) | om και εδωκεν... εις Θαρσεις (3°) U+05D0* (hab U+05D0c.ᵃ) μετ ουτων εις Θαρσεις] εις Θ. μετ ουτων A | Θαρσις (3⁰) U+05D0c.a 4 επι] εις U+05D0c.a, ο c.b AQ | εκινδυνευσεν] εκινδυνευε Qᵃ | συντριβηναι] του διαλυθηναι U+05D0c.b (postea συντρ.) A 5 ανεβοησαν] εβοων A ανεβοων U+05D0c.b) Q | αυτου] ουτων AQ* (-των Qᵃ) | ερεγκε Qᵃ 6 πρωρευς] οι γ΄ κυβερνητης Qmg | αυτω] προς αυτον A | ρεγχεις (ρεγκ. Qᵃ)] ρεγχει U+05D0* (-γχεις U+05D0c.a, c.ᵇ) | αναστα] αναστηθι U+05D0c.b Qᵃ om και 3⁰ Q | οπως] ειπως AQᵃ (επως Q*) | διασωσει Q* ᵛⁱᵈ | ημας] pr η U+05D0 | μη] pr ου U+05D0c.a AQᵃ 7 ειπεν] ειπαν Q | επιγνωμεν] επιγνωσο-μεν U+05D0* (-γνωμεν U+05D0c.a, c.ᵇ) | αυτη εστιν] η ε rescr U+05D0¹ εν ημιν] εφ ημας Q
marginal B
footnote 8 ειπον] ειπαν U+05D0AQ | απαγγειλον] + δή Qmg | ημιν] + τινος ενεκεν η κακια  U+05D0AQ  αυτη εστιν εν ημιν AQ | ερχη] + κ που πορευει U+05D0c.b + και που πορευη Qᵐᵍ | ει συ] συ ει Q 9 ειμι εγω U+05D0* (εγω ειμι U+05D0c mox ειμι εγω revoc) | τον κυριον θεον] κν τον θν Q | σεβομαι] φοβουμαι U+05D0c.b 10 φοβω μεγαλω U+05D0c.ᵇ ⁽ᵛiᵈ) (mox φοβον μεγαν revoc) | φευων U+05D0* (φευγων U+05D0c.a) 11 ποιησωμεν U+05D0A | επορυετο U+05D0c.b επωρυετο AQ* : item 13 12 αυτους] αυτο Qᵃᵛⁱᵈ εμβαλετε] ενβαλατε U+05D0 | om με 2⁰ AQa οτι] διοτι U+05D0* (οτι U+05D0c.b) κλυδων] γ pro κ inceb U+05D0* (κλ. U+05D0¹) 13 καιπερ εβιαζοντο B* ᵛiᵈ (και παρεβιαζ. Bᵃᵇ) προς] θ΄σ΄ εις Qᵐᵍ εδυναντο A εηγειρετο U+05D0* (εξηγ. U+05D0¹ c.a) 14 προς Κυριον και ειπαν μηδαμως sup ras et in mg Aa Κυριον] pr τον U+05D0* (om τον U+05D0c.b) om μη απολωμεθα...συ Κυριε U+05D0* (hab U+05D0c.a) απολοιμεθα U+05D0c.a (απολωμ. U+05D0c.b) Q διοτι] οτι AQ* (διοτι Qmg) συ] σου U+05D0c.ᵃ βεβουλου U+05D0* (εβ. U+05D0?) 15 εξεβαλον] εβαλον U+05D0*c.b ενεβαλον U+05D0c.ᵃA σαλους AQ* (-λου Qᵃ) 16 εφοβηθησαν] incep ερ U+05D0* θυσιαν AQ* (-ας Qᵃ) om κυριω U+05D0* (superscr κω U+05D01) | ηυξξαντο U+05D0¹ (ηξ. U+05D0*) AQ II 1 κητει] τητει U+05D0* (κητι U+05D0c.a, c.ᵇ) καταπιειν] και κατεπιεν U+05D0* (καταπ. U+05D0c.a, c.ᵇ) τον Ιωναν] om τον U+05D0? 2 τον θεον] om τον U+05D0c.ᵃ (rurs ras) Q 2—3 om αυτου εκ της κοιλιας...Κυριον τον θεον (2⁰) U+05D0* (hab U+05D0¹c.a (ᵛiᵈ), c.b) 2 τον θεον] om τον Q 3 ειπεν] + ως Qmg B
marginal U+05D0AQ 3 εβοησα] pr ωδη A | κρουης U+05D0* (-γης U+05D0c.a) 4 απεριψας U+05D0Q* | με 1⁰] μες (sic) U+05D0 | om σου 2⁰ Q* (hab Q¹ᵐᵍ) 5 και εγω] καγω A | επι-βλεψαι] επιστρεφε U+05D0* (επιβλεψε U+05D0¹ -ψαι U+05D0c.a, c.b) | τον λαον B* ᵇ] τον ναον BᵃᵇU+05D0 ναον AQ 6 υδωρ μοι (μου U+05D0* μοι U+05D0¹)] μοι υδωρ AQ | ψυχης] + μου Qᵃ⁽ᵐᵍ)vid | εισχισμας U+05D0* (εις σχ. U+05D0c.b) 7 φθορα ζωης] εκ φθορας ζωης U+05D0c.c(vid) εκ φθορας η ζωη AQ | Κυριε] pr προς σε U+05D0c.c (vid) 8 εκλειπειν AQ | απ εμου την ψυχην μου] την ψ. μου απ εμου AQ | ευχη] προσευχη U+05D0c.ᵇAQ 9 ελεον U+05D0c.a (mox ελεος revoc) Q | εγκατελειπον AQ* (-λιπον Qa) 10 αινεσως B* (-σεως Bᵃᵇ) | και] ε pro κ incep B* | σοι σωτηριου] εις σωτηριον μου U+05D0c.a non c,b AQ | τω κυριω] pr ω U+05D0* (om ω U+05D0¹c.a) pr τω U+05D0c.b (per incur) 11 προσεταγη] + απο κυ U+05D0c.b (postea ras) III 2 πορευθητι] pr και U+05D0c.a (postea ras) AQ | Νινευην U+05D0 3 καθως AQ* (καθα Qa) | ποριας U+05D0A
marginal B
footnote 4 εισελθειν] εισπορευεσθαι U+05D0c.b AQ | πορειαν (-ριαν U+05D0)] ποριας AQ* (πορειαν  U+05D0AQ  Qᵃ) + οδου AQ | ημερας] μερας U+05D0* (ημ. U+05D01?c.a) εκηρυξω U+05D0* (-ξεν U+05D0¹) τρεις] οι λ΄ τεσσερακοντα Qmg 5 ενεπιστευσαν] επιστευσαν U+05D0c.a | νηστειαν Bᵃᵇ AQ | και 3⁰] αι U+05D0* (και U+05D0c.a) | μικρου αυτων (om αυτ. AQ* hab Qmg) εως μεγαλου αυτων U+05D0c.b (postea μεγ. αυτ. εως μικρ. αυτ. revoc) AQ 6 λογος] λαος U+05D0c.b (mox λογος revoc) | βασια U+05D0* (βασιλεα U+05D0c.a) | Νινευης U+05D0* (ς improb U+05D0c.a postea ras) περιειλετο Qa (vid) 7 ερρεθη (ερεθη U+05D0*)] ερρηθη BᵃᵇQᵃ | παρα των μεγιστανων αυτου] παντων μεγ. αυτω U+05D0c.a, c.b γευεσθωσαν U+05D0* (γευσασθ. U+05D0c.a, c.b) A | μηθεν A | νεμεσθωσαν] + μηδεν U+05D0* (om μηδεν U+05D0c.b) | πινετωσαν U+05D0 8 ανεστρεψαν U+05D0c.b Q* απεστρεψεν A α΄θ΄ επεστρεψαν Qᵐᵍ | πονηρας] πο sup ras seq ras pl litt Aᵃ 10 οιδε U+05D01?c.a (οιδες U+05D0* vid) | μετα-νοιησει Q* (-νοησ. Qᵃ) | τη κακια η] τα κακα α A | αυτοις] αυτοι U+05D0* (-τοις U+05D0c.a) IV 2 προσηυξατο Bᵇ et fort c U+05D0AQ | ω] + (?) ωδη U+05D0c.b vid ωδη certe Qa | μου 1⁰] + ους ελαλησα A | εγνων] + εγω U+05D0c.a (mox improb) συ] + θς Q | οικτειρμων U+05D0c.b AQ* (-κτιρμ. Qa) 3 η] ει BU+05D0* (η U+05D0c.b) pr μαλλον U+05D0c.a (μ. postea ras) om με 2⁰ U+05D0c.b AQ* vid (hab Qᵐᵍ) 4 σφοδρα] + συ U+05D0* (improb U+05D0c.a postea ras) B
