@node
@author=Libanius
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Richard Foerster
@filename=tlg2200.tlg00529.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane
@publicationStmt=University of Leipzig, tlg2200.tlg00529.opp-grc1.xml.
@respStmt=Gregory R. Crane, Editor-in-Chief, Perseus Digital Library, Digital Divide Data, Corrected and encoded the text, Matt Munson, Project Manager (University of Leipzig), Annette Geßner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor, Greta Franzini, Project Manager (University of Leipzig), 2013-2014, Frederik Baumgardt, Technical Manager (University of Leipzig), 2013-2015, Simona Stoyanova, Project Manager (University of Leipzig), 2015, Project Assistant (University of Leipzig), 2013-2014
@sourceDesc=Richardus Foerster, Richard Foerster, Libanius, Declamationes XIII-XXXX, B.G. Teubner, Leipzig, 1911, 6, Internet Archive.
@sponsor=University of Leipzig
@title=Declamatio 29
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:57:56Z

2925	footnote 1 Παράσιτος — 2 πρὸς ἀγγέλλει in marg La 2 εἰσαγ- γέλλει Mor 3 ἐπινεύσητε Ma sed πι in π᾿ ἴ corr m 2  4 ὦ βουλή in marg Ma 2 | συνδράμητε C sed σ in ras n συν- δεδράμητε HV I κηρύγματι Ma sed κηρύ del et βουλή suprascr  m 2 βουλήματι La 5 παραγγελίας La sed αρ in ροσ corr n 7 καταλείπεται LaMa | ἐμπεσεῖν HVC Ferr Mor qui ἐκπε- σεῖν coni 9 οὖν inser Ma 2 Ι ἡμῶν Mor Re 11 μὲν om  La | οὖν La sed in οὐ corr ras | οὐ post οὖν inser Ma 2 | κατα- τήκεσθαι La sed αἰ ex ε corr s 12 ἐπειδὴ τίς HLa sed in  hoc ὴ corr s | ποῦ La Ι προεβάσκηνέ coni Mor et I. G. Schneider  in Steph. Thes. s. v. προσβασκαίνειν
marginal R IV 217
footnote 4 Plat. conv. p. 218 B 5 Plat. Phaed. p. 113 E 8 cf.  p. 587, 12; 595, 2 1 καθηδονὴν La 2 τὸν HV τὴν LaMa Ι οἰός Re  3 τρόφιμον La sed ιμ in ras n Ι ταύτης inserui e LaMa om  HVC edd 5 ἐλπίζειν scripsi e La εὐτρεπίζειν HVCMa sed  in hoc εὐτρε in ἐλ corr m2, edd Ι ἐπειδὰν Re Ι δὲ Ma |  Ma sed in ἀνιάτως corr m 2 7 ἔτι? Ι βιωτὸν scripsi cum Gasda  βιωτέον libri edd | θεῶν La sed εω in ras s 8 τὰ Ma sed  in τὸν corr m 2 Ι συνιδόντες scripsi auctore Re συνειδότες libri  edd 9 δότε La sed συγχωρήσατε suprascr s 10 πάλαι —  595, 1 εὐτυχές ad versus comoediae Atticae revocabat Kockius  Com. Att. fr. III 672 12 εἰ Ma sed in καὶ corr m 3 Ι τούτων  HMa 13 ἡ βουλὴ Ma sed in τῆ βουλῆ corr m 2 Ι αἰτεῖν Ferr 14 γίνεσθαι HMa 16 τις inserui e VC Par 3017 cum  Boissonadio Anecd. IV 319 τίς HMa om La edd 17 ταῦτ’  edd Ι ὡς ante ἔγνων libri excepto Par 3017 (Boissonade 1. 1.)  edd delevi Ι νυνδὶ μετέγνων Kock 18 πως scribendum coni  Re at „Reinkii comectura locum non habet, quum parasitum non deceat dubitanter loqui“ Iacobs Lect 98 qui ὡς aut  aut ὀψὲ legendum censet | τὸ inser Ma 3
footnote 8 Od. θ 167. II. ν 730 sq. 1 αἰτήσαι La | καὶ Ma 2 | λαβεῖν — 2 φέρων del Ma 2 sed  κείμενον in marg m 3 | εὐτυχές La sed ευ in ras 2 litt f εὐ- τυχής HV 2 ἐμαυτὸν scripsi auctore Gasda ἐμαυτοῦ libri  edd | φέρων LaMa | καὶ num delendum? λείπει in marg  Lay „deest aliquid“ Re καὶ ζῆν καὶ μὴ ζῆν Iacobs Add  μὴ eras La 3 ὅπως οὖν La 4 δι’ inserui auctore Sin- teni om libri edd 5 ἕλοι τὸ La | δ’ ἐκείνην LaMa  6 τὴν inserui ex HVLaMa om C edd | θεῶν La sed εων in  ras s 7 ἐπακούσατε Η sed ἑ in ras ὑπακούσατε LaMa Par  3017 „quod an sit melius non statim dicere queo“  Anecd. V 96 8 νέμουσιν — 10 ἀποθανεῖν ad versus comoe- diae Atticae revocabat Kockius 1. 1. III 672 9 ἄλλα] ἄλλο HV  ἕως Cobet Coll 284 10 ἐκπέσοι reposui e libris ἐκπέσει  Ferr ἐκπέσῃ Mor Re | δεῖ La sed εῖ in ras s 12 ἐκπέσῃ  Mor Re 14 κλῆρον πολὺν La 15 ἀκονιτὶ scripsi e LaMa  coll p. 459, 5 ἀκοπητὶ V Mor Re ἀκοποτὶ ΗΟ Ferr Ι ἕτερος  scripsi ut coni Re ὕστερον ΗVCLa sed in hoc ἕτερος suprascr  y, edd ἔτερον Ma sed corr m 2 16 τὸ τοιοῦτο La | ἔχοντα LaMa Ι ἢ πατέρων οὐκ (om LaMa) ἔχων ἔχων Ma)  cancellavi ut orta e scholio ἐκ πατέρων οὐκ ἔχων ut coni Re  („aut varians lectio aut scholion sunt ista ἢ πατέρων οὐκ
marginal R IV 218
footnote 1 πατρῷα pro πατέρων scribendum coni Cobetus Coll 284  coll Men IV 250,54 M (III 177, 581 K) πατρᾷ᾿ ἔχειν δεῖ τὸν καλῶς  εὐδαίμονα οἴκοθεν οὐκ ἔχων ἐκ πατέρων οὐδέν Iacobs Anth.  Pal. III 792 Ι τίς HLa 2 παρὰ La sed e πρὸς corr f 3 τίς Η  La 4 τὰ delendum censet Gasda Ι ταῦτα VC edd 5 παρὰ  — 6 ἐστι ut notam a lectore in margine ad superiora positam  cancellavi cum Sinteni cf. p. 597, 9 sq. παρὰ — διαδέξασθαι  glossam ad τὸν πλοῦτον ἔχειν dixit Gasda 6 ἑτέρου coni Mor 8 ἢ ante ἀπὸ in marg inser Ma 9 ἔχεις HLaMa sed σ  in LaMa eras Ι δὲ scripsi auctore Iacobsio Lect 98 γὰρ libri edd  ἧσσον δὲ ante ἔχει γὰρ excidisse coni Re Ι προηγουμένους  scripsi e La sed οὐ in ras ex ω corr s, Ma ut coni Re προηγου- μένως HVC edd 10 τοὺς inserui e libris cum Boissonadio  Anecd. V 15 om edd 11 τῶν inserui cum Gasda om edd 12 τὸ om Ma Ι τοιοῦτο LaMa 13 ἀπ’ scripsi e La et  Par 3017 cum Boissonadio Anecd. V 96 ὑπ’ HVCMa edd  15 δεῖν La sed ν eras 16 κατ’ ὀλίγον scripsi auctore Re  κατὰ λόγον libri Mor Re κατάλογον Ferr
marginal R IV 219 2 Athen. Χ p. 413 c sq. 4 Luc. Anach. 31 | cf. t. V 540,9 6 Luc. Anach. 11 10 Aristid. pro IVviris t. II p. 202,22  Dind. 12 cf. p. 576,16; 600,1 et 3 3 ἀθλητῶν scripsi auctore Meisero Ber. d. Bayr. Akad. 1905  II 159 ἀγαθῶν libri edd | ἀλλ’ scripsi καὶ libri sed eras in Ma,  Ferr om Mor Re sed „leg. videtur ἀλλ’ ὅταν vel ὅταν δ᾿“ Re  4 ταύτης HLaMa Ι τῆς] μεγάλης? 5 καὶ ante πράγματα μάτα Ma 6 παροξύναντος Ma | πρὸς τοιοῦτο scripsi τοιούτου libri sed  del Ma, edd τοιαῦτα coni Iacobs Lect 98 τοσοῦτο Gasda  7 Ante Ἕμπειρος enuntiatum quale εἰ δέ μ’ ἐρωτᾶτε, οἴαν ἐγὼ  ὀδὸν βεβάδικα excidisse coni Gasda 8 κενοτάτην ἀκούσεσθαι  Η 9 οἷον scripsi coll Aristid. 1. 1. οἴων HVCMa edd  οἴων La sed in ras ex οἷον, ut videtur, corr n οἴου et ἀπεύ- ξαιτο coni Mor Not ad Lib f VI 10 ἐπεύξαιτο Ma sed ἐπ’  ex ὑπ corr m 2 11 γυναῖκα inser Ma 2 12 οὐ in ras Ma 2  | ἐμπόρων LaMa et coni Re ἐμπορευομένων vel εὐπορούντων  (procurantium) Iacobs Lect 99 | ἦν inserui auctore εὐπορούντων  edd | οὐδοτιοὖν La οὐδὲ τῶν τεχνῶν ἐπετήδευον οὐδοτιοῦν coni  Re 13 ποιεῖν La 14 δὴ LaMa sed in hoc η in ε corr m 2 15 ἱκανὸς — 598,4 σκώμματα] „videtur hic locus scholiis in- quinatus et male distinctus, quibus sublatis expeditius legatur sic: ἱκανὸς παραστατεῖν τῷ λυπουμένῳ, συνησθῆναι δὲ πράττοντι κα- λῶς, καὶ ἐπιτεῖναι τὴν εὐφροσύνην ἐπὶ τὰ κάλλιστα τοῦ βίου  προάγειν, ὑπηρετήσασθαι τὰ μέτρια, ταῦτα δὲ ἦν πρὸς ἔνστασιν  (haec autem mediocria, quae ego amicis famulabar, erant haec,  quae nunc dicam exempli causa). ἐπιτήδειος ἦν σκώμματα —“  Re Ι περιαλγεῖν τῷ λυπουμένῳ, τῷ ἡδομένῳ συνησθῆναι Iacobs  Anth. Pal. III 599 Ι num παρηγορεῖν?
footnote 1 συλλυπηθῆναι scripsi ut coni Mor συνησθῆναι libri sed  συναλγεῖν suprascr La n Ma 2, ecld 3 προαγαγεῖν scripsi προάγειν  libri edd | ταῦτα — 4 ἔνστασιν cancellavi ut notam marginalem  lectoris cf. p. 596,5 δ᾿ HC 4 ἔνστασιν La sed σιν add n,  Ma sed ἔνστα in ras | καὶ ante σκώμματα La 5 ὧς ὀλίγοι  ante καὶ(1) LaMa Re delevi Ι ὡς ὀρχήσασθαι ὀλίγοι Ferr Mor  qui ὧς ὀλίγοι ὀρχήσασθαι coni 6 ἠβουλόμην La et Par 3017  (Boissonad. Anecd. V 19) 7 οἶος Re οἴα Gasda Ι μὴ δὲ Η  Ferr Ι τυραννίσι scripsi auctore Re τυραννίδι libri edd  8 καὶ om Ferr Mor qui δυνάσταις Coni Ι γε om La 9 πλεῖον  HV | καιρὸς La sed in marg λόγος n 10 ἢ La sed ” e “  corr s | ζῆσαι Ma sed η in ras 3 litt m 2 Ι δὲ Ma 11 τροφὴ  C Ι γυμνοὶ Ferr γυμνὸς Mor Ι καὶ — 12 ἦν in marg Ma 3  13 δὲ scripsi cum Sinteni et Gasda τε libri sed in δὲ corr  Ma 2, edd | εἶδον — 600, 10 λέγων ad versus comoediae Atticae  revocabat Kockius Com. Att. fr. III 672
marginal R IV 220
footnote 9 Il. δ 56; ζ 158; η 105; ο 165; 181; ρ 168; χ  11 cf. t. I 154, 10 16 Dem. p. 954, 7 1 μὲν om La 3 φιλογέλωτά La | φιλοπότην seripsi cum  Iacobsio Add 62 Lect 99 qui etiam de φίλοινον vel φιλόκωμον  cogitavit, et Meisero Ber. d. Bayr. Akad. 1905 II 159 φιλόποτον  HLaMa φιλόπονον VC edd φιλήδονον Cobet Coll 284 φίλ- οινον Kock 5 παρεχομένῳ HVLaMa sed in hoc ω in ου  corr m 2 6 καὶ (1) om V | „post τούτου videtur deesse“  Re, μὰ τὸν Δί’ Kock 8 πολὺ Ferr Mor qui πολλοὶ coni  10 ἐκείνω La Ι ἔσχε HV 11 τὰ om Ferr Mor | αὐτοῦ libri  edd | προὐτίθει reposui e libris sed υ inser la n, coll t. II 454,9;  IV 88, 19 προὐτίθη edd | πρὸς ἡδονὴν scripsi τῶν ἡδονῶν  libri sed del Ma 2, edd καθ’ ἡδονὴν Kock 13 δὲ Ma | δὴ]  δὲ LaMa sed in utroque eras 15 οὐδὲ Ma | εὐπορήσω La sed  ν post ω eras, Ma sed εὑ ex ἁ corr m 2 16 κηδευτὴς Η  17 καθ’ del Ma 2 | ἡμέραν scripsi auctore Kockio ἡμᾶς HCLa  edd ἡμῶν VMa Ι τροφῆς Ma sed o in υ corrm 2 τρυφῆς La
footnote 7 Plat. rep. II p. 373 C 10 Luc. paras. 1 sq. 19. Luc.  l. l. 5 1 μυρίοις Ferr Mor qui μύροις coni 3 ἡμῖν La sed in  ἤμην corr n 4 παρεχόντων scripsi e LaMa ut coni Re  παρέχων HVC edd 7 μόνων HVMa sed in hoc ω in ο corr  m 2 11 ἔφερέ μοι La sed μοι inser s, Ma sed ex ἔλεγος corr  m 2 Ι αὐτῆς libri edd 12 θάλασσα scripsi ex HLaMa θά- λαττα VC edd 13 θηρῶντες scripsi e La οἱ θηρῶντες ἐθή- ρων) Ma θηρεύοντες HVC edd 15 δ’ inserui om libri edd  I τὸ om Mor Re 16 καὶ om La Ι πάνυ scripsi auctore Co- beto Coll 284 πολὺ libri edd | χαρίεν Η 18 „sententia postu- lat περὶ τἀς ἀποθήκας περιιέναι per cellas“ Re  μαγείρους ἐπιέναι Iacobs Lect 99 at cf. p. 601, 2 19 καὶ —  601,1 ἐπαινεῖν om V
marginal R IV 221
footnote 1 Eupol. Κολ. II 484, 146 Μ (I 301, 159 K) 1 χαρίσασθαι Ma 2 τούς μαγείρους — 3 θεραπεύειν ab  hoc loco aliena censet Gasda 4 μόλις scripsi μόνος μόνον  C) libri edd θεραπεύειν μόνον. ὄρθρος Iacobs Add 131 μόνος)  et App Pors Adv 297 4 δ’ VLa 5 ἀπαγγεῖλαι La sed ἁ  ex ἑ corr s 6 δὲ Ma 7 περὶ scripsi ἐπὶ libri edd sed „ἐπὶ  aut prorsus delendum aut cum ἐν est “ Re ἔτι Iacobs  Lect 99 Ι ἔξοι Μa 8 ἀπήγγελλον scripsi ex HVCMa ἀπήγγελον  Ma edd 9 ἐνεπιμπλάμην Ma sed λα e ρα corr m 2 10 προ- τέρων scripsi πρώτων libri edd 11 καὶ — 12 ἐταμιευόμην cor- rupta censet Gasda Ι διατηρήσων LaMa sed ω in ει corr La 3  Ma 2 | περιόντα scripsi cum Sinteni προιόντα libri sed προ in  περ coit La n, in (??) Ma 2, edd 14 δὲ Ma | λαμπρῶς scripsi  ex HVC λαμπρὸς LaMa edd 15 ἐπανῄειν scripsi e VLa  Ma Par 3017 cum Boissonadio Anecd. V 33 Gasda Cobeto Coll  284 ἐπανίην HC sed in hoc ιην in ηειν corr f, edd 16 μὴ  scripsi e La μὴ δὲ Η μηδὲ VCMa | μοι om Ma Ferr
footnote 1 cf. p. 606, 12 2 Xen. conv. 6, 6 11 Opp. cyn. I 118 1 ἐμπιπλάμενος libri edd cf. p. 601, 9 2 ἐχρῆν scripsi  ἐξῆν libri sed in ἐχρῆν corr La n Ma 2, edd 4 ἄριστον —  5 πολυτελῶς delenda censet Gasda 5 οὐκ ἐδεδοίκειν Ma sed  ex οὐ δεδοίκειν corr m 2 7 δὲ inserui e libris om edd  8 εὔφρων Ferr εὖφρον Mor qui εὔφορον coni 9 ὥστε in- serui cum Gasda om libri edd | πολλὺν πολὺν Mor) ἀχρήστου  Ferr Mor qui ἀρίστου coni 11 εἶχε scripsi ἔχει libri edd  εὐκραεῖς La sed εῖς in ras n 12 πέττειν Ferr Mor | πλέον  Gasda 13 ἐπεγίγνετο LaMa Ι τὸ inser Ma 3 | ἐπερρώννυσι Η  ἐπερρώνυσι V ἐπιρρώννυσι La ἐπιρρώνυσι Ma 14 πραγ- μάτων Ma sed αγμ inser m 2 | ἦγεν scripsi ex HVMa ἤγαγεν  La ἄγειν C edd | ἐν μὲν scripsi e La cum Sinteni ἔν με HV  CMa edd 16 παράστασις La sed τα supra στα n Ι ἂν can- cellavi cum Iacobsio Lect 99 coll p. 603, 1 Ι ἑωθινῶν ἀρίστων  scripsi auctore Re ἑωθινὸν ἄριστον libri edd ἐξ ἑωθινοῦ ἀρίστου  Iacobs
marginal R IV 222
footnote 4 cf. ad p. 579, 9 | Her. III 40. Dionys. com. ΙΙΙ 555, 3 M  (II 428, 1 K). Plat. Menex. p. 242 A. Stob. floril. 38 8 Dem.  p. 240, 11; 660, 7. Lnc. tyrannic. 4 1 ἔδει inserui ex HVLaMa quod subaudiendum censuit  Re om C edd Ι ὅτι inser Ma 2 | ἀρίστου ante καιρὸς excidisse  coni Mor Not 2 ἱκανός scripsi auctore Iacobsio Add 368  App Pors 325 Lect 99 ἱκανόν) καιρός libri Ferr Mor quod  delevit Re 3 Ἀλλ’ — 5 ἄγαν praemissis verbis ὡς καὶ Λιβά- νιος citat auctor libelli de constructione verborum ed. G. Her- mann de emend. rat. gramm. p. 376,21 6 φιλεῖ scripsi e Par  3017 (Boissonad. Anecd. IV 396) ὀφείλει HVCMa sed in hoc ὀ  eras, edd ὀφειλεῖ La Ι γίγνεσθαι La 7 καθ’ ἑαυτὸν LaMa 8 ὁ ante τρόφιμος inserendum coni Iacobs Add 367 | ὁ  πάντα scripsi cum Iacobsio Add Lect 99 πάντα La sed α(2)  in ras s, Ma πάντων HVC edd sed πάντα ἦν coni in marg  Mor, πάντα ὢν Not πάντων ἄριστος Re πάντ’ ὤν Cobet Coll  284 9 num δεικνύς? at cf. p. 589 not. 2 10 πολυτελής  scripsi auctore Iacobsio Add App Pors Lect πολίτης libri edd  ὁ πολίταις πλουτῶν, οὐχ ἦττον δὲ καὶ ἐμοὶ ὅλην coni Re Ι  ἥττων La 12 δ’ ἑαυτῷ scripsi e C δὲ αὐτῷ HVLaMa edd 14 γυμνασία Η Ι signum interrogationis posui comma  libri edd 15 τίς Η Ι μισεῖ inter θεοί et σὺ La s 16 σὺ
marginal R IV 223
footnote 1 num τυγχάνει ὢν? 2 ὧς delendum censet Sintenis Ι  γυμνὸς Laf | εἰκῆ πλουτεῖ, νόσῳ ἀλοῦς χαλεπωτάτη ὑφ’ ἧς οὐδὲ  τὸ τῆς συμφορᾶς προιδέσθαι μοι δοκεῖ coni Re εἰκῆ πλουτῶν  καὶ ἄλλως lacobs App Pors 325 Lect 99 3 πλουτῶν La sed  ῶν f | ἣν om HVLaMa | ἄλλοις scripsi ex HVLa sed in hoc  del f, Ma ἄλλους C edd Ι νόσον Laf 4 τὸ] οἱ HV οἷ Laf Ma  Ι φορᾶς LaMa 5 ἀλλ’ Laf Ι ἐπῆκται scripsi auctore Re  ὑπῆκται libri sed ὑ Laf, edd 6 „fort. ὑφ’ οὖ δοκεῖ aut ὥστε  δοκεῖν“ Re Ι εὐδαιμονεῖν La sed εὐδ f 7 ὄντως Iacobs Lect  99 Ι κάκιον delendum censet Iacobs f ἣ inserui auctore Re om  libri edd 8 ἑαυτῶ om Mor 9 μὲν inserui om libri edd 10 ἠρεῖται V 11 χροιάν La | τῷ βλέμματι scripsi ex Η  VLaMa τὸ βλέμμα C edd 12 τῷ σώματι scripsi ex HVLa  τὸ σῶμα C edd om Ma 14 ἀποδέδυται scripsi ex HVLa  sed in hoc δέδυ in δύε corr s ἀποδύεται CMa edd 15 λιμῷ  inserui e CLaMa om HV edd | καίτοι scripsi καὶ τὸ libri  edd | αὐτῷ scripsi ex HVMa αὐτὸν CLa edd αὐτάρκους σίτου  μεταλαβεῖν αὐτὸν (sc. δεῖν se oportere capere cibi quod satis sit)  coni Re
footnote 2 Arist. ran. 931 5 Ter. heaut. 81 7 Arist. nub. 103  cf. t. 1 249,6 c. schol.; III 91, 12 sq. 16 Plat. Phaed. p. 67 E 1 κἂν LaMa Ι punctum post ἐλθεῖν inserui et καταδαρθὼν  scripsi καταδαρθεῖ ΗV καταδαρθῆ LaMa καταδαρθεῖν C edd  Ι τὸ πολὺ Gasda 3 πῶς? | signum interrogationis posui ex Η  colon reliqui libri edd 4 ἡμῖν scripsi ὑμῖν libri edd | ἑτέροις  coni Re | διαφθείρειν ὄντες scripsi auctore Re διαφθείροντες  libri edd 7 λέγω scripsi cum Iacobsio Add 103 Anth. Pal. III  686 et Meisero Ber. d. Bayr. Akad. 1905 II 159 coll Arist. 1. 1.  γε HVLa edd sed tollendum censuerunt Re et Cobetus Coll  285 τε CMa | ἀνυποδήτους scripsi e La coll Arist. 1. 1. cum  Iacobsio et Cobeto ἀνυποδέτους HVCMa edd cf. Phryn. lex.  s. v. cum nota Lobeckii p. 445 8 ἀπεύξαιτ’ scripsi e LaMa  ἀπεύξαιτο C edd ἀπεύξεται HV 11 δὲ HV om Ferr Mor  qui inserendum coni Ι εὐδαιμονεῖ scripsi ex HVLaMa εὐδαι- μόνει C edd 12 τὸ ante μὴ La Ι „malim μόνοι“ Re Ι μὴ μόνον  αὐτοὶ Gasda Ι ὅτι Ferr Mor qui ἔτι coni 13 τοῖς ἴσοις Ma  sed ς ἴσο in ras m 2 14 πείθειν scripsi ut coni Re πείσειν  libri edd 15 „fort. καλῶς ποιοῦσα“ Re 16 παροινίαν La  sed α supra οι s Ι τεθνηκότας scripsi e Ma ut coni Re τε  θνήσκοντας HVCLa edd
footnote 7 cf. IV 167, 23 R; t. I 151, 6 15 Philostr. Ap. Tyan. VI  11 p. 220, 10 K. hypoth. 1 ad Arist. ran. cf. Blomfield Aesch.  Pers. praef. p. XXII sq. 1 μου LaMa 2 ὑμῶν Ma | προπίνουσι scripsi auctore Re  προπίνοντι libri sed αἰτεῖν ἀνανγάζουσι (sic) suprascr Lay, edd  Ι αὐτοὶ La s 3 καὶ πρὸ ἡμῶν inserui ex HVLaMa om C  edd | οἴ γε Η 4 δὲ Ma 5 εὐτρέπιστο Ma | ὁ δ’ scripsi  ὅδ’ ὅδ’ La) libri edd 6 ὁ δ’ scripsi ὅδ’ HCMa edd ὅδ’  La οὐδ’ HV 7 λιμόν τε ἔχων La | αὑτὸν scripsi αὐτὸς Η  V αὐτοῦ La sed in αὐτὸν corr n, Ma ὅτε C edd | κατέβαλεν  scripsi e LaMa κατέλαβεν HVC edd 9 ἄρτου scripsi ut coni  Re αὐτοῦ libri αὐτοῦ C) sed in αὐτῶ corr La n et ἄρτου μικροῦ  suprascr y, edd 10 καὶ scripsi κἂν libri sed καὶ suprascr  La s, edd 11 παρ’ Re γὰρ libri edd 12 ὁ δ’ scripsi  cum Iacobsio Lect 99 ὅδ’ libri edd 13 ᾔει scripsi e La et  Par 3017 cum Boissonadio Anecd. V 33 εἴη HV ἴη CMa edd  | τῶν scripsi ex HVLa Par 3017 cum Sinteni τὸν CMa sed  in hoc in ras, edd τὸ coni Mor Not | κενῶν V | ἐλεεινότερον  καὶ φαυλότερον scripsi ἐλεεινότερος (sed ἔρος in ras La) καὶ  φαυλότεροι (sed ι in ’ν corr Lay) ἐκείνων La Par 3017 om ΗV  CMa edd 14 δείπνων HV
marginal R IV 225
footnote 11 Biant. dict. Diels Fr. Vorsokr. II 522, 6, 1. Auson. lud.  sept. sap. 62. Gerhard, Phoinix v. Kol. p. 273 2 ἕως scripsi anctore Re ὡς libri edd 3 κατ’  scripsi coll. 1. 5 et 17 καθ’ ἑαυτὸν αὑτὸν La) libri edd 4 δὲ Ma  I ὑπανήλωτο La sed α supra η y ὑπανάλωτο Ma 6 ὁ om V  LaMa 7 γε La 8 punctum (2) posui signum interrogationis  libri edd 10 ποῦ scripsi ποῖ libri edd πῆ e Par 3017 Boisso- nade Pachym. p. 98 not. 2 13 ἀλλὰ LaMa Ι ὁ om La Ι πράτ- τουσιν Ma sed ν add m 2 14 τίς HLa Ι ἐπέτρεψεν Η Ferr  Mor 15 ἀπήγαγεν La 16 φιλάνθρωπά scripsi e Ma  φιλάνθρωπόν HVCLa edd | τινα om La τι coni Re 17 τὸ La  Ma cf. p. 603,7 18 ὄ Η ὃ La | δὲ CMa edd | μᾶλλον δὲ κατε- γέλασε om La 19 ὄ Η ὃ La Ι οἰμώξῃ; scripsi e Par 3017 cum  Boissonadio Choric. p. 19 not. 1 οἰμώζει HVCLa edd οἰμώζεις  Ma sed εἰς del et η suprascr m 2 οἰμώξει; coni Re et Cobetus Coll  285 Ι σοί, τί δ’ ἐμοὶ scripsi τί δέ μοι καὶ τί μοι HVCMa τί μοι  La Ferr Mor τί δέ μοι e Par 3017 Boissonade τί Re τί σοι Cobet
marginal R IV 226
footnote 2 Dem. p. 1258, 2. Xen. anab. II 4, 11 5 cf. t. I 101, 16;  t. IV 671 11 R 11 cf. t. V 535,9 1 μόνον οὐ HC 3 τἀς La 4 ἠξίουν scripsi auctore  Gasda ἀξιῶν libri edd 5 ἐν scripsi auctore Cobeto Coll  Misc 146 6 ἔλεγεν La Ι „sic distinguo et lego: ἔλεγε καὶ τρίτον  καὶ προσιόντα“ Re Ι χαλεπῶς La sed σ add n 7 δὴ scripsi  δὲ HV δὲ δὴ LaMa ἐγὼ C edd | χρήσωμαι scripsi χρὴσο- μαι libri edd Ι ἐμαυτῷ scripsi e LaMa sed in hoc μ suprascr  m 2 ἑαυτῷ HVC edd | μὴ δὲ Η Ferr μὴ δὴ LaMa 8 τίς  Η | μὴ δ’ Η Ferr 9 τίς HLa Ι ἕτερος inserui e LaMa Par  3017 cum Boissonadio Anecd. V 422 om HVC edd 11 ἡδο- νὴν Ferr Mor 12 ἑτέρω coni Mor 17 με scripsi μὲν libri  edd 18 ὀνειροπολοῦσαν scripsi cum Gasda ὀνειροπολοῦσα  HVC edd ὀνειροπολοῦσαν Ma sed in ὀνειροπολοῦντα corr m 2  ὠνειροπόλουν La sed in ὀνειροπολοῦντα corr n | καὶ ante  κατηφὴς La | καὶ ἡμέρα καὶ inserui auctore Re om libri edd
footnote 4 cf. p. 653, 8; t. I 128, 12 c. schol. 12 Plat. Phaed. p. 67 E 1 ἀναλύοντας inserui e libris cum Boissonadio Anecd. IV  477 om edd | τόπου Ma sed πότου suprascr m 3 | καὶ ante  διαρρήγνυμαι inser Ma 2 2 τῶν φθόνων Ma sed in τῷ φθό- νῳ corr m 2 4 δὲ HVC edd | ἐπενέβη scripsi cum Gasda et  Cobeto Coll 285 coll 1. 1. ἐπανέβη libri edd 6 πράττοντα  scripsi auctore Re πράττοντι libri edd 8 τὴν — 9 μοι om  Ferr Mor Ι τὸ inser Ma 2 9 προπίνει Re προτείνει libri  Ferr Mor qui προτείνειν τῇ τύχῃ coni | τὴν inserui e La et  Par 3017 (Boissonad. Anecd. V 148) om HVCMa edd 10 μή- τηρ La sed μ’ in ras n | οὐδὲ Ma 11 οὐ(2) scripsi e Ma οὔτε  La ἔτι HVC edd „fort. lep. οὐ συγγενής οὐδ’ εἰς ἔτι φίλος  ἐστὶ λοιπός“ Re οὔτε φίλος ἔτι Iacobs Lect 99 | λοιπός scripsi  ut coni Re et Iacobs λοιπόν VLaMa et coni Mor λυπῶν Η  C Ferr λιπών Mor Re | δὲ Ma 12 τῷ coni Gasda | δὴ om  La δὲ Ma Ι ἶσον HMa Ferr ὅσα La | „fort. καὶ οὗτος τέθνηκέ  μοι aut οὗτος κατατέθνηαέ μοι“ Iacobs Lect 99 13 τίς —  14 ἑαλωκώς; labem contraxisse censet Gasda
marginal R IV 227
