@node
@author=Philo Judaeus
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Paul Wendland
@filename=tlg0018.tlg018.opp-grc1
@funder=European Social Fund Saxony
@principal=Gregory Crane
@publicationStmt=University of Leipzig, tlg0018.tlg018.opp-grc1.xml.
@respStmt=Digital Divide Data, Corrected and encoded the text, Gregory Crane, Editor-in-Chief, Perseus Digital Library, Matt Munson, Project Manager (University of Leipzig), Annette Geßner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor, Greta Franzini, Project Manager (University of Leipzig), 2013-2014, Frederik Baumgardt, Technical Manager (University of Leipzig), 2013-2015, Simona Stoyanova, Project Manager (University of Leipzig), 2015, Project Assistant (University of Leipzig), 2013-2014
@sourceDesc=Philonis Alexandrini Opera Quae Supersunt, Paul Wendland, Philo Judaeus, Typis et Impensis Georgii Reimeri, Berolini, 1898, 3, Hathi Trust.
@sponsor=University of Leipzig
@title=De mutatione nominum
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T15:05:10Z

16390	marginal p. 578 M.
footnote 1 Ἁβραὰμ per totum librum ΑΒ ἐννενήκοντα codd., item lin. 3 2 ὁ θεός σου Β: θεὸς σός Α et .sic § 18. 27. 29. 31, sed ὁ θεός σου LXX et Philo vol. II p. 54,9 et vol. II p. 180,29 Mang. 5 καὶ #x003E; coni. Mang. 7 ἀπάρχονται ἑτέρας Β ἑκατοστόν Mang.: ἑκατὸν codd. 7. S ante προκοπῆς ras. 3 litt. in Β, καὶ ex Coisl. 43 add. Mang. 13 prius τὸ Β: τὸν Α 14 μὲν οἱ scripsi: μόνοι codd.
footnote 1 post φ ras. in Β 8 νοήσῃς τὸ ὄν, ὅπερ πρὸς Hoeschel 9 ὄργανον Mang.: ὁρᾶν codd. 10 φαντασιωθῆναι Cohn: φαντασιασθῆναι codd. 11 γὰρ ex Coisl. 43 et codice Oxon. Coll. Novi 143 Mang.: οὑν ΑΒ ἔστιν] ἦν Hoesch. νοῦν scripsi: ἰσχύν codd. Μωσῆς codd. 12 καὶ θεόπτης secl. Cohn, καὶ θεοπρόπος coniciebam αὐτόν φασιν Β 13 θεῖοι D: om. codd. καὶ ἀσώματον D: om. codd. 15 ἀγαθὸν D: om. codd. 16 τῶν ἐλπιζομένων Hoesch. 18 γνωστῶς] εἰ s. s. Β, ἵνα add. Richter ὅμως D: ὁμοίως codd. 19 θνητῶν Mang.: θνητῷ codd. 20 τῶν addidi 12—19. 158,2 DC fol. 44r ἐκ τοῦ περὶ τῶν μετονομαζομένων DR fol. 55v τοῦ αὐτοῦ ἐκ τῶν μετονομαζομένων DH fol. 65v τοῦ αὐτοῦ: τὸν Μωυσῆν φασιν οἱ θεῖοι χρησμοὶ εἰς τὸν γνόφον εἰσελθεῖν, τὴν . . . . . . διὰ πάντων ἐρευνήσαντα (διερευνήσαντα DR) τὸ μόνον ἰδεῖν μὴ ἱσχῦσαι· ἐπειδήπερ οὐδὲν εὕρισκεν (ηὕρισκεν DR) οὐδὲ ἐμφερῆ τινα ἰδέαν DC DH) ἐν τῷ ἐλπιζομένῳ . . . . . . . . προθέσεως τῷ μὴ πεφυκέναι ὁρᾶσθαι τὸ ὄν θεόν DR). postrema τῷ—ὄν olim in textu lin. 6 addebam, nunc ex p. 158,2 fluxisse puto.
footnote 3 ἀκατονόμαστον D 4 τίς γὰρ D: ἐστι. τίς codd. 5 ἢ fort. del. 7 πρὸς ἀλήθειαν ante alt. τῷ add. codd., om. D 8 τί om. DRD2C τοῦ D: om. codd. ὅτι om. D 9 ἴσον τῷ] εἰς ὢν τὸ DR 10 ἀμοιρῆσαι D (Mang.): ἀφαιρῆσαι codd. τῶν D: om. codd. 11 ἀρρήτου coni. Mang. δίδωσι D (Hoesch.): δίδωμι codd. καταχρήσασθαι D καταχρῆσθαι ὁ ἀκατονόμαστος ὢν conicio ἄν D (Hoesch.): ἐν codd. ὁ ὢν D: om. codd. τοιούτω D: τῶ κυρίω codd. 12 τελειότητος D: ὁσιότητος codd. 13 Ἰακὼβ D: καὶ Ἰακὼβ codd. μου D: om. codd. 14 ἄν D: om. codd. 15 πέρα D: πέραν codd. 16 καὶ πάλιν—ἀγενήτοις om. D κατὰ χρῆσιν 17 θνητὴν D (Mang): ὠνητὴν codd. 17. 18 ἐλθοῦσιν εἰμὶ καὶ πράγματι D 18 προσερυόμενοι D, προσχρώμενοι coni. Mang., προσεχόμενοι coni. Cohn 20 τὸ scripsi: τό δν DR, ἀνθρώπων DC (fort. scrib. ἀνθρώπων τὸ), om. codd. ὄνομα D: ὀνόματι codd., ὄνομά τι Hoesch. κύριον D (Hoesch.): κυρίω codd. 20. 159,1 ὤφθην—αὐτῶν καὶ D: om. codd. 2—4 DC fol. 224r τοῦ αὐτοῦ ἐκ τοὐ περὶ τῶν μετονομαζομένων DR fol. 222 v: τί θαυμαστόν . . . . εἶδεν. 7—9 pergit DC DR I. c.: οὐχ ὁρᾷς—λέγεσθαι. 7—18 DC fol. 224 r τοῦ αὐτοῦ ἐκ τοῦ περὶ τῶν ἐν γενέσει ζητημάτων: φιλοπευστοῦντι τῷ προφήτῃ τοῖς περὶ—κοσμοῦνται (sic). 20—129,2 pergit DC DR post ad lin. 7—9 allatum: περὶ δὲ τοῦ μηδενὶ—αὐτοῖς.
footnote 2 κύριον D: om. codd., κύριος ex LXX Hoesch. 5 τὸ ὂν Α: ras. 3 litt. Β ἐστι Α οὐδ’ Β ὑπηρετοῦσαι conicio 5. 6 &lt;τὸ&gt; κύριον ὄνομα conicio 7 ἀρρήτῳ coni. Mang. ἐπιστάτῃ] παλαιστῇ conicio (v. § 44) 8 τοῦτο codd.: om. D 9 καὶ οὐ—κύριον om. D σοι D: om. codd. ὠφελεῖσθαι φησὶ DR 10 κατὰ Coisl. (v. Mang.): καὶ ΑΒ, om. D εὐφημίας DR: εὐφημήσεις DC, ὑφηγήσεις codd., mg. DC γενητῶν Β2: γεννητῶν AB1 11 μηδ’ conicio, μὴ γοῦν coni. Cohn 12 πρεσβύτατον D (Mang.): πρεσβύτερον codd. καὶ D: om. codd. οὐ ῥητός] ἄρρητος DR 13 καὶ μένει ἄρρητος ἄρρητος om. DR) καὶ ἀπερινόητος D καὶ ἀκατάληπτον scripsi: καὶ ἀκατάληπτος D, om. codd. 15 πάντων conicio 16 &lt;ταύτης&gt; τῆς 17 αὐτὸ Β (Mang.): αὐτὸν Α 19 τά κόσμου τὰς Mang., τὰς ἐν τῷ κόσμῳ δραστηρίους περιεῖπεν conicio περιέπων Mang.: περιιππεύων codd. 6—10 pergit DCDR l. c.: οὕτω καὶ Ἰακὼβ μετὰ τὴν πάλην μαθεῖν ἐθέλων ἤκουσεν ἤκουεν DC.) ἵνα τί—εὐφημίας. 11—13 Dc fol. 44v, DR DH post locum ad p. 157,12 allatum: τί διαπορεῖς, εἰ—ἀκατάληπτος. Mang. falso fragmentum, quod in D sequitur ex libro praem. et poen. 6 (II 414,25—32 M.) depromptum, nostro libro inserendum esse conicit.
footnote 1. 2 &lt;εἰ&gt; καὶ ὀψιμαθὴς ἢν, οὐ conicio ἐφαντασιώθη Cohn: ἐφαντασιάσθη 4 τὸν] τὴν Α ἀκροατὴν καὶ om. Α 5 ἄν addidi τῶν (del. δὲ) conicio 7 post οὗ add. ὁ Α, ras. in Β 11 ἱδρυσάμενος] δ ex corr. Β 11. 12 κύριον καὶ secl. Mang. 14 χρισθέντων Α δὲ] γε conicio 15 ἐν ἀρχῇ, sc. orationis dei] &lt;„κύριος ἔκτισέν με ἀρχὴν ὁδῶν αὐτοῦ εἰς ἔργα πρὸ τοῦ αἰῶνος ἐθεμελίωσέν με&gt; ἐν ἀρχῇ (Prov. 8, 22) coni. Mang. 16 Φαραὼ Β 17 Μωσῆς codd. 18 τὰς χεῖρας om. Β 19 ὁ om. Β κύριον Α 24 γεννητὸς codd. D (Ant. Mel.) 25 ἐπὶ codd.: εἰς D (Ant.) εὐρύνας om. DR (Ant.) 24—26 DP fol. 130 (ἐκ τοῦ περὶ τῶν μετονομαζομένων) DR fol. 159r τοῦ p. 434 Φίλωνος Anton. Mel. II 21 col. 1063: κύριος γεννητὸς—Ηγεμών.
footnote 1 αἴρεται scripsi: αἱρεῖται codd. νουθεσίαν coni. Mang. 2 ἀφρόνων A: ἀμφοτέρων Β 3 καθὰ coni. Cohn 4 σὸς &lt;καὶ&gt; &lt;καὶ conicio ὁ addidi 5 καὶ transpos. B 6 δεκαλόγοις codd. ἐγὼ—σου om. Β 7 ὑμῶν Hoesch.: codd. 13 ὡς fort. del. Μωυσέος codd. 15 ἰσορρεποῦς Β 15. 16 ἀντιδόσεως, ἀξιωθῆναι θείας προνοίας αὐτόν conicio 18 δὴ A: δὲ Β 18. 19 διάνοια et αὐτὴ conicio 24 &lt;μένον&gt; ἐν conicio 28 πρός τι ὡσανεί transpon.
footnote 2 &lt;σός&gt; conicio &lt;τοῦ&gt; αὐτοῦ conicio 3 φαύλην 5 μόνον Hoesch. αὐτὴ scripsi: αὐτὴ codd. 7 δέξεται Β, ex corr. A: δέξηται prius Α, δέξαιτο conicio 9 μόνον Hoesch. ἐστιν ἐκεῖνος Β 10 μόνου &lt;θεοῦ&gt; vel &lt;τούτου&gt; μόνου conicio 11 ἀτῶ Β εἰσάγει coni. Mang. 12 μόνων conicio οὕτος] τούτων conicio 13 τῶν ἐκτὸς ἄφθονον Markland: ἐκ τοῦ ἀφθόνου codd. 15 ἀθληταὶ &lt;οἱ&gt; conicio alterum τὸ vid. secl. 18 διάνοιαι διανοία codd. 19 καταλύεται Mang.: κατακλύζεται codd. 20 καὶ vid. del. 23 ἄν addidi 23. 24 εὖροι (corr. ex εὕρη) τἀγαθὸν A: εὕροιτ᾿ ἀγαθὸν Β, εὕρῃ τὸ ἀγαθὸν V 24 διαλαβών A πρὸς add. Mang., sed fort. lin. 25 ἐπελθὼν leg. 26 Stoici: Zeller III 1 p. 253. 254. 27—263,2 DC fol. 46v (post locum vol. I p. 247,12 allatum) DR fol. 24r τοῦ αὐτοῦ περὶ γενέσεως Ἄβελ et fol. 67v (post locum ad vol. I l. c. allatum): ἀδύνατον ἀπ’ ἀρχῆς . . . ἀνυπαίτιον εὑρεῖν τητῶ σώματι ἐνδεδεμένον. 4—6 DR fol. 77r τοῦ αὐτοῦ ἐκ τῶν μετονομαζομένων: μὲν—συνέρχεσθαι. 14—20 DP fol. 305v (post verba κοινωνικὸν καὶ οὐ μονωτικὸν ζῷον ὁ ἄνθρωπος ad nostrum librum relata; v. Harris p. 105. 92. eadem praecedunt in DR) DR fol. 253v τοῦ αὐτοῦ: τῷ Ἀβραὰμ εἴρηται ἐκ προσώπου—πάντα. p. 164,2. 17—19 cf. ad p. 116, 18.
footnote 1 εὑρεθῆναι conicio (cf. D) 2 συνδεδεμένον DR fol. 24 4 σοφὸν D 5 δὲ om. Β 6 οὐκ ἐθέλει D: οὐ θέλει codd., οὔ φιλεῖ coni. Mang. 12 τιθασσοῦ codd. 15 εὐαρέστει D: εὐαρεστήσει ΑΒ, in εὐαρεστήσῃ corr. B, εὐαρεστήσεις V τουτέστι D ἐμοὶ μόνῳ D: μόνω ἐμοὶ AB μόνον Mang. ex Cantabrigiensi Coll. S. Trin. B. 9. 6 17 ἐλεῶν om. D 18 πάντας D 19 εὐαρεστήσεις D: εὐαρεστεῖς codd. δὲ D εὐαρεστήσεις D: εὐαρεστεῖς codd. 25 περιέχει Mang.: παρέχει codd.
footnote 1 Μωσῆς codd. 3 5 φανῆναι θεῶ γενήσεται ἐπάξια DR 4 καὶ τοῖς χρωμένοις εἴωθεν ἀρέσκειν conicio (cf. § 40), τοῖς εἴσω καὶ ἔξω ὁμοίως εἴωθε καθαρεύειν coni. Mang., καὶ ἐκτὸς ὁμοίως εἴωθε χωρεῖν coni Cohn 10 τοῖς ex τῆς corr. Β 11 ἐν seclusi 12 κἀκεῖνο conicio 13 αὐτὸ Β, αὐτοῦ Cohn 14 ἤσκησας Β δυνατός A2: δυνατῶς Α1, δυνατὸς εἶ B, sed ο et ει ex corr. 15 τὸ καθ’ ἑκάτερον φησὶν DH τάξιν] ἀξίαν D (om. DH) καὶ τὴν πρὸς] τήν τε πρὸς DM D1RDLDH 15. 16 τὸ ἀγένητον καὶ Om. DP 16 ἀγέννητον D2RD1LDH γενόμενον DPD2R: γεννώμενον codd., e corr. D2R, γεγεννημένον D1RD1L, γεγενημένον DMD2LDH 16. 17 εἰ—εἰπεῖν om D2R 17 θεοῦ om. D1RD1L μεθορίου συνόλως D2R, μεθόριον συνόλως τε DP: μεθόριον οὖσαν μεθορίου οὔσης man. recentissima in A, coni. Hoesch.) ὅλως τε ΑΒ, μεθόριον καὶ καθόλου DMD1RDLDH 18 ὀπαδὸν] σπουδαῖον D1RDLDH, καὶ σπουδαῖον DM εἶναι] ἐστιν DP μέλλει ADMDRD1LDH γάρ D: δὲ codd. πατρὶ] περὶ DMD1RDL 19 γινομένου D1RD1L, γεγενημένου DM 2. 3 pergunt DPDR τοιαῦτα οὑν πρᾶττε –ἀποδέξεται. pergunt lin. 15. 15—165,3 DM fol. 22r DL fol. 28r et 59r DH fol. 113v DR fol. 24r Φίλωνος ἐκ τοῦ (τῶν περὶ (τῶν add. DH) μετονομαζομένων: τὸ καθ’ ἑτέραν ἀξίαν—τῷ δεσπότῃ (ἐν καλοκαγαθίᾳ D2L). 15—19 pergunt DPDR post locum ad lin. τό γὰρ καθ’ ἑτέραν ἀξίαν εὐδοκιμῆσαι—γενομένου. 18. 19 cf. librum „Philos Schrift ϋber die “ p. 43.
footnote 1 ὁ θεὸς καὶ D: καὶ φίλος codd. τοῦ DRDLDH: om. oodd. DM 2 ἔμενεν codd.: ἔμεινε D, ἔμεινεν V οὐ μεταβαλών om. D οὖν D: γοῦν codd. ἢ ὅτι D: ὅτι codd. 3 οὐχ ἐψόμεθα D: οὐκ ἐφεψόμεθα codd. 10 πρεσβύτατον conicio, πρῶτον Mang. 12 διαμαρτάνον coni. Mang. 13 κατορθοῦν conicio 14 κἄν &lt;εἰ&gt; coni. ἐστὶν] γένηται conicio (cf. LXX Alex.) μὲν &lt;γάρ&gt; conicio 15 τὴν ψυχήν DK Barb.: ἡμῶν τὴν ζωήν DCDR 15. 16 παντελῶς AD: καθαρῶς Β, καὶ παντελῶς nag. Β 17 μέν πως εἰκός DCDR 19 ζητεῖ τις] ζητεῖς conicio, ζητεῖ τίς coni. Cohn 20 εὕρῃς scripsi: εὑρήσεις codd. ‘ἀνατροπαὶ D; ἀποτροπαὶ codd. 2. 3 Platonis Tim. p. 29 DE. 14—17 DC fol. 47r ἐκ τοῦ περὶ τῶν DR fol. 67v68r ἐκ τοῦ περὶ τῶν κατονομαζομένων: ἄπειρα τὰ καταρρυπαίνοντα . . . . . . ἅπερ οὐκ ἔνεστιν ἀπολούσασθαι παντελῶς· πάντως γὰρ λείπονται κηλῖδες τινὲς τῷ θνητῷ, ἅς ὑπολωφῆσαι μέν πως εἰκός ἐστιν, ἀναιρεθῆναι δέ εἰσάπαξ ἀμήχανον. — DK fol. 93r et 116r ἐκ τοῦ περὶ τῶν μετονομαζομένων: πολλὰ καὶ ἄπειρα τὰ τοῦ κόσμου κακά καταρρυπαίνοντα, tum plane concinit cum codd., nisi quod fol. 93 κῆραι· λοφίσαι μέν γὰρ εἰκός et εἰς ἅπαξ scribit, fol. 116 κῆραι ἅς λοφίσαι μέν εἰκός. desinit ut DCDR. —Barberinus I 158: τὰ καταρρυπαίνοντα τὴν ψυχὴν ἐκνίψασθαι καὶ ἀπολούσασθαι παντελῶς οὐκ ἔστιν. ἀπολείπονται γάρ ἐξ ἀνάγκης παντὶ θνητῷ συγγενῆ σκηνώματα. λωφῆσαι μὲν γὰρ αὐτὰ εἰκός, ἀναιρεθῆναι δὲ εἰς ἅπαξ ἀδύνατον. 20. 166,1 pergit DCDR l. c. ἀγαπητὸν γὰρ οὗν DC) αἱ τῶν κακιῶν ἀνατροπαί, ἐπεὶ ἡ (ἡ om. DR) ἀρετῆς κτῆσίς ἀδύνατος ἀνθρώπῳ τῷ (τὸ DC) καθ’ ἡμᾶς 7. 8 DR fol. 136v DH fol. 199r τοῦ αὐτοῦ: διαθῆκαι ἐπ᾿– χάριτος. 19–22 DR fol. 125r Φίλωνος ἐκ τοῦ περὶ τῶν μετονομαζομένων: ὁ μηδέποτε–αὐτῷ. sequuntur verba κάλλιστα γοῦν εἴρηταί τινι· βέβαιος ἴσθι καὶ βεβαίοις χρῶ φίλοις.
footnote 1 ἐντελὴς D: παντελὴς codd. 4 δ᾿ B τὸν δὲ ᾑρημένον et ἀπολήψεσθαι conicio 7 ἀξίων] ἀξί in ras. Β 11 τὸν] τῶν Α ἀναγεγραφὼς conicio συντάξεσι Mang.: πράξεσι codd. 12 pr. καὶ] ὃν coni. Mang. 15 ὑφηγήσεσι coni. Mang. 16 οὐδένειαν scripsi: οὐθένειαν codd. 18 τὴν πᾶσαν σύστασιν coni. Mang. σύμπασαν φύσιν (vel γένεσιν) &lt;κινούμενος αὐτὸς κίνησιν&gt; οὐ &lt;τὴν&gt; διὰ conicio οὐ &lt;τὴν&gt; διὰ σκελῶν &lt;κίνησιν&gt; Markland 18. 19 ἀνθρωπόμορφος &lt;ὁ θεός&gt; conicio 19 τὴν &lt;τὸ&gt; coni. Cohn ἐμφαίνων οὐσίαν Markland 20 ἄλλας coni. Mang. δεχόμενος D 21 ὁ δυστυχής codd.: δυστυχής ἐστιν D ἐστὶν om. Β, ante ὁ pos. D 22 ἀσταθής coni. Mang.
footnote 1 αὐτῆς codd. 3 δεόντων coni. Mang. 4 γλῶσσαν Α 5 πλήξειε scripsi: πλήξει codd., πλήξῃ coni. Mang. 7 ἀνάγοι coni. Mang. 9 αὑτόν scripsi: αὐτὸν codd. τρόπον #x003E; coni. Mang. 12 παντοίας Mang.: ταντοίων codd. 15 ἀνωτάτω conicio 16. 17 ὡς ἐνῆν—μου om. 26 ἐμφανὲς coni. Mang. 27 μετὰ] δίχα conicio, &lt;οὐ&gt; μετὰ vel μετ’ &lt;οὐκ&gt; Cohn; haec enim cum φαυλίσαντες coniungenda videntur 30 δὴ Mang.: δὲ codd, 31 Μωσῆς Α γὰρ addidi
footnote 1 στοιχείῳ περιττεύει seclusi, στοιχείου περιττοῦ Markland ἑτέρου conicio προσθέσει scripsi: προσθείς codd., προσθήκῃ Markland τοῦ scripsi: τὸ codd. 2 &lt;τὸν μέν γάρ Ἀβρὰμ Ἀβραάμ προσθεὶς ἕτερον ἄλφα καὶ&gt; τὴν conicio add. δὲ Mang. Ἄβραμ B 3 τὸ Hoesch.: τὴν codd. 4. 5 οὗν φρενοβλαβείας scripsi: φρενοβλαβείας οὑν codd. 8 καὶ om. Β τὰς &lt;τοιαύτας&gt; #x003E; ὑπονοίας coni. Mang. 9 ταῦτα Β: ταῦτα τὰ A ἀπάσης (om. τὰ) coni. Mang. 10 γὰρ addidi φωνάεντα A 11 γεννήσας] alterum ν erasit Β 12 ὃν scripsi: ὃς codd. 12. 13 ὃς καὶ πάντων δι’ ἐπιστήμης ἐχώρησε coni. Mang. 13 πᾶν ex LXX Mang.: πάντα codd. 14 ὁ] αὐτὸ conicio 15 ὁπότε coni. Cohn 16. 17 ἀρχηγέτῃ ἀνθρώπων Β 18 φωνάεντα AB 23 ψυχῆς βελτιώσεσιν Mang.: ψυχαῖς βελτίοσιν codd. 20sqq. Orig. Comment. in Gen. p. 30 (ad Gen. 17,5): τὰς ἑρμηνείας τῶν ὀνομάτων ζήτει· δυνάμει γάρ ὠνομάσθησαν ὑπό τοῦ ἁγίου πνεύματος. ἀλλὰ μὴν καὶ τοῦτο χρὴ εἰδέναι, ὅτι τὰ ὀνόματα ἕξεων ἐστι καὶ καταστάσεων καὶ δυνάμεων δηλωτικά· ἐξ ὧν ἔστιν ἰδεῖν τὴν ἐπιτηδειότητα τοῦ ὀνομαζομένου. Homil. in Num. XXV 3 p. 366 (cf. etiam Philonis quaest. in Gen. III § 43).
footnote 1 Ἄβραμ Β 4 ὑφ᾿ scripsi: ἀφ᾿ codd. ἀναγνῶμεν] ἀνοίγωμεν coni. Mang., ἀκριβώσωμεν (cf. lin. 14) vel ἐρευνήσωμεν e gr. conicio, γνῶμεν coni. Cohn 8 πέρι codd. 13 Ἄβραμ B 16 ἠχοῦν coni.Mang. 20 ἐσκιογραφεῖτο A 29 ἵν᾿ B τοιαύτης conicio 2 sqq. cf. Ambros. de Abr. I 4,27.
footnote 1 δὴ Mang.: δὲ codd. οὐδὲ scripsi: οὐδὲν codd. 5 ὑπολαβόντες Mang.: ἀπολαβόντες codd. 14 ἐρευνῶμεν conicio αὕτη Cohn: αὐτὴ codd. 18 γένους εἶδος coni. Mang. (sed sic scrib. etiam lin. 19 τὸ πρότερον ὄνομα τοῦ δευτέρου) 19 κατὰ τὸ ἔλαττον secl. Cohn τοῦ προτέρου ὄνομα Β 22 γὰρ addidi, οὑν add. Mang. 24 λέγοι scripsi: λέγει codd. 2 sqq. V. vol. II ad p. 98,1. 14 sqq. cf. Ambros. l. c. 431.
footnote 4 ὅτι ex Coisl. 43 Mang.: om. ΑΒ 6 &lt;τὸ&gt; τὰς conicio alterum om. Β ὀχυρῶς (om. καὶ) vel ὀχυρὸν καὶ &lt;βεβαίως&gt; conicio 8 ἀκονιτὶ Mang.: ἀπονητὶ codd. 12 καὶ Α: ἢ B 17 ταύτης τῆς conicio τῆς αὐτῆς &lt;ἀεὶ&gt; coni. Cohn 19 πλεῖον codd. 20 διδακτικὴ Β: διδακτὴ ἀσκητὴς coni. Mang. 22 μονῇ scripsi: μόνη codd. ἐνειλημμένος conicio 24 ὑπανίσται B, ὑπανίσταται coni. Mang. 24. 25 τεθρυμμένην scripsi: τετρυμμένην codd., τετρυμένην Mang. 28 ὑποβολεῖ in ὑποβολὴ corr. B 29 alt. καὶ vid. secl.
footnote 1 γεννητῷ codd. καταβάλῃ scripsi: μεταβάλῃ codd. 2 γὰρ] ἄρ’ coni. Mang. 5 χρώμενα Hoesch. 12 &lt;τῶν&gt; τοῦ conicio 14 εἰσαεὶ codd. scripsi (cf. § 83): διδακτὴ codd. 14. 15 ἀσκητὴ Mang., #x003E; ἀσκητικὴ conicio 19 ὅσιον coni. Mang. ἐνδέον coni.Mang. 20 οὐχ &lt;οὕτως&gt; conicio 24 θεραπεία Β, fort. recte
footnote 1 ἐν ἀποκρύψει στόμα ἀποκρινόμενον coni. Mang. 2 οὐσίαις] ὕλαις coni. Mang. 4 φρόνημα B 8 μεταληφθῆς Α 11 παρὰ Β2: περὶ A (B1) 17 τῷ ὃ coni. Mang. ᾦ] ὃ Β 18 φυρόμενοι coni. Mang., fort. recte; v. Quis rer. div. her. § 234 20 βασκανίαι conicio μέχρις Α 22 οὐκ εὐκτός coni. Markland, ἄκληρος conicio 23 ἢ Β2: ἣν ΑΒ1 25 δόξης αὗ θνητῆς τε καὶ coni. Mang. 26 Ἰωσὴφ in ras. Β Εὐφραΐμ Β οὐ om. Β 27 ἐξομοιοῦντο Α 28 Ῥουβήν scripsi: Ῥουβίμ codd., item lin. 30. 174,1 29 με Β2: μὴ ΑΒ1 30 Μανασσῆ Α
footnote 5 τῷ seclusi, τῷ post ὡς vid. add. 9 σύμβολόν ἐστι· οὕτω γάρ καλεῖται Mang. δ’ s. s. Β 12. 13 ὑπαναπολεῖ coni. Ηoesch., ἐπαναπολεῖ coni. Mang. 14 ἡ seclusi 16 Ῥουβὶμ codd. τόδε Α &lt;τὸν&gt; λόγον conicio 19 δευτερεῖα Cantabr. Coll. S. Trin. (Mang.), fort. recte 24 ἀπλανεῖ coni. Mang. 25 ὢ ἄνισα coni. Mang. 29 μὴ secl. Mang. 30 μὴ add. Mang. (v. LXX)
footnote 3 θρεμμάτων Mang.: ἀημάτων codd. 7 ὑφηγήσεται 〈αὐτὸς Μωυσῆς〉 conicio 9 ἐκκρίσεως Β 13 τε seclusi τελετὰς ἀνιέρους τὰς conicio 14 στόμια scripsi: στόματα codd. ἄνωθεν coni. Mang. 16 ἀφεῖσαν (vel ἠφάνισαν?) scripsi: ἐπήεσαν codd., ἐπίεσαν coni. Mang., ἔπεμωαν coni. Cohn 18 ἀνακύψαι coni. Maug. 19 τρανὸς] θεραπευτὴς coni. Mang., τρανὸς &lt;λόγος&gt; conicio, sed fort. maior lacuna statuenda 20 κατεσχημένος Hoesch: κατισχημένος codd. 26 σῶος &lt;πᾶς&gt; coni. Mang. 28 κριτικὸν Mang.: κρεῖττον codd. 30 ἤσαν ex LXX coni. Mang.
marginal p. 596 Μ.
footnote 7 ποτίζουσι Mang.: πίνουσι codd. 9 αὐτῷ per errorem Mang. 11 καὶ om. Β 13 ἔξω Μang.: ἐξὸν codd., ἐξ ὦν coni. et post ἀγώγιμα add. αἰσθήσει Markland 14 ἀγώγιμον παραδιδόναι τοῖς φαινομένοις (πρὸς τὰ φαινόμενα Cohn) conicio ποιμαινόμενα Mang. 15 Μωσῆς codd. 16 ὑπερασπιεῖ conicio αὐτὰς scripsi: αὐτά codd. κατατρεχόντων coni. Mang. 21 ἀξιωθεῖσαι coni. Mang. 23 〈τούτου〉 τῆς conicio 26 πεύσεται Mang.: πευστέον codd. καὶ addidi 31 συντόνως Mang.: συντόμως codd.
footnote 1 νοητά coni. Mang. 3 ἄνθρωπος &lt;Αἰγύπτιος&gt; coni. Mang. 4 Μωσῆν codd. 6 ὢν seclusi 7 ἐφίωνται codd. 10 μόνῳ om. Α 11 post καὶ fort. add. part. 13 οἰκεῖ scripsi: οἰκεῖον codd., οἰκεῖ οὑν Mang. 14 περιέσχετε] περιεχόμεναι ἐκτήσασθε conicio 16 δεξιώσεσι coni. Mang. 18 τὸ seclusi 21 Μωσῆς codd. 25 ποιά] πᾶσα bene coni. Mang. 27 πάσχων B2
footnote 3 εἴη scripsi: ἡ codd. ἐξοικίζουσαν Β οὕτω] ὄντως Iloescii. 5 καθαρσίοις Mang.: καθαρσίῳ codd. 6 δ’ Β 7 θεσπιζομένους conicio 8 Μωσῆς codd. 11 δὴ conicio ἀναγράφειν conicio 13 θεσπιῳδοῦ] θεοῦ coni. Mang., ὑπὸ τοῦ θεσπιῳδοῦ secl. Cohn 15 Μωσῆς Α 17 μὴ ἡρμοκότος coni. Mang., μέν ὑπερεωρακότος vel μὲν ἀποδεδρακότος conicio 19 εὐλογίᾳ Mang. 20 τελεωτέρας Β 21 θεὸς] ἄνθρωπος θεοῦ vid. leg. 23 σκήπτροις] θρόνοις conicio 23. 24 ἐφιδρύοιτο μεγαλαυχῶν. καὶ διὰ τοῦτο οὐχ ἥκιστα &lt;εὔχεται&gt; coni. Mang. 25 μέλλουσι Β
footnote 2 αὐτῆς addidi, v. § 141 3 κυρίως om. Β 5 Ἰσαὰκ post ἄνθρωπος transpon. Β 6 υἱός] λόγος coni. Mang. 7. 8 γὰρ ἕτερον μὲν conicio 9 Μωσῆς codd. 12 lacunam statuit Cohn 13 φιλόκοσμον Mang. παιδείας Mang. 14 καὶ om. Β 16 Μωσῆς codd. 18 εἰκάσασα coui. Mang. ταυτα Β 21 πάντα Β 22 6 addidi ἡ scripsi: ἢ codd. ὁ κόσμος seciusi; videtur vocum ὁ ὁρμίσκπ expiicatio, ἡ κόσμου εἱμαρμένη vel ὁ κόσμος, ἡ εἱμαρμένη coni. Mang. 6 v. ad p. 185,4. 22. 23 cf. Gercke, Cηrysippea fr. 42. 56.
footnote 1 καὶ om. Β 2 φρόνησις om Β 6 τοῦ] τῆς coni. Cohn 7 ἀγενεῖς Α 8 συγχαρεῖταί Α: οὐ χαριεῖταί Β 12 διάπυρον] διάφορον coni. Mang. 13 εὑρήσεται Hoesch. 16 post οὖσι lacunam statuo 20 ἀσυνέτων vel ἀνεπιστημόνων coni. Mang. 23 ἄριστα v 24 αὐτῆς codd. 25 μεγάλην εὔνοιαν coni. Mang. 27 μελήσεως Β 29 γεννητοῦ codd. 31 εἰσαγαγόντες conicio
footnote 5 ἠσθένησεν Β 6. 7 συμπεφυρμένην Β 9. 10 ἀποδιδράσκουσάν τε conicio 10 διαφεύγουσαν coni. Mang. 11 εἰρηνικοῦ τρόπου vel ἡρεμαιοτάτου coni. Mang. 15 δή conicio 18 τὸ add. Hoesch. 24 ἀστὸν coni. Mang. 24. 25 ὅτι οὐκ ὀθνεῖον seclusi, irrepserunt ex lin. 23 29 δηλῶν ὅτι Mang.: δηλονότι codd. 29. 30 προσεχέστατα Mang.: πρὸς ἔσχατα τά codd.
footnote 4 οἰακονόμος seclusi, vid. add. adverbium (βεβαίως?) οἰκονομεῖ Α οἰκίαν conicio 5 χώρας Β 7 κατεβάλλετο B 10 ὑφ’ conicio 10. 11 προσερρέθησαν V, προσερρύησαν coni. Mang., προσευρέθησαν conicio 11 χωρήσει] διεχωρίσθη coni. Mang. 18 &lt;ὁ&gt; μῦθος conicio 23 ἀνωμολογῆσθαι coni. Mang. Μωσῆν codd. 28 ἐν seclusi ἐναρέτοις coni. Mang. 29 κατεσχημένος Mang.: κατισχημένος codd. 30 ταῖς Α
footnote 5 πίπτειν τε καὶ γελᾶν conicio 7 τὸ scripsi: τοῦ codd. μόνον Mang.: μόνων codd. 9 ἐπίλυπος Mang.: ἐπίλυτος codd. 12 ἡμᾶς Mang.: ἡμέραν codd. 13 γεγέννηται codd. 15 οὔτ’ conicio 16 οὕτω Α 21 χίμαρρον Β 22 διερεθίζοι conicio 27 ἔργον Hoesch. ὄρουσιν Mang.: ἔρυσιν codd. 28 πρὸς Hoesch. - 29 δή τι scripsi: δῆτα codd. τοῦ ἀγαθοῦ Β 27. 28 ὄρουσις] v. Stobaei Ecl. II 87,7—9 Wachsmuth.
footnote 1 προγήθη Hoesch., προγήθει Mang. 3 ταῦτα scripsi: αὐτὰ codd. 5 ἕλυξι Β 6 μόνον addidi 8 αὐγῆς Mang.: αὐτῆς codd. 10 γάρ addidi 11 μέλλοντος scripsi: μέλλοντι codd., μέλλον coni. Cohn ἐπελπίζομεν coni. Mang. 18 ἐνάργειαν scripsi: ἐνέργειαν codd. εἰς τὴν ἐνέργειαν ἀπιδόντες post ἔνιοι transpos. Β 22 ἀρυσάμενος Mang.: ἱδρυσάμενος codd., ὑδρευσάμενος ed. Paris. in mg. 23 τοῦ om. Β(?) v 24 ἑστιᾶσθαι ed. Paris. in mg.: αἰτιᾶσθαι ΑΒ
footnote 2 ἀεὶ Β 4 εὐπάθειαν scripsi: ἀπάθειαν codd. 5 Μωσῆς codd. 9. 10 ἀποφορτισαμένης v 11 ἐφίεται D (Ant. Mel.) καὶ om. D (Ant. Mel.) 12 εἶπεν ὁ D (Ant. Mel.): εἶπε codd. λόγος] νόμος coni. Mang. 16 ἐπιμορφάζειν Mang.: ὑπομορφάζειν codd. 19 προκρίνοντες Ant. Mel., προκρίναντος D 20 εἰκότως om. D Ant, Mel. τοῖς] τοὺς D εἰσηγουμένοις ἀπεχθάνονται Ant. Mel.: ἡγουμένους ἀπεχθάνονται D, ἀπεχθάνονται εἰσηγούμενός codd. 1 sqq. cf. Cic. Tusc. V 43. 4 Zeller III 1 p. 268 adnot. 2. 10—12 D R fol. 237 V περὶ τῶν μετονομαζομένων Anton Mel. II 32 col. 1084 Φίλωνος: τῶν φαύλων οὐδενὶ—θεός. Anton. Mel. pergit usque ad lin. 14 βίον. 17 DR fol. Φίλωνος Anton. Mel. II 60 col. 1153: οὐδενὶ τῶν φαύλων ἐπιστὰς ἔλεγχος δι’ ἡδονῆς ἐστιν. 18—20 DR fol. 213r Φίλωνος ἐκ τῶν περὶ μετονομαζομένων Mel. II 51 col. 1128 Φίλωνος: πόνος μὲν τοῖς—ἀπεχθάνονται. — 19 DR fol. 142r fol. 256 V Φίλωνος: ῥᾳστώνη τοῖς βλαβεροῖς ἕπεται. in DH sequitur ἡ ἐξ ἔθους καὶ σχολῆς ἀργία πρᾶγμα ἐπίβουλον, in DR et apud Anton. Mel. post locum ad lin. 18 laudatum locus ad vol. I p. 1—3 adlatus, tum ἡ ἐξ ἔθους . . . . . . .
footnote 1 συνετράφη B (in ras. τ): συνεστράφη Α, συνανεστράφη coni. Mang. 7 παρήβασκε v 8 ἥκετε Hoesch.: ἥκατε codd. 9 ἐπ’ &lt;ἀγαθὰ&gt; conicio, ceite latet 10 ἡμῶν om. Hoesch. προεληλυθότος Hoesch. 16 alt. κατὰ fort. secl. 17 κυλινδούμενον Mang. 19 τιθασεύοντα Mang.: τιθασσεύοντας codd. 20. 21 τὸν μυελὸν ex LXX Mang.: τῶν μυελῶν codd. 21 τῆς ex LXX addidi 29 ἱδρυθέντος scripsi: ἱδρυνθέντος codd. 30 ἐννενήκοντα codd. 31 μέν addidi
footnote 1 τὸ] τῷ conicio εἶπεν Mang. 3 ἐνδοιάσαι B: ἐνδοιάζειν Α ᾗ] ἧς conicio 9] αὐτό &lt;μόνον&gt; conicio 15 πράγματι et σώματι   συνδιαιροῦσα coni. Mang. συντέμνουσα conicio ἀπειρομεγέθη διαστήματα Mang.: ἄπειρα μεγέθη διὰ στόματος cocid. 20. 21 ὑπερβαίνουσα coni. Mang. 21 τούτου &lt;κόσμου τοὺς&gt; ὅρους conicio 22 συγγενικῶν coni. Mang. 23 ἀμερίς Β, ἀκαρής Mang. 24 τί; οὐ γέλοιον ὅτι conicio, τί οὑν; ὅ ποτε πεπιστευκὼς coni. Mang. 25 αὔραν Mang.: ὥραν codd. 26 ἀγέννητον codd. 13 Hom. Od. η 36.
footnote 1 φασι Mang. 3 Μωσῆς codd. 4 ἄνοια Mang. 5 ἀρεπεῖς Α 6 αὐτόν Hoesch. 19 ἄκρης ed. Par. in mg.: ἄχαρίς codd., ἄχρονος Mang. 21 καὶ τῇ βίᾳ] τῆς βίας conicio 22 Μωσῆν codd. 26 οὐδὲ] οὐκ conicio 28 ἐνενήκοντα καὶ ἑκτὸν scripsi: ἐννενηκονταέταις οὖσι codd., ἑκατονταέταις Mang. 30 ἑκάτερον scripsi: ἑκάτερα codd. 12–14 DL fol. 139r Φίλωνος ἐκ τῶν περὶ μετονομαζομένων: εὐδαίμων ὅτῳ—ἄπαντα.
footnote 4 fort. οἷόν τε add. 6 χρώμενος Markland: χώματος codd. 8 Μωσῆς codd. 11 παρὰ ex περὶ corr, B2 12. 13 ὡς δεκάτην λόγων ἱεράν] ἑτέρας δεκάτας &lt;ἑκατοστὸν&gt; λόγον περιεχούσας (v. § 2) vel δεκάτην ὡς ἀπαρχὴν ἱεράν conicio, δεκάτην ἑκαστοστῷ λόγῳ ἱερὰν coni. Mang. 16 τῆς] τοὺς· conicio τὴν ψυχὴν B2 17 τέλειον add. Mang. ἐννενήκοντα codd. διαλείψεις per errorem Mang. 18 &lt;δευτέρας&gt; δεκάτης conicio 19 post μέσου multa, quibus de nonagenarii numeri vi ageretur, excidisse coni. Mang. 21 &lt;μὲν&gt; ἔστιν conicio 23 ὄνος man. recentissima in mg. (Hoesch.): ὦμος AB 28 οὐκ Mang.: οὑν codd. ἐλαλήθη Β 29 μόνον οὐκ codd.
footnote 3 καὶ ἐπιτηδευμάτων om. Β εὐεπείᾳ coni. Mang. 4 ἐχρῆν οὖν conicio 5 ωσῆς codd. 9 τῇ ἀειπαρθένῳ coni. Mang. 10 δίκαια Mang.: δίκη codd. παριᾶσιν Hoesch.: παρίασιν codd. 15 ἀνδρία codd. 16. 17 τὸ ἀσεβές ψεκτόν om. Β 17 τὸ secl. Mang. βουλεύεσθαι Mang.: βούλεσθαι codd. 19 tert. τὰ secl. vel &lt;τὰ&gt; βουλευτήρια scrib. 20 ἀνθρώπων Mang.: ἄνθρωποι 23 κατεσχημένοι Mang.: κατισχημένοι codd. 24 κακοτεχνοῦντες scripsi: κατατεχνοῦντες codd. συνύφηναν scripsi: συνύφαναν codd. 27 τά αἴσχη scripsi: τὴν αἰσχύνην codd. 7. 8 DR fol. 46v τοῦ αὐτοῦ DH fol. 134r: τὸ ἐκτραγῳδεῖν καὶ ἐπικομπάζειν ἐπικωμάζειν DR) τὰ κακὰ διπλοῦν ἁμάρτημα.
footnote 1 om. Β 2 #x003E; ὡς coni. Mang. 3 εὐπρεπεῖς Β ὄντως Β 6 Μωσῆς codd. 10 ἐπαγγελίαν Mang.: ἀπαγγελίαν codd. 11 αὐτοῦ codd. 12 γεννητὸν V 14 ἐκφερομένων coni. Mang. alt. τῶν vid. secl. 22 γνώμην Β 23 τό &lt;τοῦ&gt; couicio 26. 27 παρεχάραξε Mang.: προεχάραξε προὐχάραξε Β 27 μόνος in rng. Β 32 πράγματα Β ἢ] καὶ conicio
footnote 4 τοῦ υἱοῦ Mang.: τούτου codd. 9 δὲ add. Mang. Μωσῆς codd. 12 λέξεις Mang. 13 Μωσῆς codd. 15 μιμηλάζοντες Mang.: μιμηλίζοντες codd., κιβδηλεύοντες conicio δὴ Mang.: δ’ codd. 16 τοῦτό] αὑτοὺς ex codice Oxon. Coll. Nov. 143 Mang. 19 ὁμοιότητα conicio τὴν βάσανον Β 21.22 Μωσῆς codd. 23 ἐπαμπισχόμενος scripsi: ἐπαμφισκόμενος codd. 27 Ἰακὼβ] per memoriae lapsum Philo, capitis Gen. 49 memor, lacobum pro Mose inducit Ρουβὴν scripsi: Ρουβὶμ codd. 30 μαθήματα] θεάματα coni. Mang.
footnote 4 στερεοῦ D (Cohn) 5. 6 μήτε bis scripsit Mang.: μεῖά codd. 8 αὐτῶν vel αὐταῖς conicio ἐνεργεῖς Hoesch. 10 ἐστιν D: ἐστιν ἡ codd. 11 οὐδέ εἷς D 13 σπουδὰς codd.: βλάβας D, συνουσίας conicio 14 &lt;τῷ&gt; τοῦ conicio ποταμοφορούμενος Β ὑπ’ scripsi: ἀπ’ codd. 15 δύναται coni. Cohn 16 ἀνῶσαι scripsi: ογσαι codd., στῆσαι vel. ἀντωθῆσαι (sic) coni. Mang. 21 ὑπερδεδραμηκότα Mang.: ἀποδεδραμηκότα codd. 1—4 DR fol. 204r Φίλωνος ἐκ τῶν περὶ μετονομαζομένων: φυσικῶς μὴ προὑπαρχούσης τῷ μανθάνοντι εὐφυίας ἀνωφελῆ πάντα . . . . . . καλὸν γὰρ μάθημα οὐδὲν αὐτοῖς ἁρμόζεται ἀπεστραμμένως διακειμένοις καὶ τὰ ὦτα μύουσι, πάντα δέ ὡς ἀπὸ στερεοῦ τινος ἀντιπνέοντος πρὸς τὸ πνεῦμα. 5 cf. Platonis Theaet. p. 191 C ss., supra ad p. 41,18. 10–13 DP fol. 255v τοῦ κατ’ ἀρετὴν–ζῆσαι. 19 cf. vol. II ad p. 272,23.
footnote 1 ἐξωκείλαντες Β 2 &lt;κατὰ&gt; τοῦτον coni. Cohn εὔχεται scripsi: codd., εὐχώμεθα coni. Cohn προστίθησι γοῦν bene coni. Cohn 3 ζήτω Mang.: ζῆ codd., fort. del. 5 εἰσαγόμενος coni. Mang., παιδαγωγούμενος conicio 8 αὐτό Mang.: αὐτῶ codd. 9 χρήσεσθαι Mang.: χρήσασθαι codd. 10 ἀίει περιβλεπόμενος conicio, καὶ προσβλέποντος coni. Mang. 12 ἀπέγνωκε Mang.: ἀπέγνωσε codd. 13 lacunam statuo (cf. § 178) ἃ] ὅσα DH fol. 338 θεὸν D C fol. 259 DK fol. 277 14 λαμβάνειν DC fol. 2.59 DR foi. 277 πλεῖστα] καὶ πλεῖστα DC fol. 138 DH fol. 204 et 338 καὶ μέγιστα om. DH fol. 338, καὶ μεστά μεγέθους DR fol. 277 χαρίσασθαι DC fol. 259 DRDH fol. 256: χαρίζεσθαι codd. DC fol. 138 DH fol. 204 et 338 15 προκειμένας Β 16 μελέταις coni. Mang, 20 ἐδίδαξε Mang.: ἔδειξε codd. Μωσῆς codd. 21 χαρίτων coni. Mang. 1—4 cf. orig. Comment. in Gen. p. 36 (ad eundem locum): ἐξαίρετόν τι ἠξίου περὶ τοῦ Ἰσμαὴλ ὁ Ἀβραάμ, οὐκ ἀρκούμενος τῷ „ζήτω“· διὸ προσέθηκεν „ἐναντίον σου“. τὸ γάρ ζῆν ἐναντίον κυρίου μακαρίων ἐστὶ καὶ τῶν ἁγίων μόνων (cf. Pbilonis quaest. in Gen. III § 57). 13—15 DC fol. 138r Φίλωνος ἐκ τοῦ περὶ τῶν μετονομαζομένων, fol. τοῦ αὐτοῦ ἐκ τοῦ περὶ τῶν μετονομαζομένων, DR fol. 142v ct 277r τοῦ αὐτοῦ DH fol. 204v 256r 338r Φίλωνος: οὐχ ἃ δοῦναι—δωρεάς.
footnote 3 τὸν in mg. Hoesch.: τὸ codd. φυσιολογίαν in mg. ed. Par.: φυσιολογίας codd. 7 &lt;τὸ&gt; τοῦ conicio 9 συνελόντι conicio 10 ἀποφανεῖ Mang.: ἀποφαίνει codd. 12 ἀπογνώση D 13 εὐχάριστος D: om. codd. θεῶ D 14 post ἡδῆ add. ἀγαθῶν D, fort. recte 1.5 εὐχαριστεῖ τῷ θεῷ. μυρίων D post ἔλαχεν add. ἀγαθῶν D 16 φαντασίας ὁρμῆς om. D ὁρμῆς, νοῦ. νοῦς δὲ coni. Mang. 16 βραχύτατον Dv ὄνομα μὲν D 17 δὲ om. Β θειότατον D: βραχύτατον codd., &lt;οὐ&gt; βραχύτατον coni. Grossmann, περιμάχητον coni. Mang. 18 Μωσῆν codd. 19 &lt;δ᾿&gt; ἄξιον conicio 22 αὐτὸ μόνον Mang.: μόνον αὐτὸ Α, μόνον αὐτῶ Β 23 μὲν &lt;γὰρ&gt; conicio 25 ἀνδρία codd. 11—13 DH post locum ad lin. 19 allatum: μηδεὶς οὑν — γενέσθαι θεῷ. 14—17 DH fol. 338r Φίλωνος: ὑπὲρ ὧν οὑν ἕκαστος ἔλαχεν ἡδῆ ἀγαθῶν, κατά ἔργον. 18. 19 pergit DH; ἐκεῖνος θείας ἐμφερείας ἐκμαγεῖον.
footnote 1 ἕν Mang.: ἑνός codd. 3 εἰ om. Β 5 τιμητικός Β 6 μηδὲ scripsi: μὴ codd. 8 δύναται conicio 8. 9 τελείως bis coni. Mang. 9 σου coni. Cohn 10 ἕλοιτο scripsi: ἕληται codd. τῆς Α: τοῖς Β 11 δεκάδα Mang.: πεντάδα codd. 12 ἶνα μὴ Β 13 τῇ γενέσει v ἧς Α: ἢ Β 15 ψυχῆς Α: τῆς B 17 ἐγκεχορευκότες Mang.: κεχορευκότες codd. 18 αὔξεσθαι scripsi αὔξασθαι Mang.): εὔξεσθαι codd. καρτερίας Mang.: ἀρετῆς codd. 18. 19 καὶ ἀρετῆς πάσης om. Β 19 ἐπασκηθέντες coni. Mang. (immo ἐνασκηθέντες) 20 δὲ codd.: δὴ Mang., τελείως conicio 21 Ἡσαῦ A 22 εὐλογία σοι] ἁ et οι in ras. Β2 μία σοι ex LXX conicio ἐστί scripsi: ἔσται codd.
footnote 1 μὴ καὶ coni. Mang. 6 σταθμούμενος Β 7 ἰσώτατα coni. Mang. 12 εἰς] εἰς τὸ Hoesch. 14 &lt;τοῦ&gt; οἶφι conicio σεμιδάλεως e codice versionis LXX falso Mang. ἐπιχεεῖ ex LXX Mang.: ἐπιχρίσει codd. 15 λιβανωτόν Mang. 17 &lt;αὐτῆς&gt; ἐπιθήσει conicio; v. § 249 24 διανοίαις 25 Μωσῆς codd. ἀγαθοῦ Mang.: ἀγαθὴ codd., τἀγαθοῦ conicio 28 δείκνυσι. ἐν γάρ τῶ στόματί σου, φησί, καὶ conicio ἔργον] ῥῆμα ex LXX coni. Mang. 31 εὐδαιμονίαν ἀνθρωπίνην v
marginal p. 615 M.
footnote 2 καρδίᾳ om. Β 6 δυσαπότρεπτον coni. Mang. 7 εἰς om. D Barocc. 8 τροπὴν ψυχῆς D Barocc. 9 ἀλλ’ ἐπ’ ἀλλήλοις Barocc. τρικυμίαις Barocc. τὸν τρόπον Barocc. ἐπέχει Barocc. φοροῦντα καὶ om. D Barocc. 10 ἀνατρέποντα DM Barocc.: ἐπιστρέφοντα codd., ἐπιτρέποντα DP μὲν γὰρ ἄρκτον Barocc, ἄρρηκτον DM 11 τελειότατον D Barocc. τοῦτό D Barocc. μηδ’ scripsi: μηδὲν codd., μὴ D Barocc, μηδὲ v τι om. D Barocc τῶν om. DM ἀτόπων D Barocc: ἀτοπωτάτων codd. 12 ἐμπολιτεύσασθαι conicio 15 ἀνιέντα Mang.: ἀνέντα codd. 17 ῥᾴδιον conicio 18 ἀλλὰ B 20 κακοδαίμων coni. Mang. ἐκ τύχης] ἐξ ἀρχῆς coni. Mang. 21 τὴν] ἣν coni. Mang. 22 κἄπειτα] ἐπεί τοι conicio 6—11 DP fol. 358v DM fol. 269r τοῦ αὐτοῦ ἐκ τῶν περὶ τῶν μετονομαζομένων Mel. Barocc fol. 168r Φίλωνος: χαλεπὸν τῆς add. Barocc) ψυχῆς – ἀτόπων. 23—199,2 pergit DP DM Mel. Barocc. l. c βαρὺ δὲ τὸ διὰ λόγου τά πονηρά ὅ ἐστιν ἄδικος πρᾶξις. λόγος—βλαβερώτερον.
footnote 2 Μωσῆς codd. 3 ἀκουσίοις scripsi: ἀκουσίαις codd. 7 ὑπαιτίων Mang.: ὑπαίτιαι codd. 11 οὑν seclusi, fort. θῆλυ leg., νῦν coni. Cohn 12 τριῶν μέτρων coni. Mang. 15 ἀνατέλλων Α 16 ἀσφάλειαν coni. Mang. 17 ἀποσκιάζούσα Hoesch. 18 εὐκοσμίας Β: εὐκοσμίαν Α 19 ζῷον B(?)v 21 φερόμενος et διᾴττων scripsi: φερόμενον et διάττον codd. 24 ζεύγει ex ζεύγη corr. Β 25 τὸ Hoesch.: τὰ codd. 26 εἶναι fort. secl. 27 ὅλων coni. Cohn τε καὶ addidi, καὶ add. Mang. 1 Democriti fr. 105 Natorp, qui omisit testimonia Philonea.
footnote 3 διακρίνεσθαι conicio τὴν Β: τὸν Α 4 αὐτῆς ex LXX Mang.: αὐτῶν codd. 8 ὑπερβαλούσης Β 9 οὐ om. Β 18 σοι Β: om. Α 19 prius ἡ] καὶ coni. Mang. τὰ ἀγαθὰ Β 20 θεῷ scripsi: θεοῦ ΑΒ, θεὸν Cantabrig. Coll. S. Trin. Β. 9.6, τε coni. Mang. 24 ἐπιτάττουσαν] ν add. B2 25 τοῦ πανηγεμόνος Mang.: τῶν ἡγεμόνων codd., τοῦ πάντων ἡγεμόνος coni. Cohn 26 θείας Cobn: θείου codd. 30 δ’ adddidi &lt;τὰ&gt; σπουδαῖα 31 τὸ Β2 (Mang.): om. AB1
footnote 1 μάθης Β 2 ὀσφραίνονται scripsi: ὄσφρονται codd. 5 σχέσεις Mang.: πείσεις codd. 6 σοφιστὴν Mang.: σοφιστῇ codd. 7 ταῦτα Β ἀφειμένα scripsi: ἐφιέμενα codd., ἀφιέμενα Mang. 10 &lt;δὲ&gt; add. 11 Μωσέως codd. 14 νείφει codd. 16 ἀπ’ οὐρανοῦ τροφὴν Markland (nisi quod οὖν del.): ἀποτροφήν codd. 17 ἐπινίφει coni. Mang. 18 ἔχων] χέων Maug. 20 αὐτομάτων Mang.: αὐτομαθῶν codd. ὅλης] ὑλικῆς coni. Mang., ἀνθρωπίνης conicio 21 αὐθιγενεῖ conicio 26 καθάπερ &lt;γὰρ&gt; coni. 27 ὀνοματοποιήσῃ scripsi: ὄνομα ποιήσῃ codd. 30 τυγχάνοι Α
footnote 1 #x003E; πληθυνῶ coni. Mang. 5 αὐτομαθοῦς δέ τὸ ἐρρωμενέστερον coni. Mang. τῶ ἐρρωμένω Β 8 ἂν addidi 9 καὶ] καὶ ἡ B 10 Μωσῆς codd. 11 ἀποδεδειλιακόσι coni. Mang. 18 πολλοῦ om. Β εἰκαίου coni. Mang. 19 αὐτὸν coni. Cohn 21 τὸ addidi ὃ] ὃς coni. Mang. 25 ὡς] ὡς καὶ Mang. 25 cf. ad p. 38,15.
