@node
@author=Hermogenes
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Hugo Rabe
@filename=tlg0592.tlg002.1st1K-grc1
@funder=Harvard Library Arcadia Fund
@principal=Gregory Crane
@publicationStmt=Harvard College Library, tlg0592.tlg002.1st1K-grc1.xml.
@respStmt=Digital Divide Data, Corrected and encoded the text, Gregory Crane, Editor-in-Chief, Perseus Digital Library, Matt Munson, Project Manager (University of Leipzig), Annette Gessner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig) 2015 - 2017, Bruce Robertson, Technical Advisor
@sourceDesc=Hermogenis Opera, Hugo Rabe, Hermogenes, Teubner, Leipzig, 1913, Rhaetores Graeci, 6, Hathi Trust.
@sponsor=Harvard College Library
@title=Περὶ τῶν στάσεων
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T15:05:22Z

12634	marginal W. 1 8p. 133
marginal 2
footnote P = Pa Pc V = Vc Ac Ba Ph, Py 1 de titulo v. Praef. 4 sq. cf J. ab Arnim, Stoic vet. fragn l p 21. lI p 30. 31 5 | συγ m. po.] γυμνασθέντα Ba; συγ supr. Ph 8—1 cf. Π εὑρ. 205 206. 201 Sp. 8 τῆς διαιρέσεως Vc Ba Ph δὴ Vc Ba, Sop. 9 schol. Wc (Glöckner, Über den Kommmentar des Joh. Doxapatres, l 31): πρὸς τὸν Ἑρμαγόραν . . καὶ τὸν Μινου-κιανὸν . ἀποτεινόμενος κτλ ; cf Marc. (sic) lV 63, 10 W, de Her-magora, 63, 14 de Lolliano οὔτε (pro καὶ) Sop. 10 μὲν om. Ac | ῥητορικῆς μέρος Ac Phy, Syr 13 σχεδὸν ὁ αὐτὸς V Phy, Syr.; ὁ αὐτὸς σχεδὸν P: ὁ αὐτὸς λόγος Sop 14 περὶ τῆς εὑ-ρέσεως Ph 15 Sop W V 26, 24 (9, 15): Μινουκιανοῦ ἐπιλαμ-βάνεται |γε om. Vc Ac; μὲν Marc IV 69, 9 W. |ὅ τί ποτέ Ac
marginal 134
marginal 3
footnote 1 γὰρ (pro τοίνυν) Syr. 3 τοῦ (ante καλοῦ et συμφ.) om. Syr. 2 p. 15, 7 16, 22 Sοp. V 27. 30 W. Marc IV 80, 23 81, 7 W. 4 ἢ καὶ τινῶν Sop. 5 ἢ συμφέρον PV Ph; om. Py, Syr. 2 p, 17, 22 (at 35, 14) 5 σκοπεῖν Py 7 schol. P (W VII 117, 7) τὸ δὲ ῾ ἀνάγκηʼ προσθεὶς πρὸς Μινουκιανὸν ἀποτείνεται, cf Sop. IV 82, 20 W 8 καὶ πράγματα εἶναι (om γίνεσθαι) Py 9 ῥᾶιον Vc 10. 11 καὶ ὅλως εἰ (om ὅσα) Marc. IV 85, 8. Sop. V 38, 19 W, 12 μὲν etian ante οὖν Ba | μέν οἶά τέ ἐστι Sop. | δύνασθαι Pc h Sr, Syr., (τ supr.) Vc; δύναται Pa y Ac Ba 13 ἐπέχει Pa h y Ac Ba, Syr., Sop ; ἔχει Pc, (ἐπ m 2 supr.) Vc 16 τοιαῦτα Pc h V, cf. Sop.; ὅμοια Pa 17 δὲ τὰ Vo Py; δὲ τάξιν ἔχουσι τὰ Sr 18 δὲ τὰ Pγ 19 καὶ λίχνοι Ph 22 καὶ mo.2 supr. ante κρίσιν Vc
marginal 4
footnote 1 cf. 48, 18. Arist. Rhet. B 24 p. 1401 b 24 Soph. el. 5 p. 167 b 10 3 ἡ ῥήτωρ· ταῦτα Pb 6 στρατηγός Sop. 9 χρήσασθαι Sop. | χρῆσθαι αὐτοῖς ὡς Py 11 ἀκολουθοῦντας Ph 12 ἐπι-δέχονται Pc 13 cf. 32, 14 15 εἴπηι Pc; εἴποι Pa hy ἔσται post τοῦτο Pc: post 16 ἑτέρου Py 17 ὥσπερ δὲ καὶ Vc | οὕτως δὲ καὶ Ph, (οὕτω) Sop. V 51, 22 W.: οὑτωσὶ καὶ Ba 18 πλείστη (pro ἔστι) Sop μὲν ἔχει δύναμιν ταῦτα Syr. (ex p. 29, 14?) 19 cf. 36, 12 20 τὸ om Pc h |ἐπʼ ἐρημίας post φωραθεὶς Ph 22 εἰς τοῦτον Ba | τὸν Ph: τὸ [l] Ac 23. 31, 1 προδοσίας κρίνεται V Ph : φεύγει προδοσίας Py, Syr. 2 p. 67, 26, v. l. P. cf. 44, 7
marginal 135
marginal 5
footnote 1 ἃ PVPy; ἣ| Ι?] Ρh; Sοp V 53, 1 Marc. IV 129. 16 W. τρίτην ἐξ ὑπονοίας (vel ὑποψίας) ἢ legerunt | Sop. V 55, 17 W.: πρὸς τὸν Μινουκιανὸν (cf Christoph f. 25 r, Rhein. Museum 50, 243) φι-λονικῶν τοῦτο ἐπινενόηκεν 2 περικλῆς ἐν τοῖς λογισμοῖς P βlLc, cf. 55, 7 | ἀνηλωκέναι Ac Ba Phy, (αη) P: ἀναλωκέναι, η m. 2, Vc 3 γρ καὶ ἀρχίδαμος παρὰ λακεδαιμονίοις δώρων φεύγει P | φεύγει δώρων Vc 5 καὶ τοῦτο post ἐνδέχεται Ac; om Py 7 cf. 54, 14 44, 2 | alt. ὁ om. Py 8 schol. P (W VII 135, 17, cf. 133 ann. 351 ann.): πρὸς Μδινουκιανὸν ἀποτείνεται; Sop. 55, 27 W. 8. 9 τὸ πρᾶγμα ἐνταῦθα P ch Vc Ba, Syr. (cod. V); ἐνταῦθα τὸ πρᾶγμα Pa Ac; πρᾶγμα ἐνταυθοῖ τὸ Py; τὸ πρᾶγμα ἐνταῦθα τὸ Pg, Syr. (cod S) Sop ; τὸ πρᾶγμα τὸ κρινόμενον ἐνταῦθα 10 τοῦ πράγ-ματος Py 11 δὲ om. m 1 Vc 12 ἐξισάζον μόνον Pa h Ac Ba; ἐξισα-ζόμενον Pc Vc 12. 13 schol. P (W VII 135, 27): πρὸς Μινουκιανὸν ἀντιλέγει 14 κατὰ ταυτὸν post 15 ἐξιόντας Ph: κατὰ ταὐτὸν ἄμφω om. Py 15 ἀπὸ (pro ἐκ) Ba Py; cf. 32, 16 17 δὲ πράγματα Vc
marginal 6
marginal 136
footnote 4 Christophorus (Rhein. Μuseum 50, 243): ἀποτείνεται πρὸς Μινουκιανὸν κτλ. 7 ἀλλὰ (pro καὶ) Sop. |μὴ προειλημμένον P Vc, Sop., (προσ-) Ph; μὴ προειλημμένον τῆ κρίσει Ba Py, v.l. P; βτ | ῆι] κρίσει μαὴ προειλημμένον Ac |δυνάμενά? (Syr. 2 p. 37, 13: ὥστε . . δύνασθαι τὸ ζητούμενον ἐπιδέξασθαι πέρας) |δὲ (pro τε) Ph, Marc IV 146, 4 W. 8 δʼ οὖν τινὸς τούτων Ac Py, v. l. Pa, Marc. IV 177, 25 W |ἐνδι P 9 καὶ om. Ba 10 γε om. Sr, Syr ; μὲν Py |ὧι καὶ τὰ Py: ἐν ὧι τὰ schol. P (W VII149, 15) 13 φόνου φεύγει Py 14 cf. 30, 13 15 ἑκάτεροι ante ὡραίας add. Ba Py, post γυναῖκας v. l. P, cf. 31, 13; γυναῖκας ἔχοντες ὡραίας Ac | ἄμφω γυναίκας ἔχοντες ὡραίας κατὰ ταυτὸν Ph ἄμφω om. Py 16 ἐξιόντας ἀλλήλους ἐκ P 17 κατὰ om. Ac, Syr, Sop. 21 παραθήκην Ph | ἀπαιτεῖ Ph; ἀπήτει PV Py
marginal 7
footnote 1 ἔλεγεν (om. ἔτι) Py 2 3 ἄμφω τοῖς ἑαυτῶν Pc Ac 3 γεγόνασι Pγ |λόγοις om. Ph |κατὰ om Syr., Sop 4 λαβεῖν P Vc εὑρεῖν Ac Ba Phy, schol Ph f. 131v, Marc. IV 156, 12 W | ἀλέξ-ανδρος ὁ βασιλεὺς Py 6 συμβουλεύσηι Ac, v. l. Pa 7 αὐτῶ Phy; om Wc | κατὰ om Syr., Sop. 8 πλάττοι Ac Ph 9 κατὰ om Syr.; δὲ Sop. 10 cf Demosth 13, 34; 17, 23 10. 11 Py | περὶ ἀρχῆς τῶν ἑλλήνων βουλεύεσθαί τις λέγοι Ac Ba Ph, (λέγειοι, οι m 2) Vc 11 cf. Plat Apol 21 B 12 κατὰ om. Syr., Sop. |ἐμισθώσατό Ph 13 ἀπολαμβάνων V Ph y, v. l. ἀπολαβὼν P 14 κατὰ om. Syr., Sop. 15 ἀποκηρύττει τίς τὸν ἑαυτοῦ υἱὸν Ac Py 17 εἴδη τῶν ἀσυστάτων ἐστιν ἕτερα· Pb, (εἰσὶν) Py | ἕτερα om. Sop. 19 τοῦ κριτίου Ac Ph 20 οἱ ἀθηναῖοι Ph |δεῖ PV: χρὴ Ph; χρὴ αὐτὸν Py
marginal 8
marginal 137
marginal 9
footnote 1 τοῦτο Ba 2 εἶτα V Py, Sop., v. P; δεύτερον P: ἐῖτα δεύτερον Ph 8 cf. Thuc. 7, 10 |τις | cr. VII κλέωνα στρατηγεῖν Vc; τις πέμ-πειν κλέωνα στρατηγεῖν Phy; τις κλέωνα στρατηγὸν πέμπειν Sr 5 γὰρ αὕτη ἡμάρτηται Vc 6 7 ἐπεὶ τεθνάσι γὰρ δήπου κλέων τε καὶ μαρδόνιος, ὁ μὲν πρὸ Py 7 μαρδόνιος ἐν πλατεαῖς πρινὴ Ph 10 ὁδὸν Pc 18 ταύτης Ph, (post καταψηφ.) Py 15 post τοιαῦτα add Pl, m po Ba: καὶ περὶ μὲν τῶν ἀσυστά-των τοσαῦτα 16 γε περὶ Vc Ba Py 17 εἴνεκα Ph |τρόπων Ac Ba Py; τρόπων οὐ Ph |Syr. 2 p. 42, 13: εἰς Μινουκιανὸν αἰνίττεται κτλ. 20. 21 τὰ προβλήματα μελετῶμεν om Pc (init. fol..) 22 ἐπιδεικτικῶς τὸ ἐπιδεικτικόν Vc Py, (τὰ ἐπιδεικτικά) Ac; πανηγυρικῶς τὸ ἐπιδεικτικόν P; ἐπιδεικτικῶς τὸ πανηγυρι-
marginal 10
marginal 138
footnote κόν Pg Vk; πανηγυρικῶς τὸ πανηγυρικόν Wc, ( |πανηγυρ m. po. | ικῶς) Ba, cf W VII 167, 7, Marc. IV 193, 26 W.: πανηγυρικῶς τὰ ἔνδοξα Sοp., (add καὶ ἐπιδεικτικῶς τὰ ἐπιδεικτικά) Ph: om Syr.; Vk mg.: ἐπιδεικτικῶς. πανηγυρικῶς ἔν τισι δὲ τῶν βι-βλίων ἀποδεικτικῶς γράφεται, ἀντὶ τοῦ ἀγωνιστικῶς κτλ. 2 διαιρέσεως ante 3 τῶν Ac Ba Phy, cf. Sr, Syr 4 δὴ τοῦτο Sop.; δὴ om. Vc Ac Py 6 γ᾿ ὀῦν Ph 7 καὶ om. Pab 8 τι λέγειν ἐπιχειρήσωμεν Pc | περὶ αὐτῶν λέγειν Vc Ba Pb νῦν Py 9 Agathon. fr. 11 N. 2 | alt ὁ om. Vc Ac Phy | ἂν etiam post γένοιτʼ Ba Py 10 μικρᾶς Pcy | alt καὶ om. Ac 11 τε om. Syr. 17 εἰδὼς Syr 2 p. 46, 25 (at 47, 6) | schol P (W VII 170, 13; cf. ann. 58): ἀποτείνεται δὲ πρὸς Μινουκιανὸν ἐτυμο-λογήσαντα; cf. Marc. W IV 195, 16 Sop. IV 199. 4 W 18.19 τοὺς ἀγωνιζομένους om. Syr. 2 p. 47, 12 (at 47, 17)
footnote 1 καὶ ante ὅπως add. Ba Ph, (supr.; m. 2?) Vc | τοῦτο P Ph, m.2 Vc (p 43, 9: τὰς στάσεις; W VII 174, 10: τὴν μέθοδον . . . διʼ ἧς ἑκάστην τῶν στάσεων ἐπιγνωσόμεθα); τούτων Vc Ba Py; τοῦτοων Ac 2 μέθοδος: l. 6 — p. 43, 8 (cf. Sop. V 78, 28 W.): διαίρεσις; p. 43, 15 sq. 3 τοῦ στοχασμοῦ Phy Sr, Syr. 4 αὐτὸ Vc Pγ; τὸ πρᾶγμα αὐτὸ Syr. (cf. Herm. p. 425, 14 Sp); αὐτὸς P Ac Ba Ph. m. 2 Vc | πάντων τῶν ἄλλων Ph: τῶν ἄλλων ἀπάντων Py 5 λέ-ξεται Pc | δʼ om Ph 6 sic mg. Ba Pg Wc, (ἡ μέθοδος) Vδ; δι-αίρεσις τῆς μεθόδου τῶν στάσεων P Ρπ διαίρεσις τῶν στάσεων Py ; περὶ στάσεων (ante 5 ἡ) Ph; μέθοδος διαγνώσεως τῶν στά-σεων DLz; om. Vc Ac ; Syr. 2 p. 53, 24: ἡ δὲ μέθοδος τῆς διαι-ρέσεως τῶν στάσεων; cf. Glöckner l. l (p. 28, 9 ann.) l 28 7 προ-τιθέντος Pc | συνέστη ιει Pa | mg. Vc: ῾ εἰ συνεστήκοιʼ . . πρὸς . . Μινουκιανόν 8 ἠ pro εἰ m. 1 Vc 10 οὐσιωδῶς Ba Sr, m.1 Ac, W VΙΙ]) 179, 24, Sop. 11 ἢ — 12 ὑποψίας om. Ph; deleverat Glöckner, Quaest. rhet, dissertationis thes 2 (collatis Syr. 2 p. 61, 21. Marc. IV 214, 18 W. Sοp. V 85, 8 86, 28 W. adde Sr) | καὶ m. po. supr ante ἢ Ac 12 cf 30, 19. 49, 16. 54, 5. Auct. ad Her. I 11, 18. Quin IV 2, 13 Cic. de inv I 8. 11 14 ζητοῦμεν om m. 1 Vc
marginal 139
marginal 12
footnote 2 ἢ (pro εἰ), om. πάλιν ἐπισκεπτέον, Sr | μὲν ante ὧι add. Pc 3 τι γίγνεται Vc, (γίν.) Ba | μετὰ ταῦτα post καὶ add. Phy 4 τὸ πρᾶγμια om Ph (signum ascriptum est) 5 ὁριστικὴν Ph |ποι-εῖται Vc; ποιεῖ Sr 6 ὁριστικὴ Ph | περὶ πρᾶγμα Marc IV 220, 13 W 7 τοῦ ζητουμένου ὀνόματος Syr. 2 p. 97, 25 8 cf 62, 3: Arist. Rhet A 13 p. 1374 a 4. Cic. de inv l 8, 11 Quint III 6, 41. V 10, 39 10 11 εἶναι κλέπτης V Phy 11 προστεθῆ P Ph: προσθῆις V Py, v. l. Pc 12 γε P Phy ; τε V 13 ζήτησιν οὐδεμίαν Py (cf. l. 4) 16 εἰ συμφέρον εἰ νόμιμον (mg εἰ ἔν-νομον) Ph: εἰ (ἢ Vc) συμφέρον εἰ (ἢ Vc, Sοp.) ἔννομον V Py, Sop., cf Marc. IV 224, 8 17 W 17 ὡς γενικὸν Sop. V 90,18. 20. 97, 6. 9 W., Nilus | τούτων Nilus | κοινὸν Sr | W IV 223, 4: τοὺς περὶ Ἑρμαγόραν ἐλέγχει κτλ. 18 περί τι ῥητόν Ph 19 ῥη-τὸν ᾖ Of, Marc. IV 224, 30 W. | ποιήσει Ph: ποιεῖται Py
marginal 13
footnote 1—9 cf. Arist Rhet. A 3 p.1358 b 3 sq. 2 πράγματος ante μέλλοντος Pf: om. Vδ Pq, Marc. IV 225, 28. 226, 3 W. 4. 5 μέλ-λοντος πράγματος Ac Py 6 δοῦναι ἢ P: ἢ δοῦναι τόδε τι ἢ V Ph, Nilus, (om. τόδε) Py, (om. τι) Pf, (om. τόδε τι) schol. P W VII 192, 18—26 | ἀθηναῖοι post 7 θάπτειν Ph 1 δεῖ Pγ |[III] τῶν Vc 9 cf. p. 37, 17 11 γὰρ om. Ac 12 οὐχί Vc Phy 14 γὰρ PV Py ; δὲ Ph 18 οὕτω sc δίχα, p. 37, 18. 38, 1; 10 | καὶ τοῦτο ante οὕτως Ba; om. Pf |ἢ γὰρ Ac 21 ἀντίστασιν ποιεῖ Pf, Marc. IV 240, 2 W. | γὰρ PV Py ; δὲ Ph 28 ἀνθιστῆ Ac Ba ; ἀνθί-στησιν Vc Ph y, Nilus ; ἀντεισάγῃ Pf Syr. 2 p 139, 3: ἀντιτιθῇ εὐεργέτημα PPh, cf Syr.; εὐεργέτημα μεῖζον V Pγ, v. l. P; μεῖζον εὐεργέτημα Nilus, Syr. l l 12; p. 73, 14. 83, 15
marginal 140
marginal 14 2 ἢ — 3 παθόντα om. Pc |ἕτερον γίγνεται post τι add. Ph ἂν μὲν γὰρ εἰς Ph |αὐτὸν τὸν Ac 6 τι om. Sop |μεθιστῆι Vc, Sop., Nilus; μεθίστησι Ac Phy 7 τι om Nilus; τι καὶ Pc 8 τὸ (pro τι) Pc | πεποιηκέναι τι Ba 11 μὲν P Ba Py; δὲ Vc Ph ; om. Ac | cf. Cic. de inv lI 29, 87. 42, 124 12 ὃ|ν er.] Pa; ὁ Pf Vk 14 δὲ καὶ Py 15 δὲ om. Ac | παράδειγμα om. Pf | alt οἱ om. Py 17 schol. P (W VII 206, 15): πρὸς Μινουκιανὸν κτλ τι Pa h Ac Ba; om Pc γ Vc ; ἡμῖν τι om Vγ, schol. P 18 μετα-στάσεως ἕνεκα Vc Ph | p. 75, 11 20 οὕτως (pro ἐκ τούτων) Ba 21 μὲν οὖν Ph 22 ῥητὸν Pγ, Marc. IV 254, 20 W. al. | ἐν-ταυθοῖ Py
marginal 141
marginal 15
footnote 1 κηρύγματα, ὡρισμένα πάντα Nilus, schol. P W VII 213, 6 (cf. Sοp. V 103, 4 W.) 2 [ἢ] καὶ P W IV 255, 16, ἢ περὶ 256. 1: ἢ καὶ περὶ Ah Oh Vg 2. 3 συμβαίνει γίνεσθαι Py 4 διήιρηται Ba Ph, m.1 Vc ὁ om. Ac 5 φαίνωνται χρώμενοι Py 7 τὰς ante 6 περὶ Ph 7 διανοίας τούτου Ac | καὶ post ἢ Pf: om. V Phy 8 ῥητὸν καὶ διάνοια γίνεται PV γίγνεται καὶ ποιεῖ ῥητὸν καὶ διάνοιαν Ph, (om. pr. καὶ) Sοp., (om. γίγνεται καὶ) Pf 10 τὸ P Vc Ba Py, schol. Ph f. 142r; om. Ac Ph | schol. P (W VII 212, 15): ἵνα μὴ δόξῃ πάντα ἐναντιοῦσθαι Μινουκιανῶ, διὰ τοῦτο προσέθηκε τὸ ῾ ὡς ἐπὶ τὸ πλεῖστονʼ 12 εἰ ante 11 ξένος Ph: ante ἐπὶ Vc, cf. 82, 11 cf. Cic. de or. II 24, 100 Quint. VII 6, 6. Aps. 2 p. 273, 2 Sp. -H. πολιορκίας — 13 νόμῳ om. m. 1 Py 14 τι om. Sr, Nilus | τἀυτὸ| συν m. 1, ex ν] Pa; cf. l.17 15 ἄγον Vc, (ω, supr ο) P: συνάγον Py τὸ ἔγγραφον τῶι ἀγράφωι Vc, Sοp. 17 συνάγοντος εἰς τἀυτόν Ac Ba Ph | τινος om. Py 18 cf Quint VII 6, 3. Aps. l 2 p. 275, 5
footnote Sp. -Η. 19 λέγειν post τις Ac 20 ἂν Py, ἐὰν Sop. l ῥητὰ ἦ ἢ Nilus | ἢ καὶ πλείονα om. m. 1Py |pr καὶ om. Ph 1 εἴη post 40, 20 ἓν (om. εἰς δύο) Ac 3 ἐναντίου Ph, m. 1Vc 4 δὲ om Ph 5 ὁ supr Ph: om Pcy ; cf 85, 1 6 cf. Auct ad Her. I 11, 19. Cic. de inv. II 51, 153 7 τῆς νεώς Pc V Phy, mg. Pa; αὐτῆς Pa | ἔμεινε Pc | πατρώαι ante νηὶ add. Vc Ph, cf. 85, 3. Syr. 2 p 196, 8 8 ἀπείργεται Ph 9 cf. 87, 14. Senec. controv. l 5 cet 10 ἢ θάνατον ἢ γάμον Ac 11 κόρας post τις Syr 2 p. 196, 11 ; om. Vc Ba Phy 13 ἀπὸ τοῦ (om αὐτοῦ) Vc Ba Ph Sr 15 διαστάσεων Ac | γενομένη Py 10 cf. Theon II 129, 19 Sp. Cic. de inv. II 40, 118 | εἰ χρυσία Vc Pγ 10 18. 19 χρύσεια Ph: cf. 91, 2 17 τις om. V Ph 18 εἶναι Pcy; δεῖν εἶναι Pah V, Syr.; cf. 91, 4 19 νόμον m. 1, τόνον m. 2, Vc 20 ἀνταναγινώσκοντες Phy, v. l. P 20. 21 περὶ δὲ διαστάσεως Md Οh, (ἐκ pro περὶ) DLz 21 cf. Quint VII 9, 6
marginal 16
marginal 142
marginal 17
footnote 1 ante διέθετο: add καὶ La R Vu: add. τελευτῶν Px VIW Wa; add καὶ τελευτῶν Ba, m. 2Vc; add καὶ τελευτῶν ὁ πατὴρ Pγ 2 καὶ om. V Phy γρ΄ ταύτην Pa | οὖν om. Py, Nilus | δέ γε Ba 7 τῆι post γὰρ add. Phy, (er.) Vc 8 ἔσται Pc | τι om. Ac, Nilus | ζήτησις Ph: ἡ ζήτησις Py; ζητοῦμεν Nilus 9 ποῖον Ph, Nilus 10 ταῖς λοιπαῖς Py; ἐν λοιπαῖς Nilus (at 75, 1 cet.) ζητῆσαί τι τούτων P Ba Ph, m. 2Vc: τὸν ἀγῶνα εἰσελθεῖν Vc Ac Py 14 τῆς εὐθείας Ph, v.l.Pa 15 περὶ ὃ Ac |cf. Demosth. 20, 147. 38, 16 Quint VII 6, 4 16 δὲ post ὕστερον add. Vc Phy: cf. Syr. 2 p. 159, 7 19 mg. ἐν ἄλλοις τὸ εἰ ἐφόνευσέ πουʼ οὐκ ἔστιν Pa; verba desunt Py 20 ἐστὶν ἀπαγωγὴ μὲν Vc | Phy εὐθείας Ph 21 δὲ ζήτησιν Pγ
marginal 143
marginal 18
footnote 1 cf. 45, 22. 47, 10. Π. εὑρ. p. 212, 19. 28 Sp. |τόπον ἢ χρόνον etiam post τρόπον add. P, m. 2Vc | ἢ ὅταν Py 3 λαμβάνοντες Pa |cf. Senec. controv. l 4 lX 1. Quint. VII 1, 7 | ἀποκτεῖναι Py | καὶ om. Py 4 μεμοιχευμένην Pc, cf. Syr. 2 p. 154,8 6. 7 φεύγει φόνου Vc Ba Phy 7 χρόνον. τόπον Pa 10 περὶ δὲ ἑκάστης διαιρέσεως Ac, v. l. P | ἕκαστον Ph 13 τὰ om. Pcy 15 sic Vg; περὶ τῆς διαιρέσεως τῶν στάσεων P: om. V Phy; exsp. διαίρεσις τῶν κεφαλαίων, cf. 36, 3 16 περὶ διαιρέσεως στοχασμοῦ Ba; περὶ στοχασμοῦ διαίρεσις στοχασμοῦ Ph; περὶ στοχασμοῦ καὶ τῶν κεφαλαίων αὐτοῦ Wc 17 καὶ om Py 18 ἔχει Py 20 τῆς αἰτίας Py
footnote 2 p. 31, 7 cf. Aps, l 2 p 223, 25. 276, 15 Sp. -H. |post ὑπερβάλλοντος add. Ph : ὅτ᾿ ἂν πλέον τι συνάπτηται τῆι τοῦ κρι-νομένου ὑπερθέσει ἐκ τῆς τοῦ πράγματος περιστάσεως, schol. P (W VII 261,11) 6 ἀυτῶν ἁυτὸν Ph |ὅτι om. Ac 7 πεποιή-κεισαν Py | cf. 30, 23. 50, 5 7. 8 ἀριστεὺς Pc 8 καὶ ante προδοσίας add. PAc 10 ὕστερον post 11 χρόνοις Ac; om. Py φήσει Spengel (at 63, 21 cet.) 12 ἰσχυρότερόν Py 13 τὸ παρα-γραφικὸν post δὲ add Ba Ph, (er.) Vc 13.14 συμβάλλεται δʼ οὖν τι καὶ σμικρὸν Vy 14 τι τῶι χρωμένωι καὶ σμικρόν Ph, (om καὶ) Vδ |χρωμένωι· |cr. IV] τοῦ |δὲ m. po. supr.] ἀπὸ Vc τοῦ ante ῥητοῦ add Pc h Ac, (er.) Vc 16 οἷον κριθείς Py | ὕστε-ρον om Ph 16. 17 ὕστερον δὲ αὐτῶι χρωμένωι Py 17 ἀνεῖ-λεν ὁ θεὸς Ac Py 18 cf. 42, 15 18. 19 οἱ νόμοι κωλύουσι Py 19 νομοθέται Vc | παραγράφεται οὖν ante 18 δὶς transq. ? | τὸ om. Py
marginal 19
marginal 144
marginal 20 1 ἡ τῶν om. Pγ |διττή Ac Py Sr, Sοp.; διττή τίς Pγ 2 οἱ om. Sop. W IV 329, 27: cf. l. 8 | cf Senec controv VI 6 3 αὐ-τὴν om. Pγ 5 ὁ πατὴρ om Pa 6 τῆς om. Pγ | πλέον om. Pγ; εἰδέναι πλέον Ph 8 οἱ om. Py 9. 10 ἀπαιτήσεις . . δια-βαλεῖς Pc 10 ὅτι μὴ δεῖν Ac | cf. Senec. controv. VI 6 p.262, 15 M 12 σχολὴ γὰρ m.1Vc 13 πιστεύσαοιιμεν Pa 14 καὶ om. Py, Sop. 15 μᾶλλον om Vc Ba Py, Sop. 16 ὁ om Ac Dem. 54, 31 sq 17 τεχνικόν τι Phy | θεώρημα· τουτέστιν ἢ Vc Ba Ph 17—19 ῾ aut ἢ ante διαβάλλειν del., aut διὰ τὸ ante μὴ εἶναιʼ Spengel 18. 19 αὐτοῖς Pc; αὐτῶ Vγ 21 αὐ-τοὺς om. Ac 22 cf. 43, 1 | πράγματι οἶον τί δούς post 46, 1 πῶς Ph: om. Py
marginal 145
marginal 21
footnote 2 ἢ τοῖς πᾶσιν ἢ Vc Ba Phy; ἤτοι πᾶσιν ἢ Vb 3 ἀποφαίνει Ph 4 τῶν om. Ac 5 πεπλασμένα Ph |cf Arist Rhet. A 15 p. 1376 a 19 5 6 χωριζόμενα τῆι λέξει Ph 7 ταῦτα Py; τὰ τοιαῦτα Ph 10 τὸ om V Phy, Marc. IV 347, 22 W 11 ἄλλων εἴη Vc Ba Phy, Marc IV 348, 24 W 12 ἔχεις Ph, Marc. IV 348, 27 W., (σ m 1 supr.) Ba: ἔχει P Vc Ac Py 15 cf. 15, 18 sq 16 τε καὶ Ac | cf. 16, 10 16. 17 πρᾶξις Vc Ba 17 πένης ἢ πλούσιος Py | καὶ τὰ ὅμοια Ph 18 ἀφʼ P Pγ: ἐφʼ V Ph 21 γὰρ om. Phy οὕτω om. Phyρ 22. 24 (ἂν om.) φαίνεται Pc 28 αὐτῶ Py
marginal 22
footnote 1 μόνων Ba, (ο supr.) Pa Vc | ὅσωνπερ Pγ 1. 2 ἂν ⌊I-II⌉ ⌊έ⌉χηι Pc 2 cf. 48, 7 4 τῶν προσώπων ante τῶν add. Pγ 4. 5 τῶν ἀποκηρύκτων post 4 τῆς Pc 5 ἐταζομένης Py 6 τοῖς — 7 κρίσιν om. Py 9 αὐξάνεται P | alt. καὶ om. Pc 10 cf. 42, 22 11 κατηγορουμένου Ph, m.1VcPγ | μόνου om. Phy γ, m.1 Vc 12 τὰ om. Ph 13 χρῆσθαι PV Sr; χρήσασθαι Phy γ 15 ὁ στοχασμός Py 16 κοινὰ om. Ac 18 μετεώρου τῆς δίκης οὔσης ante ὁ add. Ac Ba, m.2 Vc, cf. Syr. 2 p. 77, 14 19 τὴν post γέρας add. Pc; αὐτοῦ add. Ph 20 καὶ om. Vy | ἐτυράννησεν, mg. νευ m.1, Ph 21 οὗτος om. VcBaPhy γ 22 αὐτὰ Ph, m.2 Vc 23 ταῦτα Py, v.l. Vk
marginal 146
marginal 23
footnote 1 δήπου ante λῦσαι add. Vc Ba 7 τούτου Ph | πάντας post ἀποκηρύκτους Vc Ba; om. Ac 7. 8 τρέφει τις τοὺς ἀποκηρύ-κτους νέος πλούσιος καὶ Ph, (om. τις) Ac 8 φεύγει ante τυ-ραννίδος 10 de Minuciano cf. Georg. p. 753 Schilling 11 τῶι στοχασμῶι Pc 12 cf. 60, 13 | ὁποτέρωι Sop. 12. 13 τούτω Ac; om. Pγ, Sop. 13 λέγω ἢ τῇ μεταλήψει om. Ph 15 τε om. Ac Py 16 φησὶ Vc Ph 18 οὐκ, om. οὕτως οὐδὲ, V Phy | τ⌊οι m. 2supr.⌉ούτοις Vc | cf. 30, 1. 51, 13 20 ὡς μὴ Vc Ba Phy 21 ἀλλʼ ante οὐχ add. Py, supr. Vc | τοιούτοις Ac Phy, m. 2Vc. (m.1 ex τούτοις) Pa | ποτέρωι δὲ π⌊ρ postea add. m. 1 ⌉ότερον Pa; ποτέρωι δὲ προτέρωι( ποτέρωι Ph) Vc BaPh; π⌊ρ m. po. add.⌉ότερον δὲ ποτέρω Pγ; πότερον δὲ προτέρωι Ac, Marc. IV 380,28 W.
marginal 147
marginal 24 4 de Minuciano cf. P (W VII 315, 10) 5 δύναηται P 6 ἀπαι-τῆι μᾶλλον Vc; μᾶλλον om. Py | ἀπαιτεῖ Ph | μεθοδεύοιμεν Ac Py 11 νύκτωρ post δεσμωτήριον Ac Ph | ἐπὶ Pc Vc Ba, (εἰς supr; m.1 ?) Pa; εἰς Ac Phy 12 ὦ δεσμῶται PAc, cf. Syr.2 p.83, 29; om. Vc Ba Phy | εἰσἀῦθις γὰρ καὶ ante οὐκ add. Ac 16 ἐξετασθήσε-ται Ph, Sop. | cf. 36, 12 18 φόνου φεύγει Pc | ἐρεῖ γὰρ om. V Phy | cf. Aps. l 2 p. 235, 10 Sp. -H. 20 τῆς αἰτίας om. Vc Ba Phy | γίνεται P, εἰσάγεται V Phy | cf Aps. l 2 p. 243, 13. 273,12 Sp. -H. 22 mg. φήσει Ba
footnote 1 στοχασμοῖς om. Vc Ba Phy γ, Marc. IV 395, 9 13 W. 3 ἄλλοι Ac Ph 4 γίνεται Ph: γενήσεται, om. ἔσται, Py | πεπλα|νη m.2 ex σ⌉μένη Vc Ba 5 cf. 44, 7 | ἀνέστησαν Vc Ba Ph 6 οἱ πολέ-μιοι ante 5 εἰκόνα Vc 8 ὑπʼ (pro παρʼ) Ph | ἐξιλεούμενοι Pc ἄλλως πῶς Vγ: πως m. 2 supr. Vc 10 δύναανται Pa δύνανται Pc δεῖν post χρώματα Vc BaPhy; om. Ac Vγ 12 τις ante αὐτὸς Ac Ph, ante πεποίηκε Vc Ba Py, Marc. IV 396, 21 W. |ἢ εἰ καὶ Ph 17 οἱ supr. Pa; om. Ba Phy | ἀνειμένοι V Pc hy, (η supr.) Pa; ἀνειμένη Va kδ | ἤδη om. Pa 19 ἐναντιοῦται V Ph 20 ἡ προς περισσή mg m. 1Ba; cf. Va f. 46r, Sop. lV 402, 21 W. 21 χρῆται Vc Ba 22 χρήσεται ante ὡς Vγ, m. 2Vc: om. P
marginal 148
marginal 25
footnote 3 ἐφεώρων Ph 4 καὶ om., δὲ pro γε Vc BaPh 6 ἐφʼ ─ κρίσις om. Vc | ἐπιθεμένω Vδ k Wc, (τι m. po. supr.) Pa 7 προ-παρασκευάζεσθαι Py, (om. προ) VcBa |cf. Π εὑρ. p. 179, 29 Sp. 10 οὐ γὰρ δύναται Vδ k; οὐκ ἂν δύναται Ph οὐ δύναται γὰρ Vc Ba | ὅτι (pro τὸ) Vδ k 12 καὶ om. V 13 ὁρικῶς Ac, v.l. m. po. Pa ἐξετάζει Py | cf. 30, 1. 48, 18 14 μοιχείας Ac Ph | τὸ m. po. suppl. Ba 17 ἀντεισακτέον VcBaPy | εἰς αὐτὸ Py | κατʼ αὐ-τὴν VPhy, v.l.P: καθʼ ἑαυτὴν Pa, (αὑτὴν) Pc 18 ἀντιστρέ-φειν Pc, (ἀνα supr.) Pa; ἀναστρέφειν VcBaPh; ἀντιστρέφον Ac, Marc. IV 408, 27; ἀναστρέφον Py | alt. τὸ om. Ac Py; τὸ πρᾶγμα om. arc. IV 408, 27 (410, 13: τὸ μὴ ἀντίστρ|ο m.1 ex έ⌉φον τοῦτο) 19 μὲν supr. Ph, om. Vδ k 20 ἀναγκαίως add. ante ὅπλα Py ὅπλα add. post γε Vδk
marginal 26
marginal 149
footnote 1 ὅπλα παρασκευάσασθαι Ba, m.1 Vc | παρασκευάζεσθαι P 2 μὲν om. Ac | γε om. V | cf. Arist Rhet. B 24 p. 1401 b 24. 13 sq. 7 γίνοενται Pa; γίνεται Ac |ἀλλʼ οὐκ Ph 7. 8 γρ οὐκ ἐν στοχασμῶ μόνον ἀλλʼ ἔνθʼ ἂν εὑρίσκηται Pa, (. . ἔνθα καὶ εὑρίσκεται) Pc; mg. ἀλλʼ ὅλως ἔνθα ἂν εὑρίσκηται m. 2Vc 8 μό-νω Ac 10 εἴη Vc Ba Py | καὶ om. Ba 11 ἀνακεφαλαιουμένων, ἐπ m.2 add., Vc; ἐπανακεφαλαιούμενόν Ph 13 ἐπέδειξα οὐδὲν Dem. 19,177 | αὐτὸν post ἀληθὲς add. Ac, m.2 supr. Vc | ἐπηγ-γελκότα Pa 15 μὲν καὶ αὐτῶν ὁμοίως; καὶ αὐτῶν μὲν ὁμοίως P: μὲν ὁμοίως καὶ αὐτῶν Ph: om. καὶ αὐτῶν Py, ῾ Metroph. cet. IV 423. 9 W. 16 τε om. Pc 17 αἱ (pro καὶ) Py; καὶ αἱ Vδ; γὰρ καὶ Ac; δὲ καὶ Wc | τῶν τε Vc Ba 21 καὶ τὸ δί-καιον καὶ τὸ (τὸ om. Ac) συμφέρον καὶ δυνατὸν V Ph | καὶ τὸ ἔνδοξον Py
marginal 27
footnote 1 τε PV Pγ (p.73,7); δὲ Ph, Marc. IV 421, 1 W., (τε supr.) Vδ 3 ἕνεκα ψυχῆς Ac |εἰσάγονται Vγ 3. 4 φόβου ὀργῆς ἐλέου φθόνου, Py 6 δέξασθαί τι Pc | ἀπώσασθαι Nilus 7 δέον post ἐπιλόγους add. Ph; non expedio | prius ἢ supr. Ac, om. Pc | γρ τῶ διὰ τῶν κεφαλαίων Pa, (τὰ διὰ) Pc; num διὰ τῆς ἀνακε-φαλαιώσεως? 8 τότε Vc Ph; τό,τε Py; τῶτε P, m. po.AcBa (?m.1); τινὲς τὸτὲ γράφουσιν, ἀντὶ τοῦ ποτέ mg. P: τοτὲ δὲ Vγδ, m. 2Vc τελέως V Phy, v.l.P | ἐξαίρειν τελέως Ba, (ἐξαιρεῖν cr, m. 2?) Vc | καὶ ἔτι V Phy, v.l.Pa; καὶ ἔτι καὶ v.l.Pc; καὶ ὅλως P | ἐν τούτω — 9 προοίμια suppl. m.2.Vc, (. . ἐπίλογοι τῶν προοιμίων) m.po. Ba | ἐν τούτω Ac Phy, v. l.P; ἐν τούτοις P 9 καὶ τὰ προοίμια P Phy; τῶν προοιμίων Ac, v.l.P (de VcBa: 1.8 ann.) 10 ἤδη καὶ κατὰ Py |πλέον Ac 11 προσάγεσθαι Py 12 ὡς (om. περ) Py δὲ ἡμῖν Syr. 2 p 3, 6 13 τῶι, οῖς supr., P | non est Π. εὑρ. p. 187 Sp. |προοιμίων Ac |ταῦτα om. Py, m. 1Vc, Athanasius (Rhein. Museum 64, 553 l 29), Syr. 2 p. 3, 7 15 αὕτη ἐστίν Py | καὶ — στοχασμῶν Ac, (τινες ante καὶ; ἀτελεῖς in textu, mg. m. po. ἁπλοῖ) Ba; καὶ ἀτελεῖς τινες αὐτῶν στοχασμοὶ Vδk, (καὶ postea add., m.1?) Ph; τινες καὶ ἀτελεῖς αὐτῶν στοχασμοί P; (καὶ ἀτελεῖς m. 2 suppl, post δέ) τινες ⌊lI—III⌉ τῶν στοχασμῶν Vc; τινες αὐτῶν στοχασμοὶ (om. καὶ ἀτελεῖς) Py; καὶ ἁπλοῖ τινες ἀτελεῖς στοχασμοὶ Sop. | τῶν 〈ἁπλῶν〉 στοχασμῶν?
marginal 150
marginal 28
footnote 4 τὸ om. Phy |ἦι post 3 ὅταν Py |εἴη Ph, Nilus 5 cf. 49, 16 6 ἐφωράθη VcBaPh 7 τοῖς πᾶσιν Pc 8 τοῖς τελείοις Ba Py, m. 1Vc 10 στοχασμός om. Pγ | γε om. Pγ 10 sq. p. 31, 7 sq 12 γοῦν Ac 13. 14 τὸ πρόσωπον μόνον m. 2 Vc 14 οἷον ἀσώ-του Ac Phy, m. 2Vc 15 φόνου φεύγει Py |οὖν P Ac; μὲν Vc Ba Ph; μὲν οὖν Py γ 19 τῆς om. Ac, Marc. IV 437, 37 W. | τῆς αἰτίας αὐτὸν Vc Ba Py, (om. τῆς) Sοp. 20 ἐστιν Py, Sοp. V 143, 8 W. | ἡ ἀπολογία Vc Ba Phy γ, Sop. 21 ἀγωνιεῖται om Pγ Sr | μὴ ἔχων πρᾶγμα· τί δαὶ Pc Vc Ac, (δὲ) Ba, (δαί;) Pa; εἴ γε μὴ ἔνι πρᾶγμα· τί δέ Py, (ἔστι pro ἔνι) Vδk; εἴ γε μη ἐνι (ἑνὶ Sr) πράγματι τῆιδε (τῆ Sr) Pγ Sr; εἴ γε μὲν ἑνὶ πράγματι· τῆι Ph 22 οὐ om. Py |τούτῳ Vδk; cf. Pγ Vγ: χρήσεται δὲ οἶμαι καὶ τούτω |ἀτελὴς ὁ τοιοῦτος m. 2 (καὶ τοῦτο m. 1) Vc
marginal 29
footnote 1 τὸ πρᾶγμα Nilus 5 καὶ om. AcBa | αὐτοὺς AcPh, m.2 Vc | τὸ κρινόμενον post ἀναφέρηται add. Vc, (m. 1 supr.) Ba; τὸ πραχθὲν add. Nilus 6 ὡς καὶ AcPh γ | pr. τοῦ om. Ac 7 ἐν τοῖς λογισμοῖς post 8 τάλαντα Pγ, om. Ac; cf. 31, 2 7. 8 ἀνηλω-κέναι Pa,(α m.2) Vc 9 fort. ἀτελὴς pro στοχασμὸς | προσώπων μόνων P 11 διπλοῦ τελείου Ac 12. 13 πράγματα . . πρόσωπα V Ph y Sr, W VI 54, 18 19 ??μφοῖν Py | διχῶς Vc 20 ἐβουλή-θην V Phy 21 ἠβουλήθης Ph |ἂν om. Vδ 22 ἐξετάσωμεν VcBa; ἐξετάζομεν Ph
marginal 151
marginal 30
footnote 1 τοῖς αὐτοῖς P Py, m. 2Vc; αὐτοῖς τοῖς Vc Ba Ph; αὐτοὺς τοῖς αὐτοῖς Ac 2 ἀλλὰ καὶ Py 5 cf. 55, 14 6 ἐπανηκότες Ac 9 γὰρ τὰ om. Py 10 διάφορα ὄντα Ac 11 πάλιν: cf. 54, 6 | alt. ἡ om Ba 13 cf. 55, 22 | ἐξέτασιν Pc 17 καὶ om. Vc Ba 21 ἔστι καὶ Sr; ἔστι δὲ Vγ 25 τι om. Ac 26 cf Aps Ι 2 p. 267, 6 Sp. -H.
marginal 152
marginal 31
footnote 1 συστρατήγῳ (συ er.) Vc, (συ m.1 supr.) Ba 1. 2 εἴποι Py: ἐξείποι Pγ 2.3 στρατηγὸς προδοσίας ἐδέθη V Ph γ 4 γυναικὶ ἀυτοῦ Ph | καταλαβών Pγ, Marc. IV 454, 20 W., Syr. 2 p. 93. 11 6 pr. τῆ P Ac Ph; om. Vc Ba Pγ | alt τῆι P Vc Ph, (mg : τῆ λε-γούσῃ λείπει) Ba; om Ac Py 7 ἕτερον P Py ἄλλο V Ph 10 πά-λιν PV Ph y; πᾶσαν Nilus, schol. P W VII 372, 11 | στοχασμοῦ om. Py, Marc. IV 455, 7.16 W 12. 13 ἦι προκατασκευασθῆναί τι πρᾶγμα Phy γ, v.l.Pa; ἢ προκατασκευασθῆαί ποτε πράγματι v.l.Pc; ἦ ζητῆσαι P 14 στρατηγῶν Ph |παῖδας ἐχθροῦ πέ-νητος Vc Ba 15 τρεῖς Phy, (ante παῖδας) m. po. Vc, cf. Syr. 2 p.93, 18; om. PV 16 μὴ Py |αὐταῖς post βασάνοις add. V Ph. v. l.P, Nilus 18 ἀπέκτεινεν ante καὶ add. VcPy,(er.) Ba 19 πρῶ-τον Py 21 pr. τὸ om. Py | καὶ om. Vγδ
marginal 32
marginal 153
footnote 4 θεσμοφορ⌊ίοις m. po.; ex οις?⌉ Pa 5 ⌊ὑπὸ m.po.⌉νοήσας Pc 6—8 sic P; γρ καὶ οὕτως· ἔλυσε τοῖς θεσμοφορίοις ἀποδημοῦν-τος τοῦ ἀνδρὸς ἡ γυνή· ἀπέδρα ὁ οἰκέτης· ἐπανιὼν ὁ ἀνὴρ εὕ-ρηται πεφονευμένος· καὶ μετὰ ταῦτα ἡ γυνὴ συνειδότος φεύγει mg. m. 1P, m. 2Vc, (ἔλυσεν αὐτὸν ἐν τοῖς; συνειδότος ἡ γυνὴ) in textu Ac (cf. Syr. 2 p. 76, 17. Georgius 701 Schilling). Differunt Vc Ba Phy ab editis: l. 7 παρὰ (pro ὑπὸ) Py; ὁ οἰκέτης post 6 θεσμοφορίοις Pγ, om. Vc Ba; ὁ ἀνὴρ (pro οἰκέτης) ἀπέδρα· μετὰ Ph l. 8 πεφονευμένος ὁ ἀνὴρ καὶ μετὰ ταῦτα ἡ γυνὴ συνειδότος Ph 9 ἀνηιρῆσθαι V Ph 10 καὶ τὸ (pro τό τε) Vc Ba 11 τὸ Ph, m.1Py | αὐτὸν ante ὑπʼ Ac | δεδέσθαι Ac, (in ras. m. po.) Pa 12 ἐκ (pro μετὰ) Sop. 17 τούτους m. 2 ex ταῦτα Vc Ba 20 μὲν om. VcBa 21 φόνου φεύγει V Ph γ
marginal 33
footnote 1 ὁ τοιοῦτος P Ac Py; οὗτος ὁ Vc Ba Ph | mg. λείπει τὸ ἀκού-σιον m.1Ba, (om. λείπει) Vc |⌊ὃ⌉ Pa; ὧι Ba, (ὃ m. 2 supr.) Vc 2 ὁμολογεῖται BaPh, v.l.P | ἢ om. Ac | ἢ αἱ Ph 3 εἰ καὶ μὴ μέμηνεν Ph | ἢ οὐ P Ph; om. V, m. 1Py, v. I.P 4 στοχασμοῦ Vc Ba 5 συσταίη Pγ, Nilus | de Minucianο: Marc. IV 472, 1.7 W. 6 ὅτι post γάρ add. P | τι post ἂν add. AcPγ | ἂν om. Ba, (ἄντι m. 2 supr) Vc γίγνηται Vc Ba Ph, Nilus 7 συμπλεκόμένο P; συμπλεκομένων Pγ | αὐτὸ post συμπλ. add. Ph, Nilus | εὑρίσκεσθαι P 7.8 τὰ τοιαῦτα P Ph; ταῦτα V Py γ 8 καὶ om. Vc 11 ὁ om Pγ γ 11. 12 συλλογισμῷ om. Ph (init. pag.) 15 ποιότητι κοινή καὶ Ph 17 ὁ ὅρος — 18 τέλους om Vγ, (mg. suppl.; παρεπο-μένων) Ac; cf. 60, 4 ann. 17.18 παρεπομένων Ph. cf. Ac (ann. 17) 18 ὁ⌊ῖον m. po.⌉ Pa |cf. Quint. VII 3, 7 19 ἀποθέσθαι PPy; κα-ταθέσθαι V Phy Vγ, v. l.P, cf. Marc. IV 502, 12. Syr.2 p. 101, 25. Anon. l 2 p.391, 9 Sp. -H.
marginal 154
marginal 34
footnote 2 τὸ αὐτὸ Ph |αὔξων post δὲ Ph 4 ἐκ τῶν παραλελειμμένων Ba, m. 1Vc; om. Phy |ὅρος χωρίζει — τέλους οὐκ (cf. 59,17. 18) Vy, (παρειμένων, supr. παραλελειμμένων) Ac, m. po. Vc 5 6 8 ὃ παραλελειπται Ph; om. Vγ 6 ὁ δὲ Ph 7 οἷον om. Ac 8 ὁ δὲ Ph 9 ταῦτα ante διαφέρειν Ph, Nilus; om. Pγ Vγ 10 ἐφά-σκομεν Ac | p. 48, 10 11 μάχεσθαι P Ac Phγ; ἕπεσθαι Vc Ba Py | τὸν αὐτὸν τρόπον Py 12 ἔνθα ἂν P ἂν om. Py; ἔνθα γε V; ἐνθάδε Ph 13 γοὖν P Pγ; ὀῦν V Ph 13 χρή-σεται V Phy, Sop. 14 χρήσεται V Ph, v. l. P, cf. 48, 12; χρῆται P Py | ἐπ Ph 17 καὶ om. Pγ Vγ | τὸ om. Ac | δίχα Ba, (ἄνευ m. 2.) Vc | σφαγῆς Nilus | θορύβων Vc Ph 18 ταραχῶν Pγ Vγ τούτων; ὅπλων P Phy; γρ τοῦ μετὰ τούτων καὶ ἐν ἄλλοις μετὰ τοιούτων mg. P 19 pr. δὲ om. VcBa 20 τῶν ἄλλων Pc
marginal 35
footnote 2 γρ καὶ περατωθέν P |ἀντεγκαλεῖ Py 3 τοῦτο VcBa 4 ὅτι om. Ph | ἥτις ἐστὶν ὅτι om. V Pγ, Nilus; ἥτις ἐστὶ μὴδὲ (ὅτι m. po supr.) Py; (ἥτις ἐστὶν om.) ὅτι οὐχ οὕτως Vγ | κρίνειν δὲ ἔδει Ph καὶ κατηγορεῖν P VcPhy; om. Pγ Vγ, v. P, Nilus, (mg. κατηγο-ρεῖν, om. καὶ) Ba; Ac: κρίνειν καὶ κατηγορεῖν, οὐκ ἀναιρεῖν ἔδει 5 ἔσται τις Ac 7 παραλαμβάνεται Pc 7. 8 τὸ πρόσωπον ὡρισμένον V Ph 9 μέν τι τῶν Ph |ἐξεταζομένων Ph, cf. 29, 13 sq. 11 λέξωμεν Vc Ba 13 ἐξετάσωμεν Vc Ba 14 μετὰ ταῦτα om. |εἰ ἀφεθῇ Ac; εἰ δὲ ἀφεθείη Ph |εἴθ᾿ PV; καὶ εἰ Phy 15 ἐξετάζομεν Ph: ἐξετάσομεν Py; ἐξετάζει PVcBa; ἐξετάσει Ac |ἡ δὲ Ph 16 ὑπʼ P; ἐπ᾿ V Phy γ, v. l. Pa |ἀμφοῖν P Py γ; ἀμφοτέρων V Ph, v. l.P 21 ἔστιν PahVSr, Nilus; εἰσιν Py; om. Pcγ, Sop. 22 τῶν ὅρων Sr | εἰρημένος Ph | p. 59, 18 sq.
marginal 155
marginal 36
footnote 1 ἐστιν om. Pγ Vγ 3 cf. 37, 8 |post χρήματα add. Vc Ba Py: νόμου ὄντος τὸν μὲν ἱερόσυλον τεθνάναι τὸν δὲ κλέπτην διπλᾶ διδόναι (om. καὶ) |εἶναι κλέπτης λέγει καὶ διπλᾶ Py 5 κατα-τίθεσθαι V 6 διαιρήσεις στοχασμοῖς Pc ⌊τοῖς del.⌉ διπλοῖς κε-φαλαίοις Ph; τοῖς om. V δk | cf. p. 55, 22 8 μὲν om. τί om. V 9 τοῖς PAcPh γ; τὰ Vc Ba | δὲ post ὁμοίως Ph 11 δὲ ὁ Ac Py 13 λέγει BaPh, (cr. η m. 1) Pa, (η m. 2) Vc 14 οὗτος ex οὕτως Pc; οὕτως Py |ὅπη PVcBaPy; τίνι Ac; ὁτίνι, πῆι Ph 14. 15 τιθέντες VcBa 15 τὰ παραδείγματα Py Vγ | ὡς δεῖ Pc ⌊lI,lII⌉ Pa; om. V Phγ |λέξωμεν Ph | p. 63, 14 17 cf. Quint. V 10, 39 | μὲν om. Py |αὐτὸν om. Pc 18 ἐπελθὼν Vc Ba | ὁ δὲ τιμωρίας αὐτὸν κατατίθεσθαι Ph 19 γὰρ καὶ Ba | τῶκ βιαίωι P Ac; κατὰ τοῦ βιασαμένου VcBaPhy 21 ⌊αὐτὸν del.⌉ ὑπεύθυνον ἀυτὸν Ph |αὐτὸν om. Py | φήσει Pc; φησὶν, ει supr. m.1, Pa
marginal 156
footnote 1 μὴ post 2 αὐτὸν Phy 2 αὐτὸν om. Py | ἀφίησιν αὐτὸν Vδk 4 γὰρ (pro οὖν) Ph 4.5 ἑκάτερα Py 6 εἰ Phy 7 Dem. 21, 25 cet. 9 τὸ ante περὶ add. PPy 10 τὸ τῆς — μὴ om. Ph | ἀδικεῖν περὶ τὴν ἑορτήν Pγ | ἵνα — 12 ἀδικεῖν V Phy, v. l. P om. P 11 delevi | ἀποδίδοσι (pro ἀπολύσῃ) Ph | τοῦ Spengel; τὸ PV Ph 11.12 ἀδικεῖν περὶ τὴν ἑορτήν Phy 13 τὸ om. Ph ἀδίκημα Py 16 τῶ ἐγκλήματι τὸ πρᾶγμα Ac | τὸ post ἱεροσύλῳ add. P Phγ 17 κλέπτηι V, v.l. Pc; τὸ κλέπτην Pc, (ν er.) Pa; τὸ κλαίπτην Ph: τὸ κλέπτης Py | cf. Arist. Rhet. A 7 p.1363 b 31 | καὶ κλέπτης P: κλέπτης Ph: καὶ om. V Py Pγ: ἱερῶν ἐστι δήπου κλέπτης χρημάτων 18 δήπουθέν ἐστι VcBa 19 τ|ὸ ex ωι⌉ Pa Vc | βίαιον VcBaPhy; βιαίῳ P Ac | post εἶναι add. Vc Ba: ἀλλὰ τῶι βιασαμένωι δημοσία ἠδικηκέναι ἕπεται 21 συλλαβὼν Py
marginal 37
footnote 3 γίνεται ante 2 (alt.) καὶ Py, m. 1.c; post 3 ἀντονομάζοντα Ac, m. 2Vc ἐστὶν ὁ Pγ Vγ | δὲ Pa hy γ, Nilus; om. Pc V 5 ἀνὰ μέρος post πεπραγμένον add v. Pa, m. 2Vc; cf. (Marc. ?) IV 563, 19 W in textum v.l. irrepsit τι (sc τινὲς) προστιθέασιν ἀνὰ μέρος Py | ἢ — 6 ἱερωσύνας absciss Py | ἄλλοις Ph 10 ἀμφότεροι etian ante οἱ Py (voluitne ἀμφοτέρων?) 11 τὸ; τοῦ Py; τὸ δὲ Ph: τῶι P 11 12 γεγεννῆσθαι Pa hy Ac 12 τῶι (pro alt. τὸ) Pc ἔτι om. Ph: ἔτι ὄντα om. Vc Ba 13 αὐτοῦ Py | τοῦτο Pc 15 p. 56, 25 17 τινα μυηθέντα Py; Syr. 2 p. 119, 9: μεμυημένον 17. 18 εἰπεῖν Py; om Vδk | εἰπὼν ἃ εἶδεν om. Nilus 18 ἔχει Vγk 19 τὸ εἰπεῖν Pc 20 προσιούσης Phy 22 γε, m. 2 μὲν supr.. Vc; om. Py | ἐφεξῆς Pc 23 ποιήσεις κοινὰ, m.2 cr., Vc
marginal 38 157
footnote 4 τις post ἀποκτείνας Ph 5 τοῦ ἱερᾶσθαι P 8 το-σαῦτα Pc | ταῦτα περὶ ὅρου om. Ac 10 δὲ om. Py 11 παρ-επομένοις Ph 12 post πρός τι add. Phy: οἷον ἀνθορισμῶι συλλογισμῶι γνώμηι νομοθέτου πηλικότητι πρός τι 13 καὶ om Pcγ 14 ὥσπερ (om. καὶ) Sop. 16 τε om. Phy 17 καὶ κατʼ Sop. | ἀρχὴν Vδk, Sop. 18 cf. 68, 12; Jaeneke, De sta-tuum doctrina ab Hermogene tradita p 13 | ναυάγια Pcy, (ον supr.) Pa; ναυάγιον W Ph 19 τῶν ἐμπόρων post καταίροντος add. Vγ (cf. 66, 17) 21 οὐ δεῖ με ἐπὶ (om. εἰ) Sop. V 167,13 W.
marginal 39
marginal 158
footnote 1 τοὺς δὲ P Ac Phy; ἀλλὰ Ba. (v.l.m.2: τοὺς ῥήτορας δὲ Vc 1 pr. τοὺς om. V Pγ Vγ | alt. τοὺς om. Ac Pγ Vγ 3. καὶ om. Py Vγ | δύνανται (om. ἂν) Py 3. 4 ἀδικεῖν |δημοσία οἱ καὶ m. 2 supr.] δημόσια Vc: οἱ τὰ δημόσια mg. suppl. m.2 Ba | ὅτι. πράττουσιν Phy; οἱ καὶ δημόσια πράττοντες Ac, v.l.P; πράτ-τοντες m.1Vc Ba 4 τὰ δημόσια Pcy 6 cf. Aps. l 2 p. 269, 12 Sp. -H. | post συμμάχους add. Phy: τὰ ἀπόρρητα (ἄρρητα Py) ἐξειπεῖν 7 ἐπάγεται Sop. | δὴ οὖν Ac | εἰ καὶ ταῦτα Phys 8 κἀκεῖνο Nilus 9 τῶν τρόπων Ac; cf. 70, 3 10 πάντα Ac τις om. Py | ἀδικῇ Ac 11 ἓν Py 12 γνώμη εἰ ἐμπίπτοι νο-μοθέτου Ac Py γ, Nilus 13 λυσιτελές, mg.m.1 λοῦν, Ph 14 γε-γονὸς ἀποδείξει Ac | ὅτι καὶ μεῖζον Ac 15 τὰ om. m1Vc, Nilus 16 τῶν ἀναγκαίων ante καταστῆσαι Vk Wc, sup1. m. 2 Vc; om. Vc Ba Ph 17 ἐν P; ἐπὶ V Phy γ, v. l.P; Marc. IV 609, 21 W.: τὸ ‘ἐπὶ τούτοις’ ἐξηγητέον ‘ἐν τούτοις’ | ὃ καὶ ἀληθέστερον post τούτοις add. Pa, (er.) Pc, m. po. Py; fort. interpretationi vel v.l. ἐν — ἐπί ascripta erant ut p. 71,8 ann. 17. 18 τῆι πηλικότητι λέγω Vc Ba
marginal 40
footnote 1 de Minuciano: Georgius 755 Schilling | ante ἡ add. ἀν-αγκαίως Nilus; post ἀντίληψις add. ἡ οὖν ἀντίληψις Ph V Vγ k Sr, m. 2 Vc | ὥσπερ Sr 1. 2 ἐν στοχασμῶι ἐμάθομεν Phy, cf. Sr p. 48, 3 2 κεκώλυκε νόμος οὐδείς Py 5 οὐδʼ ἐπὶ τοιαῦτα Ph: οὐδὲ ἐπὶ ταῦτα Py; cf. 48,18. 21 6 τούτου PPy, Nilus; τούτοις V Ph. v. l.P, Sοp. 7 αὐτοὺς εἰκὸς Ac Ph 8 κακοῖς om. Ph. Nilus 9 μεταλήψει Py 10 κέχρηται Pa b; V; χρήσεται Pcy 12 συμβουλεύειν (om. καὶ) Py 13 ὁ ζωγράφος τῆι τέχνηι V Ph |⌊ἀντί er.⌉ θεσις Pa 14 νῦν om. Py, Nilus 18 πῶς Py 18. 19 μεμαθήκαμεν ἐν (τῶι add Vc Ba) ὅρωι V Phy | p. 61, 6 19 ταῦτα Ph | εἴπομεν suppl. m. 2VcBa 22 δὲ καὶ Vγ Wc | ἀντι-λήψεως Nilus, (ν supr.) Ac 23 αὐτῶν etiam ante alt. δύο Vc Ba
marginal 41
marginal 159
footnote 2 τοῖς τὰ Vk: τοῖς m. po.suppl. Pa | ⌊γ m. po.⌉ ε Pc | μόνα om. AcPy 3 ⌊ὀρθ⌉ ῆς Pa 5 ⌊ἀπ supr.⌉ αὐτῶν τῶν πεπραγμένων Ph 6 τὰ κατὰ om. Ac Phy, cf. 1 13 9 μόνοις V Phy, v.I.P. (post κεφαλαίοις) Vγ, cf. l. 10 19; om. P 10 τε om. Vc Py | καί om. Ph 12 ἐπεὶ P Ph; ἐπειδὴ V Py 13 τὰ κατὰ post μετὰ add. Vy k Wc, m. 2.Vc (Syr 2 p. 159, 22) 14 ἔπεμψεν ὁ Ac Ph | διδοὺς om. Ac 16.17 νεκροὺς om. Ac; del. Vc 18 ἀδικημάτων PV, Syr. 2 p. 130, 1; om. Ph 19 ἀντιλήψεσιν om. Ph 20 ἐστι ante 19 παρὰ Py | τὸ om. Vc Ba Phγ γ; ὡς Vγ | cf. Π εὑρ 251, 6 Sp. 23 κρίνεις με Ph
marginal 42
marginal 160
footnote 1.2 Marc. IV 636, 5 W. refert οὐδεὶς ἐφʼ οἷς ἕτερος πεποίηκε κρίνεται 2. 3 ⌊καὶ⌉ μη⌊δὲν supr.⌉, cr. m. 2, Vc: ἢ μηδὲν Ph: ἢ μὴ Ba ἔδει σε Phy | ἢ εἴργειν om. Pb Va; Marc. IV 636, 13 W. 5 τί ante βιάζῃ add. m. po Va 6 alt. καὶ om. Phy 7 ἀντεῖπες οὐδὲ ⌊I—II⌉ ἐκώλυσας Ba; ἀντεῖπ⌊ας ἢ m. po.⌉ οὐκ ἐκώλυσας Vc | οὐδὲ (pro ἢ οὐκ) Py 7. 8 ἤτοι μὴ ἔχων Dox. (in Π. εὑρ p. 251, 6 Sp.) 8 τι om. Pa |τοῦτότε Ph 11 ἀπο-βεβιωκότων Dox. 1. 1.; at rhetor sequitur Demosthenem, De cor. 18, 197. 199 cet. 12 καὶ om Ac Phy | δ⌊η?⌉ Pc: δέ γε Ph 15 cf. Π. εὑρ p. 250, 29 Sp. 17 αὐτὸ om. Vc Ba |καὶ ὁ Pc 20 ἀλλὰ καὶ τὸ εἰδέναι μεταχειρίζεσθαι P; om. Py; τὸ om. Ac; τὸ et μεταχειρίζεσθαι om. Ph; τὸ εἰδέναι om. Ba, (ἀλλὰ καὶ με-ταχ. punctis del., m. 2?) Vc 21 τοσαῦτα Vy Wc
marginal 43
footnote 2 καὶ om. Py γ 2. 3 δύο ὄντων ἐγκλημάτων 3 ὄντοιν om. Ph |τοῖν om. Pγ τις ἀντιλέγων V Ph γ Vγ Syr. 2 αὖ ὅτι καὶ Py \\9 ⌊καὶ⌉ del. ἐφʼ Ph 10 καὶ πάλιν Vγ |ὀῦν (pro οὐ) Ph |οὐδὲ Vc Ba Py | οὐ δεῖ γὰρ Vγ 11 οὐ (pro μὴ) Vc Ba 12 διελεῖν P 13 τὸν om. Vc Ba; del. Ph 10 δὲ διαί-ρεσιν Ac Ph y, Nilus 17 τιθέμενος PVPy, Sop. V 171, 25 W. θετοὺς ποιούμενος Ph, m.2Ac, cf. Syr. 2 p. 136, 23 21 δὲ (om. αὖ) Ac
marginal 161
marginal 44
footnote 3 p. 67, 22 | καὶ om. Py 5 μοιχείας τινὲς Ac Ba Ph, m.1Vc καὶ καθυφέντες Pγ Vγ 7 τὰ om. Vγ 8 τέσσαρες Ba; τρεῖς P Vc AcPy; γρ΄ καὶ τέσσαρας ὃ καὶ κρεῖττον m. 2Vc; σκόπει ⌊π er.⌉ ὅσαι (sic) Ph | καὶ αὗται παῤ ἀμφοῖν P Ac Ph; γρ καὶ ταῦτα παρʼ ἀμιφοῖν m. 1P; δύο τοσαῦτα (-ται ?) παραγραφαὶ m. po. Pa; καὶ τοσαῦται παραγραφαί Vc; γρ΄ καὶ αὗται παῤ ἀμφοῖν καὶ m.2Vc; καὶ αὗται παρ᾿ ἀμφοῖν καὶ τοσαῦται παραγραφαί Ba; καὶ αὖ τοσαῦται παραγραφαὶ παῤ ἀμφοῖν Py 9 καὶ om. V Py;? Ph 10 γῆμαι Vc Ba | καὶ om. V Phγ | ἀποβαλέσθαι V Py 11 κωλύεται Ph 12 ἑκάστην γε V Phy 15 ἀντιλήψεων om. Ac Py; ?Ph 10 νυνί V Ph 17 sic P Py; ἑπόμενος ὀρθῶς ἄν τις VPh, v.l.P
marginal 45
marginal 162
footnote 1 τῶν om. Ac, m. 1 supr. Ba 2 om. V Ph 3 πᾶσαι om. Py 5 post τι add. Ba, m. po. Pa; τοῖς ἀπ᾿ ἀρχῆς ἄχρι τέλους | ἥτις Pγ 6 αὐτῆι P Ac; αὐτοῦ Vc Ba Py; ? Ph | ἢ om. Pc 7 ἑτέραι P; πάλιν V Phy, v.l. P, Nilus 8 πρός τι — 9 γνώμῃ non legit Sopater nec norant eius auctores, V 177, 8. 14 W. 9 ποιότητι ⌊συγ in ras., καί supr m 2⌉γνώμηι Vc 11 ὁριστικῶι P Vc Phy, Nilus; γρ΄ τῶι δὲ ὁρικῶι· ὁμοίως δὲ γρ΄ καὶ ἐν τοῖς ἐφεξῆς δυσίν (1. 16. 18) P | ἐμπίπτει Py, Nilus 12 τῇ om. Ac Py | p. 66, 5 14 post χρήσεται add. Vc Ba Py: ἀξιῶν μὴ τὸ γεγονὸς μόνον ἐξετάζειν ἀλλὰ καὶ μεθʼ ἧς γνώμης, cf. 1. 19 15 cf. Aps. l 2 p. 235, 17 Sp. -H. | δὲ om. Py 15.16 φόνου φεύγει Pc Ba Py 16 et 18 ὁρικὸν ex cr. Pa Ac; ὁριστικὸν Pc hy Vc Ba; cf. 1. 11 19 ἄξιον Pc | ἀξι ⌊VI—VII evan.⌉ ο γεγονὸς μὴ μόνον Ph
marginal 46
footnote 1 οὐ suppl. m.po.Pc 2 εἶτα P AcPγ; ἔπειτα VcBa;? (evan.?)Ph 8 ἐκ⌊ΙΙ evan⌉πτωκεν Ph 4. 5 ἐν πάσηι γὰρ ἀντιθέσει ἀντεγκλη-ματικῆι ἀντίθεσις P; (ἀντιθέσει om.) V Py , v.l.P, Sop. V 178,17 W. (ἡ ἀντίθεσις) Py; (ἐν πᾶσι γὰρ ἡ ἀντ᾿ ἐγκληματικὴ) Ph; ἐν πάση γὰρ ἀντεγκληματικῆ ἀντιθέσει τοπικὴ καταδρομή Vγ; cf. 86, 19. 92, 1 5 τι om. VcBaPy 6 post ὡς add. P: ὅτι τοὺς τοιούτους οὐ δεῖ ἐλεεῖν ἀλλὰ μᾶλλον ἀναιρεῖν; mg. P: γρ καὶ οὕτως ἐρεῖ δέ τι καὶ ἀντιστατικὸν ὡς ὑπὲρ αὐτοῦ πεποίηκε τοῦτο τοῦ παθόν-τος (πεπονθότος Pc) 9 ταῖς om. Marc. IV 676, 14 W., (στά-σεσιν ἄλλαις) Py IV 673, 29 W. 11 καὶ om. Py, cf. W IV 678, 10 | πᾶν Ph 13 χρησιμώτερον P | ἀλλʼ post ἄλλως add. AcBa Ph, v.l.Pa, Nilus, (καὶ pro ἀλλʼ) v.l.Pc 14. 15 ἐστιν post μεῖζόν add. Phy 15 ἀνταποδεικνύμενον Ph 17 τούτου τοῦ VcBa 19 τι P Ph y, cf. Syr. 2 p. 140, 21. Aps. I 2 p. 232,17 Sp -H.; om. V 20 μὲν om. Pc
marginal 163
marginal 47
footnote 3 ὑπὸ om. Py | τὸ τεῖχος Pγ 5—7 cf. Herod. 8, 80 de dolo Themistoclis 5 δεῖ [circ. IX⌉ τὸν Pc | καθʼ P; πάντα V Phy; πᾶνθʼ v.l.Pc 5.6 ἂν ἐγχωροίη Ba; ἐγχωρεῖ Py 8 εἶναι (pro ἐν) Ac, v.l.P | πάση⌊η m. po⌉ Pc 8. 9 πάσηι τῆι θέσει (ἀντϊ m. po supr.) Vc 10 αὐτὸν Ph 11 ταξιάρχαις Pcy V 12 ἐξὸν pro ἐξῆν Pγ | ἐξ⌊ὸ⌉ν ἦν Pa: ἐξῆν Vγ | μοι Vγ; μὴ PAc; om. BaPhy γ, (μοι μὴ supr.; m. po.?) Vc 12. 13 ὄντι καλον εἰ μη εξον ῆν βουλεύσασθαι Pγ, (κᾶλον, mg. μᾶλλον) Ph; W IV 683, 15 18 βουλεύσεασθαι, ε m. .1?, Vc | cf. Quint. V 10, 40 14 ἡ — 15 μεμαθήκαμεν m.po.suppl. Py 15 p. 61, 6. 15 16 τινὲς: Minu-cianus apud Georgium 756 Schilling cet. | (δὲ om.) τινὲς τῶν ἀντιγράφων Sr | ἐπιγραψάντων, μένων m.2 supr., Vc 17 καὶ εἴδη Sop. 18 καὶ post γε add. Ph γ 19 τὴν om. Phy, v.l.P 20 καθάπερ καὶ VcBa, Marc. IV 684, 22 W.
marginal 48
footnote 1 τῆι (pro τε) Ph | p 67, 22. 61, 21. 53, 14 | ἄλλαις Py (at 42, 10 cet ; ἐν ἄλλοις Ph 4 τὸ Ph, m .1Vc | cf 34,19. 35,7 7 ἐγχωροίη Ac, mg. Py |[περὶ] Ph | post ἔτι add. mg. τρόπον Ph 9 alt. ὅτι om. Vγ 12 ἐχώρισάν, ἔγνώ m. 2 supr., Vc 13 ἔξω Minucianus apud Georgium 758 Scbilling Sop. V 101,14 W 15 βάσανος Pγ (ex Herm et Minuc.) 15 τι supr Ph; om Py γ 16 ψυ-χῆς πάθος Vc Ba | γρ πάθος μόνον P at Minuc. l.l | συγγνώ-μην VcBa; ? Ac; συγγνώμης Ph 17 οἷον om. Pγ | pr. ἢ om Phy | ὕπνον Pahy γ Ac; |ὕπ m 2] νον Vc; ὄκνον, γρ ὕπνον mo. 1, Ba; |οἶκτον m. po Pc | καὶ (pro alt. ἢ) Phy | εἴ om. Pγ 19 τις ἂν VcAc, m. 2Ph (ὧι — τίς ἂν — 20 συγγνώμαις suppl. m.2Ba) 20 〈ὡς〉 κἀν? 21 αὖ τῆι PV: αὐτῆι v.l.P; αὐτῆ τῆ Vγ | πάλιν αὖ τοὐναντίον μεταστάσει Py ; τῆι μεταστάσει πάλιν αὖ τοὐναν-
marginal 164
marginal 49
footnote τίον Ph γ | τοὐναντίον [Il], m. 2 γρ ἀνάπαλιν, Vc; vix san |οὐ ante χρήσεται add. AcBaPh, (er.) Vc |ταυτὶ V 1 οὐ om. Ph |εἶναι, m.2 οἶμαι, Vc |τοῖσδε (pro τοῦ δὲ) Ph 5 τῷ om. Phy γ, Sop. 6 ἡ μὲν ἔγγραφος πραγματικὴ VPh y, v.l P 7. 8 οἷον νόμου κελεύοντος ἐν ἡμέραις τρισὶ περὶ πο-λέμου βουλεύεσθαι Py | cf Aps. l 2 p. 245, 4 Sp -H. 8 βουλεύ-σασθαι Ph ἐκέλευσεν Ph, m 2Vc 9 αὐθημερὸν ante γράφει VPh; Syr. 2 p. 164, 3 11 τὰ κατὰ P: om. VPhy 18 κατὰ ταύτην Ph γ 14 p. 82, 4 sq. 10 ὅτι om. Py 19 τὸ Ph 21 alt. καὶ om. 22 ποτέρω δὲ PPy; πότερον δὲ W Ph | πρότερον Pcy; πότερον Pa; προτέρωι VcBa; ποτέρωι AcPh
marginal 65
marginal 50
footnote 2 p. 49, 1 3 τὸ δὲ Ph, Nilus | δικολογικῶν m. 1VcBa 4 γε om. Py e διπλοῦν Py | alt ὅτι om. Py 7 ὅτι post οἷον Py, supr. m. 2Vc | οἶον ὅτι χρήσιμον προσλαβεῖν ὄλυνθον Py, v.l Pa, (ὀλυνθίους) v.l Pc | προλαβεῖν Ac | ὄλυνθον VPhy 8 μέγας, m. po. μέγα φρονῶν, Vc | ὁ om. P 8. 9 λαβὼν αὐτοὺς Py | cf Demosth 1,12 10 τὸ (pro τι) AcPy 11 γενήσεται Ac 12 ἤδη πάλιν Ph οἷον om Py | cf Anaxim p. 14, 6 Sp. -H. Aristid II 503, 29 Sp 13 περιέσται (pro παραμενεῖ) Ph | τὰ δὲ (pro καὶ τὰ) Phy 14 ἀποτρεψόμεθα Py; cf. Dem. 1, 11 17 προσγενό-μενα ? cf. 79, 5 20 δὲ, om αὖ, Py, Sop. | διαιρήσεις Sop. 20— p.78, 1 cf. Anaxim p. 13, 12 Sp .-H. 21 τῆ ἐνστάσει AcPy 21—p. 78, 1 δεικνύς· εἶτα ἐκτάσει χρώμενος ὁτι, om. cet., mg. *ἀντιπαρα, Ph | τῆ ἀντιπαραστάσει AC
marginal 51
footnote 1 ἀναγκαῖον ὄν Ph (Syr. 2 p.182,1 ἀλλʼ οὖν ἀναγκαῖον) 6 cf. Dem. 1, 21 sq. | τῶ ὀλυνθιακῶ P 7 ψυχῆς post ἔχει add Ac Ph, v P: supr. m. 2Ba et (ψυχῆς ὁ) Vc 8 πῶς Py; ἢ ὡς PV Ph 9 Dem. 2, 17 10 τῶν ἀθηναίων Ph 11 ἡ etiam ante ἐξέτασις Ac | δὲ om. VcBa 13 γε (pro δὲ) m. 1VcBa 14 ἐκεῖ τε Ph; ἔγκειται καὶ PVPy 15 παρελείπομεν Ba, (ϊ m. 2 supr.) Vc; παραλείπομεν Phy 17.18 φύσει δὲ 20 οὐ γὰρ (pro ἄλλως τε οὐχ) Ph 20. 21 ὅσα ἂν ... ὅσα δἂν Vγ 21 κρίνομεν, om. δἂν, Py 24 ποιοῦμεν Vγ, m. po.Ba
marginal 166
marginal 52
footnote 2 οὖσαν, m. 2 supr. μὲν, Vc ποιοῖμεν P Ph; ποιοῦμεν Py 3 ποῖαν (pro τίνα) Ph 4 τε om. Pcγ | δόξα om. Ac 5 post ὑπάρχουσα add. ἡμῖν Ph, μὲν m. 2 supr. Vc | cf. 77,17 | δὲ (pro δʼ ἂν) Py, m. 2Vc; δὲ, mg. m.1 δἂν, Ph 8 | ἑκάτερα m. po.] Pc | ὅτι om.Py 9 λυσιτελῆ Ba, m.1Vc 10 ἐν τοῖς Ph Dem. 4,18 11 ποιήσετε Py, (αι supr.) P, (pr. ε ex η; m. 2?) Vc; ποιήσητε AcBaPh | νὴ δία P; om. VPhy, v. .l.P ἂν τοῦτο Dem. | ὡς ἐγὼ AcPy; ὡς τοῦτο ἔγωγε Ph 13 εὐπρεπεῖς Vc Ba; m. 1Pc | ἠμᾶ Py 15 ὑμῶν Pc; cf. Dem 16, 30. 31 15. 16 βλαβερὸν ἐφʼ ἑκάτερον Ac 20 21 τῶν νομικῶν στάσεων Py 21 p.82, 4. 76,14
marginal 167 53
footnote 1 καὶ m. po. add. post ὅτε Vc | ὁρικῶς ν .l.P; ὁρικῶι Ac; ὁριστι-κῶς P Vc Phy,? m.1Ba, Sop., Nilus l πρῶτον Ph 3 στάσιν V. v.l.P 4 ἔσω Py | τῶν om. Phy γ, Syr. 2 p.158, 25, (supr. m po ) Pc 4 5 sic V Ph, v. l.P, (ἀντιλέγειν ἡμερῶν) Pγ; τριάκοντα ἡμε-ρῶν δέον ἀντιλέγειν πρὶν τοῦ κυρωθῆναι P, (δέον et πρὶν add m. po.) Py 5 δὲ ταῦτα VcBa 7 ἥσσω m. po. ex εἴσω Pc Vc 8 τὰς λʹ ἡμέρας Py 8. 9 ὁ πένης ante 8 μετὰ Vc Ba Pγ; om. Ac 9 ἡμέρας add. post πένης v.l.P, post τριάκοντα Phy 10 οἱον πότε VcBa 11 τῶν om. Pcy | ἡμερῶν om. 12.13 sic Ac Phy γ, (ἀ|ποῦ m po.|σι) Pc, (οὐδὲ etiam pro οὐ) Pa; οὐ τοῖς ἀποῦσιν οὐδὲ τοῖς πρεσβεύουσιν Ba, (ἀπ[Ι]οῦσιν) Vc; aut οὐ τοῖς πρεσβείας χάριν ἀποῦσιν scrib. (cf. Marc IV 782, 7 W.) aut alte-rum del. 13 τοιαῦτα om. Phγ γ 14 ῥάμμα (sic) Ac; πρᾶγ-μα Pγ 18 ἀπαντήσεται (ει m. 1?) Vc; ἀπαντήσει Ph 20 κυ-ρίωι Ph: κυρίως Pγ
marginal 54
footnote 1 δ’ αὖ Py | προβολῆι διαιρεῖται Ba, (tum cr.) Vc 2 τοῦ om. Ac, Sop. 3 ἑτέρᾳ — θέσει om. Pc 4 ἀριστεὺς (om. τις) V, v .l.P | καὶ om. VcBa 5 φόνου φεύγει PcVcBa 7 μοι om. Pch, (m. po supr.) Py 8. 9 ἀνήιρητο VcBaPy, v.l.Pc 9 οὔπω P, m. 2VcBa, Nilus; τούτωι VcBa, (in ras.) Py; οὐδέπω Ph om Ac, v.l.Pc 10 λαμβάνει Pc δηλαδὴ μεταλαμβάνει V, (παρα-λαμβάνει, μετα m. 1 supr.) Ph 13 pr. ἢ om. Ba; |εί m. po] Pc 13. 14 δὲ ταῦτα οὐχ Pγ 15—22: folium intercidit Py 17 ὅπου Ac, Nilus: εἰ ὅπου PPh; εἰ[Ι]που Ba; εἰ[Ι]ὅπου Vc 18 αὐτὸν Ph 10 σε supr. Ph; om. Ac, Nilus | ὡς ὅτι Ph: ὅτι Nilus ἀπέκτεινα AcPh; ἀπέκτονας Nilus 20 καὶ om. Vγ, m. 1Ph 22 δεῖ VcBaPh; ἔδει PAc, m. 2Vc
marginal 168
marginal 55
footnote 1 τοιαῦτα? cf. Marc. IV 793, 18 W. | ἢ οὐ PcAc, Marc,(εἰ supr.) Vc, ([ἢ]) Ba, ([οὐ] m. 1?) Py: ἢ εἰ οὐ Pa ἢ εἰ (οὐ m. 2 supr.) Ph καὶ τοὺς Ac 2 ἀρίστους VcBaPhy; ἀριστέας PAc,m. 2Vc, Marc ἐπὶ Phy; ὑπὸ Vγ, Marc., (ἐπὶ m.1 supr) P; [ἐπὶ], m.2 ὑπὸ supr, Vc: ὑπὸ m. 2 ex ἐπὶ Ba | οὕτω ante ποιεῖν suppl. m. 2VcPh 2. 3 p. 74, 15 cet. 5. 6 προβολῆ τῆ ἀπὸ τοῦ ῥητοῦ Ac, v .l.Pc, (om τοῦ) v .l Pa 6 τοῦ νομοθέτου etiam post τῇ add. Ba, ant τῷ (er.) Vc | προσδιωρίσασθαι (sic) Ph 9 ἀντιλήψει om. Py | κοὶ om Pc 10 τὸ πρᾶγμα παρὰ Ph 11 ἐπὶ PPy, cf. 40, 11; εἰς Ph; εἰς et ἐπὶ Syr. 2 p.194, 2. 3 sq 12 πολιορκίας οὔσης Py, 40, 12 14 διττῶς Pchy Ac, (χῶς m.1 supr.) Pa; διχῶς VcBa | τε om. V | τοῦ τε (pro καὶ τοῦ) Pc 16 τίσι Va, (νι m.1 su r.) Pa, cf. Marc. IV 806,5 W.: τίνι δὴ Ac 17 ἀνῆλθον P κνῆλθε Ac; ἀνῆλθες Vγ 18 τὸν νόμον (pro μόνον) Py | alt. καὶ o ??. Phy
marginal 56
marginal 169
footnote 2 ἡ δευτέρα Py, Nilus | δὲ om. Ba 4 διωρίσασθαι v.lPa; διωρίσθαι Py; διορεῖσθαι, ι mg., Ph 6 κωλύεσθαι V Phy 7 ἐρεῖ om. VPhy, v.l.P ἐπιτρέπων Ph 8 τοῖς ξένοις AcPhy | οὐδὲν Ph, Nilus 9 ἢ Ac Ba Phy; εἰ P, (m. 2?)Vc, v .l.Py 11 καὶ om. Ph καὶ πάντῃ om Py 12 γε ante ἔξει Nilus; om Py γε ὁ φεύγων ἕξει Pc 13 ὅτι om. Py: οἷον ὅτι om. VPh, Nilus | ἔδει καὶ ὡς VcBaPhy, m. 2Pa, W IV 812, 27; καὶ δικαίως P, (om. καὶ) Ac; m. 2Vc: γρ ἑτέρως ἐξῆν σοι δικαίως εὗ ποιεῖν τὴν 14 τῆι πόλει Ph | καὶ om Ba 15 cf. 73,14 17 οὕτως om. VPh, Nilus ὡς om. Pc | cf 73, 16sq. 20 διπλοῦν τι PaBa, (τι supr.; m 1?) Vc: τι διπλοῦν PcAc; τι om Phy γ, Nilus 21 ἐπ[έ]γνωμεν Ba; ἐπιγνωσόμεθα Phγ
marginal 57
footnote 1 p. 40, 20 |ὡρισάμην Pahy γ; ὡρισάμεθα, ην m.1 supr., Pc; διωορισάμην | πλείστοις γε Py 3 l. 15 3. 4 ὡς φανεῖται οὕτως· ἡ δὲ διαίρεσις Ph 4 τοῦ ῥητοῦ Py 7 ἰσάζειν AcPy, (ον supr.) P: ἰσάζον VcBaPh ἐξισάζον Vγ 8 τῷ et τῇ om. Py p. 82, 19 10 ταῦτα δοκεῖ VcBa 12 καὶ — δυνηθῆναι om. Pc χρήσασθαι Py 13 οἷον om. VPy | δῆλα· ἔστιν δὲ ἀντίθεσις Ph 14 ὅρος βίαιος, om. ὁ, VPhy, Marc. IV 820, 24 W. | ἡ θέσις P, (ἡ om.) Ac; om VoBaPhy, Marc.; θέσις post alt μετάληψις Vγ, m. 2Ba 15 ἀντίληψις om. VcBaPhy, Marc. 16 τῷ om. Pc | τῆ supr Pa; om. Phy 18 [Ι]τῶν Pa ἡ add. ante ζήτη-σις Vc, (supr.; m. 1?) Py 19 γενομένου Pa; γινομένου Pc 21 cf. 87, 10 ἐστι VcBa | ad φανερὰ πάντα mg. γρ ταῦτα P
marginal 170
marginal 58
footnote 1 ὁ om Phy; cf. 41, 5 2 ἔσται τῆς νηός Ph 3 ἐπέμεινε .. καὶ κωλύεται Py | χειμαζομένη ante πατρώια VcBa; supr. (m.1?) Py; om Ph 4 δεσπότης εἶναι Ac 4. 5 ἀποκήρυκτος εἶ οἷον ὅτι οὐ μετέστην τῶν Ph 6 τότε VcBaPhy, Nilus, Marc. IV 822,1 W.; τοῦτο PAc | δήπουθεν ὁ νόμος ὅταν VcBaPh, (om. δήπουθεν) Nilus (cf. scholion P: ὁ νόμος δηλονότι) | κλη-ρονόμος ὢν (om ὡς), mg. m. 1 ὡς κληρονομήσων, Py 7 δια-δεξ[ό]μενος Pay; διαδεξάμενός, mg. ἐπιδικαζο, Ph |τῶν om Ba Py, (m.2 supr.) Vc 8 περὶ om. Py 9 ἡ om Py 10 ῥητοῦ (pro νόμου) Ac, Nilus | οἷον om Phy 11 ὁ νόμος VcBaPh | τοῦτο σαφῶς mg. suppl. m.1Ph | σαφῶς ante τοῦτο Pc; om Py | δίδωσι V 11 12 ἐπιμένοντα Ac, supr. Pa 12 ὃ (pro ἣν) Nilus | ἡ om. Pc 14 τις om. Py 16.17 εἶτα ἔστι τὸ μὴ προσδιωρίσασθαι. καὶ ἰσάζει εἶτα ἔστι τὸ μὴ διορίσθαι. ὧι ὁ πρότερος ἂν χρή-σεται. καὶ Ph 16 ὧι ὁπότερος ἂν PPγ; ὡς ὁ ἕτερος ἂν Py; καὶ οἷς ὁ ἕτερος ἂν Vc, (ὧ ex οἷς, m.2?) Ba; καὶ οἷς ἂν ὁ ἕτερος Ac, v.l. Pa, (om ἂν) v.l Pc 18 νυνὶ Phy
marginal 59
footnote 6 νόμος, m.1, Pc 9 καὶ om. VPhy 12 ἀπωθῶνται, ό m.2, Vc 18 πάλιν — 14 ἵνα mg. (m. 1?) Py | πάλιν διὰ τί V Py, v. l.P; διὰ τί πάλιν Ph; πάλιν δὲ, om. διὰ τί, P 14 πρὸς τοὺς κινδύνους Phy, (om πρὸς) Ac | πλέοντες Phy (ἐκπλέοντας Marc. IV 825, 4 W.) 15 l. 1. p. 81, 14. 67, 19 16 ὅσον δὲ P Phy; ἀλλʼ ὅσον V 19 τ|ρ er.]οπική Pc 20 οἱονεὶ Py, Marc. IV 827, 3 W. 20. 21 ἀντιστατική· ἐνταῦθα δὲ καὶ ἔκφρασις τοῦ χειμῶνος Py 21 παρὰ Ba 23 οὐ P; κατʼ οὐδὲν μᾶλλον Ac, v. I.Pc, (κατʼ om.) Vc Ba Phy, cf. schol. P (W VII 651, 24), Marc. IV 827, 24 | ἂν om. Ph, Marc. | νηὸς Phy, Marc.
marginal 171
marginal 60
footnote 1 ἦν Py | δὲ ὅτι ἐφʼ Ph 2 σε ἔδει V | ἐπὶ om. Ac; ἐν Ph, Marc. 3 βέλτιον φυλάξαι VPhy, Nilus | τὸν νόμον V | εἰ — 4 νέος om. Pc 5 τύχοι Py 8 ἅτερος Py, (ἅ m. po.) Ba |ἂν (pro εἰ) Ac 9 βραχὺ Py 10 cf. 84, 17 | πότερον Ph; ποῖον V Py, v.l.Pc, cf. schol. Pa; οἷον πότερον P 11 ποῖον (pro πότε-ρον) V Py, v.l.Pc, cf. schol. Pa 11. 12 γινομένου Pc 13 φαί-νεται 14 τούτου Phy | cf. 41, 9 15 κόρας post 14 τις Ph 16 αἰτεῖ Py 16. 17 αὐτὸν τεθνάναι Pah, (τουτον) Pc; τεθνάναι αὐτὸν VPy 17 τεθνήξει Ph 18 δὴ om VPy | ἔσται ἄκυρον VPy 19 μὴδὲ PAcPh, Nilus; καὶ μὴ VcBa, (om. μὴ) W IV 830, 1 20 τοῦ δὲ κλύδωνος Pah; ἀλλὰ τοῦ κλύδωνος Pc, Sop. IV 830, 2 W., Marc 830, 18; τοῦ κλύδωνος δὲ VPy | ἢ εἰ μὴδὲ Pa, (δὲ om. ) Pc; ἢ, om. cet. , Ph; εἰ, om. cet. , Py: ὁ δὲ ὅτι Ac; ὅτι οὐδʼ εἰ μὴ Ba; [ὁ δὲ m. 2 supr.] ὅτι [II—III] εἰ μη|δὲ m.2 supr.] Vc; ὁ δὲ εἰ μὴδὲ Vγ | πατρός ἐστιν V Py; πατρὸς εἴτε Ph
marginal 172
marginal 61
footnote 1 ἀλλʼ supr. Pc; καὶ Ac | οὐδετέρου P; ἑτέρου Vγ; οὐχ ἑτέρου VPy, cf. Ph: ἄλλου ἑτέρου 2 mg. m. 1 ἀντιστατικαῖς Ph 5 τῶ om. Ph, schol. P (W VII 668,8) | θέσει ante πηλικότητι add. Ph (at l. 10 p. 59, 12) 7 ἐμπίπτοι Ph | ἧι — 8 ἀντίληψις mg. suppl. m.1Ph; om. Pa (m. po. suppl.) 8 ἡ om. Py; καὶ vulg. | ποιότης Ph 11 ἐστι VcBa | cf. Auct. ad. Her. l 14, 24 12 ἐκώ-λυεν AcPy, schol P (W VII 668, 24) | αὐτοπροσώπως P 18 τίς εἰσάγων Ph, Syr. | cf. Vit. Aristoph. p.156 Westermann 14 ἡ om. V 16. 17 κεκωλυμένον Ph 17 εἰ, ὅτι m. po. supr., Vc; ὅτι Py 18 ὅτι om. Vγ; εἰ Ph, Nilus, (ὅτι supr.) Pa | τὸ πλεῖστον Ba 19. 20 τοῦτο ἐκώλυσεν V Phy 20 ὁ νομοθέτης om. Ph
marginal 62
footnote 1 οὑτοι P; αὐτοὶ VPy; om. Ph | θέλωσιν Vc; θέλουσιν Ph 4 οὐκ ἀνεῖλεν δὲ παντάπασιν Phy, (m. 2 γρ οὔκουν ἀνεῖλε παντ.) Vc, (om. δὲ; mg.m. po. οὔκουν) Ba 5 γε οὖσιν Ac 6 πε-ριέχοντα VPhy, W IV 840, 2; ἔχοντα P 11 p. 60, 16 66, 14 τὸ γεγονός | δὲ om. Py 13 καθάπερ καὶ P, (καὶ om.) VPy; ὅσα Ph 14 ἐστιν εἴδη Ph 15 ὁμοίως Ba 10 εἴτε (pro ἤτοι) Ac | τοῦ om. VcBa 17 ἐξὸν Ac 17.18 ἀποκτεῖναι, ϊννύ m.2 supr., Vc; ἀποκτεινύναι (sic) Ba 20 δέδωκεν Ph 21 τινὰ λιπόντα Ph; τινὰ om. Vc Ba; ἀριστέα λιπόντα Ac 22 ἀπέκτεινεν ὁ |στρατη-γὸς m.2; ex ἀριστεὺς?] Vc; ὁ ἀριστεὺς ἀπέκτεινε Py | φόνου φεύγει Ac 28 ἀντεγκλήματι PPy, W IV 842, 17; ἐγκλήματι
marginal 173
footnote VPh, v.l.Pa | ἀλλὰ — προειρημένων suppl. m.po.Pc | τινα (pro μετὰ) Ph 2 οἷον ὅτι Py | ἐξ[ην m.2] [lI&#x7f;—III]στίζειν Vc | μαστίζειν τοὺς *μοιχούς· μαστίζων, mg. m.1 *αὐτομόλους, Ph 3 μοιχοὺς etiam post τις Py, cf. Syr. 2 p. 198, 18 | φεύγει φόνου VPhy 6 μὲν ante διαιρεῖται Ba, (er.) Vc, post διαιρεῖται AcPh γ 8 καὶ τῶι περιεχομένωι Pc 9 ἀντιλήψει add. post μιεταλήψει Ph, m. po. Vc: at schol. P(W VII 689,23) | θέσει: monet Georgius VII 695, 13 W. ῾ παρῆκεν αὐτὴν ἐν τῇ ἐξετάσει 〈92, 7〉 ὁ τεχνικόςʼ 10 δεῖ Ph | περὶ post μὲν add. PAc, m. 2VcBa | ἡ om. Pγ |εἴη ἡ ἀμφιβολία VcBa; ἡ ἀμφιβολία γίγνεται Vγ, v.l P, v. l.m 2Vc 11 γλίσχρον αὐτὸ PPγ, (ἀχρεῖον καὶ m. 2supr.) Vc; ἀχρεῖον καὶ γλίσχρον αὐτὸ Ac Vγ, v.l.P; αἰσχρόν τε τὸ ζήτημα Ph; schol. P (W VII 684, 24): εἰ μὲν αὐτὴ καθʼ ἑαυτὴν ἡ ἀμφιβολία εἴη, ἀσθενὲς καὶ γλίσχρον ἀνάγκη εἶναι τὸ ζήτημα |εἶναι ἀνάγκη Ac | τὴν om. Ac 12 εἰ Pc, (ὅτε m. 1 supr.) Pa; ὅτε VPγ Vγ sr; ὅτλν Ph | γ[έ ex ί; m. 2]νται Ph; γένηται Ac 13 τὸ om. Ph αὐτῆς om. Pγ 14 λόγων γιγνωμένοις Ph 15 [π]ᾶσιν τούτοις ἑυρίσκεται Ph | ἐστιν m.1 supr. Pa | τοῦτο παρευρίσκεται v.l. Max. Plan. IV 846, 10 W.; γρʹ παρευρίσκεται m.2Ba
marginal 63
footnote 90, 5 —92, 11: folia exciderunt Py 2 cf. 41, 16 2 sq. χρύσεια Ph | δημόσια φησὶν εἶναι Ph 3 τις om Vγ 3. 4 τίς φησιν αὐτὴν Pa Vc; τις αὐτήν φησιν BaPh, (τις om.) Pc; φησί τις αὐτὴν Ac 4 εἶναι δημοσίαν φησὶ P φησιν εἶναι δημοσίαν VcAcPh; φησι δημοσίαν εἶναι Ba 5 post δὲ add. P: δημόσια· γέγονε γὰρ παρὰ τὸν τόνον ἡ ἀμφιβολία, eadem (om. δημόσια) Ph, mg. (scholion enim est!) Ac; om. Vγ, v. I.P; cf. 41, 15 sq | σε supr. (m. 2?) Ph 8 ὑπʼ P; ἐπʼ V Ph; cf. 86, 4. 5 9 εἶναι post τοῦτο supr. m. 2Vc | ὁ νο-μοθέτης om. Ph 10 διώκων ante ἐρεῖ add. Georgius W VII 693, 26 11 ἐπὶ — 12 λόγον v.l. P; κατὰ λόγον τῶν ἄλλων ἀδι-κημάτων P; ἐπὶ τῶν ἄλλων κατα λόγον τῶν ἀδικημάτων Ph, (τὸν ἄλλον κατάλογον) Ac; ἐπὶ τῶν ἄλλων [ἐλαττόνων del. ; τῶν supr., m.2?] ἀδικημάτων, mg. κατὰ λόγον m. 2, Vc; ἐπὶ τῶν ἄλλων ἁμαρ-τημάτων, mg. κατὰ λόγον m. po., Ba 12 τὰς, supr. καὶ (m. 2?), Vc 12. 13 τῶι περιέχοντι καὶ περιεχομένωι | καὶ περιεχόμενον om. Ph 14 δημόσια ἔσται VPh 15 δημοσίων om. Ph | ἀφεῖ-ται Pc, (ίε supr) Pa; ἀφίεται VPh
marginal 174 64
