@node
@author=Alexander of Aphrodisias
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Ivo Bruns
@filename=tlg0732.tlg011.1st1K-grc1
@funder=Harvard Library Arcadia Fund
@principal=Gregory Crane
@publicationStmt=Harvard College Library, tlg0732.tlg011.1st1K-grc1.xml.
@respStmt=Digital Divide Data, Corrected and encoded the text, Gregory Crane, Editor-in-Chief, Perseus Digital Library, Matt Munson, Project Manager (University of Leipzig), Annette Gessner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor
@sourceDesc=Alexandri Aphrodisiensis Praeter Commentaria Scripta Minora, Ivo Bruns, Alexander of Aphrodisias, Reimer, Berlin, 1887, 1, Supplementum Aristotelicum, 2.1, Internet Archive.
@sponsor=Harvard College Library
@title=De anima libri mantissa
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T15:08:14Z

42514	marginal 142r
footnote 3 τις] post ι una lit. er. V 7 γνωριμωτάτην] ην in lit. V ἀγνοστοτάτην a 9 ἀναμφίλεκτον a: ἀναφίλεκτον V 14 ποιησαίμεθα om. a 17 τὰς V: τῆς a 23 αὐτῷ Va 24 fortasse ὂν ⟨ἐν⟩ πᾶσιν αὐτοῦ Va 28 γινομένων] post ο una lit. erasa V
marginal 142v
footnote 2 ἀνδριαντοποιικῆς V: ἀνδριαντοποιητικῆς a 5 δισκεύοντα V γρ. ex. Vict: διασκεύοντα a 9 post ἄλλο τι spatio octo versuum et unius paginae relicto plura deesse indicat V 10 fortasse ⟨οὐ γὰρ φθειρο⟩ μένης τῆς ψυχῆς κτλ. cf. 12, 5 12 λείπεται] cf. p. 12, 6 13 οὐ γὰρ κτλ.] cf. p. 30, 29 18 ἔτι καὶ κτλ.] cf. p. 6, 21 24 ἂν addidi 27 fortasse ⟨ψυχὴ⟩ εἴη ἂν ἡ κτλ., ut ψυχὴ ἄρα ἐστὶν ἡ κατὰ τὸ εἶδος οὐσία 103, 2 28 διᾳφέρει a 29—103, 3 ἔτι εἰ—κατὰ τὸ εἶδος οὐσία] cf. p. 31, 10—25 29 εἰ om. Ka 31 ὅ — δεξάμενον] cf. p. 101,23 et 31,18 32 ὑγειαίνομεν Ka 35 οὐδὲ] incipit apodosis τὸ ὑποκείμενον Ka
footnote 3—5 τὸ δὲ εἶδος— αὐτοῦ] cf. p. 15, 29 sq. 6 ταδ᾿ K: τὰ δ᾿ a 7 ἤδη V ex. Vict: εἴδη Ka 8 ἐντελέχεια VK: ἐντελέχειᾳ a (ut 6) 10 παρουσία VKa ἂν οὖν scripsi: post ἂν videtur οὖν erasum esse V: ἂν Ka ὅτι V: ἄρα Ka 16 μουσικήν] sc. is est, qui 18 οὐδὲν γὰρ ἧττον κτλ.] cf. p. 16,12 23 οὐσία Ka 25 ποδαποῦ] post ο una lit. eras. V 28 ἂν om. Ka 31 αὐτῷ VKa 37 αὐτοῦ VKa
marginal 143r
footnote 1 στόματος V: σώματα Ka 5 εἴη ἂν ἡ ψυχὴ κτλ.] cf. p. 16,2 8 fortasse δυνάμεσιν ⟨ὄργανα⟩ τε om. K 10 γίνεται δὲ κτλ.] cf. p. 28,25 11 ἔχοντος] alterum ο in lit. V 12 κατηγοῦμεν a 15—17 τὸ δυνάμενον—ζωὴν ἔχον om. K 17 ὀργανικόν] cf. p. 16,11 sq. 18 δῆλον ὡς ἀσώματος κτλ.] cf. p. 17,10 sq. 20 ἢ εἰ εἶδος m2, ἢ εἶδος m1 V: ἢ εἶδος Ka 25 ἀλγηδῶν Ka 26 ἀλλὰ] supra primam lit. paululum erasum V 27 τις supra lin. V 34 ἃς δέ φαμεν κτλ.] cf. p. 23, 8 sq., ubi superfluum supplementum meum 36 παλαίει V ex. Vict.: πάσχει K: παλαιὰ a
footnote 2 εἰσὶ δὲ κτλ.] cf. p. 16, 19 4 τὸ μὲν γὰρ κτλ.] cf. p. 29, 26 sq. 7 καὶ γεν. Va: τε καὶ γεν. K γεννητική VK: γενητική a οὐ in lit. V οὐ γάρ, ὥς τινες κτλ.] cf. p. 31, 25 10 πλέον δέ τι ἢ κτλ.] plus habent plantae, quam haberent secundum naturam solam cf. ἀλλ᾿ ἐκεῖνος πλέον τι παρὰ τοῦτον ἔχει p. 109, 24 ἔχει γὰρ κτλ.] cf. p. 31, 7 11 αὐτῶν VKa 12 ἃ κατὰ] fortasse καθ᾿ ἃ παρουσία Ka 14 μέντοι V: μὲν Ka 15 ἐπὶ V ex. Vict: ἐπεὶ Ka ὁρμητικὸν Va: ὀρεκτικὸν K 18 φυτικόν scripsi: φυσικόν VKa 20 τῷ ζῴῳ V: τὸ ζώῳ Ka 22 φυτικὴ scripsi: φυσικὴ V Ka 28 τὸ δ᾿ ὁρμητικόν κτλ.] cf. p. 73, 18 sq. 33 ὀρεκτικὸν VK: ὀρετικὸν a 34 τὸ post καὶ om. Ka βούλεσθαι ex. Vict: βουλεύεσθαι VKa cf. 146v11 ἔστι δὲ τοῦ ὀρεκτικοῦ καὶ τοῦ ὁρμητικοῦ τό τε ἐπιθυμεῖν καὶ τὸ θυμοῦσθαι καὶ τὸ βούλεσθαι
marginal 143v
footnote 4 τό τε V: τὸ Ka 5 κινεῖ δὲ κτλ.] cf. p. 21, 24 sq 9 βοῦς VK: βοῦν a ἄμαξαν a 11 νοεῖν τε καὶ V: νοεῖσθαι καὶ K: νοεῖν καὶ a 12 νοηθῆναι] η post ο in lit. V 14 αἴτιαι Ka: αἰτιαι V 15 τὴν om. Ka 19 κατ᾿ ἀριστοτέλην MKa ὁ μὲν γάρ τις] cf. 76,9 ἡ μὲν γάρ τίς ἐστι δύναμις ὑπηρετική . . , τὸ δέ τι τῆς ψυχῆς ἡγεμονικόν ἐστι et 81, 8 ἡ μέν τίς ἐστι δόξαστική, ἡ δὲ 22 ὕλῃ ἐν scripsi: ὕλη ἐν VMKa ὕλη εἶναι M πάντας M fortasse πάντα ⟨γίνεσθαι⟩ cf. v. 26 ἐν ᾧ τὸ δύνασθαι] incipit apodosis 24 νοῶν supra lin. m¹ 28 παρεμφαινόμενον γὰρ κτλ.] cf. p. 84, 15 et adn. 29 ἔμελλεν VM: ἔμελεν Ka 30 οὔτε] fortasse οὐδὲ cf. Ind. οἰς M: αἷς VKa αὐταῖς εἶναι M 31 τοῦο οὖν M 32 αἰτήληψις a
footnote 2 ἀφῆ δὲ om. 3 τῶν δὲ VKa: ἀλλὰ τῶν M 4 ἀδυνάτου M 5 γεννητὸν MKa 6 ἀδύνατον ἦν τὴν M 7 τις VKa: τίς ἐστι 8 οὐδὲν αὐτῶν M fortasse οἶόν τέ τι 11 γὰρ om. 13 αἰσθητῶν V: αἰσθήσεων MKa 14 fortasse ἔστι γάρ τι ut v. 16 οὐδέ ἐστί τι τῶν ὄντων ὅλως ἐνεργείᾳ 15 ἐνέργεια M 16 πάσχον M 17 τὸ om. Ka δυνάμενον] ν post ο in lit. V 19 οὖν om. M 20 κεκοινωκόσι M 21 „περὶ τοῦ ἐν ἕξει νοῦ. “ ἄλλος δέ VMKa 22 αυτοῦ V: αὐτοῦ MKa ὢν corr. ex. οὖν (?) K 23 αὐτῶν VKMa 28 νοῦς om. 29 „περὶ τοῦ ποιητικοῦ νοῦ“. τρίτος δέ VKMa νοῦς ὁ παρὰ MKa εἰρημένους MKa 30 ὥς φησιν κτλ.] Ar. de an. 3,5. 430a15 ὁ om. MKa 34 αὐτοῦ MKa καὶ —τοιοῦτον om. M
marginal 144v
footnote 2 αὑτοῦ V: αὐτοῦ MKa 3—15 τὰ μὲν γὰρ—ἐνέργειαν γίνεται] cf. Ps. Alex. in Ar. met. 668,24—669,3 3—4 τὰ μὲν γὰρ—νοητά] ὅσα τῶν εἰδῶν ἔνυλά ἐστι καὶ ἐν ὕλῃ τὸ εἶναι ἔχει, ταῦτα ὑπὸ τοῦ νοῦ γίνεται νοητά, δυνάμει ὄντα νοητὰ καὶ μὴ καθ᾿ αὑτὰ μηδὲ ἐνεργείᾳ Ps. Al. 24—25 4 ἐστιν om. M 5 αὐτοῖς VM: αὐτῆς Ka 6 καὶ] ἐστι καὶ Ps. Al. 28 7 αὑτῶν V: αὐτῶν MKa: ἑαυτοῦ Ps. Al. 28 7—8 τὸ νοούμενον VKM: τὸν νοούμενον a 8 ἁπλῶς VM: ἁπλῶν Ka 9—10 ἐπιστήμη—ἡ κατ᾿ ἐνέργειαν om. Ps. Al. 11 αὐτὴ] αὐτή ἐστι Ps. Al. 31 τῇ VKa: ταὐτὸν τῇ M 12 δὲ καὶ om. Ps. Al.: δὲ del. Freudenthal. sed. cf. lnd. 12—13 ὁ αὐτὸς —ἐνέργειαν νῷ om. 14 λαμβάνων om. M: λαβὼν Ps. Al. χωρίσας Ps. Al. 15 κατ᾿ ἐνέργειαν ante ἐκεῖνο om. M 16 δή VKa: δέ ἐνέργεια a νοητὸν V: νοῦς MKa τῇ VKa: τῶ τῆ M αὐτοῦ VMKa bis 17 τοῦ ἄυλον M αὐτὸ M ex. Vict.: αὐτῷ VKa 19 αὑτοῦ V: αὐτοῦ MKa 20 τοιοῦτον MKa 24 αὐτὸ νοῶμεν MKa 25 fortasse τόδε δέ 25—26 τὸ δὲ—νοῆται om. M 26 εἰκότως ἐπειδὴ ἐπεὶ 27 αὐτὸ M 28 αὑτοῦ V: αὐτοῦ MKa 29 ὁ om. M
footnote 1 νοῦς om. M καὶ τῶν] αὐτῶν M 2 οὐδὲ M νοῆται M 4 τέ om. M ἔστι καὶ λέγεται] cf. εὑρίσκεται καὶ ἔστι 159r12 καλεῖται καὶ ἔστι 153v26 αὑτὸν V: αὐτον M: ἑαυτὸν Ka 7 αὐτὸν M 11 δὲ VKa: ἂν M αὑτῆς scripsi: αὐτῆς VMKa 12 ταυτὰ M ex. Vict.: ταῦτα VKa ὡς γὰρ ἔφαμεν] 108,10 14 αὐτοῖς M: αὐτῆς VKa 15 αὑτὸν V: αὐτὸν MKa αὐτὸς VKM: αὑτὸς a 16 fortasse νοητοῦ 〈αὑτοῦ〉 ἀντιλήψεται 19 ἐνοεῖτο V: ἐννοεῖτο M: ἐννοεῖ τὸ Ka 20 ἐννόει M 21 ἐστιν scripsi: εἰσιν VMKa 22 αὑτὸν om. 23 αὑτὸν ννοεῖ sic V 25—110,2 οὐδὲν γὰρ ἄλλο—νοήσει] cf. Ps. Al. in met. 673, 19—27 25 αὑτὸν V: αὐτὸν MKa τὸ M πρὸ M αὐτοῦ VMKa 26 αὑτοῦ V: ἑαυτοῦ M: αὐτοῦ Ka 27 〈ἀεὶ〉 Freudenthal addit cf. Ps. Al. v. 21 δὲ VKa: δι᾿ 28 μόνον] μᾶλλον Ps. Al. 23 30 οὗτος VKM ex. Vict.: οὖ τις a αὑτῷ V: αὐτῷ MKa 31 γὰρ ἄρα μόνον M μὲν ἄρω] μὲν γὰρ Ps. Al. 25
marginal 144v
footnote 1—2 νοῦς—μόνος om. K 1 νοήσει ἀεί Ps. Al. 26 1—2 καθὸ— νοήσει] καθὸ δὲ ἁπλοῦς ἐστι, μόνος τῶν νοητῶν μόνον ἑαυτὸν νοήσει Ps. Al. 26—27 4 Ἀριστοτέλους] Ἀριστοκλέους Zeller, die Philos. d. Griechen IV 3 785 5 ἀριστοτέλην MKa ταῦτα δὲ M 7 τι καὶ V (τ in lit.) M: καὶ Ka 9 δὲ τί τὸ M 10 δὴ om. M 12 αὑτῷ] MKa: αὐτῷ V 18 ἡ ἐνέργεια M, sed cf. αὕτη γὰρ αἰσθήσεως διαμαρτία τὸ . . γίνεσθαι p. 41,12 αὕτη γὰρ φύσις αἰσθήσεως τὸ . . κρίνειν p. 152r52 19 ὄντα αἰκαθ᾿ αὐτοῦ VMKa 20 δὴ αὕτη V: δὲ (δὴ?) αὕτη M: δὲ αὐτή Ka fortasse καθ᾿ αὑτὰ ⟨τὰ εἴδη αὐτῶν⟩. εἰ δὴ αὕτη 21 ἐνέργεια VK: ἐνέργειᾳ a: ἐνεργεία M 22 γίνεσθαι V: ἄγεσθαι MKa sed cf. 112,1 25 αὑτοῦ V: αὐτοῦ MKa 27 οὐσίᾳ a 29 ἑαυτῶν φύσει VK: ἑαυτοῦ φύσει M: ἑαυτῶν φύσειν a 31 τελειούμενον M πατητικὴ M
footnote 1 δὲ om. M 2 αὐτῷ VMKa ὁ om. αὑτοῦ V: αὐτοῦ MKa 8 παρὰ τὴν M 10 οὐχ M 11 χαρακτηρίζοντο M 13 ποιητικὸν M 16 τε] αι del. supra τε M 17 τί om. M 20 αὐτῷ VMKa 21 αὐτὸ M ποιητικότατον M 23 ἢ ex. Vict.: ἧ VMKa 25 οὔτε VKa: οὐδὲ M 27 τῷ scripsi: τῶν VKa: τοῦ M 28 τοῦ ἰδίᾳ 29 αὐτοῦ VMKa γινόμενον 31 καὶ ἀθάνατος suspectum cf. 112, 5 τὴν VM: γε Ka 35 τῇ] τ in lit. V τῇ αὐτοῦ τελειῶν φύσει Ka: τελειῶν τῆ αὐτοῦ φύσει M 36 ἐστὶ μὲν οὖν M τέχνη VMKa
marginal 145r
footnote 1 τούτου καὶ VKa: τοῦτον καὶ ποιήματα VM: ποίημά τις K: ποιήματις a παθὼν V: παθῶν corr. in παθὼν M: παθῶν Ka ὑπό τινος καὶ γενόμενος 2 νοῦς M: νοῦν VKa 3 τελειωθεὶς MKa: τελεωθείς V τὰ τῆ φύσει τὴν om. 4 τοῦ νοῦ VM: νοῦ Ka νοεῖν VKM ex. Vict.: νοεῖ a 6 τὰς ἐπιφερομένας M ἀνάγκη M post ἔχοντι paululum erasum V 7 δέ M: γε VKa 8 ταῦτα περὶ νοῦ M 9 λεγομένου scripsi: λεγομένῳ VKMa 11 αὑτοῦ V: αὐτοῦ MKa 12 δύνασθαι] cf. Ind. 13 fortasse τοῦτο 14 παντὶ γενομένω M 15—16 ἐπὶ usque ad γινομένη om. MKa 17 τότε VKa: τὸ M δι᾿ om. M 19 ἥτις scripsi: ἤ τις VKMa ὃν] fortasse ἣν 20 νοῦ καλεῖ ὁ ἀριστοτέλης M 22 κεχωρικῶς M 23 διὰ VKa: ὁ τὰ 25 ἐννοῆσαι VMKa 26 τότε M 27 ἐνέργει M τὴν ὕλην M: τῇ ὕλῃ VKa cf. Ind. 27—28 αὐτῷ περὶ τῇ ὕλῃ—καὶ ἔστιν ἐνεργείᾳ bis Ka 30 τότε om. M 32 διαινομένῳ M
footnote 1 fortasse τοῦ ὀργάνου 3 post δὴ lacuna trium literarum M ἀριστοτέλην MKa 4—5 τὴν λέξιν δὲ τὴν ἐν τῷ τρίτῳ περὶ Ψυχῆς] Ar. de an. 3,5. 430a11 sq. 5 προσοικειοῦν VK: προσεικοῦν M: προσοικοῦν a 7 ὁ αὐτὸς M 9 τὰ om. 12 τότε τούτοις MKa 15 καὶ μὴν καὶ MKa 17 ἐν ὑπάρχει 18 ἢ ex Vict.: ἣ VKa: ἥτις M cf. p. 82,12 19 τὸ om. M 22 ἀμίβων a 31 ἔτι εἰ scripsi: εἰ VKa αὐτοῦ Ka 32 ἐνεργείᾳ V ex. Vict.: ἐνέργειαν Ka
marginal 145v
footnote 3 αὐτῆς Ka 4 ἢ VK: ἡ a 5 ἐκείνου scripsi: ἐκείνει V: ἐκείνη Ka 8 ὑγειῶς Ka 11 εἶναι λέγοιμεν Ka 13 μέντοι] cf. p. 158a30 εἰ . . λέγοιτο, προσδεήσεται μέντοι 16 λέγομεν delendum videtur 17 ἢ VK: ἡ a τῶν σωμάτων delevi 19 τε om. Ka 21 οὐ post τὰ δ᾿] υ in lit. V 22 οὖν om. Ka 39 αὐτὸ Ka ἐκ τῶν Ka
footnote 1 fortasse οὐδὲ 2 αὐτὴν Ka 3 συνέχετεται V 4 ἀσώματα Ka 5 αὐτὸ VKa 8 πᾶν] post ν paululum erasum V 9 ταυτὴν a 10 τόνου ἀλλὰ] υ ἀ in lit. V ἀλλὰ εἰ V: ἀλλ᾿ ἀεὶ K: ἀλλ᾿ αἰεὶ a: ex. Vict. in mg. γρ. ἐν 13 ἀσώματος Ka 14 μὴ καὶ Ka: καὶ μὴ V 19 πεφυσσημένος K αὐτῷ VKa 23 fortasse ἡμέτερον σῶμα 25 οὔτε V ex. Vict: ὄντε Ka 38 fortasse ἔσται
marginal 146r
footnote 1 προσγινόμενα Ka: προσγενόμενα V 7 fort. συνεφθαρμένων καὶ συνηλλοιωμένων 8 τι om. K sed cf. 106,19 adn. 11 τὸ ἐκ V: τι Ka 12 τοῦ Va: τι K 14 προσγινόμενα K 23 καθὸ σῶμα m2, καθὸ σῶμα σώματι m1 V: καθὸ σῶμα Ka 25 τὸ V: τι Ka 29 τὸ V: τῷ Ka 33 αὐτοῖς V ex. Vict.: αὐταῖς Ka 35 τοῦτο Ka: τοῦτον V ἐν τούτων m2, ἐν τούτῳ m1 V: ἐν τούτων Ka 36 οὕτως] ω in lit. V 37 ὡς τὸ m2, ὡς m1 V: ὡς τὸ Ka
footnote 1 δεικνύναι V τὴν] ὴν in lit. V οὔτε . . ἀλλὰ καὶ ὁ λόγος ψευδὴς (v. 9)] cf. v. 11 et 14 et p. 12,1 6 ὥστε κἂν] ὥ et ἂν in lit. V 7 ποιότητος] οιο in lit. V 8 ψυχῇ οὖν ψυχὴ Ka 12 ante πασχόντων συμ erasum V πλεῖστα] εῖ in lit. V 13 θλωμένου m1, τεθολωμένου m2 V: τεθολωμένου Ka 14 ἀλλ᾿ οὐδὲ κτλ.] exspectas ἀλλ᾿ οὐδὲ ὡς ἄλλη οὖσα καὶ κεχωρισμένη τῷ σώματι συμπάσχει ἡ ψυχή sed cf. 7,1 οὐ μόνον δὲ παρὰ τοῦ εἴδους τό τε εἶναι κτλ. 16 συναμφότερον m2 αμφότερον m1, sed lit. trium liter. ante α m1 V: συναμφότερον Ka 19 θερμαίνεσθαι Ka: θερένεσθαι V 21 οὔ om. Ka ὑγιὴς VK: ἱγυὴς a 22 χωρίζεσθαι σώματος Ka 24 μένει Ka 25 σώματος om. K κατὰ κτλ.] cf. 122, 14 adn. 26 ἀσώματος Ka 29 ἀπ᾿ om. Ka 30 ἔτι οὐκ ἀληθὲς κτλ.] aut argumentatio (eo, quo respiramus animati sumus. anima autem respirare possumus. spiritus igitur anima) mutilata est, aut, quod magis placet, hoc tantum dixit Alex. „non verum est, nos eo, quo respiramus, animatos esse“ (οὐκ ἀληθὲς τὸ· ᾧ ἀναπνέομεν τούτῳ ἐσμὲν ἔμψυχοι”), in margine autem aliquis inter ἔμπνους et ἔμψυχος distinxit, unde verba ἔμπνοι τῇ δὲ ψυχῇ in textum irrepserunt 31 ἔμπνοι m2, ἔμπνοιοι m1 V: ἔμπνοι Ka
marginal 146v
footnote 8 cf. 27, 7 11 τὰ a 14 cf. 105,8 18 αἰσθανόμεθα Va 20 φυτικὴ V: φυτικὴν a 21 τε om. a 22 ζώη Va 25 ψυχικόν V: ψυχὴν a 27 οὐκ εἰσὶν κτλ.] differentiae non [in eis rebus positae sumt], de quibus anima agit, sed cf. v.   οὐδὲ τῷ περὶ ἃ 28 αὐταὶ scripsi: αὗται Va 31 πλείονα a 34 θρεφόμεθα a 37 ἀλλ᾿ ἔστιν] λ ἔστιν in lit. V
footnote 10 τὸ ante βούλεσθαι om. a 17 ὁρμᾶν V: ὁρᾶν a 21 Cf. Alexandri quaest. Mat. 1,8 et 1,17 22 καὶ ὁ Ka ἐν ταῖς Κατηγορίαις] Ar. Cat. 5,3a7 23 τῷ om. K ὡς ἐν K 25 ὧν om. Ka ἥ τε V: εἴ γε Ka 26 οὐκέτι δὲ] de anacolutho cf. p. 122,14 27 εἴρηκεν ἐκεῖ] Ar. Cat. 5. 3b24 28 καίτοι λέγων] saepius cf. lnd. Ar. 700a20 sq. 29 oοὖν om. Ka 31 τις τρόπος V: τις τόπος K: τι τόπος a 35 parenthesin posuit Usenerus τι εἶναι οὐδὲυ δὲ (πι supra versum ναι ου in marg. δὲν δὲ in lit. m1 sive vet. corr.) VKa οὐδὲν δὲ κτλ.] „neque quidquam, si referatur (πρὸς τὸ) ad actualem existentiam definitae qualitatis, etiam extra id, in quo inesse dicitur, separatim forma [corr. εἶδος] est.“ Usenerus
marginal 147r
footnote 6 τὸ om. K 7 ὡς] fortasse ᾧ 16 σὺν γὰρ ταύτῃ ὂν ὀργανικόν] cf. 5,10, nisi exciderunt quaedam post βαρύτητι 17 οὔτε] fortasse οὐδὲ, sed cf. v. 31 adn. 18 ἐν om. Ka 19 τῷ ξύλῳ K 22 ξύλοις m1 in marg. ὑλικοῖς in text. V: ὑλικοῖς Ka 24 τότε om. Ka ἄνθραξ] ἄν in lit. V 26 τι Ka: τινὶ V 31 νῦν (πρ vet. corr. supra lin.) V: πῦρ Ka: fortasse πυρὶ; ἐν τούτῳ enim (v. 30) cum ad carbonem referri debeat, sequitur ut ἐν ἐκείνῳ (v. 31) dictum sit de igni. sensus autem est: aeque in carbone ὡς ἐν ὑποκειμένῳ esse id, cuius natura in igni posita est (ὃ ἐν τῷ πυρὶ τὸ εἶναι ἔχει cf. τὸ δὲ ἐν ὕλῃ τὸ εἶναι ἔχει 88, 15) neque in igni esse ὡς ἐν ὑκομειμένῳ carbonem. carbonem autem ita circumscribit: id quod antea carbo erat, nunc vero, ubi ignis in eo exstitit, carbo esse desiit et interiit quae cum ita sint, poterit aliquis conicere v. 17 excidisse post οὔτε τὸ πῦρ ἐν τῷ ἄνθρακι: οὔθ᾿ ὁ ἄνθραξ ἐν τῷ πυρί 33 σημειωτέον] cf. 122,14 adn. ὁ ἀριστοτέλης K
footnote 1 ἐν τῷ δευτέρῳ τῆς Φυσικῆς Ἀκροάσεως] Ar. ausc. phys. 2,1 192b34 2 ἀρχόμενος τοῦ δευτέρου περὶ Ψυχῆς] de an. 2,1 412a18 τοῦ περὶ ψυχῆς δευτέρου Ka 4 μὲν om. Ka 5 τὴν δὲ ψυχήν V: δῆλον ὅτι τὴν ψυχὴν εἶναί φησιν Ka 6 λέγει Ka 7 εἶδος] εἶ in lit. V τὸ ante ἐν om. Ka 14 ψυχῇ scripsi: ψυχὴ V: ψυχὴς Ka 16 fortasse πάντων τῶν φυσικῶν ⟨γένεσις ἐξ⟩ οὐσιῶν. ita concludit: partes, quibus formantur verae substantiae physicae, substantiae sunt. animal autem substantia physica et anima pars animalis. anima igitur substantia physica 17—19 καὶ γὰρ τὰ τεχνητὰ—αἱ ἐντελέχειαι οὐσίαι om. Ka 21 αἱ om. Ka 22 οὐσίᾳ a 27 μὴ] οὖν Ka 28 ἀσωμάτων V: σωμάτων Ka ἐκ τούτων V: ἐξ ὧν Ka cf. 122, 14 adn.
footnote 2 οὐχ ἀπλῶς] incipit apodosis 3 ὕλης Ka κεχωρισμένον scripsi: κεχωρισμένου Va 4 μὲν om. Ka 4. 5 fortasse οὐσίας οὐσίας 5 τὴν ὕλην καὶ τὸ εἶδος Ka 12 τὸ εἶδος insiticium videtur 14 ἂν V: ἂν οὖν Ka cf. ind. s. v. asyndeton quae est hypomnematica in hoc libro scribendi ratio, permulta dissoluti sermonis exempla nolui mutare 20 ἡ ποιότης οὐκ οὐσία] cf. quae dixi ad v. 14, quae nisi obstarent, confidentius totum enuntiatum ita conformarem: ἢ ⟨εἰ⟩ ἡ ποιότης ἑτέρα τῆς ὑποκειμένης αὐτῇ φύσεως (οὐ γὰρ ταὐτὸν ὕδωρ καὶ ἡ περὶ αὐτὸ ψυχρότης, ἐπεὶ ἦν ἂν πᾶν τὸ ψυχρὸν ὕδωρ καὶ πᾶν ὕδωρ ψυχρόν), καὶ ἔστιν ἡ ὑποκειμένη τῇ ποιότητι φύσις οὐσία, ἡ ποιότης οὐκ οὐσία 22 ἀλλὰ μὴν τὸ πρῶτον, τὸ κτλ.] cf. nd. 28 ἐναντίων ἐναναντίως (sic) V: ἐναντίως K: ἐναντίως ἐναντίως a 30 μελανίας V K: μελανείας a 32 ἁπτή Ka: (sic) ἁπτή V
marginal 147v
footnote 4 ἔτι εἰ scripsi: εἰ VKa 5 ἔχει Ka 13 ἐν ἄλλοις] de mitione libellum respicere videtur. 6. 20,18 ἐδείξαμεν V K: καὶ δείξαμεν a 19 ἄπισιν V 20 ἀντείσισιν V ἔτι εἰ scripsi: ἔτι VKa 26 μετακομησθέντος, μ in lit. V, fortasse παρακομισθέντος cf. v. 22 27 ἴσον semper V: ἶσον a 31 fortasse ⟨ἡ⟩ ἐν τῷ πρώτῳ ἀέρι 33 πολυπλάσιον V: πολλαπλάσιον Ka 37—38 εἴη ἂν—ποιότητος om. K
footnote 1 ἡ—οὐ ποιότης] ἡ ποιότης οὐ ποιότης K: οὐ ποιότης ἡ ποιότης a 4 ἂν om. Ka 15 συμμεταφέρεται] verba respicit: καὶ μετενεχθέντος πάλιν εἰς ἄλλον ἀέρα ἄλλο πάλιν ἄπεισιν τοσοῦτον 19 ὄντα Via: ὄντος e Vict.: fortasse διήκοντα 22 ἐπινοία V 24.25 ἐναργὲς—διαφέρουσιν] argumentum ex margine inlatum delevi 27 τὸ μὴ μετειληφός Ka 34 λέγον Ka 37 σώματος om. Ka τῷ] fortasse ὡς
marginal 148r
footnote 1 τὸ ante ὑποκείμενον om. Ka 5 τεσσάρων a ut solet 9 ἀντιτυπές a: ἄντιπες V 13 ἐν αὐτῷ a 18 ὁμονύμως a 22 τότε om. a πλέον a πνεῦμα τότε a 23 συγκεκλεισμένα a 30 ἔξω V: ἄλλων a 31 εἴη] εἰ in lit. V 33 αυτῶν V: αὐτῶν a 36 αὐτῷ?
footnote 1 κεκοινονηκότος a 2 ἔτι᾿ om. a 3 καὶ om. a verba, quae uncis seclusi, huic loco non potest scriptor destinasse, cum verbis sequentibus (ἔτι πῶς ἐκ τῆς κτλ.) eorum opinionem refellere pergat, qui esse quaedam minima corpora ignis expertia contendant; fortasse igitur post συντίθοιτο v. 10 collocanda sunt 6 μίξίς a 8 αὐτῶν ἕκαστον a 14 θερμότητος V: ξηρότητος a ἐναναντίων V 15—16 εἰ δέ usque ad δέξασθαι om. a 18 fortasse φύσιν, εἴ γε ἀδύνατόν ἐστιν . . πεσεῖν, εἰ μὴ . . μεμιγμένον εἴη· ἐν γὰρ τούτῳ . . διαφέρει, ὥστε. continent enim haec verba εἰ δέ γε—διαφέρει adversariorum argumenta, quae si cum praecedentibus artius coniunxerimus, et anacoluthon tollitur et sententiae (inde a πῶς οὐκ v. 16) bene sic procedunt: cur materia cum calido siccoque coniuncta non tactilis est? hoc enim negantibus fatendum erit (ἔσται γὰρ οὕτως αὐτοῖς), calidum per se non sensibile esse, quia (secundum eosdem) calidum, licet ὑφεστὸς ἐνεργείᾳ, nisi cum frigido mixtum percipi non potest 21 αὐτοῦ a 24 θερμόν a 27 fortasse κοῦφον καθὸ θερμόν 28 βαρείᾳ α: βαρεία K: βαρεῖα V
marginal 148v
footnote 5 διαφέρει Ka 9 εἴδει ex. Vict.: εἴδη VKa 10 διαφέρει Ka 23—24 ἄλλῳ usque sad σύμβολον om. Ka 24 δύναται εἶναι ἢ Ka cf. ind. 27 διὰ τῶν Ka τὸ ὁρᾶν λέγοντας Ka γίνεσθαι om. Ka 33—34 εἰ μὲν—ἀέρος] cf. Al. de sens. comm. 64,10—11 35 μὲν] fortasse μένει sed cf. Ind. 36 εἶτα διὰ τί κτλ.] cf. Al. de sens. 65,6—11
footnote 3 σκότους m2, σκότος m1 V: σκότους Ka 4 τὸ γὰρ ἧττον κτλ.] cf. Al. de sens. 47,13 sq. φῶς ὑπὸ VK: φωτὸς ὑπὸ a 6 λάμπον Va 8 supra ταὐτὸ: τὸ m² V 11 ἄλλων Usenerus 12 εἰ m1 V, εἱ οὖν m2: εἰ οὖν Ka cf. 122,14 14 δή m, δέ m1 V: δή Ka ἐστι Ka 15 οἴονται Ka: οἷόν τε V 16 ἔτι εἰ κτλ.] cf. Al. de sens. 4712 εἰ πῦρ ἐστι om. Ka 17 ὁρῶμεν δὲ κτλ.] cf. Al. de sens. 65,3 ἔτι εἰ πῦρ κτλ.] cf. Al. de sens. 64,11 — 65,3 20 εἰ δι᾿ V ex Vict.: ἡ δι᾿  corr. in εἰ δι᾿ K: ἡ δι᾿ a 23 ἂν addidi 24 ἐκπίπτει Ka 25 πόρον] ante ρ 2—3 lit. e. V 27 τὸν ante ἔξωθεν] ante ν una lit. eras. V 29 σώματα Ka: σῶμα V 30 ἤτοι χεῖται V: εἶτα χεῖται K: ἢ ταχεῖται a: ἤτοι παχεῖται ex. Vict. 34 ἔτι εἰ σῶμά ἐστι κτλ.] cf. Al. de sens. 61,6—62,11 δίεισιν m2, δίεσιν m1 V
marginal 149r
footnote 9 πλήρεις VK: πληρεὶς a: fortasse εἴ γε ⟨μὴ⟩ πλήρεις 10 τὸ τῆς m1, τῆς m2 V: τῆς Ka (corpus quod in pupilla inesse solet) cf. τοῦτο τὸ σῶμα τὸ τῶν ἀ. 127,29 τουτὶ τὸ ῥεῦμα τὸ τῆς ὄψεως 128,26 16 supr καὶ v. c. συν scripsit V μεῖζον scripsi: μὴ μεῖζον VKa 19 ἔλαττον m1, ἐπ᾿ ἔλαττον v. c. V: ἐπ᾿ ἔλαττον Ka τὸ addidit Usenerus 20 ποιοῦσαν Ka ἔτι τε πῶς κτλ.] cf. Al. de sens. 6,2—7 21 ἔτι δὲ αἱ ἀκτῖνες κτλ.] cf. ἔτι πῶς οὐ συγχέονται οἱ τοιοῦτοι τύποι, ἐπειδὰν ῥέῃ τὸ ὕδωρ, τὸ δὲ αὐτό, εἰ καὶ ἐν ἀέρι πνεῦμα πολὺ εἴη 134,9 23 παραφέρονται Usenerus καὶ τούτων κτλ.] de rapidis fluviis dicere videtur, quorum vadum perlucet, dumne supericies perturbata sit. sed plura exciderunt 26 καὶ ἔσται Ka: ἢ ἔσται V ἢ πλήρεις ex. Vict.: ἢ πλῆρες a: πλῆρες V 28 fortasse ὄψονται σώματος Ka 31 ἐπισκοτεῖσθαι] ι in lit. V 32 τὸ om. Ka 33 ἀστέρων Ka καὶ τοῦτ᾿] fortasse καὶ ποῦ
footnote 2 ὁρᾶν ἡμᾶς Ka ἔτι πῶς οἱ ἐξ ἐναντίας κτλ.] cf. Al. de sens. 63,4—9 5 σώματος δίεισιν ' m2, σώματος m1 V: σώματος δίεισιν ἢ Ka 6—10 ἔτι πᾶν—παρεστῶσιν] cf. Al. de sens. 62,11—63,3 7 κατὰ τὸ αὐτό τι] fortasse τὸ αὐτό τι cf. Al. de sens. ib. ἀλλὰ μὴν· ἀδύνατον τὸ αὐτό τι καὶ ἰσοταχῶς κινούμενον ἐν τῷ ἴσῳ χρόνῳ κινηθῆναι τόδε τι τὸ διάστημα καὶ τὸ τούτου πολλαπλάσιον κτλ. 8 fortasse ⟨καὶ⟩ τὴν διπλασίαν 11 τινος m1, τινα m V: τινα Ka 17 διὰ βακτηρίας] cf. alen. de plac. Hipp. et Plat. 642, 12 (Iw. Müller) μὴ τοίνυν ὡς διὰ βακτηρίας τοῦ πέριξ ἀέρος ὁρᾶν ἡμᾶς οἱ Στωἱκοὶ λεγέτωσαν. ἡ γὰρ τοιαύτη διάγνωσις ἀντιβαινόντων ἐστὶ σωμάτων, κατὰ συλλογισμὸν ἔτι μᾶλλον, οὐ πιλητοῦ δὲ αἰσθητικὴ ἡ τοῦ ὄμματος αἴσθησις ἡμῖν ἐστιν, οὐδὲ τῆς σκληρότητος ἢ μαλακότητος, ἀλλὰ χρόας καὶ μεγέθους καὶ θέσεως, ὧν οὐδὲν ἡ βακτηρία διαγνῶναι δύναται 21 τυπώσεως] τ in lit. V 25 ἐπερείδοντας] ς in lit. V τό τε Va 26 αὐτῶν a: αὑτῶν V ἢ ἐπέρεισιν—γίνεσθαι] an tum quoque dicent esse ἐπέρεισιν 28 διαλήψεις a 30 ἐπιζητήσεις a
marginal 149v
footnote 1 διαλείψειε a 4 λέγουσι] σι m2 add. V 8 ἔν V: ἐν a 14 ante ὁποτέρωθεν duae lit. erasae V: ὁπωτέροθεν a 21 ἀνωτέρου a 23 ὅπως δηλοῦν] fortasse πως, δῆλον ὡς 26 fortasse ἢ [ποσὸν ἤ τι τῷ] μεγέθη sive ἢ πόσον τι τῷ μ. Diels 28 μεγέθει a ἀντίληψις] ις in it. V 29 ἡ ὄψις m1 in mg. V δὲ om. a εἴ τοι a 30 πάθη τὰ scripsi: παθητὰ Va 33 μὴ addidi
footnote 5 τὰ] fortasse τὸν 7 κατ᾿ ἀντικρὺ a: κατ᾿ ἄντικρυ V 8 τοῦ δῶ V: τοῦ μὴ δὲ a 8—9 ἀέρος usque ad τῶν οἰκημάτων om. a 13 ἀλεεινότερον K: ἀλαιεινότερον Va 17 ἐκτείνειν Ka 19 ἡμῖ V 20 τὰ V: τε Ka μὲν om. K 23 ὅτι V: ἄρα Ka οὐ om. Ka 30 πεφυκώς K: πεφυκῶς a: πεφυκός V 34 τοῦ om. a 36 ἀλαίαν Va κρυστάλον a
marginal 150r
footnote 12 τὸ μὲν κατὰ τὴν κλάσιν] scil. πέρας, quod nisi excidit certe supplendum est (cf. 63,24), i. e. baculi in fractura terminus. hoc enim dicit: absurdum esse dicere sos is baculi termino per facturam orto niti ao posse, posse ia altero eius termino, i. e. in eo, qui ante fracturam proprius erat baculi terminus (δύνασθαι cf. Ind.) 19 εὔθραστα a 22 τὸ in lit. V 28 ἢ ἀὴρ insiticium videtur 33 περιολισθαίνει a βατηρία a 34 παραπίπτει a
footnote 2 γίνεται a 4 γὰρ] cf. Ind. 6 διόλου V 12—13 εἰσέχοντα τοὐναντίον] α τοὐναν in lit. V 16 ἐξελέγχει a 18 ἔτι περὶ τῶν δι᾿ ἀνακλάσεως] cf. 133, 12 21 εὐθέως a 25 τὴν post ἔτι om. a 26 τί supra lin. V δήποτε τὰ m2, δήποτε ταῦτα m1 V: δήποτε τὰ a 27 ἡ post γὰρ καὶ om. a 29 γίνεσθαι om. a 33 ἀπορρεόντων] ante ν una litera erasa V
marginal 150 v
footnote 5 ἀναμετρεῖσθαι] cf. 158 r 34 6 τῷ V ex. Vict.: τὸ a 8 κατὰ βραχὺ] cf. 136, 28 ἡ scripsi: ἣ ex. Vict.: ἢ Va 9 fortasse τοῦ τῆς κόρης 11 fortasse αὐτὴν διὰ 12 οὐχὶ addidi cf. Al. de sens. 121, 1 sq. . . καὶ γὰρ εἰ πολλάκις κα πολλὰ δέχεται, πῶς καὶ διὰ τί ἄλλο τε καὶ ἄλλο μέρος τοῦ εἰδώλου δέξεται καὶ οὐχὶ ἀεὶ τὸ αὐτὸ καὶ ἐκ διαστημάτων; 14 συντιθέμένων (ο supra ω m1) V 17 αὐτῶν om. a 18 φυλάσεσθαι V 22 πῶς δέ κτλ.] cf. Al. de sens. 122, 1 sq. 24 πῶς δὲ καὶ κτλ.] cf. Al. de sens. 121, 14 sq. 26 fortasse ⟨ἢ⟩ ὑδάτων ἐμφαινόμενα cf. 62,13 29 ἀπ᾿ .αὐτῶν om. a 30 διὰ τί δὲ κτλ.] fortasse τοῦ ὁρωμένου cf. Al. de sens. 122, 3 διὰ τί δὲ κἂν ὀλίγον ἀπελθόντος τοῦ ὁρωμένου ταῦτα (ταὐτὰ Thurot) μένει ἢ ἐξ ὧν ἐν τῇ ὄψει; 31 φανείας a 32 πῶς δὲ οὐχὶ κτλ.] cf. Al. de sens. 120, 11 καὶ sante εἰ add. v. c. V 34 φερόμενα] supra ερ: νν ut videtur v. c. V
footnote 2 fortasse ⟨ἂν⟩ αὐτὰ μένει a διεκπίπτει a 3 εὐκόλως a 6 ὁρώμενα καὶ ἐμπίπτοντα a 7 τὴν ὄψιν addidi, cf. Al. de sens. 122, 4 sq. τὸ δὲ λέγειν μυωπίκσθαι τὴν ὄψιν ὑπὸ τῶν φερομένων ἐπ᾿ αὐτὴν εἰδώλων καὶ διορίζεσθαι καὶ πρὸς τὸ ὁρᾶν παρασκευάζεσθαι οὐκέτι τηρούντων ἐστὶ τὸ διὰ τῶν εἰδώλων γίνεσθαι τὸ ὁρᾶν. δῆλον γὰρ ὅτι μυωπισθεῖσα ἡ ὄψις ὑπὸ τοῦ εἰδώλου ἄλλο τι οὐκ ὄψεται, εἰ μὴ τὸ εἴδωλον. τί οὖν ταῦτα καὶ πῶς 11 τὸ δὲ λέγειν κτλ.] cf. Al. de sens. 120, 5 sq. huc pertinet etiam de sens. 120,12 — 121, 1, quo summovetur Thuroti aporia 14 ἀτοπίαν] το supra alin. V 15 αὐτοῦ V: τοῦ αὐτοῦ a 17 ἐμπιπτόν| V 18 fortasse τὸν πρὸ αὑτοῦ 21 προώσει] ante ω una lit. eras. V 24 ἃ χρόα a 25 αὐτὰ om. a 27 ἐξετάζει a 29 fortasse λέγοντας ⟨γίνεσθαι⟩ cf. 127, 27 134, 28 136, 30 33 συμμιγὲς a
marginal 151r
footnote 2 ἀναγγέλλειν] cf. 158 r 34 9 δὲ πόσου a 10 ἄπεισι corr. ex. ἄπισι V 16 fortasse ἐπὶ τῶν πόρρωθεν 19 πήχεως m², πῆχος m1 V: πήχεως a 24 fortasse ἢ ⟨τὸ⟩ ἀπὸ 25 ἀνάμαξις V: ἀνάμιξις a. Cf. φῶς . . ὃ τῇ ἀπορροίᾳ συμμιγὲν. ἐχούσῃ τὸ εἶδος τοῦ ὁρωμένου ἀναλαμβάνον καὶ ἀναμασσόμενον τὸ παῤ ἐκείνου εἶδος 136,32 27 ἀλλὰ οὐκ m2, ἀλλὰ m1 V: ἀλλὰ οὐκ a 29 μὲν om. a 30 ἀλλ᾿ Va οὔ φασιν V ex. Vict.: ὅν φασιν a 36 τὶ ἄλλου Ka 37 τὸ φῶς Ka
footnote 4 ἔσται Ka 7 τὸ] τι Usenerus 9 fortasse φῶς· ⟨οὐκ ἄρα πῦρ τὸ φῶς⟩. Usenerus 11 γε om. Ka 12 τὸ πῦρ φῶς Ka 14 λέγει Ka 24 ἔσται Diels: ἔστι VKa 25—26 οὐ σώματος Ka 27 γάρ τι Ka 29 ἀσώματος a 31 τῷ om. Ka 33 fortasse ⟨τῷ⟩ αὐτῷ καὶ ante τρία om. Ka
marginal 151 v
footnote 4 ὃ τί scripsi, ὅτι VKa 8 ἀτοπώτατον V: ἄτοπον K ex. Vict.: ὃ τόπον a 12 αὐτῷ VKa 18 ἀπολειφθείσης Ka 19 οὐχ K: οὐ Va 20 τὰ δυνάμενα κτλ.] cf. 143,22 34 μεστόν V: μέσον Ka ὂν αὐτοῦ VKa δεξάμενον αὑτοῦ scripsi: δεξάμενον αὐτοῦ m1, δεξάμενον m2 V: δεξάμενον Ka 35 αὐτῷ VKa 36 ἐν αὐτῷ VKa
marginal 152r 3 παχυμερεστέρῳ Ka 5—6 ὕδωρ usque ad μίγνυται om. Ka 6 δὲ] ε in lit. V 8 γίνεται a 10 εἰ om. Ka 11 ὃν VK: ὂν a 13 αὑτό K 14 τῷ ἐξ V ex. Vict.: τὸ ἐξ Ka ὑπὸ delendum videtur cf. v. 12 23 μόνον Ka 25 τὸ ποσὸν V: τόπον Ka 29 τοῦτο m2, τοῦ m1 V: τοῦτο Ka 30 συγχωρηθείη] ρι m1 ρη m² V 38 τὸν post ἀλλὰ καὶ] ante ν una liter. erasa V 39 εἶναι om. Ka
footnote 1 δάδας Va 2 παχύτερος] χ in lit. V 4 εἰ supra lin. V χωρισθείσης] cf. 156r11 7 μετεβήσεται V 11 παρισωθῆ Ka 13 κοτυλῶν] post ο una lit. er. V ἰσοθεὶς a 14 ἔτι om. Ka ἡμίσει VK: ἤμισυ a 21 αυτὰ V: αὐτοὺς Ka 25 αὕτη ταύτης Ka 26—27 οὕτως usque ad ποιεῖν om. Ka 28 μεμέθη V ex. Vict.: μεγέθει Ka 29 ἀριστοτέλην aut solet 34 τε om. a
footnote 4 τρεπόμενον] ρ in lit. V 6 τις φύσις ἡ τοῦτο δυναμένη] cf. 43,1 ἀλλ᾿ ἔστι τις ἡ ἀπ᾿ ἀμφωτέρων κίνησις γινομένη 11 διαφνὲς m1, διαφανὲς v. c. V fortasse ⟨τὸ⟩ δυνάμει 13 δευτέραν v. c., δευτέρα m V: δευτέραν a ταύτην V: ταύτης a 14 τοῦ κατὰ m2, κατὰ m1 V: τοῦ κατὰ a τὸ φῶς] suspectum. exaspectas τὸ φωτίζειν πεφυκὸς τοῦ κατὰ δύναμιν cf. v. 4 18 δεχομένη a: δεχομένῃ V 20 ὁρατική τε καὶ αἰσθητικὴ ψυχὴ γίνεται] pupillam animam ὁρατικὴν ieri dici nequit, ὅτι μή ἐστιν ἡ ψυχὴ καὶ ἡ ὁρατικὴ δύναμις ἐν τῷ ὀφθαλμῷ (Al. de sens. 76,3). itaque aut scribendum bendum erit ⟨ἧς⟩ τῇ τροπῇ aut prius enuntiatum (καὶ αὕτη—δεχομένη) per absolutum quem dicunt nominativum constructum est (inter perspicua corpora etiam pupilla est; et quia haec, sicut aer, lumen accipit, siquidem ipsa quque perspicua est, per mutationem, quae fit coloribus, quibus (pupilla) sicut perspicuum externum mutatur quodammodo, anima ὁρατικὴ fit et αἰσθητική) 24 et 27 αὑτοῖς ? 26 ὁ ἀήρ m2, ἀήρ m1 V: ὁ ἀήρ a 28 αἱ scripsi: οἱ Va ὕαλοι a
marginal 152v
footnote 3 κρίνειν V ex. Vict.: κρίνει a πάθει a 5 ἀλλοιουμένοις m2, ἠλλοιωμένοις m1 V: ἀλλοιουμένοις a 10 ἐν αὐτῷ m2, ἐν ταὐτῷ m1 V: ἐν αὐτῷ a 16 τοῦ ὁρᾶσθαι πεφυκότος] sc. μεταστάντος 17 μεταβολήν] cf. οὐδ᾿ αὐτὰ κατὰ τὴν ἐν αὐτοῖς μεταβολὴν ἀλλοιωθέντα 144, 18 22 τοσούτου V: τοιούτου a 26 οὕτως] ω in lit. V πορωτέρω V 29 ἄπισιν V 30 δείκνυσιν ὁ Ἀριστοτέλης] cf. Prael. γινόμενον] ν post ο in lit. V 30—31 τοῦ γὰρ—ὁρᾷ] in quavis particnla eius temporis, per quod quis videt, id (quod videt) videt 32 τε om. a
footnote 1 διαφανὲς m2, διανὲς m1 V 3 πρόισιν V 10 ὕελοι] ὕ in lit. V ταύτῆς sic V 13 τοιᾶσδε V: τοιαύτης a 14 διὰ τοῦτο om. a 15 ταυτὸ a πάσχειν] π in lit. V 16 καθάπερ εἰρήκαμεν] cf. v. 6 τρόπον τινὰ] cf. ὅσα μὲν οἰκεῖον πέρας οὐκ ἔχει, ταῦτα δὲ μηδὲ χρῶμα ἔχειν οἰκεῖον 46,8 18 δέχεται τὸ] ἔχεται τ in lit. V 19 παρουσία a: παρουσίᾳ V ἡ a: ἡ V 20 παρουσία ι v. c. (?) adscripsit 22 πάντα] ν in lit. V 24 τῷ V: τὸ a 31 ὅτι V: ἄρα a 32 sc. τῶν χρωμάτων 36 χρώνυσθαι a 37 εὗρεν V ex. Vict.: εὗρον a
marginal 153r
footnote 3 ἀθρόον a 10 ἀλλ ᾗ—δυνάμενον] oculum imaginari dici nequit (cf. 68,5 sq.); quare fortasse ἐμψύχου et δυναμένου: quia (oculus) pars est hominis animati et phantasia praediti. . eadem de causa δύναται (v. 11) aut impersonaliter (cf. Ind.) aut de homine dictum est, aon de oculo 14 λεῖα V ex. Vict.: λία a οὐδὲν scripsi: οὐδὲ Va αὐτοῖς Va 17 τῶν om. a 19 fortasse πρὸς τὰ ὁρώμενα 20 ante ὑπὸ una lit. erasa V 22 ἐπεὶ delendum videtur 24 τῶν om. a 27 ταῖς] α in lit. V 28 ἀλουργόν Va 30 χρωμάτων] χρω in lit. V 31 ἀμυδρότερα] μυ in lit. V λαμπρότερα] μ in lit. V
footnote 3 fortasse ἢ ⟨μὴ⟩ ὁρατὰ 5 ὁμόχρω- sic in medio versu V: ὁμόχρω a 6 fortasse ὑπὸ τοῦ χρώματος κινουμένη (scil. ἡ ὄψις) διὰ τοῦ μεταξὺ] intellegas de aere intermedio, hoc enim dicit: visus animadvertit superficiem unicolorem talem, qualis est, quia aequabiliter per colorem movetur (ὁμοίως ὑπὸ τοῦ χρώματος κινουμένη), quippe qui et (in quavis supericici particula) idem sit (ὑπὸ τοῦ χρώματος τοῦ οὐ τοῦ) et aequabiliter moreatur per spatium intermedium (καὶ ὁμοίως κινουμένου διὰ τοῦ μεταξύ) 12 ἀχλυωδέστερα scripsi: ἀλλοιωδέστερα Va 13 ὃ μιμούμενοι κτλ.] cf. p. 50,26 14 βούλονται a fortasse ⟨τι⟩ ἄνισον 16 αὐτῶν om. a 17 τε καὶ a 18 γωνείᾳ a 26 δέχεται a 35 τι in lit. V
marginal 153 v
footnote 1 ἐπεὶ Va: ἐπὶ ex. Vict. ἡρέμα ut solet V 2 περὶ ταῦτα a ἀχλυωδέστερα V: ἀχαιωδέστερα a 7 ᾖ] expectamus ὡρισμένον ἠρεμοῦν vel ὡρισμένον καὶ μένον, ut v. 10. hoc enim dicit: si quid aut a certa stabilique re aut ab ipso visu (sie manet sim manere videtur) idem intervallum videtur nom tenere, id moveri putamus φαίνεται a 8 μὴ τὴν ἀπόστασιν τὴν αὐτὴν a 9 αὐτὸν a 11 αὐτῷ a 13 αὕτη] fortasse ταῦτα nisi ἀντιπαραλλάττειν (Usenerus) latet παραλάτειν V 16 λέγει] scil. ἡ ὄψις 17 ἀπορία] cf. 62,9, de sens. 63,11 20 τέμνουσιν] fortasse τέμνει, nisi pauca eciderunt: τέμνουσιν ἀλλήλους ⟨οἱ κῶνοι οἱ ἀπὸ⟩ τῶν τὰ διαγώνια ὁρώντων cf. Al. de sens. 643 21 τὰ in lit. V 23 αὐτὸν] ante ν una lit. erasa V 26 ὅτι τὸ χρῶμα πέρας τοῦ διαφανοῦς] cf. Al. de sens. 91, 8 sq. 32 δεκτικὸν αὐτῶν] ὸν αὐ in lit. v τοῖς ἐν Ka
footnote 1 χρώματί Ka 7 δίοπτρα Ka ὄψει V: ὄψι a ἐπεὶ ὄψει ληπτὸν αὐτῶν ἐστ τὸ χρῶμα] haec non pertinere ad praecedentia (τὰ δίοπτα), et res ipsa et verba docent quae sequuntur δι οὗ δὲ τοῦτο φαίνεσθαι πέφυκεν et q. s. agitur enim de differentia quae interest inter φαίνεσθαι et διαφαίνεσθαι, de quas cf. Al. de sens. 95, 1 ἰδίως δὲ διαφανῆ, ὡς εἴθισται λέγεσθαι, τῶν σωμάτων μόνα τὰ δίοπτα,· ἀπὸ τοῦ φαινόμενον μὲν ἰδίως λέγεσθαι τὸ τῇ ὄψει ἀντιληπτὸν παρὰ τὸ φῶς. ὧν δὴ τοῦτο χρῶμα, ταῦτα ἰδίως διαφανῆ. τὰ γὰρ δεχόμενα τὸ φάος ἤτοι φῶς, δι᾿ οὗ πάντα τὰ ὁρώμενα ὁρᾶται, ταῦτα λέγεται συνήθως διαφανῆ. quare fortasse legendum est τὰ δίοπτα· ⟨φαινόμενα γὰρ καὶ τὰ ἄλλα σώματα παρὰ τὰ δίοπτα⟩, ἐπεὶ ὄψει ληπτὸν κτλ. 12 γίνεται V: λέγεται Ka 14 διαφανεῖ] φ in lit. V 16 λήψομεν v. c., λείψομεν m1 V: λείψομεν Ka 20 οὖν om. Ka τε καὶ V: τὰς Ka 21 ὑπέκκαυμα] cf. 149,14 τὸ δυνάμει πῦρ, τοῦτο δέ ἐστι τὸ ὑπέκκαυμα et Arist. met. 1,4. 37 1b 17 sq. 22 καὶ om. Ka πορρωτάτω corr. ex. ποαρωτάτω V κεκεῖνα (sic) V
marginal 154r
footnote 7 ῥοπὴν] ante π una lit. eras. V 10 ἐναντία—πυρί suspectum 10—14 καὶ γὰρ δὴ—ἀφέστηκεν αὐτοῦ] cf. Al. de sens. 96,12—97,3 15 ὑπέκκαυμα VK: ὑπέκκαυμένᾳ a 18 ἀφεστώς Ka 20—29 εἰκότως—μαλακτὰ εἶναι] cf. Al. de sens. 97,3—12 22 αὐτῇ Ka 23 ἀὴρ ἀνάπλεως Ka 24 γεώδους Ka: γαίώδους V, ut semper 26—27 οἷς—διαφανῆ om. K 29 δῆλον scripsi: δηλοῖ VKa cf. Al. de sens. 97, 10 κέρας δὲ καὶ τὸ χελώνιον διαφανῆ ἐργασθέντα πως γίνεται, ὅτι τὸ πλεῖστον ὕδατος ἐν αὐτοῖς· δῆλον δὲ τῷ μαλακτὰ εἶναι 31 διὰ in lit. V 32 δίοπτρα Ka
footnote 1 διαφανῆ] α ante ν in lit. V 6 πέπονθεν] cf. καὶ μᾶλλόν γε τὸ εἶδος τοῦτο τῆς ὕλης πέπονθεν 4,21 9 μᾶλλον] μᾶλ in lit. V ἔχεί sic V 12—13 ὧν κατὰ—σώμασιν] insiticium videtur 13 δὴ τοῦτο Ka 19 οἰκείους Ka 20 ἐπεὶ δέ ἐστι a ἔστι δὲ om. a 21 πρώτως a 24 γίνεται] αι in lit. V εἰ om. a 27 ἐσχάτοῦ V 29 αὐτῷ a 30 γινόμενον a αὑτὸ scripsi: αὐτὸ V: αὐτὸν a 31 διαρθροῦντες a 32 ὠκειῶσθαι Va 33 ὑμῶν a 34 φασιν in lit. V
marginal 151v
footnote 2 ὀρεκτικοῖς a 4 αὑτοὺς V 5 αὑτῶν V ὠκειώμεθα Va 9 ἐν τῷ ὀγδόῳ τῶν Νικομαχείων] ὀγδόῳ (i. e. ἐν τῷ Θ) scripsi: ἐνάτῳ Va cf. Arist. Eth. Nic. 8,2 1155 b 17—27 11 γὰρ τὸ Aristoteles: γάρ τοι V: γάρ τι a ἐν τῷ ἐνάτῳ] ἐνάτῳ (i. e. ἐν τῷ I) scripsi: δεκάτῳ Va cf. Eth. Nic. 9,8 1168 a 35—b 10 12 διαφανῆ a 15 αὐτοῦ a 16 πλῶς ἡμᾶς αὐτοὺς ὀρεγόμεθα a αὐτοὺς ἡμᾶς] cf 152,26 ἐκείνων a 17 αὑτῶν V καὶ μοχθηρῶς ἄρα καὶ λυπηρῶς] videtur supplendum esse ἔχοντες οὐκ ἄλλοι ἡμεῖς ἡμῶν αὐτῶν 18 fortasse εἰσὶν δέ, οἳ cf. 5,10 et 168,24 19 εἶναι om. a 20 ἐν Ἠθικοῖς Νικομαχείοις] Ar. Eth. Nic. 2,2 1104 b 30 27 τοῦτο] το in lit. V 30 βεργίνιος a Σωσικράτης] σωκράτης a 31 ἐνέργεια a 33 τοῦ a: τὸ V fortasse ζῆν ⟨ἐνεργεῖ⟩ ἐνεργείας 34 ἡδίαι V
footnote 4 τελειότητος] ς in lit. V 8 οἰκειῶσθαι V: οἰκειοῦσθαι a cf. Ind. 10 πότερον] π in lit. V 11 (et 151,33) ἡδίας V 13 καὶ τε a τῇ] fortasse τὴν 14 τῆς κατ᾿ αὐτὰς] scil. τῆς κατὰ τὰς αἰσθήσεις ἐνεργείας ὀρεγόμεθα cf. 153,4 ἐν δε τῷ δεκάτῳ τῶν Νικομαχείων] Ar. Eth. Nic. 10,6 1176 b 26 17 ὥς φησιν Ἀριστοτέλης] cf. de animal. gen. 2,6 742 a 22, phys. ausc 2,2 194 a 35 19 ἔσχατον] ον in lit. V ᾧ fortasse ᾧ ⟨ὡς⟩ 23 τὴν om. a 25 τε add. v. c. V αὑτοῖς V οὐχ] χ in lit. V 26 τοῦ] fortasse τὸ αὑτοις V 28 ἀληθῶς] ω in lit. V 32 ἀλλ᾿ αὐτοί γε a: ἀλλὰ τοίγε V 33 οἱ μὲν V: ἡμῖν a 36 καὶ ζῆν V: ζῆν a
marginal 155r
footnote 1 post ἐν συνεχείᾳ, nisi corruptum est, aliquid excidisse videtur. exspectas enim τὴν καθὸ τὸ εἶναί ἐστιν αὐτῷ κατὰ φύσιν ἐνέργειαν (sive ἕξιν sive τελειότητα) cf. 151,31, 153,6,7. 5 ἂν om. a προσοικειωμένον] σ m1 suppl. in mg. ante σ una lit. erasa ὀρεγόμενα] ὀ in lit. V: ὀρεγόμεθα a 8 fortasse αὑτοῖς ἰδίας m2, ἡδίας m1 V: ἰδίας a cf 152,26 11 ἡδεία corr. ex. ἡδία V 12 αὐτὸ ἐνεργεῖν] exspectas αὐτὸς ἐνεργεῖν et αὐτὸς ἥδεσθαι, sed. cf. lnd. s. v. neutrum 13 τοῦ αὐτὸ ἥδεσθαι ὀρέγοιτο ἂν] haec nisi transposueris post πρὸς ἣν οἰκειοῦται πρώτην aon intellego 14 γὰρ] ρ in lit. V 20 ἀριστοτέλην a 21 ὃν a δεκάτῳ scripsi: κ V: ι a ἐν τῷ δεκάτῳ τῶν Νικομαχείων Ἠθικῶν] Ar. Eth. Nic. 10,3 1175a10 22 δὲ om. a 24 ἐστι] εἶναι Va ἕκαστον Va 26 ὅπερ ἐστὶν αἱρετόν Va: αἱρετὸν ὄν Arist. 28 Ὅτι ἀντακολουθοῦσιν αἱ ἀρεταί] cf. Alexandri quaest. nat. et mor. 4,22 29 ἀκολουθεῖν a 31 ἔχειν v. c. ἔχει m1 V: ἔχειν a
footnote 2 μὲν om. a αὐτόν a: αὑτόν V 3 πράξαντι] π in lit. V φιλοχρήμματος V πρὸ V ex. Vict.: πρὸς a 7 τὴν ἡδονὴν ἕλοιτ᾿ ἄν m2 in mg. add. V 8 ἀλλὰ in lit. V ante προδότας desideratur sive θρασεῖς sive λεγομένους ἀνδρείους 11 αὐτῷ a νεμεῖ scripsi: νέμει Va cf. 63,25 ἐνθήσει a 12 ἀπειλούμενος scripsi: ἀπειλούμενον Va 13 χαίρειν ταῖς αὐταῖς ἡδοναῖς a 14 fortasse τῇ κατ᾿ ἐκεῖνο (cf. lnd. s. v. neutrum) λυμαίνεσθαι ⟨τὴν⟩ τῆς 20 γεωμέτρης a: γεσωμέτρης V καλεῖται] ει in lit. V 23 τινὰ om. a ταὐτὸ a 24 γὰρ καὶ ὁ a 25 γὰρ ἂν εἴη a: γὰρ ἂν εἰν Va 29 εἴη ἂν καὶ—πρὸς κακοδαιμονίαν om. a 32 πρακτοῖς V: πρακτικοῖς a
marginal 155v
footnote 1 γνωρίζει] εἰ in lit. V 3 πράττει καὶ m2, πράττει m1 V: πράττει καὶ a 6 διαφέρουσιν delevi 7 εἷς a: εἷ sic V 12 ἔχει a 14 καὶ ἡ V: καὶ a 26—27 οὕτως δὲ—πλὴν ὁμωνύμως om. a 27 post ἀρεταί εἰσιν nonnulla excidisse videntur. fortasse εἰσιν, ⟨οὐκέτι δὲ χωρισθεῖσαι⟩ 31 τῷ καλῷ a 32 (et 37) λογιστικοῦ V: λογικοῦ a 33 δὲ supra lin. V 38 τἀγαθὰ a
footnote 1 ἀκρατῆ V ex. Vict.: ἀκροατῆ a 2 φρωνήσεως a 3 ἕποιτ᾿  ἂν a 8 τὸ μὲν ex. Vict.: τὸν μὲν Va 9 ἂν εἴη m2, εἴη m1 V: ἂν εἴη a 12 fortasse τοῦτον scil. τὸν μὴ προσήκοντα σκοπόν 13 δύναμιν om. a 14 ἐν πᾶσιν om. a 15 κριτικὸς] τι in lit. V 16 πρακτοῖς ex. Vict.: πρακτικοῖς Va σκοπὸν ἔχειν α 17 ἔχει a: ἔχοι V fortasse πᾶσαν ⟨ἂν⟩ ἀρετὴν ἔχοι 20 φρονίμου scripsi: φρόνιμον Va 24 τάδε δὲ m2, τάδε m1 V: τὰ δὲ a 29 μὲν εἶναι τὸν ἄνθρωπον m2, εἶναι m1 V: μὲν εἶναι τὸν ἄνθρωπον a 30 δικαιωσύνης a 31 ἐνεργείας a
footnote 2 ὁρμά τι a 3 φαμεν V: μὲν a 10 ζῴων m2, ζωιον m1 V: ζώων a 14 τι τῶν m2, τῶν m1 V: τι τῶν a νοημάτων ἢ scripsi: ἢ Va 16 τι τὶ m1 V μόνον: μόνῳ a: fortasse μὲν 18 λέγειν] λ in lit. V: λέγειν θέσει a 19 μαρτυρεῖτ᾿ a γὰρ supra lin. V 23 αὐτοῖς] αἰ τοῖς a 25 argumentatio postulare videtur ὑπαρχόντων ἡμῖν ⟨φύσει⟩ cf. v. 29 τῷ καὶ τὰς ἐνεργείας ὑπάρχειν ἡμῖν φύσει 30 κοινωνικοὶ] post ων una lit. erasa V 35 γράμμασιν om. a 36 fortasse πολλά ⟨ἃ⟩·
footnote 4 ὁμολογουμένων καὶ κεκυρωμένων] cf. οὕτως καὶ ὑποκειμένων μέν, μὴ προηγησαμένης μεν τῆς φαντασίας ὁρμὴν ἀδύνατον γενέσθαι 161,11 εἰ ἴσον τόπον κατέχει ἥ τε ψυχὴ καὶ τὸ σῶμα σὺν αὐτῇ, καὶ χωρισθείσης τὸ σῶμα μηδὲν ἐλάττονα 141,4 δεδειγμένου δέ 14431 7 ἡγούμενον a 15 γὰρ δὴ v. c. γὰρ m1 V: γὰρ δὴ a ἡ supra lin. V 19 λῃσταί, ληστεύειν a δικαισύνης a 24 τὸ m2, τοῦ m1 V: τὸ a
marginal 156v
footnote 1 ὑπεναντιωτάτοις a 11 πραττόμενα a ἀνδρεῖα scripsi: ἀνδρεία Va 12 ἀπὸ τῆς a 15 editum est Basileae apud Joan. Vualder „Aristotelis et Xenophontis ethica politica et oeconomica (anno incerto) cf. p. 5 592 sq., deinde ex hac Vualderi editione a Sylburgio post Aristotelis Ethica Francofurti 1584 p. 248 sq. cf. 301. utrumque scias cum Aldinae lectione consentire, si hanc solam adnotavi 18 fortasse βίος αἱρετός, ⟨ὁ δὲ βίος αἱρετὸς⟩ οὐκ ἀβούλητος 21 ἐξαγωγὴν] v in lit. V fortasse κατὰ ἀρετὴν ⟨ζῶν⟩ οὐκ 26 τὸ ἄρα V: ἄρα a, cf. 23,2 et 159,31 28 ἐν om. a μόνη a 32 ἐνεργείᾳ a 33 ποιεῖ V: ποιῆ a καὶ post τι om. a
footnote 6 πάντα Usenerus: ταῦτα Va 7 χαλκευτικὴ a 8—9 χρῆται δὲ — ἐστι ποιητική om. a Vualder Sylburg 10 αὐτὴ Usenerus: αυτη V: αὕτη a 12 τὸν ὧν οὐκ ἄνευ λόγον] de hoc cf. 161,26 αἱ αἰσθήσεις . . εἰ μὲν πρὸς τὸ εἶναι τὸν ἄνθρωπον ἀναγκαίου χώραν ἔχουσιν, μηκέτι δὲ συνεργοῦσιν πρὸς τὰς ἐνεργείας τῆς ἀρετῆς, τὸν ὧν οὐκ ἄνευ λόγον ἔχοιεν ἄν. εἰ δὲ πρὸς τῷ ἀναγκαῖαι εἶναι καὶ συνεργοῦσιν . . . , οὐκ ἔχουσιν τὸν ὧν οὐκ ἄνευ λόγον 15 μὴ V: μὲν a 17 fortasse ἦσαν ⟨ἂν⟩ 18 οὐκ ἄῤ Usenerus: οὐ γὰρ Va 19 οὐ scripsi: οὖν (sic) V: οὖν a 21 ἐκλογὴν] κ in lit. V ὑγιαίνοντος om. Vualder 22 ἄνευ] ευ in lit. V 23 ποιήσαντο a 24 περὶ] ἐπὶ Vualder ut solet. Sylburg correxit in adnot. 30 παρουσίᾳ a τούτων] ν in lit. V 31 οὐκ om. a 33 ὑγιαίνοι τε] ι τ in lit. V αὐλοὺς] α in lit. V 34 αὐτῶν ἐνοχλεῖ a ἐναβουλήτοις a
marginal 157r
footnote 11 οἷόν τε a οὐκ ἦν] cf. 160,4 sq. αὐτὴ a: αυτη V ὑποκειμένων] cf. 1584 12 fortasse φαντασίᾳ δὲ ⟨δεῖ⟩ 13 αυτὸν V: αὐτῶν a: fortasse αὐτὴν 21 εἰ om. a 24 αὐτα V: αὐτοὺς a 26 αὐταὶ a: αὐται V 28 ἀναγκαίῳ a 30 κρητὶς a: κριτὴς Vualder Sylburg 35 fortasse ἢ [εἰ] ἐφέξομεν
footnote 2 τῷ scripsi: τὸ Va cf. 60,25 ὅμοιον γὰρ το λέγειν κεχωρισμένα εἶναι τὰ αἰσθανόμενα τῷ λέγειν 3 εὐδαιμοία a 6 οὖν del. Madvig Cic. de in. 4,11,26, sed cf. lnd. 7 τὸ τὸ V: τὸ a καὶ τὸ ἀγαθὸν del. Madvig ib. 9 σώματος] ς in lit. V 17 τὸ in lit. V 18 αὐτὸν a 21 συντελεῖ a 23 δύναται Vualder Sylburg αὐτὸν Va καὶ om. a 24 αὐτὰ Sylburg 26 εἰ ἡ om. a Vualder: ἡ om. Sylburg 27 ἕκαστον scripsi: ἑκάστου Va 32 ἀνενδεὲς V: ἀνενδεὴς a cf. lnd. s. v. neutrum
marginal 157v
footnote 2 ὑγειας Va 4 πρς (sic) V προηγμένα V: προηγούμενα a 5 ἐπισπαστικά V: ἐπιστατικά a 8 γὰρ ἂν v. c. ἂν m1 V: γὰρ ἂν a 13 τοῦτο a 15 δεῖ V: δὴ a ὠκείωσεν V: ἐκείνωσεν a: οἰκείωσεν Vualder Sylburg 18 ἡμῖν in lit V 20 δεομένου a 27 συντείνοι V Sylburg: συντείνει a 34 παραλαμβάνειν a 35 ἀποικονομίας V Sylburg: ἀπ᾿ οἰκονομίας a cf. 160,25 36 οὐχὶ] χ in lit. V
footnote 3 ἢ in lit. V 4 μόνου corr. ex. μόνον V 5 ἐν] ν in lit. V 10 ἀρετὴ καὶ Va 11 ποιὰ a 16 ἐν V Sylburg: ἐν om. a 19 ἐκτὸς] ο in lit. V 25 ἣ a 26 συντελεῖ a 28 ὃ Valder: ὁ Va 29 ὑγείας Va 32 εὐδαινία a αὐτοί] αὐτὰ Sylburg 35 ὑγιείας V: ὑγείας a 36—37 καὶ σκοπὸς τῷ—ὁ τέλος ἐστὶ om. a Vualder Sylburg 37 ταῦ| τὰ V
marginal 158r
footnote 4 βούλεται] α in lit. V 6 ἂν κατὰ ἂν κατὰ a 12 αὐτάρκῆς V 12—13 ὥσπερ τῷ αὐλητῇ—αὐλεῖν ἐστιν] τὸ αὐλεῖν post ἐστιν addit Sylburg, melius πρὸς delebis, quod suadent verba respondentia τῷ εὐδαιμονοῦντι ἐν τῷ εὖ ζῆν ἐστιν τὸ εὐδαιμονεῖν 19 αὑτῷ Sylburg: αὐτῷ Va 20 παρόντα a: παρον (παρο|) V 31 συντελεῖ a 38 ὑγεία Va
footnote 1 τέλος ἡ a: τέλος V 2 ἡ ἀρετὴ m1 in mg. V ὑγεία ὑγιείας V: ὑγεία ὑγείας a 5 αὐτοῦ a 9 αὑτῷ Sylburg: αὐτῷ Va ἐκλέγοιτο] ιτ in lit. V 11 παρῆλθεν] cf. p. 163,33 ἡ φύσις τῆ ἐκλογῆς ἕνεκεν τὴν ἀρετὴν παραλαμβάνει ἄρα] accent. et spir. ia lit. V 23 τῇ addidi ἀρετῇ scripsi: ἀρετὴ Va 24 οὐ V Sylburg: οὗ a 36 (et 38) τινὸς sic V
footnote 1 οὕτως] fortasse ἁπλῶς 2 αὐτάρκεις] ει in lit. V ἔξω a 3 ὑγειῶς a 4—5 τὸ δὲ φάναι, ὥσπερ . . δύνασθαι χρῆσθαι, οὕτως κτλ.] cf. ἀνεπαίσθητος γάρ, ὃν λέγουσιν προεμπίπτειν, ὁ ἀήρ, οὗ τῇ ποσότητι τὸ διάστημα ἀναμετρεῖσθαι p. 135,5 φῶς γάρ τι ἐκπέμπεσθαι ἀπὸ τῆς ὄψεως, ὃ τῇ ἀπορροίᾳ. . . ἀναγγέλλειν p. 137,2 6 πρὸς διασταλτέον V 13 ἔχοντα v. c. ἔχον m1 V: ἔχοντα a 16 λέγεται] αι in lit. V προῆχθαι] αι in lit. V 18 ἐρέσθαι scripsi: ἔρεσθαι a: αιρεσθαι (sic) V 20 καὶ post αὐτὸ om. a ἀποπροηγμένον V Sylburg: ἀπὸ προηγουμένον a 21 ἢ Vualder: ἡ Va 27 ἀπὸ προηγμένον V 28 φορὰ V Sylburg: φορᾶ a 29 προηγμένος] ante ς una lit. eras. V 32 προηγμένον V Vualder Sylburg: προγμένον a
footnote 1 fortasse περὶ ἐκείνου ⟨λόγος⟩ 4 καὶ τὸν V: καὶ τὸ a 7 ἡ Va 11 τὴν a: τ cetera evanuerunt V 13 εὐδαιμονίας] υδ in lit. V λέγειν om. a ἅλις V Sylburg: ἅλος a 14 τῶν a: τῶν τῶν V 18 δι᾿ ἃ ἦν Sylburg: διὰ ἦν V: δι᾿ ἣν a 20 εὐδαινία a 22 οὔ φησιν Ἀριστοτέλης] Ar. Met. 10,9 1858 a 31 24 αἳ ἔχουσαι] cf. 151,18 28 ἐπεὶ V: ἐπὶ a 36 ὑλικοῖς V: εἰὃικοῖς a
marginal 159v
footnote 8 τὸ delevi 10 ζούου a γένος a 18 fortasse ἡ ⟨κατὰ τὸ⟩ δίπουν 19 ἐ||||ν παντὶ V γὰρ post ἔστι om. a 25 δύναται a 27 πτηνὸν καὶ πεζὸν καὶ ἔνυδρον a
footnote 1 τε καὶ ἐφ᾿ ἡμῖν suspectum cf. 171,23 2 ὁποῖον — ἀξιοῦμεν insiticium videtur 3 ἅπασιν ἐδόκει m2, υπεσιν εδουει m1, πασιν ἐδοκει v. c. V: ἅπασιν ἐδόκει Ca: fortasse γίνοιτο, ⟨ὃ⟩ καὶ αὐτό τισιν ἐδόκει 4 γιγνομένων V: γινομένων Ca 6 γίγνεται corr. ex. γίνεται V: γίνεται Ca δὴ V: δὲ Ca 9 τύχῃ v. c. et m2, εὐχῇ m1 V: τύχῃ Ca 9 ἀριστοτέλει VC: ἀριστοτέλῃ a 10 ἐν τῷ πέμπτῳ τῶν Μετὰ τὰ φυσικά] i. e. ἐν τῷ Ε (cf. p. 151,9. 11) τῶν Μετὰ τὰ φυσικά. respicit enim, ut videtur, Ar. Met. Ε 2, 1026 a 33—1027b 16. 11 τοῦ Va: τῶν C τὸ μὴ m2, μὴ m1 V: τὸ μὴ Ca 13 συμβεβηκος ὂν v. c. συμβεβηκοσιν m1 V: συμβεβηκός τι ὄν C: συμβεβηκὸς ὂν a τὸ γὰρ μὴ ὄν v. c. τὸ γὰρ δι᾿ ὂν ὄν m1 V: τὸ γὰρ μὴ ὂν ὂν C: τὸ γὰρ μὴ ὂν ὅν a ?? συμβέβη| κε (βη in mg. m1, τινι sive γινι, quod in extremo argine a v. c. adscriptum est, ad vocem obscuram ?? referendum esse videtur) V: συμβέβηκεν C: καὶ συμβέβηκεν a. locus corruptus ita fere restituendus videtur: εἰ γάρ ἐστίν πως τὸ μὴ ὂν ἐν τοῖς οὖσιν (⟨ἔστι δέ, ἐπεὶ ἐν τοῖς οὖσίν⟩ ἐστὶ τὸ κατὰ συμβεβηκὸς ὄν· τὸ γὰρ μὴ ὄν, εἴ τινι συμβέβηκεν εἶναι, λεγόμενον [sc. ἐστὶ cf. p. 5,10] κατὰ συμβεβηκός τι ὄν). εἴη ἄν τις καὶ κίνησις ἀναίτιος. omnis quantum ego video huius capitis disputatio mirabili quadam nititur verborum Aristoteliorum interpretatione (et. Ε2, 1026b 13) ὥσπερ γὰρ ὀνόματι μόνον τὸ συμβεβηκός ἐστιν. διὸ Πλάτων τρόπον τινὰ οὐ κακῶς τὴν σοφιστικὴν περὶ τὸ μὴ ὂν ἔταξεν et (v. 21, ib) φαίνεται γὰρ τὸ συμβεβηκὸς ἐγγύς τι τοῦ μὴ ὄντος. haec enim a logica ad physicam rationem trsansferens sumit scriptor idem esse secundum Aristotelem τὸ μὴ ὄν atque τὸ κατὰ συμβεβηκός, et, cum τὸ συμβεβηκὸς in rebus esse appareat, esse etiam τὸ μὴ ὄν. hoc autem (in parenthesi v. 13, quam ego constitui) demonstrato pergit (v. 15), eiam act esse τὸ μὴ ὄν: ὅτι δέ ἐστί πως τὸ μὴ ὂν ἐν τοῖς οὖσιν ἐνεργείᾳ κτλ. 15 οὗ ὄντος v. c. et m2, οὗ παντος m V: οὗ ὄντος Ca πως m2, πω m1 V: πως Ca 16 ὂν] ὅν a 17 ἐστιν ἀίδια· sic m1 V ἄλλα δὲ φθειρόμενα m2, αλλα αειρομεν m1 ἄλλα φθειρόμενα v. c. V: ἄλλα δὲ φθειρόμενα Ca 18 αἰτίαν Ca: αιτιαν v. c. σιτια m1 V 19 τε VC: τι a 20 ἀτονία m2, ἀτοπία m1 V: ἀτονία Ca
footnote 2 ἐγίγνετο] fortasse ἐφίετο 3—4 δέ τινα—ψευδῆ ἔστιν om. C 7 γενέσει V: γενέσι Ca 8 προηγεῖται οὐδ’ αὐτὰ om. C αὐτὰ corr. ex. αὖ τὰ V 9 τι τοῦ m2, του m1 V: τι τοῦ Ca 10 ὂν ἐν—κατὰ συμβεβηκὸς om. C 11 αἰτία a ἐπακολουθήσει Ca μὴ τοῦ m2, μὴ m1 V: μὴ τοῦ Ca 12 ἐπηκολουθηκότος VC: ἐπηκολουθηκότως a 13 fortasse οὐκ αἴτιον. ⟨τὸ⟩ ἄρα ἐπακολουθῆσαν τούτῳ κτλ. 14 τούτω a 15 αὐτόματος a 17 εἶναι om. Ca 19 προκαταβέβληται] προκ in lit. V 20 ἐκινούμεθα] κι in lit. V 21 fortasse τοῦτο 22 κατ’ αὐτὰ C 28 πολλῷ C 29 ὀλίγον m2, οὐκ ὀλίγον m1 V: ὀλίγον Ca τε] cf. Ind. 33 εἴη ἂν Ca
marginal 159v
footnote 4—5 οὐδὲ τὸ ἐν τοῖς ἐπὶ πολὺ] fortasse οὔτε ἐν οἷς τὸ ἐπὶ πολὺ 9 αἱ εἀναίτιοι (sic) spatio duarum litterarum post αἱ relicto (ad hanc lacunam φ referenda est, quam litteram in mg. posuit v. c.) V: ἀναίτιος C: αι ἀναίτιοι (post αι fenestra) a δει sic V: δε? C: δεῖ a 11 τοῦτο ante οὖ] οὕτω (in mg. τοῦτο) C. apertum est scriptorem inter ea distinguere, quae iussu naturae coacti agimus eaque, quae propter τοῦ μὴ ὄντος praesentiam libera voluntate ipsi comittimus. temptavi igitur γιγνόμεναι, ⟨αἰ δὲ γίγνονται⟩ ἀναιτίως (cf. v.171,13 sq.) καὶ κατὰ τὸ μὴ ὄν, αὗται δὲ τὸ κτλ. τοῦτον C 13 τῶν post αἰτίων om. C 14 ἔχειν C 18 γεννητῷ Ca 27 οἷόν τε Ca 29 καὶ ὁπότερον m1 in mg. V 30 ἔρχεται (a supra ἔ m1) V: ἄρχεται Ca: fortasse βουλῆς, ἔρχεται ⟨ἐπὶ τοῦτο⟩
footnote 1—2 γὰρ τὸ usque ad ἐφ’ αὑτῷ ἔστι om. Ca τὸ αὐτὸ τῷ scripsi: τὸ αὐτὸ m1, τῷ αὐτὸ m2, V 5 γενέσθαι καὶ m2, καὶ m1 V: καὶ Ca 14 τοῦ τε ἀνθρώπου] cf. v.16 et p. 174,9: ἡ βουλὴ καὶ ἡ προαίρεσις καὶ ἡ κρίσις καὶ ὁ ἄνθρωπος τῆς τοιαύτης πράξεως αἴτιος αἴτιον] scil. τῶν πραττομένων 20 αὐτῷ] fortasse αὐτὸ 21 post ἐν αὐτῷ apodosis excidisse videtur ἔχει C 27 ἀνερεῖν Ca 28 τὴν βουλήν, ἥν τε—αἰτίαν i. e. τὴν βουλὴν τήν τε αἰτίαν, ἣν ὡς οὔσης τινὸς (scil. τῆς βουλῆς) τὴν φαντασίαν ἔχομεν hoc est tollere) consiliam consiliique causam in phantasia positam 31 τὸ V: τοῦ Ca 32 τὸ om. C τισιν Va: αὐτοῖς C 33 τοῦ πρᾶξαι scripsi: τὸ ?? πρᾶξαι sic (ὸ ?? in lit.) V: τὸ πρᾶξαι Ca
marginal 160r
footnote 1 εἶναι VC: εἷ a κρίνειν Va: κινεῖν C 2 ἐκ τῆς βουλῆς Va: ἐν ταῖς βουλαῖς 3 τῶν Va: τῶν κακῶν C 4 ἢ δὴ scripsi: ἤδη VCa 7 ἡμῶν VC: ἡμῖν a 12 ἀλόγως VC: ὀλίγως a 15 γε om. C 21 ποτὲ δὲ om. 27 τῆς supra lin. V 28 οὐδ’ εἰ Va: οὐδείς C τὰ αὐτὰ VC: τὰ κατὰ a: τὰ κακὰ ex. Vict. 39 ὄντα Va: ἀεὶ ὄντα C ὅμοιος] ante ος lit. unius lit. V αὑτῶ scripsi: αὐτῷ VCa
footnote 7 ὅλως γὰρ τούτοις scripsi: ὅλως (m1) τούτοις γὰρ V: ὅλοις γὰρ τούτοις Ca 9 ὥς τι Ca 12 ἐσθίει Ca 14 ἀ| νεννόητος (ν post α in mg. m1) V: ἀνοητος C: ἀνενόητος a τὰ δίκαια Ca 15 τὰ ἄδικα Ca 16 πραιρετοικοί α 18 αὑτοὺς scripsi: αὐτοὺς Ca 22—23 ἥ γε ὁδὸς—γνώριμος] „si quidem via ad ipsa in nostro arbitrio est et nota“ Caninius. ante οὐκ ἀγνοεῖται plura exciderunt. sensum fortasse haec assequuntur: πεπηρωμένοις ⟨ἀγνοεῖται μήτε τὰ αἰσχρὰ (ἀμφότερα γὰρ⟩ οὐκ ἀγνοεῖται, εἴ γε ὁδός ἐπ’ αὐτὰ ἐφ’ ἡμῖν τε καὶ γνώριμος) 22 ὀδὸς ἐστὶν ἡ C 23 ποιοῖ a 24 ἢ τάδε addidi 25 εὐφυίαι] αι in lit. V τε πρός τινα καὶ (α supra lin. καὶ supra lin. et in lit.) V: τε καὶ πρός τινας C: τε πρός τινας a ἀφυΐαι] εὐφυίαι a 26 τηρῶσιν] fortasse μὴ πηρῶσιν cf. τοῖς κατὰ φύσιν ἔχουσιν ἔτι καὶ μηδέπω διὰ κακίαν πεπηρωμένοις 28 ἀστροφόροις Ca 29 αὑτοῦ scripsi: αὐτοῦ VCa
marginal 160v
footnote 1 edidit Ioan. Conr. Orelli in libro „Alexandri Aphr. Ammonii etc. de fato quae supersunt“ Turici 1824 p. 124 2 καὶ Va: δὲ καὶ HC ἱκανὴ περὶ αὐτῶν κτλ.] cf. 179,25 et Alex. de fato 163r30 τὸ μὲν οὖν εἶναί τι τὴν εἱμαρμένην . .  ἱκανῶς ἡ τῶν ἀνθρώπων συνίστησι πρόληψις κτλ. 4 τῆς om. C τῶν δεδογμένων HCa: τῶνδε δειγμενον V 6 αὐτῶν om. C Orelli 7 τίς ποιῆ a 8 αἰτίοις Ca: αὐτοῖς αἰτίοις VH καὶ ταῦτα VHa: καὶ καταυτα C 10 τεττάρων] τε in lit. V 12 κἀκείνων VC: καὶ τούτων H: κᾀείνων a 13 αὐτόματον] ante ν una litera erasa V καὶ τὸ αὐτόματον om. Orelli 15 αὕτη scripsi: αὐτὴ VHCa 16 αἰτιατῶν a ἐξ αὐτῆς VH: ἐξ αὐτῶν C: ἐξ αὐτοῖς a 17 fortasse ἐνυπάρχοντα· οὐ γὰρ αὐτὸ τὸ γιγνόμενον 18 οὐκ ἔχει Orelli 19 αὐτῷ VHCa 20 δι’ αὐτό V: αὐτά HCa 22 τε om. Ca 24 ὁ σκοπὸς ὡρισμένος Ca 26 ποιητιτὰ a ποιεῖν C 27 φύσει a 28 δὲ VHCa: τε Orelli 30 ἄστατον VH: ἄτακτον Ca
footnote 2 ταὐτα] ταὐ supra lin. V 5 οὖν ἐπεὶ V: οὖν ἐπὶ C: οὖν ἐπὶ (in mg. ἐπεὶ) H: ἦν ἐπὶ a 7 αὐτω καὶ κυρίῳ C 8—10 κατὰ συμβεβηκὸς—λευκὸς κατὰ συμβεβηκὸς om. C 8 τοῦτο H: τούτου Va 9 αἴτι H: αἴτιος Orelli 10 ὑγείας a τούτῳ C 11 ἔτι γὰρ Orelli 12 αἴτιον om. orelli 15 τὴν om. C 18 ἅπαντα Orelli 19 ἀλλ᾿ ἃ κατὰ 21 φασὶ Orelli 24 ὡρισμένα H 26 πάντα τὰ HCa: πάντα V 28 τύχὴν V φασιν Orelli 30 τυχεῖν VHa: τυχεῖν αὐτῶν ἐφ’ C: πρᾶξαι Orelli 31 ἡ om. a 32 ἀπαντήσει C 35 προκεμένου (supra ει ϊ m1) V δέλεγομεν V λέγομεν τοῦτ Ca γεγονέναι VHa: εἶναι C τε om. C
marginal 161r
footnote 3 εἰ VHa: ἡ C 4 ἂν om. Ca 7 ἀόριστον scripsi: ἀορίστω V: ἀορίστῳ HC: ἀορίστῳ a: ἀορίστως Bloch. cf. τὸ μὲν οὖν καθ᾿  αὑτὸ αἴτιον ὡρισμένον, τὸ δὲ κατὰ συμβεβηκὸς ἀόριστον Ar. ausc. phys. 2,5 196b28 9 —10 καὶ τούτων—γιγνομένοις om. C 12 τὸ] fortasse τι 14 γένηται Orelli διαστρόφων] ante φ paululum erasum V „ἡ (τέχνη) τῶν διαστρόφων scil. ἀνθρώπων significare videtur artes eorum, quorum membra distorta sunt, V. c. funambulorum, saltatorum et aliorum id genus praestigiatorum“ Orelli. sed neque διάστροφος saltatorem significat neque quid sibi velint in hac argumentatione funambuli assequor. ad ὧν suppleas τεράτων aliud enim prodigiorum genus auctor tangere videtur, pumilos dico et distortos (διάστροφοι). notum enim erat illo tempore, non solum natura, sed etiam arte procreari haec monstra; testis est de subl. liber 445 cf. Jahn Arch. Beitr. p. 430 Casaub. ad Suet. Aug. 83. Marquardt VlI, 1, 152,4. sed τῇ post ἐπὶ delendum videtur 18 δυστυχίαν] χι in lit. supra lin. V 19 τὴν ἄλλως V: τηνάλλως Ha 21 τούτων Ca 23 εἰώθαμεν καὶ τῶν (in mg. suppl. ἐπὶ) H 24 γενομένῳ Orelli 25 τὸ οὗ Ca: τοῦ οὗ VH: οὖ Orelli 26 γεγονέναι καὶ τὸ ἐπακολουθήσαι ὥσπερ C γίγνεται Orelli: γίγνηται VHCa 29 ἔσται 30 γιγνομένῳ ἐπακολουθῆσαν
footnote 1 ὁ HC: οὐ Va 2 κατέζεσθαι a τήνδε τὴν θέσιν Va: τὴν θέσιν C: τήνδε τὴν φύσεως θέσιν H: τήνδε τῆς φύσεως θέσιν Orelli 3 καὶ ὁ μὲν VHCa: δὲ καὶ ὁ 0relli 4 ὕππον C 5 τούτῳ om. Ca 8 τῶν ἀνθρώπων om. Orelli ποιὰ a 10 ἐπεὶ πλείω VH: ἐπὶ πλείου C: ἐπὶ πλείω a 11 τινας om. Orelli 12 τῷ αὐτό τι ἅμα a ἔσται Orelli: εἶναι VHCa 16 συγχωροῦν ἂν τό τυχεν C 19 τὰς om. C 21 τεκτωνικῶν V 24 edidit Orelli ib. p. 134 sq. 25 τίσι Orelli 26 εἶναι τε Orelli 27 ἄστατον m1 V: ἄστοχον H: ἄστατον C: ἄστρατον a 29 γε H: τε VCa τὸ ὄνομα Ca 31 αὑτοῖς scripsi: αὐτοῖς VHCa
footnote 3 ποτὲ Orelli 5 εὐκυρεῖ a 6 ἔρωται C τε om. Orelli: fortasse τε ⟨καὶ μοῖραν⟩ τι om. C 7 πεπραγμένων τε ἢ Orelli 8 ἑαυτῶν ἐκείνοις C γε V: γε HC: καὶ a 9 αὐτοῖς VHa: αὐτῆς C: om. Orelli 12 αὖ τῶν VCa: αὐτῶν 17 αὑτοῖς scripsi: αὐτοῖς VCHa συνειδέναι V Ca: συνεῖναι H Orelli 20 οἷον Ca προμηνύσειν Orelli 22 αὐτοῖς VH: αὐτῆς Ca: αὐτῶν Orelli 25 φανῆναι καὶ κατὰ C τὰς τοιαύτας σύνθεσιν a 26 τοῖς οὕτως ἔχουσιν] cf. ἐν ταῖς περιστάσεσιν αὐτοῖς ἐπιθέμενοι καὶ ταῖς συμφοραῖς v. 23 28 ἔχειν om. Orelli κατατεχνίας a 30 οἳ καὶ VHC: οἷς καὶ a 34 ἐκείνη a
marginal 161v
footnote 1 αὑτοῖς scripsi: αὐτοῖς VHC? a: αὐτοὺς Orelli 2 λέγω C 3 τῆς εἱμαρμένης om. Orelli 4 τίνα VCKa: ποῖα 5 περὶ ἔργου a 6 τὰ ζητούμενα VH: ζητούμενα KCa 10 τ’ ἀΐδια Ka τὴν τοιαύτην KCa 13 ὡς αὕτως V 16 ἡμαρμένην a 18 καὶ κατὰ C 19 αἰτίας VHCKa: οὐσίας Orelli 21 δὲ καὶ ἐν τοῖς C 22 τῆς VKa: οἷ? C: τὸ τῆς 23 προκείμενα C 25 ἔχοι scrpsi: ἔχειν VHKCa: ἔχει Orelli 28 δὲ] μὲν Orelli 32 συνωδόν a: συνωδον V 34—35 οὕτω — εἱμαρμένην om. C 36 ἀλλ᾿  VKa: καὶ C?: καὶ (in mg. ἀλλ’) H
footnote 1 ταὐτά Va: ταῦτα HK: τὰ αὐτὰ 3 τέχνην τε om. C 4 τε om. Ka 5 δὴ VHKCa: δὲ 0relli 8 ἡμαρμένην a ἀλλ᾿  ἐν VHKa: καὶ ἐν C 12 μετὰ τούτου Orelli 13 τε εἶναι καὶ ἀπαράβατον 14 τὸν ποιητὴν] Hom. Il. 6488 16 ἐπ’ ἢν V 18 αὑτῇ Orelli: αὐτῇ VHKCa τάδε 0relli 20 αὐτῆς C: αὐτὴν VKHa 22 ἀνατιθέντες corr. ex. ἀναγκαίως K 26 καὶ ante παρὰ om. H Orelli 28 ἐνὸν HKCa: ἐμὸν V 29 εἰ VHKC: ἀ a: ἂν ex. Vict. 30 αὑτοῖς V: αὐτοῖς KHCa 31 εὑρησειλογίαι V: εὑρεσιλογίαι a 32 τοῖς γενέσει C 34 φύσιν a ὁραθεισα m1 V: ὁρισθεῖσα KHa: ὁραισθεῖσα 35 τὰ μέγιστα Orelli
marginal 162r
footnote 1 καὶ om. Orelli fortasse ἐνδεχομένου cf. 184,32 3 τὸν om. Orelli 8 ἀναγκαία a πειρωμένους (in mg. προῃρημένους) VH: πειρωμένους KCa 9 τοῦ τὸ Ka ταὐτά scripsi cf.182,1: ταῦτα VKHCa παῤ ἃ Orelli 10 τὰ τὴν Orelli ἐπαράβατον a 13 ταὐτὰ scripsi: ταῦτα VKHCa 14 γίγνεσθαι καθ’ εἱμαρμένην λέγοιεν λέγοιμεν Orelli 16 εἶναι om. ka C? καὶ τὰ ἐφ’ Orelli 17 καὶ ante τὰς om. Orelli 19—20 μόνον—τέλη om. C 20—22 ἀνάγκη—εἱμαρμένην τέλος om. C 23 ὅτι γὰρ om. C 25 γὰρ i. e. λέγω cf. Ind. τε] cf. Ind. τῶν add. Bloch apud Orelli τῆς om. KCa 26 ante ἐν δὲ τοῖς ἀνθρώποις Blochio nonnulla excidisse videbantur, at omnia sana sunt,  dummodo γὰρ v. 25 recte interpretemur 27 ὂν δὲ VH: οὐδὲ K Ca 28 δοκεῖ τούτῳ KCa γίγνεται Orelli γεγονότος κενῶς del. Bloch 30 τοῦδε VKCa: τούτου H 33 ἡμῶν Orelli: ἡμῖν VCHKa
footnote 1 συναίρασθαι V 3 fortasse συμβουλιῶν cf.185,21 4 τινῶν om. 5 συστῆσαι om. H fortasse διδασκαλίαι κελεύεται Orelli 8 τι om. 10 αἱ om. Ka 11 τινων supra τινα C 16 τήνδε a 17 ἔμελλε HCKa 18 ἐπιτηδειότητα ante δύναμιν del. K 19 μελανίας μελανίας a βουρέα a 20 ταῦτα Bloch: ταῦτά VHKCa οὕτε τι Orelli: οὔτε VKHCa οἷς δὲ scripsi: τοῖς δὲ VHKCa 21 ὑποκείμενον (in mg. ἀντικείμενον) ἀφωρισμένως HC: ἀφορισμένως VKa 22 ταῦτὰ H ἀντικείμονον a ἔχει scripsi: ἔχειν VKHCa 25 ἐνδέχεται VH: ἐνδέχεσθαι KCa: Blochius ante τοῦτ᾿  ἐνδέχεται nonnulla excidisse pultat, sed legendum videtur τουτέστι ἐνδέχεται cf. Al. de fato 165 r41 εἰ τὰ ἐξ ἀνάγκης ὄντα ἐν θατέρῳ οὐκ ἔχει δύναμιν τοῦ δέξασθαι τοῦ ἐν ἐστι τὸ ἐναντίον, οὐκ ἐξ ἀνάγκης ἂν εἴη ἐν οἷς ἐστι τὰ καὶ τοῦ ἐναντίου αὐτοῖς δεκτικά. εἰ δὲ μὴ ἐξ ἀνάγκης, ἐνδεχομένως 26 ἐξ om. Ka 26 —27 ἐν ᾧ—ἀνάγκης om. 27 ἀνάγκην V 30 καὶ ante ἀπὸ om. C 32 ἡ om. C 33 παραβασθῆναι V: παραβαθῆναι HCKa
marginal 162v
footnote 3 αὑτοῖς scripsi: αὐτοῖς VHCKa 5 αὐτὴν εἶναί φασιν C 6 τῷ VHC: τῶν Ka 8 γεννητοῖς CKa 9 συνιστᾶσαν Ka: συστᾶσαν VH: συνιστωσαν C 12 φύσιν εἶναι 13 fortasse ζῴῳ, ἀνθρώπῳ 14 Σωκράτει HKa Καλλία a 15 οὖσα V: οὔσης HKCa κατὰ ταῦτα H: ταυτὰ Va: κατ’ αὐτὰ K 19 ἱκανῶς Ka 20 πρόσταξις H: προστάξις a: προστάξεις K, fortasse recte cf. A1. de fato164r38 24 τὸ om. 0relli 26 ἀψιμάχων a 28 αὐτῶν (i. mg. αὐτοῦ) H: αὐτοῦ VKCa 29 καὶ post πόνων om. Ka 31 καὶ post ἣν om. Orelli αὐτῶν KHa 31—33 διὰ—θανάτου in mg. suppl. 32 αὐτῷ Ka 35 τε om. C
