@node
@author=Alexander of Aphrodisias
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Ivo Bruns
@filename=tlg0732.tlg013.1st1K-grc1
@funder=Harvard Library Arcadia Fund
@principal=Gregory Crane
@publicationStmt=Harvard College Library, tlg0732.tlg013.1st1K-grc1.xml.
@respStmt=Digital Divide Data, Corrected and encoded the text, Gregory Crane, Editor-in-Chief, Perseus Digital Library, Matt Munson, Project Manager (University of Leipzig), Annette Gessner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor
@sourceDesc=Alexandri Aphrodisiensis Praeter Commentaria Scripta Minora, Ivo Bruns, Alexander of Aphrodisias, Reimer, Berlin, 1892, 2, Supplementum Aristotelicum, 2.2, Internet Archive.
@sponsor=Harvard College Library
@title=Ἠθικὰ προβλήματα [Sp.]
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T15:10:51Z

20697	footnote 4 οὐκ add. Vict. (οὔτ’ ἀγαθὸν οὖτε κακόν B²) 8 ἐναντίον ἀπλοῦν τῷ δὲ πλούτῳ a: ἐναντίον τῷ δὲ πλούτῳ Vict. Sp. 9 δὲ om. a Sp. εἶναι om. tit. 10 ὡς] ἡ ὡς tit. 15 οὐ γένος tit. 17 ἃ om. a 20. 21 ἡ λέξις ἐκ τοῦ τῶν Ν. tit. ικομαχιῶν V (semper) 22 περὶ ἡδονῆς tit. 23 θήσεται aSp. 23 τι add. tit. 24 ἐστιν om. tit. 25 ἐστι— ἐπιστήμη om. tit. ποιητέον (bis) V
footnote 2. 3 πότερον- ὠφελίμων om. tit. 5 τῷ om. aSp. Ἀριστοτέλους aSp.: om. tit. 7 ἐν-μαθήματι] πανταχοῦ tit. 10 ἀκολουθοῦσιν a 11 ἡ ἡδ. aSp. 13 ἑαυτὰς aSp. 15 χάριν αἱρετόν, ἀλλ’ tit. τοῦ καλοῦ om. a Sp. 16 μεσότητές εἰσιν τοῦ καλοῦ a Sp. 17 πότερον ἢ (ἢ add. Vict. ὡς γένος ἢ ὡς ὅλον τῶν ἀρετῶν ἡ ἀρετή tit. Vict. Sp. 18 ἄλλης λέξεως ἐξήγησις ἐκ τοῦ τρίτου τῶν ικομαχείων Ἠθικῶν Ἀριστοτέλους, δί ἧς δείκνυται, ὅτι καὶ αἱ κακίαι ταῖς ἀρεταῖς ὁμοίως ἐφ’ ἡμῖν tit. Vict. Sp. 20 πῶς εἰ ἐκ τῶν ἐναντίων τὰ ἐναντία γίνεται, οὐκ ἔσται ἐκ μὲν δικαιοσύνης ἀδικία, ἐκ δὲ ἀδικίας δικαιοσύνη, καὶ ἐπὶ τῶν ἄλλων ἀρετῶν τε καὶ κακιῶν ὁ αὐτὸς λόγος tit. Vict. Sp. 22 οὐκ add. B2 Sp. (οὐκ ἀ. οὖτε κακόν B²) 24 τὸ δὲ] καὶ τὸ a Sp. 26 ἀδιαφόρους S2FaSp.: διαφόρους VS¹B1 : οὐ διαφόρους B² 29 δυναμένων] δυνάμεων a
footnote 1 τῇδε V 6 δυναμένων Vict.: δυνάμεων libri 8 ἔχειν] ν s. v. V 9 δύν|α|ναμιν V δ’ ἔτι a 13 ἐστιν alt. καὶ om. a Sp. 18 αὐτῷ V εὐζην V 19 γενομένοις Sp. 20 τῷ VBS: Vict.?: τὸ Fa: τοῦ Sp. 22 δεδομένον circumscripsi 25 ἡμᾶς circumscripsi τὸ om. Sp. 26 ἡμᾶς del. Sp. 26. 27 οἰκειώμεθα a Sp. 27 τε del. Sp. 28 ἐκεινω’’, ἀλλὰ sic V 29 διότι] ὅτε Schsartε 32. 33 τῷ οὖν οὗ a Sp. 37 ἡ a
footnote 1 δεῖ τὸ τῇ a 1. 2 fortasse ⟨τὸ⟩ αἱρετόν αρετὸν suspectum Sp. 3 ὁμοιοειδεῖς a 4 ὅτι—ἡδοναί repetit B Sp. 5 αὕτη a 7 ἢ] ἡ a 9 ταῦτα a ἐπιθυμίας Sp. 11 διαφορά a 13 οὕτω V²: οὐ τῶν V: οὕτων B¹: αὐτῶν GS¹F: ὡσαύτως SB²a Sp. 14 συνδιαιροῖντο V²: οὖν διαιροῖντο V¹B¹GS¹F: διαιροῖντο S²B²a Sp. 15 αἱ ante ἡδοναὶ add. Ga Sp. 17 εἰ ἐπὶ πλέον SF 20 παρακολουθεῖ a Sp.: γὰρ ἀκολουθεῖ libri 22 ὡμολόγηται] ὁμολογεῖται a Sp. 23 τὰς om. a post φευκτάς, add. ὑστε καὶ αἱ ἡδοναὶ τοιαῦται B² 24 αὐταὶ aSp.: αὗται sic V: αὕται SF 28 μόνον sive μόνον οὐ coni. Sp. 28. 29 αὐτῇ scripsi: αὐτῆσ V: αὐταῖς GFS Sp. 31 ἔτι εἰ αἱ Schartc: ἕπεται V (V2? in mg : γρ. ἐπεὶ α γε ἐπ’ ἄλλαις) S¹FB¹G: εἰ δὲ αἱ B2S2 (in mg. addit ἔπειτ’ αἱ S2) Sp.: εἰ δὲ αἱ ἔπειθ’ αἱ a ( ἔπειθ’ αἱ lineola subducta del. Vict.2)
footnote 1 γινομέναισ V1 (corr. V²) 2 δύναναι V1 (corr. V²) αὐλοῦ Vict.?: αὐτοῦ libri 3 ἂν οὖν V2 5 ὅ v2 Vict.? Sp.: V¹: ἅς SFa 6. 7 διαφόρως B²S²a Sp.: διαφόροις VFB¹S 11 τοῖς] ταῖς Sp. 12 pr. καὶ] τε καὶ aSp. 14 pr. καὶ] τε καὶ a Sp. 18 ἂν οὖν aSp. 19 γίνεται Sp.: γίνοιτο libri 21. 22 τοῦ μεταξὺ ἄρα. ἐξ ἧς δὲ Ba (sed τῆς a) Sp.: τῆσ μεταξυ ἑξῆσ (ἐξ ἧς S1) VS¹L: τῆς μεταξὺ οὖν ἐξ ἧς δὲ S2L: τῆς ὄων μεταξὺ ἐξ ἧς ἄρα F: τῆς μεταξ ἑξῆς ἄρα G 26. 27 εἰ γὰρ δὴ] εἰ γὰρ δεῖ L Vict.: ἤ γὰρ δεῖ S²B 2a (,,εἰ si verum, καὶ ante εἴη del. “S  Sp.) 28 οὗδε V: ῷ δὲ Vict.? 31 ἄδικον alt. m1 in mg. V δίκαιος add. Sp. δὲ καὶ ἕξεως B 33 fortasse μήτε —μήτε
footnote 3 κακοὺς ἢ σπουδαίους ἀλλ’ B1 4 ὁμολογοῖεν ⟨ἂν⟩ Sp.: ὁμολογοῖεν VFS: ὁμολογεῖεν Ba 12 μό |ν//μον V ἥ γε] εἴ γε LS²F Vict. Sp.: ἤ γε a 13 μετέβαλε a Sp. 14 αὕτη a κακίᾳ Sp.: κακία libri 16 ἄρ’ οὐκ coni. Sp. ἔσται] ἐστὶν aSp. 19 οῦτωσ V 24 ἤδη καὶ] ἤδη δὲ καὶ Vict. Sp.: fortasse ἡ δῶ [καὶ] 25 ἅπόντα] ἀπαντᾷ Sp.: fortasse ἀ π’ οὐ τοῦ (αὐτῆς?) 28 μεταβολή] μεταβάλλει coni. Sp. ἡ τισ V 29 λεγομένων (λεγο in lit. V)] λεγομένη S2Ba Sp. 33 οὐκ ἄρα S2 B2a Sp. 34 λαμβάνοι] ,,adversarius, sed fortasse hic et postea λαμβάνοιτο“ Sp.
footnote 4 ἐλάμβανε τὸ Sp.: ἐλαμβάνετο libri 8 παρά] πρός aSp. 9 κάλλιστον] μάλιστα Sp.: κάλλιστα Schwartc 17—129,23 τῷ πλούτω—προαιρούμενοι om. GFSL (G in mg.: ἐντεῦθεν λείπεται τὸ τέλος τοῦδε τοῦ δ κεφαλαίου καὶ τὰ λοιπὰ ἄλλα δ αεφάλαια ὁλόκληρα. τὸ δ’ ἑπόμενόν ἐστι τὸ τέλος τοῦ κεφαλαίου τὸ ἀρχόμενον ἐκ τοῦ ‘βιάζονται’’. ὁ ζητῶν δ’ ἴσως εὑρήσει. excidisse plura  signo notatum in S. lacunae vestigium deest in FL.) 22 ἡ add. B2a Sp. 27 ἄλλων V1 in mg. οὐδὲ τῷ πλούτῳ δὴ coni. Sp.: lacunam indicavi 32 λέγοι ⟨ἂν⟩ Sp.: λέγοι V Vict.: λέγει a 33 τοιαύτη] τ in lit. V
footnote 5 οὐδ’ scripsi: οῦτ’ libri ἀδιάφορόν ἐστιν coni. Sp. 6 ἀδιάφοροι scripsi (,,indiferenttes“ Bagolinus): διάφοροι libri ταῦτα δ’] ταὐτόν coni. Sp. 10 ἀδιάφοροι V 11 ᾖ πᾶν coni. Sp. 14 pr. ἢ] ή V 15.16 κατηγορούμενον] inter ο et ν una littera erasa V 16 θατέρω V 21 ἀδιαφόροις] φ in lit. V 26 ἐν add. B2a Sp. alt. τὸ] τὸν B2a Sp. 27.28 πῶς γὰρ οὐκ] ως γὰρ οὐκ in lit. V 31 τοῖς Vict.: τῆς libri δι’ αὐτὸ] fortasse διὰ ὰ τὸ
footnote 1 δοκεῖ] εῑ in lit. V 8 οὐκ] fortasse εἰ λύπῃ a: λύπη V ἔσται γὰρ οὕτω τῷ Sp. 11 δὲ δὲ V 12 ἡδομένοις scripsi: ἡδομένας VB: γινομέναις Ba Sp. 20 ἐκεῖνοισ sic V 20. 21 οὐ μὴν—ἡδονάς om. Ba Sp. 31 lacunam indicavi 34 καθόλον Sp. ψυχικὴν] κὴν in litt. 5 litterarum V 35 pr. εἴτ’ B2a Sp.: εἴδ’ VΒ 37 λύπη ⟨ἡ⟩ coni. Sp. fortasse τοῖς ἡδονὴ—p. 126,1 ἀγαθὸν in lit. V
footnote 1 τοῖσ] ταῖσ a Sp. 2 κακόν VB¹: ἐναντίον ὡς κακὸν κακῷ B2a Sp. τὸ ἐφ’ οἷς μηδὲ γενόμενον VB¹: ἐλλείψει β Sp. 8 διαχύσει Vict. (ubique restituit): διαλύσει litbri 9 ὁ om. a Sp. αὐτῇ Sp.: αὐτῆς libri διάλυσις V 10. 11 τῇ τοιαύτῃ ἡδονῇ Sp.: τῆς τοιαύτης ἡδονῆς libri 13 ἐναντία V: ἐναντίον Βa 14 διαλύσει V 19 τῇ ἡδονῇ B2 Sp: τῆς ἡδονῆς libri bis 21 ὅσαι B2a Sp.: ὅσα libri 22 αὐταῖς] υ in lit. V 23 διό coni. Sp. 21 post τῶν add. ἐνεργειῶν, εἰ δὲ τῶν B2a: τῶν ⟨ἐνεργειῶν ἡδονῶν⟩ coni. Sp.
footnote 2 ἐστι Ba Sp. 3 ante ἢ titulum iterat Ba  Sp. 5 πᾶσαν B2a Sp.: πῶσ ἂν VB 6 πασῶν. ⟨ἢ⟩ ἡ Vict. Sp. 7 ὅτι—λόγου punctis notat B2 (in mg.: λύσις οὐ μέντοι ἀκριβής): om. a 8 οὐδὲ Sp.: οὔτε libri 14 λύπας] υ in lit. V 29 ὧν] ν s. v. V 29. 30 ἑβδόμῳ τῶν Ἠθικῶνν] Eth. Nic. VII, 1. 1145 a 15s sqq. 31. 32 ἐναντίον ἔσται λύπη Sp. 36 αἷς Sp.: οἷς] libri
footnote 1 alt. δὲ V1 in mg. 3 οὕτε γένος Ba Sp.: οὐ γένος V 4 ante οὔτε titulum iterat Ba Sp. οὔτε] οὐ B²a Sp. 6. 7 γε οὕτωσ V: τε sa Sp.: fortasse δὲ οὕτως 7 εἰδῶν οὕτως τἆλλα θa Sp. 8 ἀναιρουμένης] ης s. v. in lit. V 9 ἐν] εῖναι coni. Sp. bene 10 ἀποφρονήσεωσ V οὐκ ἂν] υκ ἂν in lit. V εἴη] η add. v. c. V 17 τῆς ἀρετῆς coll. post κατηγορεῖσθαι Ba Sp. 19 εἴη] η add. v. c. V ἐκείνη a 20 οὐ punctis notat B: om. a 21 τελείαν Sp. 22 τι a Sp.: τισ (ι in lit.) V 25, 26 δτι-πράττουσιν add. Ba Sp. 27 ἀνασκησίαν] ἀναισθησίαν Vict. Sp. 28 αὐτοὺς Sp. 30 ἐπικαλοῦνται B2a Sp.: ἐπικαλοῦσιν V ἔχονται a
footnote 1 ἐρωτῶντες sic V: ἐρωτῶντες B1 ὡς addidi: ἐστὶ καὶ add. B2a Sp. 6 εἰσιν (εἰσιν V)] ἴασιν coni. Sp. fortasse recte πεπεισμένοι μὲν βλαβήσεσθαι B2a Sp. εἴκοντες δὲ τῇ aSp. 8 αὐτήν] ην in lit. V 9 ἔννοιαν] εὖνοιαν a Sp. 10 ἀ| νεννόητοι (νεν in lit. V οἱ μηδέπω B Sp.: οἱ μὴ δέπω (μὴ s. v.) V: ὅρμη δέπω a 15 κοινὴ] ὴ in lit. V 17 τούτοις Sp.: τούτους libri 19 ὰμαρτήματα] tert. α in lit. V 20 ὅτι] ο in lit. V δὲ μὴ corr.e μὴ δὲ V: δὲ μὴ δὲ Ba Sp. βίη] β in lit. V 21 αὐτοὺς αἰτίους⟩ Θiels 22 ὀργ ἴκὰ (κὰ in lit.) sic V 23 προαιρουμένους] pr. υ in lit. V 24 εῖεν] νin lit. V εὶ] οἱ Vict. 25 αὑτοὺς Sp.: αὐτοὺς V: om. a τῶν κακῶν φρονοῦσιν VFB1 s1: Sp.) νόμων καταφρονοῦσιν, τὰ κακὰ οὐχ ἡγούμενοι εἶναι κακά B²S²a Sp. 27 αὐτοῖσ V αὐτοὶ Ba Sp.: αὑτοὶσ V: αὐτοις FS ὅτε γ’ ἦν Schwartz: ὅτε μὴν VBFS¹: εἴ γε B2a Sp. 28 τὸ μὴ πράττειν B2a Sp. δι’ ἃ γεγόνασιν scripsi: διαγεγόνασιν VB¹B¹F: ἂν διαγεγόνασιν B²S²a Sp. 31 μοχθηρᾷ Schsartz: μοχθηρὰ VFB¹S¹: αλρετὰ B²S2a Sp. τὰ delevi
footnote 1. 2 δι ἣν] δ’ ἦν a 6 εὶ] fortasse καὶ ὅτε Diels, cf. 29,27: ὅτι libri ἠμέλουν V 13 ἡ δι’—οὐ βίᾳ (15)] om. Ba Sp. del. 14 fortasse ⟨ποιοῦμεν οὔθ’ ἃ δι’ ἄγνοιαν⟩ ποιοῦμεν 15 οὐ del. v. c. V βίᾳ—ἁμαρτανόμενα (16) V in mg. 16 τὰ add. B²SFa Sp. 17 ἁμαρτανόμενα] ἀμαρτανόμεῦ |V 20 αὐτοτσ V εῖεν] εἴη Sp. 22 ἀγαθα V οἱ δὲ] οῖ δὲ V 24 ὑπολήψεις] εἰ in lit. V ἀεὶ] δὴ a 27 ἐπεὶ τὰ a 30 αὑτοῖς VB: αὐτοὶ a Sp. 32 ἀκού| σίον V 35 γινόμενα] ινο in lit. V
footnote 6 γὰρ χάριν B2 coni. Sp. 7 αρετάσ V τ’ ἔχειν coni. Sp. 9 ἄρα (in mg. m¹ VB: ὁ γὰρ ἄνθρωπος GFS (S² in mg. ἄρα) MNL: ὁ ἄνθρωπος ἀρα a Sp. 11 οὐ—γίνονται] sententiaaut manca (ἀρεταὶ ἀρετῶν] υ ἀρ in lit. V 21 οὐδὲ coni. Sp.: οὔτε libri 22 ἡ] ἠ V 24 post ὁ litura V 26 οὐδὲ Sp.: οὕτε libri 27 γένος] τινὸς a 29 ἐν Sa Sp.: ἐπὶ V 30 ἡ om. aSp. διπλῇ a Sp. ἑκατέρα corr. in ἑκατέραι v. c. V 31 ἤ add. v. c. V 32 δεῖ] δὴ a 34 δεῖ S2B (in lit.) a: διὰ VS1 αὐτῷ V
footnote 2. 3 ἀμφοτέροις] ἀμφοτέρας a 7 ὑπὸ] ἐπὶ aSp. 10 τῷ BSaa Sp.: τοῦ VB¹S 14 ὄν om. aSp.· 16 τῷ] τὸ a 18 titulum ea form reddunt Vict. et Sp. quas exstsat in tabula ἐκ τοῦ τρίτου] Eth. Nic. Ill, 1. 1110b 15 21 ἐν B2: in lit. Vict.:? ἐν ἡ VB¹aSp. 22 ἐν τοῖς ἔμπροσθεν] th. Nic. III, 1.1110a2 23 μεταβαλῶν ,vir doctus in e,emplo bitbl. univ. Monac.“ Sp. 24. 25 μὲν γὰρ πράττειν aSp. 25 λεγο |μὲν (υ sive ου supraν v. c.?) V 28 τοῦ sic V 29 πράττει 8 B² Vict. Sp.: πράττειν ὃ VFa αὑτοῦ V 30 ἢ ὡς a 31 αὐτῷ aSp. 32 πράττον ἡ V: πράττοντι SΒ (ante τέλος rasura) a Sp.: fortasse καὶ ⟨τοῦ⟩ τοῦτο πρ άττεῖν τέλος 23 ὃν om. aSp. βιάζεται addidi
footnote 3 ἔδειξεν] cf. l. c. 1110a3 ὑπὸ] ὁ in lit. V 4 ὑπὸ] ἐπὶ Sp. 6 οτος a Sp.: οὕτως libri 7 ἡ τοῦ om. aSp.: δι’ αὐτοῦ Diels καταβάλοι Diels: καταβάλλοι 1ibri 8 κηνήσασ V 10 ποιήσαι Diels: ποιήσει a Sp.: ποιήσῃ V συνήθῇ sic V 11 εἶπεν] ic. Eth. III, 1.1110a15 14 κινεῖ] ι in lit. V 16 δὲ add. B²S2 Sp. δι’ ἡδονῆς] διὰ ἡδονὴν aSp. 19 titulum eaforma qua exstat in tabula reddunt s² Vict. Sp. 21 κτὰ sic V 23 ἐδειέεν] t. Vic. K,5. 1175a 20sqq. 24 ἐφ’ ας γίνονται add. ante ἡδονὰς F8aa Sp. συναυξομένας FS1 25 τὰς ἐνεργείας B2a Sp.: ταῖς ἐνεργείαις VB9 26 ἡ addidi τὰς — (28) γίνονται om. S1 28 ταὐτὰ 2 Vict. Sp.: τ’αῦτὰ V: ταῦτα SFa ἐνεργείαις] ἡδοναῦς Vict. 31 περιηίιεδαι  a Sp.
footnote 1 ἀδιαφόρων GFS¹: ἀδιαφόρων sic V: διαφόρων B²S²aa Sp.: διαφορῶν S¹: fortasse αὐτοῦ τοῦ ἀπὸ τῶν διαφόρων 2 αὐτοὶ] οἱ in lit. V διαφορῶν V 3 ἢ] ἡ V περιποιητικά] ε in lit. V 7 γε] τε coni. Sp. 10 post ὥσπερ add. αἱ aSp. 11 post αἷς add. αἱ aSp. 13 ἂν add. Sp. αλρετώτεραι GFS ποιοῦσαι v. c. VS²Ba Sp.: ποιῆσαι V¹: ποιήσασαι GFS 14 αὐτῆς coni. Sp. 17 post ὃ paululum erasum V 20 εἰ add. aSp. αἱ om. Sp. 25 αἰτία γίνοιτο Sp.: αἴτιοι γίνοιντο libri φέροιεν Sa Sp.: φέροι sic V¹: εν in ng. add. v. c. V: φέροι B1GF: φέροι ἐν B² 26 τοῖς σώφροσι add. ante φευκταί B² 27 αἴτιαι a Sp. 29 ἐνέργείά i. e. ἐνεργεία V 30 ἐν τῷ ἑβδόμῳ] th. Νic. VIl,13. 1153a14 30. 31 δυνήσονται a 31 χωρίζεσθαι V Sp.: χωρήσεσθαι SFG Vict.: χωρήσεται a: χωρίσεται Vict.? ἐνεργείαις] ante αἱ 2 litt. erasae V
footnote 2. 3 ἐν τιῷ τελευταίῳ] Εth. Nic. X, 4. 1174b14 3 δὲ καὶ a Sp. post αἴσθησιν add. κειμένων Vict. τοιοῦτον Vict. B² Sp.: τοιούτων VBSa 6 ᾦ] ante ῷ lit. 1 litt. V: in lit. B 7 ἑκάστην B2 Sp. 8 ὑφ’ αὑτὴν Sp. ex Arist. 11 εὖ ἔχοντος B² Vict. Sp.: περιέχοντος VB¹Sa 11. 12 ὑφ’ αὑτὴν aSp. ex Arist. (ὑπ’ οὐ. Arist. K) 14 ἡ a μὲν εἰ] μένει a 15 τε καὶ ταῖς aSp. 20 αἱ om. a Sp. ἀρστα sic V 22 ἑκατέρῳ Fa Sp.: ἑκατέρου V 23 μή V 24 δῆλον αἱ εἰς VB¹B¹: δ. ὡς εἰς B²: δ. ὡς S2aSp.: fortasse δηλονότι εἰς 25 αἰτίαι VBBV: οἶαι αἱ B²SaSp.: fortasse αὗ ται δ’ 26 ἀφαι V 27 εἰ VS¹F: ὅς B2a: ὡς S2 Vict.? Sp.: εἴ γε Schsart post εἷπεν sad. δηλῶν a Sp. ἐνέργείαι sic V 28 λέγων] Eth. Nic. X,10 1175a3 οὐδεῖσ V 29 ἀνθρώπεια corr. ex ἀνθρώπια V 30 καινὰ B2S2a Sp.: κενὰ VB¹B¹F 32 διανοια V 31, 32 παρακέκλιται Sa: παρακέκλισται
footnote 1 ἐμβλέποντες B2S2a Sp.: ἐκβλέποντες VB ¹S¹F γίνεται om. Arist. vulg. 2 ἐνέργεια] a s. v. V 3 τοιαύταις] ς in lit. V τοιαύταις -ἠμελημέναις om. a (ἀνέσεσι—ἠμελημέναις add. Vict., qui τοιαύταις delere videtur, quod om. Sp.) 4 τὸ] ὀ in lit. V: τοῦ Viel. 5 ἐν τῷ δευτέρῳ Περι ψυχῆς] de an. ΙΙ, 9. 421a10 17 ἡ om. a Sp. 20 τοῦ τὸν B² Vict.?: τοῦτον libri τοῦδέ] τοιοῦδέ aSp. 21 περὶ] πρὸ a   τὸν coni. Sp. τὸ] το V: τοῦ coni. Sp. 26 καὶ coni. Sp.: δὲ καὶ V: δὲ καὶ a ἀπατη V 27 ἀφροσύνης aSp. κακίας τινος ἄλλης cni. Sp. 28 κακὸν πᾶσα] πᾶσα κακόν coni. Sp. item v. 30
footnote 5 alt. αἱ om. a Sp. 7 ἀγαθὰς] pars superior litt. θ in lit. V 10 χάριν] χα in lit. V 14 alt. καὶ om. a Sp. 16 δὲ V2B: δεῖ V¹: δὴ SFGa Sp. 18 ἔτι om. a Sp. 20 λυπήσεσθαι a 22 ἐπεὶ] εὶ in lit. V δυνάμεις SFa Sp.: δύναμις VB 23 ἢ εὶ Vict. 25 εῖεν ⟨ἂν⟩ Schwartz 29 γοῦν SFa Sp.: οὖν VB 33 δὲ] fortasse δὴ 34 ἐνέργειαισ V 36 φευκτὰς B2a δὲ om. a
footnote 2 οἰκεῖαι V 3 αὐταὶ Sp. 4 τὰ om. a Sp. 5 αὐταὶ aSp. 7 ἐν τῷ πρώτῳ] Eth. Nic. , 3. 1095b16 8 titulum iterat 8 ante ἢ διά τι a 9 ⟨ἢ⟩ διότι scripsi 10 ἡδονὴ μόνη B αὐτὸν V²Sa Sp.: αὐτὸν V¹: αὐτῶν G 11 αὐτὸ V2 Sp.: αὐτὸ V¹: αὑτὸν Sa αὐτὸ V μόνον] μόνη a Sp. 12 αἱρετὸν GFS1 αλρετὰ addidi: καὶ add. V2?BSGFa ἔσται coll. post ἐκεῖνα GSFa Sp. 14 ἀνδρίαν sic V 17 αἰσχρὸν addidi: post τὸ αἰσχρὸν add. S²B2a Sp. εἴη μὲν a κακὸν S²B2a Sp.: καλὸν V 18 φυλασσόμενοι BS²a Sp.: φυλασσομένῳ V 19 οὐδὲ V ἂν om. a Sp. 21 αὐτὸ V 22 ἂν addidi 23. 24 ἀλλοτι V 24 αἱ del. (sive corr. in εἰ V 25 εἴη coni. Sp. 26 τουτ’ v 27 γε in ras. BSFG aSp.: δὲ V 28 αὐτὰς a Sp. 31 καλὸν ἢ] ν ἢ in lit. V
footnote 2 ἡ SFa Sp.: εἰ VΒ 3 αἰσχρὸν V 5 post ἡδὺ add. ὃ a 8 αὑτῶν V: αὐτοῦ B¹: αὐτοῦ B2a Sρ.: ἑαυτοῦ S² 10 ᾦ Vict. Sp.: ὡς libri δὲ om. a 11 τῷ Vict.? Sp.: τὸ libri 12 ἐρυθαίνεσθαι V²GSFB: ἐρυθένεσθαι V¹: ἐρυθραίνεσθαι a Sp. 13 γινόμενον ἔτι aSp. 19 τῶν ἧττον σπ. Vict. 20 κωμωδοῦντοσ V 21 τραγηματίζεν] μα in lit. V 8 ἡ θiels: δὴ VS¹B GF: δὴ ὅπερ S²B²a Sp. λύσει V (corr. V2) 23 αῦτη V: αὐτὴ a Sp.: αὐτῆς SF ἔτι in lit. V εἰ add. Schvart 25 εἷεν οὖν ἂν V²B Vict. Sp. 26 ἀκολάστου] κ in it. V ᾖσθῆναι V (corr. V²) 30 χρήσιμον] σι add. V2 31 ἠ V ἀναιρεῖ τὸ] ἀναιρεῖτο V
footnote 1 αὐτὸ V 2 δὲ add. V²BS2a Sp. 4 πᾶν δὲ VBSa Sp.: ἐᾶσοι V¹F1B1 ὥστε G 5 ποιητικόν] ό in lit. V 7 τι] ι in lit. V 9 ἀγαθοῦ (θ in lit. V 10 αυτοῦ V 11 οὓς B²Sa Sp.: ὃ VB¹F Vict. post μόνον add. τὸ χρήσιμον Vict. Sp. τὸ V¹ GF: οὐκ ἔσται τὸ V²BSa Sp.: fortasse τὸ χρήιμον, ⟨ἀναιρεθήσεται τὸ χρήσιμον⟩ ἀναιρουμένου 12 ὑπ] ἐπ’ a post ἔχει add. ἀναιρεῖται τὸ χρήσιμον GF 13 χρήσιμον in lit. V διότι χρησίμου] διότι χρη in mg. V1 ⟨ὡς⟩ ἀγαθοῦ Schsartc 14 ὃ V2 corr. ex ὄ 17 χρησίμου V 18 ὅτῷ V 20 τοῖς om. SFa 21 τοῦτο] τούτου a Sp. ἔχοι ἂν τὸ scripsi: ἔχοι ἂν VFS¹B¹: ἂν τὸ S2a: ἂν τὸ (εἴη, quod ante ἂν scripserat, del.) B²: ἂν εἴη τὸ coni. Sp. 22 οὐδὲ VS¹B¹F: οὐδὲν S2B2a fortasse recte: δὲ οὐδὲν Vict. Sp. 23 δὴ] δὲ Vict. Sp. 24 τό γε] τὸ vel τότε coni. Sp. 27 εἰ om. del. Sp. ,,nisi apodoais ecidit“ 28 συναίρεται V²B Vict. Sp.: συναναιρεῖται VFGa 29 τὸ ⟨μὴ⟩ F Sp.: τὸ VBSa 30 ἐνεργείας] α in lit. V 31 lacunam indicavi πάντα] τα add. V2
footnote 1 Vict.?: παιδείᾳ libri item v. 6.17 καταζῆν scripsi: κατὰ τὴν VB¹S¹: κατὰ SB²aSp. σπουδῆς] ς in lit. V 6 παιδιάν Vict. 7: παιδείαν libri 7 τε Sp.: γε libri, quod S¹F coll. ante ἐπιστήμης 8 εἴη ἡμῖν a Sp. 11 οὔτε B² Sp.: οὔτε VS²2 Vict.: οὔτε ἃ S¹a ἐν τοῖς om. a 13 περὶ αἰδοῦς in lit. V 14 ἐν τῷ δευτέρῳ] Εth. Nic. II, 7. 1108a30 15 ἐν τῷ τετάρτῳ] Etm. Nic. IV,15. 1128b10 19 αἰδὼς] ante ς unsa lit. erasa V 20 λοιπὸν αὐτό φησιν εἶναι a Sp. δὴ V2: διὰ V1a: om. B² Vict. Sp. 26 συνίσμεν V (et v. 32 αὐτοισ V τὴν add. Sp. αἰδομένοις a Sp. 32 αὑτοῖς V²B²: αὐτοῖς VFB¹: αὐτοῖς αὐτοῖς a: αὐτοὶ αὐτοις Vict.? 7 Sp.
footnote 3 ἀποκέκλεισται B²S1 Vict.? Sp.: ἀποκέκληται VFB1 : ἀποκέκλειται G: ἀποκέκλεισθαι S¹a 4 εἰ δεῖ V2 Vict. Sp.: εἰδει V¹: ἔδει Fa 5 ἣ V corr. ex ἤ 5, 6 ὁ—αἰδώς circumscripsi 6 τοῦτο ⟨τὸ⟩ coni. Sp.: τοῦ Vict. πάθους Vict. οὐδὲ forttasse οὐδενὶ 7 αὐτὸν (in mg οἶμαι Ἀριστοτέλη V1) V¹FS¹B1G: αὐτὸν τὸν Ἀριστοτέλη λέγοντα (δηλοῦντα B²) B²S²a Sp. 8 ἐστιν] στ in lit. V 9 αἰσχρὰ πάντα VB ¹S¹: τὰ αἰσχρὰ παρ’ αὐτοῖς S²B²aSp. 10 τῆς] Ϛ in lit. V 23 ήθικαὶ] θι s. v. V 25 τε VSB¹FML: del. B2: om. aSp. εἵπετο VB¹: ἔκ τε τοῦ S¹FL (τοῦ corr. ex τὸ): επετο (ἔπετο a: ἕπεται Sp.) τὸ γὰρ S²B²aSp. fortasse φρονήσεως ⟨καὶ ἠθικῆς ἀρετῆς⟩ ε ἴ γε τὸ 26 σκοπὸν] inter ο et π paull. eras. V αὐτὸν] αὐτὴν a Sp. 28 ἐφιέμεθα] ι s. v. V 29 ex gr. Eth. Vic. II, 9. 110a20s sqq.
footnote 1 pr. ν in lit. V ἡ om. a Sp. 5 αὕτη M: αὑτὴ (erat αὕτη) V: αυτη L: αὐτὴ a Sp. 8 δοκεῖ μοι ἐλλιπὲς εῖναι in mg. 9 εἰ ἡ Vict.? Sp.: εἰ V: ἡ Sa ἐνεργεία a 12 εἰ οὖν ἐστιν a Sp.: ἢ οὐκ ἔτι VB: ἢ οὐκ ἔστιν FS φύσιν V 14 ἐφίεται V οὐ add. Sch wart 15 σιτιον V 16 ⟨ἤν⟩, ἐν coni. Sp. 18 fortasse ⟨αἴτιον⟩ τοῦ 21 καὶ om. a Sp. 22 fortasse ⟨καὶ⟩ κα θὸ ἄνθρωπός ἐστι, οἰκείαις ἐν. εἰ om. aSp. 23 γίνοιτο a 25 ἔτι ἡ Vict. Sp.: ἔτι ἡ VBFB²a: ἔτι εἰ B1 ἐνέργεια] α s. v. V 26 τρόπον] ν in lit. V ἐν τῷ τελευταίῳ] Eth. Nic. X, 4. 5. 1174b14 sq. ἡ om. a Sp. 27 εἴη] εἴ in lit. V ἐνεργείᾳ B2a Sp.: ἐνεργείας VB1 29 ἡδονή V αὐτή V 31 ἐνεργείᾳ a
footnote 2 ταῖς ἀρεταῖς Schwartz 3 δεῖ add. S²B²a Sp. 4 τοῦ τὸ B²a Sp.: τοῦτο VFB πλεῖον a Sp.: τέλεον Sclwartz αὐτῇ V μὲν οὖν V²B: Vict. Sp. 6 ἐνεδείξατο] Eth. Nic. , 3.1095b 14 sqq. 7 αρδανάπαλου V 8 χάριν coll. ante τῆς FSa 9 ἡδειαι V¹ 10 γε Diels: τε libri: om. aSp. 16 διὰ τὰς om. a ἐπὶ] ἐν aSp. γινομένας (ας in lit. B) Ba Sp.: γινομέναις VF 22 τούτῳ VB¹: τούτων S¹F: ζῆν. διὸ SB²aSp.: fortasse τοῦ τό τοι cf. de an. 8,25. 97,1 25 παραμυθούμενος V (corr. V² 30 αὐτὴν V¹ (corr. V² συμβαίνει] μβ in lit. V 33 συνυπάρχει] υ pr. in lit. 4—5 litt. V 34 τὸ ζήτημα τοῦτο γέγραπται αὐτολεξὶ δι’ ὅλου τοῦ ᾶς κεφαλαίου V mg. cf. infra 151,17 sq.
footnote 1 τὸ καλὸν V μενούσης a δ’αὑτὴν a Sp.: δι’ αὐτῆς S¹: διὰ αὐτὴν V 2 ἔχοντες a 3 αλρετὸν om. a Sp. 4 ὑπ’ in lit. V 6 ἡ εἰ μὴ V2SBVa Sp.: εἴη μὴ V1 ἀληθὲς aSp. 9 ἢ καὶ μᾶλλον add. B2, recte cf. 151,29 9.10 εἰ καὶ] ἤ καὶ a: εἰ infra 10 αὕτη V2B: αυτη V¹: αἰτὴ Sa Sp.: αὐτή F παρασκευάζει (παρασκευάζοι V2B2 infra) τὰς S2VB²a infra: παρασκευάζοντας V¹B¹F 11 καὶ ἢ a Sp. 12 ἠ V 13 ἡ om. a Sp. ἡδονὴ] ὴ s. v. V 16 alt. τὸ Fa Sp.: τε VΒ infra 20 αἱ ante ἐπὶ add. V2B infra ἡδοναὶ] αι in lit. V αἱ αὐταὶ V2BFBa Sp. infra: αὗται V εἶεν] ἶε in lit. V 22 αὐτὰσ V 26 ἐστιν, ἀλλ’ Vict. ἀλλ’ ἀπιθάνως Sp.: ἀλλὰ πιθανῶς V(et infra) FB: ἀλλ’ ἀπιθάνως Sa 31 τερπνὸν a Sp. 33 πῶς οὐ συνδιαιρούντων in lit. B² Vict. Sp. infra: ὁπωσοῦν διαιρούντων libri ἐστι] ἐπὶ Sp. Suppl. Arist. II 2 Alex. sc cripta minora.
footnote 7 κακῶν S¹H μικταὶ] λυπηραὶ Sa 14 δι’ αὐτὰσ V 15 αλρεταὶ FB²aSp.: ἀρεταὶ V 16 καὶ B²: εἰ libri δυνώμεθα om. a 19 μέτρον B2 Sp.: μέτρων libri 20 τὴν om. SFa ἅς διὰ V: αἳ διὰ Vict. Sp.: διὰ SFMLa 22 τε] δὲ coni. Sp. 24 κοινωνίας coll. post φύσιν a Sp. (⟨τῆς⟩ οὖσης Schwartz) 26 αἱρετὴ V1 (corr. V2 27 αὐτὴν V αρετη V 28 ἐν αὐταῖς a Sp. 29 δι αὐτῶν V¹FS¹M2 (sed αὑτῶν) L: δι’ αὑτάς V²B¹: δι’ αὐτάς B²S²a Sp.: ὑπ’ αὐτῶν Μ ἑκάστην V2BS²a Sp.: ἑκάστης V¹ FS1 ΜL 30 αἱρετήν V¹B2S²a Sp .: αίρετή V¹: ἀρετή FS¹M ἂν addidi 31 δι’ αὐτὴν V1 in mg ἑκάστῃ] ι adscripsit V2 τῶν] ν s. v. V τὸ] τῷ Vict.? Sp.
footnote 1 αυτὰσ V ὡς] ς in lit. V εἰ ἦν ἡ scripsi: εἰ ἢν ἡ V2: εῖην V¹: εἰ ἦν BS2a Sp.: ἦν FS¹ML 3 αυτη V¹ (corr. V²) αιρετὴ V¹ (corr. V2) αυτὴν V1 (corr. V2) 4 αἱρετὴν Sp. ἐν αὑτῷ V²: ἐν αὐτῷ V¹BSF: ἐπ᾿ αὐτῷ (ἐφ᾿ αὑτῷ coni. Sp.) MLSFa Sp. 6 τὴν] ν in lit. V 7 pr. αἱ in lit. V ἃ Sp.: ὃ libri 10 τῶν] ῶν in lit. V καὶ in lit. V 11 αὐτὸς] ὸ in lit. V ὥστε] ὥσ in lit. V 12 δ᾿ del. B2 Sp. 13 αυτας V1 (corr. V2) αἱρεταὶ V2S2a Sp.: αρετὸν V¹FS¹ML 14 αυτὴν V1 (corr. V2) τὸ γὰρ s. v. V αὐτῷ V αὐτοῦ V 15 αυτὸ V1 (corr. V2) 17 σωτηρία] ante α una litt. erasa V 18 αὑτὰ (αυτὰ V1) αἱρετά] αὑτὴν αἱρετή B2S2a Sp. 19 ἡ om. a Sp. αυτὴν V 21 αυτὴν V1 (corr. V2) εἴη] εἴ in lit. V 22 αυτὴν V1 (corr. V2) τοῦ τε VB: τουτέστιν SFMLa Sp. 23 νόμοις a 26 τούτῳ B2 (in lit.) SFMa Sp.: τούτων (των s. v.) VF2: τοῦτο L 26. 27 ἄλλων] ἄ in lit. V
footnote 3 εἴη ἂν om. a αὑτὸ (αυτὸ V1)] αὐτὸν a 8 δὲ τὸ FSaaSp.: δέ τι VB 10 ἡ add. V2M 13 αὐτῷ a Sp. 14 τούτῳ] τοῦτο B² 15 εἴ γε ἡ τέχνη ante μιμεῖται add. S2B² a Sρ. fortasse recte 21 τέλος add. VBS²aSp. 22 παραγίνεται Vict. Sp. 23 ἔσται ἐν a Sp. 24 καὶ del. V2 τὰς οἰκείας [τὰς] Diels 24. 25 οἰκεῖον a Sp. 25 ἐνεργεῖν] γ in lit. 2 litt. V 26 τῷ γὰρ coni. Sp. ἀνθρώπῳ VB coni. Sp.: ἄνθρωπον FL: ἀνθρώπου Sa 29 ἂν καὶ ἡ Vict. Sp. αὕτη Diels 31 γε] τε a Sp. τελείῳ SFa Sp.: τελείου VB 32 βουλευτὰς Sp.: βουλητὰς libri
footnote 2 δὲ add. S2B2a Sp. 4 διττὴ] ὴ in lit. V δὴ (in lit. V: δὲ GSa Sp. 5 πείθεσθαι] ἐπιδέχεσθαι Sp. λόγῳ] λόγον a Sp. λόγου] λόγον Vict.? Sp. 6 ὀρεκτικὴ] κτ in lit. V 7 αὐτῇ V 9 ἐνεργείᾳ] εί add. V2 post ὀρεκτικῆς add. ἐνέργειαι μὲν V2 10. 11 ἐγγίγνεσθαι] ἐγγί in lit. V 12 ἀρετὴ M: Vict ? Sp.: ἀρετὴν Va 13 ἐνέργεια : ἐνέργειαι Sp.: ἐνεργείαι Vict. ?: ἐνέργειασ (σ corr. fortasse in ι) V: ἐνεργείας LFa 14 γίνεται] νεται in lit. V 15 ἀρετῶν V ἑκάστη Ba Sp.: ἑκάστου (ά s. v.) VF τί ⟨τὸ⟩ coni. Sp. 18 δυναμεωσ V αἱρουμένης] η in lit. V 21 τε καὶ a Sp. 22 τε τοῦ] μὲν τοῦ a Sp. 29 alt. αἱ s. v. VB: om. SFa Sp. 32 ταύτας a ἀρετὰς] ὰς in lit. V συνίστασθαι] συν in lit. V 33 pr. τε del. Schwartz : alt. Sp.
footnote 2 s. v. V 5 alt. δὲ om. a Sp. 8 μέσου sic V 9 δέδεικται VB Vict. Sp.: ἔτυχεν MLSFa 10 εἴη] εἴ V1 (corr. V² 11 τῶν in lit. V 12 ἡ om. a Sp. 17 αἱ περὶ V Vict. Sp.: περὶ V¹ SFa 26 μὲν om. a Sp. 29 ἡ δὲ B Vict. Sp.: ἡ δὲ V²: ἡ οὐ V¹F: ἢ σὺ S¹Μ: ἢ δὲ S2a: ἢ οὖ L 30 περὶ scripsi: ἐπὶ libri 33 τὴν δὲ τοιαύτην V² 36 αὐτῇ Schπart: αὐτη V¹: αὔτη V¹: αὐτὴ a Sp. 37 ante pr. τῶν 2—3 litt. erasae V
footnote 4 ἀληθές VB¹L: καὶ ἀληθὲς τὸ Ma: ἀληθές, τὸ Vict.? Sp.: τὸ ἀληθὲς τὸ B² 6 δια V 7 τι] τις V1 (corr. V2) 14 εἴη ἂν οὖν ἡ ἀρετὴ add. ante τὴν S2B2a cf. 144,34 sqq. 19 ὅτι add. ante οὐ B Vict. Sp. ἡ add. SFa Sp. supra τοῦ] τούτου Vict. 20 χάριν] χάρ in lit. V 22 καλοῦ το sic V 24 μέτρον ⟨ον in lit.) BS² Vict?1 Sp. supra: μέτριον VS¹ Fa χρὴ add. VBaSp. supra: om. V¹ 27 ἢ εἰ a αὶρεσεωσ V 29 ἢ καὶ μᾶλλον om. Vict. Sp. εῖ] εἰ καὶ Vict. Sp. αὕτη scripsi: αυτη V: αὐτὴ Sp. cf.145,10 29. 30 παρασκευάζει Sp.: παρασκευάζοι libri cf. supra 30 οὐδ’ ἂν] οὐδὲν a ἡδονὴν] ονη in lit. V 31 εἶναι καὶ ἢ Vict.
footnote 1 ὧν B2aSp. supra: V 3 pr. τὸ Sp.: τε libri 4 ἄμα] alt. α in lit. V 6 αἱ om. a Sp. 8 αἱρετάς s. v. (ἐρέτας in lit.) V 9 αἱρετῶν] αρετὸν a Sp. συντελεῖν a 10 μὲν] μ in lit. V 12 ἀλλ’ ἀπιθάνως SFaSρ.: ἀλλὰ πιθανῶς VD 18 τερπνόν a Sp. 19 οὔσας BS¹a Sp.: οὔσης VB²F 20 ἐνεργείαις] ις in lit. ς s. v. V 23 αἰτία a Sp. 27 αἰτίαι V 29 ἐνεργειασ (σ in lit.) V 33 ἐνέργειαι a Sp. 35 αὐτό τε] τότε a 36 αὑτοῦ Sp.
footnote 1 αὑτοῦ Sp. 4 ἐπιβάτην] supr η lit. V καὶ ἐπὶ-5 ἀλλὰ om. a (Vict. suppl., sed falso post λόγος (8), quod perspesit Sp.) 5 ζῴων ἄλλων Vict. Sp. 9 ὁμοίως] ὅμοιος Sp.: ὁμοίοις a: ὁμοῖος Vict.v 9.10 οἰκοδομικῆς] κ in lit. V 10 pr. ἐπὶ om. aSp. 11 τε om. aSp. 13 ἀφ’ ὧν B1 14 ἀποδίδωσιν V¹SFa Sp.: ἀποδώσει B : ἀποδώσειν V² 16 δεχομένων V¹ (cor. V² 17 ἐν] ὃν Sp. φευκταῖα V1 (corr. V²) τὸ μέσον a Sp. 18 αὑτῷ Sp.: αὐτ] V²: τῷ V¹Sa: ἴσως εὖ aut potius ἐν αὐτῷ’’ Vict. 20 τὴν] τ in lit. V γενομένην Sp.: γινομένην libri 25 alt. δὲ om. a Sp. 26 pr. καὶ om. a ἠθικὴ] ή s. v. V Vict.?: ὃ libri 27. 28 κατὰ ταῦτα καὶ περὶ ταῦτα coni. Sp. 28 τὰ αὐτὰ SFa Sp. 31 τὸ post εὖ coll. Sp. falso, cf. 15522 et Arist. Nic. Eth. II, 6. 1107a8 33 προαιρετικὴν Vict.?: διαιρετικὴν διὰ libri cf. l. c. 1106b  36
footnote 1 τοῖς] αὐτοῖς V¹ (corr. V²) 2 ἔχοι a προχειριζομένοις FSa Sp.: προχεριομένη (supr η lit.) V: προχειριομένης sic B1 4. 5 φυλασσομένη V² Vict.? Sp.: φυλασσομένης V¹SL (ex corr) Fa 5 ἐν VBI Vict.?: ἐκ S2: εὖ GF MS1 a Sp. εὖ τυγχάνει V: ἐντυγχάνει G¹FLMS¹a Sp.: εὐτυγχάνει G²S²: τυγχάνει Vict. 6 ἕξεων Vict. Sp.: ἐξ ὧν libri δειλία in lit. V 8 φυλάττομεν ἡ a 9 κατ’ αὐτὰ a ἐνδείας] ἀνδρείας B1 αροῦμεν ἡ a 11 ἕξέων] ἐξ ὧν a 12 pr. καὶ om. Sp. 16 τοῦ Vict. Sp.: τῷ VS¹ B¹ FG: τούτῳ SB²a τι corr. ex τε V2 21 τούτοις a 25 ἒν ἦν V²BFΜ Vict.?: ἐνῆν V¹: ἐνην G: ἔνην b: εὗ ἦν Sa: ἦν Vict.: ἓν Sp., qui confert Arist. Eth. Nic. 1106a30 26 ἴσῃ] ισ in lit. V 26. 27 τοὺ ναντίον (ante ν pr. lit. 1 litt. V 27 γνωρίμους S2: γνωρίμου VFLΜS2: γνω- ρίμου γεγονότος man. rec. VBS¹a Sp. 28 ὁρισθὲν τὸ V²S²Ba Sp.: ὁρισθέντος V¹FGS¹M1 31 πράξεων] ων in lit. V
footnote 1 ἕκαστον coni. Sp. 2 προόδου V 8 alt. τῶν del. V2 11 αὐταὶ B2Sa Sp.: αὗταί VFB ἔλεγεν coni. Sp. νῦν B²MS²a Sp.: εἰ VB¹ S¹FL 12 αὕτη ἀρετή a 13 συμμετρία V 15 ἐν om. a 18 ἐναντίαι a: ἐναντία V 19 δεήσει a Sp. 20 τὸ μέσως Schwartz: τῷ μέσῳ libri (⟨οὐ⟩ τῶ μέσῳ ⟨τὸ⟩ εὑ μ., ἀλλὰ τῷ ἄκρῳ coni. Sp.) τῷ ἄκρως B2 Vict.? M1 οὐδ’] ἀλλ’ a μὴ δὴ a: μὲν δὴ Sp. 22 τὰς s. v. V 23 ἃ μέσως a: ἀμέσως FL 24 ἄκρων] ἄκρον a Sp. ἄκρον] ἄκρων V¹ (corr. V2) a 26 ταὐτὸν εἷναι a Sp. alt. ἕναι om. a Sp. 31 αὐτὸς] τοῖς S¹F: οἶς S²a 31. 32 ἐν τῷ lIερὶ αἰσθήσεως] De,sensu c. 4. 441 b 14 34 οὐδὲ V2B: οὐδὲν V¹F a Sp.
footnote 9 φήσει V1 (corr. V²) 10 δεήσειν Schwartz 13 ἡ om. Sp. ὡρίσθαι] αι in lit. V 14 γινόμενος a Sp. 17 ἔνδειαν] α in lit. V 19 αἱ ἀρεταί] αρεταί a 20 εἰς τὸ a 21 ἀφαιρεθείη] εί in lit. V καταλιπόμενον V (corr. V) item v. 23 25 τὰ del. Sp. λυόμενα] λεγόμενα Vict.? M λέξεως] Eth. Nic. , 6. 1107a8 28 ἐπιχαιρεκακίαι V 29 πάντα ἀ in lit.) V 30 ψέγεται scripsi cum Arist. vulg.: λέγεται libri τῷ αὐτὰ φαῦλα Vict. ex Arist. vulg. οὐχ αἱ Vict. ex, Arist.: οὐ καὶ libri: οὐ καὶ Schwartz οὐδὲ VM: ἀλλ’ οὐδὲ LSa: οὐδὲ αἱ Vict. ex Arist. 32 ἁμαρτάνει a ἢ μὴ V² Vict.? Sp.: εἰ μὴ Sa: μὴ VS¹L51 τε del. V²: om.B Arist. 33 ἣν B2 in lit. Vict.? ἦν libri ἀπλῶς τὸ ποιεῖν Vict. ex, Arist. 34 ὅμοιον οὖν Vict. Sp. ex Arist. καὶ περὶ Arist. εἶναι μεσ. Arist.
footnote 1 ἐλλείψειν V 4 τὸ τὸ] τὸ a Sp. 5 καὶ] οὐδὲ a Sp. 6 ἐλλείψεως καὶ ὑπερβολῆς a Sp. 7 οὐ] ὑ in lit. V 10 ⟨ἢ⟩ ὡς γένος Sp. 11 ante ἐπεὶ titulum iterat B, cui B2 verb praemittit εἰκότως ζητεῖται 14 ἔχει πρὸς] ἔχειν πρὸς a Sp. 15 ὡς ὅλον VBS (scil. τὴν ἀρετὴν): τὸ ὡς ὅλον F: τὸ ὡς ὅλων a Sp. εἵπετο τῶν μὲν a 19 fortasse ⟨μήτε ὡς γένος μήτε ὡς ὅλον δεῖ κατηγορεῖσθαι⟩. ἢ εἰ 20 τελείαν B2: τελείων VFB¹: τελειῶν a: τελεία coni. Sp. 21 μέμικται (μέμεικται?) Schwartz: δέδεικται VFB1S1 Vict.: σύγκειται S2B2a Sp. 22 ἔγει SBFa Sp.: ἔχειν V 24 πάσαις a Sp. 26 παντὶ a Sp. 27 τήνδε (τῆν δὲ V)] τὴν a Sp. 28 τάδε V2F Vict. Sp.: τῆν δὲ V¹Sa τήνδε δὲ] τὴν δὲ δὴ Vict. Sp. 29. 30 ἑκάστης] ἑκάστῃ a Sp. 30 μίξει scripsi: μίξεις libri
footnote 3 ἐκ τοῦ τρίτου] Εth. Νic. ΙΙΙ, 7.1114a31 6 post φαινομένου add. αὐτοῖς V 2 in mg. 7 post κύριοι add. ὑπάρχουσιν Vict. ὁποῖος Arist. 7. 8 τοιοῦτο a Sp. 8. 9 αὑτῷ τῆς ἕ. Arist. τῆς s. v. V 10 μηδεὶς] μή. οὐθεὶς Arist. vulg. αὑτῷ Vict. Sp.: αὐτῷ V: αὐτοῦ SFMLa ἀλλὰ δι᾿  Arist. 11 τέλους] supra   ς lit. V 12 ἔσεσθαι] εσ s. v. V 13 ᾗ κρινεῖ Β2 Arist.: η κρινει ὁ V¹: ἢ κρινεῖ V²Β2: ἢ εἰ (ἠει G εἰ Vict. ἡ εἰ L): κρίνει GMLSF Vict. a: ἢ κρίνει Sp. 14 ᾡ] ὡς a τοῦτο] τοῦ s. v. V 15 ἑτέρου Arist. καὶ τὸ Arist. 17 καὶ (pr.) VΒ: καὶ τὸ Vict. Sp. ex Arist.: καὶ τὸ om. SFMLa 19 πάντα a  Sp. 22 αὐτοῖσ V 23 ἐφ’ ἡμῖν coll. post ἐνέργειαι a Sp. αἱ δὲ a  Sp. μὲν] om. a Sp.: fortasse μόνον, nisi exciderunt nonnulla post γινόμενον (24) 24 βία V τὸ διὰ V2 B: διὰ τὸ V¹: διὰ Fa  Sp. S2B² in mg.: ἴσως οὕτως ὀφείλει λέγειν: τὸ γὰρ δι’ ἑκούσιον ἄγνοιαν οὐ βίᾳ οὐδὲ ἀκούσιον 25 ⟨ἃ⟩ ἀγνοοῦντες scripsi: ἀγνοοῦντες ⟨ἃ⟩ Vict. 27 περὶ Sp. 28 ἐπεὶ corr. ex ἐπὶ V1 αὐτοῖσ V1 29 παρὰ] περὶ coni. Sp.
footnote 1 ἃ γὰρ] fortasse ἅπερ ἑκούσιον L2BS2a Sp.: ἀκούσιον VS¹FML1, 1. 2 ἑκούσιον—ἡμῖν del. Sp. 2 pr. καὶ V²S2Ba  Sp.: ἠ V¹: ἢ S1 ἀκούσια a alt. ἡμῖν] ἡ in lit. V 12 λεγομένων] ω in lit. V ὧν add. Β² 13 αὐτῷ V ⟨ἃ⟩ διὰ scripsi 14 ποιεῖ ante τῆς om. Sp. fortasse αἰτίαν ⟨ἔχων⟩, 14. 15 ζήσας ἀνειμένως FML: ζήσασαν εἰ μὲν ὡσ V: ζησας ἀνειμέν ὡς S¹B¹: ζητήσας ὡς S²B²a Sp. 16 βία V 16. 17 μηδὲν μὲν ἡμῶν Vict. 17 αὐτῷ V 18 τε καὶ a  Sp. 21 εἰδόσιν V οὔτε γὰρ] ε γὰρ in lit. V 22 αὐτῷ V ταῦτα] τι ΜL 23 οὔτε V1 in mg. τὰ] τὰς a 24 τὰ scripsi: η τε sic V¹: οἴ τε, V²: ἥ τε FS¹ΜL: ἢ τὰ S2: τὰ ἢ Β in lit. a  Sp. βία V 28 ταυτὰ a 30 ὑπ’ αὐτῶν Sp.: ὑφ’ αὑτῶν libri 31 ακούσια V 34 τὸ B2S2a Sp.: τὰ VB1: om. S¹FΜL
footnote 2 μετὰ λόγου] μεγάλοι οὐτέ V (corr. V²ῶ 15 οῖῦν V (corr. Vῶ 17 βουλευτὰ a Sp. 18 βουλευτὰ alc V 21 αἴ] fortasse κ αἰ αἱ s. v. V 23 ὀρέξεως] infra ἐξ lit. V 25 ἡ ὄρεξις aSp. τῶν s. v. V 27 τὰ om. a Sp. 29 κατὰ τέχνας aSp. 31 ἐκτώμεθα a γὰρ σm. a τὰ in lit. V 32 ὥσπερ γῶ V²3FsaSp.: ὡς γὰρ S¹ Fν1 35 ἀνάληψίν] ante ψψ una littera erasa V 36 ὅσω V 37 εἷ add. V²aa Sp.
footnote 2 τί δεῖν om. S²B2a Sp.: fortasse ποιεῖν ἐφ’ αὑτοῖς] ἐπ’ αὐτοῖς Sp. ἐπ del. Sp. 4 αὐτὸς] inter ο et ς lit. V εἰ add. V2Β Vict. 5 αἴτιον] ἕκαστον a Sp.: αὐτὸν Schwartz ἕξεως V2SBa  Sρ.: λέξεως V¹FLM 6 τῶν ἀγαθῶν] ῶ et pr. ἀ in lit. V 9 κακὰ] κακοὶ a  Sp. 11 οἳ καὶ scripsi: οἷς libri: οἳ coni. Sp. 12 αὐτοῖς V τε delevi 16 εἰ om. a ποιᾶς Diels: ποίας libri ⟨δεῖ⟩ τῷ a Sp. ἔξοντι V 17 κρίνει a Sp. 19 καὶ αἱ ἀρεταὶ a Sp. 20 αὐταὶ] αυται V1 (corr. V2): αὗται a 21 ὁμοίως ⟨ἔχει⟩ sive ὁμοία coni. Sp. 22 fortasse ⟨ἐπὶ⟩ τῶν 26 fortasse δυνάμενον 27 αὐτοὺς] αὐτὴν a λαμβάνειν] β in lit. V: λαμβάνει a Sp. 33 ante ἢ B iterat titulum usque ad δικαιοσύνη (31)
footnote 1 ἣ] ἢ Sp. ἢ B2Ν: καὶ Va  Sp.: ἢ καὶ F 3 τῷ scripsi: τῶν libri 4 τὰ] τοῦ Vict.: om. 4. 5 ἔχειν—τούτων (τούτὢν V)] οἷον ἐναντίον ἐστὶ τῶν ὧν ἐστι μεταξύ S2B2 a Sp., sed praemissis verbis λείπεται ῥῆμα λείπει (?) ἤ τι τοιοῦτον B² 6 ὄντα VB Vict. Sp.: ἠδόντα FG1: ἰδόντα Sa: ἀεὶ ὄντα N: ἢ εἰ οὐδὲν τὰ G1 et S1 in mg. τῶν a Sp.: τῷ libri 7 εἰ δὲ πᾶν S2B²a Sp.: εἰ πᾶν VB¹: εἴη ἂν S¹F: ἢ εἰ πᾶν Ν 9 alt. ἡ om. a Sp. 10 γίγνοιτο a Sp. 11 ἐν τῇ Ν ἦν, καὶ a Sp. 13 καθ’ αὑτὴν Β2 Sp.: κατ’ αὐτὴν libri σὺν εἴδει S²Ba Sp.: συνείδει V: ἐν εἴδει S¹F τινι τὰ Sp. ἁπλῶς τὰ Ν 14 καὶ ἐκ τῆς στ. a  Sp. 15 ἐκ δὲ τῆς] τῆς δὲ S²B2a Sp. 15.16 τε καὶ μὴ ὑπομένοντος FS1N: τῇ ἕξει εἰς ἣν ἡ μεταβολή S²B²a Sp. ἐκ δὲ— ὑπομένοντος om. B1 (Β2 supplet lectionem, quam exhibent S2a 16 ἶντα a 17 οὐ—τινος om. SFa οἴονται V 18 χωριστὴ VΒ Sp. χωρὶς τῆς SFa: χωριστὰ Vict. τῷ] τὸ Vict. 20 μεταβάλλῃ] ῃ in lit. V 21. 22 ἀε’— εἴδους] ἐν ἄλλῳ τινὶ εἴδει B²S²a Sp. ὁ v 23 αὕτη V: αὐτὴ a  Sp. 24 μεταβάλλουσα a Sp. ἀμείβει] βει s. v. V 25 τὰ] τὰ τα V
