@node
@author=Septuaginta
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Henry Barclay Swete D.D
@filename=tlg0527.tlg035.1st1K-grc1
@funder=Harvard Library Arcadia Fund
@principal=Gregory Crane
@publicationStmt=Harvard College Library, tlg0527.tlg035.1st1K-grc1.xml.
@respStmt=Digital Divide Data, Corrected and encoded the text, Gregory Crane, Editor-in-Chief, Perseus Digital Library, Matt Munson, Project Manager (University of Leipzig), Annette Gessner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig) 2015 - 2017, Bruce Robertson, Technical Advisor
@sourceDesc=The Old Testament in Greek, Henry Barclay Swete D.D, Septuaginta, Cambridge University Press, Cambridge, 1905, 3, The Internet Archive.
@sponsor=University of Leipzig
@title=Psalmi Salomonis
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T14:54:58Z

6646	marginal r
footnote Jnscr ψαλμοί Σολομῶντος l ( μαωνος h) om ir ά om r ψαλμος τω hilmpv Σαλομων ; πρωτὸς i Ι 1 τον θεον] om τον r 5 πολλην lr] πολυν himpv 4 διεδοθη ilr| διελθοι hmpv γην] +και η δοξα οὕτων εως εσχατου τἢν γην r (imprnb r¹) ουτων 2⁰] αυτου l 6 ειπον l πεσωσι in0 πεσωσι μεν l 7 και εγω ir] καγω h)mpv II Σαλομων hilpy doest tit in m 1 κατε-βαλλε ir] κατεβαλε hlmpv r
marginal hilmpv 2 κατεπατουν hilmpv 3 om οι i εβεβξλουν hilmpv 4 απορ-ριφ. hlmpv απερριψ. i ευοδωκεν ilr] ευωδωκεν hmpv αυτου hilprv] αυτης m 5 ἐξουθενώθη ilr] ἐξουθενήθη hmpv om εως hmpv 6 υιοι] pr οι hilmpv θυγατέρες] r αἱ hilmpv εθνεσι hilmpv 7 1γκατελιπεν hilmpv 6 απε-στρεψε himpv om τὸ hilmpv ελεου hilmpv οὕτων 1⁰] αυτου i 10 εβαρυ-θυμησεν ii 11 οσα] ο ex ου fee χcott 12 τα δικ. πανια i 13 εστησεν hmν εστησε p | παραπορευομ. hilmpς 15 εμιαιωσαν] εμιαινον hilmbv εαυτας hilmpς 16 κριμασι hilmpv 17 και iv] om hlmpv
marginal r
marginal §C
footnote 20 ονειδισαν i κατεσπασε hilmpς 22 περιειλετο hilmpς 24 Κυριου]  chilmpv  + του θεου i και 3⁰] καγω ί om Κυριε i χειρα hi (χειρα σου του βαρ. i) lmοpv Ιερουσαλημ hilmpv επαγωγη ilmrp] απαγ. hv 26 επιτιμησῃς hilmpv αυτοις )mprv] αυτους il 27 ζηλω hilmpς αλλα hlmpv 28 εκχεας i om και hilmpv 29 ατιμια hl mpv] αἰτία μία r ἀτμία μια 1 30 εως] + ου i εδειξε himpv 31 διαφερομενον ilr] διεφθαρμενον hmpv 32 εξ. ουδενωσεν chilmpv εστι chmpv 33 ειπειν l (de c non liq) | κραταιος] pr και (? κς) c r
marginal chilmpv 35 ο ανιστων clr] nm ο himpv απωλειαν chilmpv αιωνος] αιωνιον chilmpν ουτων l 36 om του chilmpv 37 Κυριου cmghimprv] αυτου cttxt] 39 αμαρτωλου] + αποδουναι αμαρτωλοις εις τον αιωνα κατα τα εργα ουτων i εποιησε chimpv 40 οσιοις] μετ hmpv ΙΙΙ γ om hv Σαλ ομων chilmpv 1 ουκ ευλογεις] ου λογεις r* 2 και αινον clr] καινον himpv ψαλατε chilpv ψαλλατε m ψαλλε και] φαλαι ι θεω] κυριω i αγα-θης iv] ολης chlmpv 3 μνημονευουσι chilmpv του κυριου (2⁰)] om του chilmpv 4 om του chilmbv εναντιον chcorriilmbv (ενωπιον h*vid) 5 εδικαιωσε chilmpv επεσε climpv
marginal r
footnote 6 σωτηρια] pr η i αυτω c*r] αυτου ccorrhilmpv 7 δικαιου] pr του  chilnpv  chilmpv 9 om αυτου r 10 πανια chilmpv οσιον himprv] θειον cl 11 αμαρτωλος] pr ο i ζωην] pr την i 12 προσεθηκεν ilr] προσεθηκαν hmpv (de c non liq) αμαρτιαις clr] αμαρτιαο himpv 13 πτωμα] σπέρμα i 14 ου μη] om μη chilmpv επισκεπτεται i 15 om η chiimpv 16 om τον chlmpv ουκ] pr και chilmpv IV δ΄ cilr] γ΄ hr διαλογη του cilr] ψαλμος τω hpυ | Σαλομων chiipv ανθρωπαρεσκοις] + τεταρτος i (doest tit in m) 1 καθησαι βεβηλε chilmpv οσιω clr] οσιων i om hmpv 2 κατακρινει cl κατακρινων hmpv 3 ζηλω chilmpv αμαρτωλων] αμαρ-τιων chilmpv εν 3⁰] pr και chilmpv 4 γλωσσα] + αυτου chilmpv r
marginal chilmpv 6 ως ακακος] ωσακκος r 9 δικαιωσαισαν ir] δικαιωσαιαν c δικαιως ειεν l δικαιωσαιεν hmpv οσιοι clr] pr οι himpr δικαιου] pr του i 10 μονον] νομον chilmpv δολου] δουλου r 11 ουτων] αστοῦ i επ οικον cilr] εν οικω hmpv ευσταθεια chlv 12 αδικου chilmpv 13 απεστη cilr] ανεστη hpv οικον cilr] om hnpς 15 ολοθρευσαι hilmpv (de c non liq) (ως αδης clr] ως ο αδ. i om hmpς 17 πενια] pr εν |Inpς om και 2⁰ r λυπαις cilr] οδυναις hmpv εξεγερσις] εγερσις i απορια mp 18 απο-πεσοιεν] ααοπεσοι chilv αποπεσει Imp χειρος mp αυτου 2⁰] + cv ατιμια chilmpv 19 κ pr κενος χερσιν αυτου εισελθοι εις τὸν οικον αυτοι chilmpv
marginal r
footnote 20 μονώσει chilmpv αναληψιν chilmpv 22 οφθαλμους εκκοψαισαν  chilmpv  κορακες] εκκοψειαν κορακες οφθ. ἀνθρώπων chilmpV 26 ηρημωσαν chilmpv πολλῶν ἀνθρώπων | ἀνθρώπων πολλῶν c εσκορπισεν (εσκοπ, r* )] εσκορπισαν εν cihilmpV 24 εμνησθησαν θεου] εμνησθης ανου r απασι clr] πασι hmpv 25 παρωξυνεν r 27 om και 1⁰ chilmpv V έ cilr δʼ hν τω Σαλομων ψαλμος πεμπτος i ψ. Σολομων cl ψ. Σαλομων hpv (doest tit in m) 1 τo ονομα imp 2 ευχρηστος] συ χρηστος chilmpv η cilr] ει hmpv 4 ου γαρ.. δυνατου] om cl σκυλα iv] + ανθρωπος hmpv 6 παρα] απο i σου 10 cilr] σοι hmpv r
marginal ¶i
marginal chilmpv 7 ἀποστρέφῃ lr] ἀποστρέψῃς ὶ ἀποστρέψεις linpς (de c non liq) εἰ ο θεος ημων chilmpv 8 βαρυνεις i 9 αλλα hmpv 11 τρέφεις] + κε cfort ερημοις] pr εν chilmpv 12 πεινασωσι chilmpv αρουσι chilmpv προσωπον ir] προσωπα chlmpς 13 αρχοντας cilr] pr τους hmpv τρεφεις] στρεφεις r 14 ερπακουσῃς r ελεω chilmpv 15 φειδω clr] ηφειδοι i φίλω hmpv και εαν clr] + και himpv 16 ου 1⁰] ουκ r η ελπις επι σε] επι σε Κυριε η ελπις chilmpv 18 αυταρκιας r (-κειας cl)] αυταρ-κεσιας hmpv 21 ευφρανθησαν chlmpv τη βασίλεια] pr εν chlmpv
marginal r
footnote VI ζ c|] έ h om r Σαλομων chl Σολομων r (doest tit in m) 1 επι-  chlmpv  καλεσασθαι cr] επικαλεισθαι hlmpv 4 ορασεων chlmpv σαλων hmpv σαλον clr 6 ευλογησεν l ευλογησε chmpv τω ονοματι clr] το ονομα hmpv 7 ευσταθια] ευσταθεια chlv εξυμνησε chlmpv τω ονοματι clr] το ονομα hmpv του θεου] + αυτου chlmpv 8 εισηκουσε chlmpv | ο κυριος] om ο chlmpv 9 ελεος clr] ελεον hmpv VII ζ΄ clr] ζ΄ hν ¹ Σαλομων chlmpv Σολομων r doest tit in m 1 μισησαντες chlmpv r
marginal chlnpv 7 o συ cl επακουσεις cl 8 απωσῃ chlmpv παιδιας r (θειας hmpV)] παίδεια I(de c non liq) 9 η] ωr VIII clrcorr) ζ΄ hpv θʼ r* |Σαλομων chlpv Σολομων r (doest tit in m) 1 ηκουσε chlmpv τo ους μου] η ψ υχη 7 οδους] δους r 8 ανακαλυψεν r εγνωσαν cl 9 καταγαιης l κρυφοις c VIII 11 την γυναικα] om την clulmpv 12 διηρπαζον chlmpν ως μη] ουκ chimp
marginal r
marginal §i
footnote 13 επατουν chlmpv ακαθαρσιας] θαρσ sup ras r εμιαινον clilmpv  chilmpv  14 παρελιπον chilmpv 15 αυτους cilr] αυτοις hmpv 16 ηγαγε chmpv om τον 20 i 17 εκρινε chilmpv 18 ειπον hilmpv εισελθετε chilmpv 19 ομαλισαν i αυτου ilr] ουτων hmpv 20 εστησε chimpv post ποδας 2 vel 3 lilt ras r μετ i 22 ο θεος] om ο chilmpv 23 πανια chilmpv εξεχεε chimps 24 απηγαγε chilmbv α] ας chilmpv εγεννησεν m 26 εμιαναν chilmpv 27 εθνεσι chilmbrcott v 29 om γην εν i 30 ειδον chilmpv 31 ημων cilr] ουτων hmpv 32 την δικαιοσυνην r 34 Ἰλημ c* μετα cr] ttετ hilmpv ελεου Cc Corr hilmpv (παιδ incep c*) r
marginal chilmpv 35 πιστις] pr η chilmpv τραχηλον] pr τον chilmpv 36 καταπιη chilmpv om ως chilmpς 37 η ελπις ημων] ηλπισαμεν chilmpv 38 εις] εφ chilmpv 39 η ευδοκια] om η cl η ευδ. ουτων i Κυριος c 40 στο-μασιν ι και] + συ hmpv IX τω Σαλομων εις νικος ψαλμος θ΄ και εις ελ i Σαλομων chilprv (doest tit in m) 1 Ιερουσαλημ i αποικησια hmp 2 απερριφησαν chilmpv ο κυριος i η διασπορα cilr] επι διασπ. hmpv 3 om τη i 5 αδικα] κακα chilmpy 6 om αι cl 7 εργοις] pr εν chlmpv
marginal r
footnote 9 εαυτω chiimpv αδικα hmpv 11 χρηστευσει cl χρησιμεύσει i  chilmpv  12 εξηγοριαις chlmpv 13 παντων i 14 αφεσει r ημαρτηκοσιν l 15 ημαρτον chilmpv 16 om σου 1⁰ cltilmpv οικτειρον chilmpv ελεον chilmpv 18 καταπαυσει cil καταπαυσῃ |hmpv τον αιωνα] pr εις chilmpv 20 ελεημοσυνη] pr η hilmpv επι chilmpv Χ εν υμνοις] υμνος chilpv |τω Σαλομων chilpv + ψαλμος ί i (doest tit in m) 1 καθαρισθηναι] pr και chlmpv 2 om και chilmpv om γαρ cl υπομενουσι chilmpv 3 δια-πρεψει] διαστρεψει chilmpv 4 μνησθεται chilmpv r
marginal chilmpv 5 γαρ cilr] om hmpv 6 Κυριος] ο κυριος clilmpv κριμασιν] pr εν i | το ονομα |hmpv Κυριου] + εις τον αιωνα i 5 δοξασουσι chlmpv δοξα-σωσι i 9 επ chilmpv σωφροσυνην hmprv] ευφροσυνην cil XI 1 Σαλ. ωμων |] Σαλομων hipv Σολομων r (doest tit in m) 2 ελεησεν i | Ισραηλ] pr εν tmpv αυτου i 3 om τα i om εις i απο 20] υπο cthilmpv 5 ορη] ὄροι i 6 εφυγον chilmpv δρυμοι] βουνοι c εσκιασαν] εσκιρτησαν mp 7 orm θεου i 8 αγαθα εις τον αιωνα και ετι Ισραηλ c corr| (οιη pro Ιηλ c*) 9 Ιερουσαλημ| pr εν hlmpv om το cl
marginal r
footnote XII Σαλομων chipv (doest tit in m) 1 δολερα | πονηρα c* 2 ποι-  chilmpv  κιλια στροφης ir] ποικ. τροφης cl ποιησει διαστροφης hmpς λαω cilr] αλω Imv αλλω p καλλονην cilr] καλαμην hmpv 3 φευδη i παρανομου himpv 4 συγχεαι chilmpv παρανομους οικους hlmpV χειλεσι chilmpv ψιθυρων i κακων mp σκορπισθειη chilmpv 6 φυλαξοι] pr συγχααι οικους και r om Κύριος...κατευθυναι r ανδρος ποιουντος r 7 παίδων i 8 οσιοι] pr οι ci κληρονομησαιεν ch(i)lmpv επαγγελιας] + Κυριου chilmpv XIII ιγ | τρεις και δεκατος i Σαλομων chipv om ψαλμος cl (doest tit in m) 1 εσκεπασε chilmpv 2 βραχιων] ω sup ras r 3 επεδραμον hilmpv | επιλλον hilmpv μυλαις] + ουτων hlmpv οστα] pr τα i ο κυρωως ci r
marginal chilmpv 4 παραπτωματα] pr τα chiimpv 5 om η chilmpv δικαιου] pr του cl εκ παντων τουτων ουδεν hilmpv 5-6 om ουδεν...αμαρτωλου cl 6 των αμαρτωλων himpv 11 φοβουμενους] + αυτον chilmpv X IV ψαλμος 1δ i Σαλωμων lr] Σαλομων chipv (doest titin m) 1 υπομενουσι chilmpv πορευομενοις] + εν ακακια και i ω cl] om r ως hmpv ον i 2 του κυριου] om του chilmpv 3 κληρονομια clr] pr η himpv Ισραηλ cilr] pr ο hmpv 4 η επιθυμια cilr] εν επιθ. hmpv
marginal I
footnote 5 του θεου] αυτου c om l ταμεια (ταμιεια ch(i)lmpv)] pr τα c(i)l 6 ελεου  chilmpv  chilmpv κληρονομησουσι chmpv XV om τω cl Σαλομων chipv μετ ωδης hipv om cl (desttit in m) 1 βοηθειαν] pr την i ηλπισα] εσωθην r 2 συ] + ει i 3 τι i om σοι i 5 καινον ilr] και αινον hmpv μετα] chilmpv απαρχη cl απαρχης i 6 om οργη c 7 επι chilmpv ολο-θρευσαι chilmpv 8 μακραν απο δικα8ων chilmpv 9 διωκομενου chmprv πολεμου (cmniec Gebhardt)] απο λιμου ir λιμου clhhlmpv καταδιωξεται chilmp καταληψεται chilmpv Κυριου himprv| του θεου cl καταληφθῇ σονται hilr corr καταληφθησηται c 11 ανομιαι] pr αι chilmpv κατωτατου i 12 ουχ ευρεθησει sup ras r r
marginal §c
marginal chilmpv 13 αι] και i] αμαρτιαι] ανομιαι chilmpv εξερημωσωσιν r αμαρτωλοι] pr οι hlmpv 14 αυτου] + αποδουναι αμαρτωλοις εις τον αιωνα χρονον hmpv 15 om και αμαρτωλοι... χρονον hmpv απολουνται αμαρτωλοι i απολ. οι αμ. cl XVI μνος cilr] ψαλμος hpv Σαλομων chipv om οσιοις hpv (deeλt tit in m) 1 ωλισθησαν l υπνωσα i om εν cl καταφθορα climv 2 τω μακραν] το μ. γενεσθαι i 3 Κυριος] θεος i μου 2⁰] + εις σωτηριαν i 4—5 om ενυξεν...εις σωτηριαν i 4 ενυξε chimpv εσωσε chIimpv 5 αντελαβετο r 6 om πει chilmpv καρδιας] + μου chilmpv 7 8 om απο αμαρτιας... και 10 i 10 αλογον] ν sup ras i 11 om γογγυσμον...εμου l
marginal r
footnote 12 στήριξον hlnpV om εν τω ενισχυσαι σε την ψ. μου l 13 εν πενια  hilmpv  παιδειαν hmpv* 14 αυτου 10 ir] αυτης hlmpv XVII Σαλομων hibv μετ hilpv (doest tit in m) 1 συ] + αυτος hilmpv βασιλευς] + εις τον αιωνα ο θεος i ημων 1⁰] + και i om ημων 2⁰ hilmpv 3 ελπιζομεν i τον θεον τον σ. | θεον τον σ. himpv ελεου hilmpv 4 εθνη] + εν κρισει hilmpv 5 επι] εν l σπερματος] + αυτου hilnpv εκλιπεῖν il σου] το l 6 ημιν 1⁰] ημων i υπεθεντο i εξωσαν hilmpv om ουκ l μετα] pr και i αφειλοντο hilmpv 8 ερημωσαν i αλαλαγματος hmpv σπερμα] pr το hilnmpv 10 ευρεθειη hmpv r
marginal hilmpv 11 ουκ 1⁰] pr κατα τα εργα ουτων hilmpv (om ουκ hmpv) εξηρευνησε himpv ουτων ενα ilr] αυτους hmpvv 12 κυριος] θεος i εποιησεν i 13 ερημωσεν i ανομος ilr] ανεμος hmpv om επι hilmpv τεκνα] pr τα i 14 ουτων i 15 εποιησε i εν υπερηφανια iv] υπερηφανιαν hlmpv του θεου om του i 16 τοις θεσις hilmpv 17 επεκρατουν hlmpv απεκρατουν i |υιοι pr οι hiimpv εν μεσω εν αυτοις εν] εν αυτοις εν μεσω hiimpv 18 εφυγον -hiimpv απο τουτων l om οσιων l εξεπετασαν l 20 om εφυγοσαν.. οσιων hilmpv σκορπισμος] pr ο hilmpv ενεσχεν i της γῆς i 21 αυτου i 22—23 ο βασιλευς ... υιον Δαυιδ post εις τον καιρον...παιδα σου pos i 23 υιον] υῶ r ειδcς i| ο1δcς hv οιδας mp om επι l
marginal r
footnote 26 εξωσον il αμαρτωλοα lr] αμαρτωλῶν i αμαρτωλους hmpv ως] εν i  hilmpv  συντριψον i 27 om εν απειλη...προσωπου αυτου mp 28 συναξαι i 29 ετι ilr] om hmpv 30 ουτων εισιιν) (h)il(mpv) της γῆς] om της i 31 αυτοις] pr εν l om διαψαλμα m 32 τον ζυγον] om τον hilmpv 33 καθαρισει himpv 34 ερχεσθε il 35 δικαιος] + και p 36 om οτι παντες...χριστος κυριος i 37 εφ ιππον i ουδε 2⁰] και hit 38 του] αυτου r r
marginal hilmpv 39 καταξει ir] παταξει hlmpv αιωνα] pr τον i 41 λαου μεγαλου hilmpv 42 κατειργασατο hilmpv δυνατον] δυναμιν l om i μετ hmpv δικαιοσυνην r 45 αφησοι i ουτων] αυτω l 46 ισοτητι ilmgr] οσιοτητι hltxt mpv αυξει p 47 Ισραηλ 1⁰] Ιερουσαλημ i 48 τιμιον το πρ. hilmpv λαους hilmpv ηγιασμενου iv] ηγιασμενων hmpv ηγιασμενους l 49 ουτων r Οm ως i 50 γινομενοι hilmpv Ισραηλ] Ιερουσαλημ i ποιησαι (ποιῆσαι) ilr] ἀ ποιήσει h 51 ρυσαι l X VIII Σαλομων hipv ετι ir] επι hlpς (doest tit in m) 2 om η i επι 1⁰] μετα hilmpv επιβλεπουσιν l
marginal r
