@node
@author=Soranus
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=no feature metadata have been provided; look at the name of the feature and at the data itself to get some clues
@editor=Johannes Ilberg
@filename=tlg0565.tlg004.1st1K-grc1
@funder=Harvard Library Arcadia Fund
@principal=Gregory Crane
@publicationStmt=Harvard College Library, tlg0565.tlg004.1st1K-grc1.xml.
@respStmt=Digital Divide Data, Corrected and encoded the text, Gregory Crane, Editor-in-Chief, Perseus Digital Library, Matt Munson, Project Manager (University of Leipzig), Annette Gessner, Project Assistant (University of Leipzig), Thibault Clérice, Lead Developer (University of Leipzig), Bruce Robertson, Technical Advisor
@sourceDesc=Sorani Gynaeciorum Libri IV De signis Fracturarum De Fasciis Vita Hippocratis Secundum Soranum, Johannes Ilberg, Soranus, Teubner, Leipzig, 1927, 4, Corpus Medicorum Graecorum/Latinorum.
@sponsor=University of Leipzig
@title=Vita Hippocratis Secundum Soranum
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T15:04:28Z

836	footnote 1 Siepan. Byz. s. v. Κῶϲ; Suid. s.u Ἱπποκράτηϲ; ?? Cl?? VII 155 sqq.; ῾Yppocratis genus tita dogma' in cod. Bruxellensi 1342–1350 (ed. Schoene, Rh. Mus. LVIII 56 sqq.) 4 ἀφ οῦ μὲν εἰκοϲτόϲ] ab Hercxle per Phaenare-?? matrem a Praxithea ut tidetur Therpiade ortam (Epist. 2. IX 314 L. Praxthea nuncupatutr ipsius Hippocratis mater) 6 Ἐρατοϲθένηϲ καὶ Φερεκύ-δηϲ καὶ Ἀπολλόδωροϲ] cf. Iacobn, Apollodors Chromik p. 295 sqq.; F Gr Hist I F 59 p. 409 6 sq. Αρειοϲ ὁ Ταρϲεύϲ] Αpclepiadeus cui Dioscurides Matexiam medicam dedicauit (cf. Diels, Doxogr. Gr. p. 87, 3) 8 Ἡροδίκου] Cnidium vide-tur dicere, non Selymirianum (cf. Diels, Anongm. Londin. p. 115) 17 Ἀνδρέαϲ] cf. Soran. Gyn. IV 1,6; Galea. Submgur,cmp.53, 11 Bounet 18 ἐμπρῆϲαι . . . υρομη.] idem de temple Coo ex Varroxe Plin. Nat. hist. XXXVI 4; cf. Tietses, Chit. VII l. c. 1 Γἐνοϲ καὶ Βίοϲ Ἱπποκράτουϲ κ. c U E: ιπποκρατουϲ βιοϲ κ ϲ. β 3 τῶ γι HFIJ: τὸ γένοϲ RUEβ ἡρακλείδα superscript. M φαινερέτηϲ β 5 ιθ Μ : ἐννακαιδϲκαταῖοϲ RUEβ (ἐνεακ.) in mg. τὸ λεγόμενον πολύϲτυ-λον R (τ. λ. π.εἰϲ [?] τὴν ϲιταρᾶ ad υ.10 man. rec. F) spectant fort. ad 18 7 ἡρακλείδα superscript M ιδίου adiec Μ 2 in mg. et ceteri ex ?? posteriorum: sustuli 8 Γοργ[ν]ου erasa ν littera Μ : γοργίνου l: γοργί?? (in ras.) F 9 〈τοῦ 〉 Ἄβδηρ. Westerwann 10 ιϲτόμαχοϲ libri: corr C. Keil, Zs. f. Aw. LII 265; cf. Sehoene. Rh. Mus. LVIII 58 sq. 12 ἀνερευνήϲνϲα HIJ 13 ἀγπιάδο β Ἀγριανίου C. F. Hermann (cf. Real -Encycl. I 892, X 1550): Ἀγριανοῦ libri Z καὶ k libri, Wesermann: ἕκτῃ καὶ εἰκοϲτῇ editt. ceterae 14 θυϲιάζειν suprα ἐναγίζειν F 2 ἐν αὐτῇ om. β 16 ἰδίαϲ adiec. M 4 in mg. εἰ ceteri: sustuli 18 τὸ om. β
footnote 4 ὑπὸ Περδίκκα] similia narrnatur de Cleommbroto sive Erasistrato An-tiochum sanantihum Plin Nat. hist. VII 123, XXIX 5 (cf. Welimann, Herm. XXXV 380 sq.; Mesk, Rh Mus. LXVIII 366 sqq.) 11—13] cf. Abderitarum epistula (10) IX 320 sqq. L. 13 —18] ex oratione Thessali (Πρεϲβευτικὸϲ) IX 418 sqq. L. 13 Ἰλλυριῶν] Plin. Nat hist. VII 123 18 —23] cf. Eptstulae 1 — 9 IX 312 sqq. L.; 400 sq (Δόγμα Ἀθην.) 23 ἐπιϲτολῆϲ] scil. Epi n="5 (IX 316 sq. L.) 23 —24] cf. oratio Hippocratis ad Thessalos (Ἐπιβιώμιοϲ. IX 402 sq L.), item Thessali filii ad Athenienses (Πρεϲβευτικόϲ, IX 404 sqq, 426) 1 ὅτι om. β κατὰ τόπουϲ τὸ libri (τὰ om HJ2): τὰ κατὰ τόπουϲ editt. 2 θεάϲαϲθαι ante ἀποτελούμενα J: θεάϲαϲθαι ante τὰ κατὰ τόπουϲ ἀπ. β ποικιλώτερον MR: ποικιλότερον ceteri, sed τελεὠτερον J (γρ ποικιλό-τερον J2) 3 θετταλῶν J 5 φθίϲιϲ νόϲοϲ καὶ φθίϲω τὸ φθείρω F in mg. παρακληθέντα M: παρακληθέντοϲ ceteri (corr. F): ante παρακλ. add. καὶ R 6 δημοϲίωϲ β 8 om τοῦ 8 φίλαϲ U E β J 9 αὐτοῦ] ἐκείνου J. δηλώϲαϲ H γεγονὸϲ M 2. τένοϲ (libri ἔπειτα R E H β1 (corr. β2) I J παραφυλάϲϲω τὸ προϲδοκῶ F mg. 10 τέρπεϲθαι R1 E2 β καὶ λῦϲαι R 11 τῶν add. M et ceteri πρὸϲ ὡϲ ceteri (suprascr. εἰϲ Η) 13 λοιμο om. β Παιόνων editi.: πλειόνων libri 14 ϲκῆψιϲ ἡ πρόφαϲιϲ ἢ φροντί ἡ ἀναβολή in mg. F 17 ἐπὶ] εἰϲ J 18 τοϲοῦτο H I J 19 ὑπῆρξεν M. ὑπῆρχεν ceteri διαπτὐϲτου M: πύϲτιϲ ἡ φήμη in mg. P 20 καὶ τοῦ in ras. F editt.: παρὰ libri (del. β) Ὑϲτἀνουϲ scripsi coll. Hippocr. IX 316, 315 L.: ὑϲτάνιδοϲ libri 21 δεομένου post δωρεοῖϲ M, post ὑπάρχου ceteri 23 ἑαυτοῦ M: ἰδίαν ceteri 24 ὑπό τῶν β 25 〈οὐ〉 παρὰ Κῴοιϲ 〈μόνον〉 Westernn
footnote 1—3] cf. IX 402 L. (Δόγμα Ἀθην) 42 (Πρεϲβευτικόϲ; Phin. Nat. hist. VII 123 4 Ὅρκου] IV 628 — 632 L. 1 αὐτὸν om. υ, in mg. add. U2 ὑφ᾿ ἡρακλ. UE 2 ἐμύηϲαν] supraser. ἐδίδα??αν F2 3 πρυτανεῖον οἰκίϲκοϲ δημόϲιοϲ, ἔνθα ἐϲιτοῦντο δημοϲίᾳ οἱ τιμῆϲ παρὰ τοῖϲ ἀθηναίοιϲ τυχόντεϲ in mg. FJ 5 ὅτε καὶ δημόκριτοϲ 5 M: καὶ om. ceteri τελευτῆκαι β 6 γενέϲθαι φαϲὶν J ὁγδ. καὶ π., item ἑκ. καὶ τεϲϲ. et ἐκ. καὶ ἐνν. β 7 τινἑϲ] καὶ ἕτεροι J ἄλλοι β 8 ϲμῆνοϲ ἦν Μ: ϲμ. ἢν μελιϲϲῶν ceteri ἐργαζομένων J 9 οῦ] ὧν β 10 αἰ τιτθαί post ἀπήλλαττον M, ante χρίουϲαι ceteri 11 αὐτοῦ in mg. M?? sine signo, post εἰκόϲιν additum in ceteris, iterum post κεφαλὴν in J λέγουϲιν ἐν ?? (ἐν M3 supra λέγουϲι) 12 ὁ ὁδυϲϲεὐϲ H: ὀδυϲϲεὺϲ Ι ἄλλοι] ἔτεροι J 13 εὐπρεπείηϲ M 14 φρουρεῖν M R: τηρεῖν ceteri. ζητεῖν J (in mg. manu rec. γρ τηρεῖν) 16 παράταϲιν Ι φυλάττεϲθαι βJ 17 χρήζων H 18 τοὐ ἱματίου] ἱμάτιον β 20 ad εὐμαρέϲ in mg. F εὐμάρεια ἡ εὐκολία καὶ ἡ εὐκοϲμία, in J εὐμαρία ἡ εὐκοϲμία καὶ ἡ εὐκολία ὡϲ ἐνταῦθα τὸ βJ: τι Ermerins 21 τὸ om. Ι, add HF1 ἐπιϲκοτεῖν UEβR2F2J2: ἐπιϲκοπεῖν MR1HF1IJ1?? supra ἐμπποδζειν P post πρῶτον add μὲν β 22 τὸ δύναϲθαι add J2 τηρῆϲαι Ml2J1: τηρεῖϲθαι RU EH β F1I1J2: τηρεῖν F1 23 διὰ τὸ τὸν βJ ποτὲ] ἄλλοτε J ἄλλοτε δ᾿ οῦ J: ποτε δὲ 8 β: ὅλλοτε δὲ Westermann. 24 μετὰ τούτων om. M 25 ἔϲτιν om. libri: add. M1F2. ἔϲτιν αἰτ. εἰπ. β § 14 ex superioribus §§ 6 — 10 coflata redactort debetur, posteriori fortasse καθάπερ εἴρηται p. 178, 2 καὶ ante τ. τρόπ. om. U τοῖϲ τρόποιϲ M: τὸν τρόπον ceteri
