@node
@author=Scholia In Sophoclem
@availability=Available under a Creative Commons Attribution-ShareAlike 4.0 International License.
@convertor_author=Ernst Boogert
@convertor_date=July, 2020
@convertor_execution=Ernst Boogert
@convertor_institution=Protestant Theological University (PThU), Amsterdam/Groningen, The Netherlands
@convertor_version=1.0.0
@description=open tag without further specification. See the name of the .tf-file for it's meaning
@editor=Petrus N. Papageorgius
@filename=tlg5037.tlg004.1st1K-grc1
@funder=Harvard Library Arcadia Fund
@principal=Gregory Crane
@publicationStmt=Harvard College Library, tlg5034.tlg004.1st1K-grc1.xml.
@respStmt=Digital Divide Data, Corrected and encoded the text, Gregory Crane, Editor-in-Chief, Perseus Digital Library, Matt Munson, Project Manager (University of Leipzig), Annette Gessner, Project Assistant (University of Leipzig) 2015 - 2017, Thibault Clérice, Lead Developer (University of Leipzig) 2015 - 2017, Bruce Robertson, Technical Advisor
@sourceDesc=Scholia in Sophoclis tragoedias vetera, Petrus N. Papageorgius, Scholia in Sophoclem, Teubner, Leipzig, 1888, Internet Archive.
@sponsor=Harvard College Library
@title=Scholia in Sophoclem (scholia vetera)
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2020-12-11T15:11:29Z

87742	error Λαρτίου
error πεῖραν
error ἐχθρῶν
error ἴχνη
error ἄποπτος
error ξυναρπάζω
error σακεσφόρῳ
error ἀλώμεθα
error ἐφήκεις
error παρέστη
error τέρμ᾿
error πύλαις
error μαιμῶσαν
error ἄδαστα
error ἔχων
error ἐμπίπτων
error κακὰ
error ἐλώφησεν
error τἀνδρὶ
error ὀκνεῖς
error σε;
error ἐννοεῖς
error ἐποικτείρω
error εἴδωλʼ
error χειρὶ
error πράσσοντʼ
error ἐπιχαίρω
error ὅταν
error ζαμενὴς
 ἢ ἐπὶ ἵπποις μαινόμενον
error αἴθωνι
error πείθει
error ῥῦμα
error πύργου
error ἀνοήτους
error ἀπαλέξασθαι
error φάτις
error ἐλαφαβολίαις
error ὑποβαλλόμενοι
error κλέπτουσι
error ἀσώτου
error ἄρῃ
error ἀτάρβητα
error καγχαζόντων
error βαρυάλγητ᾿
 σου
error κλῃζομέναν
error περίφαντος
error θανεῖται
error παραπλήκτῳ
error ἱππονόμους
error μὲν
error πλευροκοπῶν
 ἡμῶν
error μεθεῖναι
error τοίας
error δικρατεῖς
error ἑ.
error ξυναλγεῖν
error ἄπλατος
error φρούδου
error λόγος
error οἰομανίαν
error φρονοῦντας
error πεπαυμένος
error ἐχόντων
 καὶ
error ἦθον
error ἐμαίετʼ
error κενὰς
error ἐπιπλήσσω
error πεῖραν
 οὔτε
error ὑμνούμενα
error ηὐχένιζε
error φῶτας
error ἡμεῖς δὲ μεμαθήκαμεν
error ἀνέσπα
error ἐρειφθεὶς
error κυροῖ
error σιδηροκμῆσιν
error εἶ;
error ἐν χειμῶνι γέγονας
error ἀφροντίστως
error ναΐας
error ἐλίσσων
error ἀφόβοις
error ἐξειργασμένοις
error ὄργανον
error ἄλημα
error ἀτώμενος
error εἴπῃς
error ὄνησιν
error ὀλέθριον
error μὲν τὴν
error ἄγραις
error ἐπάκτιον
error ἔχοντα
error τοῦτο
error εὔφρονες
error μέγα
error ἔχω
error ἑ.
error ἀρκέσας
error Ἀργείοισιν
error τοσοῦτον
error ἀδάματος
error αἱμάξαι
error ἑκόντος
error ἐχθαίρομαι
error ἕδρας
error γυμνὸν
error ἔρυμα
error ἄσπλαγχνος
error θερμαίνεται
error καλῶς
error ὡς
error χειρὶ
error σὰ
error συνηλλάχθης
error ἰάπτων
error Αἴαντος
error τρέφει
error δαίμων
error κληροῦχον
error φύσαντα
error θανασίμους
error τίκτουσ᾿
error μνῆστις
error εὐθύνων
error αἶρʼ
error πωλοδαμνεῖν
error ζηλοῦν
error πνεύμασιν
error ἔμπα
error τηλωπὸς
error θήραν
error ἀγωνάρχαι
error ἐμὸς
error ἐπισκήνους
error πύκαζε
error ἐπῳδὰς
error τομῶντι
error πήματι
error κρῖνε
 λέγειν
error ἀκούουσιν
error —;
error μαλάσσου
error δοκεῖς
error φρονεῖν
error Ἰδαίᾳ
error ἐλπίδ᾿
error ἀνύσειν
error ἐξεπέμψω
error εὕρηται
error μέγιστʼ
error λευκῷ
error αἴλινον
error ὀργαῖς
error ἔθρεψεν
error τοῦδε
error μακρὸς
error κρύπτεται
error ἁλίσκεται
error φρένες
error τότε
error ἐξαλύξωμαι
error ἔγχος
error ἄδωρα
error δεινὰ
error κύκλος
error ἀρτίως
error ὠφελεῖν
error λιμὴν
error τέλους
error τιμᾶτε
error ἅμα
error εἶμ᾿
error ἀνεπτάμαν
error ἰάψῃς
 τοῦτο
error εὔφρων
error πελάσαι
error θοᾶν
error πάνθυτα
error ἐξήνυσεν
error φλέγει
error ἀναύδητον
error μετανεγνώσθη
error Ἀτρείδαις
error Μυσίων
error κρημνῶν
error διεπεραιώθη
error λόγου
error νέοισιν
error ἐγκαταζεύξας
error ἰοὺ
error ἢ
error ὑπεσπανισμένον
error χόλου
error τοσοῦτον
error κἀπέσκηψε
error περισσὰ
error οἴκων
error κράτος
error κείνων
error ἵστω
error ἀστεργῆ
error ἐπιστολὰς
error θροεῖ
error τοῦτο
error ἀτρύτων
error ἤλγησ᾿
error τῷ;
error πάρεστʼ
error φέρειν
error ἀντηλίους
error χάριτος
 περί τινος
error θηγάνῃ
error περιστείλας
error εὐσκευοῦμεν
error τῶνδε
error νεορράντῳ
error προστρέπω
error πομπαῖον
 ἀντι
error ἐπίσκεψαι
error γένος
error θροεῖ
 οἷον
error φιλοπόνων
error ῥυτῶν
error ἀπύοι
 τλήμων
error τλήμων
error συνναύταν
error πηκτὸν
error κατηγορεῖ
error αἱμάχθης
error κωφὸς
error δυσώνυμος
error παμπήδην
error συγκαθαρμόσαι
error ἔμελλες
error ἐξανύσειν
error φαέθοντ᾿
error ἄρχων
error ἀριστόχειρ
error γενναία
error ἀρτίου
error δοκεῖν
error σκοποὶ
error ἄχει
error φυτεύει
error μαινομένοις
error κλύοντες
error περισπερχὲς
error ὑπεστέναζον
error ὄμμα
error ἀνίας
error κακὸν
error γεγῶτα
error σὰ
error οὐδὲν
error λόγοισιν
error πρισθεὶς
error δωρεὰν
error κἀκεῖνον
error ἐκεῖνα
error πάρεστιν
error ἔχει
error ἐμοὶ
error δορὶ
error χλωρὰν
error παρευθύνοντες
error ἦ
error σὲ
error ἄλλων
error κόλαζ᾿
error με
 με
error καλῶς
error ἄνδρʼ
error ὀργὴν
error τῦδε
error προστρόπαιος
error θησαυρὸν
error πολυπλάγκτων
error δορυσσοήτων
error Τροίαν
error πόνων
error ὄτοβον
error ἐννυχίαν
error ἐρώτων
error πρὶν
error Σουνίου
error αἰχμαλωτίδος
error διωμόσω
error ποίου
error ἔοιγμεν
error βαλεῖτε
error λελειμμένοι
error ὄπισθεν
error φάρμακον
error ἀνδρὸς
error ἑρκέων
error ἑδωλίοις
error αὐτὸς
error ἄνδῤ
error ἐλλοῖς
error αἵματος
error συγκειμένους
error ὑπερπονουμένῳ
error προδήλως
error ἔμπας
error ς
error ἔψευσας
error οὑπιβρόντητος
error ταχύνετε
error ἐπίκαιρον
error κλισίας
error ἴλη
error ὑπασπίδιον
error σύριγγες
error στρατηγήσαντος
error πολυχρύσους
error πολύφθορον
error ἤνεγκα
error ἑ.
error δεινοῖς
error ἕπῃ
error χρῇ
error αὐτὸν
error οὖν
error ἐφίετο
error χαλκόπλευρον
error κλέπτοντες
error ἀρχέπλουτον
error ὁ καιρὸς
error κἀνακούσωμεν
error ᾔσθου
error ὑπολειφθῇ
error τὸ
error ἀρὰ
error με
error σωκῶ
error τάκεις;
error ἀθεωτάτας
error ἀπάταις
error γενναίων
error γενναίων
error παγκοίνου
error ἐφίῃ
error θεὸν
error πετραίῳ
error οἰχνῶ
error μυδαλέα
error ἀνήνυτον
error ὑπεραλγῆ
error Κρίσαν
error βουνόμον
error προφυτεύσαντες
error ἄχθη
error χεροῖν
error ἀγλαίας
error πολέμους
 τοῖς
error πλάθειν
error τίνι
error ἄνετε
error κακότητος
error αὐτοφόντην
error τλήμων
error ἔμμην᾿
error κἀπικωκύω
error ἐπωνομασμένη
error δύσθεον
error ὑλακτε
error κλεινὸς
error οὔσας
error κάρτα
 πρὸς
error κασιγνήτου
error μέλλοντος
error ματαίῳ
error μέλειν
error μῖσος
error ἐκτρέπεις
error κακῶς
error ἐπαρκούντως
error λυπεῖν
error καλοῦ
error πως
error μύθων
error μακρῶν
error γόων
error κατηρεφεῖ
error κενὴ
error σμικρῶν
error ἐφέστιον
error πατρὶ
error πεῖραν
error γένυς
error τὸ πολύπους ἐν ὑπερβολῇ ἔθηκεν
error τέρας
error δεινοῖς
error θεσφάτοις
error κατασχήσει
error αἰκίαις
error πρόρριζος
error φίλους
error τῆσδε
error παρεῖτο
error ποινὰς
error ἐξεκίνησεν
error ἂν
error ἂν
 τοῦ μένους
error εἰσορῶ
error ἄτερ
error πάγκαρπ᾿
error προστατήριε
error βάξιν
error εὐημεροῦσαν
error ἐδεξάμην
error ζυγωτῶν
error κἀκεῖνος
error καὶ τὰ ἱππικὰ φρυάγματα
error φρυάγμαθʼ
error τὸν
error ἄστομοι
error παρασπᾷ
error κἀξισώσαντε
error λύων
error χνόας
error λαγχάνει
error σποδοῦ
error προστατῶν
 ὅλως
error ἕκηλοι
error ἐδάμη
error μελέτωρ
error πένθει
error πανσύρτῳ
error παμμήνῳ
error παραγάγῃς
error κοινοτόκων
error ὁλκοῖς
error λώβα
error κέκευθεν
error ἰδεῖν
error ἀρχαῖον
error γάλακτος
error ἐστὶν
error πατρὸς
error νεώρη
error ὄμμα
error τόδε
error τἀπιτίμια
error κῦρος
error φέρει
error δυσχερὴς
error Ὀρέστου
error φερέγγυος;
error εὐτυχεῖ
error ξυνοίσω
error πράκτορʼ
 ἀρσενικοῖς
error φόνου
error τούτω
error ἐτύγχαν᾿
 φησὶ
error ἀπορρεῖ
error ποτὲ
error μοι
error πάλιν
error μεθέψομαι
 καὶ
error Ατρείδαις
error Ἐρινὺν
 καὶ κοινὸν
error Διὸς
error ἱστορῶ
error ἀζήμιος
error δίχα
error κύτει
error μοι
error ἐπισκοπῶν
error ἐγὼ
error τῷ
error τῇδε
error δίκης
error τεθνηκότος;
error σὸν
error ἠσκημένον
error σφραγῖδα
error φθέγμ᾿
error σωμάτων
error ἐχρῄζετε
error ἀνέφελον
error καταλύσιμον
error δίκαια
error τόδε
error μακρὰν
error ὑπερτέραν
error χάριτος
error ἄλλοισι
error μοι
error ἐγγενὴς
error τοιούτοις
error ταῦτα
error ἐφέξετον
error χερὶ
error ἔχω
error τἀπιτίμια
error ἀπὸ
error κακόν
error ἑδώλια
error αἷμα
error τάφον
error Ἠλέκτρας
error ἔρημοι
error ζῶσιν
error ὑπεξαιροῦσι
error Αἴγισθον
 ἂν
 ἂν
 ἂν
error με
error θανοῦσιν
error μικρὸν
error ἔα
error ταφεῦσιν
error τόδ᾿
error τάσσε
error ἱερεὺς
error σαλεύει
error σκήψας
 τὰ
error βίου
 τὸ
error προσθήκῃ
error πᾶσιν
error ζώσας
error προθυμίας
error ἴσος
error γὰρ
 ἂν
 ὅτι
error χειμάζον
error ἐπιστέλλει
error δυστέκμαρτον
error ἐκφεύγει
error ῥώμῃ
error ἐπιστροφὴν
error τιμωροῦντα
error ἵστασθε
error κτῆρας
error ἐξαγγέλλεται
error πάλλων
error πάλλων
error Παιὰν
error νέον
error ἐξανύσεις
 τε
error σὲ
error Διὸς
error ἄτας
error ἠνύσατ’
error ἐκτοπίαν
error πήματος
error στόλος
error ἱκτῆρες
error Ἀμφιτρίτας
error ἐνδατεῖσθαι
error μονόστολον
error αἰτεῖς
error ὑπηρετεῖν
error λόγου
error πραχθέντος
error δαίμονι
error δεδρακότ᾿
error ἄμοιρον
error θεοῦ
error θεήλατον
error δυστύχησεν
error δρῶσιν
 κατὰ
error κωφὰ
error χθονοστιβῆ
error ταῦτα
error ἄθυμος
error φάτιν
error ἰὸν
error αὐτὰ
error προσαυδᾶν
error τρέφω
error νῦν
error πρὸς Τειρεσίαν
error σοι
error ἐκπρᾶξαι
error μέλει
error πιστὸς
error ἑαυτοῖς
error ἀγύρτην
error τοὐπιόντος
error κυρήσας
error ἐξισωτέον
error τοῦδε
error γεγράψομαι
error ἀμφιπλὴξ
error καταίσθῃ
error σχολῇ
error αἰνικτὰ
error τύχη
error ξυμφορᾷ
error ὁμόσπορος
error ἀρρήτων
error ἀελλοπόδων
error πάντα
error οἰωνοθέτας
error ἀποφάσκονθ᾿
error βασάνῳ
error Οἰδιπόδα
 καὶ
error ἡδύπολις
error τῷ
error ἀτλητῶν
error ἐφάνθη
error ὀρθῆς
error κατηγορεῖτο
error τοὐπίκλημα
error τἀνδρὸς
error ποίησον
error σεμνόμαντιν
error ἔρευναν
error ἃν
error κομίζεται
error ἐκκαλοῦσι
error ἐνταῦθ᾿
error κεῖνα
error φρονῶν
error διπλῇ
error τοῦδε
error τἀμὰ
error μηδὲν
error ὅμως
error κακὰ
error ἀποκρίνας
error ὀναίμην
error τούσδε
error φίλον
error πύματον
error ψυχὰν
error αὐτοῖν
error οὔρισας
error διέσχον
error ὀκνῶ
error οἰκεὺς
error πάρεστιν
error Δωρὶς
error ἠγόμην
error σπουδῆς
error πλαστὸς
error θατέρᾳ
error ἄτιμον
error χρείη
error ἑ.
 ἐπεὶ
error πωλικῆς
error τροχηλάτην
error ὄχου
error κέντροισι
error ἀνδρὸς
error ὧνπερ
error ἄναγνος
error ἐμβατεύειν
error ταὔτʼ
error αὐτὸν
error οἰόζωνον
error ἐκβαλεῖν
error μοῖρα
error αἰθέρα
error γηράσκει
error ἀφόβητος
error ἔρξεται
error ματᾴζων
 ἀσέπτων καὶ
error χορεύειν
error ἄθικτον
error Ὀλυμπίαν
 τιμώμενον
error ἄγχιστος
error ἄγγελος
error διπλῆν
error Ἰσθμίας
error ἐστὲ
error σκόπει
error σημήνας
error ξυναλλαγῇ
error εὐνάζει
error ὑφηγητῶν
error λέχος
error πρόνοια
error ὀκνεῖν
error τοῦτʼ
error δόμους
error γεννητῶν
error ὅθ᾿
error μηδενὶ
error κἆθ᾿
error ἐμπολήσας
error πλάνης
error σημήναθ᾿
 ἤδη
error τρίτης
error χαίρειν
error Οἰδίπους
error ἀναρρήξῃ
error τῆς
error ἴδρις
error αὔξειν
error χορεύεσθαι
error πλάκες
error ἀνάσσων
error ἰδὼν
error μαθὼν
error ποιμνίοις
error ἀρκτοῦρον
error ἱστορεῖς
error τοῦ;
error μαθεῖν;
error τόδʼ
error τριβὰς
error ἀναλώσαιμι
error τλήμων;
error τεκόντας
error ἐξήκοι
error ἐναριθμῶ
error ἀποκλῖναι
error τοξεύσας
error παρθένον
error ἀκούειν
error ἄλοκες
error περίαλλʼ
error ἀρεῖσθε
error ἐγγενῶς
error ἑ.
error περιπολοῦντ᾿
error ἀρτάνην
error ἐφυμνῶν
error ἤρασσ᾿
error σχολῇ
error ἀπότροπον
error ἄφατον
error δυσούριστον
error ἐπίπολος
error μόνιμος
error ἐπῆρε
error ποδίας
error θανὼν
error τάδʼ
error τέκνων
error κηλῖδα
error κακῶν
error ὕπουλον
error αἷμα
error ὅτι
error ἐμφύλιον
error ἴτʼ
error ἐπαιτεῖς
error γένεθλα
error κύριον
error αἷν
error μετειχέτην
error φίλοιν
error προὐξένησαν
error παραρρίψει
error ἴσων
error ὀνειδιεῖσθε
error τηλικάσδʼ
error καιρὸς
error ἀφοῦ
error ᾔδει
error κράτιστος
error ἂν
error πόλει
error πρὸς
error φίλων
error ἐπεὶ
error ὑπέρτερον
error ἀτωμένη
 καὶ
error νέκυν
error θησαυρὸν
error βορᾶς
error ἔχειν
error νεῖσθαι
error ἐσθλῶν
error τούτοις
error ἔπος
error ἔπος
error ἀρτάναισι
error λωβᾶται
error μόνα
error κράτη
error ἀλγίονα
error τέλει
error πότμον
error λεύκασπιν
error πανσαγίᾳ
error ὀξυτέρῳ
error στεγανὸς
error γένυσιν
error ὑπεροπτίας
error τανταλωθεὶς
error βακχεύων
error στυφελίζων
 ὁ   κεραυνὸς
error τέλη
error μεγαλώνυμος
error συντυχίαις
error ἐρέσσων
error λέσχην
error πέμψας
error σάλῳ
error χθονὸς
error ἥδ᾿
error πλέοντες
error δορὶ
error κατελθὼν
error ἐμοῦ
error οὗτος
error ἐπιστάσεις
error ἀναστροφὴν
error οἷ
error ἀλγυνῇ;
error βραδὺς
error κύκλῳ
error διψίαν
error γενῇδος
error στύφλος
error ἐπημαξευμένη
error ἠφάνιστο
error οὖν
error ἔχειν
error τῳ
error βουλεύει
error μεστῶσαι
error ἀμφικίονας
error ἐρρόθουν
error μὴ
error παρηγμένους
error μισθαρνοῦντες
error οἶσθα
error ῥυθμίζεις
error τοῦτο
error ἀπλομένων
error ἄγει
error φύσιν
error δικτυοκλώστοις
error περιφραδὴς
error ταῦρον
error φθέγμα
error φρόνημα
error δυσαύλων
error αἴθρια
error ξυμπέφρασται
error ξύνεστι
error ἔρδει
error ἀπιστοῦσαν
error ἄγγελος
error ἐξέβην
error τῇ
error θοὔρμαιον
error ἐλεύθερος
error κακῶν
error ἆῤ
error σήραντες
error ἐπιρρόθοις
error εἴχομεν
error ψιλὸν
error κακὰς
error ἐκφέρει
error πρόχου
error στέφει
error ἱέμεσθα
error ἐκπεπληγμένην
error ᾗ
error ἄγραπτα
error ἐγὼ
error προὐκήρυξας
error χρόνο
error ἄλγος
error περισκελῆ
error νῦν
error τάφου
error λόγων
error κατέσχον
error φρονεῖς
error τιμᾷς
error δοῦλος
error τούτους
error φιλάδελφα
 ἡ
error ῥέθος
error εἰδέναι
error ξύμπλουν
error τοὖργον
error ἁγνίσαι
error ὠφελουμένη
error νυμφεῖα
error ἀρώσιμοι
error ἡρμοσμένα
error υἱάσιν
error ἀνειμένας
error σεισθῇ
error ἔρεβος
error βυσσόθεν
error δυσάνεμον
error στόνῳ
error ἀντιπλῆγες
error ἐρείπει
error νιν
error νιν
error ἀμᾷ
error πάμπολις
error προσαύσῃ
error ὀλιγοστὸν
error μόρον
error λυσσαίνων
error ἀπορθοῖς
error φέρεσθαι
error ἔχειν
error πόνους
error ψυχρὸν
error πτύσας
error ἐγγενῆ
error ὑπερβὰς
error στήσειε
error δορὸς
error ἀναρχίας
error δὲ
error καταρρήγνυσι
error ὀρθουμένων
error ἀμυντέʼ
error κοσμουμένοις
error χρημάτων
error πέφυκα
error σκότου
error κυνῶν
error τιμῆς
error ἐρεμνὴ
error αὐτόπρεμνʼ
error ηδὲν
error ὑπτίοις
error στρέψας
error μετάστασιν
error οὖν
error ἀκοσμοῦντας
error 735
error 741.
error σὺ
error ἰὼν
error ἰὼν
error ὕστερον
error ἐπεξέρχῃ
error Ὄλυμπον
error δεννάσεις
error μῖσος
error ὄμματ’
error δόξῃς
error οὐδαμᾷ
error αὐτὰ
error σφε
error κατώρυχι
error μάχαν
error κτήμασι
error ἐννυχεύεις
error αὐλαῖς
error ἔχων
error ξύναιμον
error ἄμαχος
error παγκοίταν
error θάλαμον
error ἀνύτουσαν
error ἔγκληρον
error ὕμνος
error θνητῶν
error ξέναν
error Σιπύλῳ
error δάμασεν
error φθιμένᾳ
error ἔγκληρα
error ἐπικτῶμαι
error ἄκλαυτος
error ποταινίου
error θανοῦσιν
error μερίμνας
error πότμου
error Λαβδακίδαισιν
 ἢ
error κοιμήματʼ αὐτογένητα
error πατρὶ
error οἵων
error οὓς
error ἀραῖος
error δυσπότμων
 με
error ὡς
error ὀργὰ
error λαμπάδος
error ἀδάκρυτον
error ἄνω
error κατασκαφὴς
error ἀείφρουρος
error μακρῷ
error τρέφω
error κάρα
error ᾐρόμην
error νόμου
error ἑ.
error με
error τροφῆς
error δίκην
error ξυμμάχων
error ἁμαρτάνουσι
error ὕπερ
 με
 αὐτὴν
error κοιρανίδαι
error βασιλίδα
error σεβίσασα
error ταμιεύεσκε
error μοιριδία
error νιν
error ὀργαῖς
error δεσμῷ
error δεινὸν
error μένος
error γυναῖκας
error πῦρ
error Βοσπόριαι
error ἵν᾿
error ἀραχθὲν
error ἀκμαῖσιν
error πάθαν
error Ἐρεχθειδᾶν
error ἑ.
error στόμα
error χηλαῖσιν
error φοναῖς
error μυδῶσα
 ἢ
error κἀνέπτυε
error τοῦδʼ
error φθίνοντʼ
error λιτὰς
error ἀπορροιβδεῖ
error βεβρῶτες
error ἀκεῖται
error ἀκίνητος
error τοῦδε
error ὑμῖν
error νόσου
error ἐμπολήσων
error ψυχὴν
error ἀνόσιὁν
error ἑ.
error ἄνω
error ὑστεροφθόροι
error κατηργυρωμένος
error φανεῖ
error γυναικῶν
error καθήγισαν
error πόλιν
error λακεῖν
error συντέμνουσι
error δυσμαχητέον
error δρᾶ
error ἐπόψιον
error πολυώνυμε
error Ἰταλίαν
error παγκοίνοις
error Βακχᾶν
error μητρόπολιν
error πέτρας
error Κωρύκιαι
error Κασταλίας
error κισσήρεις
error ἀκτὰ
error ἀγυιὰς
error τὰν
error κεραυνίᾳ
error μολεῖν
error κλιτὺν
error σε
error καταρρέπει
error ἐμοὶ
error ἀφεῖται
error προδῶσιν
error Εὐρυδίκην
error παιδὸς
error τύχῃ
error προσήγορος
error ἀνασπαστοῦ
error κἀποπλήσσομαι
error παρήσω
error μαλθάσσοιμ᾿
error νηλεὲς
error μὲν
error θεὸν
error θαλλοῖς
error συγκατῄθομεν
error ὀρθόκρανον
error νυμφεῖον
error ἀκτέριστον
error μολὼν
error ἆσσον
error λιθοσπαδῆ
error κλέπτομαι
error ἠθροῦμεν
error σινδόνος
error καθημμένην
error τέλη
error ἐφήκει
error θανατόεντ᾿
error ἄνολβα
error ἰδεῖν
error ὁδοῖς
error λακπάτητον
error φέρων
error παμμήτωρ
error κακάγγελτα
error ἐπεξειργάσω
error ἐναντία
error ὀξύθηκτος
error πέριξ
error βλέφαρα
error ἑ.
error ἐφυμνήσασα
error ἀνέπταν
error ἀνταίαν
error κἀκείνων
error ἑ.
error φοναῖς
error γίνεται
error ἢ τὰ μικρὰ τῶν κακῶν λυσιτελέστερά ἐστι
error βράχιστα
error κράτιστα
error τερμίαν
error μέλλοντα
error ὅτοισι
error αὐτὰν
error δυσκόμιστος
error δὲ
error ἐστὶν
error Πλευρῶνι
error Ὅμηρος
error ποτοῦ
error θώκων
error ξυστᾶσʼ
error τῳ
error αὐτοῦ
error ἐπίσταμαι
error ὡς
error φρενοῦν
error καιρὸν
error τἀνδρὶ
error ἀγεννήτων
error ἐλεύθερον
error διδακτά μοι
error ἐξενωμένου
error ἱδρῦσθαι
error γυναικὶ
error λάτριν
error πονεῖν
error ἐξαφεῖται
error χώρας
error ξυνέρξων
error φλογιζόμενον
error αἰτῶ
error πόθι
error ποθουμένᾳ
error οἷα
error ὄρνιν
error ἀδακρύτων
error τι
error αὔξει
error Κρήσιον
error ἀναμπλάκητον
error ἀντία
error οἴσω
error στέρεσθαι
error ἑ.
error ἐξαίρει
error ὑπεκδραμόντα
error Ἡρακλείων
error μένειν
error ἴσχ᾿
error χαρὰν
error ὄκνου
error τάχ᾿
error ποθοῦν
error μεθεῖτο
error αὐτὸς
error προστάταν
error χαρτὸν
error πατρῴας
error ὁρίζεται
error εἰσὶ
error ἀνήριθμον
error ἐμποληθεὶς
error ἐνιαυτὸν
error ἐδήχθη
error τοὔπος
error ἐπακτὸν
error Εὐρυτείαν
error φρενὶ
error ἐλευθέρου
error αὐτὸν
error τότʼ
error πλακὸς
error ἔργου
error κείνῳ
error τοῦτο
error φρενὶ
error σπέρμα
error κρίνοις;
error ξυνεμπόρων
error ἤνυτον
error ὠδίνουσα
error δακρυρρόει
error διήνεμον
error οἷ
error μάτην
error ἐκείνους
error ἑ.
error ἐξείρηκας
error ἔχει
error ταύτης
error ἕλοι
error θέλξειεν
error παρώσας
error πατρίδα
error ἐντεθέρμανται
error ἀγορᾷ
error ἐξελέγχειν
error βλάστας
error γνώμης
error προσμένωμεν;
error αὐτόκλητος
error ἐμοῦ
error κἀννεώσασθα
error ἔβλαστεν
error ἐ.
error δίκαια
error τήνδε
error ὢν
error ἦ
error σέθεν
error ἱστορούμενος
error ὁρᾷς
error κἀμοῦ
error κὴρ
error λήσεις
error ἐντακείη
error ἑ.
error ἀγνώμονα
error στόλῳ
error ἐκφέρεται
error παρέβαν
error ἔννυχον
error τετραόρου
error φάσμα
error Βακχείας
error ἱέμενοι
error ἀνάμιγδα
error μετώπων
error εὐῶπις
error ἀμμένει
error ἐξόδῳ
error συγκατοικτιουμένη
error ἐμπόλημα
error χλαίνης
error φθίνουσαν
error τῶνδʼ ὑπεκτρέπει πόδα
error λύπημα
error φόνων
error πόρευε
error διερροίζησεν
error πύθῇ
error ἀμφίθρεπτον
error ὕδρας
error ἐγκεκλεισμένον
error τόλμας
error γνῶμα
error σκότῳ
error πράσσῃς
error χρόνῳ
error καὶ
error πανδίκως
error καινὸν
error ἕρκει
error τέχνην
error ἄγγος
error καὶ
error χρυσαλακάτου
error Γραχὶν
error ἀναρσίαν
error σεῦται
error δάμαρ
error ὤλλυτο
error ναὸς
error αὐτῷ
error πονῶν
error παρῆκα
error ἄθικτον
error ἀρτίχριστον
error ἡλίου
error ζυγάστρῳ
error φάτιν
error κάταγμα
error προπετὲς
error ἀναζέουσι
error ὕπο
error βαλόντʼ
error τοῦδε
error χρόνον
error μητέρʼ
error ποθεν
error στυγούμενον
error πατρὸς
error ἐ.
error φυλλάδα
error κατηύχετο
error φοινίας
error μὲν
error ἐδαίνυτο
error ἀμφίκλυστον
error ἀνευφήμησεν
error πέδονδε
error κατακτήσαιτο
error ἆρον
error σπασμοῖσι
error καὶ
error ξυνηγορεῖς
error τρέφειν
error οἷον
error προσέμιξεν
error ἀναδοχήν
error αὐτόπαιδι
error κατουρίζει
error νεφέλα
error δράκων
error ἀέλιον
error ἢ
error τὰ
error δὲ
error ἐπιζέσαντα
error ἀισσόντων
error προσέβαλεν
error ὀλοὰ
error ἀδινῶν
error ἄχναν
error ἄχναν
error δολίαν
error θοὰν
error αἰπεινᾶς
error αἰχμᾷ
error πράκτωρ
error στέγη
error πόμπιμον
error διηίστωσεν
error θάνατον
error φωνεῖς;
error σαφηνῆ
error νύμφα
error κτίσαι
error κοῖλα
error ἐρήμη
error ψαύσειεν
error ὀργάνων
error κἄλλῃ
error ἐπεσκιασμένη
error φρούρουν
error Ἡρακλείοις
error ἄνω
error εὐνήτριαν
error ἐλώπισεν
error παιδὶ
error ᾧ
error φρένας
 τε
error νιν
 αὐτὴν
error περαιτέρω
error δύσκριτʼ
error ἑστιῶτις
error τόπων
error ταρβαλέα
 τι
error ἄσπετον
error ἄναυδος
error μήσομαι; 
error ὠμόφρονος
error φοιτάδα
error βρύκει
error ἀκήλητον
error δύσμορον
error εὐνάσαι
error μου
error ἕρπει
error πόθεν
error ὠλεκόμαν
error τῷδε
error πῦρ
error ὀνήσιμον
error ἔμπλεον
error ὀδυνᾶν
error ἔνδοθεν
error θρῴσκει
error δειλαία
error ἀποτίβατος
error ἐχόλωσεν
error ἐπίδοιμι
error αὔτως
error ὠκυπέτᾳ
error στυγνὸς
error ἀμφίβληστρον
error προσμαχθὲν
error ἀρτηρίας
error ῥοφεῖ
error χλωρὸν
error πέδῃ
error ἄγλωσσος
error φύσιν
error βέβρυχα
error κακοῖς
error σκέψαι
error αἰαῖ
error παῖσον
error βέλος
error δαίνυται
error κἀπροσήγορον
error ἄμικτον
error σκύλακ᾿
error τόποις
error ἐγευσάμην
error ἴστε
error σφαλήσεται
error παρασχὼν
error προθυμῇ
error ποικίλλεις
error ἐκτόπου
error θυμὸς
error ὁμαιμόνων
error ἄκοιτιν
error φήμην
error ἐπακτίᾳ
error ἔδραν
error στάσιν
error ἐμοὶ
error δράσειν;
error ἐπώμοτον
error ἔλθοις
error ἔλαιον
error ἀραῖος
error εἴργασαι
error ἐστὶν
error ἄλλου
error ἐκκαλῇ
error παλαμναῖον
error ἐπισκήπτω
error δάμαρτα
error κήδευσον
error πιστεύσαντ᾿
error μοῖραν
error φθίνοντι
error δικαιοῖς
error ἐκδιδαχθῶ
error τελευτᾷς
 πρὶν
error ἐγκονεῖτʼ
error ἐφορᾷ
error ἐκείνοις
error ὑπέχοντι
 τοῦ
error δὲ
error καινοπαγῆ
error ἐ.
error ἀκτὴ
error ἀκμὴ
error ψύχει
error ἀμφιτρῆτος
error σῶν
error σῖγα
error κάτωθεν
error στίβου
error οἰκοποιὸς
error φυλλὰς
error ὑπόστεγον
error ἔκπωμα
error πυρεῖ᾿
error θησαύρισμα
error κῶλον
error κηρὶ
error νόστον
error νώδυνον
error παρόντα
error προσπεσὼν
error στίβος
error ἐκκλέψῃς
error κλεπτέον
error στείλαντες
error ἅλωσιν
error ἠξίωσαν
error δοῦναι
error ἐσχάτων
error ἐγκρατὴς
error σοφισθῆναι
error ἔλεγχον
error γλῶσσαν
error ἡγουμένην
error προσμῖξαι
error δόλῳ
error ὀκνεῖν
error αἱρεῖ
error θηρατέ᾿
error δωρήματα
error ποίω
error κεκλῇ᾿
error συνῄνεσα
error προσῇ
error Πολιὰς
error στέγειν
error ὑπόπταν
error ὅτῳ
error ὠγύγιον
error ὑπουργεῖν
error ἐσχατιαῖς
error ὄμμ᾿
error ἔνεδρος
error ἀποκαίριον
error προσπεσὼν
error θυραῖον
error ὀγμεύει
error σμυγερῶς
error παιῶνα
error ἀλύει
error παντὶ
error παλάμαι
error πρωτογόνων
error ὕστερος
error μοῦνος
error λασίων
error τηλεφανὴς
 καὶ
error ἀμάχητα
error τῶνδε
error τῇδε
error του
error στίβου
error διάσημα
error ἔντοπος
error γένους
error Ἑλλάδος
error ὄκνῳ
error ἀνταμείψασθ
error γʼ
error φεῦ
error τὸ
error προσέσχε
error εἰδῶ
error αὐδῶμαι
error προσέσχες
error εἶπας;
error κλέος
error πικρὸς
error μὲν
error ἄναξ
error χαράγματι
error ᾗ
error ποντίας
error κατέσχον
error σάλου
error τύχοι
error βεβώσας
error σύμφορα
error νευροσπαδὴς
error ἐκθλίβων
error ἄφαντον
error ταύτῃ
error ἐξεμπολήσει
error ξενώσεται
error σώφροσιν
error ἐκεῖνο
error ἀδηφάγον
error ἀντίποινʼ
error ἀληθεῖς
error θυμῷ
error χεῖρα
error γὰρ
error ἐρῶ
error πέρα
error εὐγενὴς
error ἐλέγχω
error μέτα
error τροφεὺς
error εἰδόμην
error Σίγειον
error πλάτῃ
error κεῖνος
error τλημονέστατον
error κρατύνει
error σχέτλι᾿
error ἐμοῦ
error κἀκεῖνον
error ἤρασσον
error κεῖνος
error ἥκων
error ἐνθάδ᾿
error δηχθεὶς
error ἔχων
error τητώμενος
error ἡγουμένων
error ἀκοσμοῦντες
error διδασκάλων
error ὀρεστέρα
error Διὸς
error Πακτωλὸν
 τοῦ
error ἐπηυδώμαν
error ἔφεδρε
error ὑπέρτατον
error προσᾴδεθ
error γόνος
error ἐπίστω
error ἐξήρυκε
error ἔλεξας
error κἀνταῦθ᾿
error ἔμελλʼ
error οὐδέπω
error περιστέλλουσιν
error παλιντριβῆ
error ταῦτα
error θεῖ᾿
error φυλάξομαι
error σθένει
error χρηστὰ
error μεταστήσειαν
error εἴκῃ
error ὅσοισι
error παρέργῳ
error φορήματος
error ἀκράτωρ
error παλαιὰν
error ἱκμένοις
error σμικρῷ
error θάτερα
error ὁρᾶν
error δυσοίστων
error ἔνθα
error δὲ
error προσκύσαντες
error ἄοικον
error εὐκάρδιος
error τάδε
 ἰδὼν
error Πεπάρηθον
error ἴσων
error ἐξαργούμενα
error φροῦδοι
error κόροι
error μέγα
error διεμπολᾷ
error παῖ
error αἴτιον
error λέγων
error κλύεις
error μὴν
error θατέρου
error βία
error οὗτος
error αἰσχρὰ
error δηλώσειν
error ἐφεῖτο
error παῖ
error στελεῖν
error οὔκουν
error ὁρίζει
error ἀνῇ
error ἄῃ
error ἀντιοστατεῖ
error κοιμῶ
error παρερρύηκεν
error δοῦναι
error λέκτρων
error δέσμιον
error δρομάδ᾿
error παγκρατὴς
error ἐχθίονι
 καὶ ἐχθίονι
error ἔρξας
error νοσφίσας
error ἴσοις
error ἀμφιπλήκτων
error βιοτὰν
error βάσιν
error ἐγχώρων
error ἀντίτυπον
error κηκιομέναν
error φορβάδος
error τουτἦν
error ὑπάρχοι
error ἐξανίησιν
error ἄτα
error σπόρον
error αἴρων
error νεμόμεσθʼ
error πτανῶν
error πτανοῖς
error πώματος
error ἥσθη
error προσενώμα
error ὑπαντήσας
error ἀνύσει
error κείνων
error δούρατι
error μηνῶν
error αὐλὰν
error Μηλιάδων
error πυρὶ
error ἑ.
error βρύκομαι
error ἀπάμησον
error ἰυγὴν
error τοὐπίσαγμα
error πλάνοις
error ᾔτου
error ἀνῇ
error ἐκεῖνοι
error πρόστροπον
error ὅπως
error κεκτημένῳ
error κηκῖον
error Κεφαλλὴν
error τρέφοιτε
error ἀνακαλουμένῳ
error δρᾶν
error θέμις
error ἐκεῖσε
error παραφρονεῖς
error φρονεῖς
error ὑπτιάζεται
error ἀδαὴς
error ἀλγέων
error εὐαὴς
error εὐαίων
error πόδα
error ἄρνυται
error ἀτελῆ
error μάκιστον
error ὅτι
error ὧν
error αὐδῶμαι
error ἔχεις
error οὖρος
error ἀνόμματος
error ἁλώσιμον
error φρενῶν
error οἰκούρημα
error εὐχερεῖ
error γέμων
error ἀπαλλάξῃ
error ἐπίσχωμεν
error ξυμφορὰς
error φίλον
error δέοντος
error τοὐνθένδε
error τοῦ
error σε
error φύσιν
error φυτεύσαντος
error δρᾷς
error δεῖ
error ἐπῶν
error ἔφυν
error κακοῦ
error σὺ
error ξυνουσίαι
error καταρρῶγες
error εἰωθόσιν
error φήνασθαι
error νεκρὸν
error ἄλλως
error γενοῦ
error δίπυλον
error θανοῦμαι
error τίσω
error μετοίσεις
error προσχωρεῖν
error ἐκκλέψας
error εἶ;
error πέπραμαι
error θέλῃ
error σε
error τολμήστατε
error Ἡφαιστότευκτον
error σῶν
error γῆς
error χεῖρες
error συνθηρώμεναι
error πρόβλημα
error ἀφυῆ
error νοεῖς
error προὐβάλου
error νεκρὸν
error κλοπῇ
error κέντρον
error ἐπόψιοι
error βαρὺς
error κακοῖς
error παρείκοι
error λόγου
error κρίσις
error εὐσεβῆ
error χρήζων
error τούτων
error δεῖ;
error πατῶν
error προσφθεγκτὸς
error νεὼς
error στείλωσι
error τούτῳ
error νὼ
error ταχεῖς
error σιτονόμου
error ἐλπίδος;
 πρωτάδες
error ἔχῃ
error δαίμονος
error λωβατὸς
error ἀπώσῃ
error φιλότητ᾿
error γελᾷ
error πάλλων
error ἐκβεβιασμένον
error ἄθλιον
error μεταλλαγᾷ
error ἐρέσσῃ
error ὁρῶν
error μυρίʼ
error ἀνατέλλονθ᾿
error ὀδύναν
error πολλῶν
error οῦδʼ
error θῆραι
error χαροπῶν
error ἀνέδην
error ἐρύκεται
error φοβητὸς
error ἕρπετε
error αἰόλας
error κρατύνων
error κῆρα
error ἀποφεύγειν
error βόσκειν
error ἀδαὴς
error λῷστε
error στυγερὰν
error κράτιστον
error τέτακται
error ἔλθῃς
error μετρίαζε
error τεύξω
error μετόπιν
error ἐπήλυδες
error λύπᾳ
error αὐταῖς
error ἄρθρον
error γένυν
error φονᾷ
error λιβάδʼ
error ὁμοῦ
error σοι
error ἂν
error ἑ.
error παλίντροπος
error ἀναρλεῖμ
error ἔτι
error ἐάσω
error ἀμείψας
error μεταγνῶναι
error ἀτηρὸς
error νῦν
error πέρα
error πέρα
error δολούμεθα
error στρατοῦ
error ψευδοκήρυκας
error ζώντων
error ἄριστα
error εὐλογοῦντα
error σύμβουλον
error εὐνοίᾳ
error ἔσω
error ἀκαλυφῆ
error παῦλαν
error μαλαχθῇς
error ὡς
error θέλων
error πίκτησις
error παιωνίας
error προσήγορος;
error ἰδόντες
error ἐξανασχήσεσθε
error πανώλει
error ἔχω
error πατρὸς
error πιστεύσαντα
error ποδὶ
error ἔμπυον
error ὤν
error κακοῖς
error μανθάνειν
error ἑλεἵν
error λόγοις
error στείχωμεν
error ἐμὴν
error ἔρξεις;
error βουλεύματα
error ἀνδρὶ
error ἐκκριθεὶς
error στρατοῦ
error ἐμὴν
error θεοὺς
error τίθεμαι
error καλέσω
error ἐμοὶ
error ἄρσην
error ἀντίτυπον
error ἐπιβάντες
error φίλων
error δαίμων
error φέροντα
error ἐμοὶ
error θάκοισιν
error βεβήλοις
error πυθώμεθα
error τελεῖν
error ὡς
error βρύων
error αὐτὸν
error πέτρου
error ἧ
error ἐξοικήσιμος
 μὴ
error δεῦρο
error ἐμοῦ
error προσήκεις
error τῶν
error δηλοῦμεν
error τοῦ
error νιν
error τοῦτο;
error δρῶ
error προστρέπω
error θεὸς
error ἐπώνυμοι
error δαίμονος
error αὐτοῦ
error σοι
error δεινῶπες
error εὖιε
error ἀγνώμονες
error ξενόστασιν
error πτερὸν
 φησὶ
error συθεὶς
error συθεὶς
error πλανάτας
error ἀστιβὲς
error ἀμαιμακετᾶν
 ἀλλʼ
 δὲ
error εὐφήμου
error τινʼ
error ἅζονθʹ
error ναίει
error φατιζόμενον
error δεινὸς
error ἄνομον
error φυτάλμιος
error τε
error οὗ
error συντρέχει
error πάμμορʼ
error ἔχεις
error ἀπερύκου
error εἴκοντας
error ἀίεις
error ἂν
error τέτροφεν
error ἐπιβαίνοντες
 δὲ
error κλίνῃς
error ἡσθῶ
error τέδ᾿
error χαλᾷς
error ἔφυ
error ἀπόπτολις
error φύσις
error κατακρυφὰν
error μοιριδία
error προπάθῃ
error παραβαλλομένα
error ἀντιδίδωσιν
error ἄφορμος
error ἐπεὶ
error γεραὸν
error ἀκόντων
error προσορωμένα
error τῶνδε
errorἐ λαύνετε
error μητρὸς
error ἱκόμην
error φυγὴν
error οἷς
error ἐχέγγυον
error ῥύου
error ἱερὸς
error βραχέσι
error φίλος
error ἡμῶν
error Αἰτναίας
error κυνῆ
error δουῖν
error τροφαὶ
error προμηθίᾳ
error πονεῖν;
error νῦν
 ἁσμένως
error σύννομοι
error νηλίπους
error τε
error σκοποῦσι
error ἀλιτηροῦ
error λαβέσθαι
 ἤ
error ἀριθμὸς
error ὤρον
error κράτη
error φλαῦρον
error στήσωσι
error κειμένου
error προσθέσθαι
error χώρας
error κατασκιῶσι
error αἷμα
error βάρος
error ἡμῖν
error φασιν
error κἀπαναίρονται
 τὸ ἐφʼ αὐτοῖς
error τοῦτʼ
error δʼ
error συμμάχου
error ἐγᾦδα
error πρὸς
error προξένει
error Κατέστειψας
 ἀπὸ
error λαβὰς
error ἀμφιστόμους
error νεαρᾶς
error οἰνεοτόκῳ
error βαλὼν
error ἕν
error ἕω
error κηγὰς
error τελευταῖον
error μελίσσης
error μέθυ
 φησὶ
 καὶ
error δράσαντι
error δὲ
error ἐκτείνουσαν
error ἄνευ
error τοῦτο;
error γὰρ
error τί;
error ἴδρις
error ἐπιστροφαὶ
error προστροπὴν
error οὐ
error ὤν
error προσφορὰ
error δηλώσεται
 τοῦ
error ξύμφωνα
error σαφὴς
error τἀκίνητʼ
error ἐφαίνετο
error τοιοῦδʼ
error δορύξενος
error χάριν
error μέτα
error ξυνοίσομαι
error ἀνδρὸς
error πιστώσομαι
error ὄκνος
error τοῖσδ᾿
error ἀνάγκη
 ἐπὶ
error ὀκνεῖ
error κείνοις
error ἀγωγῆς
 οὐδὲ
error ξένε
error ἀργῆτα
error μινύρεται
error ἀνέχουσα
error ἀνήλιον
error ἄχνας
error νάρκισσος
error θεαῖν
error μινύθουσιν
 αἱ
error ὠκυτόκος
 καὶ
error νιν
error δαΐων
 ἀπὸ
error μὲν
error πλάτα
error ἐγὼ
error ὀκνεῖτε
error γένει
error ἱκοῦ
error ἐγὼ
error μιᾶς
error μεστὸς
error δόμοισιν
error γένος
error τοιαῦτα
error πάραυλον
error ἑ.
error ταῦτʼ
error κλύω
error Ζηνὸς
error στόμωσιν
error πείθειν
error τούσδε
error δʼ
error ἴσος
error τῶνδε
error μαρτύρομαι
error ἕλω
error τῶνδε
error τοῦδε
error τήνδε
error ξένοι
error τήνδε
error ξένε;
error ἐμῆς
error ξέν᾿;
error εἴργου
error οὔ
error πόλει
error ὁδοιπορεῖν
error ἑ.
error τούτοιν
error πόλει
error ἑ.
error χρόνῳ
error βραδὺς
 δʼ
error τελεῖ
error ἀνεκτέα
error ποδὸς
error ξένῳ
error ἂν
error πέφυκας
error πόλιν
error αὐτούς
error ξυναίμων
 δὲ
error ἴσχων
error σαυτοῦ
error μηνίουσιν
error ἆκον
error νομίζων
 ἀντὶ τοῦ
error μὲν
error οὕς
error ἐπεύξωνται
error ὤν
 αὐτῷ
error ἐπιστροφαὶ
error χαλκοβόαν
error ἀκταῖς
error τιθηνοῦνται
error ὧν
 δὲ
error ἐγρεμάχαν
error ἕσπερον
error πελῶσ᾿
error προσχώρων
error Θησειδᾶν
error ἀμπυκτήρι᾿
error δεινὰ
error ἀρωγὰς
error ἐμφύντε
error τοῦδε
error λιπαρὲς
error λιπαρὲς
error μέλου
error ἔχω
error ἁγὼν
 δεῖ
 καὶ
error ἔμπολιν
error ἔκυρον
error προστάτης
error εἰκαθεῖν
error ἐξεπᾴδονται
 ἂν
error τίνειν
error δὲ
error σῶν
error τις
error θέλοντος
 ἄχορος
 βῆναι κεῖθεν ὅθενπερ ἥκει ὡς τάχιστα:
error κοῦρος
 τὸ
error ἄκη
error προσφορὰ
error δυσπρόσοιστον
error ἦλθον
error λόγχαις
error ἐπώνυμος
error ἀνδρὶ
error δικαιῶν
error χρῄζει
error χἀτέρᾳ
 μὴ
error νεόθεν
error τἀξίωμ᾿
error οὐρανία
error ἀφῇς
error ἅλιον
error ξυμφορᾶς
error ἀνδρὶ
error ἀποστροφὴ
error τῷ
error συμβαλὼν
error ἀμφίσταται
error γᾷ
error ἀφθεγγὲς
error συντύχοιμι
error χάριν
error μετάσχοιμι
error ἁνὴρ
error γύαλον
error Ποσειδαονίῳ
error ἁγιάζων
error κοινὸς
error ἐπιρράξασα
error τύχην
error νέορτον
error προκειμένων
error ἄλυπα
error κείσεται
error κέκευθε
error ἐξάγιστα
error ἀδῇον
error ἐντρεπώμεθα
error σφὼ
error σοὶ
error θεὸν
error ἐννυχίων
error θεαὶ
error θηρὸς
error εὐνᾶσθαι
error τʼ
error ἀνέχει
error ἡγητῆρος
error ἐξηγούμενος
error ὁδὸν
error μιᾷ
 δὲ τὸ
error στὰς
error λουτρὰ
error ἐπιστολὰς
error νομίζεται
error χθόνιος
error ἀνίεσαν
error πτύξας
error τροφὴν
error λύγδην
error θώυξεν
error οἱ
error ἀρχαίαν
error ἂν
error δικαιοῦν
error ἀστακτὶ
error ἐξαπείδομεν
error βαιὸν
error ἐξέπραξεν
error ἀλύπητον
error ἐξεπέμπετʼ
error τις
error παρείμην
error  φίλων
error παροίσομεν
error ἑ.
error νῷν
error ἀφίλητος
error κυρήσῃς
error ἑ.
error σὸν
error ἔρημος
error οὐδεὶς
error σφῷν
 ἔνια
error ὁμαίμοις
error πρόσφορα
